!set introhook_exists=yes
!set introhook_tableless=yes
!default confparm1=X

<br>Paramétrage pour tous les exercices  <i>&nbsp; Formules de dérivées et primitives </i>.

!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm2 list X,T,XT  prompt La variable est toujours \(x\),La variable est toujours \(t\),La variable est de manière aléatoire \( x \) ou  \(t \) 
</ul>

Paramétrage pour les exercices <em>&nbsp; Formules de dérivées et primitives </em>&nbsp; 1 à 5 seulement. <br>
<small>Les exercices 6 à 8b sont affichés uniquement en mode "rigoureux" </small>


!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm1 list S,R  prompt Affichage simplifié (ex: La dérivée de \(x^3\) est ...),Affichage rigoureux (ex : La dérivée de \( x \mapsto x^3 \) sur  \({\RR}\) est la fonction \(x\mapsto \)...)
</ul>
