!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur le calcul intégral et ses applications.<br />

Les exercices pour lesquels le type de fonction n'est pas indiqué ne concernent que les fonctions polynômes et rationnelles.<br />
Certains exercices sont conçus pour des étudiants ne disposant pas de la technique d'intégration par parties.


!read oef/intromenu.phtml
!tail
