!header
!read Exindex


<img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;"/>


Ce module regroupe pour l'instant $exototal exercices sur la construction géométrique d'une combinaison linéaire de vecteurs.

!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=

!read oef/intromenu.phtml
!tail
