!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur
<ul>
<li> les représentations paramétriques et les équations cartésiennes de droites et de plans de l'espace, </li>
<li> la distance d'un point à une droite ou à un plan,</li>
<li> la distance entre deux plans parallèles,</li>
<li> la distance entre deux droites non sécantes.</li>
</ul>

!read oef/$module_language/intromenu.phtml
!tail
