#if defined TARGET_giocatore
# define TITLE Scegli tu
#endif
#if defined TARGET_computer
# define TITLE Sceglie il computer
#endif
#if defined TARGET_partita
# define TITLE Una partita
#endif
#if defined TARGET_pairs1
# define TITLE LEVEL: Analisi di fasi di gioco
#endif
#if defined TARGET_pairs2
# define TITLE LEVEL: Confronto tra terne
#endif
#if defined TARGET_pairs3
# define TITLE LEVEL: Quattro lanci
#endif
#if defined TARGET_pairs4
# define TITLE LEVEL: Confronto di probabilità
#endif
#if defined TARGET_single1
# define TITLE LEVEL: Probabilità per una terna
#endif
#if defined TARGET_single2
# define TITLE LEVEL: Probabilità sui quattro lanci
#endif
\text{testa=T}
\text{croce=C}
