!header
!read Exindex

!if $lang=it
  Questo modulo raccoglie al momento $exototal esercizi basati sul gioco
  francese <i>Le compte est bon</i> (Il conto è giusto).
  Vengono mostrati sei numeri (quattro nella versione più facile). Si
  tratta di trovare un numero dato a partire da questi sei numeri
  e utilizzando le 4 operazioni.
  Le variazioni permettono di lavorare su una rappresentazione
  con un diagramma delle operazioni.
  !goto end
!endif
!if $lang=en
  This module contains for now $exototal exercices based on the french TV game <i>Le compte est bon</i>.
  six numbers are shown (four for an easier level). The goal is to obtain a target number
  starting from those six numbers and using the four basic arithmetic operations.
  Variants allow to use a tree representation of these calculations.
  !goto end
!endif

Ce module regroupe pour l'instant $exototal exercices basés sur le jeu <i>Le compte est bon</i>.
Six nombres sont montrés (quatre pour un niveau plus facile). Il s'agit
de trouver un nombre donné à partir de ces six nombres en utilisant les 4 opérations.
Des variations permettent de travailler sur une représentation en graphe des opérations.

:end
!read oef/intromenu.phtml
!tail
