!header
!read Exindex

!if $lang notwordof en it ca es

Ce module regroupe pour l'instant $exototal exercices sur l'apprentissage 
du logiciel Geogebra 
et/ou l'utilisation de mots de vocabulaire simple en géométrie.

!goto end
!endif

!if $lang iswordof en

 This module currently contains $exototal exercises on Geogebra
 and/or simple vocabulary words in geometry
 !goto end
!endif

!if $lang iswordof it

 Questo modulo contiene $exototal esercizi per
 l'apprendimento del software GeoGebra
 e/o l'utilizzo del vocabolario elementare in geometria.

 !goto end
!endif

!if $lang iswordof ca

 Aquest mòdul conté $exototal exercicis per
 l'aprenentatge del software GeoGebra
 i/o la utilització del vocabulari elemental de geometria.

 !goto end
!endif

!if $lang iswordof es

 Este módulo contiene $exototal ejercicios para
 el aprendizaje del software GeoGebra
 y/o la utilización del vocabulario elemental de geometría.

 !goto end
!endif

:end

!read oef/$module_language/intromenu.phtml
!tail
