#if defined TARGET_distpl
# define TITRE Distance point-droite I
#endif
#if defined TARGET_distpl2
# define TITRE Distance point-droite II
#endif
#if defined TARGET_par1
# define TITRE Parallèle (éq. cartésienne)
#endif
#if defined TARGET_par2
# define TITRE Parallèle
#endif
#if defined TARGET_perp1
# define TITRE Perpendiculaire I
#endif
#if defined TARGET_pntonline
# define TITRE Point sur droite I
#endif
#if defined TARGET_pntonline2
# define TITRE Point sur une droite II
#endif
#if defined TARGET_lineonpnt
# define TITRE Droite passant par un point I
#endif
#if defined TARGET_lineonpnt2
# define TITRE Droite passant par un point II
#endif
#if defined TARGET_pnt2eq
# define TITRE 2 points
#endif
#if defined TARGET_slope2eq
# define TITRE Point et coefficient directeur
#endif
#if defined TARGET_parm2eq
# define TITRE Rep. paramétrique vers éq. cartésienne
#endif
#if defined TARGET_perp2
# define TITRE Perpendiculaire II
#endif
#if defined TARGET_parparam
# define TITRE Parallèle en rep. paramétrique
#endif


\title{TITRE}
