!!! On pose les questions dans ce fichier. D'habitude, c'est par
!!! des forms (formulaires). Voici un exemple de conception de la forme de réponse.
!!! j'ai mis etape=0 quand le travail est terminé (Status Done)
!!! pour éviter le réaffichage des énoncés
!form reply
!if $[$etape]=1
  $(name_sol[8]): <input type="text" name="valint" size="20" value="$valint">
!endif
!if $[$etape]=2
  !set wims_html_mode=li
  <ul class="wims_nopuce">
  !reset nbsol
  !formradio nbsol from 0 to 3 prompt $(name_sol[1..4])
  </ul>
!endif
!if $[$etape]=3 and $[$repnbsol]=1
  $(name_sol[5]): <input type="text" name="sol1" size="20" value="$sol1">
!endif
!if $[$etape]=3 and $[$repnbsol]=2
  <ul> <li>$(name_sol[6]): <input type="text" name="sol1" size="20" value="$sol1">
  </li><li>$(name_sol[7]): <input type="text" name="sol2" size="20" value="$sol2">
  </li></ul>
!endif
<div class="wimscenter">
<input type="submit" name="user" value="$name_valid">
</div>
!formend
