!if $mode = exo1
  <h3>Résolution d'une équation du premier degré</h3>
  Une équation du type \(ax + b = 0) possède :
  <ul><li>une solution unique lorsque \(a\) est différent de 0 ;
  </li><li>aucune solution lorsque \(a\) est égal à \(0\) et \(b\) est différent de \(0\) ;
  </li><li>une infinité de solutions lorsque \(a\) et \(b\) sont égaux à \(0\).
  </li></ul>
  <p>
  <i><font color=blue>Exemples de résolution </font></i>:
  </p>
  <ol><li>Résoudre l'équation (1) :  \(3 - 2(x + 7) = -2x + 8)
  <br> (1) $m_Leftrightarrow \(3 - 2x - 14 = -2x + 8)
  <br> (1) $m_Leftrightarrow \(0x = 19)
  <br> Cette égalité étant impossible, l'équation n'a aucune solution.
  <br> L'ensemble des solutions est l'ensemble vide : S = $m_emptyset .
  </li><li>
  Résoudre l'équation (2) : \(-3 + 4(x + 5) = 4x + 17)
  <br> (2) $m_Leftrightarrow \(-3 + 4x + 20 = 4x + 17)
  <br> (2) $m_Leftrightarrow \(0x = 0)
  <br> Cette égalité étant vérifiée pour tout réel \(x), l'équation a une infinité de solutions.
  <br> L'ensemble des solutions est : S = $m_RR.
  </li><li>
    Résoudre l'équation (3) : \(x - \frac {x + 5}{3} = \frac {3x + 4}{6})
  <br> (3) $m_Leftrightarrow \(\frac {6x - 2(x + 5)}{6} =  \frac {3x + 4}{6})
  <br> (3) $m_Leftrightarrow \(6x - 2(x + 5) = 3x + 4)
  <br> (3) $m_Leftrightarrow \(6x - 2x - 10 = 3x + 4)
  <br> (3) $m_Leftrightarrow \(x = 14)
  <br> Cette équation a une solution unique. L'ensemble des solutions est S = {14}.
  </li><li>Résoudre l'équation (4) : \(2x + 4 = 3x \sqrt{2} + 9)
  <br> (4) $m_Leftrightarrow \(2x - 3x \sqrt{2} = 5)
  <br> (4) $m_Leftrightarrow \(x(2 - 3 \sqrt{2}) = 5)
  <br> (4) $m_Leftrightarrow \(x = \frac{5}{2 - 3\sqrt{2}})
  <br> (4) $m_Leftrightarrow \(x = \frac{5(2 + 3\sqrt{2})}{(2 - 3\sqrt{2})(2 + 3\sqrt{2})})
  <br> (4) $m_Leftrightarrow \(x = \frac {10+15\sqrt{2}}{4 - 18})
  <br> (4) $m_Leftrightarrow \( x = \frac {10+15\sqrt{2}}{-14})
  <br> (4) $m_Leftrightarrow \( x = -\frac{5}{7}- \frac{15}{14}\sqrt{2})
  <br> Il y a une solution unique. L'ensemble des solutions est S = {\(-\frac{5}{7}- \frac{15}{14}\sqrt{2})}.
  </li><ol>
!endif
!if $mode isin exo2,exo2A,exo2B
  <h3>Résolution d'une équation du second degré :</h3>
  Une équation du type \(x^2 = k) ou plus généralement \((ax+b)^2 = k) possède :
  <ul><li>aucune solution lorsque \(k < 0) ;
  </li><li>une solution unique lorsque \(k) est égal à 0 ;
  </li><li>deux solutions lorsque \(k > 0) : dans ce cas, \(x^2 = k) $m_Leftrightarrow \(x = -sqrt(k)) ou  \(x = sqrt(k)).
  </li></ul>
  Une équation du type \((ax + b)(cx + d) = 0), avec \(a) et \(c) non nuls, possède en général deux solutions  (elle a parfois une solution double).
  <br> La propriété utilisée est : "Un produit de facteurs est nul si et seulement si l'un (au moins) des facteurs est nul".
  <br>
  <br> En dehors des cas précédents, une équation  du type \(a(x) = b(x)) se résout  selon la méthode suivante :
   <br> - on se ramène par transposition  à une équation du type \(  f(x) = 0) ;
   <br> - on factorise \( f(x) ) pour transformer l'équation en une équation produit.
 </p>
  <p>
 <h3>Exemples de résolution</h3>
  <ol><li>> Résoudre l'équation (1) : \(x^2 = -3)
  <br> Cette égalité étant impossible, cette équation n'a aucune solution.
  <br> L'ensemble des solutions est l'ensemble vide : S = $m_emptyset .
  </li><li>
  Résoudre l'équation (2) : \((2x + 1)^2 = 0)
  <br> (2) $m_Leftrightarrow \(2x + 1 = 0)
  <br> (2) $m_Leftrightarrow \(x = -\frac{1}{2})
  <br> Cette équation a une solution unique. L'ensemble des solutions est : S = {\(-\frac{1}{2})} .
  </li><li>
  Résoudre l'équation (3) : \((3x - 2)^2 = 5)
  <br> (3) $m_Leftrightarrow \(3x - 2 = -\sqrt{5}) ou \(3x - 2 = \sqrt{5})
  <br> (3) $m_Leftrightarrow \(3x = 2 - \sqrt{5}) ou \(3x = 2 + \sqrt{5})
  <br> (3) $m_Leftrightarrow \(x = \frac{2}{3} - \frac{\sqrt{5}}{3}) ou \(x = \frac{2}{3} + \frac{\sqrt{5}}{3})
  <br> Cette équation a deux solutions. L'ensemble des solutions est : S = {\(\frac{2}{3} - \frac{\sqrt{5}}{3}) ; \(\frac{2}{3} + \frac{\sqrt{5}}{3})} .
  </li><li>
  Résoudre l'équation (4) : \(7x^2 + 5x = 0)
  <ul><li>(4) $m_Leftrightarrow \(x(7x + 5) = 0)
  </li><li>(4) $m_Leftrightarrow \(x = 0) ou \(7x + 5 = 0)
  </li><li>(4) $m_Leftrightarrow \(x = 0) ou \(x = -\frac{5}{7})
  <</li><li>Cette équation a deux solutions. L'ensemble des solutions est :
  S = {\(0) ; \( -\frac{5}{7})}.
  </li></ul>
 </li><li>
 Résoudre l'équation (5) : \((2x + 7)(5x - 11) = (2x + 7)(x - 4))
  <ul><li>(5) $m_Leftrightarrow \((2x + 7)(5x - 11) - (2x + 7)(x - 4) = 0)
  </li><li>(5) $m_Leftrightarrow \((2x + 7) [(5x - 11) - (x - 4)] = 0)
  </li><li>(5) $m_Leftrightarrow \((2x + 7)(5x - 11 - x + 4) = 0)
  </li><li>(5) $m_Leftrightarrow \((2x + 7)(4x - 7) = 0)
  </li><li>(5) $m_Leftrightarrow \(2x + 7 = 0) ou \(4x - 7 = 0)
  </li><li>(5) $m_Leftrightarrow \(x = -\frac{7}{2}) ou \(x = \frac{7}{4})
  </li><li>Cette équation a deux solutions. L'ensemble des solutions est : S = {\(-\frac{7}{2}) ; \(\frac{7}{4})} .
  </ul></li><li>
  Résoudre l'équation (6) : \((x + 3)^2 = (2x + 7)^2)
  <ul><li>(6) $m_Leftrightarrow \((x + 3)^2 - (2x + 7)^2 = 0)
  </li><li>(6) $m_Leftrightarrow \([(x + 3) + (2x + 7)]  [(x + 3) - (2x + 7)] = 0)
  </li><li>(6) $m_Leftrightarrow \((x + 3 + 2x + 7) (x + 3 - 2x - 7) = 0)
  </li><li>(6) $m_Leftrightarrow \((3x + 10) (-x - 4) = 0)
  </li><li>(6) $m_Leftrightarrow \(3x + 10 = 0) ou \(-x - 4 = 0)
  </li><li>(6) $m_Leftrightarrow \(x = -\frac{10}{3}) ou \(x = -4)
  </li><li>Cette équation a deux solutions. L'ensemble des solutions est : S = {\(-\frac{10}{3}) ; \(-4)} .
  </li></ul>/li></ol>
!endif
!if $mode = exo3
  <h3>Résolution d'une équation avec quotient</h3>
  <p>
  Une équation du type \(\frac{A(x)}{B(x)} = 0) est définie si \(B(x)) est différent de 0.
  </li><li>Sur l'ensemble de définition de l'équation : \(\frac{A(x)}{B(x)} = 0) $m_Leftrightarrow \(A(x) = 0)
  </li><li>Plus généralement, une équation du type \(\frac{A(x)}{B(x)}  = \frac{C(x)}{D(x)}) est définie si \(B(x)) et \(D(x)) sont différents de 0.
  </li><li>Sur l'ensemble de définition de l'équation : \(\frac{A(x)}{B(x)}  = \frac{C(x)}{D(x)}) $m_Leftrightarrow \(A(x)D(x) = B(x)C(x))
  </p><p>
  <h3>Exemples de résolution</h3>
  </li><li>1) Résoudre l'équation (1) : \(\frac{2x + 3}{4x - 5} = 0)
  </li><li>La valeur interdite de l'équation est le réel \(x) qui annule le dénominateur  \(4x - 5).
  </li><li>\(4x - 5 = 0) $m_Leftrightarrow \(x = \frac{5}{4}). Donc la valeur interdite est \( \frac{5}{4}).
  </li><li>L'équation est définie sur l'ensemble D = $m_RR-{\(\frac{5}{4})}.
  </li><li>Pour tout \(x) appartenant à D :
  </li><li>(1) $m_Leftrightarrow \(2x + 3 = 0)
  </li><li>(1) $m_Leftrightarrow \(x = -\frac{3}{2})
  </li><li>Cette équation a une solution unique. L'ensemble des solutions est : S = {\(-\frac{3}{2})} .
  <br>
  <br> 2) Résoudre l'équation (2) : \(\frac{5}{2x + 1} = \frac{4}{3})
  <br> La valeur interdite de l'équation est le réel \(x) qui annule le dénominateur  \(2x + 1).
  <br> \(2x + 1 = 0) $m_Leftrightarrow \(x = -\frac{1}{2}). Donc la valeur interdite est \(-\frac{1}{2}).
  <br> L'équation est définie sur l'ensemble D = $m_RR-{\(-\frac{1}{2})}.
  <br> Pour tout \(x) appartenant à D :
  <br> (2) $m_Leftrightarrow \(15 = 4(2x + 1))
  <br> (2) $m_Leftrightarrow \(15 = 8x + 4)
  <br> (2) $m_Leftrightarrow \(x = \frac{11}{8})
  <br> Cette équation a une solution unique. L'ensemble des solutions est : S = {\(\frac{11}{8})} .
  <br>
  <br> 3) Résoudre l'équation (3) : \(\frac{5x^2 + 3x }{10x + 6} = 0)
  <br> La valeur interdite de l'équation est le réel \(x) qui annule le dénominateur  \(10x + 6).
  <br> \(10x + 6 = 0) $m_Leftrightarrow \(x = -\frac{3}{5}). Donc la valeur interdite est \(-\frac{3}{5}).
  <br> L'équation est définie sur l'ensemble D = $m_RR-{\(-\frac{3}{5})}.
  <br> Pour tout \(x) appartenant à D :
  <br> (3) $m_Leftrightarrow \(5x^2 + 3x = 0)
  <br> (3) $m_Leftrightarrow \(x(5x + 3) = 0)
  <br> (3) $m_Leftrightarrow \(x = 0) ou \(5x + 3 = 0)
  <br> (3) $m_Leftrightarrow \(x = 0) ou \(x = -\frac{3}{5})
  <br> Le réel \(-\frac{3}{5}) n'appartenant pas à D, cette équation a une solution unique. L'ensemble des solutions est : S = {\(0)}.
!endif
