!header

Ce module regroupe des exercices de résolution d'équations au niveau Seconde.
Il y a 3 types d'équations proposés&nbsp;:
<ul>
<li>Équations du premier degré</li>
<li>Équations du second degré</li>
<li>Équations quotient</li>
</ul>
<p>
Les exercices sont à étapes : on demande d'abord le nombre de solutions, puis
les valeurs de ces solutions.
</p>
Si aucun choix n'est fait, le type d'exercice est choisi au hasard.
<hr>
!set liste=exo1,exo2,exo3,exo2A,exo2B

!form new
<div class="wimscenter">
!default mode=
!set wims_formselect_switch=multiple
  !formselect mode list $liste prompt \
Équations du premier degré,\
Équations du second degré,\
Équations quotient,\
Équations du second degré avec un membre au carré,\
Équations du second degré avec un facteur commun,\
!set wims_formselect_switch=
</div>
<input type="hidden" name="module" value="$module">
<div class="wimscenter">
<input type="submit" value="Sélectionnez l'exercice puis cliquez ici">
</div>
!formend

!tail
