!header
!readproc lang/names.fr
!!! La présentation de l'exercice.
!read present.phtml
<hr style="width:50%">
!if $error!=$empty
  !read msg.phtml
  <hr style="width:50%">
!endif
!if $status=done
  !!! L'analyse de réponse finale
  !read answer.phtml
!endif
!read form.phtml
<hr style="width:50%">
<p>
!set wims_ref_class=wims_button
!href exo_Renew
!if $worksheet=$empty
  !set wims_ref_class=wims_button
  !href exo_Intro
!endif
</p>
!tail
