!!! This file contains error messages. It will be processed
!!! whenever the variable `error' is not empty.

<div>
  Votre réponse à la question précédente.
!if $[$etape]=2
  $name_valint: \($valint\)
!endif
!if $[$etape]=3
  !if $[$nbsol] isin 0,1,2,3
    $(name_nbsol1[1]): $(name_nbsol1[$nbsol+2])
  !endif
!endif
!if $[$etape]=0
  !if ($[$repnbsol]=0 or $[$repnbsol]=3) and $[$nbsol] isin 0,1,2,3
    $(name_nbsol1[1]): $(name_nbsol1[$nbsol+2])
  !endif
  !if  $[$repnbsol]=1
    \name_solution: \($sol1\)
  !endif
  !if  $[$repnbsol]=2
    $name_solution 1: \($sol1\); $name_solution 2: \($sol2\)
  !endif
!endif
<br>
!if bien iswordof $error
  <span class="oef_indgood">Bonne réponse.</span>
  !exit
!else
  <span class="oef_indbad">
  <b>$wims_name_Error:</b>
  </span>
  !if novalint iswordof $error
    <span class="oef_indbad">$(name_erreur[1;]).</span>
    !exit
  !endif
  !if ervalint iswordof $error
    <span class="oef_indbad">$(name_erreur[2;]) \($repvalint).</span>
    !exit
  !endif
  !if nonbsol iswordof $error
    <span class="oef_indbad">$(name_erreur[3;])</span>
    !exit
  !endif
  !if ernbsol iswordof $error
    <span class="oef_indbad">$(name_erreur[4;]):</span>
    !if $[$repnbsol]=0
      <span class="oef_indbad">$(name_erreur2[$[$repnbsol+1];])</span>
    !endif
    !exit
  !endif
  !if nosol1 iswordof $error and $[$repnbsol]=1
    <div class="oef_indbad">$(name_msg[1;])</div>
  !endif
  !if nosol1 iswordof $error and $[$repnbsol]=2
    <div class="oef_indbad">$(name_msg[2;])</div>
  !endif
  !if nosol2 iswordof $error and $[$repnbsol]=2
    <div class="oef_indbad">$(name_msg[3;])</div>
  !endif
  !if ersol1 iswordof $error and $[$repnbsol]=1
    <div class="oef_indbad">$(name_msg[4;])</div>
  !endif
  !if ersol1 iswordof $error and $[$repnbsol]=2
    <div class="oef_indbad">$(name_msg[5;])</div>
  !endif
  !if ersol2 iswordof $error and $[$repnbsol]=2
    <div class="oef_indbad">$(name_msg[6;])</div>
  !endif
  !if soleg iswordof $error
    <div class="oef_indbad">$(name_msg[7;])</div>
  !endif
!!! FIN DE BONNE REPONSE
!endif
</div>

!!!            !exit
!!!!!         !msg $error
