!header
!read Exindex
!if $lang=en
  This module currently contains $exototal exercises of interactive
  deduction on inequalities: simple formulas (sum, square, product) on one or
  several variables.
  !goto tail
!endif
Ce module contient en ce moment $exototal exercices de déduction interactive
sur les inégalités&nbsp;: formules simples (sommes, produits, carrés) sur
une ou plusieurs variables.

:tail
!read related.phtml Deductio, Inégalités

!read deduc/intromenu.phtml
!tail
