\text{colorlist=red,green,blue,gray,orange,cyan,violet,black}
\text{colorname=\colorlist}

\if{\lang=it}{
  \text{colornamef=rossa,verde,blu,grigia,arancione,azzurra,violetta,nera}
  \text{colornamem=rosso,verde,blu,grigio,arancione,azzurro,violetto,nero}
}
\if{\lang=es}{
  \text{colornamem=rojo,verde,azul,gris,naranja,cián,violeta,negro}
  \text{colornamef=roja,verde,azul,gris,naranja,cián,violeta,negra}
}
\if{\lang=fr}{
  \text{colornamem=rouge,vert,bleu,gris,orange,cyan, violet,noir}
  \text{colornamef=rouge,verte,bleue,grise,orange,cyan,violette, noire}
}
\if{\lang=es}{
  \text{colorname=rode,groene,blauwe,grijze,oranje,cyan,paarse,blauwe}
  \text{colornamef=colorname}
}
\if{\lang=nl}{
  \text{colorname=rode,groene,blauwe,grijze,oranje,cyan,paarse,blauwe}
}
