#if defined TARGET_tie || defined TARGET_IXI
#define TITLE_nl Vlinder
#endif
#if defined TARGET_twosqr
#define TITLE_nl Twee vierkanten
#endif
#if defined TARGET_threesqr
#define TITLE_nl Drie vierkanten
#endif
#if defined TARGET_foursqr
#define TITLE_nl Vier vierkanten
#endif
#if defined TARGET_cube
#define TITLE_nl Cubus
#endif
#if defined TARGET_house
#define TITLE_nl Huis
#endif
#if defined TARGET_diag
#define TITLE_nl Vierkant met diagonalen
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE_nl Pizza
#endif

#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE_nl Pyramide
#endif

#if defined TARGET_pentagram
#define TITLE_nl Pentagram
#endif

#if defined TARGET_triangle
#define TITLE_nl Driehoek
#endif
#if defined TARGET_bigsquare
#define TITLE_nl Vierkant
#endif
#if defined TARGET_cross
#define TITLE_nl Kruis
#endif
#if defined TARGET_V
??
#define TITLE_nl V
#endif
#if defined TARGET_stool
#define TITLE_nl Krukje
#endif
#if defined TARGET_H
#define TITLE_nl H
#endif
#if defined TARGET_M
#define TITLE_nl M
#endif
#if defined TARGET_W
#define TITLE_nl W
#endif
#if defined TARGET_asterisk
#define TITLE_nl Asterisk
#endif
#if defined TARGET_grill
#define TITLE_nl Hek
#endif
#if defined TARGET_pentagon
#define TITLE_nl Pentagon
#endif
