#if defined TARGET_tie || defined TARGET_IXI
#define TITLE_it Fiocco
#endif
#if defined TARGET_twosqr
#define TITLE_it Due quadrati
#endif
#if defined TARGET_threesqr
#define TITLE_it Tre quadrati
#endif
#if defined TARGET_foursqr
#define TITLE_it Quattro quadrati
#endif
#if defined TARGET_cube
#define TITLE_it Cubo
#endif
#if defined TARGET_house
#define TITLE_it Casa
#endif
#if defined TARGET_diag
#define TITLE_it Quadrato + diagonali
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE_it Pizza
#endif

#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE_it Piramide
#endif

#if defined TARGET_pentagram
#define TITLE_it Pentagramma
#endif

#if defined TARGET_triangle
#define TITLE_it Triangolo
#endif
#if defined TARGET_bigsquare
#define TITLE_it Quadrato
#endif
#if defined TARGET_cross
#define TITLE_it Incrocio
#endif
#if defined TARGET_V

#define TITLE_it V
#endif
#if defined TARGET_stool
#define TITLE_it Sgabello
#endif
#if defined TARGET_H
#define TITLE_it H
#endif
#if defined TARGET_M
#define TITLE_it M
#endif
#if defined TARGET_W
#define TITLE_it W
#endif
#if defined TARGET_asterisk
#define TITLE_it Asterisco
#endif
#if defined TARGET_grill
#define TITLE_it Griglia
#endif
#if defined TARGET_pentagon
#define TITLE_it Pentagono
#endif
