#if defined TARGET_tie || defined TARGET_IXI
#define TITLE_fr Noeud de papillon
#endif
#if defined TARGET_twosqr
#define TITLE_fr Deux carrés
#endif
#if defined TARGET_threesqr
#define TITLE_fr Trois carrés
#endif
#if defined TARGET_foursqr
#define TITLE_fr Quatre carrés
#endif
#if defined TARGET_cube
#define TITLE_fr Cube
#endif
#if defined TARGET_house
#define TITLE_fr Maison
#endif
#if defined TARGET_diag
#define TITLE_fr Carré + diagonales
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE_fr Pizza
#endif

#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE_fr Pyramide
#endif

#if defined TARGET_pentagram
#define TITLE_fr Pentagramme
#endif

#if defined TARGET_triangle
#define TITLE_fr Triangle
#endif
#if defined TARGET_bigsquare
#define TITLE_fr Carré
#endif
#if defined TARGET_cross
#define TITLE_fr Croix
#endif
#if defined TARGET_V
#define TITLE_fr V
#endif
#if defined TARGET_stool
#define TITLE_fr Tabouret
#endif
#if defined TARGET_H
#define TITLE_fr H
#endif
#if defined TARGET_M
#define TITLE_fr M
#endif
#if defined TARGET_W
#define TITLE_fr W
#define TITLE_it W
#endif
#if defined TARGET_asterisk
#define TITLE_fr Astérisque
#endif
#if defined TARGET_grill
#define TITLE_fr Grille
#endif
#if defined TARGET_pentagon
#define TITLE_fr Pentagone
#endif
