#if defined TARGET_tie || defined TARGET_IXI
#define TITLE Bow tie
#endif
#if defined TARGET_twosqr
#define TITLE Two squares
#endif
#if defined TARGET_threesqr
#define TITLE Three squares
#endif
#if defined TARGET_foursqr
#define TITLE Four squares
#endif
#if defined TARGET_cube
#define TITLE Cube
#endif
#if defined TARGET_house
#define TITLE House
#endif
#if defined TARGET_diag
#define TITLE Square + diagonals
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE Pizza
#endif

#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE Pyramid
#endif

#if defined TARGET_pentagram
#define TITLE Pentagram
#endif

#if defined TARGET_triangle
#define TITLE Triangle
#endif
#if defined TARGET_bigsquare
#define TITLE Square
#endif
#if defined TARGET_cross
#define TITLE Cross
#endif
#if defined TARGET_V

#define TITLE V
#endif
#if defined TARGET_stool
#define TITLE Stool
#endif
#if defined TARGET_H
#define TITLE H
#endif
#if defined TARGET_M
#define TITLE M
#endif
#if defined TARGET_W
#define TITLE W
#endif
#if defined TARGET_asterisk
#define TITLE Asterisk
#endif
#if defined TARGET_grill
#define TITLE Grill
#endif
#if defined TARGET_pentagon
#define TITLE Pentagon
#endif
