#if defined TARGET_tie || defined TARGET_IXI
#define TITLE_es Pajarita
#endif

#if defined TARGET_twosqr
#define TITLE_es Dos cuadrados
#endif
#if defined TARGET_threesqr
#define TITLE_es Tres cuadrados
#endif
#if defined TARGET_foursqr
#define TITLE_es Cuatro cuadrados
#endif
#if defined TARGET_cube
#define TITLE_es Cubo
#endif
#if defined TARGET_house
#define TITLE_es Casa
#endif
#if defined TARGET_diag
#define TITLE_es Cuadrado + diagonales
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE_es Pizza
#endif

#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE_es Pirámide
#endif

#if defined TARGET_pentagram
#define TITLE_es Pentagrama
#endif

#if defined TARGET_triangle
#define TITLE_es Triángulo
#endif
#if defined TARGET_bigsquare
#define TITLE_es Cuadrado
#endif
#if defined TARGET_cross
#define TITLE_es Cruz
#endif
#if defined TARGET_V

#define TITLE_es V
#endif
#if defined TARGET_stool
#define TITLE_es Taburete
#endif
#if defined TARGET_H
#define TITLE_es H
#endif
#if defined TARGET_M
#define TITLE_es M
#endif
#if defined TARGET_W
#define TITLE_es W
#endif
#if defined TARGET_asterisk
#define TITLE_es Asterisco
#endif
#if defined TARGET_grill
#define TITLE_es Rejilla
#endif
#if defined TARGET_pentagon
#define TITLE_es Pentágono
#endif
