!if $printexo=1
    !read $phtmldir/print.phtml
!else
    !header
    <p>
    <hr> 
    <p>
    !if $status=waiting
	!read $phtmldir/form.phtml
	<p>
        !href exo_Renew
    !else
	!read $phtmldir/answer.phtml
	<p>
	!href exo_Again
	    .
	!if $worksheet=$empty
	    !href exo_Intro
	    .
	!endif
    !endif
    :end
    !tail
!endif
<script type="text/javascript" src="$jsdir/wz_tooltip.js"></script> 
