<script type="text/javascript" src="$jsdir/wz_dragdrop.js"></script> 
<p align="center">
<table>
    <td>
    <table bgcolor=$bgcolor1 cellpadding=$cellpadding cellspacing=$cellspacing>
	<td valign="top" align="left">
	    !if $(question$n) != $empty
		$(question$n)
		<br>
	    !endif
	    !if $(formula$n) != $empty
		!insmath $(formula$n)
		<br>
	    !endif
	    !if $exotext != $empty
		$exotext
	    !endif
	</td>
	!if $image=1
	    !if $XSIZE>450
		<tr>
	    !endif
	    <td valign="top" align="center">
		!if $draw=1
		    !! for fly
		    !set ins_attr=name="image$n" id="image$n"
		    !set insdraw_size=$XSIZE,$YSIZE
		    !insdraw $(image$n)
		!else
		    !if $plot=1
			!! for GNUplot
			!set ins_attr=name="image$n" id="image$n"
			!set insplot_set=$(image_settings$n)
			!insplot $(image$n)
		    !else
			!if $applet=1
			    $(object$n)
			!endif
		    !endif
		!endif
	    </td>
	!endif
	!if $javascript != $empty
	    !if $XSIZE>450
		<tr>
	    !endif
	    <td>
	    !! this file handles the input
		!read $javascript
	    </td>
	!endif
    </table>
    <tr>
    <td>
</table>
</p>
<p align="left">
    !href target=wims_mhelp module=$module&+session=$session&+cmd=help
    $helptext
    </a>
</p>
$dhtml
