!set n=$counter
!! multiplechoice=1 choose from $options possibilities
!! each possibility is called ex1,ex2,ex3...ex10 etc
<p align="center">
    <table>
	<td valign="top">
	    $(question$n)
	    !if $(formula$n) != $empty
		<br>
		!insmath $(formula$n)
	    !endif    
	    !if $image=1
		<br>
		!if $plot=1
		    !set insplot_set=$(image_settings$n)		
		    !insplot $(image$n)
		!endif
		!if $draw=1
		    !set insdraw_size=$XSIZE,$YSIZE
		    !insdraw $(image$n)
		!endif
	    !endif
	    !if $applet=1
		<br>
		$(object$n)
	    !endif
	    !if $exotext != $empty
		<br>
		$exotext
	    !endif
	    <br>
	    !href target=wims_mhelp module=$module&+session=$session&+cmd=help
	    $helptext
	    </p>
	<td>
	!if $image=0 or $XSIZE>400
	    <tr>
	!endif	
	<td valign="top" align="center">
	    <table cellpadding="1" border="0">
		<td  valign="top" align="center">
		    <table cellpadding="5" border="1">
			!set t=0
			!for p=1 to $options
			    !increase t
			    <td  valign="top">	
				<a onclick="window.location.href = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=$p'; return false">
				    !if $multiimage=1
					!if $draw=1
					    !set insdraw_size=$xsize,$ysize
					    !insdraw $(ex$p)
					!else
					    !if $plot=1
						!set insplot_set=$(image_settings$n)
						!insplot $(ex$p) 
					    !endif
					!endif
				    !else
					!if $math=0
					    <font color=blue>$(ex$p)</font>
					!else
					    !insmath $(ex$p)
					!endif
				    !endif
				</a>
			    </td>
			    !if $t=2
			    	<tr>
				!set t=0
			    !endif
			!next p
		    </table>
		</td>
		<tr>
		<td  valign="top" align="center">
		    <p>
			<input type=button style="$mybuttonstyle" onclick="window.location.href = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=%3F'; return false" name="but2" value="$dontknow">
		    </p>
		</td>
	    </table>	
	</td>
    </table>
</p>
			
			
