#if defined TARGET_oefmentpourc1 || defined TARGET_oefmentpourc2 || defined TARGET_oefmentpourc3 || defined TARGET_oefmentpourc4 || defined TARGET_oefmentpourc5
\text{name_instruction=Calculer mentalement.,Combien font,de,Mentalement,de,font}
#endif
#if defined TARGET_oefmentprop1 || defined TARGET_oefmentprop2 || defined TARGET_oefmentprop3 || defined TARGET_oefmentprop4 || defined TARGET_oefmentprop5
\text{name_f=de pommes,de fraises,d'abricots,de prunes,de pêches,de poires,d'oranges,de framboises,de nectarines,de cerises}
\text{name_instruction=On sait que,coûte,Combien coûte,On peut dire que}
#endif
#if defined TARGET_oefprobpourc1 || defined TARGET_oefprobpourc2 || defined TARGET_oefprobpourc3 || defined TARGET_oefprobpourc4 || defined TARGET_oefprobpourc5
\matrix{name_m= sont internes , sont demi-pensionnaires , sont externes
  ont entre 0 &euro; et 5 &euro; d'argent de poche , ont entre 6 &euro; et 10 &euro; d'argent de poche , ont entre 11 &euro; et 20 &euro; d'argent de poche
  aiment la couleur jaune , aiment la couleur rouge , aiment la couleur bleue
  viennent à pied au collège , viennent en vélo au collège , viennent en bus au collège
  viennent au club échec du collège , viennent à la chorale du collège , viennent au club montage vidéo du collège }
\text{name_instruction=Il y a,Nous savons que,élèves dans un collège.,des élèves,
Combien d'élèves, Il y a,élèves qui}
#endif
#if defined TARGET_oefrelpourcfract4 || defined TARGET_oefrelpourcfract5
\text{name_instruction=Associer chaque pourcentage avec la fraction qui lui correspond.}
#endif
#if defined TARGET_oefprobprop1 || defined TARGET_oefprobprop2 || defined TARGET_oefprobprop3
\matrix{name_t=Une cuillère à soupe de farine contient une masse de, de farine, Combien contiennent , cuillères,,g,La masse en g,La farine en g,Les grammes,Le nombre de cuillères,La soupe,La cuillère,10,20,1,3,20,1
  Un carré d'un mètre de côté a un périmètre de,,Quel est le périmètre d'un carré de , de côté,m,m,Le périmètre en m,Le carré en m,Le côté en m,La longueur du côté en m,Le carré en m,Mètre,4,4,1,3,50,1
  Pour un effectif de trois personnes&#44; il faut , de pain, Combien de baguettes dois-je acheter pour le goûter de, personnes,,baguette(s),Le nombre de baguettes,Le pain en g,La baguette en g,Effectif,Le Goûter,Le Pain en g,1,1,1,2,7,3
  Pour un effectif d'une personne&#44; on compte une masse de, de spaghettis, Quelle masse de spaghettis faut-il prévoir pour un effectif de, personnes,,g,La masse en g,Le gramme,Les spaghettis en g,Effectif,Cuisson en min,Spaghettis en g,15,25,10,3,15,1
  Pour une durée d'une heure&#44; il est tombé, de hauteur d'eau de pluie, Quelle hauteur d'eau tombe-t-il pour une durée de,,h,mm,La hauteur en mm,La pluie en mm,L'eau en mm,La durée en h,Heure,La pluie en mm,5,30,1,2,12,1
  Un automobiliste parcourt une distance de, en une heure, Quelle distance parcourt-il en,,h,km,La distance en km,Le voyage en km, km,La durée en h,Le voyage en h,Le nombre d'automobilistes,40,90,1,2,12,1
  Une moto consomme en moyenne un volume de, de carburant pour 100 kilomètres, Quel volume de carburant consomme-t-elle pour parcourir,,km,L,Le volume en l,Le carburant en l,Le parcours en km,La distance en km,La moto en &euro;,Kilomètres,6,14,0.5,2,10,100
  Une masse de 1 kg de tomates coûte,,Quel est le prix d'une masse de, de tomates,kg,&euro;,Le prix en &euro;,Nombre de tomates,L'euro,La masse en kg,La tomate en kg, kg,3,9,0.5,2,10,1
  Un mètre de tissu coûte,,Quel est le prix d'une longueur de, de tissu,m,&euro;,Le prix en &euro;,Le tissu en &euro;,L'euro,La longueur en m,Mètres,Achats en m,5,20,1,2,10,1
  Une masse de 1 kg de fraises coûte,,Quel est le prix d'une masse de, de fraises,kg, &euro;,Le prix en &euro;,Les fraises en &euro;,L'euro,La masse en kg,Les fraises en kg, kg,4,12,0.5,2,10,1
}
#endif
#if defined TARGET_oefprobprop4 || defined TARGET_oefprobprop5
\matrix{name_t=, cuillères à soupe de farine contiennent une masse de, de farine, Combien contiennent ,, cuillères,g,La masse en g,La farine en g,Les grammes,Le nombre de cuillères,La soupe,La cuillère,10,20,1,3,20,1
Un carré de , mètres de côté a un périmètre de,, Quel est le périmètre d'un carré de , de côté,m,m,Le périmètre en m,Le carré en m,Le côté en m,La longueur du côté en m,Le carré en m,Mètre,4,4,1,3,50,1
Pour un effectif de , personnes&#44; il faut , de pain, Combien de baguettes dois-je acheter pour le goûter de, personnes,personnes,baguette(s),Le nombre de baguettes,Le pain en g,La baguette en g,Effectif,Le Goûter,Le Pain en g,1,1,1,2,7,3
Pour un effectif de , personnes&#44; on compte une masse de, de spaghettis, Quelle masse de spaghettis faut-il prévoir pour un effectif de,, personnes,g,La masse en g,Le gramme,Les spaghettis en g,Effectif,Cuisson en min,Spaghettis en g,15,25,10,3,15,1
Pour une durée de , heures&#44; il est tombé, de hauteur d'eau de pluie, Quelle hauteur d'eau tombera-t-il pour une durée de,,h,mm,La hauteur en mm,La pluie en mm,L'eau en mm,La durée en h,Heure,La pluie en mm,5,30,1,2,12,1
Un automobiliste parcourt en , heures une distance de ,, Quelle distance parcourt-il en,,h,km,La distance en km,Le voyage en km, km,La durée en h,Le voyage en h,Le nombre d'automobilistes,40,90,1,2,12,1
Pour , kilomètres&#44; une moto consomme en moyenne un volume de , de carburant, Quel volume de carburant consomme-t-elle pour parcourir,,km,L,Le volume en l,Le carburant en l,Le parcours en km,La distance en km,La moto en &euro;,Kilomètres,6,14,0.5,2,10,100
Une masse de , kg de tomates coûtent ,, Quel est le prix d'une masse de, de tomates ,kg,&euro;,Le prix en &euro;,Nombre de tomates,L'euro,La masse en kg,La tomate en kg, kg,3,9,0.5,2,10,1
, mètres de tissu coûtent ,, Quel est le prix d'une longueur de, de tissu,m,&euro;,Le prix en &euro;,Le tissu en &euro;,L'euro,La longueur en m,Mètres,Achats en m,5,20,1,2,10,1
Une masse de , kg de fraises coûtent ,, Quel est le prix d'une masse de, de fraises,kg, &euro;,Le prix en &euro;,Les fraises en &euro;,L'euro,La masse en kg,Les fraises en kg, kg,4,12,0.5,2,10,1
}
#endif
#if defined TARGET_oefprobprop1 || defined TARGET_oefprobprop2 || defined TARGET_oefprobprop3 || TARGET_oefprobprop4 || defined TARGET_oefprobprop5
\text{name_easy=On trouve facilement}
\text{name_instruction=Nous avons des grandeurs proportionnelles dans le problème suivant&nbsp;}
\text{name_reponse=Réponse}
#endif
#if defined TARGET_oefprobproprapp1 || defined TARGET_oefprobproprapp2
\text{name_instruction=Écrire le coefficient de proportionnalité sous forme de fraction&nbsp;}
#endif
#if defined TARGET_oefprobproprapp3
\text{name_instruction=Compléter l'égalité suivante&nbsp;}
#endif
#if defined TARGET_oefprobproprapp4 || defined TARGET_oefprobproprapp5
\text{name_instruction=Pour trouver la réponse, je fais le calcul suivant&nbsp;}
#endif
#if defined TARGET_oefprobproprapp1 || defined TARGET_oefprobproprapp2 || defined TARGET_oefprobproprapp3 || defined TARGET_oefprobproprapp4 || defined TARGET_oefprobproprapp5
\matrix{name_t=Une photo est au format,x,Cela signifie que si la photo a une longueur de,cm&#44; alors la largeur est de, cm.,10,15,10,13,9,13,11,15,13,17,Longueur en cm,Largeur en cm
  Sur un quadrillage&#44; je reproduis le dessin d'une maison à l'échelle ,/,Cela signifie que si sur le dessin originel un segment mesure , cm&#44; alors je dois sur mon quadrillage un segment de , cm.,3,4,2,3,7,25,8,15,5,12,Mesure en cm, Mesure sur le quadrillage en cm
  À la station essence&#44; je remplis mon réservoir d'essence au ,/,Cela signifie que si le réservoir a une capacité de , L&#44; alors je verse , L d'essence.,3,4,2,3,5,12,5,6,3,7,Volume du réservoir en L,Volume d'essence en L
  Une télévision est au format,x, Cela signifie que si l'écran de la télévision a une longueur de, cm&#44; alors sa largeur est de, cm.,3,4,9,16,9,16,3,4,10,16,Longueur en cm,Largeur en cm
  Un magasin me propose la promotion suivante sur les DVD : , GRATUITS POUR L'ACHAT DE, Cela signifie que pour , DVD achetés&#44; , DVD me sont offerts.,3,5,2,7,3,12,7,25,2,15,Nbre de DVD payés,Nbre de DVD gratuits
}
#endif
#if defined TARGET_oefprobproprapp4 || defined TARGET_oefprobproprapp5
\matrix{name_q= L'agrandissement de ma photo a une longueur de , cm,Calculer sa largeur.
  La longueur de la maison sur le dessin originel mesure ,cm, Calculer la longueur de la maison sur la feuille quadrillée.
  Mon réservoir a une capacité de, L , Calculer la quantité d'essence prise à la station.
  Ma télévision a un écran de ,cm de longueur, Calculer la largeur de l'écran.
  J'achète ,DVD, Calculer le nombre de DVD gratuits.
}
#endif
#if defined TARGET_oefprobproprapp1 || defined TARGET_oefprobproprapp2
\text{name_instruction=Écrire le coefficient de proportionnalité sous forme de fraction&nbsp;}
#endif
#if defined TARGET_oefprobproprapp3
\text{name_instruction=Compléter l'égalité suivante&nbsp;}
#endif
#if defined TARGET_oefprobproprapp4 || defined TARGET_oefprobproprapp5
\text{name_instruction=Pour trouver la réponse, je fais le calcul suivant&nbsp;}
#endif
#if defined TARGET_oefregle31 || defined TARGET_oefregle32 || defined TARGET_oefregle33 || defined TARGET_oefregle34 || defined TARGET_oefregle35
\matrix{name_t=Pour fabriquer , objets &#44; il faut, minutes de travail,2
  Pour un gâteau de , personnes&#44; il faut, grammes de sucre,20
  Pour acheter , jouets identiques&#44; il faut dépenser ,&euro;,1 }
\matrix{name_q=Calculer la durée en min pour fabriquer , objets.
  Calculer la masse en grammes de sucre pour un gâteau de , personnes.
  Calculer la dépense en &euro; pour acheter , jouets identiques.}
# if defined TARGET_oefregle31
\text{name_instruction=Pour trouver la réponse, mettre le raisonnement dans l'ordre.}
# endif
\matrix{name_instruction1=Pour trouver la réponse
  Il faut
  Ensuite
  Conclusion : il faut
  Compléter avec les étiquettes}
# if defined TARGET_oefregle31 || defined TARGET_oefregle32
\text{name_e=Je calcule la durée pour fabriquer 1 objet., min pour fabriquer , objet.,je calcule la durée pour fabriquer , objet(s).
  Je calcule la masse de sucre pour un gâteau de 1 personne.,grammes de sucre pour un gâteau de , personne.,je calcule la masse de sucre pour un gâteau de , personnes.
  Je calcule la dépense pour 1 jouet., &euro; pour acheter , jouet.,je calcule la dépense pour , jouets.}
# else
\text{name_e=Je calcule la durée pour fabriquer , objet(s)., min pour fabriquer , objet.,je calcule la durée pour fabriquer , objets.
  Je calcule la masse de sucre pour un gâteau de , personne(s).,grammes de sucre pour un gâteau de , personne.,je calcule la masse de sucre pour un gâteau de , personnes.
  Je calcule la dépense pour , jouet., &euro; pour acheter , jouet.,je calcule la dépense pour , jouets.}
# endif
#endif
#if defined TARGET_oefrelpourcfract1
\text{name_instruction=Écrire le pourcentage sous forme de fraction.}
#endif
#if defined TARGET_oefrelpourcfract2 || defined TARGET_oefrelpourcfract3
\text{name_instruction=Écrire la fraction sous forme de pourcentage.}
#endif
#if defined TARGET_oefvocprop1 || defined TARGET_oefvocprop2 || defined TARGET_oefvocprop3 || defined TARGET_oefvocprop4 || defined TARGET_oefvocprop5
# if defined TARGET_oefvocprop1
\text{name_instruction=Placer les mots dans l'ordre pour faire une phrase correcte.}
\matrix{enonc=Deux grandeurs, sont proportionnelles, si les valeurs de l'une, s'obtiennent, en multipliant (ou en divisant), par un même nombre non nul, les valeurs de l'autre.
  Deux grandeurs, sont proportionnelles, lorsque les valeurs de l'une, s'obtiennent, en multipliant(ou en divisant), les valeurs de l'autre, par un même nombre non nul.
  Deux grandeurs, sont proportionnelles, si l'on peut calculer, les valeurs de l'une, en multipliant (ou en divisant), les valeurs de l'autre, par un même nombre non nul.}
#endif
# if defined TARGET_oefvocprop2
\matrix{name_t=Une cuillère à soupe de farine contient 15 g de farine et trois cuillères contiennent 45 g.,1
  Un chiot de 4 mois pèse 7 kg. A l'âge de 12 mois&#44; il pèse 12 kg.,2
  Un mètre de tissu coûte 10 &euro;. Si j'en achète une longueur de 5 m&#44; je paye 30 &euro;.,2
  Un carré de 3 m de côté a une aire de 9 mètres carrés et un carré de 6 m de côté a une aire de 36 mètres carrés.,2
  Un carré de 3 m de côté a un périmètre de 12 m et un carré de 6 m de côté a un périmètre de 24 m.,1
  Un congélateur qui a un volume de 150 litres coûte 300 &euro;&#44; un modèle de 300 litres coûte 500 &euro;.,2
  Pour un effectif de 3 personnes&#44; il faut une baguette de pain. Pour un goûter de 12 personnes&#44; j'achète 4 baguettes.,1
  Pour un effectif de 4 personnes&#44; on compte une masse de 250 g de spaghettis. Pour 12 personnes&#44; je prévois 750 g.,1
  Pour une durée d'une heure&#44; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#44; il est tombé 60 mm.,1
  Pour une durée d'une heure&#44; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#44; il est tombé 40 mm.,2
  Une masse de 3 kg de fraises coûte 10 &euro;. Sur l'étiquette&#44; nous pouvons lire aussi 1 kg pour 4 &euro;.,2
  Un automobiliste parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 4 h.,1
  Un automobiliste parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 5 h.,2
  Dans un lotissement&#44; un terrain de 800 mètres carrés d'aire coûte 120 000 &euro; et un autre de 1 200 mètres carrés coûte 160 000 &euro;.,2
  Une moto consomme en moyenne un volume de 4 litres de carburant pour 100 kilomètres. Pour parcourir 50 km&#44; elle a consommé 2 litres.,1
  Une masse de 2 kg de tomates coûte 3 &euro;. Pour 6 kg&#44; je paierai 9 &euro;.,1
  Une voiture qui roule a une vitesse de 10 km/h&#44; a besoin d'une distance de freinage de 2 m. Si elle roule à 50 km/h&#44; elle a besoin de 16 m.,2
}
\text{reps=avons,n'avons pas, je ne sais pas}
\matrix{name_instruction=Dans le texte précédent, nous
des grandeurs proportionnelles.}
# endif
# if defined TARGET_oefvocprop3
\matrix{name_t=Une cuillère à soupe de farine contient 15 g de farine et trois cuillères contiennent 45 g.,1
  Un carré de 3 m de côté a un périmètre de 12 m et un carré de 6 m de côté a un périmètre de 24 m.,1
  Pour un effectif de 3 personnes&#44; il faut une baguette de pain. Pour un goûter de 12 personnes&#44; j'achète 4 baguettes.,1
  Pour un effectif de 4 personnes&#44; on compte une masse de 250 g de spaghettis. Pour 12 personnes&#44; je prévois 750 g.,1
  Pour une durée d'une heure&#44; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#44; il est tombé 60 mm.,1
  Un automobiliste parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 4 h.,1
  Une moto consomme en moyenne un volume de 4 litres de carburant pour 100 kilomètres. Pour parcourir 50 km&#44; elle a consommé 2 litres.,1
  Une masse de 2 kg de tomates coûte 3 &euro;. Pour 6 kg&#44; je paierai 9 &euro;.,1
  Un chiot de 4 mois pèse 7 kg. A l'âge de 12 mois&#44; il pèse 12 kg.,2
  Un mètre de tissu coûte 10 &euro;. Si j'en achète une longueur de 5 m&#44; je paye 30 &euro;.,2
  Un carré de 3 m de côté a une aire de 9 \(m^2\) et un carré de 6 m de côté a une aire de 36 \(m^2\).,2
  Un congélateur qui a un volume de 150 litres coûte 300 &euro;&#44; un modèle de 300 litres coûte 500 &euro;.,2
  Pour une durée d'une heure&#44; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#44; il est tombé 40 mm.,2
  Une masse de 3 kg de fraises coûte 10 &euro;. Sur l'étiquette&#44; nous pouvons lire aussi&#44; 1 kg pour 4 &euro;.,2
  Un automobiliste parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 5 h.,2
  Dans un lotissement&#44; un terrain de 800 \(m^2\) d'aire coûte 120 000 &euro; et un autre de 1 200 \(m^2\) coûte 160 000 &euro;.,2
  Une voiture qui roule a une vitesse de 10 km/h&#44; a besoin d'une distance de freinage de 2 m. Si elle roule à 50 km/h&#44; elle a besoin de 16 m.,2}
\text{name_instruction=Mettre en relation}
\text{rep=Grandeurs proportionnelles,Grandeurs non proportionnelles}
# endif
# if defined TARGET_oefvocprop4
\text{name_p=proportionnel,proportionnelle}
\matrix{name_t=Une cuillère à soupe de farine contient 15 g de farine et trois cuillères contiennent 45 g.,2,La masse,La farine,Le gramme,au nombre de cuillères,à la soupe,à la cuillère,
  Un carré de 3 m de côté a un périmètre de 12 m et un carré de 6 m de côté a un périmètre de 24 m.,1,Le périmètre,Le carré,Le côté,à la longueur,au carré,au mètre
  Pour un effectif de 3 personnes&#44; il faut une baguette de pain. Pour un goûter de 12 personnes&#44; j'achète 4 baguettes.,1,Le nombre de baguettes,Le pain,La baguette,à l'effectif,aux personnes,au pain
  Pour un effectif de 4 personnes&#44; on compte une masse de 250 g de spaghettis. Pour 12 personnes&#44; je prévois 750 g.,2,La masse,Le gramme,Les spaghettis,à l'effectif,aux personnes,aux spaghettis
  Pour une durée d'une heure&#44; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#44; il est tombé 60 mm.,2,La hauteur,La pluie,L'eau,à la durée,à l'heure,à la pluie
  Un automobiliste parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 4 h.,2,La durée,Le voyage,L'automobiliste,à la distance,au voyage,aux km
  Une moto consomme en moyenne un volume de 4 litres de carburant pour 100 kilomètres. Pour parcourir 50 km&#44; elle a consommé 2 litres.,1,Le volume,Le carburant,Le parcours,à la distance,à la moto,aux kilomètres
  Une masse de 2 kg de tomates coûte 3 &euro;. Pour 6 kg&#44; je paierai 9 &euro;.,1,Le prix,La tomate,L'euro,à la masse,à la tomate,aux kg
  Un mètre de tissu coûte 10 &euro;. Si j'en achète une longueur de 5 m&#44; je paye 50 &euro;.,1,Le prix,Le tissu,L'euro,à la longueur,aux mètres,aux achats
  Une masse de 3 kg de fraises coûte 9 &euro;. Sur l'étiquette&#44; nous pouvons lire aussi&#44; 1 kg pour 3 &euro;.,1,Le prix,L'étiquette,La lecture,à la masse,aux fraises,aux kg
  Dans un lotissement&#44; un terrain de 800 \(m^2\) d'aire coûte 100 000 &euro; et un autre de 1 200 \(m^2\) coûte 150 000 &euro;.,1,Le prix,L'euro,Le terrain,à l'aire,au lotissement,au terrain}
\text{name_instruction=Choisir la bonne grandeur}
# endif
# if defined TARGET_oefvocprop5
\matrix{name_t=Une cuillère à soupe de farine contient 15 g de farine et trois cuillères contiennent 45 g.,2,La masse en g,La farine en g,Les grammes,Le nombre de cuillères,La soupe,La cuillère,15,45,1,3
  Un carré de 3 m de côté a un périmètre de 12 m et un carré de 6 m de côté a un périmètre de 24 m.,1,Le périmètre en m,Le carré en m,Le côté en m,La longueur en m,Le carré en m,Mètre,12,24,3,6
  Pour un effectif de 3 personnes&#44; il faut une baguette de pain. Pour un goûter de 12 personnes&#44; j'achète 4 baguettes.,1,Le nombre de baguettes,Le pain en g,La baguette en g,Effectif,Le Goûter,Le Pain en g,1,4,3,12
  Pour un effectif de 4 personnes&#44; on compte une masse de 250 g de spaghettis. Pour 12 personnes&#44; je prévois 750 g.,2,La masse en g,Le gramme,Les spaghettis en g,Effectif,Cuisson en min,Spaghettis en g,250,750,4,12
  Pour une durée d'une heure&#44; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#44; il est tombé 60 mm.,2,La hauteur en mm,La pluie en mm,L'eau en mm,La durée en h,Heure,La pluie en mm,20,60,1,3
  Un automobiliste parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 4 h.,2,La distance en km,Le voyage en km, km,La durée en h,Le voyage en h,Le nombre d'automobilistes,120,240,2,4
  Une moto consomme en moyenne un volume de 4 litres de carburant pour 100 kilomètres. Pour parcourir 50 km&#44; elle a consommé 2 litres.,1,La distance en km,La moto en &euro;,Kilomètres,Le volume en l,Le carburant en l,Le parcours en km,100,50,4,2
  Une masse de 2 kg de tomates coûte 3 &euro;. Pour 6 kg&#44; je paierai 9 &euro;.,1,Le prix en &euro;,Nombre de tomates,L'euro,La masse en kg,La tomate en kg, kg,3,9,2,6
  Un mètre de tissu coûte 10 &euro;. Si j'en achète une longueur de 5 m&#44; je paye 50 &euro;.,1,Le prix en &euro;,Le tissu en &euro;,L'euro,La longueur en m,Mètres,Achats en m,10,50,1,5
  Une masse de 3 kg de fraises coûte 9 &euro;. Sur l'étiquette&#44; nous pouvons lire aussi&#44; 1 kg pour 3 &euro;.,1,Le prix en &euro;,L'étiquette en &euro;,La lecture en &euro;,La masse en kg,Les fraises en kg, kg,9,3,3,1
  Dans un lotissement&#44; un terrain de 800 \(m^2\) d'aire coûte 100 000 &euro; et un autre de 1 200 \(m^2\) coûte 150 000 &euro;.,1,Le prix en &euro;,L'euro,Le terrain en \(m^2\),L' aire en \(m^2\),Le lotissement en \(m^2\),Terrain en &euro;,100 000,150 000,800,1 200}
\text{name_instruction=Compléter le tableau de proportionnalité en choisissant la bonne grandeur
  et les bonnes valeurs.}
# endif
#endif
#if defined TARGET_oefprobproprapp1 || defined TARGET_oefprobproprapp2
\text{name_solution=Le coefficient de proportionnalité sous forme de fraction est&nbsp;}
\text{name_instruction=Écrire le coefficient de proportionnalité sous forme de fraction }
#endif
#if defined TARGET_oefprobproprapp4
\text{name_solution=Le calcul à faire est}
#endif
#if defined TARGET_oefprobproprapp5
\text{name_solution=Le calcul à faire et son résultat pour compléter le tableau sont}
#endif
#if defined TARGET_oefprobproprapp3
\text{name_instruction=Compléter l'égalité suivante }
#endif
#if defined TARGET_oefprobproprapp4 || defined TARGET_oefprobproprapp5
\text{name_instruction=Pour trouver la réponse, je fais le calcul suivant }
#endif
#if defined TARGET_oefvocprop2
\text{name_repred=avons,n'avons pas}
\matrix{name_solution=Dans le texte précédent, nous
des grandeurs proportionnelles.}
#endif
