\text{lang=slib(oef/env lang)}
#include "lang_title_fr.inc"

#if defined TARGET_tableau1 || defined TARGET_calcechelle1 || defined TARGET_coef1 || defined TARGET_comparer1 || defined TARGET_mouvement1 || defined TARGET_pourcentageA1 || defined TARGET_quatrprop1 || defined TARGET_reconnaitre1 || defined TARGET_utilechelle1
# define NUM 1
#endif
#if defined TARGET_tableau2 ||defined TARGET_calcechelle2 || defined TARGET_coef2 || defined TARGET_comparer2 || defined TARGET_mouvement2 || defined TARGET_pourcentageA2 || defined TARGET_quatrprop2 || defined TARGET_reconnaitre2 || defined TARGET_utilechelle2
# define NUM 2
#endif
#if defined TARGET_tableau3 || defined TARGET_calcechelle3 || defined TARGET_coef3 || defined TARGET_comparer3 || defined TARGET_mouvement3 || defined TARGET_pourcentageA3 || defined TARGET_quatrprop3 || defined TARGET_reconnaitre3 || defined TARGET_utilechelle3
# define NUM 3
#endif
#if defined TARGET_tableau4 || defined TARGET_calcechelle4 || defined TARGET_coef4 || defined TARGET_comparer4 || defined TARGET_mouvement4 || defined TARGET_pourcentageA4 || defined TARGET_quatrprop4 || defined TARGET_reconnaitre4 || defined TARGET_utilechelle4
# define NUM 4
#endif
#if defined TARGET_tableau5 || defined TARGET_calcechelle5 || defined TARGET_coef5 || defined TARGET_comparer5 || defined TARGET_mouvement5 || defined TARGET_pourcentageA5 || defined TARGET_quatrprop5 || defined TARGET_reconnaitre5 || defined TARGET_utilechelle5
# define NUM 5
#endif

\title{TITRE NUM}
