#if defined TARGET_calcechelle1 || defined TARGET_calcechelle2 || defined TARGET_calcechelle3 ||defined TARGET_calcechelle4 || defined TARGET_calcechelle5
# define TITRE Calculer un rapport d'échelle
#endif
#if defined TARGET_coef1 || defined TARGET_coef2 || defined TARGET_coef3 || defined TARGET_coef4 || defined TARGET_coef5
# define TITRE Coefficient niveau
#endif
#if defined TARGET_comparer1 || defined TARGET_comparer2 || defined TARGET_comparer3 || defined TARGET_comparer4 || defined TARGET_comparer5
# define TITRE Comparer des proportions
#endif
#if defined TARGET_mouvement1 || defined TARGET_mouvement2 || defined TARGET_mouvement3 || defined TARGET_mouvement4 || defined TARGET_mouvement5
# define TITRE Mouvement uniforme
#endif
#if defined TARGET_pourcentageA1 || defined TARGET_pourcentageA2 || defined TARGET_pourcentageA3 || defined TARGET_pourcentageA4 || defined TARGET_pourcentageA5
# define TITRE Appliquer un pourcentage
#endif
#if defined TARGET_quatrprop1 || defined TARGET_quatrprop2 || defined TARGET_quatrprop3 || defined TARGET_quatrprop4 || defined TARGET_quatrprop5
# define TITRE Quatrième proportionnelle niveau
#endif
#if defined TARGET_reconnaitre1 || defined TARGET_reconnaitre2 || defined TARGET_reconnaitre3 || defined TARGET_reconnaitre4 || defined TARGET_reconnaitre5
# define TITRE Reconnaître
#endif
#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4 || defined TARGET_tableau5
# define TITRE Tableau de nombres
#endif
#if defined TARGET_utilechelle1 || defined TARGET_utilechelle2 || defined TARGET_utilechelle3 || defined TARGET_utilechelle4 || defined TARGET_utilechelle5
# define TITRE Utiliser un rapport d'échelle
#endif
