!header
!read Exindex

!if $lang=it
  Questo modulo al momento contiene $exototal esercizi sulle frazioni.
  !goto tail
!endif
!if $lang=fr
  Ce module regroupe pour l'instant $exototal exercices sur les fractions.
  !goto tail
!endif
!if $lang=nl
  Deze module bevat $exototal oefeningen met breuken.
  !goto tail
!endif

This module actually contains $exototal exercises on fractions.

:tail

!read oef/$module_language/intromenu.phtml
!tail
