#if defined TARGET_Verbesirrgulie || defined TARGET_Verbesirrgulie2 || defined TARGET_Verbesirrgulie3 || defined TARGET_Verbesirrgulie4
# define TITRE Verbes irréguliers
#endif
#if defined TARGET_ecrire1
# define TITRE Dictée I
#endif
#if defined TARGET_ecrire2
# define TITRE Dictée: Infinitive->
#endif
#if defined TARGET_ecrire3
# define TITRE Dictée: d'une forme à l'autre
#endif
#if defined TARGET_ecrire4
# define TITRE Dictée: d'une forme aux autres
#endif

