#if defined TARGET_interpret || defined TARGET_arbre1 || defined TARGET_arbre2 || defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4 || defined TARGET_tableau5 || defined TARGET_tableau6
\text{name_classeA1=Femmine,Esterni,Fumatori,Francesi,di&nbsp;,di&nbsp;,di&nbsp;,di&nbsp;}
\text{name_classeA2=Maschi,Interni,Non fumatori,Stranieri,di&nbsp;,di&nbsp;,di&nbsp;,di&nbsp;}
\text{name_classeB1=Adolescenti,Biondi,Sportivi,Lavoratori,di&nbsp;,di&nbsp;,di&nbsp;,di&nbsp;}
\text{name_classeB2=Bambini,Bruni,Non sportivi,Disoccupati,di&nbsp;,di&nbsp;,di&nbsp;,di&nbsp;}
\text{name_caption=Tabella per numero di persone}
\text{name_reply=Risposta}
\text{name_total=Totale}
#endif
#if defined TARGET_interpret || defined TARGET_arbre1 || defined TARGET_arbre2
\text{name_groupe=Un gruppo,Un liceo,Un gruppo,Un gruppo}
\text{name_individu=individui,allievi,individui,individui}
note for translators: in the following keep commas
\text{name_statement=conta,distribuiti come segue}
#endif
#if defined TARGET_interpret || defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau4 || defined TARGET_tableau3  || defined TARGET_tableau5 || defined TARGET_tableau6
\text{name_approx=approssimativamente}
\text{name_consig=Scrivete le percentuali con tre cifre decimali.}
#endif
#if defined TARGET_interpret
\text{name_consigne=Completa le affermazioni seguenti (per valori arrotondati all'intero)}
\text{name_of=di}
\text{name_cond1=sono}
\text{name_cond2=Tra gli individui}
note for translators: in the following keep commas
\text{name_feedback=Per la domanda,il totale di riferimento,e la prima parte è,quindi la risposta è}
#endif
#if defined TARGET_arbre1 || defined TARGET_arbre2
\text{name_consigne=Completa l'albero con valori in % arrotondati all'intero.}
#endif
#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4 || defined TARGET_tableau5 || defined TARGET_tableau6 || defined TARGET_loibinom1
\text{name_and=e}
#endif

#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3
\text{name_intro1=Studiamo un gruppo di}
\text{name_intro2=persone composto}
\text{name_intro3=Tra i}
\text{name_intro4=contiamo}
\text{name_intro5=,individuo è nel gruppo di}
\text{name_intro6=persone sono,un individuo è nel gruppo di}
#endif
#if defined TARGET_tableau4 || defined TARGET_tableau5 || defined TARGET_tableau6
\text{name_intro1=Studiamo un gruppo di persone composto}
\text{name_intro2=Nel gruppo di}
\text{name_intro3=contiamo}
\text{name_intro4=e tra il}
\text{name_intro5=,nessuno nel gruppo di}
\text{name_of=di}
#endif

#if defined TARGET_tableau1
\text{name_statement=Completa la tabella qui sotto.}
#endif

#if defined TARGET_tableau2 || defined TARGET_tableau4 || defined TARGET_tableau3 || defined TARGET_tableau5 || defined TARGET_tableau6
\text{name_statement=Completa le tabelle qui sotto.}
\text{name_caption1=Tabella marginale in percentuale}
#endif
#if defined TARGET_tableau2 || defined TARGET_tableau4
#endif

#if defined TARGET_tableau6
\text{name_intro6=qual è la percentuale di}
\text{name_intro7=Qual è la percentuale di}
#endif

#if defined TARGET_equiproba1
\text{name_statement1=velocisti partecipano alla finale dei 100 metri}
\text{name_statement2=Quanti sono i podi possibili}
\text{name_statement3=Supponiamo di essere in condizioni di equiprobabilità}
\text{name_statement4=Qual è la probabilità di ciascun podio}
\text{name_answer1=numero di podi}
\text{name_answer2=probabilità}
\text{name_consig=Se inserite un valore approssimato, indicate almeno cinque cifre decimali.}
#endif

#if defined TARGET_equiproba2
\text{name_g=Giovanni,Piero,Alberto,Massimo,Carlo}
\text{name_f=Clara,Alice,Franca,Giovanna,Sofia}
\text{name_and=e}
\text{name_people=persone}
\text{name_statement1=fanno parte di una assemblea di}
\text{name_statement2=Scegliamo a caso nell'assemblea un presidente e un segretario}
note for translators: in the following keep commas
\text{name_statement3=Qual è la probabilità che,sia presidente e,sia segretario}
\text{name_statement4=Scegliamo casualmente nell'assemblea due segretari}
note for translators: in the following keep commas
\text{name_question=Qual è la probabilità che,siano designati}
\text{name_answer=probabilità}
\text{name_solution1=Nel primo caso si hanno}
\text{name_solution2=possibili esiti}
\text{name_solution3=Nel secondo caso, si hanno}
\text{name_solution4=possibili esiti poiché l'ordine di estrazione non influenza}
#endif

#if defined TARGET_equiproba3
\text{name_statement1=Un giardiniere mescola}
\text{name_statement2=bulbi di tulipani rossi con}
\text{name_statement3=bulbi di tulipani gialli}
\text{name_statement4=Realizza quindi un bordo piantando in fila a caso i}
\text{name_statement5=bulbi}
\text{name_statement6=Calcola la probabilità dei seguenti eventi}
\text{name_cond1=I}
\text{name_cond2=tulipani rossi sono tutti gli uni accanto agli altri}
\text{name_cond3=I tulipani rossi e gialli sono alternati lungo il bordo}
\text{name_cond4=tulipani posti nella parte destra del bordo sono rossi}
\text{name_solution1=Se tutti i fiori sono differenti, si avranno}
\text{name_solution2=esiti possibili}
\text{name_solution3=Dal momento che}
\text{name_solution4=tulipani rossi sono identici, è necessario dividere questo numero per}
\text{name_solution5=Allo stesso modo, i}
\text{name_solution6=tulipani gialli sono identici, è necessario quindi dividere ancora per}
\text{name_solution7=Quindi, si hanno}
\text{name_solution8=esiti possibili}
\text{name_solution9=Quanti tulipani gialli si possono avere a sinistra dei tulipani rossi}
\text{name_solution10=Quindi}
\text{name_solution11=La fila comincia con un tulipano rosso, oppure con un tulipano giallo}
\text{name_solution12=Dove possiamo mettere l'ultimo tulipano rosso}
\text{name_solution13=Si hanno}
\text{name_solution14=possibilità}
\text{name_or=o}
#endif

#if defined TARGET_equiproba2 || defined TARGET_equiproba3 || defined TARGET_loibinom1 || defined TARGET_loivar3
\text{name_consig=Indicare i valori esatti delle probabilità, per esempio utilizzando frazioni.}
#endif

#if defined TARGET_loibinom1
\text{name_statement1=Abbiamo comprato un dado non truccato con}
\text{name_statement_list=una faccia bianca,facce bianche,una faccia nera,facce nere}
note for translators: in the following keep commas
\text{name_statement2=Lanciamo il dado,volte di seguito,i lanci sono indipendenti,e indichiamo con,la variabile aleatoria}
\text{name_variable=numero di facce bianche ottenute}
\text{name_question=Fornire la legge di probabilità di}
#endif

#if defined TARGET_loibinom1 || defined TARGET_loivar3
\text{name_solution1=Ad ogni lancio,la probabilità di avere una faccia bianca è}
\text{name_solution2=e quella di avere una faccia nera è}
\text{name_solution4=una probabilità di}
#endif
#if defined TARGET_loibinom1
\text{name_solution3=Per esempio se lanciamo il dado 2 volte, il principio del prodotto dà}
\text{name_solution5=di avere 0 facce bianche}
\text{name_solution6=di avere 2 facce bianche}
\text{name_solution7=di avere 1 faccia bianca}
#endif
#if defined TARGET_loivar3
\text{name_solution3=Il principio del prodotto dà}
\text{name_solution5=di avere 0 facce nere}
\text{name_solution6=di avere 2 facce nere}
\text{name_solution7=di avere 1 faccia nera}
#endif

#if defined TARGET_loivar1
note for translators: in the following keep commas
\text{name_statement1=Dato un universo,e una probabilità,su,definita da}
\text{name_statement2=Definiamo una variabile aleatoria reale \(X\) per la tabella di valori seguente}
\text{name_statement3=Indica la legge di probabilità \(P_X\) di \(X\) completando la tabella seguente}
note for translators: in the following keep commas
\text{name_hint=Nella prima tabella,per ogni}
#endif

#if defined TARGET_loivar2
\text{name_list_rep=un gioco equilibrato,un gioco vantaggioso,un gioco svantaggioso}
note for translators: in the following keep commas
\text{name_statement=Sono dati un universo,munito di una probabilità,e una variabile aleatoria reale,con la legge di probabilità definita dalla tabella seguente}
\text{name_question1=Calcola l'aspettativa matematica di}
\text{name_question2=Calcola la varianza di}
\text{name_question3=La v.a.r.}
\text{name_question4=corrisponde a}
#endif

#if defined TARGET_loivar3
\text{name_variable=numero di facce nere ottenute}
\text{name_comma=}
note for translators: in the following keep commas
\text{name_statement=Abbiamo acquistato un dado non truccato con,facce bianche e,facce nere,Lanciamo il dado,volte di seguito,i lanci sono indipendenti,e indichiamo con,la v.a.r,Fornire la legge di probabilità di}
#endif

#if defined TARGET_proba1 || defined TARGET_proba2 || defined TARGET_proba3
\text{name_and=e}
note for translators: in the following keep commas
\text{name_statement=Data una probabilità,definita su un universo,e due eventi,tali che}
\text{name_question=Calcola}
#endif
#if defined TARGET_proba1
\text{name_incomp=incompatibili}
#endif
