#if defined TARGET_loibinom1
# define TITLE Loi binomiale 1
#endif
#if defined TARGET_arbre1 || defined TARGET_arbre2
# define TITLE Arbre NUM
#endif
#if defined TARGET_interpret
# define TITLE Tableau croisé
#endif
#if defined TARGET_loivar1 || defined TARGET_loivar2 || defined TARGET_loivar3
# define TITLE Loi de probabilité de v.a.r. NUM
#endif
#if defined TARGET_proba1 || defined TARGET_proba2 || defined TARGET_proba3
# define TITLE Calcul de probabilités NUM
#endif
#if defined TARGET_equiproba1 || defined TARGET_equiproba2 || defined TARGET_equiproba3
# define TITLE Equiprobabilité NUM
#endif
#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4 || defined TARGET_tableau5 || defined TARGET_tableau6
# define TITLE Tableau croisé NUM
#endif
