#if defined TARGET_loibinom1
# define TITLE_it Legge binomiale 1
#endif
#if defined TARGET_arbre1 || defined TARGET_arbre2
# define TITLE_it Albero NUM
#endif
#if defined TARGET_interpret
# define TITLE_it Tabella incrociata
#endif
#if defined TARGET_loivar1 || defined TARGET_loivar2 || defined TARGET_loivar3
# define TITLE_it Legge di probabilità di una v.a.r. NUM
#endif
#if defined TARGET_proba1 || defined TARGET_proba2 || defined TARGET_proba3
# define TITLE_it Calcolo di probabilità NUM
#endif
#if defined TARGET_equiproba1 || defined TARGET_equiproba2 || defined TARGET_equiproba3
# define TITLE_it Equiprobabilità NUM
#endif
#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4 || defined TARGET_tableau5 || defined TARGET_tableau6
# define TITLE_it Tabella incrociata NUM
#endif
