 blocks.cpp
#if defined TARGET_tie || defined TARGET_IXI
#define TITLE Vlinder
#endif
#if defined TARGET_twosqr
#define TITLE Twee vierkanten
#endif
#if defined TARGET_threesqr
#define TITLE Drie vierkanten
#endif
#if defined TARGET_foursqr
#define TITLE Vier vierkanten
#endif
#if defined TARGET_cube
#define TITLE Cubus
#endif
#if defined TARGET_house
#define TITLE Huis
#endif
#if defined TARGET_diag
#define TITLE Vierkant met diagonalen
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE Pizza
#endif

pyramid.cpp
#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE Pyramide
#endif

pentagram.cpp
#if defined TARGET_pentagram
#define TITLE Pentagram
#endif

sides.cpp
#if defined TARGET_triangle
#define TITLE Driehoek
#endif
#if defined TARGET_bigsquare
#define TITLE Vierkant
#endif
#if defined TARGET_cross
#define TITLE Kruis
#endif
#if defined TARGET_V
??
#define TITLE V
#endif
#if defined TARGET_stool
#define TITLE Krukje
#endif
#if defined TARGET_H
#define TITLE H
#endif
#if defined TARGET_M
#define TITLE M
#endif
#if defined TARGET_W
#define TITLE W
#endif
#if defined TARGET_asterisk
#define TITLE Asterisk
#endif
#if defined TARGET_grill
#define TITLE Hek
#endif
#if defined TARGET_pentagon
#define TITLE Pentagon
#endif
