 blocks.cpp
#if defined TARGET_tie || defined TARGET_IXI
#define TITLE Pajarita
#endif

#if defined TARGET_twosqr
#define TITLE_es Dos cuadrados
#endif
#if defined TARGET_threesqr
#define TITLE_es Tres cuadrados
#endif
#if defined TARGET_foursqr
#define TITLE_es Cuatro cuadrados
#endif
#if defined TARGET_cube
#define TITLE_es Cubo
#endif
#if defined TARGET_house
#define TITLE_es Casa
#endif
#if defined TARGET_diag
#define TITLE Cuadrado + diagonales
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE Pizza
#endif

pyramid.cpp
#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE Pirámide
#endif

pentagram.cpp
#if defined TARGET_pentagram
#define TITLE Pentagrama
#endif

sides.cpp
#if defined TARGET_triangle
#define TITLE Triángulo
#endif
#if defined TARGET_bigsquare
#define TITLE Cuadrado
#endif
#if defined TARGET_cross
#define TITLE Cruz
#endif
#if defined TARGET_V
??
#define TITLE V
#endif
#if defined TARGET_stool
#define TITLE Taburete
#endif
#if defined TARGET_H
#define TITLE H
#endif
#if defined TARGET_M
#define TITLE M
#endif
#if defined TARGET_W
#define TITLE W
#endif
#if defined TARGET_asterisk
#define TITLE Asterisco
#endif
#if defined TARGET_grill
#define TITLE Rejilla
#endif
#if defined TARGET_pentagon
#define TITLE Pentágono
#endif
