!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

!insdraw $graphe2
<br>Voici une droite de pente $pente tracée ci-dessus.

!if $result5 < $bareme5
  <br>Il vaudrait mieux prendre une pente de $okpente.
!else 
  <br>La valeur de la pente est correcte, vous gagnez $bareme5 point.
!endif

<hr>
<table bgcolor=lightyellow><tr><td>
Vous avez obtenu $module_score (sur 10) points pour l'ensemble des $step questions.
<br>($phrase_result)
</td></tr></table>
