!header

$module_title est une étude sur la relation entre longueur et 
période d'un pendule.
<p><hr> <p>

 !form new
<input type=hidden name=module value=$module>
Nombre de mesures : <select name="nm">
<option value="3">3</option>
<option value="4">4</option>
<option value="5" selected>5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
</select>
<center>
 <input type=submit value="Au travail">
 </center> 
</form>
!tail
