!! Ce fichier présente la question à résoudre.

!if $debug = 1
  <h1>DEBUG MODE</h1>
  $debugstr
!endif
<div style="position: absolute; left: 5px; top: 50px;">
<img src="$module_dir/images/pendule1.gif">
</div>

!!!!!!!!!!!!!!!!!! STEP 1 !!!!!!!!!!!!!!!!!!!!!!!!!
!if $step=1
 <h3>Complétez le tableau</h3>
 Une série d'observations a été faite sur des pendules 
de longueurs différentes.
<ul>
!for i = 1 to $nm
<li>On a observé un pendule de longueur
$(l$i) m. La durée totale de $(nosc$i) oscillations était de 
$(duree$i) s.
!next i
</ul>
!endif $step=1
!!!!!!!!!!!!!!!!!!!!!!!! STEP 2 !!!!!!!!!!!!!!!!!!!!!!!
!if $step=2
 <h3>Tracez le graphique de la période en fonction de la longueur</h3>
!endif $step=2
!!!!!!!!!!!!!!!!!!!!!!!! STEP 3 !!!!!!!!!!!!!!!!!!!!!!!
!if $step=3
 <h3>Calculez les carrés des périodes</h3>
!endif step=3
!!!!!!!!!!!!!!!!!!!!!!!! STEP 4 !!!!!!!!!!!!!!!!!!!!!!!!
!if $step=4
<h3>Tracez le graphique du carré de la période en fonction de la longueur</h3>
!endif $step=4
!!!!!!!!!!!!!!!!!!!!!!!! STEP 5 !!!!!!!!!!!!!!!!!!!!!!!!
!if $step=5
<h3>Faites une régression linéaire</h3>
!read tableau2.phtml
<br>($phrase_result)<br>
!insdraw $graphe
<p>
Il apparaît que les points du graphique sont alignés avec l'origine. On peut donc faire une régression linéaire,
c'est à dire trouver une droite d'équation y=ax qui passe bien près des points.
!endif $step=5
