<span "style=color:grey;"> donner 3 chiffres significatifs</span>
<table border=1>
<tr>
<th>
 longueur (m)
</th>
!for i from 1 to $nm
 <td>$(l$i)</td>
!next i
</tr>
<tr>
<th>
 Période (s)
</th>
!for i from 1 to $nm
<td>$(T$i)</td>
!next i
</tr>
<th>
 Carré de la période
 !instex (s^{2})
</th>
!for i from 1 to $nm
<td>
 !if $step=3
  !if $debug=1
   <input type=text size=7 name=rTc$i value=$(Tc$i) >
  !else
   <input type=text size=7 name=rTc$i >
  !endif
 !else
  !if $(g_rTc$i)=1
   <font color=green>$(rTc$i)</font>
  !else
   <span style="text-decoration: line-through;">
     <font color=red>$(rTc$i)</font>
   </span>
   <br><font color=blue>$(Tc$i)</font>
  !endif
 !endif $step=3
</td>
!next i
</tr>
</table>
