<span "style=color:grey;"> donner 3 chiffres significatifs</span>
<table border=1>
<tr>
<th>
 longueur (m)
</th>
!for i from 1 to $nm
 <td>
 !if $step=1
  !if $debug=1
   <input type=text size=7 name=rl$i value=$(l$i) >
  !else
   <input type=text size=7 name=rl$i >
  !endif
 !else
  !if $(g_rl$i)=1
   <font color=green>$(rl$i)</font>
  !else
   <span style="text-decoration: line-through;">
     <font color=red>$(rl$i)</font>
   </span>
   <br><font color=blue>$(l$i)</font>
  !endif
 !endif $step=1
 </td>
!next i
</tr>
<tr>
<th>
 Période (s)
</th>
!for i from 1 to $nm
<td>
 !if $step=1
  !if $debug=1
   <input type=text size=7 name=rT$i value=$(T$i) >
  !else
   <input type=text size=7 name=rT$i >
  !endif
 !else
  !if $(g_rT$i)=1
   <font color=green>$(rT$i)</font>
  !else
   <span style="text-decoration: line-through;">
     <font color=red>$(rT$i)</font>
   </span>
   <br><font color=blue>$(T$i)</font>
  !endif
 !endif $step=1
</td>
!next i
</tr>
</table>
