!set liste = v(AM).v(AB) = c, v(AM).v(BM) = c,AM^2 + BM^2 = c, AM^2 - BM^2 = c,AM = c BM
!set wims_formselect_switch=multiple
<tr>
<td><i>Produit scalaire et ensemble de points</i> :<br>
sélectionner au dessus  la ligne <br><i>Produit scalaire et
ensemble de points</i>
<br>et une ou plusieurs des lignes ci-contre</td> <td>

 !formselect confparm1 from 1 to 5 prompt $liste
 </td>
</tr>
  !set wims_formselect_switch=
