%%%%%%%%%%%%%% TITLE %%%%%%%%%%%%%
#if defined TARGET_1k_exp
# define TITRE 1. Dérivée du produit d'une fonction exponentielle par une constante
#endif

#if defined TARGET_2aff_exp
# define TITRE 2. Dérivée du produit des fonctions exponentielle et affine
#endif

#if defined TARGET_3secdeg_exp
# define TITRE 3. Dérivée du produit des fonctions exponentielle et du 2nd degré
#endif

#if defined TARGET_4Qexp_k
# define TITRE 4. Dérivée du quotient d'une fonction exponentielle par une constante
#endif

#if defined TARGET_5Qexp_aff
# define TITRE 5. Dérivée du quotient des fonctions exponentielle et affine
#endif

#if defined TARGET_6Qexp_secdeg
# define TITRE 6. Dérivée du quotient des fonctions exponentielle et du 2nd degré
#endif
