%%% HELP %%%%
\text{aide = 
    <ul>
     <li>Pour la fonction exponentielle, on pourra saisir soit <code>exp(k*x)</code> soit <code>e^(k*x)</code>.</li>
     <li>Pour l'écriture des nombres décimaux, on pourra utiliser au choix le point ou la virgule comme séparateur décimal.</li>
     <li>Pour les produits, on peut omettre le symbole <code>*</code> entre deux facteurs.<br>
         Par exemple : \(-2 x \mathrm{e}^{3 x+4}\) est obtenu en saisissant 
         <code>-2*x*e^(3*x+4)</code> ou <code>-2xe^(3x+4)</code>...    
     </li>
    </ul>
}
