#if defined TARGET_prinj
# define TITRE Preuve injectivité réciproque
#endif
#if defined TARGET_prcroiss
# define TITRE Preuve croissance réciproque
#endif
#if defined TARGET_prsurj
# define TITRE Preuve surjectivité réciproque
#endif
#if defined TARGET_bijquad
# define TITRE Bijectivité quadratique
#endif
#if defined TARGET_quadratic
# define TITRE Quadratique
#endif
#if defined TARGET_fraction
# define TITRE Fraction
#endif
#if defined TARGET_Imagerciproque2
# define TITRE Image réciproque de l'image
# endif
#if defined TARGET_Imagerciproque
# define TITRE Image réciproque d'un intervalle
#endif
#if defined TARGET_Imagedelimager
# define TITRE Image de l'image réciproque
#endif
#if defined TARGET_nonderrecip
# define TITRE Réciproque non dérivable
#endif
#if defined TARGET_quadratic
# define TITRE Quadratique
#endif
#if defined TARGET_reciproc
# define TITRE Dérivée réciproque
#endif
#if defined TARGET_invval
# define TITRE Valeur réciproque
#endif
