\integer{confparm1=\confparm1}
\integer{confparm1=NaN isin \confparm1 or \confparm1=?1}
#if defined TARGET_deve1 || defined TARGET_deve2 || defined TARGET_deve3 || defined TARGET_deve4 || defined TARGET_deve5 || defined TARGET_deve6
\integer{confparm2=\confparm2}
\integer{confparm2=\confparm2= or NaN isin \confparm2?2}
#endif
#if defined TARGET_deve7 || defined TARGET_deve8
\integer{confparm2=1}
#endif
