\consigne
#if defined TARGET_ratio2 ||TARGET_ratio3
<ul class="inline"><li>
\embed{reply1,1,<img src="\methoddir/\ListImage[1]" alt="\ListDescr[1]">}
\bch1
</li><li>
\embed{reply1,2,<img src="\methoddir/\ListImage[2]" alt="\ListDescr[2]">}
\bch2
</li><li>
\embed{reply1,3,<img src="\methoddir/\ListImage[3]" alt="\ListDescr[3]">}
\bch3
</li><li>
\embed{reply1,4,<img src="\methoddir/\ListImage[4]" alt="\ListDescr[4]">}
\bch4
</li>
</ul>
#endif

#if defined TARGET_utilratio2 || defined TARGET_utilratio3
<ul class="inline"><li>
\embed{reply1,1,<img src="\methoddir/\ListImage[1]" alt="\ListDescr[2]">}
\bch1
</li><li>
\embed{reply1,2,<img src="\methoddir/\ListImage[2]" alt="\ListDescr[2]">}
\bch2
</li><li>
\embed{reply1,3,<img src="\methoddir/\ListImage[4]" alt="\ListDescr[4]">}
\bch4
</li>
</ul>
#endif
