!let tmp1=$(sys$[$wims_read_parm])
<td><table border="0">
!for i=1 to $nbreequ
   <tr>
      !if $i<$nbreequ
         <td rowspan="$nbreequ"> $(m_leftbrace$[$nbreequ]) </td>
      !endif
      !let tmp4=!line $i of $tmp1
      !distribute items $tmp4 into tmp5,tmp6,tmp7
      !readproc script/texmath.proc $tmp5
!!      !let sortie=!texmath $tmp5
      <td>\($sortie)</td>
      <td>
       \($(symboleaff[$tmp6]))
      </td>
      !readproc script/texmath.proc $tmp7
!!      !let t=!texmath $tmp7
      <td>\($sortie)</td>
   </tr>
!next i
</table></td>
<td>$(comment$[$wims_read_parm])</td>
