!header
!let wims_backslash_insmath=yes

$module_title est un exercice proposant de résoudre pas à pas une équation, une inéquation ou un système de deux équations à deux inconnues.

<hr />

!default nocalcul=1
!default nbreexo=1
!default natcoef=1
!default mode=1
!default difficulte=1
!default listnat=entier

!form new
<ul>
<li> Type d'exercice
!formselect mode from 1 to 3 prompt Equation,Système d'équations,Inéquation
</li>
<li> Nature des coefficients

!let listnat=entier,entierrel,fractions,fractionsrel,decimal1,decimal1rel,decimal2,decimal2rel
!let affnat=Entier positif,Entier relatif,Fraction positive,Fraction relative,Décimal positif 1, Décimal relatif 1,Décimal positif 2,Décimal relatif 2

!formselect natcoef list $listnat prompt $affnat
</li>
<li>Forme de l'énoncé (voir le détail ci-dessous)
!formselect difficulte from 1 to 4
</li>

<li>
!formcheckbox  nocalcul list 1 prompt Ne pas demander d'effectuer les calculs.
</li>
<li> Nombre d'exercices
!formselect nbreexo from 1 to 8
</li>
</ul>

<input type="hidden" name="module" value="$module" />
<div class="wimscenter"><input type="submit" value="Au travail" /></div>
!formend
<div class="wimscenter"><hr width="90%"></div>
Détails sur la forme de l'énoncé :<br />
Les systèmes sont de la forme
!!<table class="wimscenter wimsnoborder"><tr><td rowspan="2">$m_leftbrace2</td><td>a x+b=c</td></tr><tr><td>a'x+b'=c'</td></tr></table> avec des coefficients sp&eacute;cifiques.<br>
\(\begin{cases} a x + b &=c\\ a'x+b'&=c' \end{cases} \)

<table class="wimsborder wimscenter">
 <tr><td>Forme</td><td>Equation/inéquation</td><td>Système</td></tr>
 <tr><td>1</td><td>\(a X+b=c)</td><td>\(b'\) ou \(b\) est nul</td></tr>
 <tr><td>2</td><td>\(a X+b=c X+d)</td><td>\(a'\) ou \(a\) est égal à +/-1</td></tr>
 <tr><td>3</td><td>\(e(a X+b)=c X+d)</td><td>coefficients quelconques</td></tr>
 <tr><td>4</td><td>\(\frac{a X+b}{c}=\frac{a'X+b'}{c'})</td><td>idem 3 pour l'instant !</td></tr>
</table>
!read related.phtml equation_systems, equations, inequations

!tail
