# Variable initialisation file.
# This file is read by wims for new sessions.

# content of the file: initialisation of the problem.

renewlink=cmd=renew&worksheet=$worksheet&$module_init_parm

!default status=0
!default bareme=10-1*(C)-2*(R)
wims_module_log=$cmd
noexo=1
exogood=0
noteinter=0

insmath_rawmath=yes
wims_backslash_insmath=yes
listaction=src/comb.phtml,src/multiplier.phtml,src/transposer.phtml,src/conclure.phtml,src/substituer.phtml,src/dessiner.phtml,src/simplifier.phtml,src/echanger.phtml
meserreur=<div class="wims_warning"> <b>Erreur: </b> Vous avez envoyé une réponse incomplète ou incompréhensible. Veuillez la corriger. </div>
erreur=$empty
evitecalc=0

symbole==,<,>,<=,>=
symboleaff==,<,>,\leq,\geq
