#if defined TARGET_ppower11
# define TITRE Puissance 2, multiplication et addition
#endif
#if defined TARGET_ppower12
# define TITRE Puissance 2, multiplication et soustraction
#endif
#if defined TARGET_ppower13
# define TITRE Puissance 2, multiplication et soustraction ou addition
#endif
#if defined TARGET_ppower01
# define TITRE Puissance 2
#endif
#if defined TARGET_ppower02
# define TITRE Puissance de 2 à 4
#endif
#if defined TARGET_decimal
# define TITRE Nombres décimaux et puissances de 10
#endif
#if defined TARGET_defecritscien
# define TITRE Définition écriture scientifique
#endif
#if defined TARGET_defpuisdix
# define TITRE Définition puissance de 10
#endif
#if defined TARGET_defpuisnb
# define TITRE Définition puissance, exposant entier positif
#endif
#if defined TARGET_defpuisnb2
# define TITRE Définition puissance, exposant entier relatif
#endif
#if defined TARGET_encadr
# define TITRE Encadrement de nombres décimaux
#endif
#if defined TARGET_operation1
# define TITRE Opération 1
#endif
#if defined TARGET_operation2
# define TITRE Opération 2
#endif
#if defined TARGET_ordregrandeur
# define TITRE Ordre de grandeur
#endif
#if defined TARGET_tabpuis
# define TITRE Tableau de puissances
#endif
#if defined TARGET_tabpuis2
# define TITRE Tableau de puissances II
#endif
#if defined TARGET_powerneg
# define TITRE Puissances
#endif
#if defined TARGET_power
# define TITRE Puissance d'un nombre
#endif
#if defined TARGET_power10
# define TITRE Puissances de 10
#endif