#if defined TARGET_ppower11
# define TITRE_es Potencia 2; multiplicacion y suma
#endif
#if defined TARGET_ppower12
# define TITRE_es Potencia 2; multiplicacion y resta
#endif
#if defined TARGET_ppower13
# define TITRE_es Potencia 2; multiplicación y resta o suma
#endif
#if defined TARGET_ppower01
# define TITRE_es Potencia 2
#endif
#if defined TARGET_ppower02
# define TITRE_es Potencia de 2 a 4
#endif
#if defined TARGET_decimal
# define TITRE_es Números decimales y potencias de 10
#endif
#if defined TARGET_defecritscien
# define TITRE_es Definición escritura científica
#endif
#if defined TARGET_defpuisdix
# define TITRE_es Definición potencia de 10
#endif
#if defined TARGET_defpuisnb
# define TITRE_es Def. Potencia; exponente entero positivo
#endif
#if defined TARGET_defpuisnb2
# define TITRE_es Def. Potencia; exponente entero relativo
#endif
#if defined TARGET_encadr
# define TITRE_es Encuadre de números decimales
#endif
#if defined TARGET_operation1
# define TITRE_es Operación 1
#endif
#if defined TARGET_operation2
# define TITRE_es Operación 2
#endif
#if defined TARGET_ordregrandeur
# define TITRE_es Orden de magnitud
#endif
#if defined TARGET_tabpuis
# define TITRE_es Cuadro de potencias
#endif
#if defined TARGET_tabpuis2
# define TITRE_es Cuadro de potencias II
#endif
#if defined TARGET_powerneg
# define TITRE_es Potencias
#endif
#if defined TARGET_power
# define TITRE_es Potencia de un número
#endif
#if defined TARGET_power10
# define TITRE_es Potencias de 10
#endif
