#if defined TARGET_ppower11 || defined TARGET_ppower12 || defined TARGET_ppower13 || defined TARGET_ppower01 || defined TARGET_ppower02
\text{name_statement=Berekenen zonder calculator}
#endif
#if defined TARGET_powerneg
\matrix{name_statement=Het getal,is
  Schrijf als een product van machten}
\text{name_choix=positive, negative}
\matrix{name_feed=Heb je gekeken of,de exponent,de exponenten
  van het niet positieve getal,even of oneven is
  van de niet positieve getallen,even of oneven zijn
  Het teken van de exponent,Het teken van de exponenten, is niet zinvol voor de beantwoording van deze vraag.
  Het product van positieve getallen, de machten van positieve getallen zijn altijd positief.}
#endif
#if defined TARGET_defecritscien
\text{name_statement=Geef de wetenschappelijke schrijfwijze van \(A\) in}
#endif
#if defined TARGET_defpuisdix
\text{name_statement=Schrijf als een decimaal getal }
\text{name_instruction=You will write the answer as an integer or decimal number.}
#endif
#if defined TARGET_defpuisnb
\text{name_statement=Bepaal de waarde van \(A\) in}
#endif
#if defined TARGET_defpuisnb2
\text{name_statement=Bepaal de waarde van \(A) in}
\text{name_instruction=Schrijf je antwoord als een geheel getal<br>of als een niet verder te vereenvoudigen breuk.}
#endif
#if defined TARGET_encadr
\text{name_statement=Geef de grenzen van het getal, uitgedrukt als machten van 10.}
\text{name_answer1=exponent}
\text{name_answer2=exponent}
\text{name_hint=Je kunt eerst \(A\) schrijven met wetenschappelijke notatie.}
#endif
#if defined TARGET_operation1 || defined TARGET_operation2
\text{name_statement=Reken uit en schrijf in de vorm}
\text{name_instruction=Geef het resultaat in de vorm}
#endif
#if defined TARGET_ordregrandeur
\text{name_statement=Bepaal de orde grootte van getal \(A) in:}
\text{name_instruction=Let op: de macht kan ook 0 worden.}
#endif
#if defined TARGET_tabpuis
\text{name_statement=Vul de tabel verder in}
\text{name_feed=Opgelet: altijd geldt}
#endif
#if defined TARGET_tabpuis2
\text{name_statement=Vul de tabel verder in}
\text{name_feed=Opgelet: in't algemeen is \(a^m*a^n\) iets anders dan \(a^{mn}\)}
\text{name_warning=Opgelet.}
#endif
#if defined TARGET_decimal
\matrix{name_statement=Schrijf het getal, twee manieren
  wetenschappelijke notatie
  als,met \(a\) integers en geen veelvoud van  10 }
\text{name_answer=wetenschappelijke notatie,exponent, exponent}
#endif
#if defined TARGET_power
\text{name_statement1=Schrijf}
\text{name_statement2=als een macht van een geheel getal (integer)}
\text{name_hint=vereenvoudig eerst de breuk.}
\text{name_feedback1=Heb je de regel}
\text{name_feedback2=niet door elkaar halen}
\text{name_and=and}
#endif
#if defined TARGET_power10
\text{name_statement=Schrijf het getal als}
\text{name_answer=exponent}
#endif
