#if defined TARGET_ppower11
# define TITRE_nl Power 2; multiplication and addition
#endif
#if defined TARGET_ppower12
# define TITRE_nl Power 2; multiplication and subtraction
#endif
#if defined TARGET_ppower13
# define TITRE_nl Power 2; multiplication and subtraction or addition
#endif
#if defined TARGET_ppower01
# define TITRE_nl Power 2
#endif
#if defined TARGET_ppower02
# define TITRE_nl Power from 2 to 4
#endif
#if defined TARGET_decimal
# define TITRE_nl Decimale getallen en machten van 10
#endif
#if defined TARGET_defecritscien
# define TITRE_nl De wetenschappelijke notatie
#endif
#if defined TARGET_defpuisdix
# define TITRE_nl Van Macht naar Decimaal getal
#endif
#if defined TARGET_defpuisnb
# define TITRE_nl Positieve machten I
#endif
#if defined TARGET_defpuisnb2
# define TITRE_nl Negatieve machten I
#endif
#if defined TARGET_encadr
# define TITRE_nl Grenzen van decimale getallen
#endif
#if defined TARGET_operation1
# define TITRE_nl Bewerkingen 1
#endif
#if defined TARGET_operation2
# define TITRE_nl Bewerkingen 2
#endif
#if defined TARGET_ordregrandeur
# define TITRE_nl Orde grootte
#endif
#if defined TARGET_tabpuis
# define TITRE_nl Tabel van Machten I
#endif
#if defined TARGET_tabpuis2
# define TITRE_nl Tabel van Machten II
#endif
#if defined TARGET_powerneg
# define TITRE_nl Machten
#endif
#if defined TARGET_power
# define TITRE_nl Machten van een getal
#endif
#if defined TARGET_power10
# define TITRE_nl Machten van 10
#endif
