#if defined TARGET_division
# define TITRE Division posée
#endif
#if defined TARGET_oefmultiplication5 || defined TARGET_multipli || defined TARGET_oefmultiplication1 || defined TARGET_oefmultiplication2 || defined TARGET_oefmultiplication3 || defined TARGET_oefmultiplication4
# define TITRE Multiplication
#endif
#if defined TARGET_oefaddition1 || defined TARGET_oefaddition2 || defined TARGET_oefaddition3 || defined TARGET_oefaddition4 || defined TARGET_oefaddition5
# define TITRE Addition
#endif
#if defined TARGET_oefmachop1 || defined TARGET_oefmachop2 || defined TARGET_oefmachop3 || defined TARGET_oefmachop4 || defined TARGET_oefmachop5
# define TITRE Utilisation de la calculatrice
#endif
#if defined TARGET_oefmentaladd1 || defined TARGET_oefmentaladd2 || defined TARGET_oefmentaladd3 || defined TARGET_oefmentaladd4 || defined TARGET_oefmentaladd5
# define TITRE Calcul mental d'additions
#endif
#if defined TARGET_oefmentalsoust1 || defined TARGET_oefmentalsoust2 || defined TARGET_oefmentalsoust3 || defined TARGET_oefmentalsoust4 || defined TARGET_oefmentalsoust5
# define TITRE Calcul mental de soustractions
#endif
#if defined TARGET_oefposer1 || defined TARGET_oefposer2 || defined TARGET_oefposer3 || defined TARGET_oefposer4 || defined TARGET_oefposer5
# define TITRE Poser
#endif
#if defined TARGET_oefsoustract1 || defined TARGET_oefsoustract2 || defined TARGET_oefsoustract3 || defined TARGET_oefsoustract4 ||defined TARGET_oefsoustract5
# define TITRE Soustraction
#endif
#if defined TARGET_oeftable1 || defined TARGET_oeftable2
# define TITRE Table d'addition
#endif
#if defined TARGET_oeftable3 || defined TARGET_oeftable4 || defined TARGET_oeftable5
# define TITRE Table de multiplication
#endif
#if defined TARGET_oefvocaboper1 || defined TARGET_oefvocaboper2 || defined TARGET_oefvocaboper3 || defined TARGET_oefvocaboper4 || defined TARGET_oefvocaboper5
# define TITRE Vocabulaire
#endif
#if defined TARGET_oefmult011 || defined TARGET_oefmult012 || defined TARGET_oefmult013 || defined TARGET_oefmult014 || defined TARGET_oefmult015
# define TITRE Multiplication par 0,1 0,01 0,001
#endif
#if defined TARGET_oefmult101 || defined TARGET_oefmult102 || defined TARGET_oefmult103 || defined TARGET_oefmult104 || defined TARGET_oefmult105
# define TITRE Multiplication par 10, 100, 1000
#endif
#if defined TARGET_table
# define TITRE Table de multiplication
#endif
#if defined TARGET_oefgrandeurprod1 || defined TARGET_oefgrandeurprod2 || defined TARGET_oefgrandeurprod3 || defined TARGET_oefgrandeurprod4 || defined TARGET_oefgrandeurprod5
# define TITRE Ordre de grandeur multiplication
#endif
#if defined TARGET_oefgrandeurdiff1 || defined TARGET_oefgrandeurdiff2 || defined TARGET_oefgrandeurdiff3 || defined TARGET_oefgrandeurdiff4 || defined TARGET_oefgrandeurdiff5
# define TITRE Ordre de grandeur soustraction
#endif
#if defined TARGET_oefgrandeuradd1 || defined TARGET_oefgrandeuradd2 || defined TARGET_oefgrandeuradd3 || defined TARGET_oefgrandeuradd4 || defined TARGET_oefgrandeuradd5
# define TITRE Ordre de grandeur addition
#endif
#if defined TARGET_decomp
# define TITRE Décomposition
#endif
