!let tmp1=$(sys$[$wims_read_parm])

<table>
<tr><td><table>
!for i=1 to $nbreequ
   <tr>
      !if $i<$nbreequ
         <td rowspan=$nbreequ> $(m_leftbrace$[$nbreequ]) </td>      
      !endif
      !let tmp4=!line $i of $tmp1
      !let tmp4=!texmath $tmp4
      !distribute items $tmp4 into tmp5,tmp6,tmp7
          <td>\($tmp5)</td>
          !let tmp3=!item $tmp6 of $symboleaff
          <td>\($tmp3)</td>
          <td>\($tmp7)</td>
   </tr>
!next i
</table></td>
<td>$(comment$[$wims_read_parm])</td>
</tr>
</table>
