!let mempara=$empty
!for i=1 to 50
   !let repexo$i=$empty
!next i
!let repexo=$empty
!let nbreesscalc=0
!let evitecalc=0
<u>Llista d'accions:</u>
<lu>
!if $mode=2
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=1>
<input type=submit value=Sumar/Restar> dues equacions per obtenir una nova equació.
</form></li>
!endif
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=2>
<input type=submit value=Multiplicar/Dividir> una $nom per un nombre.
</form></li>
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=3>
<input type=submit value=Transposar> un terme d'una $nom.
</form></li>
!if $mode=2
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=8>
<input type=submit value=Intercanviar> les dues equacions del sistema.
</form></li>
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=5>
<input type=submit value=Substituir> una incògnita per la seua expressió obtinguda d'una altra equació.
</form></li>
!endif
!if $nocalcul!=1
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=7>
<input type=submit value=Simplificar> l'escriptura d'una $nom.
</form></li>
!endif
!if $mode=4
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=6>
<input type=submit value=Dessiner> les solutions.
</form></li>
!endif
<li>
!form reply
<input type=hidden name=status value=3>
<input type=hidden name=action value=4>
<input type=submit value=Acabar> l'exercici.
</form></li>
</lu>
!!<b>Nota: </b> Una descripció detallada de les diferents accions està disponible a l'ajuda.<p>
