!header

$module_title és un exercici que proposa resoldre pas a pas una equació, una
inequació o un sistema de dues equacions amb dues incògnites.

<p><hr> <p>

!default nocalcul=1
!default nbreexo=1
!default natcoef=1
!default mode=1
!default difficulte=1
!default listnat=entier

!form new
<ul>
<li> Tipus d'exercici 
!formselect mode from 1 to 3 prompt Equació,Sistema d'equacions,Inequació
</li>
<li> Natura dels coeficients

!let listnat=entier,entierrel,fractions,fractionsrel,decimal1,decimal1rel,decimal2,decimal2rel
!let affnat=Naturals,Enters,Fraccions positives,Fraccions,Decimals positius 1, Decimals 1,Decimals positius 2,Decimals 2

!formselect natcoef list $listnat prompt $affnat 
</li>
<li> Dificultat
!formselect difficulte from 1 to 3 
(no disponible pels sistemes d'equacions)
</li>

<li>
!formcheckbox  nocalcul list 1 prompt No demani efectuar els càlculs.
</li>
<li> Nombre d'exercicis
!formselect nbreexo from 1 to 8
</li>
</ul>

</ul>
<input type=hidden name=module value=$module> 
<center><input type=submit value="A treballar"></center>
</form>

!read related.phtml sistemes d'equacions, equacions, inequacions 

!tail
