#if defined TARGET_coord
\text{warning1=Er is een tekenfoutje voor }
\text{warning2=Je hebt de assen verwisseld bij }
\text{name_instruction=Geef de co&ouml;rdinaten voor }
\text{name_and=en}
#endif
#if defined TARGET_croissant || defined TARGET_croissant2
\text{name_choix=stijgend,dalend}
\text{instruction=Bepaal aan de hand van de getallenlijn de volgorde van de getoonde getallen.}
#endif
#if defined TARGET_itineraire
\text{instruction=We vragen de route om van punt \(\A\) naar punt \(\B\) en wel zo dat
twee opeenvolgende punten op de route &eacute;&eacute;n co&ouml;rdinaat gemeen hebben.
Geef je antwoord als een lijst van de tussenstappen}
\text{name_question=De route is }
\text{name_consigne=Geef de route als een lijst met de namen van de punten, gescheiden door een komma.}
\text{name_answer=De route }
#endif
#if defined TARGET_ordre
\text{instruction=Vul aan de hand van de getallenlijn de onderstaande uitdrukking in. 
Gebruik de symbolen  &lt;, &gt; of = }
#endif
#if defined TARGET_ordrerelatif
\text{instruction=Geef het nauwkeurigste interval van \u met behulp van de volgende getallen}
#endif
#if defined TARGET_placerc
\text{instruction=Teken het punt\(A\) met co&ouml;rdinaten }
#endif
#if defined TARGET_position
\text{liste=rechts, links}
\text{name_inst=De x-co&ouml;rdinaat van punt \(B\) op de getallenlijn is +BBBB of -BBBB , van \(A\)
 met x-co&ouml;rdinaat AAAA. Wat is de x-co&ouml;rdinaat van \(B\)&nbsp;}
\text{name_answer=De x-co&ouml;rdinaat is }
#endif
#if defined TARGET_position0
\text{liste=rechts, links}
\text{name_inst=Een punt \(A\) op de getallenlijn heeft een x-co&ouml;rdinaat van +AAAA of -AAAA en ligt , van 0. Welke x-co&ouml;rdinaat heet het punt&nbsp;}
\text{name_answer=De x-co&ouml;rdinaat is }
#endif
#if defined TARGET_relatifdist
\text{instruction=Bepaal met behulp van de getallenlijn de afstand tussen de twee punten \(A (\A)\) en \(B (\B)\).}
\text{name_answer=De afstand tussen }
\text{name_and=en}
#endif
#if defined TARGET_relatrule
\text{instruction=Geef de waarden van de getoonde punten op de getallenlijn.}
#endif
#if defined TARGET_rulefrac0
\text{consigne=Het pijltje op de getallenlijn.}
#endif
#if defined TARGET_rulefrac
\text{consigne=Het pijltje op de schaalverdeling of onderverdeling.}
#endif
#if defined TARGET_rulefracirr || defined TARGET_rulefracrelirr
\text{consigne=De breuk is niet vereenvoudigbaar.
De pijl wijst naar de schaalverdeling of onderverdeling.}
#endif
#if defined TARGET_rulefracrel
\text{consigne=De pijl wijst naar de schaalverdeling of onderverdeling.}
#endif
#if defined TARGET_rulefrac0 || defined TARGET_rulefrac || defined TARGET_rulefracirr || defined TARGET_rulefracrel || defined TARGET_rulefracrelirr
\text{instruction=Zie de getallenlijn. Het punt -aangegeven met een pijl- 
heeft de quoti&euml;nt van twee gehele getallen. Het zijn : }
\text{name_numden=Teller,noemer} 
\text{name_warning=Je hebt de breuk niet vereenvoudigd.}
\text{name_solution=De oplossing is}
\text{name_consigne=Volgorde}
#endif


