#if defined TARGET_coord
\text{warning1=Il y a une erreur de signe pour}
\text{warning2=Vous avez confondu l'abscisse et l'ordonnée de}
\text{name_instruction=Dar las coordenadas de los puntos}
\text{name_and=y}
#endif
#if defined TARGET_croissant || defined TARGET_croissant2
\text{name_choix=creciente,decreciente}
\text{instruction=Ayudándose de la regla graduada, ordenar de forma,
  los siguientes números}
#endif
#if defined TARGET_itineraire
\text{instruction=Deseamos ir del punto \(\A\) al punto \(\B\), pasando por todos los puntos
  del dibujo una vez y de manera que dos puntos consecutivos tengan una coordenada igual.
  Proporcionar un itinerario dando la lista ordenada de los puntos por los que se pasa:}
\text{name_question=El itinerario es }
\text{name_consigne=Deberá escribirse el nombre de los puntos separados por comas.}
\text{name_answer=Itinerario}
#endif
#if defined TARGET_ordre
\text{instruction=Ayudándose de la regla graduada, completar las expresiones
  con los símbolos}
#endif
#if defined TARGET_ordrerelatif
\text{instruction=Dar el mejor marco posible de \u
  tomando los números de la lista siguiente}
#endif
#if defined TARGET_placer
\text{instruction=Mettez le point \(A\) en}
#endif
#if defined TARGET_position
\text{liste=derecha, izquierda}
\text{name_inst=El punto \(B\) tiene de abscisa +BBBB o -BBBB. Ahora bien está a la, de \(A\)
  que tiene de abscisa AAAA. ¿Cuál es su abscisa?}
\text{name_answer=Su abscisa es}
#endif
#if defined TARGET_position0
\text{liste=derecha, izquierda}
\text{name_inst=El punto \(A\) tiene de abscisa +AAAA ou -AAAA. Ahora bien está a la , de 0.
  ¿Cuál es su abscisa?}
\text{name_answer=Su abscisa es}
#endif
#if defined TARGET_relatifdist
\text{instruction=Ayudándose de la regla graduada, determinar la distancia entre
  los puntos \(A (\A)\) y \(B (\B)\).}
\text{name_answer=Distancia entre}
\text{name_and=y}
#endif
#if defined TARGET_relatrule
\text{instruction=En la siguiente recta graduada, dar el valor de
  los puntos anotados}
#endif
#if defined TARGET_rulefrac0
\text{consigne=La flèche pointe sur une graduation.}
#endif
#if defined TARGET_rulefrac
\text{consigne=La flèche pointe sur une graduation ou une demi-graduation.}
#endif
#if defined TARGET_rulefracirr || defined TARGET_rulefracrelirr
\text{consigne=Debe presentarse la fracción en forma irreductible.
  La flèche pointe sur une graduation ou une demi-graduation.}
#endif
#if defined TARGET_rulefracrel
\text{consigne=La flèche pointe sur une graduation ou une demi-graduation.}
#endif
#if defined TARGET_rulefrac0 || defined TARGET_rulefrac || defined TARGET_rulefracirr || defined TARGET_rulefracrel || defined TARGET_rulefracrelirr
\text{instruction=Aquí tiene una recta graduada. El punto indicado por la flecha sobre la recta graduada
  tiene como abscisa al cociente de dos enteros. Se trata de }
\text{name_numden=numerador,denominador}
\text{name_warning=No ha simplificado la fracción..}
\text{name_solution=Una solución es}
\text{name_consigne=Instrucciones}
#endif
