#if defined TARGET_rulefrac0
# define TITRE_nl Getallenlijn en breuken 0
#endif
#if defined TARGET_rulefrac
# define TITRE_nl Getallenlijn en breuken 1
#endif
#if defined TARGET_rulefracirr
# define TITRE_nl Getallenlijn en onvereenvoudigbare breuken
#endif
#if defined TARGET_rulefracrel
# define TITRE_nl Getallenlijn en breuken (pos. en neg.)
#endif
#if defined TARGET_rulefracrelirr
# define TITRE_nl Getallenlijn en onvereenvoudigbare breuken (pos. en neg.)
#endif
#if defined TARGET_coord
# define TITRE_nl Co&ouml;dinaten in het platte vlak
#endif
#if defined TARGET_croissant
#define TITRE_nl Noteer de getallen in de goede volgorde I
#endif
#if defined TARGET_croissant2
#define TITRE_nl Noteer de getallen in de goede volgorde II
#endif
#if defined TARGET_itineraire
#define TITRE_nl Route door het platte vlak
#endif
#if defined TARGET_ordre
#define TITRE_nl Groter of kleiner ? I
#endif
#if defined TARGET_ordrerelatif
#define TITRE_nl Noteer de getallen in de goede volgorde III
#endif
#if defined TARGET_placer
#define TITRE_nl Zet een punt in het platte vlak
#endif
#if defined TARGET_position
#define TITRE_nl Links of rechts van een punt
#endif
#if defined TARGET_position0
#define TITRE_nl Links of rechts van nul
#endif
#if defined TARGET_relatifdist
#define TITRE_nl Afstend op de getallenlijn
#endif
#if defined TARGET_relatrule
#define TITRE_nl Getallenlijn en getallen
#endif
