#if defined TARGET_rulefrac0
# define TITRE_es Règle et fractions 0
#endif
#if defined TARGET_rulefrac
# define TITRE_es Regla y fracciones 1
#endif
#if defined TARGET_rulefracirr
# define TITRE_es Regla y fracciones irreductibles
#endif
#if defined TARGET_rulefracrel
# define TITRE_es Regla y fracciones relativas
#endif
#if defined TARGET_rulefracrelirr
# define TITRE_es Regla y fracciones irreductibles (relativ)
#endif
#if defined TARGET_coord
# define TITRE_es Coordenadas en el plano
#endif
#if defined TARGET_croissant
#define TITRE_es Ordenar números relativos
#endif
#if defined TARGET_croissant2
#define TITRE_es Ordenar números relativos II
#endif
#if defined TARGET_itineraire
#define TITRE_es Itinerario en el plano
#endif
#if defined TARGET_ordre
#define TITRE_es Números relativos y orden I
#endif
#if defined TARGET_ordrerelatif
#define TITRE_es Orden de los relativos
#endif
#if defined TARGET_placer
#define TITRE_es Placer un point dans le plan
#endif
#if defined TARGET_position
#define TITRE_es A derecha o izquierda de un punto
#endif
#if defined TARGET_position0
#define TITRE_es A la derecha o la izquierda de 0
#endif
#if defined TARGET_relatifdist
#define TITRE_es Distancia sobre la recta graduada
#endif
#if defined TARGET_relatrule
#define TITRE_es Regla y números relativos
#endif
