!header
!read Exindex

!if $lang=en
  This module currently contains $exototal exercises on powers of a
  number, powers of 10, scientific notation.  
  !goto end
!endif

!if $lang=it
  Questo modulo contiene al momento $exototal esercizi sulle proprietà
  delle potenze di un numero, sulle potenze di 10 e l'approssimazione
  di un numero tra potenze di 10, sulla notazione scientifica.
  !goto end
!endif

!if $lang=es
  Este módulo agrupa por el momento  $exototal ejercicios sobre las potencias 
  de un número, las potencias de 10 y el encuadre por potencias de 10, 
  la notación científica. 
  !goto end
!endif

Ce module regroupe pour l'instant $exototal exercices sur les puissances 
d'un nombre, les puissances de 10 et l'encadrement par des puissances de 10, 
la notation scientifique. 

:end
!read oef/intromenu.phtml
!tail
