#if defined TARGET_airellelo
# define TITRE_fr Aire de parallélogramme
#endif
#if defined TARGET_airepent
# define TITRE_fr Aire de pentagone
#endif
#if defined TARGET_parallelo
# define TITRE_fr Sommet de parallélogramme
#endif
#if defined TARGET_givenscale
# define TITRE_fr Produits scalaires donnés
#endif
#if defined TARGET_combifind
# define TITRE_fr Trouver une combinaison linéaire
#endif
#if defined TARGET_combi3
# define TITRE_fr Combinaison linéaire de 3 vecteurs
#endif
#if defined TARGET_combi
# define TITRE_fr Combinaison
#endif
#if defined TARGET_angle
# define TITRE_fr Angle
#endif
#if defined TARGET_airetriang
# define TITRE_fr Aire de triangle
#endif
#if defined TARGET_airequadri
# define TITRE_fr Aire de quadrilatère
#endif
#if defined TARGET_rellin
# define TITRE_fr Relation linéaire
#endif

