#if defined TARGET_airellelo
\text{name_instruction=Compute the area of the parallelogram in the cartesian plane
  whose 4 vertices are}
\text{name_hint=L'aire du parallélogramme est la longueur du produit vectoriel
  des deux vecteurs représentant deux côtés adjacents du parallélogramme.}
\text{name_answer=Area}
#endif
#if defined TARGET_airepent
\text{name_instruction=Compute the area of the pentagon \(A B C D E\) in the cartesian
  plane whose 5 vertices are}
\text{name_answer=Area}
#endif
#if defined TARGET_parallelo
\text{name_instruction=We have a parallelogram \(A B C D) in the cartesian plane,
  whose 3 first vertices are at the coordinates}
\text{name_instruction2=Compute the coordinates of the fourth vertex}
#endif
#if defined TARGET_givenscale
\text{name_instruction=Let, be two vectors in the plane. Find the vector \(v\) having the following scalar products:}
\text{name_hint=Here, \(\langle \cdot, \cdot \rangle) is the scalar product.}
#endif
#if defined TARGET_combifind
\matrix{name_instruction=Let
  be two vectors in the plane, and let
  be another vector. Try to express v as a linear combination of \(v_1) and \(v_2)}
#endif
#if defined TARGET_combi3
\text{name_instruction=Let,be three vectors in the plane. Compute the vector}
#endif
#if defined TARGET_combi
\text{name_instruction=Let, be two vectors in the plane. Compute the vector}
#endif
#if defined TARGET_angle
\text{name_instruction=We have 3 points in the plane}
\text{name_instruction2=Compute the angle \(\widehat{BAC})
  (in degrees, between 0 and 180).}
\text{name_hint=Use the relation between the scalar product of two vectors and
  the angle between them.}
\text{name_answer=The angle}
#endif
#if defined TARGET_airetriang
\text{name_instruction=Compute the area of the triangle in the cartesian plane whose
  3 vertices are}
\text{name_hint=The vector product of two vectors gives the area of a parallelogram,
  and the half of a parallelogram is a triangle.}
\text{name_answer=Aire}
#endif
#if defined TARGET_airequadri
\text{name_instruction=Compute the area of the quadrilateral \(A B C D\) in the cartesian
plane whose 4 vertices are}
\text{name_hint=You may cut the quadrilateral into 2 triangles, and compute the area
  of each triangle by the vector product.}
\text{name_answer=Area}
#endif
#if defined TARGET_rellin
\matrix{name_instruction=We have 3 plane vectors,
  Find 3 integers \(a), \(b) and \(c) such that,
  but the integers a,b,c are not all zero.}
\text{name_cond1=are integers and not all zero}
\text{name_cond2=The algebraic sum of vectors is zero}
#endif
