#if defined TARGET_airellelo
# define TITRE Area of parallelogram
#endif
#if defined TARGET_airepent
# define TITRE Area of pentagon
#endif
#if defined TARGET_parallelo
# define TITRE Vertex of parallelogram
#endif
#if defined TARGET_givenscale
# define TITRE Given scalar products
#endif
#if defined TARGET_combifind
# define TITRE Find combination
#endif
#if defined TARGET_combi3
# define TITRE Combination 3 vectors
#endif
#if defined TARGET_combi
# define TITRE Combination
#endif
#if defined TARGET_angle
# define TITRE Angle
#endif
#if defined TARGET_airetriang
# define TITRE Area of triangle
#endif
#if defined TARGET_airequadri
# define TITRE Area of quadrilateral
#endif
#if defined TARGET_rellin
# define TITRE Linear relation
#endif
