\language{fr}
\format{html}
#if defined TARGET_suml || defined TARGET_sumg || defined TARGET_chgtva1 || defined TARGET_chgtva2 || defined TARGET_interversion
\author{Sophie,Lemaire}
\email{sophie.lemaire@universite-paris-saclay.fr}
#endif
#if defined TARGET_indsom || defined TARGET_sommation || defined TARGET_sommation2

\author{Bernadette,Perrin-Riou}
\email{bernadette.m.riou@orange.fr}
#endif
#if defined TARGET_sommedouble2 || defined TARGET_sommegraphe
\author{Thomas,Guillon}
\email{bernadette.m.riou@orange.fr}
#endif
#if defined TARGET_sommedouble
\author{Bernadette,Perrin-Riou;Sophie,Lemaire}
\email{bernadette.m.riou@orange.fr,sophie.lemaire@universite-paris-saclay.fr}
\computeanswer{no}
#endif
