!header
!read Exindex
!if $lang=en
  This module contains actually $exototal exercises on vectors in 3D
  (linear combinations, angle, length, scalar product, vector product, cross
  product, etc.).
!else
  Ce module regroupe pour l'instant $exototal exercices sur les vecteurs en
  3D (combinaisons linéaires, angle, longueur, produit scalaire, produit
  vectoriel, produit mixte, etc.).
!endif
!read oef/intromenu.phtml
!tail

