#include "lang_title_fr.inc"

#if defined TARGET_angle1 || defined TARGET_ptesimi1 || defined TARGET_rapport1
# define NUM 1
#endif
#if defined TARGET_angle2 || defined TARGET_ptesimi2 || defined TARGET_rapport2
# define NUM 2
#endif
#if defined TARGET_angle3 || defined TARGET_ptesimi3 || defined TARGET_rapport3
# define NUM 3
#endif
#if defined TARGET_angle4 || defined TARGET_ptesimi4 || defined TARGET_rapport4
# define NUM 4
#endif
#if defined TARGET_ptesimi5
# define NUM 5
#endif

\title{TITLE NUM}
