#if defined TARGET_angle1 || defined TARGET_angle2 || defined TARGET_angle3 || defined TARGET_angle4
# define TITLE Angle de similitude directe
#endif
#if defined TARGET_ptesimi1 || defined TARGET_ptesimi2 || defined TARGET_ptesimi3 || defined TARGET_ptesimi4 || defined TARGET_ptesimi5
# define TITLE Propriété des similitudes
#endif
#if defined TARGET_rapport1 || defined TARGET_rapport2 || defined TARGET_rapport3 || defined TARGET_rapport4
# define TITLE Rapport de similitude
#endif
