#if defined TARGET_resoudre_pb7
\matrix{name_enonce=XXXX avait un rendez-vous à
  Elle est arrivée avec
  de retard.
  Pour y aller, elle a couru
  et a pris le bus pendant}
\text{name_question=A quelle heure XXXX est-elle partie&nbsp;}
\text{name_question2=Elle est partie de chez elle à }
#endif
#if defined TARGET_resoudre_pb6
\matrix{name_enonce=XXXX avait un rendez-vous. Elle est partie de chez elle à
  Elle est arrivée avec
  de retard.
  Pour y aller, elle a couru
  et a pris le bus pendant}
\text{name_question=A quelle heure était son rendez-vous}
\text{name_question2=Son rendez-vous était à}
#endif
