
!set cut=357
<center>
!for i=1 to $askcnt
 !if $i isin $cut
  <p>
 !else
  !if $i>1
   &nbsp;&nbsp;&nbsp;&nbsp;
  !endif
 !endif
 !for t in a,b,c1,c2
  !set t$t=!item $i of $($(t)_list)
 !next t
 !set formula=!htmlmath x = $ta*t+$tc1, y = $tb*t+$tc2
 !if $status=waiting
  !href cmd=reply&good=$i $formula
 !else
  !if $i=$good
   <b>
  !endif
  !if $i=$real
   <font color=blue>
  !endif
  $formula
  !if $i=$good
   </b>
  !endif
  !if $i=$real
   </font>
  !endif
 !endif
!next i
</center>

