
!set cut=!item $askcnt of 0,0,0,3,4,4,46,47
<center>
!for i=1 to $askcnt
 !if $i isin $cut
  <p>
 !else
  !if $i>1
   &nbsp;&nbsp;
  !endif
 !endif
 !for t in ab,cb
  !set t$t=!item $i of $($(t)_list)
 !next t
 !set formula=!htmlmath $tab*y+$tcb
 !if $status=waiting
  !href cmd=reply&good=$i x&nbsp;=&nbsp;$formula
 !else
  !if $i=$good
   <b>
  !endif
  !if $i=$real
   <font color=blue>
  !endif
  x&nbsp;=&nbsp;$formula
  !if $i=$good
   </b>
  !endif
  !if $i=$real
   </font>
  !endif
 !endif
!next i
</center>

