!set t_1=parametri&#269;nih

<b>Vaja.</b> V kartezi&#269;ni ravnini je podana premica,
!if $givtype=2
 katere graf je prikazan na sliki.
 <p><center>
 !set ins_attr=alt="Graf premice"
 !insplot [-$range:$range] [-$range:$range] ($ba)*x-($ca) notitle
!else
 ki jo opisuje
 !if $givtype=1
  sistem parametri&#269;nih ena&#269;b
 !else
  ena&#269;ba
 !endif
 <p><center><font size=+1>
 !set formula=!line $givtype of x = $a*t+$c1, y = $b*t+$c2\
	\
	$b*x-$a*y = $c\
	y = $ba*x-$ca\
	x = $a/$b*y+$cb
 !htmlmath $formula
 </font>
!endif
</center> <p>
!if $asktype=2
 Katera od naslednjih slik prikazuje graf te premice? Kliknite nanjo.
!else
 Katera od naslednjih $(t_$asktype) ena&#269;b ustreza tej premici? Kliknite nanjo.
!endif
<p>
!read choice.$asktype.phtml
<p>
