!if $subject<6
    !if $teaching=1
    Immagina di voler estrarre due carte la cui somma è 11:
<table>
    <tr>
    <th>XX</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th><th>10</th><th><span style=font-size:120%;color:red">11</span></th><th>12</th><th>13</th>
    </tr><tr>
    <td><b>1</b></td><td>2</td><td>3</td><td>4</td> <td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td>
    </tr><tr>
    <td><b>2</b></td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td>
    </tr><tr>
    <td><b>3</b></td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td>
    </tr><tr>
    <td><b>4</b></td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td>
    </tr><tr>
    <td><b>5</b></td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td>
    </tr><tr>
    <td><b>6</b></td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td>
    </tr><tr>
    <td><b>7</b></td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td>
    </tr><tr>
    <td><b>8</b></td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td>
    </tr><tr>
    <td><b>9</b></td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td>
    </tr><tr>
    <td><b>10</b></td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td>
    </tr><tr>
    <td><span style=font-size:120%;color:red"><b>11</b></span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td>
    </tr><tr>
    <td><b>12</b></td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td>
    </tr><tr>
    <td><b>13</b></td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td><td>26</td>
    </tr>
</table>

    !endif
<br />Un comune mazzo di carte da gioco:<br />
<ul> 
    <li>
	52 carte
    </li>
    <li>
	4 semi:
	<ul>
	    <li>
		<em>cuori</em>:<br />
		<img src="$module_dir/cards/H6.gif" alt="noalt" />
	    </li>
	    <li>
		<em>quadri</em>:<br />
		<img src="$module_dir/cards/R6.gif" alt="noalt" />
	    </li>
	    <li>
		<em>fiori</em>:<br />
		<img src="$module_dir/cards/K6.gif" alt="noalt" />
	    </li>
	    <li>
		<em>picche</em>:<br />
		<img src="$module_dir/cards/S6.gif" alt="noalt" />
	    </li>
	    <li>
                ogni seme ha un Jack (J)<br />
                ogni seme ha una Regina (Q=Queen)<br />
                ogni seme ha un Re (K=King)<br />
                ogni seme ha un Asse (A)<br />
	    </li>
	 </ul>
    </li>
    <li>
	26 carte rosse (<em>cuori</em> &amp; <em>quadri</em>)
    </li>
    <li>
	26 carte nere (<em>fiori</em> &amp; <em>picche</em>)
    </li>
</ul>
<table>
    <tr>
    <th>
      <span style="font-size:120%"><em>cuori</em></span><br />
      <img src="$module_dir/cards/H2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H10.gif" alt="noalt" />
      <br />
      <img src="$module_dir/cards/H11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%"><em>quadri</em></span><br />
      <img src="$module_dir/cards/R2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R9.gif" alt="noalt" />
      <img src="$module_dir/cards/R10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/R11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%"><em>fiori</em></span><br />
      <img src="$module_dir/cards/K2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/K11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%"><em>picche</em></span><br />
      <img src="$module_dir/cards/S2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/S11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S1.gif" alt="noalt" /> 
    </th>
    </tr>
</table>

!endif
!if $subject isin 6,7,8,9
    !if $teaching=1
    Alcuni esempi:<br />
    <ol>
	<li>
            Supponiamo di avere 3 dadi non truccati.
	    <br />
            È richiesto di calcolare la probabilità dell'uscita di: un
	    1 e due 6.
	    <br />
	    E che l'ordine della sequenza non sia importante<br />
	    Il risultato può essere:<br />
	    <ul>
		<li><kbd>166</kbd></li>
		<li><kbd>616</kbd></li>
		<li><kbd>661</kbd></li>
	    </ul>
	    E questo è il modo di calcolare la probabilità
	    !if $status=done
		<br />
		!!insmath 3\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}
    		<img src="$module_dir/gifs/help7a.gif" alt="noalt" />
	    !else
		.<br />
	    !endif
	</li>
	<li>
	    Ora supponiamo di avere 4 dadi non truccati.
	    <br />
	    È richiesto di calcolare la probabilità dell'uscita di: un 1, due 6 e un 5. 
	    <br />
	    Anche in questo caso che l'ordine della sequenza non sia importante.<br />
	    Questo risultato può essere ottenuto in (4!)/2 = 24/2 = 12  modi diversi<br />
	    <ul>
		<li><kbd>1665</kbd></li>
		<li><kbd>5661</kbd></li>
		<li><kbd>6615</kbd></li>
		<li><kbd>6651</kbd></li>
		<li><kbd>1566</kbd></li>
		<li><kbd>5166</kbd></li>
		<li><kbd>6165</kbd></li>
		<li><kbd>6561</kbd></li>
		<li><kbd>6156</kbd></li>
		<li><kbd>6516</kbd></li>
		<li><kbd>1656</kbd></li>
		<li><kbd>5616</kbd></li>
		<li><kbd>pfff</kbd></li>
	    </ul>
	    E utilizzando questo schema è possibile calcolare la probabilità
	    !if $status=done
		<br />
		!!insmath 12\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}
		<img src="$module_dir/gifs/help7b.gif" alt="noalt" />
	    !else
		.<br />
	    !endif
	</li>
	<li>
	    Supponiamo di avere 3 dadi non truccati.
	    <br />
	    E che ci sia richiesto di calcolare la probabilità che la somma dei 
	    tre dadi sia 10.
	    <br />
	    Ci sono diversi modi per ottenere 10 con 3 dadi:<br />
	    <ul>
		<li>1 3 6 
	<br />che possono essere ottenuti in ordini diversi (tutte le <em>permutazioni</em>...):
		    <ul>
			<li>1 3 6</li>
			<li>1 6 3</li>
			<li>3 1 6</li>
			<li>3 6 1</li>
			<li>6 3 1</li>
			<li>6 1 3</li>
		    </ul>
		    in sostanza 6 modi, ovvero: <b>3!</b>
		</li>
		<li>1 4 5 --- anche in questo caso in <b>3!</b> modi</li>
		<li>2 2 6 --- attenzione: solo in <b>3</b> modi</li>
		<li>2 3 5 --- in <b>3!</b> modi</li>
		<li>2 4 4 --- attenzione: solo in <b>3</b> modi</li>
		<li>3 3 4 --- attenzione: solo in <b>3</b> modi</li>
	    </ul>
	    Il totale è quindi 6+6+3+6+3+3 = 27 modi.<br />
	    Se invece pensiamo a tutte le possibilità di lanci diversi per questi 3 dadi ne
 	    abbiamo in totale:  6&times;6&times;6 = 216<br />
	    La probabiltà è quindi:<br />
	    !!insmath \frac{27}{6 \cdot 6 \cdot6} = \frac{27}{216} = \frac{1}{8}
	    <img src="$module_dir/gifs/help7c.gif" alt="noalt" />
    </ol>
    !endif
Lo sviluppo di un comune dado da gioco:<br />
<img src="$module_dir/dice/dobbelsteen.gif" alt="noalt" />
!endif
