
!if $subject<6
    !if $teaching=1
    Suppose you look for two cards with a sum of 11:
<table>
    <tr>
    <th>XX</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th><th>10</th><th><span style=font-size:120%;color:red">11</span></th><th>12</th><th>13</th>
    </tr><tr>
    <td><b>1</b></td><td>2</td><td>3</td><td>4</td> <td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td>
    </tr><tr>
    <td><b>2</b></td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td>
    </tr><tr>
    <td><b>3</b></td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td>
    </tr><tr>
    <td><b>4</b></td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td>
    </tr><tr>
    <td><b>5</b></td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td>
    </tr><tr>
    <td><b>6</b></td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td>
    </tr><tr>
    <td><b>7</b></td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td>
    </tr><tr>
    <td><b>8</b></td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td>
    </tr><tr>
    <td><b>9</b></td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td>
    </tr><tr>
    <td><b>10</b></td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td>
    </tr><tr>
    <td><span style=font-size:120%;color:red"><b>11</b></span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td>
    </tr><tr>
    <td><b>12</b></td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td>
    </tr><tr>
    <td><b>13</b></td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td><td>26</td>
    </tr>
</table>

    !endif
A deck of normal playing cards:<br />
<ul> 
    <li>
	52 cards
    </li>
    <li>
	4 flavours:
	<ul>
	    <li>
		<em>hearts</em>:<br />
		<img src="$module_dir/cards/H6.gif" alt="noalt" />
	    </li>
	    <li>
		<em>diamonds</em>:<br />
		<img src="$module_dir/cards/R6.gif" alt="noalt" />
	    </li>
	    <li>
		<em>clubs</em>:<br />
		<img src="$module_dir/cards/K6.gif" alt="noalt" />
	    </li>
	    <li>
		<em>spades</em>:<br />
		<img src="$module_dir/cards/S6.gif" alt="noalt" />
	    </li>
	    <li>
		every flavour has one Jack<br />
		every flavour has one Queen<br />
		every flavour has one King<br />
		every flavour has one Ace<br />
	    </li>
	 </ul>
    </li>
    <li>
	26 red cards (<em>hearts</em> &amp; <em>diamonds</em>)
    </li>
    <li>
	26 black cards (<em>clubs</em> &amp; <em>spades</em>)
    </li>
</ul>
<table>
    <tr>
    <th>
      <span style="font-size:120%"><em>hearts</em></span><br />
      <img src="$module_dir/cards/H2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H10.gif" alt="noalt" />
      <br />
      <img src="$module_dir/cards/H11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%"><em>diamonds</em></span><br />
      <img src="$module_dir/cards/R2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R9.gif" alt="noalt" />
      <img src="$module_dir/cards/R10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/R11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%"><em>clubs</em></span><br />
      <img src="$module_dir/cards/K2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/K11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%"><em>spades</em></span><br />
      <img src="$module_dir/cards/S2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/S11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S1.gif" alt="noalt" /> 
    </th>
    </tr>
</table>

!endif
!if $subject isin 6,7,8,9
    !if $teaching=1
    A few examples:<br />
    <ol>
	<li>
	    Suppose we have 3 normal fair dice.
	    <br />
	    You are asked to calculate the chance of : 1 and 2 &times; 6  pips.
	    <br />
	    And the sequence is not interesting<br />
	    The results can be:<br />
	    <ul>
		<li><kbd>166</kbd></li>
		<li><kbd>616</kbd></li>
		<li><kbd>661</kbd></li>
	    </ul>
	    And this is the way to calculate the chance
	    !if $status=done
		<br />
		!!insmath 3\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}
    		<img src="$module_dir/gifs/help7a.gif" alt="noalt" />
	    !else
		.<br />
	    !endif
	</li>
	<li>
	    Now suppose we have 4 fair dice
	    <br />
	    And you were asked to calculate the chance of: 1 and 2&times;6  and one 5.
	    <br />
	    again the sequence is irrelevant.<br />
	    This result can be reached at (4!)/2 = 24/2 = 12  different ways<br />
	    <ul>
		<li><kbd>1665</kbd></li>
		<li><kbd>5661</kbd></li>
		<li><kbd>6615</kbd></li>
		<li><kbd>6651</kbd></li>
		<li><kbd>1566</kbd></li>
		<li><kbd>5166</kbd></li>
		<li><kbd>6165</kbd></li>
		<li><kbd>6561</kbd></li>
		<li><kbd>6156</kbd></li>
		<li><kbd>6516</kbd></li>
		<li><kbd>1656</kbd></li>
		<li><kbd>5616</kbd></li>
		<li><kbd>pfff</kbd></li>
	    </ul>
	    And using such scheme, you could calculate the chance
	    !if $status=done
		<br />
		!!insmath 12\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}
		<img src="$module_dir/gifs/help7b.gif" alt="noalt" />
	    !else
		.<br />
	    !endif
	</li>
	<li>
	    Suppose we have 3 fair dice.
	    <br />
	    And you were asked to calculate the chance on a total of 10 pips.
	    <br />
	    Getting 10 pips from 3 dice:<br />
	    <ul>
		<li>1 3 6 
	<br />the permutations are:
		    <ul>
			<li>1 3 6</li>
			<li>1 6 3</li>
			<li>3 1 6</li>
			<li>3 6 1</li>
			<li>6 3 1</li>
			<li>6 1 3</li>
		    </ul>
		    basically  6 ways , or better: <b>3!</b>
		</li>
		<li>1 4 5 --- also <b>3!</b> ways</li>
		<li>2 2 6 --- attention: only <b>3</b> ways</li>
		<li>2 3 5 --- also <b>3!</b> ways</li>
		<li>2 4 4 --- attention: only <b>3</b> ways</li>
		<li>3 3 4 --- attention: only <b>3</b> ways</li>
	    </ul>
	    The total is now  6+6+3+6+3+3 = 27 ways.<br />
	    For these 3 dice in total:  6&times;6&times;6 = 216 different possibilities<br />
	    The chance is thus :<br />
	    !!insmath \frac{27}{6 \cdot 6 \cdot6} = \frac{27}{216} = \frac{1}{8}
	    <img src="$module_dir/gifs/help7c.gif" alt="noalt" />
    </ol>
    !endif
A map of a normal die:<br />
<img src="$module_dir/dice/dobbelsteen.gif" alt="noalt" />
!endif
