
!if $subject<6
    !if $teaching=1
    Stel je zoekt twee kaarten met een som van 11:
<table>
    <tr>
    <th>XX</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th><th>10</th><th><span style=font-size:120%;color:red">11</span></th><th>12</th><th>13</th>
    </tr><tr>
    <td><b>1</b></td><td>2</td><td>3</td><td>4</td> <td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td>
    </tr><tr>
    <td><b>2</b></td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td>
    </tr><tr>
    <td><b>3</b></td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td>
    </tr><tr>
    <td><b>4</b></td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td>
    </tr><tr>
    <td><b>5</b></td><td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td>
    </tr><tr>
    <td><b>6</b></td><td>7</td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td>
    </tr><tr>
    <td><b>7</b></td><td>8</td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td>
    </tr><tr>
    <td><b>8</b></td><td>9</td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td>
    </tr><tr>
    <td><b>9</b></td><td>10</td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td>
    </tr><tr>
    <td><b>10</b></td><td><span style=font-size:120%;color:red">11</span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td>
    </tr><tr>
    <td><span style=font-size:120%;color:red"><b>11</b></span></td><td>12</td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td>
    </tr><tr>
    <td><b>12</b></td><td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td>
    </tr><tr>
    <td><b>13</b></td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td><td>26</td>
    </tr>
</table>

    !endif
Een kaartspel bestaat uit:<br />
<ul> 
    <li>
	52 kaarten
    </li>
    <li>
	4 soorten kaarten:
	<ul>
	    <li>
		Harten:<br />
		<img src="$module_dir/cards/H6.gif" alt="noalt" />
	    </li>
	    <li>
		Ruiten:<br />
		<img src="$module_dir/cards/R6.gif" alt="noalt" />
	    </li>
	    <li>
		Klaver:<br />
		<img src="$module_dir/cards/K6.gif" alt="noalt" />
	    </li>
	    <li>
		Schoppen:<br />
		<img src="$module_dir/cards/S6.gif" alt="noalt" />
	    </li>
	    <li>
		elke soort heeft &eacute;&eacute;n Boer<br />
		elke soort heeft &eacute;&eacute;n Vrouw<br />
		elke soort heeft &eacute;&eacute;n Heer<br />
		elke soort heeft &eacute;&eacute;n Aas<br />
	    </li>
	 </ul>
    </li>
    <li>
	26 rode kaarten (Harten &amp; Ruiten)
    </li>
    <li>
	26 zwarte kaarten (Klaver &amp; Schoppen)
    </li>
</ul>
<table>
    <tr>
    <th>
      <span style="font-size:120%">$Harten</span><br />
      <img src="$module_dir/cards/H2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H10.gif" alt="noalt" />
      <br />
      <img src="$module_dir/cards/H11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%">$Ruiten</span><br />
      <img src="$module_dir/cards/R2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R9.gif" alt="noalt" />
      <img src="$module_dir/cards/R10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/R11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%">$Klaver</span><br />
      <img src="$module_dir/cards/K2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/K11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%">$Schoppen</span><br />
      <img src="$module_dir/cards/S2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/S11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S1.gif" alt="noalt" /> 
    </th>
    <tr>
</table>

!endif

!if $subject=21 or $subject=22
<br />
<span style="color:blue"><ul>
<li>Een empirische kans is een proefondervindelijke kans.<br />
Je moet dan eerst de knikkers laten vallen in het bord van Galton. <br />
Met behulp van het resultaat kun je de kansen uitrekenen</li>
<li>Een theoretische kans is een kans, waarbij je geen proef nodig hebt.<br />
Je kunt deze kansen uitrekenen zonder het experiment met de vallende knikkers.<br />
Denk bijvoorbeeld aan een dobbelsteen en de kans op het gooien van 4 ( P(4)=1/6 ).<br />
Bij dit onderdeel moet je je afvragen hoevaak de knikker 'een keuze' maakt.<br />
</li>
<li>Mocht je helemaal niet weten hoe je dit aan moet pakken.<br />
Vul een fout antwoord in en bekijk galton.pdf .<br />
galton.pdf zal niet zichtbaar zijn tijdens een toets.</li>
</ul></span>
!endif

!if  $subject=23
    <br />
    <span style="color:red"><b>
    Elke tak, moet je afzonderlijk tekenen.<br />
    Het getal en de letter moet je op de juiste tak zetten en afsluiten met een enter.</b></span>
!endif

!if $subject=6 or $subject=7
    !if $teaching=1
	Een paar voorbeeldjes:<br />
	<ol>
	    <li>
		Stel we hebben 3 eerlijke dobbelstenen.
		<br />
		Gevraagd wordt de kans op een: &eacute;&eacute;n en twee zessen.
		<br />
		De volgorde doet er niet toe.<br />
		De resultaten kun je op drie manieren bereiken, te weten<br />
		<ul>
		    <li><kbd>166</kbd></li>
		    <li><kbd>616</kbd></li>
		    <li><kbd>661</kbd></li>
		</ul>
		Hiermee kun je de kans berekenen
		!if $status=done
		    <br />
		    !!insmath 3\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}
    		    <img src="$module_dir/gifs/help7a.gif" alt="noalt" />
		!else
		    .<br />
		!endif
	    </li>
	    <li>
		Stel we hebben 4 eerlijke dobbelstenen.
		<br />
		Gevraagd wordt de kans op een: &eacute;&eacute;n en twee zessen en een vijf.
		<br />
		De volgorde doet er niet toe.<br />
		De resultaten kun je op (4!)/2 = 24/2 = 12  manieren bereiken, te weten<br />
		<ul>
		    <li><kbd>1665</kbd></li>
		    <li><kbd>5661</kbd></li>
		    <li><kbd>6615</kbd></li>
		    <li><kbd>6651</kbd></li>
		    <li><kbd>1566</kbd></li>
		    <li><kbd>5166</kbd></li>
		    <li><kbd>6165</kbd></li>
		    <li><kbd>6561</kbd></li>
		    <li><kbd>6156</kbd></li>
		    <li><kbd>6516</kbd></li>
		    <li><kbd>1656</kbd></li>
		    <li><kbd>5616</kbd></li>
		    <li><kbd>pfff</kbd></li>
		</ul>
		Hiermee kun je de kans berekenen
		!if $status=done
		    <br />
		    !!insmath 12\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}\cdot \frac{1}{6}
		    <img src="$module_dir/gifs/help7b.gif" alt="noalt" />
		!else
		    .<br />
		!endif
	    </li>
	    <li>
		Stel we hebben 3 eerlijke dobbelstenen.
		<br />
		Gevraagd wordt de kans op een totaal score van 10 ogen.
		<br />
		Dat kan worden bereikt met de volgende combinaties:<br />
		<ul>
		    <li>1 3 6 
		<br />Deze combinatie kan op de volgende manieren worden bereikt:
		    <ul>
			<li>1 3 6</li>
			<li>1 6 3</li>
			<li>3 1 6</li>
			<li>3 6 1</li>
			<li>6 3 1</li>
			<li>6 1 3</li>
		    </ul>
		    Dus dit kan op 6 manieren , ofwel <b>3!</b>
		</li>
		<li>1 4 5 --- ook op <b>3!</b> manieren</li>
		<li>2 2 6 --- letop: kan maar op <b>3</b> manieren</li>
		<li>2 3 5 --- ook op <b>3!</b> manieren</li>
		<li>2 4 4 --- letop: kan maar op <b>3</b> manieren</li>
		<li>3 3 4 --- letop: kan maar op <b>3</b> manieren</li>
	    </ul>
	    In't totaal is dat 6+6+3+6+3+3 = 27 manieren.<br />
	    Voor drie dobbelstenen zijn er in't totaal 6&times;6&times;6 = 216 mogelijkheden<br />
	    De kans is dus nu :<br />
	    !!insmath \frac{27}{6 \cdot 6 \cdot6} = \frac{27}{216} = \frac{1}{8}
	    <img src="$module_dir/gifs/help7c.gif" alt="noalt" />
	</ol>
    !endif
<img src="$module_dir/dice/dobbelsteen.gif" alt="noalt" />
!endif
