blocks.cpp

#if defined TARGET_tie || defined TARGET_IXI
#define TITLE Noeud de papillon
#endif
#if defined TARGET_twosqr
#define TITLE Deux carrés
#endif
#if defined TARGET_threesqr
#define TITLE Trois carrés
#endif
#if defined TARGET_foursqr
#define TITLE Quatre carrés
#endif
#if defined TARGET_cube
#define TITLE Cube
#endif
#if defined TARGET_house
#define TITLE Maison
#endif
#if defined TARGET_diag
#define TITLE Carré + diagonales
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE Pizza
#endif

pyramid.cpp
#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE Pyramide
#endif

pentagram.cpp
#if defined TARGET_pentagram
#define TITLE Pentagramme
#endif

sides.cpp
#if defined TARGET_triangle
#define TITLE Triangle
#endif
#if defined TARGET_bigsquare
#define TITLE Carré
#endif
#if defined TARGET_cross
#define TITLE Croix
#endif
#if defined TARGET_V
??
#define TITLE V
#endif
#if defined TARGET_stool
#define TITLE Tabouret
#endif
#if defined TARGET_H
#define TITLE H
#endif
#if defined TARGET_M
#define TITLE M
#endif
#if defined TARGET_W
#define TITLE W
#define TITLE_it W
#endif
#if defined TARGET_asterisk
#define TITLE Astérisque
#endif
#if defined TARGET_grill
#define TITLE Grille
#endif
#if defined TARGET_pentagon
#define TITLE Pentagone
#endif
