#if defined TARGET_corres3 || defined TARGET_corres4 || defined TARGET_corres5
# define TITRE Correspondance de racines carrées
#endif
#if defined TARGET_reduitsom2 || defined TARGET_reduitsom3 || defined TARGET_reduitsom4
# define TITRE Écriture réduite d'une somme
#endif
#if defined TARGET_liaison3 || defined TARGET_liaison4 || defined TARGET_liaison5
# define TITRE Racines et nombres
#endif
#if defined TARGET_entier
# define TITRE Tableau d'entiers.
#endif
#if defined TARGET_rationnel
# define TITRE Tableau de fractions.
#endif
#if defined TARGET_decimal
# define TITRE Tableau de décimaux.
#endif
#if defined TARGET_puissance1
# define TITRE Tableau de puissances de 10.
#endif
#if defined TARGET_puissance2
# define TITRE Tableau de puissances quelconques
#endif
