!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les cônes de révolution et la construction de leurs patrons.<br>
<br>L'exercice Patron cône 1 demande dans certains cas l'emploi de la racine cubique. Ces cas n'existent pas dans l'exercice Patron cône 1*. C'est la seule différence entre ces deux exercices.
<p>Les deux exercices portant sur le patron d'un abat-jour sont plus difficiles car ils demandent de l'initiative, mais les connaissances nécessaires ne dépassent pas le niveau collège (Thalès, Pythagore, proportionnalité).<br>

L'exercice Abat-jour* est construit (de manière un peu artificielle) de telle sorte que les calculs de longueurs aboutissent à des résultats qui "tombent justes". Il est donc un peu plus simple en pratique.


!read oef/intromenu.phtml
!tail
