!header
!read Exindex
!if $lang=it
  Questo modulo raggruppa alcuni esercizi sulle operazioni insiemistiche di base: unione, intersezione, complementare, differenza, differenza simmetrica, prodotto cartesiano. Gli insiemi sono tutti insiemi finiti di numeri o lettere.
!goto intromenu
!endif
!if $lang=es
  Este módulo agrupa ejercicios sobre operaciones entre conjuntos: unión, intersección, complemento, diferencia, diferencia simétrica, producto cartesiano. Los conjuntos considerados son finitos y formados por números o letras.
!goto intromenu
!endif
Ce module regroupe des exercices sur les opérations ensemblistes de base : union, intersection, complémentaire, différence, différence symétrique, produit cartésien. Les ensembles y sont toujours des ensembles finis de nombres ou de lettres.
:intromenu
!read oef/intromenu.phtml
!tail
