!set n=$counter
<script type="text/javascript">
"use strict";
var slider_min=$slider_min;
var slider_max=$slider_max;
var slider_width=$slider_width;
var slider_height=$slider_height;
var slider_text="$slider_text"
!! 3 = radialen 2 = graden
var slider_value_type=$slider_value_type;
var canvas_scripts = new Array();canvas_scripts.push("0");
 var wims_status = "";
 function sendanswer(){
  var reply = document.getElementById('myinput0').value;
  !if $rounding != 0
   if(is_real_number(reply) != 1){return;}
  !else
   if(check_f(reply) != 1){return;}
   if(is_number(reply) != 1){return;}
   !endif
  myConfirm(reply,reply,'$wims_ref_name','$session','$module','$counter','$ok_send_color'); 
 }
 !! antwoord altijd in radialen !!
 </script>
<!-- canvasdraw div and tooltip placeholder, if needed -->
<div tabindex="0" id="canvas_div0" style="position:relative;width:200px;height:200px;margin-left:auto;margin-right:auto;" ></div>
<div id="tooltip_placeholder_div" style="display:block;margin-bottom:4px;"><span id="tooltip_placeholder" style="display:none;"></span></div>
<!-- include actual object code via include file -->
<script type="text/javascript" src="$module_dir/js/sinus.2.js"></script>
!if $wims_user=supervisor
$XY = <input class="schaersvoorde_input" id="myinput0" size="6" value="$(answer$n)" />
!else
$XY = <input class="schaersvoorde_input" id="myinput0" size="6" value="" />
!endif