!set n=$counter
<script type="text/javascript">
 "use strict";
 var xaxislabel="hoek in radialen";
 var yaxislabel="y-as";
 var slider_min=$slider_min;
 var slider_max=$slider_max;
 var slider_width=$slider_width;
 var slider_height=$slider_height;
 var slider_text="$slider_text"
 !if $type=sin
    var x_start=1;
    var y_start=0;
    var angle_start=0;
    var angle_end=0;
    var gonio_correctie=0;
 !else
    var x_start=0;
    var y_start=1;
    var angle_start=90;
    var angle_end=90;
    var gonio_correctie=90;
 !endif
 var gonio = function(t){
  return Math.$type(t);
 }
 var reply = new Array();
!! -1=geen display; 0 = x-waarde;1=y-waarde; 2=graden ; 3=radialen 
!! let op : reply[0] = x; reply[1]=y;reply[2]=graden;reply[3]=radialen(=x) 
 var slider_value_type=$slider_value_type;
 var wims_status = "";
 function sendanswer(){
  myConfirm("$send ?",reply,'$wims_ref_name','$session','$module','$counter','$ok_send_color'); 
 }
 </script>
<!-- canvasdraw div and tooltip placeholder, if needed -->
<div tabindex="0" id="canvas_div0" style="position:relative;width:800px;height:200px;margin-left:auto;margin-right:auto;" ></div>
<div id="tooltip_placeholder_div" style="display:block;margin-bottom:4px;"><span id="tooltip_placeholder" style="display:none;"></span></div>
<!-- include actual object code via include file -->
<script type="text/javascript" src="$module_dir/js/sinus.4.js"></script>
