!! no need for translation
!set number=!record 7 of remarks.$taal


!!! remind title
<div style="font-color:blue ;background-color: #FFFF66 ;"><center>
<h3>	
!set q1=!item 1 of $question
  $q1
!set q2=!item 2 of $question
!if $q2!=$empty
!insmath $q2
!endif
</h3>
</div>

<table border=1 cellpadding=12>
!for p=1 to $[$counter-1]
    <td>
	$number $p 	
    </td>
    <td>
	$(result$p) 
    </td>
    <td>
	$(ahint$p)
    </td>
    <tr>
!next p    
</table>        

!if $module_score>5
   <font color=green>
   $OK
!else
   <font color=red>
   $NOK
!endif

!set the_end=!record 19 of remarks.$taal
$the_end
</font>
<p>

!if $debug=1
    <table border=1 cellpadding="5">
	<th>
	    Some debug data
	</th>
	<tr>
	<td>
	    <ol>	
		$debug_data
		<li>original appletanswer=$appletanswer</li>
	        <li>after checkproc : type=$type</li>
		<li> we check on : $identify </li>
                <li> required points are : $ptnames </li>
	    </ol>
	</td>
    </table>    
!endif
