!! no need for translation
!header


!form new
<input type=hidden name=module value="$module">



<!-- VRoyer: only one task per exercise  -->
!set tasks=1

<!-- VRoyer: precision values !set precvals=0.1,0.25,1-->


!if $lang isitemof fr,nl,en,de
   !set taal=$lang
!else
    !set taal=en
!endif



!!! preambule
<p><small>
!if $taal=fr
Ce module de <b>15 exercices interactifs</b> est une variante du module "Constructions" de Paul Byache et Joke Evers.<br>
Il s'agit de construire des éléments géométriques
<b>à la règle et au compas</b> avec l'applet <b> GeoGebra 3</b>.
<br> Le module s'adresse
à des élèves relativement avancés en mathématiques (fin du collège, début du lycée),
 d'où un niveau d'exigence plus élevé pour les constructions.
<br> Pour plus d'interactivité, quand la réponse est
insuffisante, la construction de l'élève lui est renvoyée en l'état pour qu'il la corrige.
<br>Après avoir terminé correctement une construction, l'élève doit en <b>rédiger une justification</b>.
 Son texte sera enregistré pour relecture par le professeur.
!endif

!if $taal=en
This module of <b>15 interactive exercises </b> is  a variant of
the module "Constructions" by Paul Byache and Joke Evers.<br>
It deals  with the construction  of geometric items
<b>by the rule  and compass</b> simulated by the applet <b> GeoGebra 3</b>.
<br> The module concerns
students  relatively advanced  in mathematics (levels H3 to H6),
hence a rather high level of exigence in the constructions.
<br> For more interactivity, when the answer is
insufficient, the student construction is sent back to him
for further correction.
<br>When the student has correctly done a construction,
he must  <b>write a justification</b>.
His text will be recorded  so that the teacher can read it later.
!endif


!if $taal=de
Dieses Modul von <b>15 interaktiven Aufgaben</b> ist  ein Variant des
Modules "Constructions" von Paul Byache und Joke Evers.<br>
Es behandelt geometrische Konstruktionen
<b>mit Zirkel und Lineal</b> mithilfe der Geometriesoftware <b> GeoGebra 3</b>.

<br> Falls die Konstruktion des Schülers nicht richtig ist, ist
sie ihm zurück gegeben, sodass er eine weitere und bessere Figur zeichnen kann.
<br>Wenn der Schüler eine richtige Konstruktion gemacht hat,
 muss er sie <b>schriftlich begründen</b>.
Das Text wird gespeichert,  sodass der Lehrer es später lesen kann.
!endif

</small></p>



!set style=font-size: 11pt ; font-weight: bold ; background-color: #FFFF66 ;

<p align="center">
    <table>
	<td>
	    !record 6 of remarks.$taal
	</td>
	<td>
	    <select name="subject" size="15">
		<option value="1">
		    !record 27 of remarks.$taal
		</option>
		<option value="5">
		    !record 29 of remarks.$taal
		</option>
		<option value="2">
		    !record 30 of remarks.$taal
		</option>
		<option value="3">
		    !record 33 of remarks.$taal
	        </option>
		<option value="4">
		    !record 36 of remarks.$taal
		</option>
                <option value="6">
		    !record 38 of remarks.$taal
		</option>
                <option value="7">
		    !record 39 of remarks.$taal
		</option>
                <option value="8">
		    !record 40 of remarks.$taal
		</option>
                <option value="11">
		    !record 13 of remarks.$taal
		</option>
                <option value="9">
		    !record 41 of remarks.$taal
		</option>
                <option value="10">
		    !record 42 of remarks.$taal
		</option>
                <option value="12">
		    !record 62 of remarks.$taal
		</option>
                <option value="14">
		    !record 69 of remarks.$taal
		</option>
                <option value="13">
		    !record 63 of remarks.$taal
		</option>
                <option value="15">
		    !record 70 of remarks.$taal
		</option>
	    </select>
	</td>
	<tr>
	<td>
	    !record 8 of remarks.$taal
	</td>
	<td>
	    !set pr=!record 9 of remarks.$taal
           !! in proc file precision=pr/2,
           !! so precision will be equal to 0.5 or 1 or 1.5
	    <select name="precision">
                <option value="2">
		!item 2 of $pr
		</option>
		<option value="1">
		!item 1 of $pr
		</option>
		<option value="3">
		!item 3 of $pr
		</option>
	    </select>
	</td>
	<tr>
    !if $wims_user=supervisor
	<td>
	    !record 1 of remarks.$taal
	</td>
	<td>
	    <select name="debug">
		<option value="1">
		    yes
		</option>
		<option value="0">
		    no
		</option>
	    </select>
	</td>
	<tr>
    !endif

<!-- MODIFIED BY VROYER -> only one exercise at a time
##
## 	<td>
## 	    !record 10 of remarks.$taal
## 	</td>
##
##      <td>
## 	    <select name="tasks">
## 		<option value="1">1</option>
## 		<option value="2">2</option>
## 	        <option value="3">3</option>
## 		<option value="4">4</option>
## 		<option value="5">5</option>
## 	    </select>
## 	</td>
## 	<tr>
-->
	<td>
	</td>
	<td>

<!-- config variables to pass to var.init-->

	    <div align="left">
		<input type=hidden name=taal value="$taal">
                <input type=hidden name=tasks value="$tasks">
                <input type=hidden name=precision value="$precision">
		<input type=submit style="$style" value=
		"
		!record 11 of remarks.$taal
		"
		>
	    </div>
	</td>
    </table>
    </p>
</form>

!tail
