%% Caractérisations du milieu
\text{listmil=\(\overrightarrow{A C}=\overrightarrow{C B}),
\(\overrightarrow{B C}=\overrightarrow{C A}),\(\overrightarrow{A C}=\frac{1}{2}\overrightarrow{A B}),
\(\overrightarrow{A C}=-\overrightarrow{B C}),\(\overrightarrow{B C}=-\overrightarrow{A C}),
\(\overrightarrow{B C}=-\frac{1}{2}\overrightarrow{A B}),\(\overrightarrow{A B}+\overrightarrow{A C}=3\overrightarrow{C B}),
\(\overrightarrow{D A}+\overrightarrow{D B}=2\overrightarrow{D C})}


%% Caratérisations du symétrique
\text{listsym=\(\overrightarrow{A C}+\overrightarrow{A B}=3\overrightarrow{B C}),
\(\overrightarrow{A B}=\overrightarrow{B C}),\(\overrightarrow{C B}=\overrightarrow{B A}),
\(\overrightarrow{A B}=\frac{1}{2}\overrightarrow{A C}),
\(\overrightarrow{A B}=-\overrightarrow{C B}),\(\overrightarrow{C B}=-\overrightarrow{A B}),
\(\overrightarrow{C B}=-\frac{1}{2}\overrightarrow{A C})}

%% Caractérisations du parallélogramme
\text{listpar=\(\overrightarrow{A B}+\overrightarrow{A D}=\overrightarrow{A C}),
\(\overrightarrow{B A}+\overrightarrow{B C}=\overrightarrow{B D}),
\(\overrightarrow{C B}+\overrightarrow{C D}=\overrightarrow{C A}),
\(\overrightarrow{A D}+\overrightarrow{C D}=\overrightarrow{B D})}

%% Mauvaises Caractérisations du parallélogramme
\text{listbadpar=\(\overrightarrow{A B}+\overrightarrow{A C}=\overrightarrow{A D}),
\(\overrightarrow{B A}+\overrightarrow{B C}=\overrightarrow{D B}),
\(\overrightarrow{C B}+\overrightarrow{C A}=\overrightarrow{C D}),
\(\overrightarrow{D A}+\overrightarrow{D C}=\overrightarrow{B D}),
\(A C=C B),\(A B=B C),\(\overrightarrow{A B}+\overrightarrow{B C}=\overrightarrow{A C})}
