#if defined TARGET_cubrt
#define TITLE Racine cubique
#endif
#if defined TARGET_tworoots2
#define TITLE Deux racines II
#endif
#if defined TARGET_eqmod
#define TITLE Équation avec module
#endif
#if defined TARGET_modsum
#define TITLE Module de somme
#endif
#if defined TARGET_sumofj
#define TITLE Somme de j
#endif
#if defined TARGET_cbrt
#define TITLE CBRT
#endif
#if defined TARGET_arggiven
#define TITLE Argument donné
#endif
#if defined TARGET_pentaroot
#define TITLE Pentaroot
#endif
#if defined TARGET_argask
#define TITLE Argument demandé
#endif
#if defined TARGET_quadouble
#define TITLE Quadratique racine double
#endif
#if defined TARGET_quadouble2
#define TITLE Quadratique racine double II
#endif
#if defined TARGET_argsum
#define TITLE Argument de somme
#endif
#if defined TARGET_pythagorus2
#define TITLE Pythagore II
#endif
#if defined TARGET_fraction2
#define TITLE Fraction II
#endif
#if defined TARGET_rootcoef
#define TITLE Racine et coefficients
#endif
#if defined TARGET_pythagorus
#define TITLE Pythagore
#endif
#if defined TARGET_sqrt
#define TITLE Racine carrée
#endif
#if defined TARGET_fraction
#define TITLE Fraction
#endif
#if defined TARGET_modmax
#define TITLE Module maximal
#endif
#if defined TARGET_Trianglequilat
#define TITLE Triangle équilatéral
#endif
#if defined TARGET_quadpoly
#define TITLE Racines d'un polynôme quadratique
#endif
#if defined TARGET_sumofi
#define TITLE Somme de i
#endif
#if defined TARGET_suminv
#define TITLE Somme avec inverse
#endif
#if defined TARGET_sumroot
#define TITLE Somme de racines d'unité
#endif
#if defined TARGET_tworoots
#define TITLE Deux racines
#endif
#if defined TARGET_modsum2
#define TITLE Module de somme II
#endif
#if defined TARGET_powerconj
#define TITLE Puissance conjuguée
#endif
#if defined TARGET_maxmod
#define TITLE Maximum de module
#endif

\title{TITLE}
