!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices de Terminale S sur
<ol>
<li>la continuité ;</li>
<li>le théorème des valeurs intermédiaires ;</li>
<li>la fonction racine n-ième.</li>
</ol>

Ces exercices ne font pas référence aux fonctions exponentielles et logarithmes,
sauf l'exercice "Pourquoi une fonction est continue 2".

!read oef/$module_language/intromenu.phtml
!tail
