#if defined TARGET_deriverComp
# define TITRE_en Derivative of a combined function \(u(a x + b)\)
#endif
#if defined TARGET_deriverInvRac
# define TITRE_en Dériver une composée suivie d'une fonction de référence
#endif
#if defined TARGET_deriverPoly
# define TITRE_en Derivative of a polynomial
#endif
#if defined TARGET_deriverPolys
# define TITRE_en Derivative of polynomials
#endif
#if defined TARGET_deriverProduit
# define TITRE_en The product rule
#endif
#if defined TARGET_deriverQuotient
# define TITRE_en The quotient rule
#endif
#if defined TARGET_nbdergraph
# define TITRE_en Tangent and derivative
#endif
#if defined TARGET_nbdergraph2
# define TITRE_en Tangent and derivative (2)
#endif
#if defined TARGET_varInvRac
# define TITRE_en Variation d'une composée
#endif
#if defined TARGET_varPolydeg3
# define TITRE_en Derivative of a polynomial (deg.3)
#endif
#if defined TARGET_varTrinome
# define TITRE_en Investigate a Function
#endif
