#if defined TARGET_deriverComp
# define TITRE Dérivée d'une composée u(a x + b)
#endif
#if defined TARGET_deriverInvRac
# define TITRE Dériver une composée suivie d'une fonction de référence
#endif
#if defined TARGET_deriverPoly
# define TITRE Dérivée d'une fonction polynôme
#endif
#if defined TARGET_deriverPolys
# define TITRE Calculs de dérivées de fonctions polynômes
#endif
#if defined TARGET_deriverProduit
# define TITRE Dérivée d'un produit
#endif
#if defined TARGET_deriverQuotient
# define TITRE Dérivée d'un quotient
#endif
#if defined TARGET_nbdergraph
# define TITRE Tangente et nombre dérivé
#endif
#if defined TARGET_nbdergraph2
# define TITRE Tangente et nombre dérivé (2)
#endif
#if defined TARGET_varInvRac
# define TITRE Variation d'une composée
#endif
#if defined TARGET_varPolydeg3
# define TITRE Étude guidée d'un polynôme (deg.3)
#endif
#if defined TARGET_varTrinome
# define TITRE Variation d'un polynôme du second degré
#endif
