<table>
Use for:
    <td>
	Multiplications:
    </td>
    <td>
	<input size=20 value="5*x" readonly>
    </td>
    <tr>
    <td>
	Division: 
    </td>
    <td>
	<input size=20 value="5/x" readonly>
    </td>
    <tr>
    <td>
	Fractions: 
    </td>
    <td>
	<input size=20 value="2/3" readonly>
    </td>
    <tr>
    <td>
	Powers:
    </td>
    <td>
	<input size=20 value="2^3" readonly><br>
	<input size=20 value="sin(x)^2" readonly>
    </td>
    <tr>
    <td>
	Decimal number:
    </td>
    <td>
	<input size=20 value="5.2" readonly> and not 5,2
    </td>
    <tr>
    <td>
	Set of coordinates:
    </td>
    <td>
	<input size=20 value="(10:3)" readonly>
    </td>
    <tr>
    <td>
	Attention to fractions: 
    </td>
    <td>
	<input size=20 value="5/3" readonly>  and not 1 2/3

    </td>
    <tr>
    <td>
	Parenthesis:
    </td>
    <td>
	<input size=20 value="2/(3x)" readonly>
    </td>
    <tr>
    <td>
	Parenthesis: 
    </td>
    <td>
	<input size=20 value="sin(3x)" readonly><br>
	<input size=20 value="log(3x)" readonly>
    </td>
    <tr>
    <td>
	&radic;x: 
    </td>
    <td>
	<input size=20 value="sqrt(x)" readonly>
    </td>
    <tr>
    <td>
	<sup>n</sup>&radic;x: 
    </td>
    <td>
	<input size=20 value="sqrt[n](x)" readonly>
    </td>
    <tr>
    <td>
	log(x): 
    </td>
    <td>
	<input size=20 value="log[n](x)" readonly>
    </td>
    <tr>
    <td>
	&pi;: 
    </td>
    <td>
	<input size=20 value="pi" readonly>
    </td>
</table>