<table>
De volgende symbolen van je toetsenbord moet je bij het intypen gebruiken:
    <td>
	Vermenigvuldigen:
    </td>
    <td>
	<input size=20 value="5*x" readonly>
    </td>
    <tr>
    <td>
	Delen: 
    </td>
    <td>
	<input size=20 value="5/x" readonly>
    </td>
    <tr>
    <td>
	Breuken: 
    </td>
    <td>
	<input size=20 value="2/3" readonly>
    </td>
    <tr>
    <td>
	Machten:
    </td>
    <td>
	<input size=20 value="2^3" readonly><br>
	<input size=20 value="sin(x)^2" readonly>
    </td>
    <tr>
    <td>
	Decimaal getal:
    </td>
    <td>
	<input size=20 value="5.2" readonly> en dus niet 5,2
    </td>
    <tr>
    <td>
	Co&ouml;rdinaten:
    </td>
    <td>
	<input size=20 value="(10:3)" readonly>
    </td>
    <tr>
    <td>
	Haal niet de helen<br>uit een breuk: 
    </td>
    <td>
	<input size=20 value="5/3" readonly>  en niet 1 2/3 : dat snapt een computer niet.

    </td>
    <tr>
    <td>
	Gebruik haakjes: 
    </td>
    <td>
	<input size=20 value="2/(3x)" readonly>
    </td>
    <tr>
    <td>
	Gebruik haakjes: 
    </td>
    <td>
	<input size=20 value="sin(3x)" readonly><br>
	<input size=20 value="log(3x)" readonly>
    </td>
    <tr>
    <td>
	&radic;x: 
    </td>
    <td>
	<input size=20 value="sqrt(x)" readonly>
    </td>
    <tr>
    <td>
	<sup>n</sup>&radic;(x): 
    </td>
    <td>
	<input size=20 value="sqrt[n](x)" readonly>
    </td>
    <tr>
    <td>
	<sup>n</sup>log(x): 
    </td>
    <td>
	<input size=20 value="log[n](x)" readonly>
    </td>
    <tr>
    <td>
	&pi;: 
    </td>
    <td>
	<input size=20 value="pi" readonly>
    </td>
</table>