<table>
用法:
    <td>
    乘法:
    </td>
    <td>
    <input size=20 value="5*x" readonly>
    </td>
    <tr>
    <td>
    除法: 
    </td>
    <td>
    <input size=20 value="5/x" readonly>
    </td>
    <tr>
    <td>
    分数: 
    </td>
    <td>
    <input size=20 value="2/3" readonly>
    </td>
    <tr>
    <td>
    乘幂:
    </td>
    <td>
    <input size=20 value="2^3" readonly><br>
    <input size=20 value="sin(x)^2" readonly>
    </td>
    <tr>
    <td>
    十进小数:
    </td>
    <td>
    <input size=20 value="5.2" readonly> 而不是 5,2
    </td>
    <tr>
    <td>
    坐标:
    </td>
    <td>
    <input size=20 value="(10:3)" readonly>
    </td>
    <tr>
    <td>
    分数注意事项: 
    </td>
    <td>
    <input size=20 value="5/3" readonly> 而不是 1 2/3

    </td>
    <tr>
    <td>
    括号:
    </td>
    <td>
    <input size=20 value="2/(3x)" readonly>
    </td>
    <tr>
    <td>
    括号: 
    </td>
    <td>
    <input size=20 value="sin(3x)" readonly><br>
    <input size=20 value="log(3x)" readonly>
    </td>
    <tr>
    <td>
    &radic;x: 
    </td>
    <td>
    <input size=20 value="sqrt(x)" readonly>
    </td>
    <tr>
    <td>
    <sup>n</sup>&radic;x: 
    </td>
    <td>
    <input size=20 value="sqrt[n](x)" readonly>
    </td>
    <tr>
    <td>
    log(x): 
    </td>
    <td>
    <input size=20 value="log[n](x)" readonly>
    </td>
    <tr>
    <td>
    &pi;: 
    </td>
    <td>
    <input size=20 value="pi" readonly>
    </td>
</table>
