!header
!read Exindex
<p style="
background:#2E9AFE;
margin:10px 10px 5px 10px;
padding:5px 5px 5px 5px;
border-radius: 10px;
border: 2px solid #2E9AFE;
color: white;
">
Ce module regroupe pour l'instant $exototal exercices sur les lois continues (densité, 
loi uniforme, loi normale, loi exponentielle), échantillonnage, estimation, intervalle de fluctuation, 
intervalle de confiance. Niveau Terminale ES ou S.</p>

!read oef/intromenu.phtml
!tail
