#if defined TARGET_oefanglenat1 || defined TARGET_oefanglenat2 || defined TARGET_oefanglenat3 || defined TARGET_oefanglenat4 || defined TARGET_oefanglenat5
# define TITRE Nature d'un angle
#endif
#if defined TARGET_oefcodeangl1 || defined TARGET_oefcodeangl2 || defined TARGET_oefcodeangl3 || defined TARGET_oefcodeangl4 || defined TARGET_oefcodeangl5
# define TITRE Codage des angles
#endif
#if defined TARGET_oefcompangl1 || defined TARGET_oefcompangl2 || defined TARGET_oefcompangl3 || defined TARGET_oefcompangl4 || defined TARGET_oefcompangl5
# define TITRE Comparaison d'angles
#endif
#if defined TARGET_oefestangl1 || defined TARGET_oefestangl2 || defined TARGET_oefestangl3 || defined TARGET_oefestangl4 || defined TARGET_oefestangl5
# define TITRE Estimation d'un angle
#endif
#if defined TARGET_oefmesangl1 || defined TARGET_oefmesangl2 || defined TARGET_oefmesangl3 || defined TARGET_oefmesangl4 || defined TARGET_oefmesangl5
# define TITRE Rapporteur
#endif
#if defined TARGET_oefvocangle1 || defined TARGET_oefvocangle2 || defined TARGET_oefvocangle3 || defined TARGET_oefvocangle4 || defined TARGET_oefvocangle5
# define TITRE Vocabulaire sur les angles
#endif
#if defined TARGET_oefreprodangle1 || defined TARGET_oefreprodangle2 || defined TARGET_oefreprodangle3 || defined TARGET_oefreprodangle4 || defined TARGET_oefreprodangle5
# define TITRE Reproduire un angle
#endif
#if defined TARGET_oefconstangl1 || defined TARGET_oefconstangl2 || defined TARGET_oefconstangl3 || defined TARGET_oefconstangl4 || defined TARGET_oefconstangl5
# define TITRE Construction d'un angle
#endif
