#include "lang_title_fr.inc"
#if defined TARGET_oefconstangl1 || defined TARGET_oefreprodangle1 || defined TARGET_oefvocangle1 || defined TARGET_oefmesangl1 || defined TARGET_oefestangl1 || defined TARGET_oefanglenat1 || defined TARGET_oefcodeangl1 || defined TARGET_oefcompangl1
# define NUM 1
#endif
#if defined TARGET_oefconstangl2 || defined TARGET_oefreprodangle2 || defined TARGET_oefvocangle2 || defined TARGET_oefmesangl2 || defined TARGET_oefestangl2 || defined TARGET_oefanglenat2 || defined TARGET_oefcodeangl2 || defined TARGET_oefcompangl2
# define NUM 2
#endif
#if defined TARGET_oefconstangl3 || defined TARGET_oefreprodangle3 || defined TARGET_oefvocangle3 || defined TARGET_oefmesangl3 || defined TARGET_oefestangl3 || defined TARGET_oefanglenat3 || defined TARGET_oefcodeangl3 || defined TARGET_oefcompangl3
# define NUM 3
#endif
#if defined TARGET_oefconstangl4 || defined TARGET_oefreprodangle4 || defined TARGET_oefvocangle4 || defined TARGET_oefmesangl4 || defined TARGET_oefestangl4 || defined TARGET_oefanglenat4 || defined TARGET_oefcodeangl4 || defined TARGET_oefcompangl4
# define NUM 4
#endif
#if defined TARGET_oefconstangl5 || defined TARGET_oefreprodangle5 || defined TARGET_oefvocangle5 || defined TARGET_oefmesangl5 || defined TARGET_oefestangl5 || defined TARGET_oefanglenat5 || defined TARGET_oefcodeangl5 || defined TARGET_oefcompangl5
# define NUM 5
#endif
\title{TITRE NUM}
