#if defined TARGET_distpl
# defined TITRE_nl Afstand punt-lijn I
#endif
#if defined TARGET_distpl2
# defined TITRE_nl Afstand punt-lijn II
#endif
#if defined TARGET_lineonpnt
# defined TITRE_nl Line on point I
#endif
#if defined TARGET_lineonpnt2
# defined TITRE_nl Line on point II
#endif
#if defined TARGET_par1
# defined TITRE_nl Parallel I
#endif
#if defined TARGET_par2
# defined TITRE_nl Parallel II
#endif
#if defined TARGET_parm2eq
# defined TITRE_nl Parametrized to equation
#endif
#if defined TARGET_perp1
# defined TITRE_nl Perpendicular I
#endif
#if defined TARGET_perp2
# defined TITRE_nl Perpendicular II
#endif
#if defined TARGET_pnt2eq
# defined TITRE_nl 2 points
#endif
#if defined TARGET_pntonline
# defined TITRE_nl Point on line I
#endif
#if defined TARGET_pntonline2
# defined TITRE_nl Point on line II
#endif
#if defined TARGET_slope2eq
# defined TITRE_nl Point and slope
#endif
