#if defined TARGET_distpl
# define TITRE Distance point-line I
#endif
#if defined TARGET_distpl2
# define TITRE Distance point-line II
#endif
#if defined TARGET_par1
# define TITRE Parallel (éq. cartésienne)
#endif
#if defined TARGET_par2
# define TITRE Parallel
#endif
#if defined TARGET_perp1
# define TITRE Perpendicular I
#endif
#if defined TARGET_pntonline
# define TITRE Point on line I
#endif
#if defined TARGET_pntonline2
# define TITRE Point on line II
#endif
#if defined TARGET_lineonpnt
# define TITRE Line through point I
#endif
#if defined TARGET_lineonpnt2
# define TITRE Line through point II
#endif
#if defined TARGET_pnt2eq
# define TITRE 2 points
#endif
#if defined TARGET_slope2eq
# define TITRE Point and slope
#endif
#if defined TARGET_parm2eq
# define TITRE Parametric to vector
#endif
#if defined TARGET_perp2
# define TITRE Perpendicular II
#endif
#if defined TARGET_parparam
# define TITRE Parametric parallel
#endif


\title{TITRE}
