!header
!read Exindex
 
Ce module regroupe pour l'instant $exototal exercices sur les probabilités en première et terminale : probabilités conditionnelles, variables aléatoires et arbres pondérés.
<br>Elaboré par l'IREM Picardie avec l'aide de Chantal CAUSSE et de la communauté MutuWIMS.
<br>Certains exercices sont inspirés ou des adaptations d'exercices des modules H5/probability/OEFproba1S.fr et H6/probability/OEFprobaTS.fr de Régine Mangeard.

!read oef/intromenu.phtml
!tail
