!set n=$teller

<table border="1" bgcolor="$bgcolor2">
    <td>
    问题 <b>$n</b>) 
    <p>
    这里是未知三角函数的动画.
    <br>
    $(somtekst$n)
    <p><font size="-1">
    !if $bijles=1
        !if $wims_user=supervisor
        <small>
            主持教师, 通过把 "额外支持" 设成 "否",<br> 
            后面的文本可被隐藏
        </small>
        !endif  
        所求函数<em>可能是</em>如下类型<br>
        <img src="$module_dir/gifs/nivo$nivo.$(SIN$n).gif">
        <br>
    !endif
    !if $instinker=1
        !if $nivo=1
        注意: 有些函数确实很巧妙:
        <br>
        对于 <em>f(x)=d*sin(c*x)/b</em> 或 <em>f(x)=d+c*sin(x/b)</em> 能说些什么
        !endif
        !if $nivo=2
        注意: 有些函数确实很巧妙:
        <br>
        对于 <em>f(x)=s*sin(s*x)/s</em>  能说些什么...
        !endif
    !endif
    
    <small><em>
        如果你不理解这样做的意图, 参看
        !href target=wims_mhelp cmd=help
        <b>帮助</b></a>
        </em></small>
    </p>    
    </td>
    <tr>
    <td>
    确定函数的正确变量/参数:
    <br>
    $(opgave$n)
    <br>
    <!-- 是的, 当然 , 我知道: 你可以阅读网页的源文件并拷贝所要的函数...
    但是这样你学不到数学. 尽管你可以得到很好的分数 ;)
    //-->
    <p align="center">
        <font color=$fontcolor2><em> $soort </em></font>函数是:<br>
    <table>
        <td>
        <font color=$fontcolor1 size="+2">
            <em>    
            $(letter$n)(x)&nbsp;=
            </em>
        </font>
        </td>
        <td>
        !if $wims_user=supervisor 
            <input size=40 name="ANT$n" value="$(GOED$n)"> 
        !else
            <input size=40 name="ANT$n" value="$(ANT$n)"> 
        !endif
        </td>
    </table>
    </td>
</table>
