!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur des calculs commerciaux et financiers (lycée professionnel). Ces exercices ont été conçus par le groupe LP-TIC de l'IREM de Lyon.

!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=

!read oef/intromenu.phtml
!tail
