!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices simples sur les proportions,
pourcentages et taux d'évolution. 
Ils comportent des applications simples de la correspondance entre pourcentage
 ou taux d'évolution et coefficient multiplicateur.

<p>
Des exercices complémentaires sur les tableaux croisés et les arbres sont
disponibles
!href target=wims_internal module=H5/probability/OEFproba1S.fr ici
.
</p>
!read oef/$module_language/intromenu.phtml

!tail
