!header
!read Exindex
Deze module bevat oefenstof over het werken met vergelijkingen.<br>
Gevraagd wordt een vergelijking via het slepen met de muis 
 -met getallen en/of operators- te completeren.
 <p>
 Door gebruik te maken van de onderstaande instel-mogelijkheden, kan deze module oefeningen 
 genereren voor de lagere school (<em>bewerkingen met positieve getallen</em>) , voor
 onderbouw (<em>positief,negatief,breuken</em>), 
 voor de bovenbouw (<em>wortels en complexe getallen</em>) 
 en hoger (<em>vergelijkingen met meerdere variabelen</em>)

!read oef/intromenu.phtml
!tail
