!set n=!recordcnt src/data
!reset objlist
!for i=1 to $n
 !set l=!record $i of src/data
 !set l=!line 1 of $l
 !set objlist=!append item $l to $objlist
!next i

<tr><td align=center>Kies de open plek(ken) in de vergelijking:
</td><td>
!set wims_formselect_switch=multiple size=4
!set confparm3=50 0
!formselect confparm3 list 1 0,2 0,3 0,\
	50 0,0 1,0 2,\
	0 50,1 1,2 1,\
	2 2,50 50\
	prompt \
	1 open plek, 2 open plekken, 3 open plekken,\
	alles open, 1 operator, 2 operators,\
	alle operators, 1 open plek  + 1 operator,2 open plekken + 1 operator,\
	2 open plekken + 2 operators, alles open
!reset wims_formselect_switch
<tr><td align=center>keuze uit de volgende "termen":
</td><td>
!set confparm1=1
!formselect confparm1 from 1 to $n prompt $objlist
</td>
<tr><td align=center>Keuze uit de volgende "operators":
</td><td>
!set confparm2=2
!formselect confparm2 from 1 to 3 prompt \
	+ and -, + - &times;, + - &times; &divide;
<tr><td align=center>Het aantal extra "sleep-objecten":
</td><td>
!set confparm4=1
!formselect confparm4 from 0 to 5

