!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les intérêts composés. 
L'ensemble de ses exercices aborde les notions suivantes :
<ul><li>Passage des intérêts simples aux intérêts composés</li>
<li>Calcul de valeur acquise en faisant varier la durée de capitalisation</li>
<li>Calcul de la durée d'un placement. Plusieurs méthodes sont proposées mais une seule est de niveau BAC PRO.</li>
<li>Calcul de la valeur actuelle d'un capital futur.</li>
</ul>

Une approche pragmatique est réalisée et le thème suivant
 est abordé :
<ul>
<li>vie économique et professionnelle</li>
</ul>

Ils ont été réalisés pour un niveau de Terminal BAC PRO section tertiaire.

!read oef/intromenu.phtml
!tail
