#if defined TARGET_connecteursLN
#define TITLE_it Connettivi booleani
#endif
#if defined TARGET_deduction
#define TITLE_it Deduzione logica
#endif
#if defined TARGET_implication
#define TITLE_it Implicazione nel linguaggio naturale
#endif
#if defined TARGET_incoherence
#define TITLE_it Regolamento inconsistente
#endif
#if defined TARGET_negationLN
#define TITLE_it Negazione nel linguaggio naturale
#endif
#if defined TARGET_negationMath
#define TITLE_it Negazione in matematica
#endif
#if defined TARGET_reciproque
#define TITLE_it Reciproca o contronominale ?
#endif
#if defined TARGET_tautologie
#define TITLE_it Tautologie
#endif
#if defined TARGET_valeursVerite
#define TITLE_it Valori di verità
#endif
#if defined TARGET_validite
#define TITLE_it Validità di una proposizione
#endif
