#if defined TARGET_connecteursLN
#define TITLE Connecteurs booléens
#endif
#if defined TARGET_deduction
#define TITLE Déduction logique
#endif
#if defined TARGET_implication
#define TITLE Implication en langage naturel
#endif
#if defined TARGET_incoherence
#define TITLE Règlement incohérent
#endif
#if defined TARGET_negationLN
#define TITLE Négation en langage naturel
#endif
#if defined TARGET_negationMath
#define TITLE Négation en mathématiques
#endif
#if defined TARGET_reciproque
#define TITLE Réciproque ou Contraposée ?
#endif
#if defined TARGET_tautologie
#define TITLE Tautologies
#endif
#if defined TARGET_valeursVerite
#define TITLE Valeurs de vérité
#endif
#if defined TARGET_validite
#define TITLE Validité d'une proposition
#endif
