#if defined TARGET_oefsysequa1 || defined TARGET_oefsysequa2 || defined TARGET_oefsysequa3 || defined TARGET_oefsysequa4 || defined TARGET_oefsysequa5 || defined TARGET_oefsysequa6 || defined TARGET_oefsysequa7 || defined TARGET_oefsysequa8
\author{Jean-Luc, Donadoni}
#else
\author{Jean-Luc, Donadoni; Fabrice, Guerimand}
#endif
\email{jluc.donadoni@laposte.net}
\language{fr}
\range{-5..5}
\computeanswer{no}
\format{html}
maintainer WIMSEDU
