\text{name_and=et}
#if defined TARGET_Equation1 || defined TARGET_Equation2 || defined TARGET_Equation3 || defined TARGET_Equation4 || defined TARGET_Equation5 || defined TARGET_Equation6 || defined TARGET_Equation10 || defined TARGET_Equation11 || defined TARGET_Equation12 || defined TARGET_Equation13 || defined TARGET_Equation14
\text{name_enonce=Résoudre l'équation}
\text{name_then=La solution est}
#endif
#if defined TARGET_correquat1
\text{name_enonce=Mettre en relation chaque équation d'inconnue,
  avec sa solution.}
#endif
#if defined TARGET_Equation10 || defined TARGET_Equation11 || defined TARGET_Equation12 || defined TARGET_Equation13 || defined TARGET_Equation14
\text{name_instruction=Donner votre résultat sous une forme aussi simplifiée que possible.}
#endif
#if defined TARGET_optrou1 || defined TARGET_optrou2 || defined TARGET_optrou3 || defined TARGET_optrou4 || defined TARGET_optrou5 || defined TARGET_optrou6
\text{name_enonce=Compléter l'opération}
#endif
#if defined TARGET_oefsysequa1 || defined TARGET_oefsysequa2 || defined TARGET_oefsysequa3 || defined TARGET_oefsysequa4 || defined TARGET_oefsysequa5 || defined TARGET_oefsysequa6 || defined TARGET_oefsysequa7 || defined TARGET_oefsysequa8
\text{name_enonce=Résoudre le système d'équations}
\text{name_solution=La solution du système est}
\text{name_instruction=Si nécessaire, utiliser le point comme séparateur décimal.}
#endif
