!set wims_backslash_insmath=yes
!set introhook_tableless=yes

!set list_menu0=\(\vee,\wedge,\neg\)
                           
!set name_menu1=Vocabulaire
!set list_menu1=et&#44; ou&#44; \(\overline{\phantom{x}}),$list_menu0

!if $lang=it
  !set name_menu1=Notazione
  !set list_menu1=e&#44; o&#44; \(\overline{\phantom{x}}),$list_menu0
  !goto menu
!endif

:menu
!default confparm1=1
$name_menu1
!reset wims_formselect_switch
!set wims_html_mode=li
<ul class="wims_nopuce inline">
!formradio confparm1 list 1,2 prompt $list_menu1
</ul>
