!header
!read Exindex

!if $lang iswordof it

  Questo modulo raccoglie al momento $exototal esercizi sui fondamenti della
  Logica Proposizionale, per studenti delle scuole superiori.
  <p>
  La versione originale è stata progettata come parte di un lavoro
  interdisciplinare in Francese e Matematica, per le seconde classi dei
  licei francesi.
  </p>

!goto end
!endif

Ce module regroupe pour l'instant $exototal exercices sur les fondements de la Logique Propositionnelle, pour des élèves du lycée. <BR/>Il a été conçu dans le cadre d'un travail interdisciplinaire
en Français et en Mathématiques, en classe de Seconde.

:end
!read oef/$module_language/intromenu.phtml
!tail
