!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur le calcul fractionnaire.
Toutes les explications des règles pour ces calculs sont présentes dans le cours en ligne
!href target=wims_internal module=H2/algebra/docfractions.fr DOC Écriture fractionnaire.

<p>
Ces calculs sont accessibles à des élèves de troisième, même si aujourd'hui (2019)
certains calculs sont abordés plutôt en seconde. On pourra également de manière profitable
faire d'autres exercices pour découvrir ou redécouvrir les nombres en écriture fractionnaire
je pense à un autre module écrit pour des cinquièmes, mais utilisable dès les classes de
fin de primaire
!href target=wims_internal module=H2/algebra/oefrationnel.fr OEF Nombres en écriture fractionnaire
$ mais aussi les modules :
!href target=wims_internal module=H2/algebra/oeffraction.fr OEF Fractions
$ ou
!href target=wims_internal module=E6/number/fractions.fr OEF Fractions pour des sixièmes (et fin primaire)
$ ou encore
!href target=wims_internal module=H2/algebra/oefcalcul.fr OEF Calculs
$ qui aide à faire quelques révisions.
</p>

<p>
Des petits problèmes simples sont également présents dans le module 
!href target=wims_internal module=H3/algebra/pbsolving.fr OEF problèmes solving.
$
</p>
<p>
Une particularité de ce module d'exercices est que les sources LaTeX sont accessibles
en passant par la version imprimable pour tous les exercices.
Cela permet de fabriquer rapidement une feuille de TD ou un sujet de devoir
à la maison en réalisant plusieurs sujets différents facilement.
</p>
!read related.phtml fraction
!read oef/intromenu.phtml

!tail
