#if defined TARGET_quadrilatere || defined TARGET_nompolygone
\author{Bernadette, Perrin-Riou}
\email{bernadette.m.riou@orange.fr}
#endif
#if defined TARGET_quadpart || defined TARGET_polyconvreg || defined TARGET_nbconst2 || defined TARGET_nbconst || defined TARGET_airepolygone
\author{Marie-Claude, David}
\email{Marie-Claude.David@universite-paris-saclay.fr}
#endif

\language{fr}
\range{-5..5}
\format{html}
