#if defined TARGET_quadrilatere
# define TITRE Quadrilatères
#endif
#if defined TARGET_quadpart
# define TITRE Quadrilatères particuliers 1
#endif
#if defined TARGET_polyconvreg
# define TITRE Polygone convexe régulier*
#endif
#if defined TARGET_nompolygone
# define TITRE Nommer un polygone
#endif
#if defined TARGET_nbconst2
# define TITRE Nombres et construction*
#endif
#if defined TARGET_nbconst
# define TITRE Nombres constructibles*
#endif
#if defined TARGET_airepolygone
# define TITRE Formules pour les aires
#endif
\title{TITRE}
