#if defined TARGET_additionA || defined TARGET_additionB || defined TARGET_additionC
#define TITLE Addition et fractions
#define TITLE_it Addizioni e frazioni
#define TITLE_es Adición y fracciones
#endif

#if defined TARGET_soustractionA || defined TARGET_soustractionB || defined TARGET_soustractionC
#define TITLE Soustraction et fractions
#define TITLE_it Sottrazioni e frazioni
#define TITLE_es Sustracción y fracciones
#endif

#if defined TARGET_mult1A || defined TARGET_mult1B || defined TARGET_mult1C || defined TARGET_mult2A || defined TARGET_mult2B || defined TARGET_mult2C || defined TARGET_div1A || defined TARGET_div1B || defined TARGET_div1C || defined TARGET_div2A || defined TARGET_div2B || defined TARGET_div2C
#define TITRE Multiplication et fractions
#define TITR2 Division et fractions
#define TITRE_it Moltiplicazioni e frazioni
#define TITR2_it Divisioni e frazioni
#define TITRE_es Multiplicación y fracciones
#define TITR2_es División y fracciones
#endif

#if defined TARGET_adddec
#define TITLE Addition et décimaux
#define TITLE_it Addizioni e decimali
#define TITLE_es Adición y decimales
#endif

#if defined TARGET_soudec
#define TITLE Soustraction et décimaux
#define TITLE_it Sottrazioni e decimali
#define TITLE_es Sustracción y decimales
#endif

#if defined TARGET_muldec1 || defined TARGET_muldec2
#define TITRE Multiplication et décimaux
#define TITRE_it Moltiplicazioni e decimali
#define TITRE_es Multiplicación y decimales
#endif 

#if defined TARGET_divdec1 || defined TARGET_divdec2
#define TITLE Division et décimaux
#define TITLE_it Divisioni e decimali
#define TITLE_es División y decimales
#endif
