n=$counter
# test voor 10^
AAA=!nospace $(reply$n)
t=!itemcnt $AAA
AAA=!lower $AAA
AAA=!replace [a-z\~!@#$%&_:;\(\)] by $empty in $AAA

sigstring_a=$empty
sigstring_g=$empty
check=$empty

!for p=1 to $t
    A=!item $p of $AAA
    !if ? isin $A
	check=!append item 0 to $check
    !else
	G=!item $p of $(answer$n)
	!if $A>999 or $A<0.001
	    !if 10^ notin $A and 10^ isin $G
		errortext=Je moet het getal $tt omzetten naar een wetenschappelijke schijfwijze...<br />Dus iets met <b>10^</b>
	        goback=1
		!exit
	    !endif
	!endif
	!ifval $A=$G
	    sigstring_a=!append word $A to $sigstring_a
	    sigstring_g=!append word $G to $sigstring_g
	    check=!append item 1 to $check
	!else
	    check=!append item -1 to $check
	!endif
    !endif
!next p
sigstring_a=!singlespace $sigstring_a
sigstring_g=!singlespace $sigstring_g
tot_a=!exec sigdigits $sigstring_a 
tot_g=!exec sigdigits $sigstring_g
#oud: sig1,dec1,sig2,dec2,c_base,exponent,ok
#real_significant,integer,decimal,c_base,exponent,ok
score=0
digit_errors=aantal significante cijfers,aantal cijfers voor de komma,aantal decimalen,het grondtal,de exponent
idx=1
your_rep=<ol>
!for p=1 to $t
    A=!item $p of $AAA
    G=!item $p of $(answer$n)
    A=!htmlmath $A
    G=!htmlmath $G
    !if $(check[$p])=1
	ca=!line $idx of $tot_a
	cg=!line $idx of $tot_g
	!increase idx
	corr=0
	tmp_rep=$empty
	!for r in 2,3,4,5
	# check integerpart,decimalpart,c_base,exponent
	    a1=!item $r of $ca
	    g1=!item $r of $cg
	    !if $a1 = $g1
		!increase corr
	    !else
		!if -1 isin $a1
		    tmp_rep=!append word <li><span style="color:red">nonsense : $A</span></li> to $tmp_rep
		    r=4
		    corr=0
		!else
		    tmp_rep=!append word <li>$(digit_errors[$r]) <span style="color:red"><b>$a1</b></span> &ne; <span style="color:green"><b>$g1</b></span> to $tmp_rep
		!endif
	    !endif
	!next r
	!if $corr=4
	    score=$[$score+1]
	    your_rep=!append word <li><span style="color:green">$A</span></li> to $your_rep
	!else
	    score=$[$score+$corr/4]
	    !if $corr<2
		k=red
	    !else
		k=orange
	    !endif
	    your_rep=!append word <li><span style="color:$k">$A</span>&ne;$G<ul>$tmp_rep</ul></li> to $your_rep
	!endif    
    !else
	!if $(check[$p])=-1
	    your_rep=!append word <li><span style="color:red">$A</span> &ne; $G</li> to $your_rep    
	!else
	    your_rep=!append word <li><span style="color:red">$dontknow</span></li> to $your_rep
	!endif
    !endif
!next p
your_rep=!append word </ol> to $your_rep
reply$n=$(reply$n)<br />$your_rep

maxscore=$[$maxscore*($score/$t)]

!if $maxscore>0.9
    remark$n=$OK
!else
    !if $maxscore >0.45
	remark$n=$BOK
    !else
	remark$n=$NOK
    !endif
!endif
    
modulescore=$[$modulescore+$maxscore]
    
!if $extra != $empty
    remark$n=!append line $extra to $(remark$n)
!endif
goback=0
!exit

!exit
