算术序列的一般公式是:
<p>
<ul>
    <li> 递推公式: u<sub>n+1</sub> = <em>r</em> &times; u<sub>n</sub></li>
    其中 u<sub>0</sub> = b</li> 
    <li> 通项公式: u<sub>n</sub> = b &times; <em>r</em><sup>n</sup> <br>
</ul>
一个例子:<br>
    已知某算术序列, 其中 
    U<sub>8</sub>=26
    及
    U<sub>9</sub>=29
    <br>
    计算此序列的项 U<sub>1</sub> 和 U<sub>3</sub> ...
    <br>你可以填入:<br>
    <textarea cols=20 rows=4 readonly>U1=5 
and
U3=11</textarea>
 <br>或者<br>
    <textarea cols=20 rows=4 readonly>5 and 11</textarea>
    
!if $subject isitemof 3,8
    <p>
    注意: 在检查你的回答时, 会 '区分大小写'
    <p>
如果要你给出<b>递推公式</b>:<br>
    <textarea cols=20 rows=4 readonly>U(n+1)=4*U(n) 
    with U(0)=5</textarea>
    <p>
    如果要求<b>通项公式</b>:
    <br>
    <textarea cols=20 rows=4 readonly>
    Un=21+4n
    或者:
    U_n=21+4*n
    </textarea> 
!endif
<hr>            
