!header
!read Exindex
!if $lang=en
This module contains $exototal exercises about the <b>limit calculus
of logarithm and exponential functions</b>.

The required and tested skills are:
<small><ul>
<li>limits of polynoms and quotient of polynoms, of functions ln and exp </li>
<li>computational properties of limits (theorems about the limits of sums, products, quotients, composed functions) ;</li>
<li>indeterminate forms;</li>
<li>compared growth properties between polynoms and the functions exp and ln.</li>
</ul>
<span style="color:blue">
The exercises are composed of several steps. An exercise goes on, even if
a false reply has been given at the precedent step. The good answers
are provided after each step, to enable further evaluations.
</span>
  !goto tail
!endif
!if $lang=nl
Deze module bevat op dit moment $exototal oefeningen over <b>het berekenen van limieten van logaritmische en exponentiele functies</b>

De vereiste en te testen vaardigheden:
<ul>
<li>Limieten van polynomen en hyperbolische functies</li>
<li>Limieten van exponentiele en logaritmische functies</li>
<li>Limieten van sommen, producten en quotienten van samengestelde functies en tussenvormen</li>
<li>
	Groeieigenschappen van polynomen, exponentiele en logaritmische functies</li>
</ul>
<span style="color:blue">
De oefeningen zijn opgebouwd uit diverse stappen.<br>
Ook al is er een foutief antwoord gegeven op een tussenstap, gaat de oefening gewoon verder.
[<em>de goede antwoorden van de tussenstappen worden na elke stap getoond.</em>]
</span>
  !goto tail
!endif
Ce module regroupe pour l'instant $exototal exercices sur les <b>calculs de limites
en classes de Terminale</b> (ES, S, STI).

Les compétences requises et testées portent sur :
<ul>
<li>les limites des fonctions de référence (polynômes, quotient de polynômes,
 exp, ln) aux bornes de leurs ensembles respectifs de définition ;</li>
<li>les règles opératoires sur les limites (théorèmes sur les limites de sommes, produits, quotients, composées) ;</li>
<li>la détection des formes indéterminées ;</li>
<li> les propriétés de croissances comparées entre fonctions
polynômes et fonctions exp ou ln.</li>
</ul>
<span style="color:blue">
Les exercices comportent plusieurs étapes successives. Un exercice continue à se dérouler même
si une réponse fausse a été donnée à l'étape précédente. Les réponses justes sont
indiquées après chaque étape, afin de pouvoir continuer correctement les calculs.
</span>
:tail
!read oef/$module_language/intromenu.phtml
!tail
