!! fichier de gestion de l'action conclure.

!! fichier de gestion des actions de combinaison lineaire
!goto $wims_read_parm
!exit

:question
Error de l'exercici. Em sap molt de greu però has d'abandonar i informar del
problema a l'autor.
!exit

:reponse
<font color=red>No has acabat pas la resolució de l'exercice.</font><br>
El resultat l'has de donar amb el format següent : <br>
!distribute items $listinc into tmp1,tmp2
!let tmp=\($tmp1=c) on \(c) és un nombre.,<table><tr><td rowspan=2> $(m_leftbrace2)</td><td>\($tmp1=c)</td></tr><tr><td>\($tmp2=d)</td></tr></table> on \(c) i \(d) són dos nombres, \($tmp1 symb c) on \(c) és un nombre i \(symb) un dels quatre símbols de desigualtat
<blocquote><p>
!item $mode of $tmp
</p></blocquote>
  Els resultats s'han de simplificar el màxim possible.<br>
!href cmd=resume&status=1 tornar
   al menú general.
!exit

:analyse
!distribute items $listinc into tmp1,tmp2
tmp3=!line 1 of $(sys$nbetape)
!distribute items $tmp3 into tmp3,tmp4,tmp5
!if $tmp5=$tmp1 and $mode=1
 tmp=$tmp5
 tmp5=$tmp3
 tmp3=$tmp
!endif
!if $tmp3!=$tmp1 
   !exit
!endif
i=0
replygood0=0
test=$empty
reply0=$tmp5
!read anstype/numeric
!if NaN isin $test
   !exit
!endif
tmp6=!exec maxima $tmp5;
!if $tmp5 notsametext $tmp6
   !exit
!endif
!if $mode=2
   tmp3=!line 2 of $(sys$nbetape)
   !distribute items $tmp3 into tmp3,tmp4,tmp5
   !if $tmp3!=$tmp2 
      !exit
   !endif
   i=0
   replygood0=0
   test=$empty
   reply0=$tmp5
   !read anstype/numeric
   !if NaN isin $test
      !exit
   !endif
   tmp6=!exec maxima $tmp5;
   !if $tmp5 notsametext $tmp6
      !exit
   !endif
!endif
status=5
!exit