!! pour echanger deux equations d'un systeme.

<u><b>Intercanviar les dues equacions :</b></u>
!goto $wims_read_parm
!exit

:question
!form reply
Clica sobre el botó "Canviar" per canviar de lloc les dues equacions del sistema o sobre l'enllaç "tornar" per tornar al menú de les accions. 
<input type=hidden name=status value=3>
<center><input type=submit value="Canviar"></center>
</form>
!exit

:reponse

!exit

:analyse
!! ------------- calcul du nouveau syst?e
tmp1=!line 1 of $(sys$nbetape)
tmp2=!line 2 of $(sys$nbetape)
sys$[$nbetape+1]=!append line $tmp2 to $(sys$[$nbetape+1])
sys$[$nbetape+1]=!append line $tmp1 to $(sys$[$nbetape+1])
comment$[$nbetape+1]=He intercanviat les dues equacions del sistema.
!increase nbetape
status=1
evitecalc=0
!exit
