!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes


<tr><th>Type de suites proposées</th>
<td>
!set wims_html_mode=li
<ul>
!formcheckbox confparm1 list A,G,X prompt suites arithmétiques, suites géométriques, autres suites
</ul>

</td>
</tr>
<tr><th>Mode de définition des suites proposées</th>
<td>
!set wims_html_mode=li
<ul>
!formcheckbox confparm2 list T,R,S prompt définies par le terme général, définies par une relation de récurrence, définies par leur dénomination ou une situation concrète
</ul>
</td>
</tr>
