!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes

!!<tr><td><strong>...</strong></td>
!!<td>
!! !formradio confparm1 from 1 to 3
!!</td>
!!</tr>
<tr><td>
Ce paramétrage s'applique uniquement à l'exercice "Dérivée(s) de polynôme(s)"

<div class="formHelp">
Si plusieurs calculs de dérivées sont demandés, les degrés des polynômes à dériver correspondront aux différentes cases cochées (s'il y en a plusieurs).<br \>
Le nom de la variable sera le même pour toutes les fonctions à dériver, et aléatoire entre toutes les possibilités. <br \>Les noms de variables autres que \(x \) ou \(t \) doivent être constitués d'une seule lettre, minuscule ou majuscule. Les écrire dans la case "autre(s)" en les séparant par une virgule.
</div>
</td></tr>
<tr><th>Nombre de dérivées à calculer</th>
<td>
!set wims_html_mode=li
<ul>
!formradio confparm1 list 1,2,3,4,5 prompt 1,2,3,4,5
</ul>
</td>
</tr>
<tr><th>Degré des polynômes</th>
<td>
!set wims_html_mode=li
<ul>
!formcheckbox confparm2 list 1,2,3,4,5  prompt 1,2,3,4,5
</ul>
</td>
</tr>
<tr><th>Nom de la variable</th>
<td>
!set wims_html_mode=li
<ul>
!formcheckbox confparm3 list x,t, prompt \(x \),\(t \)
<li>autre(s) : <input size="5" name="confparm4""></li>
</ul>
</td>
</tr>
