!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes

!! !set introhook_tableless=yes
!! !set wims_html_mode=li
!! Text ....
!!<ul>
!! !formradio confparm1 from 1 to 3
!!</ul>

!set menu_list=5,10,20,50,80,100

!default confparm1=20
!default confparm2=1
!default confparm3=1
!set introhook_tableless=yes

!if $lang_choice=en or $lang=en
  !set intro_desc1=Number of games
  !set intro_desc2=Show game log (max 50 games)
  !set intro_desc3=Print verbose instruction when available
  !goto hook
!endif
!if $lang_choice=fr or $lang=fr
  !set intro_desc1=Nombre de jeux
  !set intro_desc2=Montrer les logs des jeux (max 50 jeux)
  !set intro_desc3=Afficher des instructions détaillées lorsqu'elles sont disponibles
  !goto hook
!endif

!set intro_desc1=Numero di partite
!set intro_desc2=Mostra il riepilogo delle partite giocate (massimo 50 partite)
!set intro_desc3=Inserisci istruzioni esplicite se disponibili

:hook
<ul>
<li>
$intro_desc1
<ul>
!formradio confparm1 list $menu_list prompt $menu_list
</ul>
</li>
<li>
$intro_desc2
<ul>
!formradio confparm2 list 1,0 prompt $wims_name_yes,$wims_name_no
</ul>
</li>
<li>
$intro_desc3
<ul>
!formradio confparm3 list 1,0 prompt $wims_name_yes,$wims_name_no
</ul>
</li>
</ul>
