#if defined TARGET_calcexp
# define TITRE Limite de u(x)*exp(kx)
#endif
#if defined TARGET_calcln
# define TITRE Limite de u(x)*ln(kx)
#endif
#if defined TARGET_compln
# define TITRE Limite de k.ln(ax+b) ou k/ln(ax+b)
#endif
#if defined TARGET_compoexp
# define TITRE Limite de k.exp(ax+b) ou k/exp(ax+b)
#endif
#if defined TARGET_croisscomp
# define TITRE Croissance comparée : limites de base
#endif
#if defined TARGET_indeterminateForm
# define TITRE Formes indéterminées ou non avec ln ou exp
#endif
#if defined TARGET_indformwithexp
# define TITRE Formes indéterminées ou non avec exponentielle
#endif
#if defined TARGET_indformwithln
# define TITRE Formes indéterminées ou non avec logarithme
#endif
#if defined TARGET_qcmref
# define TITRE Limites de référence (QUIZZ)
#endif
