#if defined TARGET_calcexp
# define TITRE_nl De limiet van u(x)*exp(kx)
#endif
#if defined TARGET_calcln
# define TITRE_nl De limiet van u(x)*ln(kx)
#endif
#if defined TARGET_compln
# define TITRE_nl De limiet van k*ln(ax+b) of k/ln(ax+b)
#endif
#if defined TARGET_compoexp
# define TITRE_nl De limiet van k*exp(ax+b) of k/exp(ax+b)
#endif
#if defined TARGET_croisscomp
# define TITRE_nl Stijgen en dalen : basis eigenschappen
#endif
#if defined TARGET_indeterminateForm
# define TITRE_nl Onbepaalde vorm met ln of exp
#endif
#if defined TARGET_indformwithexp
# define TITRE_nl Formes indéterminées ou non avec exponentielle
#endif
#if defined TARGET_indformwithln
# define TITRE_nl Formes indéterminées ou non avec logarithme
#endif
#if defined TARGET_qcmref
# define TITRE_nl Limieten [basis]
#endif
