#if defined TARGET_calcexp
# define  TITRE_en Limit of u(x)*exp(kx)
#endif
#if defined TARGET_calcln
# define  TITRE_en Limit of u(x)*ln(kx)
#endif
#if defined TARGET_compln
# define  TITRE_en Limit of k.ln(ax+b) ou k/ln(ax+b)
#endif
#if defined TARGET_compoexp
# define  TITRE_en Limit of k.exp(ax+b) ou k/exp(ax+b)
#endif
#if defined TARGET_croisscomp
# define  TITRE_en Compared growth : basic properties
#endif
#if defined TARGET_indeterminateForm
# define  TITRE_en Indeterminate forms with ln or exp
#endif
#if defined TARGET_indformwithexp
# define  TITRE_en Indeterminate forms with ln
#endif
#if defined TARGET_indformwithln
# define  TITRE_en Indeterminate forms with ln
#endif
#if defined TARGET_qcmref
# define  TITRE_en Basic limits (QUIZZ)
#endif
