!header
!read Exindex
Deze module bevat op dit moment $exototal oefeningen over <b>het berekenen van limieten van logaritmische en exponentiele functies</b>

De vereiste en te testen vaardigheden:
<small>
<ul>
    <li>
	Limieten van polynomen en hyperbolische functies
    </li>
    <li>
	Limieten van exponentiele en logaritmische functies
    </li>
    <li>
	Limieten van sommen, producten en quotienten van samengestelde functies en tussenvormen
    </li>
    <li> 
	Groeieigenschappen van polynomen, exponentiele en logaritmische functies
    </li>
</ul>
<font color=blue>
De oefeningen zijn opgebouwd uit diverse stappen.<br>
Ook al is er een foutief antwoord gegeven op een tussenstap, gaat de oefening gewoon verder.
[<em>de goede antwoorden van de tussenstappen worden na elke stap getoond.</em>]
</font>
<marquee><a href="mailto:royer.veronique@orange.fr"><font color=red><b>NIEUWE OEFENING...SVP FOUTEN MELDEN</b></font></a></marquee>
</small>
!read oef/$module_language/intromenu.phtml
!tail
