!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices d'entrainement et activités concrètes sur les probabilités en Lycée professionnel. Ce module permettra de travailler les connaissances suivantes
<ul>
  <li>construction et lecture d'un tableau à double entrée</li>
  <li>construction d'un arbre</li>
  <li>réunion et intersection d'évènement</li>    
  <li>calcul et utilisation de l'intervalle de fluctuation</li>  
</ul>
  
!read oef/intromenu.phtml
!tail
