!header
!read Exindex
<p>Les exercices de ce module demandent de lire ou de placer des angles sur le cercle trigonométrique.
</p>
<p>Pas de paramétrage spécifique pour les exercices dont le titre commence par "Enroulement". 
Ces exercices sont formulés pour des évèles qui utilisent exclusivement la notion d'enroulement 
de la droite réelle sur le cercle trigonométrique.</p>

!read oef/intromenu.phtml
!tail
