!set introhook_exists=yes
<tr>
<th><b>Angles proposés : </b></th>
<td>
<ul class="wims_nopuce">
<li>
!set wims_ref_id=confparm11
!formcheckbox confparm1 list 1 prompt \(\pm \pi,\pm \frac{\pi}{2},\pm \frac{3 \pi}{2}\)
</li><li>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 2 prompt \(\pm \frac{\pi}{4},\pm \frac{3\pi}{4},\pm \frac{5\pi}{4},\pm \frac{7\pi}{4}\)
</li><li>
!set wims_ref_id=confparm13
!formcheckbox confparm1 list 3 prompt \(\pm \frac{\pi}{3},\pm \frac{2\pi}{3},\pm \frac{4\pi}{3},\pm \frac{5\pi}{3}\)
</li><li>
!set wims_ref_id=confparm14
!formcheckbox confparm1 list 4 prompt \(\pm \frac{\pi}{6},\pm \frac{5\pi}{6},\pm \frac{7\pi}{6},\pm \frac{11\pi}{6}\)
</li>
</ul>
</td>
</tr>
<tr><th>Fond : </th>
<td>
!formradio confparm2 list 1,2 prompt quadrillage , angles
</td>
</tr>
<tr>
<th>
<br class="spacer" /><b>Notation des angles : </b></th>
<td>
!formradio confparm3 list 1,2 prompt \((\overrightarrow{OA},\overrightarrow{OB})\),\(\widehat{AOB}\)
</td>
</tr>

