\css{<style>
table.lceb th {background-color:lightgreen; padding:10px;width:60px;border:3px solid;}
table.lceb td {border:3px solid;padding:10px;font-size:130%;}
td.goal {border:3px solid;padding:10px;background-color:#CCFFCC;
  font-weight:bold;font-size:130%;}
td.answer {border:3px solid;padding:10px;background-color:orange;}
pre { left:100px; right:100px; width:200px; padding:20px; text-align:left; border:1px solid }
.wims_oef_input {font-size:120%;}
</style>
}
