#if defined TARGET_module
# define TITRE_nl Modulus
#endif
#if defined TARGET_reim
# define TITRE_nl Reël en Imaginair
#endif
#if defined TARGET_arggiven
# define TITRE_nl Argument III
#endif
#if defined TARGET_conj
# define TITRE_nl Complex toegevoegde
#endif
#if defined TARGET_arg
# define TITRE_nl Argument I
#endif
#if defined TARGET_arg0
# define TITRE_nl Argument (T)
#endif
#if defined TARGET_argask
# define TITRE_nl Argument II
#endif
