#if defined TARGET_module
# define TITRE_fr Module
#endif
#if defined TARGET_reim
# define TITRE_fr Re et Im
#endif
#if defined TARGET_arggiven
# define TITRE_fr Argument donné
#endif
#if defined TARGET_conj
# define TITRE_fr Conjugué
#endif
#if defined TARGET_arg
# define TITRE_fr Argument
#endif
#if defined TARGET_arg0
# define TITRE_fr Argument (T)
#endif
#if defined TARGET_argask
# define TITRE_fr Argument demandé
#endif
