#if defined TARGET_module
# define TITRE Module
#endif
#if defined TARGET_reim
# define TITRE Re and Im
#endif
#if defined TARGET_arggiven
# define TITRE Given argument
#endif
#if defined TARGET_conj
# define TITRE Conjuguate
#endif
#if defined TARGET_arg
# define TITRE Argument
#endif
#if defined TARGET_arg0
# define TITRE Argument (T)
#endif
#if defined TARGET_argask
# define TITRE Asked argument
#endif
