!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.

!! !set introhook_tableless=yes
!! !set wims_html_mode=li
!! Text ....
!!<ul>
!! !formradio confparm1 from 1 to 3
!!</ul>



!set introhook_exists=yes
!set confparm1=1
<tr><th><strong>Sélectionner un thème pour l'éditeur Python :</strong></th>
</tr>
<tr><td>
!formradio confparm1 list 1,2,3 prompt thème classique,thème bleu,thème matrix
</td>
</tr>
