\matrix{data=
ag,Algeria
ao,Angola
bc,Botswana
bn,Benin
by,Burundi
cd,Chad
cm,Cameroon
cn,Comoros
ct,Central African Republic | Central Africa
cv,Cape Verde
dj,Djibouti
eg,Egypt
ek,Equatorial Guinea
er,Eritrea
et,Ethiopia
ga,Gambia
gb,Gabon
gh,Ghana
gv,Guinea
iv,Cote d&#39;Ivoire
ke,Kenya
li,Liberia
lt,Lesotho
ly,Libya
ma,Madagascar
mi,Malawi
ml,Mali
mo,Morocco
mp,Mauritius
mr,Mauritania
mz,Mozambique
ng,Niger
ni,Nigeria
pu,Guinea-Bissau
rw,Rwanda
se,Seychelles
sf,South Africa
sg,Senegal
sl,Sierra Leone
so,Somalia
su,Sudan
to,Togo
ts,Tunisia
tz,Tanzania
ug,Uganda
uv,Burkina Faso
wa,Namibia
wz,Swaziland
za,Zambia
zi,Zimbabwe
}
