\matrix{data=
ar,Argentina
bb,Barbados
bf,Bahamas
bh,Belize
bl,Bolivia
br,Brazil
ca,Canada
ci,Chile
co,Colombia
cs,Costa Rica
cu,Cuba
do,Dominica
dr,Dominican Republic
ec,Ecuador
es,El Salvador
gj,Grenada
gt,Guatemala
gy,Guyana
ha,Haiti
ho,Honduras
jm,Jamaica
mx,Mexico
ns,Suriname
nu,Nicaragua
pa,Paraguay
pe,Peru
pm,Panama
sc,Saint Kitts and Nevis
st,Saint Lucia
td,Trinidad and Tobago
us,United States | United States of America | US | USA
uy,Uruguay
ve,Venezuela
}
