\matrix{data=
af,Afghanistan
aj,Azerbaijan
am,Armenia
ba,Bahrain
bg,Bangladesh
bm,Burma
bt,Bhutan
bx,Brunei
cb,Cambodia
ce,Sri Lanka
ch,China
cy,Cyprus
id,Indonesia
in,India
ir,Iran
is,Israel
iz,Iraq
ja,Japan
jo,Jordan
kg,Kyrgyzstan
kn,North Korea
ks,South Korea
ku,Kuwait
kz,Kazakhstan
la,Laos
le,Lebanon
mg,Mongolia
mu,Oman
mv,Maldives
my,Malaysia
np,Nepal
pk,Pakistan
qa,Qatar
rp,Philippines
sa,Saudi Arabia
sn,Singapore
sy,Syria
tc,United Arab Emirates
th,Thailand
ti,Tajikistan
tu,Turkey
tx,Turkmenistan
uz,Uzbekistan
vm,Vietnam
ym,Yemen
}
