\matrix{data=
ag,Algeria,\af
ar,Argentina,\am
as,Australia,\oc
bg,Bangladesh,\as
br,Brazil,\am
ca,Canada,\am
ch,China,\as
eg,Egypt,\af
et,Ethiopia,\af
fr,France,\eu
gm,Germany,\eu
id,Indonesia,\as
in,India,\as
ir,Iran,\as
it,Italy,\eu
ja,Japan,\as
ks,South Korea,\as
kz,Kazakhstan,\as
ly,Libya,\af
mg,Mongolia,\as
mx,Mexico,\am
ni,Nigeria,\af
pk,Pakistan,\as
rp,Philippines,\as
rs,Russia,\eu
sa,Saudi Arabia,\as
su,Sudan,\af
tu,Turkey,\as
uk,United Kingdom,\eu
up,Ukraine,\eu
us,United States| United States of America | US | USA,\am
vm,Vietnam,\as
}

