#if defined TARGET_arret
# define TITRE_nl Afstand tot stilstand
#endif
#if defined TARGET_impot
# define TITRE_nl Impôt célibataire/marié
#endif
#if defined TARGET_trajet
# define TITRE_nl Traject met de auto
#endif
#if defined TARGET_vitesse
# define TITRE_nl Snelheids berekening
#endif
#if defined TARGET_vitesse2
# define TITRE_nl Snelheid en teller
#endif
#if defined TARGET_vitesse12
# define TITRE_nl Snelheid
#endif
