#if defined TARGET_symax7
#define TITLE Symétrie axiale 7
#endif
#if defined TARGET_symcen7
#define TITLE Symétrie centrale 7
#endif
#if defined TARGET_trans7
#define TITLE Translation 7
#endif
#if defined TARGET_rota7
#define TITLE Rotation 7
#endif
#if defined TARGET_associerapportsitu
#define TITLE Associer rapport homothétie à la situation correspondante
#endif
#if defined TARGET_symax2
#define TITLE Symétrie axiale 2
#endif
#if defined TARGET_symcen2
#define TITLE Symétrie centrale 2
#endif
#if defined TARGET_rota2
#define TITLE Rotation 2
#endif
#if defined TARGET_rota2bis
#define TITLE Rotation 2 bis
#endif
#if defined TARGET_symax1
#define TITLE Symétrie axiale 1
#endif
#if defined TARGET_symcen1
#define TITLE Symétrie centrale 1
#endif
#if defined TARGET_rota1
#define TITLE Rotation 1
#endif
#if defined TARGET_trans1
#define TITLE Translation 1
#endif
#if defined TARGET_symax3
#define TITLE Symétrie axiale 3
#endif
#if defined TARGET_symcen3
#define TITLE Symétrie centrale 3
#endif
#if defined TARGET_trans2
#define TITLE Translation 2
#endif
#if defined TARGET_trans3im
#define TITLE Image d'un point par translation
#endif
#if defined TARGET_trans3ant
#define TITLE Antécédent d'un point par translation
#endif
#if defined TARGET_symax4
#define TITLE Symétrie axiale 4
#endif
#if defined TARGET_symcen4
#define TITLE Symétrie centrale 4
#endif
#if defined TARGET_rota4
#define TITLE Rotation 4
#endif
#if defined TARGET_symax6
#define TITLE Symétrie axiale 6
#endif
#if defined TARGET_symcen6
#define TITLE Symétrie centrale 6
#endif
#if defined TARGET_rota6
#define TITLE Rotation 6
#endif
#if defined TARGET_homo2
#define TITLE Homothétie 2
#endif
#if defined TARGET_homo1
#define TITLE Homothétie 1
#endif
#if defined TARGET_homo3
#define TITLE Homothétie 3
#endif
#if defined TARGET_symax5
#define TITLE Symétrie axiale 5
#endif
#if defined TARGET_symcen5
#define TITLE Symétrie centrale 5
#endif
#if defined TARGET_association
#define TITLE Propriétés des transformations
#endif
