#if defined TARGET_rota2 || defined TARGET_symax2 || defined TARGET_symcen2 || defined TARGET_symax3 || defined TARGET_symcen3
\text{name_answer=Il modulo}
#endif

#if defined TARGET_symax7 || defined TARGET_symcen7 || defined TARGET_rota2 || defined TARGET_symax2 || defined TARGET_symcen2 || defined TARGET_rota2bis || defined TARGET_symax1 || defined TARGET_symcen1 || defined TARGET_symax5 || defined TARGET_symax3 || defined TARGET_symcen3 || defined TARGET_symcen5
\text{name_conclusion=Conclusione}
#endif
#if defined TARGET_symax7
\text{name_instruction=Applicando la simmetria di asse}
\text{name_onmeme=si sovrappone a se stesso}
\text{name_solution=Applicando la riflessione lungo la retta}
#endif
#if defined TARGET_symcen7
\text{name_instruction=Applicando la simmetria di centro}
\text{name_solution=Applicando la rotazione di 180° attorno al punto}
#endif
#if defined TARGET_trans7
\text{name_instruction=Applicando la traslazione che trasforma}
\text{name_en=in}
#endif
#if defined TARGET_rota7
\text{sens=in senso antiorario, in senso orario}
#endif
#if defined TARGET_rota4
\text{name_sense=in senso antiorario, in senso orario}
#endif
#if defined TARGET_rota7
\text{name_instruction=Applicando la rotazione di centro \(A\) e angolo \(120^{\circ}\) in senso}
\text{name_feedback=Hai sbagliato il senso di rotazione}
#endif
#if defined TARGET_symax7 || defined TARGET_symcen7
\text{name_onhexa=si sovrappone all'esagono}
\text{name_imageof=l'immagine dell'esagono}
\text{name_is=è l'esagono}
\text{name_solhexagone=l'esagono}
#endif
#if defined TARGET_symax7 || defined TARGET_rota7 || defined TARGET_trans7 || defined TARGET_symcen7
\text{name_hexagone=È l'esagono}
\text{name_statement=La figura qui sotto è costituita da 10 esagoni regolari numerati da 1 a 10.
<p>L'esagono 5 è indicato con le lettere ABCDEF.</p>
 I è il punto medio del segmento [AB].}
\text{name_question=Qual è l'immagine dell'esagono}
\text{name_alt=esagono}
#endif
#if defined TARGET_symax2
\text{name_instruction=Qual è il simmetrico del modulo,tramite la,riflessione rispetto alla retta, alla retta}
\text{name_transf=simmetria di asse}
#endif
#if defined TARGET_symcen2
note for translators: keep commas
\text{name_instruction=Qual è il simmetrico del modulo,tramite la,rotazione di 180° attorno al punto, al punto}
\text{name_transf=simmetria centrale di centro}
#endif
#if defined TARGET_rota2 || defined TARGET_rota2bis || defined TARGET_rota1
\text{name_sens_list=in senso orario,in senso antiorario}
#endif
#if defined TARGET_rota2
note for translators: keep commas
\text{name_instruction=Qual è l'immagine del modulo,tramite la rotazione di centro, di angolo}
note for translators: keep commas
\text{name_saut_list=salto,salti}
\text{name_feedback=Attenzione, hai sbagliato il senso di rotazione.}
#endif
#if defined TARGET_rota2bis || defined TARGET_rota1
note for translators: keep commas
\text{name_saut_list=salto,salti}
#endif
#if defined TARGET_rota2bis
note for translators: keep commas
\text{name_instruction=Qual è l'angolo della rotazione di centro, che trasforma il 
modulo,in,Non dimenticare di specificare l'unità di misura nella risposta}
\text{name_answer=Angolo}
\text{name_condition1=L'angolo è corretto}
\text{name_condition2=Hai specificato i gradi}
\text{name_and=e}
note for translators: keep commas
\text{name_feedback=Attenzione,hai trasformato correttamente il modulo, in, ma ti sei
sbagliato sul senso di rotazione,non hai specificato i gradi dell'angolo,non hai utilizzato l'angolo
corretto e hai dimenticato di specificare i gradi, hai l'angolo corretto ma hai dimenticato 
di specificare i gradi}
#endif
#if defined TARGET_symax2 || defined TARGET_symcen2 || defined TARGET_rota2 || defined TARGET_rota2bis
\text{name_statement=Si consideri la figura seguente composta da venti moduli numerati da 1 a 20 nella quale l'angolo \(\widehat{AOB}\) soddisfa la condizione}
#endif

#if defined TARGET_symax1
note for translators: keep commas
\text{name_instruction=Qual è il simmetrico rispetto alla retta,del quadrato}
\text{name_onmeme=a se stesso. È il proprio simmetrico.}
\text{name_oncarre=al quadrato}
#endif
#if defined TARGET_symcen1
note for translators: keep commas
\text{name_instruction=Qual è il simmetrico rispetto al punto,del quadrato}
#endif
#if defined TARGET_rota1
note for translators: keep commas
\text{name_instruction=Qual è l'immagine del quadrato,tramite la rotazione di centro,che trasforma il quadrato,nel quadrato}
#endif
#if defined TARGET_symax1 || defined TARGET_symcen1 || defined TARGET_rota1
\text{name_statement=Si consideri la figura seguente composta da quadrati identici numerati da 1 a 8 e nella quale gli angoli tra due quadrati contigui sono uguali a due a due.
<p>Il punto \(O\) è il punto medio del segmento <span class="nowrap">\([DH]\).</span></p>}
\text{name_carre=È il quadrato}
#endif
#if defined TARGET_symax5
note for translators: keep commas
\text{name_instruction=Qual è l'immagine dell'aquilone,tramite la simmetria di asse}
#endif
#if defined TARGET_symcen5
\text{name_instruction=Qual è l'immagine dell'aquilone,tramite la simmetria di centro}
#endif
#if defined TARGET_symax5 || defined TARGET_symcen5
\text{name_statement1=La figura qui sotto è un pavimento costituito da aquiloni identici.}
note for translators: keep commas
\text{name_statement2=Il quadrilatero, così formato è un rombo di centro}
\text{name_answer=L'aquilone}
#endif

#if defined TARGET_symax6
note for translators: keep commas
\text{name_instruction=Qual è l'immagine del segmento,tramite la simmetria di asse}
note for translators: keep commas
\text{name_label=tramite la simmetria di asse,l'immagine del segmento,è il segmento}
#endif
#if defined TARGET_symcen6
note for translators: keep commas
\text{name_instruction=Qual è il simmetrico rispetto al punto,del quadrilatero}
\text{name_answer=Il quadrilatero}
#endif
#if defined TARGET_rota6
\text{name_instruction=Qual è l'immagine del triangolo, tramite la rotazione di centro O che trasforma il triangolo, nel triangolo}
#endif
#if defined TARGET_symax6 || defined TARGET_symcen6 || defined TARGET_rota6
\text{name_statement=Si consideri l'esagono ABCDEF di centro O rappresentato qui sotto.}
#endif

#if defined TARGET_associerapportsitu
\text{name_liste=un ingrandimento senza inversione, una riduzione senza inversione, una riduzione con inversione, un ingrandimento con inversione}
\text{name_situation=situazione}
\text{name_ssituation=Situazione}
\text{name_sol1=quindi l'omotetia è un ingrandimento senza inversione (\name_situation 1)}
\text{name_sol2=quindi l'omotetia è una riduzione senza inversione (\name_situation 2)}
\text{name_sol3=quindi l'omotetia è una riduzione con inversione (\name_situation 3)}
\text{name_sol4=quindi l'omotetia è un ingrandimento con inversione (\name_situation 4)}
\text{name_statement1=\(k\) indica un numero non nullo}
\text{name_statement2=Si consideri una figura di partenza (in blu) e la sua immagine (in rosso) tramite l'omotetia di centro \(O\) e rapporto \(k\) illustrata nelle quattro situazioni qui sotto in funzione dei valori di <span class="nowrap">\(k\).</span>}
\text{name_statement3=In base al valore del rapporto dell'omotetia completa le frasi e scegli la situazione corretta}
note for translators: keep commas
\text{name_question=Un'omotetia di rapporto,è,Questo è illustrato dalla}
\text{name_alt=2 triangoli omotetici}
#endif

#if defined TARGET_trans1
note for translators: keep commas
\text{name_statement=Si consideri il parallelepipedo rettangolo seguente,Qual è l'immagine del punto,tramite la traslazione che trasforma,in}
note for translators: keep commas
\text{name_solution=Il quadrilatero,forma un parallelogramma,La traslazione che trasforma,in,trasforma il punto}
#endif

#if defined TARGET_symax3
note for translators: keep commas
\text{name_instruction=Qual è l'immagine del modulo,tramite la simmetria di asse}
#endif

#if defined TARGET_symcen3
note for translators: keep commas
\text{name_instruction=Qual è l'immagine del modulo,tramite la simmetria di centro}
#endif

#if defined TARGET_symax3 || defined TARGET_symcen3
\text{name_statement=Si consideri il pavimento seguente costituito da moduli identici}
\text{name_alt=pavimento}
#endif

#if defined TARGET_trans2
\text{name_into=nel punto}
\text{name_alt=Punti situati su una rete punteggiata a maglia triangolare}
note for translators: keep commas
\text{name_statement=Completa le frasi seguenti,Applicando la traslazione che trasforma il punto,l'immagine del punto,è}
#endif

#if defined TARGET_trans3im || defined TARGET_trans3ant
\text{name_statement1=Si considerino quattro punti}
\text{name_and=e}
\text{name_mapsto=in}
\text{name_yourreply=La tua risposta}
\text{name_condition=Punto posizionato correttamente?}
#endif

#if defined TARGET_trans3im
note for translators: keep commas
\text{name_statement2=Operando sugli oggenti in figura,sposta il punto,affinché diventi l'immagine del punto,tramite la traslazione che trasforma}
#endif

#if defined TARGET_trans3ant
\text{name_statement2=Operando sugli oggenti in figura,trascina e sposta il punto,affinché diventi la preimmagine del punto, mediante la traslazione che trasforma}
#endif

#if defined TARGET_symax4 || defined TARGET_symcen4 || defined TARGET_rota4
\text{name_statement1=La figura qui sotto è un pavimento costituito a partire dal triangolo BEJ che è isoscele e rettangolo in J}
\text{name_alt=triangoli}
#endif
#if defined TARGET_symax4 || defined TARGET_symcen4 || defined TARGET_rota6
\text{name_answer=Il triangolo}
#endif

#if defined TARGET_symax4
note for translators: keep commas
\text{name_statement2=Qual è l'immagine del triangolo,tramite la simmetria di asse}
#endif
#if defined TARGET_symcen4
note for translators: keep commas
\text{name_statement2=Qual è l'immagine del triangolo,tramite la simmetria di centro}
#endif
#if defined TARGET_rota4
note for translators: keep commas
\text{name_statement2=Qual è l'immagine del triangolo,tramite la rotazione di centro,e angolo,in senso}
\text{name_feedback=Attenzione,ti sei sbagliato sul senso della rotazione}
#endif

#if defined TARGET_homo1 || defined TARGET_homo2 || defined TARGET_homo3
\text{name_alt=triangoli omotetici}
#endif
#if defined TARGET_homo1
\text{name_figure=Triangolo}
\text{name_homot=omotetia di rapporto}
\text{name_statement1=I triangoli rosa sono le immagini del triangolo verde \(ABC\) tramite alcune omotetie di centro D.}
\text{name_statement2=Associare a ciascuno dei triangoli rosa l'omotetia che gli corrisponde.}
#endif
#if defined TARGET_homo3
\text{name_statement1=Applicando alla figura A delle omotetie di centro O e di rapporti diversi si sono ottenute altre figure.}
\text{name_instruction=Esprimere il rapporto cercato sotto forma di un numero intero o di una frazione irriducibile.}
note for translators: keep commas
\text{name_quest1=Qual è il rapporto dell'omotetia con centro O che permette di ottenere la figura, dalla figura A}
note for translators: keep commas
\text{name_quest2=Applichiamo l'omotetia con centro O e rapporto, alla figura, Otteniamo così la figura}

#endif

#if defined TARGET_homo2
note for translators: keep commas
\text{name_sol_list=Il rapporto,è negativo e inferiore a,è positivo e superiore a,è positivo e inferiore a,è negativo e superiore a,Questo corrisponde a}
\text{name_types_list=si tratta di un ingrandimento con inversione,si tratta di un ingrandimento senza inversione,si tratta di una riduzione senza inversione,si tratta di una riduzione con inversione}
\text{name_statement1=Cliccare sulla figura che corrisponde all'affermazione}
note for translators: keep commas
\text{name_statement2=Il triangolo,è l'immagine del triangolo,tramite l'omotetia di centro,e di rapporto}
\text{name_color_list=arancione,blu}
#endif

#if defined TARGET_association
\matrix{name_list=simmetria centrale,effettuare un mezzogiro attorno a un punto
simmetria assiale, piegare lungo una retta
traslazione, scorrere senza rotazione&#44; né inversione&#44; né deformazione
rotazione, far girare attorno a un punto
omotetia, ingrandire o ridurre una figura}
\text{name_statement=Associare a ogni trasformazione la sua azione}
#endif

