#if defined TARGET_symax7
#define TITLE_it Simmetria assiale 7
#endif
#if defined TARGET_symcen7
#define TITLE_it Simmetria centrale 7
#endif
#if defined TARGET_trans7
#define TITLE_it Traslazione 7
#endif
#if defined TARGET_rota7
#define TITLE_it Rotazione 7
#endif
#if defined TARGET_associerapportsitu
#define TITLE_it Associare il rapporto di omotetia alla situazione corrispondente
#endif
#if defined TARGET_symax2
#define TITLE_it Simmetria assiale 2
#endif
#if defined TARGET_symcen2
#define TITLE_it Simmetria centrale 2
#endif
#if defined TARGET_rota2
#define TITLE_it Rotazione 2
#endif
#if defined TARGET_rota2bis
#define TITLE_it Rotazione 2 bis
#endif
#if defined TARGET_symax1
#define TITLE_it Simmetria assiale 1
#endif
#if defined TARGET_symcen1
#define TITLE_it Simmetria centrale 1
#endif
#if defined TARGET_rota1
#define TITLE_it Rotazione 1
#endif
#if defined TARGET_trans1
#define TITLE_it Traslazione 1
#endif
#if defined TARGET_symax3
#define TITLE_it Simmetria assiale 3
#endif
#if defined TARGET_symcen3
#define TITLE_it Simmetria centrale 3
#endif
#if defined TARGET_trans2
#define TITLE_it Traslazione 2
#endif
#if defined TARGET_trans3im
#define TITLE_it Immagine di un punto tramite una traslazione
#endif
#if defined TARGET_trans3ant
#define TITLE_it Preimmagine di un punto tramite una traslazione
#endif
#if defined TARGET_symax4
#define TITLE_it Simmetria assiale 4
#endif
#if defined TARGET_symcen4
#define TITLE_it Simmetria centrale 4
#endif
#if defined TARGET_rota4
#define TITLE_it Rotazione 4
#endif
#if defined TARGET_symax6
#define TITLE_it Simmetria assiale 6
#endif
#if defined TARGET_symcen6
#define TITLE_it Simmetria centrale 6
#endif
#if defined TARGET_rota6
#define TITLE_it Rotazione 6
#endif
#if defined TARGET_homo2
#define TITLE_it Omotetia 2
#endif
#if defined TARGET_homo1
#define TITLE_it Omotetia 1
#endif
#if defined TARGET_homo3
#define TITLE_it Omotetia 3
#endif
#if defined TARGET_symax5
#define TITLE_it Simmetria assiale 5
#endif
#if defined TARGET_symcen5
#define TITLE_it Simmetria centrale 5
#endif
#if defined TARGET_association
#define TITLE_it Proprietà delle trasformazioni
#endif
