#if defined TARGET_point1 
#define TITLE_CA Punt
#endif

#if defined TARGET_point2 
#define TITLE_CA Punto reanomenat
#endif

#if defined TARGET_ligne1 
#define TITLE_CA Recta
#endif

#if defined TARGET_ligne2 
#define TITLE_CA Segment
#endif 
 
#if defined TARGET_ligne3 
#define TITLE_CA Semirecta
#endif

#if defined TARGET_cercle1 
#define TITLE_CA Circumferencia (centre-punt)
#endif

#if defined TARGET_cercle2 
#define TITLE_CA Circumferencia (centre-radi)
#endif

#if defined TARGET_cercle3 
#define TITLE_CA Circumferencia (centre-diametre)
#endif

#if defined TARGET_cercle4 
#define TITLE_CA Circumferencia (tres punts)
#endif
 
#if defined TARGET_cercle5 
#define TITLE_CA Circumferencia (centre-radi) 2
#endif
