#if defined TARGET_point1 
#define TITLE Point
#endif

#if defined TARGET_point2 
#define TITLE Point renommé
#endif

#if defined TARGET_ligne1 
#define TITLE Droite
#endif

#if defined TARGET_ligne2 
#define TITLE Segment
#endif 
 
#if defined TARGET_ligne3 
#define TITLE Demi-droite
#endif

#if defined TARGET_cercle1 
#define TITLE Cercle (centre-point)
#endif

#if defined TARGET_cercle2 
#define TITLE Cercle (centre-rayon)
#endif

#if defined TARGET_cercle3 
#define TITLE Cercle (centre-diamètre)
#endif

#if defined TARGET_cercle4 
#define TITLE Cercle (trois points)
#endif
 
#if defined TARGET_cercle5 
#define TITLE Cercle (centre-rayon) 2
#endif
 
