#if defined TARGET_point1 
# define TITLE_EN Point
#endif

#if defined TARGET_point2 
# define TITLE_EN Point with name
#endif

#if defined TARGET_ligne1 
# define TITLE_EN Line
#endif

#if defined TARGET_ligne2 
# define TITLE_EN Segment
#endif 
 
#if defined TARGET_ligne3 
# define TITLE_EN Semiline
#endif

#if defined TARGET_cercle1 
# define TITLE_EN Circle (center-point)
#endif

#if defined TARGET_cercle2 
# define TITLE_EN Circle (center-radius)
#endif

#if defined TARGET_cercle3 
# define TITLE_EN Circle (center-diameter)
#endif

#if defined TARGET_cercle4 
# define TITLE_EN Circle (three points)
#endifi
 
#if defined TARGET_cercle5 
# define TITLE_EN Circle (center-radius) 2
#endif
