#if defined TARGET_point1 
#define TITLE_IT Punto
#endif

#if defined TARGET_point2 
#define TITLE_IT Rinominare punto
#endif

#if defined TARGET_ligne1 
#define TITLE_IT Retta
#endif

#if defined TARGET_ligne2 
#define TITLE_IT Segmento
#endif 
 
#if defined TARGET_ligne3 
#define TITLE_IT Semiretta
#endif

#if defined TARGET_cercle1 
#define TITLE_IT Circonferenza (centro-punto)
#endif

#if defined TARGET_cercle2 
#define TITLE_IT Circonferenza (centro-raggio)
#endif

#if defined TARGET_cercle3 
#define TITLE_IT Circonferenza (centro-diametro)
#endif

#if defined TARGET_cercle4 
#define TITLE_IT Circonferenza (tre punti)
#endif
 
#if defined TARGET_cercle5 
#define TITLE_IT Circonferenza (centro-raggio) 2

#endif
