#if defined TARGET_2term0
# define TITRE 2 termes
#endif
#if defined TARGET_3term0
# define TITRE 3 termes
#endif
#if defined TARGET_3term1
# define TITRE 3 termes avec parenthèses
#endif
#if defined TARGET_4term0
# define TITRE 4 termes
#endif
#if defined TARGET_4term1
# define TITRE 4 termes 1 paire
#endif
#if defined TARGET_4term2
# define TITRE 4 termes 2 paires
#endif
#if defined TARGET_5term0
# define TITRE 5 termes
#endif
#if defined TARGET_5term1
# define TITRE 5 termes 1 pair
#endif
#if defined TARGET_5term2
# define TITRE 5 termes 2 paires
#endif
#if defined TARGET_5term3
# define TITRE 5 termes 3 paires
#endif
#if defined TARGET_6term0
# define TITRE 6 termes
#endif
#if defined TARGET_6term1
# define TITRE 6 termes 1 paire
#endif
#if defined TARGET_7term0
# define TITRE 7 termes
#endif
#if defined TARGET_8term0
# define TITRE 8 termes
#endif
