!header
!read Exindex
<a href="https://wimsedu.info/?page_id=5089" target="_blank">
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" title="Communauté MutuWIMS" style="float:right;margin-left:0.5em;margin-right:0.2em;"/></a>
Ce module regroupe pour l'instant $exototal exercices sur les vecteurs dans le plan repéré : calcul de coordonnées, de normes, de déterminants.
<br/>Et quelques applications : déterminer si deux droites sont parallèles, prouver l'alignement de points, trouver le quatrième sommet d'un parallélogramme.


<br />Elaboré avec la communauté <a href="https://wimsedu.info/?page_id=5089" target="_blank">MutuWIMS</a>
!read oef/intromenu.phtml
!tail
