#if defined TARGET_convertirp3
#define TITLE Convertir vers la base p 3
#define TITLE_it Convertire in base p 3
#endif
#if defined TARGET_paquet3
#define TITLE Reste d'un groupement
#define TITLE_it Resti di raggruppamenti
#endif
#if defined TARGET_paquet1
#define TITLE Nombre de paquets 1
#define TITLE_it Numero di pacchetti 1
#endif
#if defined TARGET_compter
#define TITLE Compter en base p
#define TITLE_it Calcoli in base p
#endif
#if defined TARGET_decompter
#define TITLE Décompter en base p
#define TITLE_it Calcoli in base p (reverse)
#endif
#if defined TARGET_convertirp
#define TITLE Convertir vers la base p 1
#define TITLE_it Convertire in base p 1
#endif
#if defined TARGET_convertir10
#define TITLE Convertir de la base p vers la base 10
#define TITLE_it Convertire dalla base p alla base 10
#endif
#if defined TARGET_convertirp2
#define TITLE Convertir vers la base p 2
#define TITLE_it Convertire in base p 2 
#endif
#if defined TARGET_paquet2
#define TITLE Nombre de paquets 2
#define TITLE_it Numero di pacchetti 2
#endif
#if defined TARGET_predecesseur1
#define TITLE Prédécesseur particulier en base p
#define TITLE_it Precedente particolare in base p
#endif
#if defined TARGET_predecesseur2
#define TITLE Prédécesseur quelconque en base p
#define TITLE_it Precedente qualunque in base p
#endif
#if defined TARGET_successeur1
#define TITLE Successeur particulier en base p
#define TITLE_it Successivo particolare in base p
#endif
#if defined TARGET_successeur2
#define TITLE Successeur quelconque en base p
#define TITLE_it Successivo qualunque in base p
#endif
