#if defined TARGET_paquet1 || defined TARGET_paquet2
\text{txtst2=Combien de paquets de}
\text{txtst3=jetons peut-on réaliser lorsqu'on dispose de}
\text{txtst4=jetons ?}
\text{txtans1=On peut réaliser}
\text{txtans2= paquet(s).}
#endif

#if defined TARGET_paquet1 || defined TARGET_paquet2 || defined TARGET_paquet3
\text{txtyourreply=Votre réponse}
\text{txtinstruction=Ecrire le nombre de paquets en base \basep.}
\text{txtanalyse=réponse correcte }
\text{txtgoodanswer=La bonne réponse est}
#endif

#if defined TARGET_paquet3
\text{txtst2=Combien de jetons non utilisés restera-t-il si on réalise des paquets de}
\text{txtst3=jetons lorsqu'on dispose de}
\text{txtst4=jetons ?}
\text{txtans1=Il restera}
\text{txtans2= jeton(s).}
#endif

#if defined TARGET_compter
\text{txtstatement1=Les nombres sont écrits en base \basep.}
\text{txtstatement2=Compter de}
\text{txta=à}
\text{txtinstruction=Les nombres doivent être séparés par des virgules.}
\text{txtanalyse=réponse correcte }
\text{txtgoodanswer=La bonne réponse est}
#endif

#if defined TARGET_decompter
\text{txtstatement1=Les nombres sont écrits en base \basep.}
\text{txtstatement2=Décompter de }
\text{txta=à}
\text{txtinstruction=Les nombres doivent être séparés par des virgules.}
\text{txtanalyse=réponse correcte }
\text{txtgoodanswer=La bonne réponse est}
#endif


#if defined TARGET_convertirp || defined TARGET_convertir2 || defined TARGET_convertirp3 || defined TARGET_convertir10 || defined TARGET_parquet1 || defined TARGET_parquet2 || defined TARGET_paquet3 || defined TARGET_predecesseur1 || defined TARGET_predecesseur2 || defined TARGET_successeur1 || defined TARGET_successeur2
\text{txtstatement1=Dans cet exercice on utilise la base \basep.}
#endif

#if defined TARGET_convertirp || defined TARGET_convertir2 || defined TARGET_convertirp3 || defined TARGET_convertir10 
\text{txtbase=Base}
\text{txtbaseten=Base dix}
#endif


#if defined TARGET_convertirp || defined TARGET_convertirp2
\text{txtstatement2=Convertir le nombre suivant, écrit en base dix, dans la base \basep ?}
\text{txtstatement3=Convertir les nombres suivants, écrits en base dix, dans la base \basep :}
#endif

#if defined TARGET_convertirp3
\text{txtstatement2=Convertir le nombre suivant, écrit en base dix, dans la base \basep ?}
#endif

#if defined TARGET_convertir10
\text{txtstatement2=Ecrire le nombre suivant en base dix?}
\text{txtstatement3=Ecrire les nombres suivants en base dix :}
#endif

#if defined TARGET_predecesseur1 || defined TARGET_predecesseur2 || defined TARGET_successeur1 || defined TARGET_successeur2
\text{txtst2a=Quel est le}
\text{txtst2b=du nombre suivant dans cette base ?}
\text{txtst3a=Trouvez les}
\text{txtst3b=des nombres suivants dans cette base :}
\text{txtnum=Nombre}
\text{txttype=prédécesseur,,successeur}
\text{txttypes=prédécesseurs,,successeurs}
\text{txtttype=Prédécesseur,,Successeur}
#endif

\text{txtnombre=nombre}
