#if defined TARGET_paquet1 || defined TARGET_paquet2
\text{txtst2=Quanti pacchetti di}
\text{txtst3=gettoni si possono realizzare quando si dispongono}
\text{txtst4=gettoni?}
\text{txtans1=Si possono realizzare}
\text{txtans2= pacchetti}
#endif

#if defined TARGET_paquet1 || defined TARGET_paquet2 || defined TARGET_paquet3
\text{txtyourreply=Vostra risposta}
\text{txtinstruction=Scrivere il numero di pacchetti in base \basep.}
\text{txtanalyse=risposta corretta}
\text{txtgoodanswer=La risposta corretta è}
#endif

#if defined TARGET_paquet3
\text{txtst2=Quanti gettoni non utilizzati resteranno se si creano pacchetti da}
\text{txtst3=gettoni quando si dispongono}
\text{txtst4=gettoni?}
\text{txtans1=Rimarranno}
\text{txtans2= gettoni}
#endif

#if defined TARGET_compter || defined TARGET_decompter
\text{txtstatement1=I numeri sono scritti in base \basep.}
\text{txtstatement2=Scrivere i numeri da}
\text{txta=a}
\text{txtinstruction=I numeri devono essere separati da una virgola.}
\text{txtanalyse=risposta corretta}
\text{txtgoodanswer=La risposta corretta è}
#endif

#if defined TARGET_convertirp || defined TARGET_convertir2 || defined TARGET_convertirp3 || defined TARGET_convertir10 || defined TARGET_parquet1 || defined TARGET_parquet2 || defined TARGET_paquet3 || defined TARGET_predecesseur1 || defined TARGET_predecesseur2 || defined TARGET_successeur1 || defined TARGET_successeur2
\text{txtstatement1=In questo esercizio si utilizza la base \basep.}
#endif

#if defined TARGET_convertirp || defined TARGET_convertir2 || defined TARGET_convertirp3 || defined TARGET_convertir10 
\text{txtbase=Base}
\text{txtbaseten=Base dieci}
#endif


#if defined TARGET_convertirp || defined TARGET_convertirp2
\text{txtstatement2=Convertire il numero in tabella, scritto in base dieci, nella base \basep.}
\text{txtstatement3=Convertire i numeri in tabella, scritti in base dieci, nella base \basep:}
#endif

#if defined TARGET_convertirp3
\text{txtstatement2=Convertire il numero in tabella, scritto in base dieci, nella base \basep.}
#endif

#if defined TARGET_convertir10
\text{txtstatement2=Scrivere in base dieci il numero in tabella.}
\text{txtstatement3=Scrivere in base dieci i numeri in tabella:}
#endif

#if defined TARGET_predecesseur1 || defined TARGET_predecesseur2 || defined TARGET_successeur1 || defined TARGET_successeur2
\text{txtst2a=Qual è il}
\text{txtst2b=in tale base del numero in tabella?}
\text{txtst3a=Trovare i}
\text{txtst3b=in tale base dei numeri in tabella:}
\text{txtnum=Numero}
\text{txttype=precedente,,successivo}
\text{txttypes=precedenti,,successivi}
\text{txtttype=Precedente,,Successivo}
#endif

\text{txtnombre=numero}
