"""XKCD-style passphrase generator (French wordlist).

Each call to :func:`generate_passphrase` picks ``n`` words uniformly from
``_WORDS`` using :mod:`secrets`. With the default of 4 words from a list
of ~400 entries the entropy is ``log2(400**4)`` ≈ 35 bits — strong enough
for a bcrypt-hashed login password that's also rate-limited at the API.

Words are common French nouns without diacritics so they're easy to type
on any keyboard layout the first time the user logs in.
"""

from __future__ import annotations

import secrets

_WORDS: tuple[str, ...] = (
    # Animals
    "chat",
    "chien",
    "lapin",
    "loup",
    "ours",
    "lion",
    "tigre",
    "renard",
    "cerf",
    "biche",
    "ecureuil",
    "herisson",
    "mouton",
    "vache",
    "cheval",
    "ane",
    "cochon",
    "poule",
    "canard",
    "oie",
    "cygne",
    "paon",
    "aigle",
    "faucon",
    "hibou",
    "chouette",
    "corbeau",
    "moineau",
    "hirondelle",
    "perroquet",
    "dauphin",
    "baleine",
    "requin",
    "poisson",
    "grenouille",
    "crapaud",
    "serpent",
    "lezard",
    "tortue",
    "escargot",
    "papillon",
    "abeille",
    "fourmi",
    "araignee",
    "scarabee",
    "libellule",
    "sauterelle",
    "mouche",
    "moustique",
    # Food / drink
    "pain",
    "fromage",
    "beurre",
    "huile",
    "oeuf",
    "viande",
    "poulet",
    "boeuf",
    "agneau",
    "jambon",
    "saucisse",
    "salade",
    "tomate",
    "carotte",
    "oignon",
    "ail",
    "pomme",
    "poire",
    "banane",
    "fraise",
    "framboise",
    "raisin",
    "citron",
    "orange",
    "peche",
    "abricot",
    "cerise",
    "prune",
    "melon",
    "ananas",
    "noisette",
    "amande",
    "noix",
    "miel",
    "confiture",
    "gateau",
    "biscuit",
    "chocolat",
    "glace",
    "soupe",
    "riz",
    "pates",
    "pizza",
    "sucre",
    "sel",
    "poivre",
    "lait",
    "cafe",
    "vin",
    "biere",
    # Body
    "tete",
    "oeil",
    "oreille",
    "nez",
    "bouche",
    "dent",
    "langue",
    "gorge",
    "cou",
    "epaule",
    "bras",
    "coude",
    "main",
    "doigt",
    "ongle",
    "poitrine",
    "ventre",
    "dos",
    "jambe",
    "genou",
    "pied",
    "orteil",
    "cheveu",
    "sourcil",
    "peau",
    "coeur",
    "poumon",
    # Nature
    "arbre",
    "fleur",
    "feuille",
    "branche",
    "racine",
    "herbe",
    "champ",
    "foret",
    "riviere",
    "lac",
    "mer",
    "ocean",
    "ile",
    "montagne",
    "colline",
    "vallee",
    "plage",
    "sable",
    "rocher",
    "pierre",
    "terre",
    "ciel",
    "nuage",
    "soleil",
    "lune",
    "etoile",
    "planete",
    "vent",
    "pluie",
    "neige",
    "feu",
    "fumee",
    "ombre",
    # Time
    "jour",
    "nuit",
    "matin",
    "midi",
    "soir",
    "semaine",
    "mois",
    "annee",
    "heure",
    "minute",
    "printemps",
    "ete",
    "automne",
    "hiver",
    # House
    "maison",
    "porte",
    "fenetre",
    "mur",
    "toit",
    "sol",
    "plafond",
    "escalier",
    "salon",
    "cuisine",
    "chambre",
    "salle",
    "bain",
    "douche",
    "lit",
    "table",
    "chaise",
    "fauteuil",
    "canape",
    "armoire",
    "etagere",
    "lampe",
    "miroir",
    "tableau",
    "tapis",
    "rideau",
    "casserole",
    "poele",
    "couteau",
    "fourchette",
    "cuillere",
    "assiette",
    "verre",
    "tasse",
    "bol",
    "plat",
    "cle",
    "serrure",
    # Tools / objects
    "livre",
    "cahier",
    "crayon",
    "stylo",
    "papier",
    "regle",
    "gomme",
    "ciseaux",
    "colle",
    "ordinateur",
    "clavier",
    "ecran",
    "telephone",
    "montre",
    "horloge",
    "lunettes",
    "sac",
    "valise",
    "parapluie",
    "chapeau",
    "gant",
    # Clothing
    "pull",
    "pantalon",
    "jupe",
    "robe",
    "chemise",
    "veste",
    "manteau",
    "chaussure",
    "botte",
    "ceinture",
    "cravate",
    "foulard",
    # Transport
    "voiture",
    "velo",
    "moto",
    "camion",
    "autobus",
    "train",
    "avion",
    "bateau",
    "navire",
    "fusee",
    "route",
    "rue",
    "autoroute",
    "pont",
    "gare",
    "port",
    "aeroport",
    # Buildings
    "ecole",
    "eglise",
    "hopital",
    "magasin",
    "restaurant",
    "theatre",
    "cinema",
    "musee",
    "bibliotheque",
    "parc",
    "jardin",
    "place",
    "marche",
    "usine",
    "bureau",
    "ferme",
    "chateau",
    "tour",
    "palais",
    # Roles
    "ami",
    "voisin",
    "enfant",
    "parent",
    "frere",
    "soeur",
    "oncle",
    "tante",
    "cousin",
    "fils",
    "fille",
    "mari",
    "eleve",
    "professeur",
    "medecin",
    "infirmier",
    "pompier",
    "policier",
    "soldat",
    "juge",
    "avocat",
    "ingenieur",
    "artiste",
    "peintre",
    "musicien",
    "ecrivain",
    "acteur",
    "danseur",
    "chanteur",
    "boulanger",
    "boucher",
    "fleuriste",
    "jardinier",
    "pecheur",
    "chasseur",
    "marin",
    "pilote",
    # Abstract / misc
    "amour",
    "joie",
    "peur",
    "colere",
    "tristesse",
    "espoir",
    "reve",
    "idee",
    "pensee",
    "parole",
    "voix",
    "son",
    "bruit",
    "silence",
    "paix",
    "courage",
    "force",
    "vie",
    "sante",
)

assert len(_WORDS) >= 200, "wordlist too short for adequate entropy"


def generate_passphrase(n_words: int = 4, separator: str = "-") -> str:
    """Return an XKCD-style passphrase of ``n_words`` joined by ``separator``."""
    if n_words < 1:
        raise ValueError("n_words must be ≥ 1")
    return separator.join(secrets.choice(_WORDS) for _ in range(n_words))


def wordlist_size() -> int:
    return len(_WORDS)
