!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes

<tr>
<th>Ex. Signe de "produit ou quotient"</th>
<td>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm1 list 1,2,3 prompt Que des produits,Que des quotients, L'un ou l'autre
</ul>
</td>
</tr>
