!! fichier de gestion de la conclusion de l'exercice avant la notation.

<u><b>Geef het resultaat:</b></u>
!goto $wims_read_parm
!exit

:question
!form reply
Volgens de berekeningen hierboven is de ggd van $AA0 en $BB0 :<p>
ggd($AA0,$BB0)=
<input type=text name=repexo1 size=5 value=$(repexo1)>.<p>
<input type=hidden name=status value=3>
<center><input type=submit value="Versturen"></center>
</form>
!exit

:analyse
erreur=$empty
!if $(RR$[$nbetape])>1
   !increase nbreerrrais
   !exit
!endif

tmp=!exec maxima gcd($AA0,$BB0)

!if $repexo1!=$tmp
   erreur=verkeerd antwoord.<p>
   !increase nbreerrrais
   status=2
   !exit
!endif
   status=5
!exit

:reponse
Het algoritme van Euclides is nog niet af. Je moet verder gaan met de 
berekeningen voordat je kunt concluderen.<p>
!form reply
<input type=hidden name=status value=1>
<center><input type=submit value="Verder gaan"></center>
</form>

!exit
