!for i=1 to 5
   !let repexo$i=$empty
!next i
!let nbreesscalc=0
<u>Mogelijke handelingen:</u>
<lu>
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=1>
<input type=submit value=Deling> van twee gehelen om de berekening te vereenvoudigen.
</form></li>
<li>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=3>
<input type=submit value=Concluderen> naar aanleiding van de gedane berekeningen.
</form></li>
</lu>
