insmath_rawmath=yes
wims_backslash_insmath=yes
wims_print_precision=2

!if $status=0
   nbreerrcalc=0
   nbreerrrais=0
   nbreesscalc=0
   nbreaide=0
   !read don.ini
   status=1
!endif

!if $status=3
   !let tmp=!item $action of $listaction
   !read $tmp analyse
!endif

!if $status=4
   !read src/conclure.phtml analyse2
!endif

!if $status=5
   tmp=$[max(0,10-$nbreerrrais*2-$nbreerrcalc)]
   noteinter=$[$noteinter+$tmp/$nbreexo]
   !if $noexo=$nbreexo
      module_score=$[min(10,max(0,$noteinter))]
   !endif
!endif
