\text{name_longueur=een lengte, een volume,een hoogte,een gewicht,een prijs}
#if defined TARGET_pourcentage
\text{name_augdim=verhoogt,verlaagt}
\text{name_question=Je,met,Met hoeveel moeten wij, vermenigvuldigen }
\text{name_answer=Je moet vermenigvuldigen met}
#endif
#if defined TARGET_pourcentage2
\text{name_genre=1,1,1,2,2,2}
\text{name_augmen=verhoging, verlaging}
\text{name_augmen2=\name_augmen}
\text{name_augmen3=verhoging en, verlaging en}
\text{name_multiplie=te vermenigvuldigen met,te vermenigvuldigen met}
\text{name_enonce=Men verandert, en}
\text{name_answer=Het is een,Percentage}
\text{name_question=Druk deze, uit in een percentage.}
\text{name_question1=Het is een ,of een }
#endif
