#define TITLE 5 - Gerbage
#define TITLE_en 5 - Gerbage

\text{name_solution=<ul>(format décimal)
<li>Poids = \poids (unités de poids)</li>
<li>Pression = \pression (unités de pression)</li>
</ul>}
\matrix{name_vocab=poids d'un empilement
pression}

\if{\lang=en}{
\text{name_solution=<ul>(format décimal)
<li>Poids = \poids (unités de poids)</li>
<li>Pression = \pression (unités de pression)</li>
</ul>}
\matrix{name_vocab=poids d'un empilement
pression}

}
