
\if{\lang=fr}{
La masse d'un élément est m = \masse kg.
<ol>
<li>Calculer le poids d'un empilement de \quantite éléments (on prendra g = \gravite N/kg).</li>
<li>Cet empilement repose sur un socle de masse \masse2 kg de dimensions \longueur m par \largeur m.
Calculer la pression exercée sur le sol par l'ensemble.</li>
</ol>
}
\if{\lang=en}{
La masse d'un élément est m = \masse kg.
<ol>
<li>Calculer le poids d'un empilement de \quantite éléments (on prendra g = \gravite N/kg).</li>
<li>Cet empilement repose sur un socle de masse \masse2 kg de dimensions \longueur m par \largeur m.
Calculer la pression exercée sur le sol par l'ensemble.</li>
</ol>
}
