\if{\lang!=en}{
Un point A est situé à \profondeur m au-dessous de la surface d'un lac.
La pression supportable par les canalisations est
\pression bars. La pression atmosphérique est \press_at Pa,
la masse volumique de l'eau est \rhoo kg/m<sup>3</sup>,
g = \gravite N/kg, 1 bar = 10<sup>5</sup> Pa.
<ol>
<li>En appliquant le principe fondamental de l'hydrostatique,
calculer la pression au point A, en pascals et en bars.
</li>
<li>
Y a-t-il risque de rupture des canalisations ?
</li>
</ol>
<div class="wims_instruction">
Donnez le résultat de la première question sous
forme décimale avec une précision d'au moins 10<sup>-2</sup>.
</div>
}

\if{\lang=en}{
Un point A est situé à \profondeur m au-dessous de la surface d'un lac.
La pression supportable par les canalisations est
\pression bars. La pression atmosphérique est \press_at Pa,
la masse volumique de l'eau est \rhoo kg/m<sup>3</sup>,
g = \gravite N/kg, 1 bar = 10<sup>5</sup> Pa.
<ol>
<li>En appliquant le principe fondamental de l'hydrostatique,
calculer la pression au point A, en pascals et en bars.
</li>
<li>
Y a-t-il risque de rupture des canalisations ?
</li>
</ol>
<div class="wims_instruction">
Donnez le résultat de la première question sous
forme décimale avec une précision d'au moins 10<sup>-2</sup>.
</div>
}
