\if{\lang=fr}{
Pour enfoncer une punaise, on exerce sur la tête (disque de diamètre \diametre mm) une force pressante d'intensité \force N.
<ol>
<li>Calculer l'aire de la tête (on prend \(\pi=3,14\) ).</li>
<li>Calculer la pression exercée par le doigt sur la tête de la punaise (à 1 Pa près).</li>
<li>L'aire de la pointe est \aire_pointe mm<sup>2</sup>. Quelle est la pression exercée par la pointe sur le mur ?</li>
</ol>
}

\if{\lang=en}{
Pour enfoncer une punaise, on exerce sur la tête (disque de diamètre \diametre mm) une force pressante d'intensité \force N.
<ol>
<li>Calculer l'aire de la tête (on prend \(\pi=3,14\) ).</li>
<li>Calculer la pression exercée par le doigt sur la tête de la punaise (à 1 Pa près).</li>
<li>L'aire de la pointe est \aire_pointe mm<sup>2</sup>. Quelle est la pression exercée par la pointe sur le mur ?</li>
</ol>
}
