\if{\lang!=en}{
<p>Les résultats doivent être donnés au
\special{help fscient, format scientifique}
avec très exactement quatre chiffres significatifs.
Les puissances de 10 se notent comme à l'aide de certaines calculatrices,
par une lettre "e" qui signifie "10 à la puissance..."
</p><p>
Vous ne donnerez que les réponses numériques.
</p>

}

\if{\lang=en}{
<p>The results doivent être donnés au
\special{help fscient, format scientifique}
avec très exactement quatre chiffres significatifs.
Les puissances de 10 se notent comme à l'aide de certaines calculatrices,
par une lettre "e" qui signifie "10 à la puissance..."
</p><p>
Vous ne donnerez que les réponses numériques.
</p>
}
