\if{\lang=fr}{
<div class="float_left spacer"><img src="\image" alt=""></div>
Pour soulever des caisses, un chariot élévateur utilise un vérin de diamètre intérieur
 \diametre cm.
Pour maintenir cette caisse en équilibre, le vérin doit exercer une force \(\vec{F}\)
 d'intensité \force daN.
Déterminer la pression à l'intérieur de la chambre cylindrique du vérin (à 1 bar près).
}

\if{\lang=en}{
<div class="float_left spacer"><img src="\image" alt=""></div>
Pour soulever des caisses, un chariot élévateur utilise un vérin de diamètre intérieur
 \diametre cm.
Pour maintenir cette caisse en équilibre, le vérin doit exercer une force \(\vec{F}\)
 d'intensité \force daN.
Déterminer la pression à l'intérieur de la chambre cylindrique du vérin (à 1 bar près).
}
