\if{\lang!=en}{
<h3>Notation scientifique :</h3>
Écrire un nombre en notation scientifique, c'est l'écrire sous la forme d'un
produit d'une puissance de 10 et d'un nombre décimal ayant
<span class="bold">un seul chiffre</span>,
<span style="text-decoration:underline">autre que zéro</span>,
<span class="bold">avant la virgule</span>.
<h4>Exemple :</h4>
A = 674.8 <span class="bold">s'écrit au format scientifique :</span>
<ul><li>
A = 6.748e2 (avec 4 chiffres significatifs)
</li>
<li>
A = 6.75e2  (avec 3 chiffres significatifs)
</li>
<li>
A = 7e2     (avec 1 chiffre significatif)
</li>
</ul>
(Le "e2", par exemple, signifie pour l'ordinateur, 10<sup>2</sup>).
}
\if{\lang=en}{
<h3>Scientific notation:</h3>
Écrire un nombre en notation scientifique, c'est l'écrire sous la forme d'un
produit d'une puissance de 10 et d'un nombre décimal ayant
<span class="bold">un seul chiffre</span>,
<span style="text-decoration:underline">autre que zéro</span>,
<span class="bold">avant la virgule</span>.
<h4>Exemple :</h4>
A = 674.8 <span class="bold">s'écrit au format scientifique :</span>
<ul><li>
A = 6.748e2 (avec 4 chiffres significatifs)
</li>
<li>
A = 6.75e2  (avec 3 chiffres significatifs)
</li>
<li>
A = 7e2     (avec 1 chiffre significatif)
</li>
</ul>
(Le "e2", par exemple, signifie pour l'ordinateur, 10<sup>2</sup>).
}
