#define TITLE 8 - Presse
#define TITLE_en 8 - Presse

\text{name_aide=La pression exercée sur le petit piston se retransmet intégralement sur le grand piston.}
\matrix{name_vocab=aire petit piston en
aire petit piston en
pression
unité
diamètre grand piston
soit en cm à 1 cm près}


\if{\lang=en}{
\text{name_aide=La pression exercée sur le petit piston se retransmet intégralement sur le grand piston.}
\matrix{name_vocab=aire petit piston en
aire petit piston en
pression
unité
diamètre grand piston
soit en cm à 1 cm près}
}
