\if{\lang!=en}{
Une presse hydraulique est constituée de deux cylindres de diamètres différents, reliés par une conduite.
Ils contiennent un liquide, en contact avec les deux pistons. En agissant sur le petit piston, on exerce
une pression qui se transmet sur le grand piston. Le petit piston a un diamètre de \diametre cm et est
soumis à une force de \force N.

<ol>
<li>Quelle est la pression exercée en un point de la surface de ce piston ?
<div class="wims_instruction">On rappelle : 1 Pa = 1 N/m<sup>2</sup></div>
</li>
<li>Quel doit être le diamètre du grand piston pour que la force qu'il exerce
ait une intensité de \FORCE daN ?</li>
</ol>
}
\if{\lang=en}{
Une presse hydraulique est constituée de deux cylindres de diamètres différents, reliés par une conduite.
Ils contiennent un liquide, en contact avec les deux pistons. En agissant sur le petit piston, on exerce
une pression qui se transmet sur le grand piston. Le petit piston a un diamètre de \diametre cm et est
soumis à une force de \force N.

<ol>
<li>Quelle est la pression exercée en un point de la surface de ce piston ?
<div class="wims_instruction">On rappelle : 1 Pa = 1 N/m<sup>2</sup>.</div>
</li>
<li>Quel doit être le diamètre du grand piston pour que la force qu'il exerce
ait une intensité de \FORCE daN ?</li>
</ol>
}
