\if{\lang=fr}{
Un objet de poids \poids N est posé sur la table d'une scie à fil, l'aire de la surface de
 l'objet en contact avec la table est égale à \surface m<sup>2</sup>.
Parmi les valeurs suivantes, quelle est celle qui indique la pression
en Pascal exercée par l'objet sur la table ?
<div class="wims_instruction">On rappelle que 1 Pa = 1 N/m<sup>2</sup>.</div>
}

\if{\lang=en}{
An object of weight \N is placed on the table of a wire saw, the surface area of
  the object in contact with the table is equal to \surface m<sup>2</sup>.
Of the following, which is the one that indicates the pressure
in Pascals exerted by the object on the table?
<div class="wims_instruction">Remember that 1 Pa = 1 N/m<sup>2</sup>.</div>
}
