!set namelist=numéro atomique,symbole,nom de l'élément,masse atomique
!set name_alea=aléatoire
!set name_header=Information fournie (si applicable),\
  Information demandée (si applicable),\
  Exclure les éléments au-dessus du numéro,\
  ou une liste de numéros<br/>des éléments à tester

<tr><th>$(name_header[1])
</th><td>
!formselect confparm1 list 0,1,2,3,4 prompt $name_alea,$namelist
</td></tr>
<tr><th>$(name_header[2])
</th><td>
!formselect confparm2 list 0,1,2,3,4 prompt $name_alea,$namelist
</td></tr>
<tr><th><label for="confparm3">$(name_header[3])</label>
</th><td>
<input size="3" id="confparm3" name="confparm3" value="54" /></td>
</tr>
<tr><th><label for="confparm4">$(name_header[4])</label></th><td>
<input size="40" id="confparm4" name="confparm4" />
</td></tr>
