!header
!read Exindex
<p>Ce module regroupe pour l'instant $exototal exercices sur la construction d'une
 représentation graphique à l'aide de Python pour une classe de seconde.
 Le but est de travailler de concert dans des cadres algébriques, graphiques et
 algorithmiques afin de maîtriser la notion de fonction.</p>
<p>La boucle "While" est utilisée bien qu'elle met en évidence un problème lié à la construction
 des flottants avec python. Ce problème de mantisse est reproduit simplement avec
 l'instruction print(-0.97+0.3).
 Dans ce cas-là, la note de l'élève passe à 9.9/9.8 et un feedback explique la nature de l'erreur.</p>
<p>L'exercice "Fonction 13" utilise un algorithme pour colorier les différents points selon
 la monotonie de la fonction. Il fonctionne uniquement pour des fonctions continues.
 Pour garder un algorithme simple, la discontinuité en zéro de la fonction inverse ne sera
  pas traitée. Néanmoins un feedback explique le problème.</p>

!read oef/intromenu.phtml
!tail
