!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set confparm1=1
!set confparm2=1,2,3,4,5,6,7
<tr><td>Sélectionner un thème pour l'éditeur Python :</td>
</tr>
<tr><td>
!formradio confparm1 list 1,2,3 prompt thème classique,thème bleu,thème matrix
</td>
</tr>
<tr><td>Les exercices intitulés "fonction 13" et "fonction 14" étudient respectivement
le signe et la monotonie d'une fonction. Il peut être intéressant
 de choisir une ou des fonctions spécifiques&nbsp;:</td></tr>
<td>
!formcheckbox confparm2 list 1,2,3,4,5,6,7 prompt \( \bf{\sqrt{x}}\),\(\bf{\frac{1}{x}}\),\(\bf{-x^3}\),\(\bf{-x^2}\),\(\bf{x^2}\),\(\bf{x^3}\),\(\bf{a x+ b}\)
</td>
</tr>
