!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

!if $mode=1
  !if $flpoly=ok
    !let module_score=!eval 10 - $errcnt
  !else
    !let module_score=0
  !endif
  !if $flpoly=ok
    !let module_score= !eval 10 - $errcnt
    <span class="mygreen">$(name_ansmode1[1]).</span>
  !else
    !let module_score=0
    <span class="myred">$(name_ansmode1[2]).</span>
  !endif
!endif
!if $mode=2
  !if error=bad
    !!let module_score=0
  !else
    !!let module_score=10
  !endif
  <p>
  $(name_answer[1]): $(name_formchoice2[1;1]) ($pt1$pt2)
  $(name_formchoice2[1;2]) ($pt3$pt4) $(name_formchoice2[1;3])
  <span class="$colorrep1">$(posrel1[$marep1]).</span>
  !if $marep1=1 and $goodrep1=1
    $(name_formchoice2[1;2])
    <span class="$colorrep2">$(posrel2[$marep2]).</span>.
  !endif
  </p>
!endif
!if $mode=3
  <p>$(name_answer[1]): $(name_formchoice3[1;1]) ($tplan), $(name_formchoice3[1;2])
  ($pt1$pt2) $(name_formchoice3[1;3])
  <span class="$colorrep1">$(posrel3[$marep1])</span>.</p>
  !if $colorrep1=myred
    <p>$(name_answer[2]): <strong>$(posrel3[$goodrep1])</strong>.</p>
  !endif
!endif
<p>
$name_score
</p>
