!set t=!positionof item $mode in $listexos
!set title=!item $t of $exotitles
!set module_title=$title
!read style.css

!header

!! La présentation de l'exercice.
!read present.phtml

!if $status=waiting
  !if $error!=$empty
    <div class="wims_msg alert">
    !read msg.phtml
    </div>
  !endif
  !! La forme de réponse
  !read form.phtml
  <p>
  !set wims_ref_class=wims_button
  !href exo_Renew
  </p>
!else
  !if $error!=$empty
    <div class="wims_msg alert">
    !read msg.phtml
    </div>
  !endif
  !! L'analyse de réponse
  !if $status=done
    !read answer.phtml
  !endif
  <p>
  !set wims_ref_class=wims_button
  !href exo_Again
  !if $worksheet=$empty
    !set wims_ref_class=wims_button
    !href exo_Intro
  !endif
  </p>
!endif

:end
!tail
