!! Ce fichier présente la question à résoudre.

!let insdraw_size= 400,400
!let $cadre = $cadre\
  $dessindtes
!if $mode=1
  !!let plan=AMN
  $name_present11
  <p>
  $(name_present12[1])
  <span class="myred">($tplan)</span>
  $(name_present12[2])
  <span class="myblue">ABCD</span>.
  </p>
  <div class="wims_instruction">
  $name_present_inst11
  <p>$name_present_inst12</p>
  </div>
!endif
!if $mode=2
  $name_present21<p>
  $(name_present22[1]) <span class="myred">($pt1$pt2)</span> $(name_present22[2])
  <span class="myblue">($pt3$pt4)</span> $(name_present22[3]).
  </p>
!endif
!if $mode=3
  $name_present31<p>
  $(name_present32[1]) <span class="myred">($pt1$pt2)</span> $(name_present32[2])
  <span class="myblue">($tplan)</span> $(name_present32[3]).
  </p>
!endif
<div class="wimscenter">
!insdraw $cadre
</div>
