# Variable initialisation file.
# This file is read by wims for new sessions.

# content of the file: initialisation of the problem.

!read language lang/names

status=waiting
wims_module_log=$cmd

wims_backslash_insmath=yes
wims_backslash_instex=yes
wims_multiexec=pari,octave,maxima

!set listexos=1,2,3
!if $mode=$empty
  mode=1,2,3
  mode=!randitem $mode
!else
  mode=$mode
!endif

step=1
next=0
note=0

answer=
error=$empty

listpoint=A,B,C,D,I,J,K,L,M,N,O,P,Q,R,S,T
numpoint=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20


## coordonnées des points à plat
ptA=0,0
ptB=6,18
ptC=24,0
ptD=18,12

ptI=8,0
ptJ=16,0
ptK=6,4
ptL=12,8
ptM=2,6
ptN=4,12
ptO=12,12
ptP=18,6
ptQ=10,16
ptR=14,14
ptS=20,8
ptT=22,4


relieU1=Q,K1,R,K,O,I1,P,I,J,P1,L,R1
relieU3=K,J,L,J1,Q,P,R,P1,I,K1,O,Q1
relieU5=I,N,J,N1,S,Q,T,Q1,R,S1,M,I1
relieU7=S,I1,T,I,R,M1,Q,M,J,T1,N,Q1

relieX1=L,Q,K,Q1,I,O1,J,O,R,L1,P,J1
relieX3=I,L,J,L1,O,R,P,R1,Q,O1,K,I1
relieX5=N,J1,M,J,R,T,Q,T1,I,M1,S,R1
relieX7=I,S1,J,S,N,R,M,R1,Q,N1,T,J1

relieV1=S,K,T,K1,P,M1,O,M,L,S1,N,O1
relieV3=L,N1,K,N,S,O1,T,O,M,K1,P,T1

relieY1=L,T,K,T1,N,P,M,P1,S,L1,O,N1
relieY3=N,L1,M,L,P,S,O,S1,K,M1,T,P1

ptU1=-2,-6
ptU2=-2,-6
ptU3=26,-4
ptU4=26,-4
ptU5=0,24
ptU6=0,24
ptU7=-6,-4
ptU8=-6,-4

ptX1=8,24
ptX2=8,24
ptX3=16,16
ptX4=16,16
ptX5=30,-6
ptX6=30,-6
ptX7=24,16
ptX8=24,16

ptV1=-8,0
ptV2=-8,0
ptV3=2,20
ptV4=2,20

ptY1=32,0
ptY2=32,0
ptY3=22,10
ptY4=22,10

ptI1=8/3,0
ptJ1=64/3,0
ptK1=2,4/3
ptL1=16,32/3
ptM1=2/3,2
ptN1=16/3,16
ptO1=8,16
ptP1=22,2
ptQ1=22/3,52/3
ptR1=50/3,38/3
ptS1=56/3,32/3
ptT1=70/3,4/3

colorA=blue
colorB=blue
colorC=blue
colorD=blue
colorI=green
colorJ=green
colorK=green
colorL=green
colorM=green
colorN=green
colorO=green
colorP=green
colorQ=green
colorR=green
colorS=green
colorT=green

# face ABC 1
# face BCD 2
# face ACD 3
# face ABD 4
faceA=1,3,4
faceB=1,2,4
faceC=1,2,3
faceD=2,3,4
faceI=1,3
faceJ=1,3
faceK=4,3
faceL=4,3
faceM=1,4
faceN=1,4
faceO=1,2
faceP=1,2
faceQ=2,4
faceR=2,4
faceS=2,3
faceT=2,3

faceX1=1,3
faceX2=1,3
faceU1=1,3
faceU2=1,3

faceX3=1,4
faceX4=1,4
faceU3=1,4
faceU4=1,4

faceX5=2,3
faceX6=2,3
faceU5=2,3
faceU6=2,3

faceX7=2,4
faceX8=2,4
faceU7=2,4
faceU8=2,4

faceY1=1,5
faceY2=1,5
faceV1=1,5
faceV2=1,5

faceY3=1,6
faceY4=1,6
faceV3=1,6
faceV4=1,6

face1=1,2,5
face2=2,3,6
face3=3,4,5
face4=1,4,6

## droite d'appartenance
## AB=1 BC=2 CD=3 DA=4, AC=5, BD=6
dte1=A,B,A-B,1,4
dte2=B,C,B-C,1,2
dte3=C,D,C-D,2,3
dte4=A,D,A-D,3,4
dte5=A,C,A-C,1,3
dte6=B,D,B-D,2,4

dteA=1,4,5
dteB=1,2,6
dteC=2,3,5
dteD=3,4,6
dteI=5
dteJ=5
dteK=4
dteL=4
dteM=1
dteN=1
dteO=2
dteP=2
dteQ=6
dteR=6
dteS=3
dteT=3

!read var.init2
