\text{name_nom=Il poliedro si chiama}
#if defined TARGET_11 || defined TARGET_12
\text{name_feed=Vediamo qui gli sviluppi dei poliedri seguenti}
# if defined TARGET_11
\text{name_instruction=Seleziona lo sviluppo del poliedro mostrato}
# endif
#if defined TARGET_12
\text{name_instruction=Seleziona il poliedro convesso il cui sviluppo è qui mostrato}
# endif
#endif
#if defined TARGET_21
\text{name_instruction=Individua il numero di spigoli del poliedro il cui sviluppo è qui mostrato}
\text{name_rep=Il numero di spigoli è}
#endif
#if defined TARGET_22
\text{name_instruction=Individua il numero di vertici del poliedro il cui sviluppo è qui mostrato}
\text{name_rep=Il numero di vertici è}
#endif

#if defined TARGET_31 || defined TARGET_32
\text{name_instruction=Ecco lo sviluppo di un poliedro convesso.
  Seleziona i vertici che si incollano sul vertice constrassegnato con una croce.}
#endif
