#if defined TARGET_11
# define TITRE_it Scegli lo sviluppo
#endif
#if defined TARGET_12
# define TITRE_it Scegli il poliedro
#endif
#if defined TARGET_21
# define TITRE_it Numero di spigoli
#endif
#if defined TARGET_22
# define TITRE_it Numero di vertici
#endif
#if defined TARGET_31
# define TITRE_it Identifica i vertici I
#endif
#if defined TARGET_32
# define TITRE_it Identifica i vertici II
#endif
