!header
!read Exindex
<center>
  <table width=75% bgcolor=lemonchiffon>
    <tr>
      <td>
       <p>
       Ce module regroupe pour l'instant $exototal exercices 
       se ramenant à la résolution d'une équation du premier ou 
       du second degré, à une variable réelle. Ces exercices sont 
       du  niveau seconde. Ils ont été conçus dans le but de donner 
       aux enseignants des classe de seconde, des exemples d'exercices 
       pouvant servir dans le cadre de l'<b>aide individualisée</b>.
      </td>
    </tr>
  </table>
</center>

!read oef/$module_language/intromenu.phtml
!tail