<b>Types d'expressions </b>
<table class="wimstable">
<tr>
<td>
!formcheckbox confparm1 list 1 prompt \(f_1 \pm f_2\)
</td><td>
!formcheckbox confparm1 list 2 prompt \(f_1 \times f_1\)
</td><td>
!formcheckbox confparm1 list 3 prompt \(\frac{f_1}{f_2}\)
</td><td>
</td>
</tr><tr>
<td>
!formcheckbox confparm1 list 5 prompt \(e_1 \pm f_1\)
</td><td>
!formcheckbox confparm1 list 6 prompt \(e_1 \times f_1\)
</td><td>
!formcheckbox confparm1 list 7 prompt \(\frac{e_1}{f_1}\)
</td><td>
!formcheckbox confparm1 list 8 prompt \(\frac{f_1}{e_1}\)
</td>
</tr><tr>
<td>
!formcheckbox confparm1 list 9 prompt \(f_1 \pm f_2 \pm f_3\)
</td><td>
!formcheckbox confparm1 list 10 prompt \(e_1 \pm f_1 \pm f_2\)
</td><td>
!formcheckbox confparm1 list 11 prompt \(f_1 - (f_2 \pm f_3)\)
</td><td>
!formcheckbox confparm1 list 12 prompt \(f_1 - (f_2 \pm e_1)\)
</td>
</tr><tr>
<td>
!formcheckbox confparm1 list 13 prompt \((f_1 \pm f_2) \times f_3\)
</td><td>
!formcheckbox confparm1 list 14 prompt \(f_1 \pm f_2 \times f_3\)
</td><td>
!formcheckbox confparm1 list 15 prompt \((e_1 \pm f_1) \times f_2\)
</td><td>
!formcheckbox confparm1 list 16 prompt \(e_1 \pm f_1 \times f_2\)
</td>
</tr><tr>
<td>
!formcheckbox confparm1 list 17 prompt \(\frac{f_1 \pm f_2}{f_3}\)
</td><td>
!formcheckbox confparm1 list 18 prompt \(\frac{f_1 \pm f_2}{e_1}\)
</td><td>
!formcheckbox confparm1 list 19 prompt \(\frac{e_1 \pm f_1}{f_2}\)
</td><td>
!formcheckbox confparm1 list 20 prompt \(\frac{e_1 \pm f_1}{e_2}\)
</td>
</tr><tr>
<td>
!formcheckbox confparm1 list 21 prompt \(\frac{f_1}{f_2 \pm f_3}\)
</td><td>
!formcheckbox confparm1 list 22 prompt \(\frac{e_1}{f_1 \pm f_2}\)
</td><td>
!formcheckbox confparm1 list 23 prompt \(\frac{f_1}{e_1 \pm f_2}\)
</td><td>
!formcheckbox confparm1 list 24 prompt \(\frac{e_1}{e_2 \pm f_1}\)
</td>
</tr>
</table>
<div class="formHelp">
Sélectionnez les types d'expressions à calculer. Les variables f désignent des fractions et les variables e des entiers.
</div><br class="spacer">

<b>Fractions irréductibles : </b>
!formradio confparm2 from 1 to 2 prompt oui , non
<div class="formHelp">
Si vous sélectionnez <i>oui</i>, les fractions apparaissant dans les expressions seront toujours irréductibles.
</div><br class="spacer">

<b>Complexité des valeurs : </b>
!formradio confparm3 from 1 to 3
