!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur la structure cellulaire et l'unité structurale
du vivant. Les exercices permettent de faire le point sur des connaissances de base en cytologie animale, végétale
et bactérienne. Ceci est aussi l'occasion de montrer que tous les êtres vivants sont constitués d'au moins une
cellule (unité).

!read oef/intromenu.phtml
!tail
