!header
!read Exindex

!if $lang=it
  Questo è essenzialmente un modulo di esercizi finalizzati
  all'allenamento nell'esecuzione delle operazioni.
  È data una espressione e è richiesto di completarla, sia inserendo
  termini che inserendo operatori, in modo da rendere l'eguaglianza
  corretta.
  <p>
  Sono permesse differenti configurazioni in modo da poter adattare
  l'esercizio a diversi livelli, a partire dalla scuola primaria (numeri
  interi positivi e negativi, numeri decimali,...) fino a livello
  secondario più avanzato (espressioni irrazionali, numeri complessi).
  </p>
  !goto end
!endif
!if $lang=fr
  C'est un outil d'entraînement essentiel pour les opérations arithmétiques.
  Il vous fait remplir une équation algébrique où des termes ou des
  opérateurs manquent, pour qu'elle devienne une équation correcte.
   <p>
  Selon la configuration, l'exercice peut convenir aux élèves du primaire
  (nombres positifs ou relatifs, décimaux), au lycée ou davantage (racines,
  nombres complexes).
  </p>
  !goto end
!endif
!if $lang=nl
  Deze module bevat oefenstof over het werken met vergelijkingen.
  Gevraagd wordt een vergelijking via het slepen met de muis
 -met getallen en/of operators- te completeren.
 <p>
 Door gebruik te maken van de onderstaande instel-mogelijkheden, kan deze module oefeningen
 genereren voor de lagere school (<em>bewerkingen met positieve getallen</em>), voor
 onderbouw (<em>positief,negatief,breuken</em>),
 voor de bovenbouw (<em>wortels en complexe getallen</em>)
 en hoger (<em>vergelijkingen met meerdere variabelen</em>)
 </p>
  !goto end
!endif

This is an essential training tool for arithmetic operations.
It makes you to fill-in an algebraic equation, either with missing
terms or missingh operators, in order to make the equation correct.
 <p>
And with different configurations, the exercises may fit students from
primary schools (positive or relative numbers, decimals) to senior high
school or even more (roots, complex numbers).
</p>

:end
!read oef/intromenu.phtml
!tail
