\text{name_answer=Probabilità}

#if defined TARGET_ball
\text{name_evenodd=pari,dispari}
\text{name_color=rossa,verde,blu,gialla}
\text{name_colors=rosse,verdi,blu,gialle}
\text{name_statement1=Un sacchetto contiene}
\text{name_the=La,Le,la,le}
\text{name_balls=pallina,palline}
\text{name_have=abbia,abbiano}
\text{name_a=un}
\text{name_number=numero}
\text{name_and=e}
\text{name_statement2=Si estraggono a caso,dal sacchetto.}
\text{name_is=è}
\text{name_one=una}
\text{name_space=}
\text{name_step1=La probabilità di estrarre solo palline,}
\text{name_step2=La probabilità di ottenere}
\text{name_enum=sono numerate da 1 a}
\text{name_step3=La probabilità che tra le,palline estratte}
\text{name_replygood=Risposta esatta!}
\text{name_yourreply=La tua risposta}
\text{name_sol1=La probabilità di estrarre solo palline,}
\text{name_sol2=La probabilità di ottenere}
\text{name_sol3=Dal momento che si hanno,il cui numero è,la probabilità di estrarre esattamente}
\text{sort_nameadj=1}
#endif
#if defined TARGET_birthdays
\text{name_statement=Supponiamo che i compleanni di una certa popolazione siano distribuiti
  uniformemente nei 365 giorni dell'anno. Se prendiamo a caso \people persone
  dall'elenco telefonico, qual è la probabilità che almeno due di queste 
  \people persone compiano gli anni lo stesso giorno?
}
\text{name_hint=Prova a calcolare invece la probabilità che queste \people persone compiano
  tutte gli anni in giorni diversi.}
#endif
#if defined TARGET_bw
\text{name_statement=In un sacchetto sono contenute \black palline nere e \white palline bianche.
  Se estraiamo due palline a caso dal sacchetto, qual è la probabilità che le due palline siano}
\text{name_space=}
\text{name_balls=una nera e una bianca,entrabe nere,entrambe bianche}
#endif
#if defined TARGET_coins
\text{name_statement1=Supponiamo che ogni volta che lanciamo una moneta la probabilità
  di ottenere testa sia esattamente 1/2.}
\text{name_statement2=Se lanciamo \times volte la moneta, qual è la probabilità di ottenere
  esattamente \faces volte testa?}
\text{name_solution=Ci sono \(C_\times^\faces) differenti modi
  in cui le \faces facce possono essere distibuite nei \times lanci
 della moneta. E ogni modo ha probabilità \(1/2^(\times)\).}
#endif
#if defined TARGET_freeway
\text{name_statement1=Stando alle statistiche, un pedone che cammina lungo un certo tratto
  di autostrada nel tempo di 1 minuto ha probabilità \min di essere investito
  da un'auto.}
\text{name_statement2=Il Sig. X scommette di riuscire a camminare su questo tratto di
  autostrada per \tot minuti senza diventare vittima di un incidente.
  Qual è la probabilità che il Sig. X vinca questa assurda scommessa?}
\text{name_answer=Probabilità di vittoria}
#endif
#if defined TARGET_rg
\text{name_color=rossa,rosse,verde,verdi}
\text{name_statement=In un sacchetto sono contenute ,palline rosse e ,palline verdi.
  Se estraiamo casualmente, palline dal sacchetto}
\text{name_statement2=qual è la probabilità che siano }
\text{name_and=e}
#endif
