The general formula of an arithmetic sequence is:

<ul>
    <li> The Recursion formula: u<sub>n+1</sub> = <em>r</em> &times; u<sub>n</sub></li>
    Wherein u<sub>0</sub> = b</li> 
    <li> the Formula: u<sub>n</sub> = b &times; <em>r</em><sup>n</sup> <br />
</ul>
A small example:<br />
    Given the arithmetic sequence with 
    U<sub>8</sub>=26
    and
    U<sub>9</sub>=29
    <br />
    Calculate the terms U<sub>1</sub> and U<sub>3</sub> of this sequence...
    <br />You may fill in:<br />
    <textarea cols="20" rows="4" readonly="readonly">U1=5 
and
U3=11</textarea>
 <br />or <br />
    <textarea cols="20" rows="4" readonly="readonly">U_1=5 U_2=11</textarea>
    
!if $subject isitemof 3,8
    
    Take care: we check your answers 'case sensitive'
    
If being asked to give the <b>Recursion formula</b>:<br />
    <textarea cols="20" rows="4" readonly="readonly">U(n+1)=4*U(n) 
    with U(0)=5</textarea>
    
    If being asked the <b>Formula</b>:
    <br />
    <textarea cols="20" rows="4" readonly="readonly">
    Un=21+4n
    or something like:
    U_n=21+4*n
    </textarea> 
!endif
<hr />			
