#if defined TARGET_afflin
\text{name_question=Quelle est la fonction linéaire associée à la fonction affine}
\text{name_answer=Fonction linéaire}
#endif
#if defined TARGET_afflin2
\text{name_enonce=Soit \(f\) une fonction affine vérifiant,
  et, Elle est&nbsp;}
\text{name_answer=Il faut donner tous les choix possibles.}
\text{name_list=linéaire, constante, ni linéaire ni constante}
#endif
#if defined TARGET_affine
\text{liste=het origineel, het beeld}
\text{name_enonce=Zij \(f\) de lineaire functie gedefinieerd door,
   Bepaal,van ,onder}
#endif
#if defined TARGET_drcadran
\text{name_enonce=De rechte \(d\) stelt de lineaire functie}
\text{name_enonce2=Het x-coordinaat van een punt \(A\) dat op de rechte \(d\) ligt is gelijk aan}
\text{name_question=Stel je de rechte voor en zeg in welk kwadrant punt \(A\) ligt}
\text{name_hint=Hier is de grafiek van de rechte}
\text{name_answer=Kwadrant}
#endif
#if defined TARGET_droiteanim
\text{choix= alleen de helling,
  alleen het y-coordinaat van de oorsprong,
  de helling en het y-coordinaat van de oorsprong}
\text{name_enonce=Hier is de geanimeerde lijn met vergelijking}
\text{name_question=Wat varieert er: de helling \(a\),
  het y-coordinaat van de oorsprong \(b\) of allebei}
\text{name_answer=Hetgene dat varieert}
#endif
#if defined TARGET_droitepar
\text{name_question=Geef de vergelijking van de lijn die evenwijdig
  loopt aan de getrokken lijn,  door het punt}
#endif
#if defined TARGET_fonctlin
\text{name_enonce=Bepaal \(f(x)\) voor de linear functie \(f\) als}
#endif
#if defined TARGET_itineraire
\text{name_enonce=Wij willen van punt \(\A\) naar punt \(\B\), waarbij we door alle
  punten van het grafiek gaan en zodanig dat twee opeenvolgende punten altijd
  een coordinaat hetzelfde hebben. Geef een route door de volgorde van de punten
  te geven zoals je er langsgaat}
\text{name_inst=Schrijf de namen van de punten met kommas ertussen.}
\text{name_question=Route}
#endif
