#if defined TARGET_affine
# define TITRE Image et antécédent; application affine
#endif
#if defined TARGET_afflin
# define TITRE Fonctions linéaire et affine
#endif
#if defined TARGET_afflin2
# define TITRE Fonction affine ou linéaire ?
#endif
#if defined TARGET_drcadran
# define TITRE Droite et cadran
#endif
#if defined TARGET_droiteanim
# define TITRE Droite animée
#endif
#if defined TARGET_droitepar
# define TITRE Équation de droite affine parallèle
#endif
#if defined TARGET_eqdroite
# define TITRE Déterminer graphiquement une équation de droite (niveau 1)
#endif
#if defined TARGET_eqdroite1
# define TITRE Déterminer graphiquement une équation de droite (niveau 2)
#endif
#if defined TARGET_fonctlin
# define TITRE Fonction linéaire 1
#endif
#if defined TARGET_itineraire
# define TITRE Itinéraire dans le plan
#endif
