#if defined TARGET_affine
# define TITRE_nl Beeld en origineel; lineaire functie
#endif
#if defined TARGET_afflin
# define TITRE_nl Fonctions linéaire et affine
#endif
#if defined TARGET_afflin2
# define TITRE_nl Fonction affine ou linéaire ?
#endif
#if defined TARGET_drcadran
# define TITRE_nl Lijn en kwadrant
#endif
#if defined TARGET_droiteanim
# define TITRE_nl Geanimeerde lijn
#endif
#if defined TARGET_droitepar
# define TITRE_nl Vergelijking van een evenwijdige lijn
#endif
#if defined TARGET_eqdroite
# define TITRE_nl Vergelijking van een lijn
#endif
#if defined TARGET_eqdroite1
# define TITRE_nl Vergelijking van een lijn (niveau 2)
#endif
#if defined TARGET_fonctlin
# define TITRE_nl Lineaire functie
#endif
#if defined TARGET_itineraire
# define TITRE_nl Route op een kaart
#endif
