!read language lang/names

!header

$name_intro

<span class="wims_mod_title">$module_title</span> $name_intro2.
!form new
<fieldset class="property_fields">
<legend>$wims_name_setup</legend>
<input type="hidden" name="module" value="$module" />
!default rows=2
!default cols=3
!default kind=sum
<p>
$name_intro3
!formselect rows from 2 to 8
 <label for="rows">$name_rows</label> $name_and
!formselect cols from 2 to 8
 <label for="cols">$name_cols</label>,
 $name_intro4
</p><p>
$name_intro5
!formselect kind list sum,product prompt $n_sum,$n_product
$name_intro6
$name_intro8
</p><p>
$name_intro7
!default allow=120
!formselect allow list 30,60,90,120,180,240,300,420,600,900,1200,1800\
	prompt 0.5,1,1.5,2,3,4,5,7,10,15,20,30
 <label for="allow">$name_minutes</label>.
</p>
</fieldset>
<div class="wimscenter"><input type=submit value="$name_start"></div>
!formend

!tail
