!if $taal=nl
    <tt>I'm sorry, this (english) page is not yet fully functional...</tt>
!endif    
<div align="center">
<table bgcolor="$bgcolor2" width="90%">
    <td>
    <div align="center">
    <h4>
    <p align=center>
    <table border=1 width="100%">
        <td>函数</td><td>意义</td>
        <tr>
        <td>
        !htmlmath y=a+sin(x)
        </td>
        <td>
        垂直平移 <font color=$fontcolor3>a</font>
        </td>
        <tr>
        <td>
        !htmlmath y=a*sin(x)
        </td>
        <td>
        垂直放大 <font color=$fontcolor3>a</font> 倍
        <br>在物理中相当于强度,<br>
        在声学中 <em>a</a> 是音量
        </td>
        <tr>
        <td>
        !htmlmath y=sin(a+x)
        </td>
        <td>
        水平平移 <font color=$fontcolor3>a</font><br>
        在技术中是相位变化
        </td>
        <tr>
        <td>
        !htmlmath y=sin(a*x)
        </td>
        <td>
        用 <font color=$fontcolor3>a</font> 改变周期<br>
        在物理中相当于频率的变化,<br>
        在声学中 <font color=$fontcolor3>a</font> 相当于音高的变化
        </td>
    </table>
    </td>
    <tr>
    <td>    
    <applet codebase="$appletdir" archive="jcm1.0-config.jar" code="FamiliesOfGraphs.class" width="600" height="400"> 
    <param name="Parameter1" value="a 0 10 1"> 
    <param name="Function" value="a+sin(x)">  
    <param name="UseFunctionInput" value="no"> 
    <param name="XLabel" value="x-as"> 
    <param name="YLabel" value="y-as"> 
    <param name="UseGrid" value="yes"> 
    <param name="GridColor" value="orange">  
    <param name="UseLimitsPanel" value="no"> 
    <param name="BackgroundColor" value="black"> 
    <param name="Insets" value="5"> 
    <param name="CanvasColor" value="white"> 
    <param name="GraphColor" value="red"> 
    <param name="AxesColor" value="blue"> 
    <param name="PanelBackground" value="yellow"> 
    <param name="BorderWidth" value="0"> 
    <param name="PanelTitle" value="Som voor $wims_user"> 
    <param name="TitleBackground" value="yellow"> 
    <param name="Example1" value="垂直平移:a+sin(x) ; a+sin(x)">
    <param name="Example2" value="强度放大(音量):a*sin(x) ; a*sin(x)">
    <param name="Example3" value="水平平移:sin(x+a) ; sin(x+a)">
    <param name="Example4" value="频率/周期(音高):sin(x*a) ; sin(x*a)">
    $geenjava</applet>
    
    </td>
</table>
  
  
  
