!if $wims_user=supervisor
    !if $type=3 
    !read printbaar.phtml
    !exit
    !endif
    !if $type = 1 
    !read debug.phtml
    !exit
    !endif
!endif

!set n=$teller
请用正确的语法写出你的回答: <em><font color=garkgreen>f(x)=sin(x)</font></em> 

而 <font color=red>不是</font> : <em><font color=red>f(x)=sinx</font></em>
<p>
!if $nivo=1
    所需的公式是如下类型的:
    <img src="$module_dir/gifs/nivo$nivo.$(SIN$n).gif">
    <ul>
    <li>
        <em> f(x)=d+b*$(SIN$n)(x+c)</em> 
    </li>
    <li>
        <em> f(x)=d-b*$(SIN$n)(c*x) </em>
    </li>
    <li>
        <em> f(x)=d*$(SIN$n)(x+c)</em>
    </li>
    <li>
        <em> f(x)=$(SIN$n)(x+c)</em>
    </li>
    <li>
        <em> f(x)=$(SIN$n)(c*x+d)  </em>
    </li>
    <li>
        <em> f(x)=c+$(SIN$n)(x)  </em>  
    </li>
    <li>
        <em> f(x)=b-$(SIN$n)(x)  </em>
    </li>
    !if $instinker=1
        <li>
        <em> f(x)=c+$(SIN$n)(x)/d  </em>
        </li>
        <li>
        <em> f(x)=b-$(SIN$n)(d*x)/c  </em>
        </li>
    !endif
    </ul>
    及其变形....<br><br>
    !if $instinker=0
    <br>这里不涉及分数...
    !else
    <br>但是这里混入了分式<br>
    想一想当 <em><b>f(x)=$(SIN$n)(x)/d</b></em> 内的 <em>d</em> 趋于 0 时会怎样
    !endif
    <br><b>
    有时把滑尺调整到 "零" 是有用的, 别的时候把它设为 "1" 更方便
    </b>
!endif

!if $nivo=2

    所需公式具有一般形式:<br>
    <img src="$module_dir/gifs/nivo$nivo.$(SIN$n).gif">
    <br>
    以下的动画显示一个 "移动的" 正弦函数.<br>
    '变量' <b><em>s</em></b> 用于动画.
    "s" 分 20 步从 <b>0</b> 变到 <b>1</b>. 
    <ul>
    <li><font color=purple size=+1> 
        <em>  0 < s < 1 </em>
        &nbsp;一条水平直线
        <font>
    </li>
    <li><font color=$fontcolor3 size=+1>
        <em> f(x)= $(SIN$n)(s*x) </em>
        <font>
    </li>
    <li><font color=$fontcolor6 size=+1>
        <em> f(x)= s*$(SIN$n)(x+s) </em>
        <font>
    </li>
    <li><font color=$fontcolor4 size=+1>    
            <em> f(x)= s+$(SIN$n)(x) </em>
        <font>
    </li>    
    </ul>
    <p align="center">
    <img src=$module_dir/gifs/goniohelp.gif>

!endif
<hr>
<p>
    
!read $authordir/algemenehelp.phtml

