\text{name_tabl=Remplir le tableau&nbsp;}
#if defined TARGET_oefechelle1 || defined TARGET_oefechellereelle1 || defined TARGET_oefechelcarte1
\text{name_head=Longueurs sur la carte en cm, Longueurs réelles en cm}
# if defined TARGET_oefechelle1
\text{name_enonce=Sur un plan, une longueur de,est représentée par une longueur
  de ,cm sur la carte.}
\text{name_enonce2=L'échelle du plan est}
# endif
# if defined TARGET_oefechellereelle1
\text{name_enonce= Nous avons un plan à l'échelle,
  Nous avons mesuré sur ce plan une longueur de}
\text{name_enonce2=La longueur réelle correspondante est de }
# endif
# if defined TARGET_oefechelcarte1
\text{name_enonce=Nous avons un plan à l'échelle ,
  La longueur réelle est de}
\text{name_question=La longueur sur la carte sera de}
# endif
#endif
#if defined TARGET_oefprobprop1euro
\matrix{t=Une cuillère à soupe de farine contient 15 g de farine et trois cuillères contiennent 45 g.,2,La masse en g,La farine en g,Les grammes,Le nombre de cuillères,La soupe,La cuillère,15,45,1,3
Un carré de 3 m de longueur de côté a un périmètre de 12 m et  un carré de 6 m de côté a un périmètre de 24 m.,1,Le périmètre en m,Le carré en m,Le côté en m,La longueur en m,Le carré en m,Mètre,12,24,3,6
Pour un effectif de 3 personnes&#130; il faut une baguette de pain. Pour un goûter de 12 personnes&#130; j'achète 4 baguettes.,1,Le nombre de baguettes,Le pain en g,La baguette en g,Effectif,Le goûter,Le pain en g,1,4,3,12
Pour un effectif de 4 personnes&#130; on compte une masse de 250 g de spaghettis. Pour 12 personnes&#130; je prévois 750 g.,2,La masse en g,Le gramme,Les spaghettis en g,Effectif,Cuisson en min,Spaghettis en g,250,750,4,12
Pour une durée d'une heure&#130; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#130; il est tombé 60 mm.,2,La hauteur en mm,La pluie en mm,L'eau en mm,La durée en h,Heure,La pluie en mm,20,60,1,3
Un automobiliste  parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 4 h.,2,La distance en km,Le voyage en km, km,La durée en h,Le voyage en h,Le nombre d'automobilistes,120,240,2,4
Une moto consomme en moyenne un volume de 4 litres de carburant pour 100 kilomètres. Pour parcourir 50 km&#130; elle a consommé 2 litres.,1,La distance en km,La moto en &euro;,Kilomètres,Le volume en l,Le carburant en l,Le parcours en km,100,50,4,2
Une masse de 2 kg de poisson coûte  32 &euro;.  Pour 6 kg&#130; je paierai 96 &euro;.,1,Le prix en &euro;,Nombre de poissons,L'euro,La masse en kg,Le poisson en kg, kg,32,96,2,6
Un mètre de tissu coûte 12 &euro;. Si j'en achète une longueur de 5 m&#130; je paye 60 &euro;.,1,Le prix en &euro;,Le tissu en &euro;,L'euro,La longueur en m,Mètres,Achats en m,12,60,1,5
Dans un lotissement&#130; un terrain de 800 m² d'aire coûte 100 000 &euro; et un autre de 1 200 m² coûte 150 000 &euro;.,1,Le prix en &euro;,L'euro,Le terrain en m²,L' aire en m²,Le lotissement en m²,Terrain en &euro;,100 000,150 000,800,1 200}
#endif
#if defined TARGET_oefprobprop1
\matrix{t=Une cuillère à soupe de farine contient 15 g de farine et trois cuillères contiennent 45 g.,2,La masse en g,La farine en g,Les grammes,Le nombre de cuillères,La soupe,La cuillère,15,45,1,3
Un carré de 3 m de longueur de côté a un périmètre de 12 m et  un carré de 6 m de côté a un périmètre de 24 m.,1,Le périmètre en m,Le carré en m,Le côté en m,La longueur en m,Le carré en m,Mètre,12,24,3,6
Pour un effectif de 3 personnes&#130; il faut une baguette de pain. Pour un goûter de 12 personnes&#130; j'achète 4 baguettes.,1,Le nombre de baguettes,Le pain en g,La baguette en g,Effectif,Le goûter,Le pain en g,1,4,3,12
Pour un effectif de 4 personnes&#130; on compte une masse de 250 g de spaghettis. Pour 12 personnes&#130; je prévois 750 g.,2,La masse en g,Le gramme,Les spaghettis en g,Effectif,Cuisson en min,Spaghettis en g,250,750,4,12
Pour une durée d'une heure&#130; il est tombé 20 mm de hauteur d'eau de pluie. En trois heures&#130; il est tombé 60 mm.,2,La hauteur en mm,La pluie en mm,L'eau en mm,La durée en h,Heure,La pluie en mm,20,60,1,3
Un automobiliste  parcourt une distance de 120 km en 2 h. Son voyage de 240 km a une durée de 4 h.,2,La distance en km,Le voyage en km, km,La durée en h,Le voyage en h,Le nombre d'automobilistes,120,240,2,4
Une moto consomme en moyenne un volume de 4 litres de carburant pour 100 kilomètres. Pour parcourir 50 km&#130; elle a consommé 2 litres.,1,La distance en km,La moto en &euro;,Kilomètres,Le volume en l,Le carburant en l,Le parcours en km,100,50,4,2
Une masse de 2 kg de poisson coûte 800 F.  Pour 6 kg&#130; je paierai 2 400 F.,1,Le prix en F,Nombre de poissons,Le Franc,La masse en kg,Le poisson en kg, kg,800,2 400,2,6
Un mètre de tissu coûte 1 200 F. Si j'en achète une longueur de 5 m&#130; je paye 6 000 F.,1,Le prix en F,Le tissu en F,Le Franc,La longueur en m,Mètres,Achats en m,1 200,6 000,1,5
Dans un lotissement&#130; un terrain de 800 m² d'aire coûte 1 200 000 F et un autre de 1 200 m² coûte 1 800 000 F.,1,Le prix en F,Le Franc,Le terrain en m²,L' aire en m²,Le lotissement en m²,Terrain en F,1 200 000,1 800 000,800,1 200}
#endif
#if defined TARGET_oefprobprop2 || defined TARGET_oefprobprop3
\matrix{t=, cuillères à soupe de farine contiennent une masse de, de farine. Combien contiennent , cuillères ?,,g,La masse en g,La farine en g,Les grammes,Le nombre de cuillères,La soupe,La cuillère,10,20,1,3,20,1
Un carré de , mètres de longueur de côté a un périmètre de,. Quel sera le périmètre d'un carré de , de longueur de côté ?,m,m,Le périmètre en m,Le carré en m,Le côté en m,La longueur en m,Le carré en m,Mètre,4,4,1,3,50,1
Pour un effectif de , personnes&#130; il faut , de pain. Combien de baguettes dois-je acheter pour le goûter de, personnes ?,,baguette(s),Le nombre de baguettes,Le pain en g,La baguette en g,Effectif,Le goûter,Le pain en g,1,1,1,2,7,3
Pour un effectif de , personnes&#130; on compte une masse de, de spaghettis. Quelle masse de spaghettis faut-il prévoir pour un effectif de, personnes ? ,,g,La masse en g,Le gramme,Les spaghettis en g,Effectif,Cuisson en min,Spaghettis en g,15,25,10,3,15,1
Pour une durée de , heures&#130; il est tombé, de hauteur d'eau de pluie. Quelle hauteur d'eau tombera-t-il pour une durée de, ?,h,mm,La hauteur en mm,La pluie en mm,L'eau en mm,La durée en h,Heure,La pluie en mm,5,30,1,2,12,1
Un automobiliste parcourt en , heures une distance de , . Quelle distance parcourt-il en, ?,h,km,La distance en km,Le voyage en km, km,La durée en h,Le voyage en h,Le nombre d'automobilistes,40,90,1,2,12,1
Pour , kilomètres&#130; une moto consomme en moyenne un volume de , de carburant. Quel volume de carburant consommera-t-elle pour parcourir, ?,km,L,Le volume en l,Le carburant en l,Le parcours en km,La distance en km,La moto en &euro;,Kilomètres,6,14,0.5,2,10,100
Une masse de , kg de tomates coûtent ,. Quel sera le prix d'une masse de, de tomates ?,kg,&euro;,Le prix en &euro;,Nombre de tomates,L'euro,La masse en kg,La tomate en kg, kg,3,9,0.5,2,10,1
, mètres de tissu coûtent ,. Quel sera le prix d'une longueur de, de tissu ?,m,&euro;,Le prix en &euro;,Le tissu en &euro;,L'euro,La longueur en m,Mètres,Achats en m,5,20,1,2,10,1
Une masse de , kg de fraises coûtent ,. Quel sera le prix d'une masse de, de fraises ?,kg, &euro;,Le prix en &euro;,L'étiquette en &euro;,La lecture en &euro;,La masse en kg,Les fraises en kg, kg,4,12,0.5,2,10,1}
\text{name_enonce=Nous avons des grandeurs proportionnelles dans le problème suivant&nbsp;}
\text{name_answer=Réponse}
#endif
#if defined TARGET_oefprobprop1 || defined TARGET_oefprobprop1euro
\text{name_enonce=Compléter le tableau de proportionnalité en
  choisissant la bonne grandeur et les bonnes valeurs&nbsp;}
#endif
#if defined TARGET_tabprop || defined TARGET_tabproportion || defined TARGET_tabprop0
\text{name_enonce=Compléter le tableau de proportionnalité suivant&nbsp;}
\text{name_question=Le coefficient de proportionnalité est&nbsp;}
#endif
#if defined TARGET_oeftablprop4 || defined TARGET_oeftablprop4euro || defined TARGET_oeftablprop5 || defined TARGET_oeftablprop5euro || defined TARGET_oeftableprop1 || defined TARGET_oeftableprop1euro || defined TARGET_oeftablprop2 || defined TARGET_oeftablprop2euro || defined TARGET_oeftablprop1 || defined TARGET_oeftablprop1euro || defined TARGET_oeftablprop0 || defined TARGET_oeftablprop0euro || defined TARGET_oeftablprop6 || defined TARGET_oeftablprop6euro
\text{name_enonce=Compléter le tableau de proportionnalité suivant&nbsp;}
\text{name_head=Nbre d'objets,Prix en}
#endif
#if defined TARGET_oeftablprop3
\text{name_enonce=Nous avons un segment qui a pour longueur,
Sur une droite, nous plaçons plusieurs fois ce segment bout à bout.}
\text{name_question=Compléter le tableau de proportionnalité suivant&nbsp;}
\text{name_head=Nbre de segments,Longueur en cm}
#endif
#if defined TARGET_oeftablprop6 || defined TARGET_oeftablprop4 || defined TARGET_oeftablprop5 || defined TARGET_oeftablprop1 || defined TARGET_oeftablprop2 || defined TARGET_oeftablprop0
\text{name_money=Francs}
#endif
#if defined TARGET_oeftablprop6euro || defined TARGET_oeftablprop4euro || defined TARGET_oeftablprop5euro ||  defined TARGET_oeftablprop2euro || defined TARGET_oeftablprop1euro || defined TARGET_oeftablprop0euro || defined TARGET_oeftablprop1euro || defined TARGET_oeftablprop0euro
\text{name_money=euro}
#endif
#if defined TARGET_distance || defined TARGET_oefvitesse1 || defined TARGET_oefduree1 || defined TARGET_oefdistance1
\text{name_head=Durée en min,Distance en km}
#endif
#if defined TARGET_oefvitesse1
\text{name_enonce=Une voiture a parcouru une distance de,
  en }
\text{name_question=La vitesse moyenne est de}
#endif
#if defined TARGET_oefduree1
\text{name_enonce=Une voiture roule à une vitesse moyenne de,
  Elle a parcouru une distance de}
\text{name_question=La durée du parcours est de}
\text{name_question2=Si je convertis en heures et minutes}
#endif
#if defined TARGET_oefdistance1
\text{name_enonce=Une voiture roule à une vitesse moyenne de ,
  Le voyage a duré}
\text{name_question=La distance parcourue est de}
#endif
#if defined TARGET_distance
\matrix{name_M=Un piéton, marche,La promenade
Un vélo, roule,L'excursion
Une voiture, roule,Le voyage
Un cheval, galope,La chevauchée}
\text{name_enonce=à une vitesse moyenne de, a duré}
\text{name_question=La distance parcourue est}
#endif
