#if defined TARGET_trinome1 || defined TARGET_trinome2 || defined TARGET_trinome3 || defined TARGET_trinome4 || defined TARGET_trinome5
# define TITRE Trinôme du second degré
#endif
#if defined TARGET_ineqgrpara1 || defined TARGET_ineqgrpara2 || defined TARGET_ineqgrpara3 || defined TARGET_ineqgrpara4 || defined TARGET_ineqgrpara5
# define TITRE Inéquation graphique et parabole
#endif
#if defined TARGET_ineqgrhyper1 || defined TARGET_ineqgrhyper2 || defined TARGET_ineqgrhyper3 || defined TARGET_ineqgrhyper4 || defined TARGET_ineqgrhyper5
# define TITRE Inéquation graphique et hyperbole
#endif
#if defined TARGET_ineqalgpara1 || defined TARGET_ineqalgpara2 || defined TARGET_ineqalgpara5
# define TITRE Inéquation algébrique carrée
#endif
#if defined TARGET_ineqalgpara3
# define TITRE Inéquation algébrique
#endif
#if defined TARGET_ineqalgpara4 || defined TARGET_ineqalgpara6
# define TITRE Inéquation algébrique produit
#endif
#if defined TARGET_homographie1 || defined TARGET_homographie2 || defined TARGET_homographie3 || defined TARGET_homographie4 || defined TARGET_homographie5
# define TITRE Fonction homographique
#endif
#if defined TARGET_eqgrparabole1 || defined TARGET_eqgrparabole2 || defined TARGET_eqgrparabole3 || defined TARGET_eqgrparabole4 || defined TARGET_eqgrparabole5
# define TITRE Résolution graphique et parabole
#endif
#if defined TARGET_eqgrhyperbole1 || defined TARGET_eqgrhyperbole2 || defined TARGET_eqgrhyperbole3 || defined TARGET_eqgrhyperbole4 || defined TARGET_eqgrhyperbole5
# define TITRE Résolution graphique et hyperbole
#endif
#if defined TARGET_eqalgpara1 || defined TARGET_eqalgpara2
# define TITRE Équation algébrique carrée
#endif
#if defined TARGET_eqalgpara3
# define TITRE Équation algébrique
#endif
#if defined TARGET_eqalgpara4 || defined TARGET_eqalgpara5 ||TARGET_eqalgpara6
# define TITRE Équation algébrique produit
#endif
#if defined TARGET_eqalghyper1 || defined TARGET_eqalghyper2 || defined TARGET_eqalghyper3 || defined TARGET_eqalghyper4 || defined TARGET_eqalghyper5
# define TITRE Équation algébrique quotient
#endif
#if defined TARGET_ineqalghyper1 || defined TARGET_ineqalghyper2 || defined TARGET_ineqalghyper3 || defined TARGET_ineqalghyper4 || defined TARGET_ineqalghyper5
# define TITRE Inéquation algébrique quotient
#endif

