<b>Types de transformations </b>
<table class="wimstable">
<tr>
<td>
!set wims_ref_id=confparm11
!formcheckbox confparm1 list 1 prompt \(\sqrt{p} \rightarrow a \sqrt{b}\)
</td><td>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 2 prompt \(p \sqrt{q} \rightarrow \sqrt{a}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm13
!formcheckbox confparm1 list 3 prompt \(p \sqrt{q} \sqrt{r} \rightarrow a \sqrt{b}\)
</td><td>
!set wims_ref_id=confparm14
!formcheckbox confparm1 list 4 prompt \(p \sqrt{q} \sqrt{r} \rightarrow \sqrt{a}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm15
!formcheckbox confparm1 list 5 prompt \(p \frac{\sqrt{q}}{\sqrt{r} } \rightarrow a \sqrt{b}\)
</td><td>
!set wims_ref_id=confparm16
!formcheckbox confparm1 list 6 prompt \(p \frac{\sqrt{q}}{\sqrt{r} } \rightarrow \sqrt{a}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm17
!formcheckbox confparm1 list 7 prompt \(\sqrt{p} + \sqrt{q} \rightarrow a \sqrt{b}\)
</td><td>
!set wims_ref_id=confparm18
!formcheckbox confparm1 list 8 prompt \(u \sqrt{p} \pm v \sqrt{q} \rightarrow a \sqrt{b}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm19
!formcheckbox confparm1 list 9 prompt \(\sqrt{p} + \sqrt{q} + \sqrt{r}\rightarrow a \sqrt{b}\)
</td><td>
!set wims_ref_id=confparm110
!formcheckbox confparm1 list 10 prompt \(u \sqrt{p} \pm v \sqrt{q} \pm w \sqrt{r} \rightarrow a \sqrt{b}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm111
!formcheckbox confparm1 list 11 prompt \((\sqrt{p} + q)^2 \rightarrow a + b \sqrt{c}\)
</td><td>
!set wims_ref_id=confparm112
!formcheckbox confparm1 list 12 prompt \((\sqrt{p} + \sqrt{q})^2 \rightarrow a + b \sqrt{c}\)
</td>
</tr>
</table>
<div class="formHelp">
Sélectionnez le ou les types de transformations à effectuer.
</div><br class="spacer">
