!header
!read Exindex
Ta zbirka vaj omogoèa utrjevanje aritmetiènih operacij.
Re¹evalec mora sestaviti pravilno enaèbo z vstavljanjem 
ustreznih èlenov ali operacij na predvidena mesta.
 <p>
Z razlièno izbiro nastavitev lahko vplivate na zahtevnost naloge.
Za osnovno ¹olo bodo npr. zanimive naloge, ki vsebujejo
naravna in cela ¹tevila, ulomke in decimalna ¹tevila, 
za srednjo pa naloge 
s koreni ali kompleksnimi ¹tevili. 
Na zahtevnost naloge pa seveda vpliva tudi ¹tevilo iskanih èlenov,
vrsta uporabljenih operacij, uporaba oklepajev, ¹tevilo odveènih elementov 
in podobne nastavitve.


!read oef/intromenu.phtml
!tail
