!set n=!recordcnt src/data
!reset objlist
!for i=1 to $n
 !set l=!record $i of src/data
 !set l=!line 1 of $l
 !set objlist=!append item $l to $objlist
!next i

<tr><td align=center>Elementi za vstavljanje:
</td><td>
!set wims_formselect_switch=multiple size=5
!set confparm3=50 0
!formselect confparm3 list 1 0,2 0,3 0,\
	50 0,0 1,0 2,\
	0 50,1 1,2 1,\
	2 2,50 50\
	prompt \
	1 èlen, 2 èlena, 3 èleni,\
	Vsi èleni, 1 operacija, 2 operaciji,\
	Vse operacije, 1 èlen in 1 operacija,2 èlena in 1 operacija,\
	2 èlena in 2 operacije, Vsi èleni in vse operacije
!reset wims_formselect_switch
<tr><td align=center>Vrsta èlenov:
</td><td>
!set confparm1=1
!formselect confparm1 from 1 to $n prompt $objlist
</td>
<tr><td align=center>Vrsta operacij:
</td><td>
!set confparm2=2
!formselect confparm2 from 1 to 3 prompt \
	+ in -, + - &times;, + - &times; &divide;
<tr><td align=center>©tevilo odveènih elementov:
</td><td>
!set confparm4=1
!formselect confparm4 from 0 to 5
