!set wims_backslash_insmath=yes
!read language lang/names
!header
!read defaults

<p>
$name_intro1
</p>
!form new
<input type="hidden" name="module" value="$module" />
$name_intro2
<fieldset class="property_fields">
<legend>$wims_name_setup</legend>
<ul>
<li>
<label for="type">$name_intro3</label>
!formselect type from 1 to 3 prompt $name_prompt1
</li><li>
<label for="style">$name_type&nbsp;:</label>
!set wims_formselect_switch=multiple
!formselect style list 1,3,4,5 prompt $name_prompt2
</li><li>
!set wims_formselect_switch=
$name_chinese</label>
!formselect askcnt from $askcntmin to $askcntmax
<label for="askcnt">$(name_numberequation[1])</label>
$(name_numberequation[2])
!formselect miss list no,yes prompt $name_prompt3
<label for="miss">$name_good</label>.
</li><li>
$name_session
!formselect repeat from $repeatmin to $repeatmax
<label for="repeat">$name_questions</label>
$name_Score.
</li></ul>
</fieldset>
<div class="wimscenter wimsform">
<input type="submit" value="$wims_name_work" />
</div>
!formend

!read related.phtml lines, parametric_curves

!tail
