
$name_present1
!if $givtype=2
  $name_present2
   <p class="wimscenter">
  !set ins_attr=alt="$name_attribut1"
  !set wims_ins_alt=empty
  !insplot [-$range:$range] [-$range:$range] ($ba)*x-($ca) notitle
   </p>
!else

!if $givtype=1
    $name_equations
 !else
    $name_equation
 !endif
 <div class="wimscenter" style="padding:10px">
 !set formula=!line $givtype of x = $a*t+$c1, y = $b*t+$c2\
	\
	$b*x-$a*y = $c\
	y = $ba*x-$ca\
	x = $ab*y+$cb
 \($formula\)
  </div>
!endif
!if $asktype=2
  $name_question1 $name_clickon
!else
  $name_question2
  $name_clickon
!endif
<div>
!read choice.$asktype.phtml
</div>
