!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes

!if $lang_choice=fr or $lang=fr
  !set name_intro1=Expression à trouver&nbsp;:
  !set name_intro2=à partir d'étiquettes (par défaut)
  !set name_intro3=parmi une liste de propositions
  !set name_intro4=Si vous cochez les deux choix, le serveur choisira aléatoirement pour chaque génération de l'exercice une des deux possibilités.
  !goto hook
!endif

:hook
<div class="field box">
<strong>$name_intro1</strong>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formcheckbox confparm1 list 1,2 prompt $name_intro2, $name_intro3 
</ul>
$name_intro4
</div>
!default confparm1=1
