# precheck for equation.proc
n=$counter
# checkt alleen lijnen.
!if $(reply$n)=?
    maxscore=0
    remark$n=$NOK
    goback=0
 !exit
!endif
ta=!itemcnt $(reply$n)
# correct answer is a function x(t)=3*x
tg=!itemcnt $(answer$n)
# if student_reply is a line produced by 2 points:
# line=r1:slope=-1*(-0.22196 )/( 0.97505 ):constant=(2.7303)/( 0.97505 ):affine ,
# point=p2:x=-1.980952380952381:y=2.3492063492063497 ,
# point=p1:x=-5.104761904761904:y=1.6380952380952385 , 

# if student_reply is a function:
# function=function1:3*x-1.0000002 ,

# take care: there is a trailing "," not introduced by scripts but somehow by the browser?
!if $rounding<1
    rnd=100
!else
    rnd=$rounding
!endif
found=0
!for p=1 to $ta
    A=!item $p of $(reply$n)
    !if $A != $empty
	test=!replace internal function= by @ in $A
	!if @ isin $test
	    # it is a function
	    A=!replace internal : by , in $A
	    rep=!item 2 of $A
	    rep= y = $rep
	    !increase found
	!else
	    test=!replace internal line= by @ in $A
	    !if @ isin $test
		# it's  line build from 2 points
		!increase found
		A=!replace internal : by , in $A
		chk=!item 3 of $A
		!if $chk=perpendicular
		    # x=345
		    rep=!item 2 of $A
		!else
		    !if $chk=horizontal
			# y=123
			rep=!item 2 of $A
		    !else
			# slope=1/3
			rc=!item 2 of $A
			rc=!replace internal = by , in $rc
			rc=!item 2 of $rc
			rc=$[(round($rnd*$rc))/$rnd]		
		    
			# constant=0.234
		        c=!item 3 of $A
			c=!replace internal = by , in $c
			c=!item 2 of $c
			c=$[(round($rnd*$c))/$rnd]
			!if $c=0
			    fun=$[$rc]*x
			!else
		    	    fun=!rawmath $[$rc]*x+$[$c]
		        !endif
			# this is the line
			rep= y = $fun
		    !endif
		!endif
	    !endif
	!endif
	!if $found > $tg
	    errortext=Je hoeft hier maar $tg grafiek(en) te tekenenen...
	    goback=1
	    maxscore=$[$maxscore*$P8]
	    !exit
	!endif
    !endif
!next t

reply$n=$rep

!readproc $checkdir/equation.proc


reply$n=!replace internal x by t in $(reply$n)
reply$n=!replace internal y by x(t) in $(reply$n)
!exit
