<center><u><font size=+2> Formulaire de trigonométrie </font></u></center>

!let dessin=line 20,20,20,120,black \
line 20,120,220,120,black \
line 20,20,220,120,black \
line 21,110,30,110,red \
line 30,110,30,119,red \
text black,10,115,medium,A \
text black,10,10,medium,B \
text black,230,115,medium,C

<u><b>Relation trigonométrique dans un triangle rectangle :</b></u><p>
<table>
<tr>
<td>
\(ABC) est un triangle rectangle en \(A).<p>
\(\cos(\widehat{ABC})=\frac{\mbox{C\^ot\'e adjacent}}{\mbox{Hypot\'enuse}}=\frac{AB}{BC})<p>
\(\sin(\widehat{ABC})=\frac{\mbox{C\^ot\'e oppos\'e}}{\mbox{Hypot\'enuse}}=\frac{AC}{BC})<p>
\(\tan(\widehat{ABC})=\frac{\mbox{C\^ot\'e oppos\'e}}{\mbox{C\^ot\'e adjacent}}=\frac{AC}{AB})
</td>
<td>
!insdraw $dessin
</td>
</table>

<u><b>Formules trigonométriques :</b></u><p>
Soit \(\alpha) un angle aigu, alors :
<blocquote>
<p>\(\cos^2(\alpha)+\sin^2(\alpha)=1)</p>
<p>\(tan(\alpha)=\frac{sin(\alpha)}{cos(\alpha)})</p>
</blockquote>
!! changeto oef/$module_language/help.phtml
