#include "lang_title_fr.inc"
#if defined TARGET_deftangente1 || defined TARGET_definition1 || defined TARGET_distance1 || defined TARGET_calculd1
# define NUM 1
#endif
#if defined TARGET_deftangente2 || defined TARGET_definition2 || defined TARGET_distance2 || defined TARGET_calculd2
# define NUM 2
#endif
#if defined TARGET_deftangente3 || defined TARGET_definition3 || defined TARGET_distance3 || defined TARGET_calculd3
# define NUM 3
#endif
#if defined TARGET_deftangente4 || defined TARGET_definition4 || defined TARGET_distance4 || defined TARGET_calculd4
# define NUM 4
#endif
#if defined TARGET_deftangente5 || defined TARGET_definition5 || defined TARGET_distance5 || defined TARGET_calculd5
# define NUM 5
#endif

\title{TITRE NUM}
