#if defined TARGET_distance1 || defined TARGET_distance2 || defined TARGET_distance3 || defined TARGET_distance4 || defined TARGET_distance5
# define TITRE Distance d'un point à une droite
#endif
#if defined TARGET_definition1 || defined TARGET_definition2 || defined TARGET_definition3 || defined TARGET_definition4 || defined TARGET_definition5
# define TITRE Définition
#endif
#if defined TARGET_calculd1 || defined TARGET_calculd2 || defined TARGET_calculd3 || defined TARGET_calculd4 || defined TARGET_calculd5
# define TITRE Calcul de distance
#endif
#if defined TARGET_deftangente1 || defined TARGET_deftangente2 || defined TARGET_deftangente3 || defined TARGET_deftangente4 || defined TARGET_deftangente5
# define TITRE Définition de la tangente
#endif
