!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur l'écriture complexe 
des transformations du plan.
Il contient des exercices concernant:
<ul>
<li> l'enseignement obligatoire sur la composée de transformations 
complétant le module de Véronique Royer
</li>
<li> l'enseignement de spécialité sur les similitudes.</li>
</ul>

!read oef/$module_language/intromenu.phtml
!tail
