!! Place here the code to show analysis of reply to the exercise

!if $error!=$empty
 !exit
!endif

你的回答: <em>$(text$choice)</em>
<p>

!if $diagnostics=good
 对的! 你的选择是正确的.
!else
 !if $choice=C and $good=C
 你作了正确的选择, 但是你的例子是错的.
 !else
 不对, 你的回答是错的. 正确回答是:
  <font color=blue>$(text$good)</font>
 !endif
!endif
<p>

!if $status=done
 !if $repeat<2
 在这个回答里
 !else
 经过重复了 $repeat 次后
 !endif
 你的得分为 $module_score/10.
!else
 你还需要
 !href cmd=next 重复
$[$repeat-$repeated] 次才能得到成绩.
!endif
<p>
