!form reply
<ul>
<li>
<input type=radio name=choice value=A>A. $textA
<li>
<input type=radio name=choice value=B>B. $textB
<li>
<input type=radio name=choice value=C>C. $textC
!if $exask=yes
 <br>
 对于这种情形, 请给出使条件成立的例子:<br>
 a=<input size=5 name=exa1 value="$exa1">, 
 b=<input size=5 name=exb1 value="$exb1">, <p>
和不能成立的例子:<br>
 a=<input size=5 name=exa2 value="$exa2">, 
 b=<input size=5 name=exb2 value="$exb2">.
!endif
</ul>
<input type=submit value="发送回答">
</form>
