!header

!! The presentation of the exercise.
!read present.phtml

<p><hr> <p>

!if $status=waiting
 !if $error!=$empty
  !read msg.phtml
  <p><hr width=50%> <p>
 !endif
 !! Reply form
 !read form.phtml
 !if $repeatd<1 or $repeated>=$repeat
  <p>
  !href exo_Renew
.
 !endif
!else
 !if $error!=$empty
  !read msg.phtml
  <p><hr width=50%> <p>
 !endif
 !! Analysis of reply
 !read answer.phtml
 !if $repeated<1 or $repeated>=$repeat
  <p>
  !href exo_Again
.
 !endif
 !if $worksheet=$empty
  !href exo_Intro
.
 !endif
!endif

:end
!tail
