# Variable initialisation file.
# This file is read by wims for new sessions.

# content of the file: initialisation of the problem.

!bound wlevel between integer 1 and 3 default 2
!bound slevel between integer 1 and 4 default 2
!bound repeat between integer 1 and 10 default 1

exask=!item $slevel of no,yes,yes,yes
scoreexp=!item $slevel of 1,1,1.5,2.3

repeated=0
goodgot=0
wims_module_log=$cmd level=$wlevel repeat=$repeat exask=$exask
status=start
