!header

<b><font color=red>$module_title</font></b>
是一种网上七巧板拼图游戏, 碎片只能按行或按列作横向或纵向滑动,
而且保证最后能得到正确的图形.
<p>
<b><font color=red>$module_title</font></b>
游戏几乎不需要数学知识, 
相反的, 你可以去看看游戏
!href module=U2/algebra/qpuzzle Q-Puzzle
, 了解拚图游戏也会用到相当深的数学概念。
<p>
!form new
<input type=hidden name=module value="$module">
 选择你喜欢的片数:
!read data/spuzzle/photindex
!default level=2x3
!formselect level list $levels
&nbsp;<input type=submit value="开始游戏">
</form>

!tail

