!if $subject=5 or $subject=7
    !! JCM applet 
    !set n=$counter
    !set insplot_set=$(image_settings$n)
    $(question$n)
    <br />
    <input id="schaersvoorde_ok_button"  value="TERUG NAAR DE SOM" type="button" onclick="window.close();"/>
    <br />
    $(object$n)
    
 !exit
!endif

!if $subject isin 10,11,12,13
    <a onmouseover="return escape(' LET OP:<br />je moet <span style=\'color:green\'>SUN JAVA</span> gebruiken bij deze Applet<br />Schakel de MICROSOFT eigen JAVA versie uit<ul><li>Ga naar bij Internet Explorer</li><li>Naar het tabblad Extra</li><li>Kies voor Internet Opties</li><li>Daarna het tabblad Geavanceerd </li><li>onderdeel Microsoft VM</li><li><span style=\'color:red\'>Schakel Java JIT compiler uit</span>.</li></ul>')">Je werkt het <span style="color:blue">gemakkelijkst</span> met GeoGebra</a>,<br />
    als je gewoon een willekeurig punt maakt met je muis<br />
    om dan vervolgens via 'rechter muisknop' de co&ouml;rdinaten te veranderen.
    <ol>
	<li>
	    <img src="$module_dir/gifs/a.gif" alt="noalt" />
	<li>
	    <img src="$module_dir/gifs/b.gif" alt="noalt" />
	<li>
	    <img src="$module_dir/gifs/c.gif" alt="noalt" />
    </ol>

    <script type="text/javascript" src="$jsdir/wz_tooltip.js"></script>
!endif 



!if $special_parm=showimage
    !set n=$counter
    !if $image=1
	!if $plot=1
	    !set insplot_set=$(image_settings$n)
	    !insplot $(image$n)
	!else
	    !set insdraw_size=$xsize,$ysize
	    !insdraw $(image$n)
	!endif
    !endif
!endif
