!if $subject=5 or $subject=7
    !! JCM applet 
    !set n=$counter
    !set insplot_set=$(image_settings$n)
    
    $(question$n)
    <br />
    <input id="schaersvoorde_ok_button"  value="BACK TO THE EXERCISE" type="button" onclick="window.close();"/>
    <br />
    $(object$n)
    
 !exit
!endif

!if $subject isin 10,11,12,13
    <a onmouseover="return escape(' ATTENTION :<br />YOU MUST HAVE <span style=\'color:green\'>SUN JAVA</span><br /><br />Disable or delete MICROSOFT \'s own incompatible JAVA version <br />');">
    It's easiest to work with GeoGebra,</a> if you just produce a point, and change afterwards the coordinates.<br />
    (very hard placing a point with mathematical precision with a trembling mouse...)<br />
    Use the right mousebutton over the point:<br />
    <ol>
	<li>
	    <img src="$module_dir/gifs/a.gif" alt="noalt" />
	<li>
	    <img src="$module_dir/gifs/b.gif" alt="noalt" />
	<li>
	    <img src="$module_dir/gifs/c.gif" alt="noalt" />
    </ol>

    <script type="text/javascript" src="$jsdir/wz_tooltip.js"></script>
!endif 



!if $special_parm=showimage
    !set n=$counter
    !if $image=1
	!if $plot=1
	    !set insplot_set=$(image_settings$n)
	    !insplot $(image$n)
	!else
	    !set insdraw_size=$XSIZE,$YSIZE
	    !insdraw $(image$n)
	!endif
    !endif
!endif
