#include "lang_title_fr.inc"

#if defined TARGET_mean1 || defined TARGET_choixindic1 || defined TARGET_diagboite1 || defined TARGET_mediane1 || defined TARGET_ecartvar1 || defined TARGET_transfo1 || defined TARGET_struct1 || defined TARGET_repgraph1 || defined TARGET_quantile1 || defined TARGET_mobile1 || defined TARGET_histogr1
# define NUM 1
#endif
#if defined TARGET_mean2 || defined TARGET_choixindic2 || defined TARGET_diagboite2 || defined TARGET_mediane2 || defined TARGET_ecartvar2 || defined TARGET_transfo2 || defined TARGET_struct2 || defined TARGET_repgraph2 || defined TARGET_quantile2 || defined TARGET_mobile2 || defined TARGET_histogr2
# define NUM 2
#endif
#if defined TARGET_mean3  || defined TARGET_choixindic3 || defined TARGET_diagboite3 || defined TARGET_mediane3 || defined TARGET_ecartvar3 || defined TARGET_transfo3 || defined TARGET_struct3 || defined TARGET_repgraph3 || defined TARGET_quantile3 || defined TARGET_mobile3 || defined TARGET_histogr3
# define NUM 3
#endif
#if defined TARGET_mean4  || defined TARGET_choixindic4 || defined TARGET_diagboite4 || defined TARGET_mediane4 || defined TARGET_ecartvar4 || defined TARGET_transfo4 || defined TARGET_struct4 || defined TARGET_repgraph4 || defined TARGET_quantile4 || defined TARGET_mobile4 || defined TARGET_histogr4
# define NUM 4
#endif
#if defined TARGET_mean5  || defined TARGET_choixindic5 || defined TARGET_diagboite5 || defined TARGET_mediane5 || defined TARGET_ecartvar5 || defined TARGET_transfo5 || defined TARGET_struct5 || defined TARGET_repgraph5 || defined TARGET_quantile5 || defined TARGET_mobile5 || defined TARGET_histogr5
# define NUM 5
#endif
#if defined TARGET_mediane6
# define NUM 6
#endif

\title{TITLE NUM}
