!read language lang/names
!header

<p>$name_intro</p>

!set exolist=1,2,3,4,5
!form new
<fieldset class="property_fields">
!default mode=1
!default niv=1
!default selplan=1
<legend>$wims_name_setup</legend>
<ul><li class="field">
$(name_intro_choice[1]):
!set wims_formselect_switch=multiple
!formselect mode list $exolist prompt $exotitles
!set wims_formselect_switch=
</li><li class="field">
$(name_intro_choice[2]):
!formradio niv list 1,2,3 prompt $name_level
</li><li class="field">
<label for="ceplan">$(name_intro_choice[3]) =</label>
!formradio selplan list 1,2 prompt $name_alea
<input size="6" id="ceplan" name="ceplan" value="J,F,Q">
</li></ul>
</fieldset>
<input type="hidden" name="module" value="$module">
<div class="wimscenter"><input type="submit" value="$wims_name_work"></div>

!formend

!tail
