 blocks.cpp
#if defined TARGET_tie || defined TARGET_IXI
#define TITLE 领结
#endif
#if defined TARGET_twosqr
#define TITLE 两个方块
#endif
#if defined TARGET_threesqr
#define TITLE 三个方块
#endif
#if defined TARGET_foursqr
#define TITLE 四个方块
#endif
#if defined TARGET_cube
#define TITLE 立方体
#endif
#if defined TARGET_house
#define TITLE 房屋
#endif
#if defined TARGET_diag
#define TITLE 方块 + 对角线diagonals
#endif
#if defined TARGET_pizza3 || defined TARGET_pizza4
#define TITLE 圆盘
#endif

pyramid.cpp
#if defined TARGET_pyramid1 || defined TARGET_pyramid1b || defined TARGET_pyramid1c || defined TARGET_pyramid1d || defined TARGET_pyramid2 || defined TARGET_pyramid2b || defined TARGET_pyramid3
#define TITLE 锥形
#endif

pentagram.cpp
#if defined TARGET_pentagram
#define TITLE  五边形
#endif

sides.cpp
#if defined TARGET_triangle
#define TITLE 三角形
#endif
#if defined TARGET_bigsquare
#define TITLE 方块
#endif
#if defined TARGET_cross
#define TITLE 十字
#endif
#if defined TARGET_V
??
#define TITLE V字
#endif
#if defined TARGET_stool
#define TITLE 凳子
#endif
#if defined TARGET_H
#define TITLE H
#endif
#if defined TARGET_M
#define TITLE M
#endif
#if defined TARGET_W
#define TITLE W
#endif
#if defined TARGET_asterisk
#define TITLE 星形
#endif
#if defined TARGET_grill
#define TITLE 篱笆
#endif
#if defined TARGET_pentagon
#define TITLE 五边形
#endif
