!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les  
thèmes suivants pour accompagner un cours d'introduction aux probabilités :
<ol>
 <li>Analyse combinatoire (permutations, arrangements, combinaisons, 
 formule du binôme) ;</li>
 <li>Probabilité sur un ensemble fini (calcul de la probabilité d'un événement) ;
 </li>
 <li>Probabilités conditionnelles. </li>
</ol>
Ce module ne contient pas d'exercices sur les lois de probabilité. 
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=yes
!read oef/$module_language/intromenu.phtml
!tail
