!if $subject=10
    <img src="$module_dir/gifs/exo$subject.jpg" alt="noalt" />
!endif
!if $subject>15 and $subject <22
!! html5 canvas
<img src="$module_dir/gifs/sgraph1.jpg" alt="" />
<hr />
<img src="$module_dir/gifs/sgraph2.jpg" alt="" />

!endif

!if $subject>21
!! geogebra
<ul><span style="color:red">TIP</span><li><span style="color:red">Zet eerst de lijnen ongeveer goed neer.</span></li><li><span style="color:red">Gebruik dan via je rechtermuisknop de optie 'herdefinieer'.</span></li><li><span style="color:red">Verander nu de co&ouml;rdinaten van je punten.</span></li></ul>
!endif
