!default confparm2=2
!default confparm1=1
!default confparm3=1

<tr><th>Mode de résolution<br>
(pour les exercices avec un #)
</th><td>
!formselect confparm2 list 1,2 prompt guidé,brut
</td></tr>
<tr><th>Degré maximum des monômes
</th><td>
!formselect confparm1 list 1,2,3,4,5,6
</td></tr>
<tr><th>Nature des nombres<br>
<small>pour les exercices REMPLACER et REDUIRE</small></th>
<td>
!formselect confparm3 list 1,2,3,4,5,6 prompt Entier positif,Décimal positif 1,Décimal positif 2,Entier relatif, Décimal relatif 1,Décimal relatif 2
</td></tr>
