!header
!read Exindex
<p>Ce module regroupe pour l'instant $exototal activités sur les probabilités.
  Le but de l'ensemble des exercices est de permettre aux élèves d'appréhender l'algorithme
  relatif à une distribution d'échantillonnage.
  Seuls les exercices intitulés "échantillonnage" traitent de cette notion.
  Un script python réalise les simulations d'échantillons et de leur représentation
  graphique. Le niveau visé est une classe de seconde.
  Le but est de travailler de concert dans des cadres algébriques, graphiques et
  algorithmiques afin de maîtriser la notion d'échantillonnage.
</p><p>
  Trois des exercices sont extraits de la compilation d'exercices fournie par la direction 
  générale de l'enseignement scolaire écrite en juin 2009 pour illustrer 
  le programme de BAC PRO.
</p>
<p>
Deux exercices abordent le jeu du franc-carreau avec 2 niveaux possibles:
<ul><li>Niveau 3 ème sans Python</li>
<li>Niveau seconde avec Python</li>
</ul>
</p>
<p>
Trois exercices abordent la méthode de Monte-Carlo avec 3 niveaux possibles:
<ul><li>Méthode de Monte-Carlo 1 : Calcul de pi + intervalle de confiance</li>
<li>Méthode de Monte-Carlo 2 : Calcul d'une intégrale simple + intervalle de confiance</li>
<li>Méthode de Monte-Carlo 3 : Calcul d'une intégrale complexe + intervalle de confiance</li>
</ul>
</p>
   
!read oef/intromenu.phtml
!tail
