!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set promptlist= borne inférieure et supérieure arrondies classiques,borne inférieure arrondie par défaut et borne supérieure par excès
!default confparm1=1
!default confparm2=ambiance
!set wims_html_mode=li 
<tr><td>
<strong>Sélectionner un thème pour l'éditeur Python</strong></td>
<td>
<ul class="wims_nopuce">
!formradio confparm2 list ambiance,neat,zenburn prompt thème sombre,thème clair aéré,thème sombre aéré
</ul></td></tr>
<tr><td><strong>Échantillonnage / Monte-Carlo</strong></td>
<td>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm1 list 1,2 prompt $promptlist
</ul>
</td>
</tr>
