!header
!read Exindex
<div style="
background:#5A52AB;
margin:10px 10px 5px 10px;
padding:5px 5px 5px 5px;
border-radius: 10px;
border: 2px solid #5A52AB;
color: white;
">
Ce module regroupe pour l'instant $exototal exercices sur l'intervalle de
fluctuation en classe de seconde ou en classe de première et intervalles de confiance.

<p>><b>Les exercices indiqués par "#" existent en version "première"</b> (c'est à dire
lorsque l'intervalle de fluctuation est calculé par la loi binomiale) <b>et en
version "seconde"</b> (c'est à dire quand l'intervalle de fluctuation a une amplitude de <math>
<mrow>
  <mfrac>
    <mrow>
      <mn>2</mn>
    </mrow>
    <mrow>
      <msqrt>
        <mi>n</mi>
      </msqrt>
    </mrow>
  </mfrac>
</mrow>
</math> ).
Les autres n'existent qu'en version "seconde".
</p>
Le réglage souhaité se fait en bas du cadre ("Niveau (pour les exercices indiqués par un #)")
</div>
!read oef/intromenu.phtml
!tail
