!header
!read Exindex

On peut le considérer comme un exercice ou un jeu, mais 
c'est un important outil pour l'entrainement sur les opérations
arithmétiques. En cherchant à placer les nombres dans le tableau, vous êtes
obligé de calculer mentalement et rapidement leurs sommes, produits, etc.
<p>
Et selon la configuration, l'exercice peut convenir aux élèves du primaire
(nombres positifs ou relatifs, décimaux) au lycée ou davantage (racines,
nombres complexes, nombres modulaires). Et les tableaux de grande dimension 
(3x5 ou 4x4) peuvent
être de véritables défis.
</p><p>
N'oubliez pas non plus le cas de produits, qui aide à comprendre la
factorisation.
</p><p>
Bon courage !
</p>

!read oef/intromenu.phtml
!tail
