!set datalang=fr
!set n=!recordcnt src/data_$datalang
!reset objlist
!for i=1 to $n
  !set l=!record $i of src/data_$datalang
  !set l=!line 1 of $l
  !set objlist=!append item $l to $objlist
!next i

<tr><th>
Type d'objets :
</th><td>
!formselect confparm1 from 1 to $n prompt $objlist
</td></tr>
<tr><th>
Type d'opérations :
!set oplist=Sommes partout, Sommes et produits, Produits et sommes, Produits partout
</th><td>
!formselect confparm2 from 1 to 4 prompt $oplist
</td></tr>
