!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur l'utilisation d'un photocopieur 
dont les caractéristiques sont les suivantes :
<ul><li>Formats de papier disponibles : A4 (21*29.7 cm) et A3 (29.7*42 cm)</li>
<li>Dimensions utiles de la vitre : A3</li>
<li>Coefficients disponibles pour les agrandissements et réductions : de 25% à 400% en nombre entier</li></ul>
Les exercices sont classés environ par ordre de difficulté croissante.

!read oef/intromenu.phtml
!tail
