#if defined TARGET_basic
# define TITRE Résistance
#endif
#if defined TARGET_parallel
# define TITRE Parallèle
#endif
#if defined TARGET_serial
# define TITRE Série
#endif
#if defined TARGET_par3
# define TITRE Parallèle
#endif
#if defined TARGET_ser3
# define TITRE Série
#endif
#if defined TARGET_h
# define TITRE Type h
#endif
#if defined TARGET_li
# define TITRE Type il
#endif
#if defined TARGET_parser
# define TITRE Parallèle + série
#endif
#if defined TARGET_bridge
# define TITRE Type H
#endif
