!header
!read Exindex
Ce module regroupe pour l'instant $exototal
exercices sur l'initiation à l'utilisation d'un tableur au collège.
<p>
Certains exercices sont extrêmement simples (I) (notion de cellule,
de sélection de plusieurs cellules, utilisation de valeurs numériques),
 d'autres portent sur le référencement relatif (II) ou absolu (III)
 (manipulation du symbole "&#36;" dans les formules).
</p>

!read oef/$module_language/intromenu.phtml
!tail
