!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

<div class="emptyline"></div>

!if $module_score=10
Heel goed !
<center>
!insdraw  \
$dessin\
$dessinsol
</center>
!else
Je antwoord is getekend in rood, het correcte antwoord is getekend in groen.
<div class="emptyline"></div>
<ul>
!if $miss =1
<li>&eacute;&eacute;n van je punten ligt niet op de rechte lijn.</li>
!endif
!if $miss=2
<li>
    beiden punten liggen niet op de lijn. </li>
!endif
!if abs($pente- ($a))<0.15 and abs($ord-($b))>0.1
<li>
jouw lijn loopt parallel aan de correcte lijn.(de richtingsco&euml;fficient is correct )</li>
!endif
!if abs($pente-($a))>0.2 and abs($ord-($b))<0.1
<li>
de constante van je lijn is wel goed, de richtingsco&euml;fficient is fout.</li>
!endif

!if $type=2 and abs($ord)>0.1
<li>
    De grafiek van de lijn gaat altijd door de oorsprong (O).
</li>
!endif
</ul>
<div class="emptyline"></div>
<center>
!insdraw  \
$dessin\
$dessin2\
$dessinsol
</center>
!endif

Je score is $module_score (uit 10).
