!! On pose les questions dans ce fichier. D'habitude, c'est par
!! des forms. Voici un exemple de conception de la forme de réponse.

!if $status=waiting

!if $click_cnt=0
Klik op een punt van de lijn: 
!else
Klik op een tweede punt van de lijn:
!endif

<p>
!form reply
!distribute item alt="Cliquer",1,form click  into ins_attr,ins_border,ins_tag

<center>
!insdraw\
$dessin\
$dessin1
</center>
</form>
!endif

