
!header

<b>$module_title </b> <br>
is een oefening over grafieken bij lineaire formules 
<p> <p><hr> <p>
!read names.phtml
Je wordt gevraagd punten in de grafiek bij een lineaire formule aan te geven.

!set type=1
!form new
<p align="center">
<table summary="">
<th>
<p align="left">
!formradio type list 2 prompt lineair door de oorsprong, lineair
</th>
<tr>
<th>
<table summary="">
<th>
<p align="left">
!formradio type list 1 prompt lineair gegeven door:
</th>
<th>
<p align="left">
!set liste= rep,direct,indirect, applindir,applinante
!set mode=$liste
!!!set wims_formselect_switch=multiple
  !formselect mode list $liste prompt \
$name1,$name2,$name3,$name4,$name5,$name6,$name7
  !set wims_formselect_switch=
</th>
</table>
</th>
<tr>
<th>
<p align="left">
!default coeff=1
De co&euml;fficienten zijn: 
!formselect coeff list  1,2,3 prompt  gehele getallen, breuken, decimale getallen
</th>
<tr>
<th>
<input type=hidden name=module value="$module">
<center><input type=submit value="Aan het Werk">
</th>
</table>
</form>

.

!tail


