!header

!! La présentation de l'exercice.
!read present.phtml

<div class="emptyline"></div>

!if $status=waiting
 !if $error!=$empty
  !read msg.phtml
  <div class="emptyline"></div>
 !endif
 !! La forme de réponse
 !read form.phtml
 <p>
 !href exo_Renew
.
!else
 !if $error!=$empty
  !read msg.phtml
  <div class="emptyline"></div>
 !endif
 !! L'analyse de réponse
 !read answer.phtml
<div class="emptyline"></div>
!set wims_ref_class=wims_button
 !href exo_Again
&nbsp;
 !if $worksheet=$empty
!set wims_ref_class=wims_button
  !href exo_Intro
&nbsp;
 !endif
!endif

:end
!tail
