!! Ce fichier présente la question à résoudre.


!set eqlin_tex=!texmath $equationlin
!set eq_tex=!texmath $equation
<b>Exercice.</b>

!set aff=!item $type of lineaire ,lineair door de oorsprong

!if $mode issametext rep
Geef twee punten van de grafiek van de lineaire formule 
!insmath  f: x \mapsto  $eq_tex   

!endif

!if $mode issametext direct 
Geef twee punten van de grafiek van de lineaire formule <b>f</b> met
hellingsgetal<b><i> rc = $a</i></b> en zo dat het beeld van $A gelijk is aan $B. 
!endif

!if $mode issametext indirect 
Geef twee punten van de grafiek van de lineaire formule <b>f</b> met
hellingsgetal<b><i> rc = $a</i></b> 
en zo dat $B het beeld is van $A. 
!endif

!if $mode issametext applindir 
Geef twee punten van de grafiek van de lineaire formule 
!insmath f: x \mapsto  $eqlin_tex + b 
 voor een nog onbekende b zodat het beeld van $A gelijk is aan $B. 
!endif

!if $mode issametext applinante
Geef twee punten van de grafiek van de lineaire formule
!insmath f: x \mapsto  $eqlin_tex + b
 voor een nog onbekende b
zo dat $B het beeld is van $A. 

!endif
<p>
Klik nu op twee punten van de lijn.<br>
Zorg dat deze punten ruim uit elkaar liggen.
</p> 
