#if defined TARGET_tabvaleur1 || defined TARGET_tabvaleur2 || defined TARGET_tabvaleur3
\text{name_enonce=Par lecture graphique, compléter le tableau des coordonnées
  des points&nbsp;}
\text{name_answer=Abscisse de,Ordonnée de}
#endif
#if defined TARGET_pourcent1
\text{name_enonce=Calculer les nombres suivants&nbsp;}
\text{name_head=Calculs,Réponses}
\text{name_answer=Réponse}
#endif
#if defined TARGET_pourcent2
\text{name_enonce=Écrire les nombres décimaux suivants sous forme de quotient
  dont le dénominateur est égal à 100&nbsp;}
#endif
#if defined TARGET_pourcent3
\text{name_enonce=Écrire les nombres suivants en écriture décimale&nbsp;}
#endif
