\email{fwguerima@free.fr}
Fork WIMSEDU
#if defined TARGET_equationA1 || defined TARGET_equationA2 || defined TARGET_equationA3 || defined TARGET_equationA4 || defined TARGET_equationA5 || defined TARGET_equationB1 || defined TARGET_equationB2 || defined TARGET_equationB3 || defined TARGET_equationB4 || defined TARGET_equationB5 || defined TARGET_equationC1 || defined TARGET_equationC2 || defined TARGET_equationC3 || defined TARGET_equationC4 || defined TARGET_equationC5
\author{G., Bayle;Fabrice, Guerimand}
#else
\author{Fabrice, Guerimand}
#endif
