!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! À la fin, confparm1 est nul pour un choix aléatoire,       !!
!! sinon il désigne un enregistrement précis de data/cycles   !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!let confparm2 = !recordcnt data/cycles

!for var_boucle0=1 to $confparm2
  !let confparm3 = !record $var_boucle0 of data/cycles
  !let confparm4 = !positionof line /title/ in $confparm3
  !let confparm4 = !eval $confparm4 + 1
  !let ligne$var_boucle0 = !line $confparm4 of $confparm3
!next var_boucle0

<tr><td align="center">Choix de l'exercice</td>
    <td>
      <select name="confparm1">
      <option value=0>aléatoire</option>
!for var_boucle1=1 to $confparm2
      <option value=$var_boucle1>
       $(ligne$var_boucle1)
      </option>
!next var_boucle1
      </select>
    </td></tr>
