!!! allowing [ -5 : 6 ] [ 1,4] [1 ;5 ]


!!<input type="text" value="" id="myinput0" size="10" />

<script type="text/javascript">
//<![CDATA[
<!-- no validator  -->
 "use_strict";
 rem1="Ik verwacht hier de intervalnotatie...<br />iets als <b>[</b> 1.234 <b>,</b> 2.345 <b>]</b> <br />dus met vierkante haken en een komma, puntkomma of dubbelepunt als scheidingsteken...";
 function sendanswer(){
  var reply = document.getElementById('myinput0').value;
  if( reply.length == 0){setAlarm(r1+" $counter ");return; };
  if ( reply.indexOf('?') != -1 ){ dontknow();     return; };
  if ( reply.indexOf('(') != -1 ){ setAlarm(rem1); return; };
  if ( reply.indexOf('{') != -1 ){ setAlarm(rem1); return; };
  if ( reply.indexOf('<') != -1 ){ setAlarm(rem1); return; };
  if ( reply.indexOf('[') < 0   ){ setAlarm(rem1); return; };
  rep = reply.toLowerCase();
  rep = rep.replace(/[a-z\[\]\%\~\@\$$\=\+]/g,'');
  var ans = rep.split(':');
  if( ans.length != 2 ){
   ans = rep.split(';');
   if(ans.length != 2 ){
    ans = rep.split(',');
    if(ans.length != 2 ){ 
     setAlarm(rem1);return;
    };
   };
  };
  myConfirm(r0+'<br />'+reply,ans,'$wims_ref_name','$session','$module','$counter','$ok_send_color');
 }
//]]>
</script>

