
!if $abandon!=yes
  $name_answer
  !if $laps>$allow
    $name_answerchrono
  !endif
  <table class="wimscenter wimsborder">
  !for i=1 to $rows
    <tr>
    !for j=1 to $cols
     <td>$(x$[$j+$cols*($i-1)])</td>
    !next j
    <th scope="row"><span style="color:blue">$(rowsum$i)</span></th>
  !next i
  <tr>
  !for j=1 to $cols
    <td><span style="color:blue">$(colsum$j)</span></td>
  !next j
  <th scope="col"><span style="color:blue" class="smaller">
    $(n_$kind)
  </span></th>
  </tr></table>
!else
  $name_answergiveup
  <table class="wimscenter wimsborder">
  !for i=1 to $rows
    <tr>
    !for j=1 to $cols
      !set t_=!item $j+$cols*($i-1) of $list
      <td>$t_</td>
    !next j
    <th scope="row"><span style="color:blue">$(rowsum$i)</span></th>
  !next i
  <tr>
  !for j=1 to $cols
    <td><span style="color:blue">$(colsum$j)</span></td>
  !next j
  <th scope="col"><span style="color:blue" class="smaller">
     $(n_$kind)
  </span></th>
  </tr></table>
!endif

$name_Score: $module_score/10.

