!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices <b>non aléatoires</b> qui constituent un CCF "Contrôle en Cours de Formation" de terminale BAC PRO.
 En effet les modalités d'évaluation au BAC PRO sont modifiées depuis la session 2012. L'épreuve ponctuelle
 qui avait lieu précédemment, est remplacée par 2 CCF de 45 minutes, notés sur 10 points, à effectuer durant l'année scolaire.
 Elle aborde les modules de formation sur les séries statistiques à 2 variables et les fonctions (dérivation extremum).
<div></div>
<br/>
L'ensemble des questions aborde la mise en place d'une modélisation à travers une problématique concrète.
L'usage des TIC est nécessaire pour résoudre les activités. Le logiciel nécessaire est LibreOffice mais
 les élèves peuvent aussi utiliser une calculatrice ou un logiciel comme Géogébra pour retrouver l'équation de la droite de tendance.
  Une évaluation par compétence est à réaliser conformément au référentiel :
 
<ul><li style="font-weight:bold">Aptitudes à mobiliser des connaissances et des compétences pour résoudre des problèmes ( /7 points)</li>
<ul><li><span style="font-weight:bold">C1 : </span>Rechercher,extraire et organiser l'information.</li>
<li><span style="font-weight:bold">C2 : </span>Choisir et exécuter une méthode de résolution.</li>
<li><span style="font-weight:bold">C3 : </span>Raisonner, argumenter, critiquer et valider un résultat.</li>
<li><span style="font-weight:bold">C4 : </span>Présenter, communiquer un résultat.</li></ul>
<li style="font-weight:bold">Capacités liées à l'utilisation des TIC ( /3 points)</li>
<ul><li><span style="font-weight:bold">TIC : </span>Expérimenter ou Simuler ou Émettre des conjectures
 ou contrôler la vraisemblance de conjectures.</li></ul></ul>

Une approche pragmatique est réalisée et les thèmes suivants sont abordés :
<ul>
<li><span style="font-weight:bold">Vie sociale et loisirs :</span> Quel prix de vente moyen au m² peut-on prévoir en 2020 sur Paris ?</li>
</ul>

Il a été réalisé pour un niveau de Terminale BAC PRO section tertiaire en vue de préparer les élèves au CCF.

!read oef/intromenu.phtml
!tail
