#if defined TARGET_angle1 || defined TARGET_angle2 || defined TARGET_angle3
# define TITRE Calcul d'angle
#endif
#if defined TARGET_oeftrouvangltriang1 || defined TARGET_oeftrouvangltriang2
# define TITRE Trouver les angles d'un triangle
#endif
#if defined TARGET_oefmesangltriang
#define TITRE Mesurer les angles d'un triangle
#endif
#if defined TARGET_vocangle1
#define TITRE Vocabulaire des angles
#endif
