#if defined TARGET_angle1 || defined TARGET_angle2 || defined TARGET_angle3
# define TITRE_nl Bereken de hoeken
#endif
#if defined TARGET_oeftrouvangltriang1 || defined TARGET_oeftrouvangltriang2
# define TITRE_nl Trouver les angles d'un triangle
#endif
#if defined TARGET_oefmesangltriang
#define TITRE_nl Mesurer les angles d'un triangle
#endif
#if defined TARGET_vocangle1
#define TITRE_nl Naamgeving van hoeken
#endif
