!if $subject < 11
    <table>
	<tr>
	<td>
	    Algemene hint: 
	    Voor co&ouml;rdinaten van de snijpunten met de <em>x-as</em>
	    ,stel je de <em>y-waarde</em> van de functie op nul.
    	    <br /> 
	    Dus stel we hebben de vergelijking <em>f(x)=x</em><sup><small>2</small></sup> - 4<em>x</em>
	    <br /> 
	    Om de nulpunten te vinden, stellen we dus <em>f(x)=0</em> ofwel <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0
	    <br /> 
	    Dus: <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0 --> <em>x</em>(<em>x</em>-4)=0 --> <em>x</em>=0 en <em>x</em>=4</em>
	    <br /> 	
	    De <em>nulpunten</em> zijn dus <em>x</em>=0 en <em>x</em>=4
	    <br /> 
	    De co&ouml;rdinaten van de snijpunten met de <em>x-as</em> zijn dus (0:0) en (4:0)
	</td>
	</tr>
    </table>
!else
    !if $subject > 15
    !else
	<table>
	<tr>
	<td>
	Als er gevraagd wordt naar een zinvolle tussenstap, mag je iets opschrijven als:<br />
	<textarea style='font-size:18px;background-color:#e8ffff;border:1px solid #ff0000' readonly="readonly" cols=50 rows=14>
	x^2 - x = 20 ->

	x^2 - x - 20 = 0 ->

	(x - 5)(x + 4) = 0 ->

	x = 5 en  x = -4

	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	De pijlen zijn verplicht !!!!
	de toegestane pijlen zijn:
	-> <-> => <=>
	</textarea>
	<br />
	Let op: ik kijk ook naar de <em>tussenstappen</em> na die omgewerkt zijn tot een "nul" vergelijking...<br />
	dus iets als <em>(x-5)*(x+4)=0</em> of <em>x^2-x-20 = 0</em>
	<br />
	En natuurlijk moet <b>de laatste "stap"</b> gewoon het eindantwoord zijn, dus iets als:<br />
	$m_rightarrow <em>x</em> = 5 and <em>x</em> = -4<br />
	Vergeet niet de pijlen als logische scheidingstekens in de uitdrukkingen !!
	</td>
	</tr>
	</table>
    !endif
!endif
