!if $subject<11
    <table>
	<tr>
	<td>
	    General hint: 
	    In order to find the coordinates of the intersection points with the <em>x-axis</em> 
	    , we have to set the <em>y-value</em> of the function to zero.
    	    <br /> 
	    Let's take the function <em>f(x)=x</em><sup><small>2</small></sup> - 4<em>x</em>
	    <br /> 
	    To find its roots -and thus the intersection points-  we set <em>f(x)=0</em> or <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0</em>
	    <br /> 
	    So: <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0 --> <em>x</em>(<em>x</em>-4)=0 --> <em>x</em>=0 and <em>x</em>=4</em>
	    <br /> 	
	    The <em>roots</em> are <em>x</em>=0 and <em>x</em>=4
	    <br /> 
	    The coordinates of the intersection points with the <em>x-axis</em> are (0:0) and (4:0)
	    <br /> 
	    ok ?
	</td>
	</tr>
    </table>
!else
    !if $subject>15
    !else
	<table>
	<tr>
	<td>
	    If asked for a meaningfull intermediate step, you may fill in something like:<br />
	    <textarea style='font-size:18px;background-color:#e8ffff;border:1px solid #ff0000' readonly="readonly" cols=40 rows=14>
	x^2 - x = 20 <->

	x^2 - x - 20 = 0 <->

	(x - 5)(x + 4) = 0 <->

	x = 5 and  x = -4


	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	Attention: the arrows are mandatory !!!
	allowed arrows are:
	-> <-> => <=>
	</textarea><br />
	    Attention: I will also check intermediate steps that are equations in a "null" form...<br />
	    like <em>x<sup>2</sup> - x - 20 = 0</em><br />
	    And ofcourse the final step, must be the solution:<br />
	    $m_rightarrow <em>x</em> = 5 and <em>x</em> = -4
	    <br />
	    Last important remark: the <b>arrows</b> are necessary as logical separators of your expressions !!
	</td>
	</tr>
	</table>
    !endif
!endif
