!if $subject<11
    <table>
	<tr>
	<td>
	    Aide générale: 
	    Pour trouver les coordonnées des points d'intersection avec l'<em>axe des x</em>,
	    on doit mettre la <em>valeur de y</em> de la fonction à zéro.
    	    <br /> 
	    Prenons la fonction <em>f(x)=x</em><sup><small>2</small></sup> - 4<em>x</em>
	    <br /> 
	    Pour trouver ses racines -et ainsi les points d'intersection-  on pose <em>f(x)=0</em> ou <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0</em>
	    <br /> 
	    Donc: <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0 --> <em>x</em>(<em>x</em>-4)=0 --> <em>x</em>=0 et <em>x</em>=4</em>
	    <br /> 	
	    Les <em>racines</em> sont <em>x</em>=0 et <em>x</em>=4
	    <br /> 
	    Les coordonnées des points d'intersection avec l'<em>axe des x</em> sont (0:0) et (4:0)
	    <br /> 
	    ok ?
	</td>
	</tr>
    </table>
!else
    !if $subject>15
    !else
	<table>
	<tr>
	<td>
	    Si on vous demande une étape intermédiaire significative, vous devez remplir de la manière suivante :<br />
	    <textarea style='font-size:18px;background-color:#e8ffff;border:1px solid #ff0000' readonly="readonly" cols=40 rows=14>
	x^2 - x = 20 <->

	x^2 - x - 20 = 0 <->

	(x - 5)(x + 4) = 0 <->

	x = 5 et  x = -4


	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	Attention: les flèches sont obligatoires !!!
	Les flèches permises sont:
	-> <-> => <=>
	</textarea><br />
	    Attention: Je vérifierai aussi les étapes intermédiaires qui sont des equations sous une forme "nulle"...<br />
	    like <em>x<sup>2</sup> - x - 20 = 0</em><br />
	    Et bien sûr, à l'étape finale, il doit y avoir la solution:<br />
	    $m_rightarrow <em>x</em> = 5 et <em>x</em> = -4
	    <br />
	    Dernière remarque importante: les <b>flèches</b> sont nécessaires comme séparateurs logiques de vos expressions !!
	</td>
	</tr>
	</table>
    !endif
!endif
