!if $subject<11
    <table>
    <tr>
    <td>
        提示: 
        为了求出与 <em>x 轴</em>的交点坐标, 
        应该令函数的 <em>y 值</em>等于 0.
            <br /> 
        例如取函数 <em>f(x)=x</em><sup><small>2</small></sup> - 4<em>x</em>
        <br /> 
        为求出它的根, 也就是交点, 令 <em>f(x)=0</em> 或 <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0</em>
        <br /> 
        于是: <em>x</em><sup><small>2</small></sup> - 4<em>x</em> = 0 --> <em>x</em>(<em>x</em>-4)=0 --> <em>x</em>=0 and <em>x</em>=4</em>
        <br />    
        <em>根</em>是 <em>x</em>=0 以及 <em>x</em>=4
        <br /> 
        因此与 <em>x 轴</em>的交点坐标是 (0:0) 和 (4:0)
        <br /> 
        ok ?
    </td>
    </tr>
    </table>
!else
    !if $subject>15
    !else
	<table>
	<td>
	作为中间步骤, 你可以如下填充:<br />
	<textarea style='font-size:18px;background-color:#e8ffff;border:1px solid #ff0000' readonly="readonly" cols=40 rows=14>
	x^2 - x = 20 <->

	x^2 - x - 20 = 0 <->

	(x - 5)(x + 4) = 0 <->

	x = 5 and  x = -4


	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	注意: 箭头是必须有的 !!!
	允许的箭头有:
	-> <-> => <=>
	</textarea><br />
	注意: 我也要检查中间步骤, 它是右边等于 0 的方程的形式...<br />
	例如 <em>x<sup>2</sup> - x - 20 = 0</em><br />
	当然最后一步应该是解:<br />
	$m_rightarrow <em>x</em> = 5 and <em>x</em> = -4
	<br />
	最后一个重要提示: 作为你的表达式的逻辑分隔符号, <b>箭头</b>也是不可缺少的 !!
	</td>
	</tr>
	</table>
    !endif
!endif
