\observation{Dans cet exercice, l'élève doit remarquer que a ou b est divisible
 par un certain nombre (par exemple 5) qui apparaît dans les instructions python disponibles. 
<br>Ensuite, il doit coder un programme du type "tant que a est positif, on lui retire 5 et on l'ajoute à b".}

\text{pr=additions,somme de \(a=\a\) et \(b=\b\),a+b}

\integer{result=\a+\b}

\text{instruction_code=instruction=[a=\a,b=\b,while a>0:,while b>0:,a=a+\d,a=a-\d,b=b-\d,b=b+\d,print(b),print(a),&#32;&#32;]}
