\observation{Dans cet exercice, l'élève doit coder un programme du type "tant que a est positif,
 on lui retire 1 et on ajoute b à une variable m".}

\text{pr=multiplications,multiplication de \(a=\a\) et \(b=\b\),a \times b}

\integer{result=\a*\b}

\text{instruction_code=instruction=[a=\a,b=\b,m=0,while a>0:,while b>0:,a=a+\d,a=a-\d,b=b-\d,b=b+\d,m=m+\d*a,m=m+\d*b,print(a),print(b),print(m),&#32;&#32;]}
