\title{Permuter deux variables}
\text{prob=Permutation circulaire de deux variables}

\text{nlalgo=\(\begin{array}{|l}
& a  \longleftarrow  b \\ \hline
& b  \longleftarrow  a
\end{array}\)}

\text{instruction=Écrire un script qui permet d'échanger la valeur des variables
 \(a=\a\) et \(b=\b\). En langage naturel, on écrit :
\nlalgo }

\text{result=\b:\a}






































































\text{instruction_code=instruction=[a=\a,b=\b,tmp=0,tmp=a,a=tmp,tmp=b,b=tmp,a=b,b=a]}
