\statement{
<div class="encadre">
<p class="problematique">\prob</p>
<div id="boited">
<img src="\imagedir/python.png" alt="Logo de Python">
</div>
<div class="enonce">
\enonce
<div class="question">
\instruction
</div>
<div class="wims_instruction">\consigne</div>
</div>
<div>
\embed{reply1,[python,[\code]];[id1,canvas init readonly fullscreen theme=[\theme[\nbtheme;]] \instruction_code,Jouer le code !]}
</div>
</div>
}

\answer{}{[print,[\result:]]}{type=runcode}{option=precision=1000 \instruction_code}
