goback=0
errortext=$empty
# edited on : Fri Mar 7 13:31:23 UTC 2008 
# reply$n=1<x<5

n=$counter

!if ? isin $(reply$n)
    # the "I don't know button"
    remark$n=$NOK
    maxscore=0
    goback=0
    !exit
!endif

extra=$empty
var4=$(reply$n)
!readproc exos/ineq.proc
!if $goback=1
    !exit
!endif
maxscore=$[$maxscore*$score2]
remark$n=$var6
modulescore=$[$modulescore + $maxscore]
goback=0
!exit

