#if defined TARGET_denomcom
\text{name_statement=Quel est le plus petit dénominateur commun à,et,
  Le plus petit dénominateur commun aux deux fractions est}
\text{name_answer=Dénominateur commun}
\text{name_youranswer=Votre réponse}
\text{name_hint=Écrire la liste des multiples de, et}
#else
\text{name_statement=Calculer l'expression suivante&nbsp;,
Calculer les expressions suivantes&nbsp;}
\text{name_inst=Vous donnerez le résultat sous forme simplifiée.,
  Vous donnerez les résultats sous forme simplifiée}
#endif
