!set introhook_exists=yes

!if $lang=en
  !set name_menu_option=Number of given questions
  !goto menu
!endif

!if $lang=it
  !set name_menu_option=Numero di domande poste
  !goto menu
!endif

!if $lang=es
  !set name_menu_option=Número de preguntas propuestas
  !goto menu
!endif

!set name_menu_option=Nombre de questions proposés

:menu
<tr><th>$name_menu_option</th><td>
!formselect confparm1 list 1,2,3,4,5
</td></tr>
