!default confparm2=2
<tr><th>Mode de résolution<br>
(seulement pour les exercices avec un #)
</th><td>
!formselect confparm2 list 1,2 prompt guidé,brut
!default confparm1=1
</td></tr>
<tr><th>Nature des coefficients</th>
<td>
!formselect confparm1 list 1,2,3,4,5,6,7,8 prompt Entier positif,Entier relatif,Fraction positive,Fraction relative,Décimal positif 1, Décimal relatif 1,Décimal positif 2,Décimal relatif 2
</td></tr>
