!read language lang/names
!header

<span class="wims_emph">$module_title</span> $name_intro1
<p>
  $(name_intro2[1])
  <span class="wims_emph">$module_title</span>
  $(name_intro2[2]).
  $(name_intro3[1;])
  !href module=U2/algebra/qpuzzle Q-Puzzle
  $(name_intro3[2;])
</p>
!form new
<input type="hidden" name="module" value="$module" />
 $name_prompt:
!read data/spuzzle/photindex
!default level=2x3
!formselect level list $levels
&nbsp;<input type="submit" value="$name_goto" />

!formend

!tail
