!read language lang/names
!header
!read present.phtml

!if $status=waiting
  !if $error!=$empty
    <div class="wims_msg warning">
    !read msg.phtml
    </div>
  !endif
  !read form.phtml
  <p>
  !set wims_ref_class=wims_button wims_secondary_button
  !href cmd=renew&worksheet=$worksheet&$module_init_parm $(name_change[1])
  $
  </p>
!else
  !read answer.phtml
  <p>
  !set wims_ref_class=wims_button
  !href cmd=renew&worksheet=$worksheet&$module_init_parm $(name_change[2])
  $
  !if $worksheet=$empty
    !set wims_ref_class=wims_button
    !href module=$module $(name_change[3])
    $
  !endif
  </p>
!endif

:end
!tail

