!if $status=waiting

  $(name_present1[1]) $level $(name_present1[2])?

  <table class="wimscenter">
  <tr><td></td>
  !for x=0 to $nx-1
    <th>
    !href cmd=reply&job=up&k=$x <img src="gifs/arrows/up1.32.gif" alt="$(name_alt[1])" />
    </th>
  !next x
  </tr>
  !for y=0 to $ny-1
    <tr><td>
    !href cmd=reply&job=left&k=$y <img src="gifs/arrows/left1.32.gif" alt="$(name_alt[2])" />
    </td>
    !for x=0 to $nx-1
    !set t_=!item $x+$y*$nx+1 of $scramble
    !set x_=$[($t_-1)%$nx]
    !set y_=$[floor(($t_-1)/$nx)]
     <td><img src="scripts/data/spuzzle/pieces/$phname/$level/p.$x_.$y_.gif" alt=""/></td>
    !next x
    <td>
    !href cmd=reply&job=right&k=$y <img src="gifs/arrows/right1.32.gif" alt="$(name_alt[3])" />
    </td>
    </tr>
  !next y
  <tr><td></td>
  !for x=0 to $nx-1
    <th>
    !href cmd=reply&job=down&k=$x <img src="gifs/arrows/down1.32.gif" alt="$(name_alt[4])" />
    </th>
  !next x
  </tr></table><p>
  $name_inst1
  </p>

  !if $showorigin>0
    $name_inst2
    <div class="wimscenter">
    !href cmd=reply&job=hide <img src="scripts/data/photos/$phname.gif" alt="$(name_alt[5])" />
    </div>
  !endif

!else # status!=waiting
  <table class="wimscenter">
  !for y=0 to $ny-1
    <tr>
    !for x=0 to $nx-1
      !set t_=!item $x+$y*$nx+1 of $scramble
      !set x_=$[($t_-1)%$nx]
      !set y_=$[floor(($t_-1)/$nx)]
      <td><img src="scripts/data/spuzzle/pieces/$phname/$level/p.$x_.$y_.gif" alt=""/></td>
    !next x
  </tr>
  !next y
  </table>

!endif # status=waiting?
