!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les séries statistiques à deux variables. 

L'ensemble de ses exercices aborde la méthode pour obtenir des droites d'ajustement affine
 à l'aide  des TIC. Les logiciels utilisés sont LibreOffice et Géogébra (A venir).
 Il développpe les notions sur les équations du 1<sup>er</sup> degré, les tableaux à double
 entrée ainsi que les calculs des coordonnées du point moyen. Les exercices n°1.i et 4.i permettent une
 évaluation par compétence.
<ul><li>Quelle serait l’étendue minimale de la glace de mer en Arctique durant l’été 2050 ?</li>
<li>Quelle est l'évolution de la température globale à la surface de la terre ?</li>
<li>Quelle est l'évolution des dépenses dans les loisirs ?</li>
<li>Quelle est l'évolution des connexions sur le serveur ?</li>
</ul>

Une approche pragmatique est réalisée et les thèmes suivants sont abordés :
<ul>
<li>Développement durable</li>
<li>Vie sociale et loisirs</li>
<li>Évolution des sciences et techniques</li>
</ul>

Ils ont été réalisés pour un niveau de Terminal BAC PRO section tertiaire.

!read oef/intromenu.phtml
!tail
