#if defined TARGET_solide1
# define TITRE Solides 1
#endif
#if defined TARGET_solide10
# define TITRE Faces dans l'espace
#endif
#if defined TARGET_solide11
# define TITRE Faces parallèles dans l'espace
#endif
#if defined TARGET_solide12
# define TITRE Faces perpendiculaires dans l'espace
#endif
#if defined TARGET_solide2
# define TITRE Reconnaitre des solides 2
#endif
#if defined TARGET_solide3
# define TITRE Reconnaitre des solides 1
#endif
#if defined TARGET_solide4
# define TITRE Faces; arêtes et sommets
#endif
#if defined TARGET_solide5
# define TITRE Bases d'un solide 1
#endif
#if defined TARGET_solide6
# define TITRE Bases d'un solide 2
#endif
#if defined TARGET_solide7
# define TITRE Côtés dans l'espace
#endif
#if defined TARGET_solide8
# define TITRE Côtés parallèles dans l'espace
#endif
#if defined TARGET_solide9
# define TITRE Côtés perpendiculaires dans l'espace
#endif
