#if defined TARGET_solide1
# define TITRE_nl Objecten deel I
#endif
#if defined TARGET_solide10
# define TITRE_nl Vlakken deel I
#endif
#if defined TARGET_solide11
# define TITRE_nl Vlakken deel II
#endif
#if defined TARGET_solide12
# define TITRE_nl Vlakken deel III
#endif
#if defined TARGET_solide2
# define TITRE_nl Objecten deel II
#endif
#if defined TARGET_solide3
# define TITRE_nl Objecten deel III
#endif
#if defined TARGET_solide4
# define TITRE_nl Vlakken en zijden
#endif
#if defined TARGET_solide5
# define TITRE_nl Grondvlak deel I
#endif
#if defined TARGET_solide6
# define TITRE_nl Grondvlak deel II
#endif
#if defined TARGET_solide7
# define TITRE_nl Zijden deel I
#endif
#if defined TARGET_solide8
# define TITRE_nl Zijden deel II
#endif
#if defined TARGET_solide9
# define TITRE_nl Zijden deel III
#endif
