\title{Question 210 NS Isoler une variable}
\keywords{quizz,literal_calculation,equations}
\observation{Question du sujet zéro sujet-specifique-3_0.pdf publié sur EDUSCOL en juin 2025 }

\text{enonce=Le volume \(V\) d’un cylindre de hauteur \(h\) et de rayon \(r\) est égal à&nbsp;&#63; <div class="wimscenter">\(V=\pi r^2 h\)</div> On cherche à isoler <span class="nowrap">\(h\).</span> On a&nbsp;&#58; }

\text{good=\(h=\frac{V}{\pi r^2}\)}
\text{bad1=\(h=\frac{\pi r^2}{V}\)}
\text{bad2=\(h=\frac{r^2}{\pi V}\)}
\text{bad3=\(h=\sqrt{\frac{V}{\pi r^2}}\)}

%%%
\text{bads=\bad1,\bad2,\bad3}

\text{feed0=On a \(V=\pi r^2 h\)  \({}\Leftrightarrow \frac{V}{\pi}= r^2 h\) \({}\Leftrightarrow \frac{V}{\pi r^2}=  h\) }

\text{feedback=La bonne réponse est \good.  <br>\feed0 }
