\title{Question 202 T Résolution d'équation}
\keywords{quizz,equations,literal_calculation}
\observation{Question du sujet zéro sujet-techno-2_0.pdf publié sur EDUSCOL en juin 2025 }
%%% MB %%%%
\text{k=randint(2..8)}
\text{x=randomitem(x,x,m,n,t,h)}
\text{enonce=La solution de l’équation \(\k\x = 0\) est&nbsp;&#58;}
\text{good=\(\x=0\)}
\text{bads=\(\x=\frac{1}{\k}\),\(\x=-\frac{1}{\k}\),\(\x=-\k\)}
\text{feedback=La bonne réponse est \good.<br> Puisque le produit est nul et que \(\k\) ne l'est pas&#44; c'est \(\x\) qui est nul.}
