\title{Question 203 T Résolution d'équation}
\keywords{quizz,equations,literal_calculation}
\observation{Question du sujet zéro sujet-techno-2_0.pdf publié sur EDUSCOL en juin 2025 }
%%% MB %%%%
\text{q=randint(14..17)}
\text{c=randomitem(9,7,8)}
\integer{k=\q*\c}
\text{x=randomitem(x,x,m,n,t,h)}
\text{enonce=La solution de l’équation \(\frac{\k}{\x} = \c \) est&nbsp;&#58;}
\text{good=\(\x=\frac{\k}{\c} \)}
\text{bads=\(\x=\k \times \c\),\(\x=\frac{\c}{\k} \),\( \x=-\q\)}
\text{temp=Puisque l'équation est équivalente à <span class="nowrap">\(\k=\c \times \x\).</span>,Puisque l'équation est équivalente à <span class="nowrap">\(\frac{\x}{\k} = \frac{1}{\c} \).</span>}
\text{temp=randomitem(\temp)}
\text{feedback=La bonne réponse est \good. <br>\temp}
