\title{Question 702 T Lire un diagramme}
\keywords{quizz,histogram}
\observation{Question du sujet zéro sujet-techno-1_0.pdf publié sur EDUSCOL en juin 2025 }

\text{cas=randomitem(1,2)}
\text{mot1=\cas=1?plus:moins}
\text{mot2=\cas=1?grande:petite}
\text{enonce=Le diagramme en barres ci-dessous donne la production d’électricité&#44; en Twh (térawatt-heure) selon son origine (source&nbsp;&#58; INSEE) <div class="wimscenter"><img src="\imagedir/imgq702.png" alt="Histogramme" ></div>L’année où la production d’électricité d’origine hydraulique était la \mot1 importante est&nbsp;&#58;}

\text{good=\cas=1?2016:2006}
\text{bads=\cas=2?2016:2006}
\text{bads=\bads,2001,2011}
\text{feedback=La bonne réponse était \good. <br>Il faut comparer les hauteurs des rectangles au sommet des barres. On recherche la plus \mot2.}
