!set introhook_exists=yes

!set confparm1=1
!set confparm2=2
!set introhook_tableless=yes
<div>
Les figures peuvent être montrées dans
!formradio confparm1 list 1,2 prompt un dessin statique, Geogebra 3D
.</div>
<div>Si l'option Geogebra 3D est sélectionnée et si cela est pertinent dans
  l'exercice, une seconde option est possible permettant de construire
 le point demandé de manière plus formelle avec les outils intersection droite
 et droite parallèle:
 <br>
!formradio confparm2 list 1,2 prompt <img src="$module_dir/images/Move_ggb.png" alt="Move"><img src="$module_dir/images/Point_ggb.png" alt="Point">,<img src="$module_dir/images/Intersection_ggb.png" alt="Intersection"><img src="$module_dir/images/Droite_ggb.png" alt="Droite"><img src="$module_dir/images/Parallele_ggb.png" alt="Parallèle">
</div>
