#if defined TARGET_posreldte1 || defined TARGET_posreldte2 || defined TARGET_posreldte3 || defined TARGET_posreldte4 || defined TARGET_posreldte5
# define TITRE Positions relatives de droites
#endif
#if defined TARGET_Calculdist1 || defined TARGET_Calculdist2 || defined TARGET_Calculdist3 || defined TARGET_Calculdist4 || defined TARGET_Calculdist5
# define TITRE Distance &#44; aire et volume
#endif
#if defined TARGET_inter2pl1 || defined TARGET_inter2pl2 || defined TARGET_inter2pl3 || defined TARGET_inter2pl4 || defined TARGET_inter2pl5
# define TITRE Intersection de plans
#endif
#if defined TARGET_interdtepl1 || defined TARGET_interdtepl2 || TARGET_interdtepl3 || defined TARGET_interdtepl4 || defined TARGET_interdtepl5
# define TITRE Intersection de droite et de plan
#endif
#if defined TARGET_posorthdte4 || defined TARGET_posorthdte5
# define TITRE Nature d'un triangle
#endif
#if defined TARGET_posorthdte1 || defined TARGET_posorthdte2 || defined TARGET_posorthdte3
# define TITRE Orthogonalité relative de droites
#endif
#if defined TARGET_patrons1 || defined TARGET_patrons2 || defined TARGET_patrons3 || defined TARGET_patrons4 || defined TARGET_patrons5
# define TITRE Patron et perspective cavalière
#endif
#if defined TARGET_Internonpar1 || defined TARGET_Internonpar2 || defined TARGET_Internonpar3 || defined TARGET_Internonpar4 || defined TARGET_Internonpar5
# define TITRE Plan non parallèle à une face
#endif
#if defined TARGET_Interpar1 || defined TARGET_Interpar2 || defined TARGET_Interpar3 || defined TARGET_Interpar4 || defined TARGET_Interpar5
# define TITRE Plan parallèle à une face
#endif
#if defined TARGET_pos2pl1 || defined TARGET_pos2pl2 || defined TARGET_pos2pl3 || defined TARGET_pos2pl4 || defined TARGET_pos2pl5
# define TITRE Positions relatives de plans
#endif
#if defined TARGET_posrelpl1 || defined TARGET_posrelpl2 || defined TARGET_posrelpl3 || defined TARGET_posrelpl4 || defined TARGET_posrelpl5
# define TITRE Positions de droite et de plan
#endif
