#include "lang_title_fr.inc"

#if defined TARGET_inter2pl1 || defined TARGET_posrelpl1 || defined TARGET_pos2pl1 || defined TARGET_posreldte1 || defined TARGET_posorthdte4 || defined TARGET_posorthdte1 || defined TARGET_Interpar1 || defined TARGET_Calculdist1 || defined TARGET_inter2plan1 || defined TARGET_interdtepl1 || defined TARGET_patrons1 || defined TARGET_Internonpar1
# define NUM I
#endif
#if defined TARGET_inter2pl2 || defined TARGET_posrelpl2 || defined TARGET_pos2pl2 || defined TARGET_posreldte2 || defined TARGET_posorthdte5 || defined TARGET_posorthdte2 || defined TARGET_Interpar2 || defined TARGET_Calculdist2 || defined TARGET_inter2plan2 || defined TARGET_interdtepl2 || defined TARGET_patrons2 || defined TARGET_Internonpar2
# define NUM II
#endif
#if defined TARGET_inter2pl3 || defined TARGET_posrelpl3 || defined TARGET_pos2pl3 || defined TARGET_posreldte3 || defined TARGET_posorthdte3 || defined TARGET_Interpar3 || defined TARGET_Calculdist3 || defined TARGET_inter2plan3 || defined TARGET_interdtepl3 || defined TARGET_patrons3 || defined TARGET_Internonpar3
# define NUM III
#endif
#if defined TARGET_inter2pl4 || defined TARGET_posrelpl4 || defined TARGET_pos2pl4 || defined TARGET_posreldte4 || defined TARGET_Interpar4 || defined TARGET_Calculdist4 || defined TARGET_inter2plan4 || defined TARGET_interdtepl4 || defined TARGET_patrons4 || defined TARGET_Internonpar4
# define NUM IV
#endif
#if defined TARGET_inter2pl5 || defined TARGET_posrelpl5 || defined TARGET_pos2pl5 || defined TARGET_posreldte5 || defined TARGET_Interpar5 || defined TARGET_Calculdist5 || defined TARGET_inter2plan5 || defined TARGET_interdtepl5 || defined TARGET_patrons5 || defined TARGET_Internonpar5
# define NUM V
#endif
\title{TITRE NUM}

