\text{tetra=linewidth 3
polyline black,0,0,24,0,6,18,0,0
polyline black,24,0,18,12,6,18
dsegment 0,0,18,12,black
}
\text{cadre=
xrange -3,30
yrange -3,20
\tetra
text \color[1],-0.4,-0.5,medium,A
text \color[3],24.1,-0.5,medium,C
text \color[2],6,19,medium,B
text \color[4],18.1,12.8,medium,D
text \color[9],1,6.2,medium,M
text \color[10],3,12.2,medium,N
text \color[5],7.8,-0.5,medium,I
text \color[6],15.8,-0.5,medium,J
text \color[7],5.8,5,medium,K
text \color[8],11.8,9,medium,L
text \color[11],12,12.8,medium,O
text \color[12],18.2,6.8,medium,P
text \color[13],10,17,medium,Q
text \color[14],14,15,medium,R
text \color[15],20,9.2,medium,S
text \color[16],22,5.4,medium,T
linewidth 5
points blue,0,0,24,0,6,18,18,12
points green,8,0,16,0,2,6,4,12,6,4,12,8,12,12,18,6,10,16,14,14,20,8,22,4
linewidth 3
\dessin
}
