#if defined TARGET_equaprod1 || defined TARGET_equaprod2 || defined TARGET_equaprod3 || defined TARGET_equaprod4 || defined TARGET_equaprod5
# define TITRE Équation produit
#endif
#if defined TARGET_equatcar3 || defined TARGET_equatcar4 || defined TARGET_equatcar5
# define TITRE Équation
#endif
#if defined TARGET_ineqequi1 || defined TARGET_ineqequi2 || defined TARGET_ineqequi3 || defined TARGET_ineqequi4 || defined TARGET_ineqequi5
# define TITRE Inéquations
#endif
#if defined TARGET_equation1 || defined TARGET_equation2 || defined TARGET_equation3 || defined TARGET_equation4 || defined TARGET_equation5
# define TITRE Résoudre une équation
#endif
#if defined TARGET_inequation1 || defined TARGET_inequation2 || defined TARGET_inequation3 || defined TARGET_inequation4 || defined TARGET_inequation5
# define TITRE Résoudre une inéquation
#endif
#if defined TARGET_representation1 || defined TARGET_representation2
# define TITRE Représentation d'ensemble de nombres
#endif
#if defined TARGET_sysequi1 || defined TARGET_sysequi2 || defined TARGET_sysequi3 || defined TARGET_sysequi4 || defined TARGET_sysequi5
# define TITRE Systèmes d'équations
#endif
#if defined TARGET_solvesys1 || defined TARGET_solvesys2 || defined TARGET_solvesys3 || defined TARGET_solvesys4 || defined TARGET_solvesys5
# define TITRE Résoudre un système d'équations
#endif
#if defined TARGET_representation3 || defined TARGET_representation4 || defined TARGET_representation5
# define TITRE Représentation d'ensemble de nombres
#endif
#if defined TARGET_solution1 || defined TARGET_solution2 || defined TARGET_solution3 || defined TARGET_solution4 || defined TARGET_solution5
# define TITRE Solution
#endif
