#if defined TARGET_equaprod1 || defined TARGET_equaprod2 || defined TARGET_equaprod3 || defined TARGET_equaprod4 || defined TARGET_equaprod5
\text{name_enonce=Quelles sont les solutions de l'équation&nbsp;}
\text{name_youranswer=Votre réponse}
\text{name_reponse=L'ensemble des solutions de l'équation est}
\text{name_inst=S'il y a plusieurs solutions, séparez-les par des virgules.}
\text{name_sol=Solutions}
#endif
