!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les pourcentages avec une seule référence
soit de répartition, soit d'augmentation, soit de diminution,
mais pas d'évolutions successives et rarement des pourcentages de pourcentage.
Ceux-ci seront dans le module
!set target=wims_external
!href module=H5/analysis/oefpercent2.fr Pourcentages 2.
Des exercices comme "Le brevet des collèges", "Le collège A" et "les soldes"
proposent plusieurs méthodes de résolutions.

!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=

!read oef/intromenu.phtml
!tail
