    <table border="0" background="$background" width="90%">
	!if $debug=1
    	<td>
            <div align="right">
            <font color=$fontcolor2>
            debug
            <br>
            </font>
            !href target=wims_mhelp  cmd=help&type=1
            <img src=$gifdir/gear.png alt="DEBUG" border="noborder">
            </a>
            </div>
        </td>
	<tr>
	!endif
	<td>
	    <font color=$fontcolor3>
		$nivo_title
	    <br>
	    </font>
	    <font color=$fontcolor2>
		$vandaag 
	    </font>
	    <br>
	    <font color=$fontcolor1>
		$voornaam
	    <br>
	</td>
	<tr>
	<td>
	    <div align="center">
		!read nivo/answer.phtml
	    </div>
	</td>
	<tr>
	<td>
	    <div align="center">
		<font color=$fontcolor1> 
		<b>    
		Your score is: $module_score
		or lets say: $cijfer
		</b>	 
	    </div>	
	</td>
    !if $poging!=0
	<tr>
	<td>
	    <div align="center">
	    <font color=$fontcolor3>
		<b> 
		$poging
		</b>
	    </font>
	    </div>
	</td>
    !endif
    </table>
</div>
!if $printbaar=3 and $wims_user=supervisor
   !href target=wims_mhelp  cmd=help&printbaar=2&type=3
    <b>print</b> these exercises
    </a>
!endif    