!if $taal=nl
    <tt>I'm sorry, this (english) page is not yet fully functional...</tt>
!endif    
<div align="center">
<table bgcolor="$bgcolor2" width="90%">
    <td>
	<div align="center">
	<h4>
	Hier zie je nog eens een keer de applet, met daarin een afstelbare
	sinus:
	<p align=center>
	<table border=1 width="100%">
	    <td>Functie</td><td>Betekenis</td>
	    <tr>
	    <td>
		!htmlmath y=a+sin(x)
	    </td>
	    <td>
		verticale translatie met <font color=$fontcolor3>a</font>
	    </td>
	    <tr>
	    <td>
		!htmlmath y=a*sin(x)
	    </td>
	    <td>
	    verticale vermenigvulding met <font color=$fontcolor3>a</font>
	    <br> in de natuurkunde heet dit wel "amplitude" ,<br>
	    in de akoestiek regel je met <em>a</a> het "geluidsvolume"
	    </td>
	    <tr>
	    <td>
		!htmlmath y=sin(a+x)
	    </td>
	    <td>
	    horizontale translatie met <font color=$fontcolor3>a</font><br>
	    In de techniek heet dit faseverschuiving
	    </td>
	    <tr>
	    <td>
	    !htmlmath y=sin(a*x)
	    </td>
	    <td>
	    Verandering van de periode met <font color=$fontcolor3>a</font><br>
	    in de natuurkunde heet dit frequentie verandering,<br>
	    in de akoestiek regelt deze <font color=$fontcolor3>a</font> de toonhoogte verandering
	    </td>
	</table>
    </td>
    <tr>
    <td>	
    <applet codebase="$appletdir" archive="jcm1.0-config.jar" code="FamiliesOfGraphs.class" width="600" height="400"> 
    <param name="Parameter1" value="a 0 10 1"> 
    <param name="Function" value="a+sin(x)">  
    <param name="UseFunctionInput" value="no"> 
    <param name="XLabel" value="x-as"> 
    <param name="YLabel" value="y-as"> 
    <param name="UseGrid" value="yes"> 
    <param name="GridColor" value="orange">  
    <param name="UseLimitsPanel" value="no"> 
    <param name="BackgroundColor" value="black"> 
    <param name="Insets" value="5"> 
    <param name="CanvasColor" value="white"> 
    <param name="GraphColor" value="red"> 
    <param name="AxesColor" value="blue"> 
    <param name="PanelBackground" value="yellow"> 
    <param name="BorderWidth" value="0"> 
    <param name="PanelTitle" value="Som voor $wims_user"> 
    <param name="TitleBackground" value="yellow"> 
    <param name="Example1" value="verticale translatie:a+sin(x) ; a+sin(x)">
    <param name="Example2" value="amplitude vergroting (volume):a*sin(x) ; a*sin(x)">
    <param name="Example3" value="horizontale translatie:sin(x+a) ; sin(x+a)">
    <param name="Example4" value="frequentie/periode (toonhoogte):sin(x*a) ; sin(x*a)">
    $geenjava</applet>
    
    </td>
</table>
  
  
  
