!set n=$teller
<table>
    <th>
	<h3>VARIABELEN INFO</h3>
    </th>
    <tr>
    <td> 
	<table>
	    <th>
		<p align="left">
		Config variabelen (intro.phtml)
		</p>
	    </th>
	    <tr>
	    <td>
		<ul>
		    <li>HINT = $HINT </li>
		    <li>bijles = $bijles </li>
		    <li>aantal_sommen = $aantal_sommen </li>
		    <li>nivo = $nivo </li>
		    <li>thema = $thema </li>
		    <li>instinker = $instinker </li>
		    <li>maxpoging = $maxpoging </li>
		</ul>
	    </td>
	</table>    
    </td>
    <tr>
    <td>
	<table>
	    <th>
		<p align="left">
		Module variabelen
		</p>
	    </th>
	    <tr>
	    <td>
		<ul>
		    <li>nivo_title = $nivo_title </li>
		    <li>gifdir = $gifdir </li>
		    <li>bewerking = $bewerking </li>
		    <li>teller = $teller </li>
		    <li>score = $score </li>
		    <li>poging = $poging </li>
		    <li>OPMERKING = $OPMERKING </li>
		    <li>wims_exec_error = $wims_exec_error </li>
		</ul>    
	    </td>
	</table>
    </td>
    <tr>
    <td>
	<table>
	    <th>
		<p align="left">
		Teller/aantal_sommen afhankelijke variabelen
		</p>
	    </th>
	    <tr>
	    <td>
		<ul>
		    <li> opgave $n
			<ul>
    			    <li>GOED$n = $(GOED$n)</li>
			    <li>goed$n = $(goed$n) </li>
			    <li>opmerking$n = $(opmerking$n) </li>
			    <li>latex$n = $(latex$n) </li>
			</ul>
		    </li>
		</ul>  
	    </td>
	</table>
    </td>
</table>