!set n=$teller
!form reply
<div align="center">
    <table border="0" background="$background"  width ="90%">
	<td>
	    <font color=$fontcolor2>
		$vandaag
	    </font>
	    <font color=$fontcolor1>
	    <br>
    		$voornaam $achternaam
	    </font>
	    <br>
	    <font color=$fontcolor7>
		$nivo_title
	    </font>
	</td>
	<tr>
	<td>
	    <div align="center">
		<table>
		    <td>
	    		<font color=$fontcolor3>
			    $OPMERKING
			</font>
			<p>
		    !if $[$maxpoging - $poging] = 1
			<font color=$fontcolor2>$voornaam , I've returned 
			this exercise
			!item $poging of $telwoorden
			    &nbsp;times now <br>
			    for all kinds of trouble...
			    <br>
			    You have -after this one- just one chance left ;
			    so be carefull !
			</font>
		    !endif
			</td>
		    !if $HINT=1 and $FOUT=1
			<tr>
			<td>
			    <font color=$fontcolor2>
			    A Hint:$hint
			    </font>
			</td>
		    !endif
		</table>
	    </div>
	</td>
	<tr>
	<td>
	    <div align="right">
		!read $authordir/rekenmachine2.$taal
	    </div>
	</td>
	<tr>
    !if $debug=1
	<td>
	    <div align="right">
	    !href target=wims_mhelp  cmd=help&type=1
	    <img src=$gifdir/gear.png alt="DEBUG" border="noborder">
	    </a>
	    </div>
	</td>
	<tr>
    !endif 
	<td>
	    <div align="center">	     
		!read $authordir/kladblaadje.$taal
	     <p>
		!read nivo/form.phtml
	    </div>
	</td>
	<tr>
	<td>
	    <div align="center">
		<input type=submit value="OK and SEND">
	    </div>
	</td>
    </table>
    </form>
</div>
!if $printbaar=3 and $wims_user=supervisor
   !href target=wims_mhelp  cmd=help&printbaar=2&type=3
    <b>print</b> these exercises
    </a>
!endif 