!if $wims_user=supervisor
    !if $type=3 
	!read printbaar.phtml
	!exit
    !endif
    !if $type = 1 
	!read debug.phtml
	!exit
    !endif
!endif

!set n=$teller
Always try to write your answer in a clear syntax: <em><font color=garkgreen>f(x)=sin(x)</font></em> 

and thus <font color=red>not</font>something like : <em><font color=red>f(x)=sinx</font></em>
<p>
!if $nivo=1
    The wanted formula is of the next type:
    <img src="$module_dir/gifs/nivo$nivo.$(SIN$n).gif">
    <ul>
	<li>
	    <em> f(x)=d+b*$(SIN$n)(x+c)</em> 
	</li>
	<li>
	    <em> f(x)=d-b*$(SIN$n)(c*x) </em>
	</li>
	<li>
	    <em> f(x)=d*$(SIN$n)(x+c)</em>
	</li>
	<li>
	    <em> f(x)=$(SIN$n)(x+c)</em>
	</li>
	<li>
	    <em> f(x)=$(SIN$n)(c*x+d)  </em>
	</li>
	<li>
	    <em> f(x)=c+$(SIN$n)(x)  </em>	
	</li>
	<li>
	    <em> f(x)=b-$(SIN$n)(x)  </em>
	</li>
	!if $instinker=1
	    <li>
		<em> f(x)=c+$(SIN$n)(x)/d  </em>
	    </li>
	    <li>
		<em> f(x)=b-$(SIN$n)(d*x)/c  </em>
	    </li>
	!endif
    </ul>
    and variations hereof....<br><br>
    !if $instinker=0
	<br>but I promise there are no trics with fractions...
    !else
	<br>but I've mixed some nasty fractions in it<br>
	consider what hapens when <em>d</em> "mover" towards zero in <em><b>f(x)=$(SIN$n)(x)/d</b></em> 
    !endif
    <br><b>
    Sometimes it's useful to adjust a slider to "zero", othertimes it's more handy to set it to "1"
    </b>
!endif

!if $nivo=2

    The wanted formulas are of the general type:<br>
    <img src="$module_dir/gifs/nivo$nivo.$(SIN$n).gif">
    <br>
    The next animated gif shows a "moving" sine-function.<br>
    The 'variable' <b><em>s</em></b> is used to animate the image.
    this "s" moves in 20 steps form <b>0</b> to <b>1</b>. 
    <ul>
	<li><font color=purple size=+1> 
	    <em>  0 < s < 1 </em>
	    &nbsp;a horizontal line 
	    <font>
	</li>
	<li><font color=$fontcolor3 size=+1>
	    <em> f(x)= $(SIN$n)(s*x) </em>
	    <font>
	</li>
	<li><font color=$fontcolor6 size=+1>
	    <em> f(x)= s*$(SIN$n)(x+s) </em>
	    <font>
	</li>
	<li><font color=$fontcolor4 size=+1>	
    	    <em> f(x)= s+$(SIN$n)(x) </em>
	    <font>
	</li>    
    </ul>
    <p align="center">
    <img src=$module_dir/gifs/goniohelp.gif>

!endif
<hr>
<p>
    
!read $authordir/algemenehelp.phtml

