!header

!set taal=en
!readproc authors/jm.evers/$taal/init.proc

!form new
<input type=hidden name=module value="$module">
    <table border="0" cellpadding="5"  width="100%" >
	<td>
	    <font color=$fontcolor1>
		$vandaag
	    </font>
	    <br>
	    <font color=$fontcolor2>
		$voornaam
	    </font>
	</td>
	<tr>
	<td>
	    <center>
	    <table border="0"  cellpadding="5" >
	    !if $expert=1
		<td>
		    <font color=$fontcolor1 size=+1>
		     "Expert menu"
		    </font>
		</td>
		<td>
		    .
		</td>
		<tr>
		!if $wims_user=supervisor	
		    <td>		
			<font color=$fontcolor1>
			    Some "Debug info" 
			</font>
		    </td>
		    <td>
			<right>	
			<select name="debug" size="1">
			    <option value="0">No, I don't need that</option>
			    <option value="1">Yes ,I would like that ?</option>
			</select>
		    </td>
		    <tr>
		!endif	
		<td>
		    <font color=$fontcolor1>
			Some <b>extra</b> support during the exercise ?
		    </font>
		</td>
		<td>
		    <select name="bijles" size="1">
			<option value="1">Yes , very handy while studying</option>
			<option value="0">No thank You , this will be an exam</option>
		    </select>
		</td>
		<tr>
		<td>
		    <font color=$fontcolor1>
			A <b>hint</b> (if present)
		    </font>
		</td>
		<td>
		    <select name="HINT" size="1">
			<option value="0">No , this will be an exam</option>
			<option value="1">Yes</option>
		    </select>
		</td>
		<tr>
		<td>
		    <font color=$fontcolor1>
			How often should the exercise be <b>returned</b><br>
			because of small "syntax" related errors ? 
		    </font>
		</td>
		<td>
		    <select name="maxpoging" size="1">
			<option value="6">six times before a zero score</option>
			<option value="5">five times</option>
			<option value="4">four times</option>
			<option value="3">three times</option>
		    </select>
		</td>		
		<tr>
	    !endif
		<td>
		    <font color=$fontcolor2>
			On what <b>subject</b> would You like to practice?
		    </font>	
		</td>
		<td>
		    <select name="nivo">
			<option value="1">functions like: b*sin(ax+c)</option>
			<option value="2">s*sin(s*x + s): a moving "sine"</option>
		    </select>
		</td>
		<tr>
		<td>
		    <font color=$fontcolor2>
		    	Do you want <b>extra</b> tricky exercises?
		    </font>
		</td>
		<td>    
		    <select name="instinker">
			<option value="0">No</option>
			<option value="1">Yes, let's try</option>
		    </select>
		</td>
		<tr>
		<td>
		    <font color=$fontcolor2>
			How <b>many</b> exercises in a row?
		    </font>	
		</td>
		<td>
		    <select name="aantal_sommen" size="1">
			<option value="5">five exercises for one score</option>
			<option value="4">four</option>
			<option value="3">three</option>
			<option value="2">two</option>
			<option value="1">just one ??</option>
		    </select>
		</td>
!!		<tr>
!!		<td>
!!		    <font color=$fontcolor2>
!!			A <b>printout</b> on paper or an interactive exercise ?
!!		    </font>
!!		</td>
!!		<td>
!!		    <select name="printbaar" size="1">
!!			<option value="0">No, this will be an interactive exercise</option>
!!			<option value="1">Yes, the questions on paper</option>
!!			<option value="2">Yes, I want both questions and answers on paper</option>
!!		    </select>
!!		</td>
		!if $expert=$empty
		<tr>
		<td>
		    <font color=$fontcolor2>
			An "expert-menu" 
		    </font>
		</td>
		<td>
		    !href module=$module&cmd=new&expert=1
		    <b>"expert-menu"</b>
		    </a>
		</td>	
		!endif		
	    </table>
	</td>
	<tr>
	<td>
	    <p align="center">
		<input type=submit value="OK and SEND">
	    </p>
	</td>
    </table>
</form>

!tail
