!if $printbaar isin 1,2
    !read printbaar.phtml
!else
    !if $expert=1
	!read intro.phtml
    !else	    
	!header
	<p>
	<hr>
	<p>
	!if $status=waiting
	    !if $error!=$empty
		!read msg.phtml
		<p>
		<hr width=50%> 
		<p>
	    !endif
	    !read form.phtml
	    <p>
	    !href exo_Renew
	    .
	!else
	    !if $error!=$empty
		!read msg.phtml
		<p>
		<hr width=50%> 
	        <p>
	    !endif
	
	    !read answer.phtml
	        <p>
	    !if $bijles=1 and $module_score < 5
		!read bijles.phtml
		<p>
	    !endif
	
	    !href exo_Again	
	    .
    	
    	    !if $worksheet=$empty
		!href exo_Intro
		.
	
	    !endif
	!endif
	:end
	!tail
    !endif
!endif