!if $cmd=reply and $status!=waiting
     error=double_reply
    !exit
!endif


!if $cmd=reply and $status=waiting
    
    !readproc nivo/$bewerking
	
    !if $poging>$maxpoging
	aantal_sommen=$teller
	!goto KLAAR
    !endif

    !if $TERUG=1
	TERUG=0
	!exit
    !else
	!if $teller=$aantal_sommen
	    :KLAAR 	      	
	    status=done
	    !readproc $authordir/cijfer.$taal.proc
	!else
	    !increase teller
	    !readproc nivo/nivo$nivo
	!endif
    !endif

!endif



