animatie=$[1+1/($aantal_beeldjes-1)]*s
insdraw_animate=yes
ins_anim_frames=$aantal_beeldjes
ins_anim_loop=0
ins_anim_delay=1.2
begin=$[$begin*pi/180]
eenheidscirkel=$XSIZE,$XSIZE\
transparent white\
xrange $XRANGE\
yrange $YRANGE\
linewidth 2\
ellipse 0,0,2,2,$K3\
vline 0,0,black\
hline 0,0,black\
linewidth 1\
vline -2,0,$K4\
vline -1,0,$K4\
vline 1,0,$K4\
vline 2,0,$K4\
hline 0,-2,$K4\
hline 0,-1,$K4\
hline 0,1,$K4\
hline 0,2,$K4\
dhline cos($animatie*$rad + $begin),sin($animatie*$rad + $begin),$K1\
dvline cos($animatie*$rad + $begin),sin($animatie*$rad + $begin),$K1\
linewidth 2\
line 0,0,cos($animatie*$rad + $begin),sin($animatie*$rad + $begin),$K1\
line cos($animatie*$rad + $begin),0,cos($animatie*$rad + $begin),sin($animatie*$rad + $begin),$K1\
line 0,0,cos($animatie*$rad + $begin),0,$K1\
arc 0,0,0.5,0.5,0,$animatie*$graden+$begin,$K2\
linewidth 7\
point cos($animatie*$rad + $begin),sin($animatie*$rad + $begin),$K1\
point cos($animatie*$rad + $begin),0,$K1\
text black,0.1+cos($animatie*$rad + $begin),0.1+sin($animatie*$rad + $begin),huge,$punt\
text black,cos($animatie*$rad + $begin),-0.05,huge,$punt'\
text black,0,0,huge,O\
text black,1,0,normal,1\
text black,-1,0,normal,-1\
text black,-2,0,normal,-2\
text black,-0.05,1,normal,1\
text black,-0.05,-1,normal,-1\
text black,-0.05,-1.9,normal,-2\
textup black,-0.1,1.5,normal,y-as\
text black,1.5,0,normal,x-as\
text black,-0.05,-1,normal,-1



