xsize=400
ysize=400
n=$counter
snappoints=0,0
!for q=0 to 360 step 15
    x=$[cos($q*pi/180)]
    y=$[sin($q*pi/180)]
    snappoints=!append item $x,$y to $snappoints
    SCALE=!append line segment $x,$y,$[0.9*$x],$[0.9*$y],blue to $SCALE
!next q
!for q=0 to 360 step 45
    x=$[cos($q*pi/180)]
    y=$[sin($q*pi/180)]
    SCALE=!append line segment $x,$y,$[0.7*$x],$[0.7*$y],red to $SCALE
!next q

Xmin=-1.4
Xmax=1.4
Ymax=$Xmax
Ymin=$Xmin
XRANGE=$[$Xmax+$Ymax]
YRANGE=$XRANGE
object$n=!exec canvasdraw\
size $xsize,$ysize\
xrange $Xmin,$Xmax\
yrange $Ymin,$Ymax\
linewidth 2\
vline 0,0,blue\
hline 0,0,blue\
linewidth 1\
vline -1,0,blue\
vline 1,0,blue\
hline 0,-1,blue\
hline 0,1,blue\
opacity 255,15\
fellipse 0,0,2,2,blue\
$SCALE \
linewidth 3\
arrowhead 15\
ellipse 0,0,2,2,green\
snaptopoints $snappoints\
userdraw arrow,red\
fontfamily 26px Ariel\
string black,1.05,-0.05,P\
linewidth 10\
point 1,0,red\
point 0,0,red\
string black,0.05,-0.05,O

