!default confparm2=2
<tr><td align=center>Oplossingsmethode<br>
(alleen voor oefeningen met een #)
</td><td>
!formselect confparm2 list 1,2 prompt met hulp,zonder hulp
!default confparm1=1
</td></tr>
<tr><td align=center>Soort coefficienten</td>
<td>
!formselect confparm1 list 1,2,3,4,5,6,7,8 prompt Positief geheel getal, Geheel getal, Positieve breuk, Breuk, Positief decimaal 1, Decimaal 1, Positief decimaal 2, Decimaal 2
</td></tr>