!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur la dérivation en Première.

<ol>
<li>Calcul de nombre dérivé.</li>
<li>Détermination d'une fonction donnée avec des paramètres.</li>
<li>Approximation affine.</li>
<li>Trouver une tangente de direction donnée.</li>
<li>Trouver une tangente passant par un point donné.</li>
<li>Trouver une tangente commune à deux paraboles.</li>
<li>Trouver une tangente à une courbe de degré 4 qui est tangente en 2 points.</li>
</ol>

!read oef/$module_language/intromenu.phtml
!tail
