#!/bin/bash
teller=1
for i in a b c d e f ; do
echo "en nu $teller"
if [ "$teller" =  "6" ] ; then 
gifsicle -U --scale 0.1 --loopcount=5 --delay=14 1.gif 2.gif 3.gif $teller.gif  $teller.gif 4.gif 5.gif 6.gif $teller.gif > $i.gif
else
gifsicle -U --scale 0.1 --loopcount=5 --delay=14 1.gif $teller.gif  2.gif 6.gif $teller.gif 4.gif 4.gif 5.gif $teller.gif > $i.gif

fi 
#--loopcount=1 --delay 10 -U --disposal=bg 

mv $i.gif /var/wims/public_html/modules/contrib/SCHAERSVOORDE/H5/stat/stat-3.nl/dice/$teller.gif
let " teller = teller + 1 "
done
