\if{\del=0}{
\text{tabs1=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black"> \(x)</th>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_0)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr><tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe P</th>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"><span class="larger" style="color:red">+</span></td>
  <td style="width:15%">0</td>
  <td style="width:8%;"><span class="larger" style="color:red">+</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
 </tr>
</table>
avec \(x_0=\sing0\)
}
}{
\text{tabs1=<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black"> \(x)</th>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr>
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe P</th>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">+</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
  </tr>
</table>}
}
\if{\del=0}{
\text{tabs2=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black"> \(x)</th>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_0)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr><tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe P</th>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">+</span></td>
  <td style="width:15%"> 0</td>
  <td style="width:8%"> <span class="larger" style="color:red">+</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
</tr>
</table>
avec \(x_0=\sing00\)
}
}{
\text{tabs2=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <td style="width:15%;border:solid 1px black"> \(x)</td>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr>
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe P</th>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
  </tr>
</table>
}
}
\if{\del=0}{
\text{tabs3=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <td style="width:15%"> \(x)</td>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_0)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr><tr style="border:solid 1px black">
  <td style="width:15%">signe P</td>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%"> 0</td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
 </tr>
</table>
avec \(x_0=\sing0\)
}
}{
\text{tabs3=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black"> \(x)</th>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_1)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_2)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr><tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe P</th>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">+</span></td>
  <td style="width:15%"> 0</td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%"> 0 </td>
  <td style="width:8%"> <span class="larger" style="color:red">+</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
</tr>
</table>
avec \(x_1=\sing1) et \(x_2=\sing2)}
}
\if{\del=0}{
\text{tabs4=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black"> \(x)</th>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_0\)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr><tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe P</th>
  <td style="width:15%;text-align:left"> &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%"> 0</td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
 </tr>
</table>
avec \(x_0=\sing00\)
}
}{
\text{tabs4=
<table class="wimscenter wimsnoborder" style="border:solid 1px black">
<tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black"> \(x)</th>
  <td style="width:15%;text-align:left"> \(-\infty)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_1)</td>
  <td style="width:8%"></td>
  <td style="width:15%">\(x_2)</td>
  <td style="width:8%"></td>
  <td style="width:15%;text-align:right">\(+\infty)</td>
</tr><tr style="border:solid 1px black">
  <th style="width:15%;border:solid 1px black">signe \(P\)</th>
  <td style="width:15%;text-align:left" > &nbsp; </td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%"> 0</td>
  <td style="width:8%"> <span class="larger" style="color:red">+</span></td>
  <td style="width:15%"> 0 </td>
  <td style="width:8%"> <span class="larger" style="color:red">-</span></td>
  <td style="width:15%;text-align:right"> &nbsp; </td>
  </tr>
</table>
avec \(x_1=\sing1\) et \(x_2=\sing2\)
}
}
