!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les fonctions affines et suites arithmétiques.
L'idée est de proposer plusieurs méthodes pour résoudre un problème et d'inciter les élèves à les comparer
puis de mettre l'accent sur les tableaux de valeurs et les graphiques.
Les suites arithmétiques apparaissent comme un cas particulier repérable par leur mode de génération,
la raison de la suite correspondant au coefficient directeur.
Le problème "Coût d'un lot de savons" propose ainsi plusieurs méthodes avec des personnages
que l'on retrouvera
dans d'autres problèmes de ce module "Le meilleur tarif" "La vedette de Bréhat".

!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!!set keyw=

!read oef/intromenu.phtml
!tail
