!!!! This file can contain contents which go after the exercicse list in the intro.
!!Model for some configuration parameters. Uncomment if necessary


!!<tr><td align="center"> </td>
!!<td>
!! !formradio confparm1 from 1 to 3
!!</td>
!!</tr>

!default confparm1=A,B,C
!default confparm2=2,3
!default confparm3=B
!default confparm4=4





<tr><th>Choix du type de fonctions à faire apparaître : </th>
<td>
!set wims_html_mode=li
<ul>
  !formcheckbox confparm1 list A,B,G,C,D,E,F,H prompt fonction x-->x,fonction carré,fonction cube,fonction inverse,fonction valeur absolue,fonction racine carrée,fonctions sinus et cosinus,fonction x-->k^x
  </ul>

</td></tr>
<tr><td>Si plusieurs types de fonctions ont été sélectionnés ci-dessus, chaque exercice contient :</td>
<td>
!set wims_html_mode=li
<ul>
!formradio confparm3 list A,B prompt uniquement des fonctions de même type,éventuellement des fonctions de type différents
 </ul>
</td>
</tr>



<tr><th>Choix des opérations : </th>
<td>
!set wims_html_mode=li
<ul>
  !formcheckbox confparm2 list 1,2,3,4,5,6,7 prompt aucune <i>(dans ce cas cocher sufisamment de types de fonctions dans la liste ci-dessus )</i>,a*f,f+b,a*f+b,f(x+k),f(x+k)+b,a*f(x+k)+b
</ul>

<tr><th>Nombre de courbes (ou fonctions) proposées : </th>
<td>
!formradio confparm4 from 3 to 6
</td>
</tr>
