!let mempara=$empty
!for i=1 to 50
   !reset repexo$i
!next i
!let repexo=$empty
!let nbreesscalc=0
!let evitecalc=0
<u><b>Voici la liste des actions possibles :</b></u>

<table border=1>
<tr><td>

<table border=0>
<tr><td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="2">
<input type="hidden" name="action" value="3">
<input type="submit" value="Soustraire/Ajouter"> </form></td><td>une même expression <b>aux deux</b> plateaux de la balance.
</td>

</tr>
<tr><td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="2">
<input type="hidden" name="action" value="2">
<input type="submit" value="Diviser/Multiplier"></form> </td><td valign="middle">par un nombre les contenus <b>des deux</b> plateaux.
</td>

</tr>

!!if $nocalcul!=1 
 <tr><td align="right" valign="middle">
 !form reply
 <input type="hidden" name="status" value="2">
 <input type="hidden" name="action" value="7">
 <input type="submit" value="Simplifier"> </form></td><td valign="middle">l'écriture de l'équation obtenue à la dernière étape.
 </td>

</tr>
!!endif
<tr><td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="3">
<input type="hidden" name="action" value="4">
<input type="submit" value="Déclarer&nbsp;que&nbsp;l'exercice&nbsp;est&nbsp;terminé"> </form></td><td valign="middle"> (pour voir son score ou passer à l'exercice suivant).
</td>

</tr>
</table>

</td><td>

<table border="0"><tr>
<td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="2">
<input type="hidden" name="action" value="10">
<input type="submit" value="Soustraire/Ajouter"> </form></td><td>une expression au plateau <b>gauche</b> de la balance.
</td>
</tr>
<tr>
<td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="2">
<input type="hidden" name="action" value="12">
<input type="submit" value="Soustraire/Ajouter"> </form></td><td>une expression au plateau <b>droit</b> de la balance.

</td>
</tr>
<tr>
<td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="2">
<input type="hidden" name="action" value="9">
<input type="submit" value="Diviser/Multiplier"> </form></td><td valign="middle">par un nombre le contenu du plateau <b>gauche</b>.

</td>
</tr>
<tr>
<td align="right" valign="middle">
!form reply
<input type="hidden" name="status" value="2">
<input type="hidden" name="action" value="11">
<input type="submit" value="Diviser/Multiplier"> </form></td><td valign="middle">par un nombre le contenu du plateau <b>droit</b>.

</td>
</tr>
</table>

</td></tr></table>
