!header
!let wims_backslash_insmath=yes
$module_title est un outil proposant de résoudre pas à pas une équation, modélisée par une 
balance équilibrée dont une des masses est inconnue.
A la fin, quand on déclare que l'exercice est terminé, un score est calculé en fonction 
du nombre d'erreurs de calcul, du nombre d'erreurs de raisonnement
et du nombre d'étapes (sauf si l'option correspondante est désactivée ci-dessous).
<p>
Ce module a été créé sur le modèle de celui qui concerne la résolution libre
 d'équations, d'inéquations ou de systèmes d'équations : 
!href module=H3/algebra/eqineq voir cet autre module 
<hr> <p>

!default nocalcul=1
!default nbreexo=1
!default difficulte=1
!default sanctetape=1

!form new
<ul>

<li>Forme de l'&eacute;nonc&eacute (voir le d&eacute;tail ci-dessous)
!formselect difficulte from 1 to 3
</li>

<li> Nombre d'exercices
!formselect nbreexo from 1 to 8
</li>

<li> Réduire le score en fonction du nombre d'étapes 
!formselect sanctetape from 1 to 2 prompt Oui,Non
</li>

</ul>

</ul>
<input type=hidden name=module value=$module> 
<center><input type=submit value="Au travail"></center>
</form>
<hr>
D&eacute;tails sur la forme de l'&eacute;nonc&eacute; :<br>
<table border=1>
 <tr><td>Forme</td><td>Equation</td></tr>
 <tr><td>1</td><td>\(aX+b=c)</td></tr>
 <tr><td>2</td><td>\(aX+b=cX+d)</td></tr>
 <tr><td>3</td><td>\(e(aX+b)=cX+d)</td></tr>
</table>

!tail
