# Variable initialisation file.
# This file is read by wims for new sessions.

# content of the file: initialisation of the problem.

renewlink=cmd=renew&worksheet=$worksheet&$module_init_parm

!default status=0
!! C : nombre erreurs calcul 
!! R : nombre erreurs raisonnement
!! E : nombre d'étapes
!if $sanctetape=1
   !default bareme=10-1*(C)-2*(R)-2*(max(0,E-$difficulte-1))
!else
   !default bareme=10-1*(C)-2*(R)
!endif
wims_module_log=$cmd
noexo=1
exogood=0
noteinter=0
penche0=0

insmath_rawmath=yes
wims_backslash_insmath=yes
listaction=src/comb.phtml,src/multiplier.phtml,src/transposer.phtml,src/conclure.phtml,src/substituer.phtml,src/dessiner.phtml,src/simplifier.phtml,src/echanger.phtml,src/multgauche.phtml,src/transpgauche.phtml,src/multdroite.phtml,src/transpdroite.phtml
meserreur=<p> <b> Erreur: </b> Vous avez envoyé une réponse incomplète ou incompréhensible. Veuillez la corriger. <p>
erreur=$empty
evitecalc=0

symbole==,<,>,<=,>=
symboleaff==,<,>,\leq,\geq
