#if defined TARGET_fctinverse
# define TITRE Forme canonique d'un quotient (1)
#endif
#if defined TARGET_fctinverse2
# define TITRE Forme canonique d'un quotient (2)
#endif
#if defined TARGET_parabole
# define TITRE Parabole et forme canonique
#endif
#if defined TARGET_snddegre
# define TITRE Forme canonique du second degré (1)
#endif
#if defined TARGET_snddegre2
# define TITRE Forme canonique du second degré (2)
#endif
#if defined TARGET_varfct2degcomp
# define TITRE Variation d'une fonction du second degré (par composition)
#endif
#if defined TARGET_varfctcarre
# define TITRE Variation d'une fonction du second degré
#endif
#if defined TARGET_varffctinv
# define TITRE Variation d'une fonction homographique
#endif
