!set n=$counter
<script type="text/javascript">
    function retry(t){
	var URL; 
	if(t == 1){
	    URL = '$wims_ref_name?session=$session&module=$module&+cmd=reply&retryexo=1' ;
	}
	else
	{
	    URL = '$wims_ref_name?session=$session&module=$module&+cmd=reply&retryexo=0' ;
	}
	document.location.href = URL;
    }
</script>

!set max=!itemcnt $not_ready
!set rem=!record 5 of lang/remarks.$taal
!!#@Je score is $tmpscore uit 10...<br />De volgende $max sommen <b>mag</b> je overdoen:
$rem
<ul>
    !for p in $not_ready
	<li><span style="color:#ff0000">$questionnumber $p</span></li>
    !next p
</ul>
<div class="embedded_central">
<input style="background-color:#71ff82;font-weight:normal;font-size:16px;text-align:center;" type="button"" onclick="retry(1);" value="$retry" />
<input style="background-color:#ff5255;font-weight:normal;font-size:16px;text-align:center;" type="button"" onclick="retry(0);" value="$noretry" />
</div>






