\consigne
<ul class="inline"><li>
\embed{reply1,1,<img src="gifs/images/methods//\ListImage[1]" alt="\Listdesc[1]">}
\bch1
</li><li>
\embed{reply1,2,<img src="gifs/images/methods//\ListImage[2]" alt="\Listdesc[2]">}
\bch2
</li><li>
\embed{reply1,3,<img src="gifs/images/methods//\ListImage[3]" alt="\Listdesc[3]">}
\bch3
</li><li>
\embed{reply1,4,<img src="gifs/images/methods//\ListImage[4]" alt="\Listdesc[4]">}
\bch4
</li>
\if{\nb_meth>=5}{
<li>
\embed{reply1,5,<img src="gifs/images/methods//\ListImage[5]" alt="\Listdesc[5]">}
\bch5
</li>}
\if{\nb_meth>=6}{<li>
\embed{reply1,6,<img src="gifs/images/methods//\ListImage[6]" alt="\Listdesc[6]">}
\bch6
</li>}
</ul>
