!header
!read Exindex
<style>
.logo_desc_mod {
  float:right;
  margin-left:0.5em;
  margin-right:0.2em;
  margin-top:0.2em;
}
</style>

Ce module regroupe pour l'instant $exototal exercices sur la notion d'ordre 
et d'intervalle pour le début du lycée.
Il fait partie du groupement Ev@lwims pour cette classe.

!let test=!text select char abcdefghijklmnopqrstuvwxyz in $wims_version
!if $test!=$empty
 !let test=!positionof item $test in a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
 !let test=!char 2 to 3 of $[100+$test]
 !let test2=!text select char 1234567890. in $wims_version
 !let test=$test2$test
!else
 !let test=$wims_version
!endif
!if $test>4.02
 <p>
 Vous pouvez voir les exercices dans leur contexte d'utilisation en visitant  
 !href module=adm/class/classes/&+exampletype=3 les classes ouvertes
 .
 </p>
!endif

<img src="$module_dir/images/logo_euler.png" class="logo_desc_mod" alt="Logo Euler Académie de Versailles" title="Euler Académie de Versailles" width="48" height="36">
<div class="wims_credits">
Module de Régine Mangeard et Jean-Pierre Boudine maintenu et complété par le groupe Euler de l'académie de Versailles.
</div>

!read oef/intromenu.phtml
!tail
