#if defined TARGET_antecedent
# define TITRE Recherche graphique d'antécédents
#endif
#if defined TARGET_image
# define TITRE Image d'un nombre par une fonction
#endif
#if defined TARGET_resoGraphEq1 || defined TARGET_resoGraphEq2
# define TITRE Résoudre graphiquement une équation
#endif
#if defined TARGET_resoGraphIn1 || defined TARGET_resoGraphIn2 || defined TARGET_resoGraphIn3
# define TITRE Résolution graphique d'inéquation
#endif
#if defined TARGET_signe
# define TITRE Signe d'une fonction
#endif
