!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les calculs
avec des fractions et les représentations de fractions sur un axe
gradué.<p>
Il s'agit pour la plupart d'exercices qui existaient déjà (dans des
 modules
programmés par B. Perrin-Riou, G. Xiao et M. Gosse) et qui ont
été modifiés (en les simplifiant pour les adapter à des élèves de 5ème
ou de 6ème).
</p><p>Dans les exercices d'additions et de soustractions, un des
dénominateurs est toujours multiple de l'autre et les virgules sont
 (exceptionnellement) acceptées.</p>

!read related.phtml fractions
!href module=tool/number/fractrep.fr Un outil de représentation des fractions

!read oef/$module_language/intromenu.phtml
!tail
