\if{\tt=2}{
  Compléter le schéma suivant avec les données de la question 1.<br>
\special{imageinput \url1, 400x350, 3
reply2, 60x240
reply3, 140x100,1
reply4, 220x110
reply5, 220x220
reply6, 300x200,1}
}
\if{\tt=3}{
  Compléter le tableau de proportionnalité avec les données de la question 1.<br>
  \special{codeinput [\mat1],\size1, div
  reply2
  reply4
  reply3
  reply5
  reply6}
}
\if{\tt=4}{
  <p>Compléter le schéma suivant avec les données de la question 1.</p>
  <p>Pourcentage d'augmentation</p>
  \special{mathmlinput [\large{ reply2\; \overset{\phantom{xxx}+ reply3\%\phantom{xxxx}}{\underset{\times reply6 /100}{\mapsto}}\; reply5}],5
reply2
reply3
reply6
reply5}
}
