<table class="wimscenter wimsborder">
<tr><td></td><th>\name_header[1;1]</th><th>\name_header[1;2]</th>
  <th>\name_header[1;3]</th><th>\name_header[1;6]</th></tr>
<tr><th>\name_header[2;1]</th><td>\a</td><td>\b</td><td>\c</td><td>\g</td></tr>
<tr><th>\name_header[2;2]</th><td>\ar</td><td>\br</td><td>\cr</td><td>\gr</td></tr>
<tr><th>\name_header[2;3]</th><td>\t1 %</td><td>\t2 %</td><td>\t3 %</td><td>\tga %</td></tr>
</table>
Pour l'ensemble des trois collèges, on calcule \fgs.<br>
Environ \tga % des élèves de l'ensemble des trois collèges ont été reçus.
