\if{\tt=1}{
  <table class="wimscenter wimsborder">
  <tr><td></td><th>\name_header[1;1]</th><th>\name_header[1;2]</th><th>\name_header[1;3]</th></tr>
  <tr><th>\name_header[2;1]</th><td>\a</td><td>\b</td><td>\embed{reply4,3}</td></tr>
  <tr><th>\name_header[2;2]</th><td>\embed{reply2,3}</td><td>\br</td><td>\cr</td></tr>
  <tr><th>\name_header[2;3]</th><td>\t1 %</td><td>\embed{reply3,2} %</td><td>\t3 %</td></tr>
  </table>
  Le pourcentage de reçus sur l'ensemble des 3 collèges est : \embed{reply5,3} %.
}
\if{\tt=2}{
  Un dessin comme celui-ci aide à comprendre l'énoncé.<br>
  <img src="\url" alt="\urlt" /><br>
  Le reproduire à l'échelle équivaut à résoudre le problème.
}
\if{\tt=3}{
  <p>
  Reproduire les tableaux de proportionnalité au brouillon ou sur un tableur et les compléter.
  </p>
  \tableauA<br />
  \tableauB<br />
  \tableauC<br />
  \tableauG
}
\if{\tt=4}{
  <p>
  Il est facile de traduire les pourcentages en égalités de fractions.</p>
  pour le collège A par : \fa<br>
  pour le collège B par : \fb<br>
  pour le collège C par : \fc<br>
  pour les 3 collèges  par : \fg<br>
}
\if{\tt=5}{
  <p>
  On recherche l'opérateur qui permet de passer du tout à la partie.</p>
  pour le collège A : \opa<br>
  pour le collège B : \opb<br>
  pour le collège C : \opc<br>
}
