\if{\tt=1}{
  <ul class="wims_nopuce">
  <li>
  <label for="reply2">
  Combien d'élèves du collège A ont été reçus au brevet des collèges ?</label> \embed{reply2,3}
  </li><li>
  Quel est le pourcentage de reçues parmi les filles candidates du collège A ? \embed{reply3,3} %
  </li><li>
  Combien de garçons ont été reçus au brevet des collèges ? \embed{reply4,3}<br>
  Quel est le pourcentage de reçus parmi les garçons candidats du collège A ? \embed{reply5,3} %
  </li></ul>
}
\if{\tt=2}{
  <p>Un dessin comme celui-ci aide à comprendre l'énoncé.</p>
  <p><i>Ce dessin n'est pas à l'échelle.</i><br>
  Le réaliser à l'échelle équivaut à résoudre le problème.</p>

  <img src="\url" alt="" />
    }
\if{\tt=3}{
  <p>Reproduire le tableau de proportionnalité au
  brouillon ou sur un tableur et complétez-le.
  </p>
  \tabA
  }
\if{\tt=4}{
  <p>Recopier et compléter ce schéma.<br>
  La couleur du pourcentage est celle de l'ensemble de référence :
  rouge pour les filles, bleue pour les garçons et verte pour l'ensemble des candidats.</p>
  <img src="\url2" alt="" />
  }
\if{\tt=5}{
  <p>Recopier et compléter ce schéma.</p>
  La couleur du pourcentage est celle de l'ensemble de référence :<br>
  rouge pour les filles, bleue pour les garçons et verte pour l'ensemble des candidats.</p>
  <img src="\url4" alt="" />
  <p class="mygreen">
  \tAr % des candidats ont été reçus.</p>
}
