Au collège A, \A élèves étaient candidats au brevet des collèges et \tAr % ont été reçus.<br>
Il y avait \tfA % de filles parmi les candidats et \fr filles ont été reçues.

<ul class="wims_nopuce"><li>
  Combien d'élèves du collège A ont été reçus au brevet des collèges ?
  </li><li>
  Quel est le pourcentage de reçues parmi les filles candidates du collège A ?
  </li><li>
  Combien de garçons ont été reçus au brevet des collèges ?<br>
  Quel est le pourcentage de reçus parmi les garçons candidats du collège A ?
  </li>
</ul>
