\if{\tt=2}{
Compléter le schéma suivant avec les données de la question 1.
<br />

\special{imageinput \url1, 400x240, 3
reply2, 60x130
reply3, 140x50,1
reply4, 215x60
reply5, 215x170
reply6, 300x150,1
}
}
\if{\tt=3}{
  Compléter le tableau de proportionnalité avec les données de la question 1.
  <table class="wimscenter wimsborder">
  <tr><td>1.</td><td>\name_header[1]</td><td>\name_header[2]</td></tr>
  <tr><td>\name_header[3]</td><td>\embed{reply 2,3}</td><td>100 %</td></tr>
  <tr><td>\name_header[4]</td><td>\embed{reply 4,3}</td><td>\embed{reply 3,2} %</td></tr>
  <tr><td>\name_header[5]</td><td>\embed{reply 5,3}</td><td>\embed{reply 6,2} %</td></tr>
  </table>
}
\if{\tt=4}{
  <p>Compléter le schéma suivant avec les données de la question 1.</p>
  <p>Pourcentage de diminution</p>
 \special{mathmlinput [\large{ reply2 \; \overset{\phantom{xxx}- reply3\%\phantom{xxxx}}{\underset{\times reply6 /100}{\mapsto}}\; reply5 }],5
reply2
reply3
reply6
reply5}
}
