!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes

<tr><td><strong>Dans les exercices, la question porte sur le </strong></td>
<td>
 !formcheckbox confparm1 list 1,2 prompt Numérateur,Dénominateur
</td>
</tr>


<tr><td><strong>Dans les exercices, la variable des expressions est </strong></td>
<td>
 !formcheckbox confparm2 list 1,2,3,4,5,6 prompt x,\(e^x),\(\cos(x)),\(\sin(x)),\(\sqrt{x}),\(\ln(x))
</td>
</tr>
