!! On pose les questions dans ce fichier. D'habitude, c'est par
!! des forms. Voici un exemple de conception de la forme de r閜onse.

!if $status=waiting

!if $click_cnt=0
请点击
!if $proj=1 
投影的端点 : 
!else
一个向量的端点 :
!endif
!else
!if $proj=2
点击第二个向量的端点 :
!endif
!endif

<p>
!form reply
!distribute item alt=Cliquer,1,form click  into ins_attr,ins_border,ins_tag

<center>
!insdraw\
$dessin\
$dessin1
</center>
</form>
!endif

</form>
