!header

<b>$module_title </b>是关于平面向量沿两个方向的分解或投影的练习.
<p> <p><hr> <p>

!form new

 !set liste=orth, paral
 !set mode=$liste
  !set proj=1
  !set diff=1
它要求你画出已知向量沿着两个
  !formselect mode list $liste prompt 正交,任意
方向的
 !formselect proj list 1,2 prompt 投影,分解
. 

 <p>
难度 :
!formradio diff list  1,3,4,5 prompt 1,2,3,4
(当难度超过 1 时, 会出现干扰直线)
<input type=hidden name=module value="$module">
<center><input type=submit value="开始">
</center>
</form>

.

!tail
