!default confparm1=1
<tr><th>Nombre de questions par exercice de calcul
</th><td>
!formselect confparm1 list 1,2,3,4,5
</td></tr>
!default confparm2=5
<tr><th>Nature de la variable</th>
<td>
!formselect confparm2 list 1,2,3,4,5 prompt Entier positif,Entier relatif,Fraction positive,Fraction relative,Quelconque
</td></tr>
!default confparm3=5
<tr><th>Nature des coefficients</th>
<td>
!formselect confparm3 list 1,2,3,4,5 prompt Entiers positifs,Entiers relatifs,Fractions positives,Fractions relatives,Quelconques
</td></tr>
