\text{name_and=et}
\text{name_yourreply=Votre réponse&nbsp;}
#if defined TARGET_rapara
note for translators: keep commas
\text{name_statement=Écrire deux rapports qu'il faut comparer pour montrer que les droites,sont parallèles en utilisant la réciproque du théorème de Thalès,ne sont pas parallèles en utilisant le théorème de Thalès}
\text{name_instruction=Utiliser les étiquettes ci-dessous pour compléter l'égalité}
#endif
#if defined TARGET_raplong1 || defined TARGET_raplong2 || defined TARGET_raplong3 || defined TARGET_raplong4
note for translators: keep commas
\text{name_statement=Quelles égalités de rapports peut-on déduire en utilisant le théorème de Thalès,dans les triangles}
\text{name_instruction=Utilisez les étiquettes ci-dessous pour compléter les égalités}
\text{name_condition=Bons rapports}
#endif
#if defined RAPPORT
\text{name_solution=Les bonnes égalités de rapports sont&nbsp;}
note for translators: keep commas
\text{name_hypos=Les droites,sont parallèles,Le quadrilatère,est un parallèlogramme,est un point de la demi-droite,est un point du segment,est le point d'intersection des droites,sont sécantes en,les droites}
\text{name_or=ou}
#endif
#if defined LONGEUER || defined PARALLELE
\text{name_question=Question}
\text{name_instruction=Le dessin est indicatif et ne respecte pas les longueurs de l'énoncé}
#endif
#if defined LONGEUER
note for translators: keep commas
\text{name_statement=Les droites,sont sécantes en,Les droites,sont parallèles,Le but est de calculer la longueur du segment,connaissant les longueurs suivantes&nbsp;}
\text{name_answer=Réponse}
\text{name_question1=En utilisant le théorème de Thalès, écrire l'égalité de rapports qui permet de trouver la longueur de}
\text{name_question2=Quelle est la longueur, au millimètre près, de }
\text{name_label=Quelle est la longueur, au millimètre près, de}
\text{name_separator=Utilisez le point comme séparateur pour les décimales.}
\text{name_length=longueur}
#endif
#if defined PARALLELE
note for translators: keep commas
\text{name_bad=sont égaux et les triplets de points,sont rangés dans le même ordre,ne sont pas égaux, sont égaux,ne sont pas égaux et les triplets de points,sont rangés dans le même ordre}
\text{name_bad2=la réciproque du théorème de Thalès,le théorème de Thalès,le théorème de Pythagore,la réciproque du théorème de Pythagore}
\text{name_bad3=sont parallèles,ne sont pas parallèles}
note for translators: keep commas
\text{name_statement=Les points,sont alignés et les points,le sont aussi comme sur la figure,On connaît les distances suivantes&nbsp;}
note for translators: keep commas
\text{name_question1=Les droites,sont-elles parallèles&nbsp;}
\text{name_question2=Écrire (en utilisant les étiquettes en bas de page) deux rapports de longueurs utiles pour répondre à la question&nbsp;}
\text{name_question3=Remplacer les longueurs par leurs valeurs et réduire les deux fractions aux mêmes dénominateurs pour les comparer&nbsp;}
note for translators: keep commas
\text{name_question4=Les rapports,Je déduis donc,par,que les droites}
note for translators: keep commas
\text{name_reply=En utilisant,je déduis que les droites}
note for translators: keep commas
\text{name_answers=Numérateur,Dénominateur,Valeur numérateur,Valeur dénominateur,Ordre,Théorème,Conclusion}
note for translators: keep commas
\text{name_condition=Bons rapports,Même dénominateur,Réduction du premier rapport,Réduction du deuxième rapport}
#endif
