#if defined TARGET_raplong1
# define TITRE Rapports Thalès général
#endif
#if defined TARGET_raplong2
# define TITRE Rapports Thalès triangle
#endif
#if defined TARGET_raplong3
# define TITRE Rapports Thalès 2 triangles emboités
#endif
#if defined TARGET_raplong4
# define TITRE Rapports Thalès 2 triangles non emboités
#endif
#if defined TARGET_rapara
# define TITRE Droites parallèles
#endif
#if defined TARGET_pap
# define TITRE Longueur papillon
#endif
#if defined TARGET_pap2
# define TITRE Longueur papillon 2
#endif
#if defined TARGET_triangle
# define TITRE Longueur triangle
#endif
#if defined TARGET_triangle2
# define TITRE Longueur triangle 2
#endif
#if defined TARGET_parat1
# define TITRE Parallèles (triangle)
#endif
#if defined TARGET_parap1
# define TITRE Parallèles (papillon)
#endif
#if defined TARGET_parat2
# define TITRE Parallèles (triangle) 2
#endif
#if defined TARGET_parap2
# define TITRE Parallèles (papillon) 2
#endif