!! variable supplementaire pour la conf

!! choix du nombre de question
!default confparm1=1
<tr><th>Nombre de questions par exercice de calcul
</th><td>
!formselect confparm1 list 1,2,3,4,5
</td></tr>
!! signe des nombres utilises
!default confparm2=1
<tr><th>Les nombres aléatoires sont
</th><td>
!formselect confparm2 list 1,2 prompt Tous positifs,Quelconques
</td></tr>

!! demander ou non la simplification des resultats
<tr><td colspan="2">
!formcheckbox confparm3 from 1 to 1 prompt Ne pas demander de simplifier les résultats
</td></tr>
