!header
!read Exindex

Ce module regroupe pour l'instant $exototal exercices de calcul avec des fractions.
<div class="spacer">
Le titre de certains exercices contient une lettre dont la signification est la suivante :
<ul>
 <li> A : un des dénominateurs est multiple de l'autre&nbsp;;</li>
 <li> B : dénominateurs premiers entre eux&nbsp;;</li>
 <li> C : dénominateurs non premiers entre eux&nbsp;;</li>
 <li> D : dénominateurs égaux.</li>
</ul>
</div>
!read oef/$module_language/intromenu.phtml
!tail
