!header
!read Exindex

!if $lang iswordof it

  Questo modulo contiene al momento $exototal esercizi sui polinomi in una
  variabile (con coefficienti reali o complessi) con domande relative a:
  radici, grado, composizioni, divisione euclidea, ...

!goto end
!endif

!if $lang iswordof en

  This module actually contains $exototal exercises on one-variable polynomials 
  (with real or complex coefficients): roots, degrees, composition, euclidean
  division, ...

!goto end
!endif

Ce module regroupe pour l'instant $exototal exercices sur les polynômes à une
variables (avec coefficients réels ou complexes)&nbsp;: racines, degrés,
composition, division euclidienne, ...

:end
!read oef/intromenu.phtml
!tail
