#if defined TARGET_rectangle1 || defined TARGET_rectangle2 || defined TARGET_rectangle3 || defined TARGET_rectangle4 || defined TARGET_rectangle5 || defined TARGET_rectangle6
# define TITRE Rectangle
#endif
#if defined TARGET_rat || defined TARGET_rat2
# define TITRE Fonctions rationnelles
#endif
#if defined TARGET_poly || defined TARGET_poly2
# define TITRE Polynome
#endif
#if defined TARGET_mult1 || defined TARGET_mult2
# define TITRE Multiplication
#endif
#if defined TARGET_multmixt
# define TITRE Multiplication mixte
#endif
#if defined TARGET_trigo || defined TARGET_trigo2  || defined TARGET_trigo3
# define TITRE Fonctions trigonométriques
#endif
#if defined TARGET_hyper || defined TARGET_hyper2
# define TITRE Fonctions hyperboliques
#endif
#if defined TARGET_compvert1a || defined TARGET_compvert1b
# define TITRE Composition virtuelle
#endif
#if defined TARGET_circle || defined TARGET_circle2 || defined TARGET_circle3 || defined TARGET_circle4
# define TITRE Cercle
#endif
#if defined TARGET_multvert1
# define TITRE Multiplication virtuelle
#endif
#if defined TARGET_div1
# define TITRE Division
#endif
#if defined TARGET_arcarg
# define TITRE Arc et Arg
#endif
#if defined TARGET_divmixt
# define TITRE Division mixte
#endif
#if defined TARGET_comp1 || defined TARGET_comp2
# define TITRE Composition
#endif
#if defined TARGET_compmixt
# define TITRE Composition mixte
#endif
#if defined TARGET_reciproc
# define TITRE Dérivée réciproque
#endif
#if defined TARGET_righttriangle
# define TITRE Triangle droit
#endif
#if defined TARGET_tower
# define TITRE Tour
#endif
#if defined TARGET_signenombre
# define TITRE Signe d'un nombre
#endif
