#if defined TARGET_rectangle1 || defined TARGET_rectangle2 || defined TARGET_rectangle3 || defined TARGET_rectangle4 || defined TARGET_rectangle5 || defined TARGET_rectangle6
# define TITRE_en Rectangle
#endif
#if defined TARGET_rat || defined TARGET_rat2
# define TITRE_en Rational functions
#endif
#if defined TARGET_poly || defined TARGET_poly2
# define TITRE_en Polynomial
#endif
#if defined TARGET_mult1 || defined TARGET_mult2
# define TITRE_en Multiplication
#endif
#if defined TARGET_multmixt
# define TITRE_en Mixed multiplication
#endif
#if defined TARGET_trigo || defined TARGET_trigo2  || defined TARGET_trigo3
# define TITRE_en Trigonometric functions
#endif
#if defined TARGET_hyper || defined TARGET_hyper2
# define TITRE_en Hyperbolic functions
#endif
#if defined TARGET_compvert1a || defined TARGET_compvert1b
# define TITRE_en Virtual multiplication
#endif
#if defined TARGET_circle || defined TARGET_circle2 || defined TARGET_circle3 || defined TARGET_circle4
# define TITRE_en Circle
#endif
#if defined TARGET_multvert1
# define TITRE_en Virtual multiplication I
#endif
#if defined TARGET_div1
# define TITRE_en Division
#endif
#if defined TARGET_arcarg
# define TITRE_en Arc and Arg
#endif
#if defined TARGET_divmixt
# define TITRE_en Mixed division
#endif
#if defined TARGET_comp1 || defined TARGET_comp2
# define TITRE_en Composition
#endif
#if defined TARGET_compmixt
# define TITRE_en Mixed composition
#endif
#if defined TARGET_righttriangle
# define TITRE_en Right triangle
#endif
#if defined TARGET_tower
# define TITRE_en Tower
#endif
#if defined TARGET_signenombre
# define TITRE_en Sign of a number
#endif
#if defined TARGET_reciproc
# define TITRE_en Inverse derivative
#endif
