!if $subject isitemof 9,10,11
    <table>
	<tr>
	<td>
	    Soit la fonction
	</td>
	<tr>
	<td>
	    <img src=$module_dir/gifs/inverse-1.gif/><br />
	</td>
	<tr>
	<td>
	    Pour déterminer la fonction réciproque f<sup>-1</sup> de f, on fait la symétrie du graphe de la fonction par rapport à la droite d'équation  y=x<br />
	</td>
	<tr>
	<td>
	    <img src=$module_dir/gifs/inverse-3.gif/><br />	    
	</td>
	<tr>
	<td>
	    Donc on écrit :
	</td>
	<tr>
	<td>
	    <img src=$module_dir/gifs/inverse-2.gif/><br />
	</td>
	<tr>
	<td>
	    Vous pouvez écrire votre réponse sous la forme:
	</td> 
	<tr>
	<td>
	    <textarea cols="35" rows="2" readonly="readonly">y = 1/(x - 4)</textarea><br />
	</td>
	<tr>
	<td>
	    Attention: les parenthèses peuvent être importantes !
	</td>
	<tr>
	<td>
	    <em>y = 1/x - 4</em> n'est pas la même chose que <em>y = 1/(x - 4)</em>
	</td>
	<tr>
	<td>
	    Vous pouvez aussi écrire votre réponse sous la forme :
	</td>
	<tr>
	<td>
	    <textarea cols="35" rows="2" readonly="readonly">f^-1(x) = 1/(x - 4)</textarea><br />
	</td>
	</tr>
    </table>
!endif
