!if $subject isitemof 9,10,11
    <table>
	<tr>
	<td>
	    Given the function:
	</td>
	</tr><tr>
	<td>
	    <img src=$module_dir/gifs/inverse-1.gif/><br />
	</td>
	</tr><tr>
	<td>
	    To determine the inverse function f<sup>-1</sup> of f , we actually mirror the function in the line  y=x<br />
	</td>
	</tr><tr>
	<td>
	    <img src=$module_dir/gifs/inverse-3.gif/><br />	    
	</td>
	</tr><tr>
	<td>
	    So we write:
	</td>
	</tr><tr>
	<td>
	    <img src=$module_dir/gifs/inverse-2.gif/><br />
	</td>
	</tr><tr>
	<td>
	    Your answer may be written like:
	</td>
	</tr><tr>
	<td>
	    <textarea cols="35" rows="2" readonly="readonly">y = 1/(x - 4)</textarea><br />
	</td>
	</tr><tr>
	<td>
	    Remember: brackets do matter !
	</td>
	</tr><tr>
	<td>
	    <em>y = 1/x - 4</em> is not the same as <em>y = 1/(x - 4)</em>
	</td>
	</tr><tr>
	<td>
	    Your answer may also be written like:
	</td>
	</tr><tr>
	<td>
	    <textarea cols="35" rows="2" readonly="readonly">f^-1(x) = 1/(x - 4)</textarea><br />
	</td>
	</tr>
    </table>
!endif
