!if $subject isitemof 9,10,11
    <table>
	<tr>
	<td>
	    Gegeven de functie:
	</td>
	</tr><tr>
	<td>
	    <img src=$module_dir/gifs/inverse-1.gif/><br />
	</td>
	</tr><tr>
	<td>
	    Om de inverse functie f<sup>-1</sup> van f te bepalen, spiegelen we de functie a.h.w. in de lijn y=x<br />
	</td>
	</tr><tr>
	<td>
	    <img src=$module_dir/gifs/inverse-3.gif/><br />	    
	</td>
	</tr><tr>
	<td>
	    We schrijven dus: 
	</td>
	</tr><tr>
	<td>
	    <img src=$module_dir/gifs/inverse-2.gif/><br />
	</td>
	</tr><tr>
	<td>
	    Jij mag als eindantwoord noteren:
	</td>
	</tr><tr>
	<td>
	    <textarea cols="35" rows="2" readonly="readonly">y = 1/(x - 4)</textarea><br />
	</td>
	</tr><tr>
	<td>
	    Denk eraan dat haakjes wel belangrijk zijn...
	</td>
	</tr><tr>
	<td>
	    <em>y = 1/x - 4</em> is zeker niet gelijk aan <em>y = 1/(x - 4)</em>
	</td>
	</tr><tr>
	<td>
	    Jij mag ook als eindantwoord noteren:
	</td>
	</tr><tr>
	<td>
	    <textarea cols="35" rows="2" readonly="readonly">f^-1(x) = 1/(x - 4)</textarea><br />
	</td>
	</tr>
    </table>
!endif

!if $subject=22	 and level>2
    <img src="$module_dir/gifs/exp1.jpg" alt="noalt" />
    <br />
    <img src="$module_dir/gifs/exp2.jpg" alt="noalt" />
!endif
