!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

!read tableau.phtml
<br>($score1 / 6)<br>
!insdraw $graphe
<br><table bgcolor=lightyellow><tr><td>
La droite d'équation 
!insmath \sin(i_2)=$rapport \times \sin(i_1)
est représentée en bleu ci-dessus.
</td></tr></table>
<br>($score2 / 3)<br>
!insmath \frac{n_1}{n_2}=
!if $score3>0
 $rapport : bonne réponse
!else
 <span style="text-decoration: line-through;">
  <font color=red>$rapport</font>
 </span>
 ... correction
!insmath \frac{n_1}{n_2}=
 <font color=blue>$[round($indice1/$indice2*100)/100]</font>
!endif
<br> ($score3 / 1)
<hr>
<table bgcolor=lightyellow><tr><td>
Vous avez obtenu $module_score (sur 10) points pour l'ensemble des trois questions.
</td></tr></table>