!! Placez ici des aides à l'exercice.

Lois de Descartes de la réfraction :
<ol>
<li>Le rayon incident et le rayon réfracté sont tous deux dans le plan d'incidence</li>
<li>Le rayon incident et le rayon réfracté se situent de part et d'autre de la normale au point d'incidence</li>
<li>Soient 
!insmath n_1
et 
!insmath n_2
les indices respectifs des milieux 1 et 2, 
!insmath i_1 
et 
!insmath i_2
les angles d'incidence et de réfraction. La relation suivante est vérifiée&nbsp;:
<center>
!insmath n_1 \sin(i_1) = n_2 \sin(i_2)
</center></li>
</ol>