!header

$module_title est l'analyse d'une expérience de réfraction de la lumière
<p><hr> <p>

 !form new
 <input type=hidden name=module value=$module>
 L'exercice peut être configuré par les paramètres suivants.
 <table border="1">
<tr><th>Milieu N°1 traversé par la lumière</th>
<th>Milieu N°2 traversé par la lumière</th></tr>
<tr><td>
<ol>
  <li>
   <input type=radio name=m1 value=1 checked>
     air&nbsp;;
  <li>
   <input type=radio name=m1 value=2>
     eau&nbsp;;
  <li>
   <input type=radio name=m1 value=3>
     verre ordinaire&nbsp;;
  <li>
   <input type=radio name=m1 value=4>
     verre spécial(flint)&nbsp;;
  <li>
   <input type=radio name=m1 value=5>
     diamant&nbsp;;
 </ol>    
</td><td>
<ol>
  <li>
   <input type=radio name=m2 value=1>
     air&nbsp;;
  <li>
   <input type=radio name=m2 value=2 checked>
     eau&nbsp;;
  <li>
   <input type=radio name=m2 value=3>
     verre ordinaire&nbsp;;
  <li>
   <input type=radio name=m2 value=4>
     verre spécial(flint)&nbsp;;
  <li>
   <input type=radio name=m2 value=5>
     diamant&nbsp;;
 </ol>    
</td></tr>
</table>
Nombre de mesures : <select name="nm">
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
</select>
<center>
 <input type=submit value="Au travail">
 </center> 
</form>
!tail