!! Ce fichier présente la question à résoudre.

!if $debug = 1
  <h1>DEBUG MODE</h1>
!endif


!!!!!!!!!!!!!!!!!!!!!!!! STEP 2 !!!!!!!!!!!!!!!!!!!!!!!
!if $step=2
 <h3>Tracez le graphique pour les sinus</h3>
!endif $step=2
!!!!!!!!!!!!!!!!!! STEP 1 !!!!!!!!!!!!!!!!!!!!!!!!!
!if $step=1
 <h3>Complétez le tableau</h3>
 On a mesuré les angles d'incidence et de réfraction d'un rayon de
 lumière traversant un dioptre $milieu1/$milieu2. Les indices optiques
 respectifs de ces deux milieux transparents sont
 !insmath n_1
 = $indice1 et
 !insmath n_2
 = $indice2 .
 <table bgcolor=lightyellow><tr><td>
  Complétez le tableau suivant en calculant les sinus des angles
  d'incidence et de réfraction. Attention&nbsp;: la calculette
  doit être réglée en degré (vérifiez que
  !insmath \sin(90^{\circ})=1
  ).
 </td></tr></table>
<script type="text/javascript">
  var a; /* angle en radian */
  var v; /* valeur du sinus, cosinus ou tangente, sans unité */
  function get_a(){
    angle=document.getElementById("angle").value;
    unite=document.getElementById("unite").value;
    a=angle*unite;
  }
  function set_a(){
    if (a=="undef"){
      document.getElementById("angle").value="undef";
    } else{
      unite=document.getElementById("unite").value;
      angle=a/unite;
      document.getElementById("angle").value=angle;
    }
  }
  function get_v(){
    v=document.getElementById("trig-value").value;
  }
  function set_v(){
    document.getElementById("trig-value").value=v;
  }
  function asin(){
    get_v();
    if (v<-1 || v >1){
      a="undef";
      set_a();
    } else {
      a=Math.asin(v);
      set_a();
    }
  }
  function sin(){
    get_a();
    v=Math.sin(a);
    set_v();
  }
  function acos(){
    get_v();
    if (v<-1 || v >1){
      a="undef";
      set_a();
    } else {
      a=Math.acos(v);
      set_a();
    }
  }
  function cos(){
    get_a();
    v=Math.cos(a);
    set_v();
  }
  function atan(){
    get_v();
    a=Math.atan(v);
    set_a();
  }
  function tan(){
    get_a();
    v=Math.tan(a);
    set_v();
  }
</script>
<div id="calc-trigo" >
<table style="padding:0.5em; border:3px ridge navy; background:lightcyan; -moz-border-radius: 1em;" >
<tr>
  <td colspan="6" style="text-align:center;" >
    <b>Angle:</b>
    <input id="angle" value="0" style="text-align:right; border:3px ridge navy; -moz-border-radius: 0.5em;">&nbsp;
    <select id="unite" style="text-align:right; border:3px ridge navy; -moz-border-radius: 0.5em;">
      <option value="0.017453292519943295769">°&nbsp;</option>
      <option value="1">rad&nbsp;</option>
    </select >
  </td>
<tr>
  <td><button onclick="sin(); return false;" style="border:2px outset navy; -moz-border-radius: 0.5em;">&darr;sin</button></td>
  <td><button onclick="asin(); return false;" style="border:2px outset navy; -moz-border-radius: 0.5em;">&uarr;asin</button></td>
  <td><button onclick="cos(); return false;" style="border:2px outset navy; -moz-border-radius: 0.5em;">&darr;cos</button></td>
  <td><button onclick="acos(); return false;" style="border:2px outset navy; -moz-border-radius: 0.5em;">&uarr;acos</button></td>
  <td><button onclick="tan(); return false;" style="border:2px outset navy; -moz-border-radius: 0.5em;">&darr;tan</button></td>
  <td><button onclick="atan(); return false;" style="border:2px outset navy; -moz-border-radius: 0.5em;">&uarr;atan</button></td>
</tr>
<tr>
  <td colspan="6" style="text-align:center;" >
    <b>Value:</b>
    <input id="trig-value"  value="0" style="text-align:right; border:3px ridge navy; -moz-border-radius: 0.5em;">
  </td>
<tr>
</table>
</div>


!endif $step=1
!!!!!!!!!!!!!!!!!!!!!!!! STEP 3 !!!!!!!!!!!!!!!!!!!!!!!
!if $step=3
 <h3>Calculez le rapport des indices optiques</h3>
 (voir ci-dessous)
!endif $step=3
