!header

!read Exindex
This module actually contains $exototal exercises on one-variable polynomials 
(with real or complex coefficients): roots, degrees, composition, euclidean
division, ...

<div class="wims_warning">Please note that this module is obsolete and it is only kept for
backwards compatibility. You should use the module
!href module=H6/algebra/oefpoly.fr OEF Polynomial
instead, that contains an updated English version.
</div>

!read oef/intromenu.phtml
!tail
