!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

!read tableau.phtml
<br>($score1 / 6)<br>
!insdraw $graphe
<br><table bgcolor="lightyellow" summary=""><tr><td>
De grafiek van de vergelijking
!insmath \sin\left(i_{2}\right)\,=\, $rapport \times \sin\left(i_{1}\right)
 is getekend in blauw.
</td></tr></table>
<br>($score2 / 3)<br>
!insmath \frac{n_{1}}{n_{2}}\,=\,
!if $score3>0
 $rapport : correct antwoord
!else
 <span style="text-decoration: line-through;">
  <font color="red">$rapport</font>
 </span>
 <br>
 ... correctie
!insmath \frac{n_{1}}{n_{2}}\,=\,
 <font color=blue>$[round($indice1/$indice2*100)/100]</font>
!endif
<br> ($score3 / 1)
<hr>
<table bgcolor="lightyellow" summary=""><tr><td>
Je eindscore  voor de  drie opdrachten is $module_score punten (uit 10).
</td></tr></table>