!! On pose les questions dans ce fichier. D'habitude, c'est par
!! des forms. Voici un exemple de conception de la forme de réponse.

!form reply
!!!!!!!!!!!!!!!!!!!! STEP 1 !!!!!!!!!!!!!!!!!!!!
!if $step=1
 !read tableau.phtml
 <br><input type=submit value="OK en Opsturen">
!endif $step=1
!!!!!!!!!!!!!!!!!!!!!! STEP 2 !!!!!!!!!!!!!!!!!!!!!!!!!!!
!if $step=2
 <table summary=""><tr><td>
  !read tableau.phtml
  <br>Score tussenstand: $score1 / 6.<br> 
 </td><td>
 <table bgcolor="lightyellow" summary=""><tr><td>
 Teken in de grafiek de waarden van
 !insmath \sin\left(i_{2}\right)
 op de y-as, en de waarden van
 !insmath \sin\left(i_{1}\right)
 op de x-as.<br>
 <em>Teken de punten op het grafiek papier door met je muis op de co&ouml;rdinaten te klikken.<br>
 Je kunt het geplaatste punt verwijderen door op "Verwijder laatste punt" te klikken.<br>
 Als alle punten geplaatst zijn, klik op "Klaar en Versturen"
 </em>
 </td></tr></table>
  </td></tr></table>
 !if $debug=1
 <p>
   <h3>laatste punt : $dernier_point</h3>
   <b>lijst punten :</b> $liste_points <br>
  </p>
 !endif
 <p>
 <input type=submit name="fini" value="Klaar en Versturen"> 
 <input type=submit name="annuler" value="Verwijder laatste punt">
 <p>
 !set ins_tag=form click
 !insdraw $graphe
!endif $step=2
!!!!!!!!!!!!!!!! STEP 3!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!if $step=3
 !read tableau.phtml
 <br>Tussenstand eindscore&nbsp; $score1 / 6.<br> 
 !insdraw $graphe
 <br>
 score &nbsp;: $score2 / 3
 <p>
 <table bgcolor="lightyellow" summary=""><tr><td>
 De correcte punten liggen op een rechte lijn met vergelijking: 
 !insmath y \,=\,a\times x
 <br>of in dit geval:<br>
 !insmath \sin\left(i_{2}\right) = \frac{n_{1}}{n_{2}} \cdot \sin\left(i_{1}\right)
 
 <p>
 Bereken nu de richtings co&euml;fficient van de rechte:
 !insmath a = \frac{n_{1}}{n_{2}}= \cdot\cdot\cdot
 <br>
 De richtings co&euml;fficient = <input type=text name=rapport size=5>
 </td></tr></table>
 <input type=submit value="Klaar en Versturen"> 
!endif 
!!! $step=3
!!!!!!!!!!!!!!! step > 1 !!!!!!!!!!!!!!!!!!!!!!
!if $step >1
 !for i=1 to $nm
  <input type="hidden" name="sini$i" value="$(sini$i)">
  <input type="hidden" name="sinr$i" value="$(sinr$i)">
 !next i
!endif

</form>
