!header

<tt>$module_title</tt> is een oefening over de 'wet van Snellius' 
<p><hr> <p>

 !form new
 <input type=hidden name=module value=$module>
 Deze module kan worden geconfigureerd:
 <table border="1" summary="">
<tr><th>Medium No °1</th>
<th>Medium No °2 </th></tr>
<tr><td>
<ol>
  <li>
   <input type=radio name=m1 value=1 checked>
     lucht&nbsp;;
  <li>
   <input type=radio name=m1 value=2>
     water&nbsp;;
  <li>
   <input type=radio name=m1 value=3>
     glas&nbsp;;
  <li>
   <input type=radio name=m1 value=4>
     speciaal glas (flint)&nbsp;;
  <li>
   <input type=radio name=m1 value=5>
     diamant&nbsp;;
 </ol>    
</td><td>
<ol>
  <li>
   <input type=radio name=m2 value=1>
     lucht&nbsp;;
  <li>
   <input type=radio name=m2 value=2 checked>
     water&nbsp;;
  <li>
   <input type=radio name=m2 value=3>
    glas&nbsp;;
  <li>
   <input type=radio name=m2 value=4>
     speciaal glas(flint)&nbsp;;
  <li>
   <input type=radio name=m2 value=5>
     diamant&nbsp;;
 </ol>    
</td></tr>
</table>
Aantal metingen : <select name="nm">
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
</select>
<center>
 <input type=submit value="OK en aan het werk">
 </center> 
</form>
!tail