!! Ce fichier présente la question à résoudre.

!if $debug = 1
  <h1>DEBUG MODE</h1>
  $debugstr
!endif

!!!!!!!!!!!!!!!!!!!!!!!! STEP 2 !!!!!!!!!!!!!!!!!!!!!!!
!if $step=2
 <h3>Teken de grafiek</h3>
!endif $step=2
!!!!!!!!!!!!!!!!!! STEP 1 !!!!!!!!!!!!!!!!!!!!!!!!!
!if $step=1
 <h3>Vul de tabel aan</h3>
 In een experiment meten we de in- en uittrede hoek van bundel licht door het grenvlak [diopter] van $milieu1/$milieu2 .<br>
 De brekingsindexen van de twee media zijn gegeven en zijn respectievelijk: 
 !insmath n_{1}
 = $indice1 en
 !insmath n_{2}
 = $indice2 .
 <table bgcolor="lightyellow" sumarry=""><tr><td>
 Vul de tabel nu zelf verder in en breken de sinus van de in- en uitgaande hoeken.<br>
 Let op: <em>de gemeten hoeken staan gegeven in graden.</em>
 </td></tr></table>
!endif $step=1
!!!!!!!!!!!!!!!!!!!!!!!! STEP 3 !!!!!!!!!!!!!!!!!!!!!!!
!if $step=3
 <h3>
 Bereken de verhouding van de brekingsindexen.
 </h3>
 (zie hieronder)
!endif $step=3
