<span "style=color:grey;"> geef je antwoord op 3 decimalen nauwkeurig</span>
<table border="1" summary="">
<tr>
<th>
 !insmath i_{1}
 (graden)
</th>
!for i from 1 to $nm
 <td>
  $(incid$i)
 </td>
!next i
</tr>
<tr>
<th>
 !insmath i_{2}
 (graden)
</th>
!for i from 1 to $nm
 <td>
  $(refra$i)
 </td>
!next i
</tr>
<tr>
<th>
 !insmath \sin\left(i_{1}\right)
</th>
!for i from 1 to $nm
 <td>
 !if $step=1
  !if $debug=1
   <input type=text size=7 name=sini$i value=$(c_sini$i) >
  !else
   <input type=text size=7 name=sini$i >
  !endif
 !else
  !if $(g_sini$i)=1
   <font color="green">$(sini$i)</font>
  !else
   <span style="text-decoration: line-through;">
     <font color="red">$(sini$i)</font>
   </span>
   <br><font color="blue">$(c_sini$i)</font>
  !endif
 !endif $step=1
 </td>
!next i
</tr>
<tr>
<th>
 !insmath \sin\left(i_{2}\right)
</th>
!for i from 1 to $nm
 <td>
 !if $step=1
  !if $debug=1
   <input type=text size=7 name=sinr$i value=$(c_sinr$i) >
  !else
   <input type=text size=7 name=sinr$i>
  !endif
 !else
  !if $(g_sinr$i)=1
   <font color="green">$(sinr$i)</font>
  !else
   <span style="text-decoration: line-through;">
     <font color="red">$(sinr$i)</font>
   </span>
   <br><font color="blue">$(c_sinr$i)</font>
  !endif
 !endif $step=1
 </td>
!next i
</tr>
</table>
