#if defined TARGET_typesol
# define TITRE Type de solutions
#endif
#if defined TARGET_solution
# define TITRE 3 solutions
#endif
#if defined TARGET_3bottles
# define TITRE 3 bouteilles
#endif
#if defined TARGET_alloy3
# define TITRE Alliage 3 métaux
#endif
#if defined TARGET_almostdiag
# define TITRE Presque diagonal
#endif
#if defined TARGET_Intersectiondr
# define TITRE Intersection de droites
#endif
#if defined TARGET_centercircle
# define TITRE Centre de cercle
#endif
#if defined TARGET_Sommetstriangl
# define TITRE Sommets triangle
#endif
#if defined TARGET_quadrilat
# define TITRE Quadrilatère
#endif
#if defined TARGET_triangular
# define TITRE Système triangulaire
#endif
#if defined TARGET_solve3x3
# define TITRE Résoudre 3x3
#endif
#if defined TARGET_solve2x2
# define TITRE Résoudre 2x2
#endif
#if defined TARGET_Distancesgales
# define TITRE Distances égales
#endif
#if defined TARGET_circleeq
# define TITRE Equation de cercle
#endif
#if defined TARGET_achat
# define TITRE Au marché
#endif
#if defined TARGET_Troisentiers
# define TITRE Trois entiers
#endif
#if defined TARGET_Quatreentiers
# define TITRE Quatre entiers
#endif
#if defined TARGET_Quatreentier2
# define TITRE Quatre entiers II
#endif
#if defined TARGET_Quatreentier3
# define TITRE Quatre entiers II
#endif
#if defined TARGET_sixentiers
# define TITRE Six entiers
#endif
#if defined TARGET_homo3x4
# define TITRE Homogène 3x4
#endif
#if defined TARGET_homo2x3
# define TITRE Homogènes2x3
#endif
#if defined TARGET_ages
# define TITRE 3 âges
#endif
