!set introhook_exists=yes

!set name_introhook= Vocabulaire, altitude,cote\
Forme\
Grille\
Translation,la grille ne sera pas activée si $wims_name_yes est cochée

!default confparm1=1
!default confparm2=1
!default confparm3=grid
!default confparm4=0
<tr><th>$(name_introhook[1;1])</th>
<td>
  !formradio confparm1 from 1 to 2 prompt $(name_introhook[1;2,3])
</td>
</tr>
<tr><th>$(name_introhook[2;])</th>
<td>
  !formradio confparm2 from 1 to 3
</td>
</tr>
<tr><th>$(name_introhook[3;])</th>
<td>
  !formradio confparm3 list grid,nogrid prompt $wims_name_yes,$wims_name_no
</td>
</tr>
<tr><th>$(name_introhook[4;1])
</th>
<td>
  !formradio confparm4 list 0,1 prompt $wims_name_no,$wims_name_yes
  <div class="formhelp">$(name_introhook[4;2])</div>
</td>
</tr>
