!header
!read Exindex

!if $lang=it
  Questo modulo raggruppa attualmente $exototal esercizzi sui
  numeri complessi.
  <p>
  Quando viene richiesto un numero complesso, questo deve essere
  necessariamente inserito nella forma
  <span class="tt">a+b*i</span>.
  </p>
!goto end
!endif
!if $lang=es
  Actualmente, este módulo contiene $exototal ejercicios
  sobre números complejos.
  <p>
  En los ejercicios en los que se pide responder con un número complejo, se debe
  ingresar el número bajo la forma <span class="tt">a+b*i</span>.
  </p>
!goto end
!endif
!if $lang=nl
  Deze module bevat op dit moment $exototal oefeningen over complexe getallen.
  !goto end
!endif
!if $lang=fr
  Ce module regroupe pour l'instant $exototal exercices sur les nombres
  complexes.
  <p>
  Pour des exercices qui demandent de répondre par un nombre complexe, il faut
  impérativement saisir le nombre complexe sous
  la forme <span class="tt">a+b*i</span>.
  </p>
  !goto end
!endif

This module actually contains $exototal  exercises on complex numbers.
<p>
For exercises which ask to reply with a complex number, you must enter the
number under the form <span class="tt">a+b*i</span>.
</p>
:end
!read oef/intromenu.phtml
!tail
