!header
!read Exindex
<style>
/**** Bloc description du module ****/
.desc_mod{
  width:80%;
  margin-left:auto;
  margin-right:auto;
  border:1px solid $wims_ref_bgcolor;
  border-top-left-radius: 11px;
  border-top-right-radius: 11px;
}
.title_desc_mod{
  color:white;
  background:$wims_ref_bgcolor;
  border-top-left-radius:10px;
  border-top-right-radius:10px;
  margin-bottom:0px;
  margin-top:0px;
  padding-top:0.5em;
  padding-bottom:0.5em;
}

.p_desc_mod {
  padding-right:0.5em;
  padding-left:0.5em;
} 
</style>
<div class="desc_mod">
 <h2 class="wimscenter title_desc_mod">Description du module</h2>
 <p class="p_desc_mod">Ce module regroupe pour l'instant $exototal exercices sur la trigonométrie au collège.
  <br class="spacer">
  Par défaut certains exercices sont configurés ainsi&nbsp;: 
 </p>
 <ul>
   <li>les figures sont affichées dans l'énoncé et dans la solution&nbsp;;</li>
   <li>la ligne trigonométrique est choisie aléatoirement&nbsp;;</li>
   <li>dans les exercices à étapes, à la fin de chacune d'entre elles, quelle que soit la réponse, le serveur donne accès à l'étape suivante, 
   l'analyse de la réponse est indiquée et la bonne réponse est donnée en cas d'erreur.
   </li>
 </ul>
 <p class="p_desc_mod"> 
  Ces réglages peuvent être modifiés plus bas dans <em>Paramétrage spécifique à certains exercices du module</em> et viennent compléter le 
  <em>Paramétrage de l'affichage des aides</em> proposé dans <em>Paramétrage expert</em>.
 </p>
 <p class="p_desc_mod">
   Les exercices 01, 02 et 03 utilisent un type de réponse spécialement adapté par Julien Lyotard.
 </p>
</div>
!read oef/intromenu.phtml
!tail
