!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes

<div class="field box">
<strong>Figures</strong> (pour tous les exercices <strong>sauf</strong> 01, 02 et 03)&nbsp;:
<p><strong>Cocher pour NE PAS afficher de figure(s)&nbsp;:</strong></p>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formcheckbox confparm1 list 1,2 prompt dans l'énoncé,dans la solution
</ul>
</div>

<div class="field box">
<strong>Ligne(s) trigonométrique(s)</strong> (pour tous les exercices <strong>sauf</strong> 01, 02, 03, 04, 05, 06 et 10)&nbsp;: 
<p>choisie(s) aléatoirement parmi&nbsp;:</p>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formcheckbox confparm2 list 1,2,3 prompt sin&nbsp;,cos&nbsp;,tan
</ul>
Si vous ne cochez rien, le serveur choisira aléatoirement pour chaque génération de l'exercice une des 3 lignes trigonométriques.
</div>

<div class="field box">
<strong>Exercices à étapes</strong> (pour les exercices 09, 10 et 11)&nbsp;:
!set wims_ref_id=confparm3_1
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm3 list 1 prompt Ne pas proposer l'étape suivante en cas de réponse fausse à l'étape en cours
</ul>
Sinon, proposer l'intégralité de l'exercice et à la fin de chaque étape, pour l'étape suivante&nbsp;:

!set wims_ref_id=confparm3_2
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm3 list 2 prompt indiquer si la réponse est exacte ou non et donner la réponse exacte en cas d'erreur
</ul>

!set wims_ref_id=confparm3_3
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm3 list 3 prompt indiquer si la réponse est exacte ou non et ne pas donner la réponse exacte en cas d'erreur (à utiliser si on veut proposer plusieurs essais possibles)
</ul>
!set wims_ref_id=confparm3_4
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm3 list 4 prompt ne pas indiquer si la réponse est exacte ou non et ne pas donner la réponse exacte en cas d'erreur (à utiliser si on veut proposer plusieurs essais possibles)
</ul>
</div>
