\author{Euler,Versailles}
%%%CK GM %%%
\language{\lang}
\email{euler.wims@ac-versailles.fr}
\format{html}
\computeanswer{no}

\if{\lang=fr}{
#if defined TARGET_01CliquerHypotenuse || defined TARGET_02CliquerAdjacent || defined TARGET_03CliquerOppose || defined TARGET_04ReconTrRect1 || defined TARGET_04ReconTrRect2 || defined TARGET_05ReconTrRect3
\keywords{hypoténuse}
#endif

#if defined TARGET_06AssocVocTrigo || defined TARGET_07IdentifierLigneTrigo1 || defined TARGET_08IdentifierLigneTrigo2 ||defined TARGET_09DonnerLigneTrigo || defined TARGET_10DeuxMesures || defined TARGET_11LigneTrigoUniteEtape || defined TARGET_12LigneTrigoUnite
\keywords{cosinus,sinus,tangent}
#endif

\credits{Figure(s) réalisée(s) avec JSXGraph}
}
