%%%%%% ENONCES FRANCAIS %%%%%

\text{enonce1=
<p><span class="nowrap"> \A\B\C </span> est un triangle rectangle en \Sommet.</p>
<p><span class="quest">Associer les nombres égaux.</span></p>
}

\text{enonce2=
<p><span class="nowrap"> \A\B\C </span> est un triangle rectangle en \Sommet.</p>
Reconnaître le <strong>cosinus</strong>, le <strong>sinus</strong> et la <strong>tangente</strong> de l'angle 
<span class="nowrap">\(\widehat{\NomAngle}\).</span>
}


%%%% ACCORDION %%%%%
\text{title_accord1=Comment relier deux cases&nbsp;?}
\text{title_accord2=Comprendre les codes couleurs}
\text{procedure1=
<ul class="euler_ul"> 
 <li>Pour relier deux cases&nbsp;:
  <ul class="euler_ul">
    <li>cliquer sur l'une puis sur l'autre,</li>
    <li>ou déplacer l'une sur l'autre.</li>
  </ul>
  La case de droite vient alors à la hauteur de la case de gauche et une flèche apparaît.
  <li>Pour modifier une liaison déjà établie, utiliser les mêmes méthodes.</li>
</ul>
}

\text{procedure2=
<ul class="euler_ul">
  <li>Couleur de fond et du liseré&nbsp;:</li>
    <ul class="euler_ul">
      <li>vert : la réponse est entièrement exacte,</li>
      <li>orange : la réponse est partiellement exacte,</li>
      <li>rouge : la réponse est entièrement fausse.</li>
    </ul>
  <li>Couleur des étiquettes de la colonne de droite&nbsp;:</li>
    <ul class="euler_ul">
      <li>vert : la correspondance est exacte,</li>
      <li>rose : la correspondance est fausse.</li>
    </ul>
</ul>
}
%%%%% TABLE SOLUTION %%%%
\text{th1=Définition}
\text{th2=Application}
\text{co=longueur du côté opposé à l'angle}
\text{ca=longueur du côté adjacent à l'angle}
\text{hypot=longueur de l'hypoténuse}
