%%%%%%%%% SELON LANGUE %%%%%%%%%

%%% LEGENDES JSXGRAPH %%%
#if !defined TARGET_01CliquerHypotenuse
\text{legend1=hypoténuse}
\text{legend2=côté adjacent}
\text{legend3=côté opposé}
\text{legend4=à}
#endif


\text{Line_name=le sinus,le cosinus,la tangente}

#if defined TARGET_10DeuxMesures
\text{delangle=de l'angle}
#endif


\text{Line_cote=du côté opposé,du côté opposé à l'angle,du côté adjacent,du côté adjacent à l'angle,de l'hypoténuse}

\text{phrase=Vous avez répondu&nbsp;:}
\text{phrase2=Nous avons&nbsp;:}
\text{rep_exacte=Votre réponse est exacte.}
\text{rep_fausse=Votre réponse est fausse.}
\text{rep_incomp=Votre réponse est incomplète.}
\text{rep_imprec=Votre réponse est partiellement exacte.}
\text{la_sol=Réponse exacte&nbsp;:}

#if defined TARGET_09DonnerLigneTrigo || defined TARGET_11LigneTrigoUniteEtape || defined TARGET_10DeuxMesures
\text{introetap=La réussite d'une étape donne accès à l'étape suivante. Sinon l'exercice s'interrompt.}
#endif
