#if defined TARGET_01CliquerHypotenuse
\description{Vous devez cliquer sur l’hypoténuse du triangle rectangle donné.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés. 
Il est demandé de cliquer sur le segment qui en est l'hypoténuse.}
#endif

#if defined TARGET_02CliquerAdjacent
\description{Vous devez cliquer sur le côté adjacent à l’angle aigu précisé du triangle rectangle donné.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés. 
Il est demandé de cliquer sur le segment qui est le côté adjacent à l’angle aigu précisé.}
#endif

#if defined TARGET_03CliquerOppose
\description{Vous devez cliquer sur le côté opposé à l’angle aigu précisé du triangle rectangle donné.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés. 
Il est demandé de cliquer sur le segment qui est le côté opposé à l’angle aigu précisé.}
#endif 

#if defined TARGET_04ReconTrRect1
\description{Vous devez donner les noms des côtés du triangle rectangle donné correspondants à 
l’hypoténuse, aux côtés adjacent et opposé à l’angle aigu précisé.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés. 
Il est demandé d'indiquer les noms des côtés du triangle rectangle correspondants à 
l’hypoténuse, aux côtés adjacent et opposé à l’angle aigu précisé.}
#endif

#if defined TARGET_04ReconTrRect2
\description{Vous devez placer les étiquettes pour préciser les noms des côtés du triangle rectangle donné correspondants 
à l’hypoténuse, aux côtés adjacent et opposé à l’angle aigu précisé.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés.
Il est demandé de déplacer les étiquettes pour indiquer les noms des côtés du triangle rectangle correspondants
 à l’hypoténuse, aux côtés adjacent et opposé à l’angle aigu précisé.}
#endif

#if defined TARGET_05ReconTrRect3
\description{Pour chaque côté, vous devez préciser s’il est l’hypoténuse, le côté adjacent ou opposé d’un des angles 
du triangle rectangle.}
\observation{Dans ce QCM, un triangle rectangle et sa représentation graphique sont donnés. 
Il est demandé pour chaque côté du triangle rectangle donné, de préciser s’il est l’hypoténuse, le côté adjacent ou opposé d’un des 
angles aigus de ce triangle.}
#endif

#if defined TARGET_06AssocVocTrigo
\description{Vous devez associer l'étiquette de chaque ligne trigonométrique d’un angle donné du triangle rectangle 
avec le quotient correspondant.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés.   
Il est demandé d’associer les trois lignes trigonométriques de l’angle aigu considéré à chaque quotient 
correspondant.}
#endif

#if defined TARGET_07IdentifierLigneTrigo1
\description{Vous devez identifier les côtés dont les longueurs sont connues et déterminer la ligne trigonométrique à utiliser.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés.  
Un QCM demande pour chaque côté du triangle rectangle dont on connait la longueur, de préciser s’il est l’hypoténuse, le côté 
adjacent ou opposé d’un des angles aigus du triangle rectangle puis d'indiquer à quelle ligne 
trigonométrique correspondent les deux longueurs données.}
#endif

#if defined TARGET_08IdentifierLigneTrigo2
\description{Vous devez déterminer la ligne trigonométrique à utiliser.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés ainsi que les 
longueurs de deux de ses côtés. 
Il est demandé d'indiquer, pour l'angle précisé, quelle ligne trigonométrique correspond aux deux longueurs données.}
#endif

#if defined TARGET_09DonnerLigneTrigo
\description{Vous devez déterminer la ligne trigonométrique à utiliser et reconnaitre l'égalité correcte.}
\observation{Dans cet exercice à 2 étapes, un triangle rectangle et sa représentation graphique sont donnés ainsi que les 
longueurs de deux de ses côtés. Il est demandé d'indiquer, pour l'angle précisé, quelle ligne trigonométrique correspond aux 
deux longueurs données puis sélectionner l'expression faisant intervenir ces deux longueurs égale à cette ligne trigonométrique.}
#endif

#if defined TARGET_10DeuxMesures
\description{Vous devez identifier les rapports trigonométriques calculables étant données les longueurs données de deux côtés
 d'un triangle rectangle, construire les égalités puis en déduire les mesures en degrés des deux angles aigus, arrondies à l'unité.}
\observation{Dans cet exercice à 3 étapes, un triangle rectangle et sa représentation graphique sont donnés ainsi que les 
longueurs de deux de ses côtés. 
Il est demandé d'identifier les rapports trigonométriques calculables étant données ces longueurs données, construire les 
égalités puis en déduire les mesures en degrés, arrondies à l'unité, des deux angles aigus.}
#endif

#if defined TARGET_11LigneTrigoUniteEtape
\description{Vous devez identifier la ligne trigonométrique égale à un quotient donné puis en déduire une mesure 
d'angle en degrés arrondie à l'unité.}
\observation{Dans cet exercice à 2 étapes, un triangle rectangle et sa représentation graphique sont donnés ainsi que les 
longueurs de deux de ses côtés.
Il est demandé de choisir à quelle ligne trigonométrique correspond le quotient donné de ces deux longueurs. 
La deuxième étape demande de donner la mesure en degrés, arrondie à l’unité, de l’angle considéré.}
#endif

#if defined TARGET_12LigneTrigoUnite
\description{Vous devez calculer la mesure en degrés arrondie à l'unité de l’angle considéré d’un triangle rectangle dont on connait les longueurs de deux côtés.}
\observation{Dans cette ressource, un triangle rectangle et sa représentation graphique sont donnés ainsi que les 
longueurs de deux de ses côtés. 
Il est demandé de donner la mesure en degrés de l’angle considéré arrondie à l’unité.}
#endif
