%%%%% ENONCES %%%%%%%

\text{hypot=l'hypoténuse}
\text{caa=le côté adjacent à l'angle}
\text{coa=le côté opposé à l'angle}
\text{et=et}

\text{enonce1=\A\B\C est un triangle rectangle en \Sommet.}
\text{consigne1=Cocher la ou les propositions qui conviennent dans chacun des TROIS cadres.}

\text{quest=Le côté,est : }

\text{phrase=Vous avez répondu&nbsp;:}

\text{enonce2=\A\B\C est un triangle rectangle en \Sommet.}
\text{consigne2=Identifier les côtés du triangle.}

\text{SolDetails=
Considérons un triangle \A\B\C rectangle en \Sommet.
<ul class="euler_ul">
 <li>Considérons son angle droit <span class="nowrap oef_indbad">\(\widehat{\Hyp[1]\Sommet\Hyp[2]}\).</span>
  <p>Par définition, l'<strong>hypoténuse</strong> du triangle rectangle \A\B\C est le côté opposé à son angle droit&nbsp;;
  c'est le côté <span class="nowrap oef_indbad">[\Hyp[1]\Hyp[2]].</span>
  </p>
 </li>
 <li>Considérons l'angle aigu <span class="quest">\(\widehat{\NomAngle1}\)</span>.
  <ul class="euler_ul">
   <li>Cet angle a deux côtés&nbsp;:
       <ul class="euler_ul">
        <li>l'un est l'<strong>hypoténuse</strong>&nbsp;: 
            <span class="nowrap oef_indbad">[\Hyp[1]\Hyp[2]]</span>&nbsp;;
        </li>
        <li>l'autre est le <strong>côté adjacent</strong> à l'angle aigu 
            <span class="nowrap">\(\widehat{\NomAngle1}\)&nbsp;:</span> 
            <strong>[\Cat1]</strong>.
        </li>
       </ul>
   <li>Le troisième côté du triangle est le <strong>côté opposé</strong> à l'angle aigu 
       <span class="nowrap">\(\widehat{\NomAngle1}\)&nbsp;:</span>
       <strong>[\Cat2]</strong>.
   </li>
  </ul>
 </li>
 <li>Considérons l'angle aigu <span style="color:brown;font-weight:bold">\(\widehat{\NomAngle2}\)</span>.
  <ul class="euler_ul">
   <li>Cet angle a deux côtés&nbsp;:
     <ul class="euler_ul">
       <li>l'un est l'<strong>hypoténuse</strong>&nbsp;: <span class="oef_indbad">[\Hyp[1]\Hyp[2]]</span>&nbsp;;</li>
       <li>l'autre est le <strong> côté adjacent</strong> à l'angle aigu 
       <span class="nowrap">\(\widehat{\NomAngle2}\)&nbsp;:</span> <strong>[\Cat2]</strong>.</li>
     </ul>
   </li>
   <li> Le troisième côté du triangle est le <strong>côté opposé</strong> 
        à l'angle aigu <span class="nowrap">\(\widehat{\NomAngle2}\)&nbsp;:</span>  
        <strong>[\Cat1]</strong>. 
   </li>
  </ul>
 </li>
</ul>
}
\text{nombre=une,deux,trois,quatre}
\text{feed1=Concernant le côté }
\text{feed2=vous avez coché,la réponse exacte&nbsp;:,une réponse exacte&nbsp;:,les deux réponses exactes&nbsp;:}
\text{feed3=vous avez coché,réponse fausse&nbsp;:,réponses fausses&nbsp;:}
\text{feed4=la réponse exacte non cochée est&nbsp;:,l'autre réponse exacte non cochée est&nbsp;:,les deux réponses exactes non cochées sont&nbsp;:}
