#if defined TARGET_volume1 || defined TARGET_volume2 || defined TARGET_volume3 || defined TARGET_volume4 || defined TARGET_volume5
# define TITRE Volume d'un solide
#endif
#if defined TARGET_perpendiculaire1 || defined TARGET_perpendiculaire2 || defined TARGET_perpendiculaire3 || defined TARGET_perpendiculaire4 || defined TARGET_perpendiculaire5
# define TITRE Relation d'orthogonalité
#endif
#if defined TARGET_airelaterale1 || defined TARGET_airelaterale2 || defined TARGET_airelaterale3 || defined TARGET_airelaterale4 || defined TARGET_airelaterale5
# define TITRE Aire latérale de solide
#endif
#if defined TARGET_formuleaire1 || defined TARGET_formuleaire2 || defined TARGET_formuleaire3 || defined TARGET_formuleaire4 || defined TARGET_formuleaire5
# define TITRE Formule d'aire
#endif
#if defined TARGET_formulevolume1 || defined TARGET_formulevolume2 || defined TARGET_formulevolume3 || defined TARGET_formulevolume4 || defined TARGET_formulevolume5
# define TITRE Formule de volume
#endif
#if defined TARGET_longueur1 || defined TARGET_longueur2 || defined TARGET_longueur3 || defined TARGET_longueur4 || defined TARGET_longueur5
# define TITRE Calcul de longueur
#endif
#if defined TARGET_parallel1 || defined TARGET_parallel2 || defined TARGET_parallel3 || defined TARGET_parallel4 || defined TARGET_parallel5
# define TITRE Relation de parallélisme
#endif
#if defined TARGET_patron1 || defined TARGET_patron2 || defined TARGET_patron3 || defined TARGET_patron4 || defined TARGET_patron5
# define TITRE Patron de solide
#endif
