!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set confparm1=ambiance
<tr><td><strong>Sélectionner un thème pour l'éditeur Python :</strong></td>
</tr>
<tr><td>
!formradio confparm1 list ambiance,neat,zenburn prompt thème sombre,thème clair aéré,thème sombre aéré
</td>
</tr>
