<table>    
    <th>
    <h1>BIJLES</h1>
    </th>
    <tr>
    <th>
	<div align="left">
            De algemene formule voor een vierkantsvergelijking is:
            <img src=$module_dir/gifs/vierkantsvergelijking.gif/>
            <br />
	    De abc-formule voor de nulpunten is:
            <img src=$module_dir/gifs/abc-formule.gif/>
            <br />
	    De formule van de discriminant:
            <img src=$module_dir/gifs/discriminant.gif/>
	    <br />
	    De volgende situaties  kunnen we dus onderscheiden:<br />
	    <table cellpadding="15" style="border-width:1px;border-style:outset">
		<th>
		    <div align="left">
			<ul>
			    <li>de Discriminant is groter dan nul: er zijn dus twee nulpunten.</li>
			    <li><em>a</em> is groter dan nul: dus een <em>dal-parabool</em></li>
			</ul>
		    </div>
		    <img src=$module_dir/gifs/dal2.gif/>
		</th>
		<th>
		    <div align="left">
			<ul>
			    <li>de Discriminant is groter dan nul: er zijn dus twee nulpunten.</li>
			    <li><em>a</em> is kleiner dan nul: dus een <em>berg-parabool</em></li>
			</ul>
		    </div>
		    <img src=$module_dir/gifs/berg2.gif/>
		</th>
		<tr>		    
		<th>
		    <div align="left">
			<ul>
			    <li>de Discriminant is gelijk aan nul: er is slechts &eacute;&eacute;n nulpunt.</li>
	    		    <li><em>a</em> is groter dan nul: dus een <em>dal-parabool</em></li>
			</ul>
		    </div>
		    <img src=$module_dir/gifs/dal1.gif/>
		</th>
		<th>
		    <div align="left">
			<ul>
			    <li>de Discriminant is gelijk aan nul: er is slechts &eacute;&eacute;n nulpunt.</li>
			    <li><em>a</em> is kleiner dan nul: dus een <em>berg-parabool</em></li>
			</ul>
		    </div>
		    <img src=$module_dir/gifs/berg1.gif/>
		</th>
		<tr>		    
		<th>
		    <div align="left">
			<ul>
		    	    <li>de Discriminant is kleiner dan nul: dus er zijn g&eacute;&eacute;n nulpunten.</li>
			    <li><em>a</em> is groter dan nul: dus een <em>dal-parabool</em></li>
			</ul>
		    </div>
		    <img src=$module_dir/gifs/dal0.gif/>
		</th>
		<th>
		    <div align="left">
			<ul>
			    <li>de Discriminant is kleiner dan nul: dus er zijn g&eacute;&eacute;n nulpunten.</li>
			    <li><em>a</em> is kleiner dan nul: dus een <em>berg-parabool</em></li>
			</ul>	
		    </div>
		    <img src=$module_dir/gifs/berg0.gif/>
		    
		</th>
	    </table>	    		    
	</th>
    <tr>
    <th>
    <h2>HET BEWIJS</h2>
    
De algemene formule voor een kwadratische vergelijking (ook wel tweede
graadsvergelijking, of tweedegraads polynoom genoemd) is:

<!-- math
 \begin{displaymath}
y=ax^{2}+bx+c
\end{displaymath}
 -->
</p>
<div align="center">
<img
 width="108" height="37" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img1.gif"
 alt="$\displaystyle y=ax^{2}+bx+c$">
</div></p>


Voor een snijpunt (nulpunt,wortel) met de <img
 width="42" height="30" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img2.gif"
 alt="$ x-as$"> geldt dat: <img
 width="38" height="30" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img3.gif"
 alt="$ y=0$">


<!-- math
 \begin{displaymath}
ax^{2}+bx+c=0
\end{displaymath}
 -->
</p>
<div align="center">
<img
 width="109" height="37" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img4.gif"
 alt="$\displaystyle ax^{2}+bx+c=0$">
</div></p>


Bewijs dat voor de wortels met de <img
 width="42" height="30" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img2.gif"
 alt="$ x-as$"> geldt:


<!-- math
 \begin{displaymath}
ax^{2}+bx+c=0\rightarrow \left\{ \begin{array}{c}
 x_{1}=\frac{-b+\sqrt{b^{2}-4ac}}{2a}\\
 \\
 x_{1}=\frac{-b-\sqrt{b^{2}-4ac}}{2a}\end{array}
\right.
\end{displaymath}
 -->
</p>
<div align="center">
<img
 width="276" height="90" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img5.gif"
 alt="$\displaystyle ax^{2}+bx+c=0\rightarrow \left\{ \begin{array}{c}
x_{1}=\frac{-b+...
...t{b^{2}-4ac}}{2a}\\
\\
x_{1}=\frac{-b-\sqrt{b^{2}-4ac}}{2a}\end{array}\right.$">
</div></p>


Het Bewijs:


<!-- math
 $0=ax^{2}+bx+c$
 -->
<img
 width="109" height="36" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img6.gif"
 alt="$ 0=ax^{2}+bx+c$"> <!-- math
 $\Leftrightarrow$
 -->
<img
 width="20" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img7.gif"
 alt="$ \Leftrightarrow $"> 


<!-- math
 $0=ax^{2}+\frac{a\cdot b}{a}x+c$
 -->
<img
 width="120" height="37" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img8.gif"
 alt="$ 0=ax^{2}+\frac{a\cdot b}{a}x+c$"> <!-- math
 $\xrightarrow{a\, \, \, buitenhaakjes\, \, \, halen}$
 -->
<img
 width="122" height="25" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img9.gif"
 alt="$ \xrightarrow{a\, \, \, buitenhaakjes\, \, \, halen}$">


<!-- math
 $0=a\cdot \left(x^{2}+\frac{b}{a}x\right)+c$
 -->
<img
 width="134" height="37" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img10.gif"
 alt="$ 0=a\cdot \left(x^{2}+\frac{b}{a}x\right)+c$"><!-- math
 $\xrightarrow{zie\, toelichting}$
 -->
<img
 width="79" height="25" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img11.gif"
 alt="$ \xrightarrow{zie\, toelichting}$">


<!-- math
 $0=a\cdot \left(x+\frac{1}{2}\cdot \frac{b}{a}\right)\cdot \left(x+\frac{1}{2}\cdot \frac{b}{a}\right)-\frac{1}{4}\frac{b^{2}}{a}+c$
 -->
<img
 width="256" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img12.gif"
 alt="$ 0=a\cdot \left(x+\frac{1}{2}\cdot \frac{b}{a}\right)\cdot \left(x+\frac{1}{2}\cdot \frac{b}{a}\right)-\frac{1}{4}\frac{b^{2}}{a}+c$">
<!-- math
 $\Leftrightarrow$
 -->
<img
 width="20" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img7.gif"
 alt="$ \Leftrightarrow $">


<!-- math
 $0=a\cdot \left(x+\frac{1}{2}\frac{b}{a}\right)^{2}-\frac{1}{4}\frac{b^{2}}{a}+c$
 -->
<img
 width="178" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img13.gif"
 alt="$ 0=a\cdot \left(x+\frac{1}{2}\frac{b}{a}\right)^{2}-\frac{1}{4}\frac{b^{2}}{a}+c$"><!-- math
 $\xrightarrow{de\, \, \, term\, \, \, -\frac{1}{4}\frac{b^{2}}{a}+c\, \, \, naar\, \, \, de\, \, \, andere\, \, \, kant}$
 -->
<img
 width="205" height="33" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img14.gif"
 alt="$ \xrightarrow{de\, \, \, term\, \, \, -\frac{1}{4}\frac{b^{2}}{a}+c\, \, \, naar\, \, \, de\, \, \, andere\, \, \, kant}$">


<!-- math
 $a\cdot \left(x+\frac{b}{2a}\right)^{2}\, \, \, \, \, =\, \, \, \, \, \frac{1}{4}\frac{b^{2}}{a}-c$
 -->
<img
 width="168" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img15.gif"
 alt="$ a\cdot \left(x+\frac{b}{2a}\right)^{2}\, \, \, \, \, =\, \, \, \, \, \frac{1}{4}\frac{b^{2}}{a}-c$">
<!-- math
 $\xrightarrow{links\, \, \, en\, \, \, rechts\, \, \, delen\, \, \, door\, \, a}$
 -->
<img
 width="150" height="24" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img16.gif"
 alt="$ \xrightarrow{links\, \, \, en\, \, \, rechts\, \, \, delen\, \, \, door\, \, a}$"> 


<!-- math
 $\left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{\frac{1}{4}\frac{b^{2}}{a}-c}{a}$
 -->
<img
 width="136" height="55" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img17.gif"
 alt="$ \left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{\frac{1}{4}\frac{b^{2}}{a}-c}{a}$">
<!-- math
 $\, \, \, \, \, \, \, \Leftrightarrow$
 -->
<img
 width="32" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img18.gif"
 alt="$ \, \, \, \, \, \, \, \Leftrightarrow $"><!-- math
 $\, \, \, \, \, \, \, \, \, \left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{1}{4}\cdot \frac{b^{2}}{a^{2}}-\frac{c}{a}\, \, \,$
 -->
<img
 width="176" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img19.gif"
 alt="$ \, \, \, \, \, \, \, \, \, \left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{1}{4}\cdot \frac{b^{2}}{a^{2}}-\frac{c}{a}\, \, \, $"><!-- math
 $\xrightarrow{de\, \, \, term\, \, \, \frac{c}{a}\, \, \, \, teller\, \, en\, \, \, noemer\, \, \, vermenigvuldigen\, \, \, met\, \: 4\cdot a}$
 -->
<img
 width="278" height="27" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img20.gif"
 alt="$ \xrightarrow{de\, \, \, term\, \, \, \frac{c}{a}\, \, \, \, teller\, \, en\, \, \, noemer\, \, \, vermenigvuldigen\, \, \, met\, \: 4\cdot a}$"> 


<!-- math
 $\left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{b^{2}}{4a^{2}}-\frac{4ac}{4a^{2}}\, \, \,$
 -->
<img
 width="159" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img21.gif"
 alt="$ \left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{b^{2}}{4a^{2}}-\frac{4ac}{4a^{2}}\, \, \, $">
<!-- math
 $\, \, \, \Leftrightarrow \, \, \, \,$
 -->
<img
 width="32" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img22.gif"
 alt="$ \, \, \, \Leftrightarrow \, \, \, \, $"><!-- math
 $\left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{b^{2}-4ac}{4a^{2}}$
 -->
<img
 width="136" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img23.gif"
 alt="$ \left(x+\frac{b}{2a}\right)^{2}\, \, \, =\, \, \, \frac{b^{2}-4ac}{4a^{2}}$">


<!-- math
 $\xrightarrow{nu\, \, \, worteltrekken...}$
 -->
<img
 width="105" height="24" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img24.gif"
 alt="$ \xrightarrow{nu\, \, \, worteltrekken...}$"> 


<!-- math
 $x+\frac{b}{2a}\, \, \, =\, \, \, +\, \, \sqrt{\frac{b^{2}-4ac}{4a^{2}}}$
 -->
<img
 width="147" height="49" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img25.gif"
 alt="$ x+\frac{b}{2a}\, \, \, =\, \, \, +\, \, \sqrt{\frac{b^{2}-4ac}{4a^{2}}}$">
<!-- math
 $\, \, \, \vee \, \,$
 -->
<img
 width="23" height="14" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img26.gif"
 alt="$ \, \, \, \vee \, \, $"> <!-- math
 $x+\frac{b}{2a}\, \, =\, \, -\, \, \, \sqrt{\frac{b^{2}-4ac}{4a^{2}}}$
 -->
<img
 width="145" height="49" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img27.gif"
 alt="$ x+\frac{b}{2a}\, \, =\, \, -\, \, \, \sqrt{\frac{b^{2}-4ac}{4a^{2}}}$"> 


<!-- math
 $\Leftrightarrow$
 -->
<img
 width="20" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img7.gif"
 alt="$ \Leftrightarrow $"><!-- math
 $x+\frac{b}{2a}\, \, \, =\, \, \, \pm \, \, \, \frac{\sqrt{b^{2}-4ac}}{\sqrt{4a^{2}}}$
 -->
<img
 width="146" height="51" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img28.gif"
 alt="$ x+\frac{b}{2a}\, \, \, =\, \, \, \pm \, \, \, \frac{\sqrt{b^{2}-4ac}}{\sqrt{4a^{2}}}$">
<!-- math
 $\, \, \, \Leftrightarrow \, \, \,$
 -->
<img
 width="31" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img29.gif"
 alt="$ \, \, \, \Leftrightarrow \, \, \, $"> <!-- math
 $x+\frac{b}{2a}\, \, =\, \, \pm \, \, \frac{\sqrt{b^{2}-4ac}}{2a}$
 -->
<img
 width="141" height="51" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img30.gif"
 alt="$ x+\frac{b}{2a}\, \, =\, \, \pm \, \, \frac{\sqrt{b^{2}-4ac}}{2a}$"> 


<!-- math
 $\Leftrightarrow$
 -->
<img
 width="20" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img7.gif"
 alt="$ \Leftrightarrow $"> <!-- math
 $x_{1,2}=-\frac{b}{2a}\pm \frac{\sqrt{b^{2}-4ac}}{2a}$
 -->
<img
 width="146" height="51" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img31.gif"
 alt="$ x_{1,2}=-\frac{b}{2a}\pm \frac{\sqrt{b^{2}-4ac}}{2a}$">
<!-- math
 $\xrightarrow{Dus..........}\, \, \, \, \, \, \, \, \, \, x_{1,2}=\frac{-b\pm \sqrt{b^{2}-4ac}}{2a}$
 -->
<img
 width="207" height="51" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img32.gif"
 alt="$ \xrightarrow{Dus..........}\, \, \, \, \, \, \, \, \, \, x_{1,2}=\frac{-b\pm \sqrt{b^{2}-4ac}}{2a}$">
<BR>
<BR>
<BR>
<BR>
toelichting:


<!-- math
 $\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)=x^{2}+\frac{b}{2a}x+\frac{b}{2a}x+\left(\frac{b}{2a}\right)^{2}$
 -->
<img
 width="287" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img33.gif"
 alt="$ \left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)=x^{2}+\frac{b}{2a}x+\frac{b}{2a}x+\left(\frac{b}{2a}\right)^{2}$">


<!-- math
 $\Leftrightarrow$
 -->
<img
 width="20" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img7.gif"
 alt="$ \Leftrightarrow $"> <!-- math
 $x^{2}+\frac{2b}{2a}x+\left(\frac{b}{2a}\right)^{2}$
 -->
<img
 width="111" height="44" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img34.gif"
 alt="$ x^{2}+\frac{2b}{2a}x+\left(\frac{b}{2a}\right)^{2}$">
<!-- math
 $\Leftrightarrow$
 -->
<img
 width="20" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img7.gif"
 alt="$ \Leftrightarrow $"> <!-- math
 $x^{2}+\frac{b}{a}x+\frac{b^{2}}{4a^{2}}$
 -->
<img
 width="89" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img35.gif"
 alt="$ x^{2}+\frac{b}{a}x+\frac{b^{2}}{4a^{2}}$"><img
 width="4" height="16" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img36.gif"
 alt="$ $">

<BR>
En dus geldt:


<!-- math
 $a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)\, \, \, \, \, \, \Leftrightarrow \, \, \, \, \, \, a\left(x^{2}+\frac{b}{a}x+\frac{b^{2}}{4a^{2}}\right)$
 -->
<img
 width="289" height="45" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img37.gif"
 alt="$ a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)\, \, \, \, \, \,...
...htarrow \, \, \, \, \, \, a\left(x^{2}+\frac{b}{a}x+\frac{b^{2}}{4a^{2}}\right)$"><!-- math
 $\, \, \, \, \, \Leftrightarrow \, \, \, \, \,$
 -->
<img
 width="38" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img38.gif"
 alt="$ \, \, \, \, \, \Leftrightarrow \, \, \, \, \, $"><!-- math
 $\, a\left(x^{2}+\frac{b}{a}x\right)+a\cdot \frac{b^{2}}{4a^{2}}$
 -->
<img
 width="132" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img39.gif"
 alt="$ \, a\left(x^{2}+\frac{b}{a}x\right)+a\cdot \frac{b^{2}}{4a^{2}}$"><!-- math
 $\, \, \, \, \, \, \, \Leftrightarrow \, \, \, \, \, \, \, \, \,$
 -->
<img
 width="48" height="15" align="BOTTOM" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img40.gif"
 alt="$ \, \, \, \, \, \, \, \Leftrightarrow \, \, \, \, \, \, \, \, \, $"><!-- math
 $a\left(x^{2}+\frac{b}{a}x\right)+\frac{b^{2}}{4a}$
 -->
<img
 width="108" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img41.gif"
 alt="$ a\left(x^{2}+\frac{b}{a}x\right)+\frac{b^{2}}{4a}$">


Dus er geldt <!-- math
 $a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)=a\left(x^{2}+\frac{b}{a}x\right)+\frac{b^{2}}{4a}$
 -->
<img
 width="254" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img42.gif"
 alt="$ a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)=a\left(x^{2}+\frac{b}{a}x\right)+\frac{b^{2}}{4a}$"> 


de term <!-- math
 $a\left(x^{2}+\frac{b}{a}x\right)$
 -->
<img
 width="76" height="37" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img43.gif"
 alt="$ a\left(x^{2}+\frac{b}{a}x\right)$"> mogen we gelijk stellen
aan <!-- math
 $a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)-\frac{b^{2}}{4a}$
 -->
<img
 width="163" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img44.gif"
 alt="$ a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)-\frac{b^{2}}{4a}$"> 


<!-- math
 $a\left(x^{2}+\frac{b}{a}x\right)=a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)-\frac{b^{2}}{4a}$
 -->
<img
 width="254" height="42" align="middle" style="border-width:0px;border-style:outset"
 src="$module_dir/gifs/img45.gif"
 alt="$ a\left(x^{2}+\frac{b}{a}x\right)=a\left(x+\frac{b}{2a}\right)\cdot \left(x+\frac{b}{2a}\right)-\frac{b^{2}}{4a}$">
</th>
</table>

