!header

<em>$module_title</em> 是一种直观的游戏/练习。
它给你两个图形, 一个是另一个经平面旋转后的像。
要求你在画面上通过点击找到旋转中心。
<p>
!form new
<input type=hidden name=module value=$module>
你可以挑选难度水平:
!set level=1
!formradio level list 1,2,3
<br>每轮包含的射击数:
!set shoots=3
!formselect shoots from 1 to 8
(得分在每轮的末尾给出).
<center>
<input type=submit value="开始">
</center>
</form>
<p>
!href module=home&list=9001&search_keywords=shoot 其它打靶练习/游戏
.
!tail

