!header

!if $error=robot
 !read msg.phtml
 !goto end
!endif

!! La pr閟entation de l'exercice.
!read present.phtml

<p><hr> <p>

!if $status=waiting
 !if $error!=$empty
  !read msg.phtml
  <p>请订正错误.
  <p><hr width=50%> <p>
 !else
  !if $cmd=reply
   !read answer.phtml
   <p><hr width=50%> <p>
  !endif
 !endif
 !! La forme de r閜onse
 !read form.phtml
 <p>
 !href cmd=renew&worksheet=$worksheet&$module_init_parm 改换分数
.
!else
 !if $error!=$empty
  !read msg.phtml
  <p>请订正错误.
  <p><hr width=50%> <p>
 !endif
 !! L'analyse de r閜onse
 !read answer.phtml
 <p>
 !href cmd=renew&worksheet=$worksheet&$module_init_parm 另一个分数
.
!endif

:end
!tail

