\text{operlist=Som,Product}
\text{optionlist=sum,som of product,som of product,product}
#ifdef TYPED
\text{tstatement0=Vul de onderstaande tabel in met}
#else
\text{tstatement1=Vul de onderstaande tabel in door de}
\text{tstatement2=te slepen met je muis}
#endif
\text{tstatement3=zo dat elke lijn en elke kolom de aangegeven}
\text{tstatement31=geeft}
\text{tstatement4=for computations mod}
\text{trow=row}
\text{tcolumn=column}
\text{ofrow=of row}
\text{ofcol=of column}
\text{tequals=equals}
\text{name_case=Box}
