\text{operlist=Sum,Product}
\text{optionlist=sum,sum or product,sum or product,product}
#ifdef TYPED
\text{tstatement0=Fill-in the table below with}
#else
\text{tstatement1=Fill-in the table by dragging the}
\text{tstatement2=below into it}
#endif
\text{tstatement3=so that each line and each column gives the indicated}
\text{tstatement31=}
\text{tstatement4=for computations mod}
\text{trow=row}
\text{tcolumn=column}
\text{ofrow=of row}
\text{ofcol=of column}
\text{tequals=equals}
