\text{name_case=Case}
\text{operlist=Somme,Produit}
\text{optionlist=de sorte que les sommes des lignes et les sommes des colonnes,
	de sorte que les sommes des lignes et les produits des colonnes,
	de sorte que les produits des lignes et les sommes des colonnes,
	de sorte que les produits des lignes et les produits des colonnes}
\text{optionlist=les sommes,la somme ou le produit,la somme ou le produit,les produits}

#ifdef TYPED
\text{tstatement0=Remplissez le tableau ci-dessous par des}
#else
\text{tstatement1=Remplissez le tableau en tirant les}
\text{tstatement2=du bas dans les cases}
#endif
\text{tstatement3=de manière que chaque ligne et chaque colonne donnent }
\text{tstatement31=comme indiqué}
\text{tstatement4=en faisant les calculs modulo}
\text{trow=ligne}
\text{tcolumn=colonne}
\text{ofrow=de la ligne}
\text{ofcol=de la colonne}
\text{tequals=vaut}
