\text{operlist=somma,prodotto}
\text{optionlist=la somma indicata,la somma o il prodotto indicati,la somma o il prodotto indicati,il prodotto indicato}
#ifdef TYPED
\text{tstatement0=Completa la tabella con}
#else
\text{tstatement1=Trascina nella tabella}
\text{tstatement2=sotto}
#endif
\text{tstatement3=in modo che ogni colonna e ogni riga dia come risultato}
\text{tstatement31=}
\text{tstatement4=eseguendo i calcoli modulo}
\text{trow=riga}
\text{tcolumn=colonna}
\text{ofrow=della riga}
\text{ofcol=della colonna}
\text{tequals=uguale a}
