
\answer{\name_case 1}{\(\sh[1])}{type=dragfill}
\answer{\name_case 2}{\(\sh[2])}{type=dragfill}
\answer{\name_case 3}{\(\sh[3])}{type=dragfill}
\answer{\name_case 4}{\(\sh[4])}{type=dragfill}
\answer{\name_case 5}{\(\sh[5])}{type=dragfill}
\answer{\name_case 6}{\(\sh[6])}{type=dragfill}
\answer{\name_case 7}{\(\sh[7])}{type=dragfill}
\answer{\name_case 8}{\(\sh[8])}{type=dragfill}
\answer{\name_case 9}{\(\sh[9])}{type=dragfill}
\answer{\name_case 10}{\(\sh[10])}{type=dragfill}
\answer{\name_case 11}{\(\sh[11])}{type=dragfill}
\answer{\name_case 12}{\(\sh[12])}{type=dragfill}
\answer{\name_case 13}{\(\sh[13])}{type=dragfill}
\answer{\name_case 14}{\(\sh[14])}{type=dragfill}
\answer{\name_case 15}{\(\sh[15])}{type=dragfill}
\answer{\name_case 16}{\(\sh[16])}{type=dragfill}
