#if defined TARGET_calctersuite5AS || defined TARGET_calctersuite6AS
# define TITRE Calculer des termes d'une suite avec somme
#endif
#if defined TARGET_calctersuite5SS || defined TARGET_calctersuite6SS
# define TITRE Calculer des termes d'une suite sans somme
#endif
#if defined TARGET_calctersuite7 || defined TARGET_calctersuite8
#define TITRE Déterminer la suite
#endif
#if defined TARGET_calctersuite1 || defined TARGET_calctersuite2 || defined TARGET_calctersuite3 || defined TARGET_calctersuite4
# define TITRE Calculer des termes d'une suite
#endif
#if defined TARGET_suitebacST2Sn1
# define TITRE Suite type bac ST2S
#endif
#if defined TARGET_suitebacESn1
# define TITRE Suite type bac ES
#endif
#if defined TARGET_suitesQCM1
# define TITRE QCM sur les suites
#endif
