#if defined TARGET_calctersuite5SS || defined TARGET_calctersuite5AS
\text{data=Chaque semaine la distance parcourue est égale à la distance parcourue
la semaine précédente ?? multipliée par \r,à laquelle on ajoute \a m, multipliée par \a ??.
<br>La suite \(( u_{n})\) est donc ??géométrique,arithmétique, ni l'un ni l'autre ??. }
#endif
#if defined TARGET_calctersuite6AS || defined TARGET_calctersuite6SS
\text{data=Chaque semaine la distance parcourue est égale à la distance parcourue
la semaine précédente ?? à laquelle on ajoute \r m, multipliée par \r,multipliée par \mr ??.
<br>La suite \(( u_{n})\) est donc ??arithmétique,géométrique, ni l'un ni l'autre ??. }
#endif
