#if defined TARGET_oefconvvol1 || defined TARGET_oefconvvol2 || defined TARGET_oefconvvol3 || defined TARGET_oefconvvol4 || defined TARGET_oefconvvol5 || defined TARGET_oefconvcont1 || defined TARGET_oefconvcont2 || defined TARGET_oefconvcont3 || defined TARGET_oefconvcont4 || defined TARGET_oefconvcont5 || defined TARGET_oefconvconvol1 || defined TARGET_oefconvconvol2 || defined TARGET_oefconvconvol3 || defined TARGET_oefconvconvol4 || defined TARGET_oefconvconvol5
\text{name_enonce=Convertir&nbsp;}
#endif
#if defined TARGET_oefrecpersp3
\text{name_enonce=Cliquer sur le dessin en perspective d'un parallélépipède rectangle&nbsp;}
#endif
#if defined TARGET_oefrecpersp5
\text{list=Oui,Non,Je ne sais pas}
\text{name_enonce1=Nous avons le dessin en perspective
  d'un parallélépipède rectangle&nbsp;}
\text{name_enonce2=Les arêtes invisibles sont représentées avec des traits interrompus.
  Le dessin est correct&nbsp;}
#endif
#if defined TARGET_oefrecpersp4
\text{rv=C'est un parallélépipède rectangle,Ce n'est pas un parallélépipède rectangle}
\text{name_enonce=Mettez en relation&nbsp;}
#endif
#if defined TARGET_oefformpave5
\text{name_enonce=Donner la formule pour calculer le volume d'un parallélépipède rectangle&nbsp;}
\text{name_long=longueur,largeur,hauteur,diamètre, rayon}
#endif
#if defined TARGET_oefformpave2
\text{voli=Volume du parallélépipède rectangle}
\text{name_enonce=Mettez en relation&nbsp;}
\text{vol=Périmètre du rectangle,
  Périmètre du carré,
  Aire du carré,
  Aire du triangle,
  Aire du rectangle,
  Volume du cube}
#endif
#if defined TARGET_oefcontvol1
\text{name_enonce=Choisir la bonne unité&nbsp;}
#endif
#if defined TARGET_oefcontvol2
\text{name_enonce=Compléter&nbsp;}
#endif
#if defined TARGET_oefcontvol3 || defined TARGET_oefcontvol4
\text{name_enonce=Choisir la bonne valeur&nbsp;}
#endif
#if defined TARGET_oefcontvol5
\text{name_enonce=Mettre en relation&nbsp;}
#endif
#if defined TARGET_oefrecpersp1 || defined TARGET_oefrecpersp2
\text{name_question=Donner le nombre de faces,
  Donner le nombre d'arêtes,
  Donner le nombre de sommets,
  Les arêtes cachées sont représentées
}
\text{name_ouinon=oui,non}
#endif
#if defined TARGET_oefrecpersp1
\text{enonc=Nous avons un parallélépipède rectangle}
#endif
#if defined TARGET_oefrecpersp2
\text{enonc=Nous avons un cube}
#endif
#if defined TARGET_oefrecpatron5
\text{name_enonce=Placer les images pour obtenir le patron d'un parallélépipède rectangle}
#endif
#if defined TARGET_oefrecpatron4
\text{name_enonce=Placer les images pour reproduire le patron du parallélépipède rectangle}
#endif
#if defined TARGET_oefrecpatron3
\text{name_enonce=Placer les images pour obtenir le patron d'un parallélépipède rectangle}
#endif
#if defined TARGET_oefrecpatron2
\text{name_enonce=Le dessin du patron du parallélépipède rectangle est correct}
\text{name_choix=oui,non,je ne sais pas}
#endif
#if defined TARGET_oefrecpatron1
\text{name_enonce=Le dessin ci-contre est un patron de cube}
\text{name_choix=vrai,faux,peut-être,je ne sais pas}
#endif
#if defined TARGET_oefformpave1
\text{voli=Volume du parallélépipède rectangle}
\text{formi=longueur \(\times\) largeur \(\times\) hauteur}
\text{vol=Périmètre du rectangle,
  Périmètre du carré,
  Aire du carré,
  Aire du triangle,
  Aire du rectangle,
  Volume du cube}
\text{name_enonce=Mettez en relation&nbsp;}
\text{name_voc=longueur,largeur,hauteur,côté}
#endif
#if defined TARGET_oefconstpat3
\text{name_long=longueur,largeur,diamètre, rayon, hauteur}
#endif
#if defined TARGET_oefformpave3 || defined TARGET_oefformpave4
\text{name_enonce=Nous avons un parallélépipède rectangle
  qui a pour longueur XXXX \(\textrm{cm}\), pour largeur YYYY \(\textrm{cm}\)
  et pour hauteur ZZZZ \(\textrm{cm}\).}
\text{name_voc=formule,longueur,largeur,hauteur}
\text{name_enonce2=Donner le volume du parallélépipède rectangle&nbsp;}
#endif
#if defined TARGET_oefpaveparaperp1 || defined TARGET_oefpaveparaperp2 || defined TARGET_oefpaveparaperp3 || defined TARGET_oefpaveparaperp4
\text{name_give=Donner}
#endif
#if defined TARGET_oefpatron1
\matrix{name_enonce=Pour dessiner le patron d'un parallélépipède rectangle
  nous devons tracer sur une feuille les, faces
  Les faces sont des
  Ensuite nous découpons la feuille
  et par pliage nous obtenons le parallélépipède rectangle.}
\text{name_reps=triangles,rectangles,losanges,parallélogramme,hexagone}
#endif
#if defined TARGET_oefpatron2
\text{name_enonce=Sur le patron du cube, marier les côtés pour le pliage en
  utilisant la même lettre&nbsp;}
#endif
#if defined TARGET_oefpatron3
\text{name_question=Ce dessin est ,d'un parallélépipède rectangle.}
\text{name_choix=une représentation en perspective,un patron,un rectangle,je ne sais pas}
#endif
#if defined TARGET_oefpatron4
\text{name_enonce=Nous avons un patron de parallélépipède rectangle avec
  les dimensions suivantes&nbsp;,
  La face jaune servira de base pour poser le parallélépipède rectangle.}
\text{name_question=Quelles sont les dimensions du parallélépipède rectangle&nbsp;}
#endif
#if defined TARGET_oefpatron5
\text{name_enonce=Nous avons le patron de parallélépipède rectangle suivant&nbsp;}
\text{name_question=Choisissez le parallélépipède rectangle correspondant au patron en cliquant dessus}
#endif
#if defined TARGET_oefvolume1
\text{name_enonce1=Nous avons un cube de, cm de côté.}
\text{name_enonce2=Le volume du cube est de&nbsp;}
#endif
#if defined TARGET_oefvolume2 || defined TARGET_oefvolume3 || defined TARGET_oefvolume4 || defined TARGET_oefvolume5
\text{name_enonce2=Le volume du parallélépipède rectangle est de&nbsp;}
#endif
#if defined TARGET_oefvolume2
\text{name_enonce1=Nous avons un parallélépipède rectangle fabriqué à l'aide de cubes identiques.
  Chaque cube mesure 1 cm de côté.}
#endif
#if defined TARGET_oefvolume3
\text{name_enonce1=Nous avons un parallélépipède rectangle fabriqué à l'aide de cubes identiques.
  Chaque cube mesure ,de côté.}
#endif
#if defined TARGET_oefvolume4 || defined TARGET_oefvolume5
\text{name_enonce1=Nous avons un parallélépipède rectangle.
  Sa longueur mesure, sa largeur , et sa hauteur }
#endif
#if defined TARGET_oefsolide1
\text{name_enonce=Le solide suivant est un parallélépipède rectangle&nbsp;}
#endif
#if defined TARGET_oefsolide2
\text{name_enonce=Le solide suivant a pour nombre de faces&nbsp;}
#endif
#if defined TARGET_oefsolide3
\text{name_enonce=Le solide suivant a pour nombre de sommets&nbsp;}
#endif
#if defined TARGET_oefsolide4
\text{name_enonce=Le solide suivant a pour nombre d'arêtes&nbsp;}
#endif
#if defined TARGET_oefsolide5
\text{name_enonce=Le solide suivant a pour nombre de faces rectangulaires&nbsp;}
#endif
