#if defined TARGET_oefsolide1 || defined TARGET_oefsolide2 || defined TARGET_oefsolide3 || defined TARGET_oefsolide4 || defined TARGET_oefsolide5
# define TITRE Description de solides
#endif
#if defined TARGET_oefcontvol1 || defined TARGET_oefcontvol2 || defined TARGET_oefcontvol3 || defined TARGET_oefcontvol4 || defined TARGET_oefcontvol5
# define TITRE Contenance de volumes
#endif
#if defined TARGET_oefconvcont1 || defined TARGET_oefconvcont2 || defined TARGET_oefconvcont3 || defined TARGET_oefconvcont4 || defined TARGET_oefconvcont5
# define TITRE Conversions de contenances
#endif
#if defined TARGET_oefconvconvol1 || defined TARGET_oefconvconvol2 || defined TARGET_oefconvconvol3 || defined TARGET_oefconvconvol4 || defined TARGET_oefconvconvol5
# define TITRE Conversions
#endif
#if defined TARGET_oefformpave3 || defined TARGET_oefformpave4
# define TITRE Formule du volume du pavé
#endif
#if defined TARGET_oefpaveparaperp1 || defined TARGET_oefpaveparaperp2 || defined TARGET_oefpaveparaperp3 || defined TARGET_oefpaveparaperp4
# define TITRE Parallèles et perpendiculaires
#endif
#if defined TARGET_oefvolume1 || defined TARGET_oefvolume2 || defined TARGET_oefvolume3 || defined TARGET_oefvolume4 || defined TARGET_oefvolume5
# define TITRE Volume
#endif
#if defined TARGET_oefconvvol1 || defined TARGET_oefconvvol2 || defined TARGET_oefconvvol3 || defined TARGET_oefconvvol4 || defined TARGET_oefconvvol5
# define TITRE Conversions de volumes
#endif
#if defined TARGET_oefrecpersp1 || defined TARGET_oefrecpersp2 || defined TARGET_oefrecpersp3 || defined TARGET_oefrecpersp4 || defined TARGET_oefrecpersp5
# define TITRE Parallélépipède
#endif
#if defined TARGET_oefrecpatron1 || defined TARGET_oefrecpatron2 || defined TARGET_oefrecpatron3 || defined TARGET_oefrecpatron4 || defined TARGET_oefrecpatron5
# define TITRE Reconnaître un patron
#endif
#if defined TARGET_oefpaveparaperp1 || defined TARGET_oefpaveparaperp2 || defined TARGET_oefpaveparaperp3 || defined TARGET_oefpaveparaperp4 || defined TARGET_oefpaveparaperp5
# define TITRE Parallèles et perpendiculaires
#endif
#if defined TARGET_oefpatron1 || defined TARGET_oefpatron2 || defined TARGET_oefpatron3 || defined TARGET_oefpatron4 || defined TARGET_oefpatron5
# define TITRE Patron
#endif
#if defined TARGET_oefformpave1 || defined TARGET_oefformpave2 || defined TARGET_oefformpave3 || defined TARGET_oefformpave4 || defined TARGET_oefformpave5
# define TITRE Formules de volume
#endif
#if defined TARGET_oefconstpat1 || defined TARGET_oefconstpat2 || defined TARGET_oefconstpat3 || defined TARGET_oefconstpat4 || defined TARGET_oefconstpat5
# define TITRE Construction d'un patron
#endif
