!set prompt=<span class="bold" style="color:red">/</span> : $name_edge<br />\
	<img src="$module_dir/gifs/o1.gif" alt="o1" /> : $name_vertex<br />\
	<img src="$module_dir/gifs/circle3.gif" alt="circle3" /> : $name_insccircle<br />\
	<img src="$module_dir/gifs/o0.gif" alt="o0" /> : $name_centerinscrit<br />

$(name_question_$ctype)

!if $status!=wait
 <p>
 $(name_answer_$ctype).
 </p>
 !set prompt=$prompt\
	<span class="bold" style="color:#00ff00">/</span> : $name_biss<br />\
	<img src="$module_dir/gifs/cross.gif" alt="cross" /> : $name_yourclick<br />\
	<img src="$module_dir/gifs/circle.gif" alt="circle" /> : $name_truevertex

!endif
