#if defined TARGET_convert1 || defined TARGET_convert2 || defined TARGET_convert3 || defined TARGET_convert4 || defined TARGET_convert5
# define TITRE Conversion degré / radian
#endif
#if defined TARGET_assocgr1 || defined TARGET_assocgr2 || defined TARGET_assocgr3 || defined TARGET_assocgr4 || defined TARGET_assocgr5
# define TITRE Association de fonctions
#endif
#if defined TARGET_enchaineasy1 || defined TARGET_enchaineasy2 || defined TARGET_enchaineasy3 || defined TARGET_enchaineasy4 || defined TARGET_enchaineasy5
# define TITRE Enchainement simple de fonctions
#endif
#if defined TARGET_enchainrange1 || defined TARGET_enchainrange2 || defined TARGET_enchainrange3 || defined TARGET_enchainrange4 || defined TARGET_enchainrange5
# define TITRE Enchainement et encadrement
#endif
#if defined TARGET_enchaintvar1 || defined TARGET_enchaintvar2 || defined TARGET_enchaintvar3 || defined TARGET_enchaintvar4 || defined TARGET_enchaintvar5 || defined TARGET_
# define TITRE Enchainement et variations
#endif
#if defined TARGET_expalg1 || defined TARGET_expalg2 || defined TARGET_expalg3 || defined TARGET_expalg4 || defined TARGET_expalg5
# define TITRE Expression algébrique d'une fonction
#endif
#if defined TARGET_vocabaff1 || defined TARGET_vocabaff2 || defined TARGET_vocabaff3 || defined TARGET_vocabaff4 || defined TARGET_vocabaff5
# define TITRE Vocabulaire des fonctions affines
#endif
#if defined TARGET_valtrigo1 || defined TARGET_valtrigo2 || defined TARGET_valtrigo3 || defined TARGET_valtrigo4 || defined TARGET_valtrigo5
# define TITRE Valeurs remarquables
#endif
#if defined TARGET_traceraff1 || defined TARGET_traceraff2 || defined TARGET_traceraff3 || defined TARGET_traceraff4 || defined TARGET_traceraff5
# define TITRE Tracer de fonctions affines
#endif
#if defined TARGET_signeaff1 || defined TARGET_signeaff2 || defined TARGET_signeaff3 || defined TARGET_signeaff4 || defined TARGET_signeaff5
# define TITRE Signe de mx+p
#endif
#if defined TARGET_ptetrigo1 || defined TARGET_ptetrigo2 || defined TARGET_ptetrigo3 || defined TARGET_ptetrigo4 || defined TARGET_ptetrigo5
# define TITRE Propriétés de sinus et cosinus
#endif
#if defined TARGET_pteinverse1 || defined TARGET_pteinverse2 || defined TARGET_pteinverse3 || defined TARGET_pteinverse4 || defined TARGET_pteinverse5
# define TITRE Propriété de la fonction inverse
#endif
#if defined TARGET_ptecarre1 || defined TARGET_ptecarre2 || defined TARGET_ptecarre4 || defined TARGET_ptecarre5 || defined TARGET_ptecarre3
# define TITRE Propriété de la fonction carré
#endif
#if defined TARGET_findaff1 || defined TARGET_findaff2 || defined TARGET_findaff3 || defined TARGET_findaff4 || defined TARGET_findaff5
# define TITRE Reconnaitre des fonctions affines
#endif
#if defined TARGET_ptecar1 || defined TARGET_ptecar2 || defined TARGET_ptecar3 || defined TARGET_ptecar4 || defined TARGET_ptecar5
# define TITRE Propriété caractéristique
#endif
