!header
!read Exindex
<style>
/**** Bloc description du module ****/
.desc_mod{
  width:80%;
  margin-left:auto;
  margin-right:auto;
  border:1px solid $wims_ref_bgcolor;
  border-top-left-radius: 11px;
  border-top-right-radius: 11px;
}
.title_desc_mod{
  color:white;
  background:$wims_ref_bgcolor;
  border-top-left-radius:10px;
  border-top-right-radius:10px;
  margin-bottom:0px;
  margin-top:0px;
  padding-top:0.5em;
  padding-bottom:0.5em;
}

.p_desc_mod {
  padding-right:0.5em;
  padding-left:0.5em;
} 
.logo_desc_mod {
  float:right;
  margin-left:0.5em;
  margin-right:0.2em;
  margin-top:0.2em;
}
</style>
<div class="desc_mod">
 <h2 class="wimscenter title_desc_mod">Description du module</h2>
 <img src="$module_dir/images/logo_euler.png" class="logo_desc_mod" alt="Logo Euler Académie de Versailles" title="Euler Académie de Versailles" width="48" height="36">
 <p class="p_desc_mod">Ce module regroupe pour l'instant $exototal exercices sur la décomposition en facteurs premiers d'un nombre entier en Cycle 4 (<em>BO n° 22 du 29 mai 2019</em>).<br>
 Certains exercices peuvent être configurés spécifiquement pour être adaptés aux différents niveaux 5<sup>e</sup>, 4<sup>e</sup> et 3<sup>e</sup> (réglages à faire dans <em>Paramétrage spécifique à certains exercices du module</em>).
 </p> 
</div>
!read oef/intromenu.phtml
!tail
