!header
!read Exindex
!if $lang=fr
  Ce module regroupe pour l'instant $exototal exercices sur les systèmes
  linéaires élémentaires de 2 équations et 2 variables. Ces systèmes ont
  toujours une solution unique d'entiers. Y compris divers problèmes
  d'application.
  !goto tail
!endif
!if $lang=es
  Este módulo contiene en este momento $exototal ejercicios de sistemas lineales
  con 2 variables y dos ecuaciones elementales. Estos sistemas siempre tendrán
  solución entera única. Incluye varios problemas de aplicación.
  !goto tail
!endif
!if $lang=ca
  Aquest mòdul conté en aquest moment $exototal exercicis de sistemes lineales
  amb 2 variables i dues equacions elementals. Aquests sistemes sempre tindran
  solució entera única. Inclou alguns problemes d'aplicació.
  !goto tail
!endif
!if $lang=nl
  Deze module bevat $exototal oefeningen over lineaire systemen,
  van twee vergelijkingen met twee onbekenden.
  Deze systemen zijn altijd oplosbaar.
  !goto tail
!endif
This module currently contains $exototal exercises on elementary linear systems
of 2 equations and 2 variables. These systems will always have a unique
integer solution. Includes various application problems.

:tail
!read oef/intromenu.phtml
!tail
