!! Fichier form.phtml
!!! On pose les questions dans ce fichier. D'habitude, c'est par
!!! des forms (formulaires).
!!! j'ai mis etape=0 quand le travail est terminé (status Done) pour éviter le réaffichage des énoncés
!form reply
!if $mode1=exo3
  !goto EXO3
!endif
!if $mode1=exo4
  !goto EXO4
!endif
!!!!! EXO 1 ou 2
!if $mode1 isitemof exo1,exo2
  !if $[$etape]=1
    <ul class="question">
    <li><label for="dAB">\(A B =\)</label><input type="text" name="dAB" id="dAB" size="20" value="$dAB"></li>
    <li><label for="dAC">\(A C =\)</label><input type="text" name="dAC" id="dAC" size="20" value="$dAC"></li>
    <li><label for="dBC">\(B C =\)</label><input type="text" name="dBC" id="dBC" size="20" value="$dBC"></li>
    </ul>
  !endif
  !if $[$etape]=2 and $niveau>=$etape
    !set wims_ref_class=wims_formradio
    <ul class="question">
    !set wims_html_mode=li
    !formradio nattri from 0 to 4 prompt Triangle isocèle non rectangle et non équilatéral,\
    Triangle rectangle non isocèle,\
    Triangle isocèle-rectangle,\
    Triangle équilatéral,\
    Triangle non particulier
    </ul>
  !endif
  !if $[$etape]=3 and $niveau>=$etape
    <ul class="question">
    <li><label for="xI">\(x_I = \)</label> <input type="text" name="xI" id="xI" size="20" value="$xI"></li>
    <li><label for="yI">\(y_I = \)</label> <input type="text" name="yI" id="yI" size="20" value="$yI"></li>
    </ul>
  !endif
  !if $[$etape]=4 and $niveau>=$etape
    <ul class="question">
    <li><label for="xE">\(x_E = \)</label> <input type="text" name="xE" id="xE" size="20" value="$xE"></li>
    <li><label for="yE">\(y_E = \)</label> <input type="text" name="yE" id="yE" size="20" value="$yE"></li>
    </ul>
  !endif
  !if $[$etape]=5 and $niveau >=$etape
    <ul class="question">
    !set wims_html_mode=li
    !formradio natqua from 0 to 4 prompt Parallélogramme non particulier,\
      Losange non carré,\
      Rectangle non carré,\
      Carré,\
      Quadrilatère autre qu'un parallélogramme
    </ul>
  !endif
  !if $[$etape]=6 and $niveau>=$etape
    <ul class="question">
    <li><label for="xD">\(x_D = \)</label> <input type="text" name="xD" id="xD" size="20" value="$xD"></li>
    <li><label for="yD">\(y_D = \)</label> <input type="text" name="yD" id="yD" size="20" value="$yD"></li>
    </ul>
  !endif
  !if $[$etape]=7 and $niveau>=$etape
    <ul class="question">
    <li><label for="xF">\(x_F = \)</label> <input type="text" name="xF" id="xF" size="20" value="$xF"></li>
    <li><label for="yF">\(y_F = \)</label> <input type="text" name="yF" id="yF" size="20" value="$yF"></li>
    </ul>
  !endif
  !if $[$etape]=8 and $niveau>=$etape
    <ul class="question">
    <li><label for="xG">\(x_G = \)</label> <input type="text" name="xG" id="xG" size="20" value="$xG"></li>
    <li><label for="yG">\(y_G = \)</label> <input type="text" name="yG" id="yG" size="20" value="$yG"></li>
    </ul>
  !endif
  !if $[$etape]=9 and $niveau>=$etape
    <ul class="question">
    <li><label for="xH">\(x_H = \)</label> <input type="text" name="xH" id="xH" size="20" value="$xH"></li>
    <li><label for="yH">\(y_H = \)</label> <input type="text" name="yH" id="yH" size="20" value="$yH"></li>
    </ul>
  !endif
  !if $niveau>=$etape or $[$etape]=1
    <div class="wimscenter"><input type="submit" value="$name_validate"></div>
  !endif
  !!formend
  !goto score
  !exit
!endif
!!!! END EXO 1 ou 2

!!!! EXO 3 Droite d'Euler
!!!!
:EXO3
!!test suivant inutile ?
!if $mode1=exo3
  !!!! Calcul du centre de gravité selon la formule vect(CG)=2/3vect(CI)
  !if $etape=1 and $next=0
    <ul class="question"><li>
    Le milieu \(I\) de \([A B]\) a pour coordonnées :
    (<input type="text" name="rep1" id="rep1" size="10" value="$rep1"> ;
     <input type="text" name="rep2" id="rep2" size="10" value="$rep2">)
    </li><li>
    Le vecteur \(\overrightarrow{C I}\) a pour coordonnées :
    (<input type="text" name="rep3" id="rep3" size="10" value="$rep3"> ;
     <input type="text" name="rep4" id="rep4" size="10" value="$rep4">)
    </li><li>
    Donc \(G \) a pour coordonnées :
    (<input type="text" name="rep5" id="rep5" size="10" value="$rep5"> ;
     <input type="text" name="rep6" id="rep6" size="10" value="$rep6">)
     </li></ul>
  !endif
!!! Calcul de l'orthocentre comme intersection des hauteurs issues de A et de C
  !if $etape=2 and $next=0
    <ul class="question"><li>
    La hauteur issue de \(A\) du triangle \(A B C\) a pour équation :
     <label for="rep1">\(y\) =</label> <input type="text" name="rep1" id="rep1" size="8" value="$rep1"> x + <input type="text" name="rep2" id="rep2" size="8" value="$rep2">
    </li><li>
    La hauteur issue de \(C\) du triangle \(A B C\) a pour équation :
    !formselect rep3 list x,y prompt x,y
     = <input type="text" name="rep4" id="rep4" size="8" value="$rep4">
    </li><li>
    Donc \( H \) a pour coordonnées :
    (<input type="text" name="rep5" id="rep5" size="10" value="$rep5"> ;
     <input type="text" name="rep6" id="rep6" size="10" value="$rep6">)
    </li></ul>
  !endif
  !if $etape=3 and $next=0
    <ul class="question"><li>
    La médiatrice du segment \([B C]\) a pour équation :
     <label for="rep1">y =</label> <input type="text" name="rep1" id="rep1" size="8" value="$rep1">
     <label for="rep2">x +</label>
     <input type="text" name="rep2" id="rep2" size="8" value="$rep2">
    </li><li>
    La médiatrice du segment \([A B]\) a pour équation :
    !formselect rep3 list x,y prompt \(x\),\(y\)
     = <input type="text" name="rep4" id="rep4" size="8" value="$rep4">
    </li><li>
    Donc \( M \) a pour coordonnées :
    (<input type="text" name="rep5" id="rep5" size="10" value="$rep5"> ;
     <input type="text" name="rep6" id="rep6" size="10" value="$rep6">)
     </li></ul>
  !endif
  !if $etape=4 and $next=0
    <ul class="question"><li>
    Le vecteur \(\overrightarrow{G H}\) a pour coordonnées :
     <label for="rep1">\(x\) = </label><input type="text" name="rep1" id="rep1" size="8" value="$rep1">
     et \(y\) = <input type="text" name="rep2" size="8" value="$rep2">
    </li><li>
    Le vecteur \(\overrightarrow{G M}\) a pour coordonnées :
      <label for="rep3">\(x'\) = </label><input type="text" name="rep3" id="rep3" size="8" value="$rep3">
      <label for="rep4">\(y'\) = </label><input type="text" name="rep4" id="rep4" size="8" value="$rep4">
    </li><li>
    Appliquons le critère de colinéarité :
    <label for="rep5">\(x y'\) =</label> <input type="text" name="rep5" id="rep5" size="10" value="$rep5">
    <label for="rep6">\(y x'\) =</label> <input type="text" name="rep6" id="rep6" size="10" value="$rep6">
    </li><li>
    Conclusion : Comme \(x y'-x y'\) est
    !formselect rep7 list 0,1 prompt nul,non nul
     , les vecteurs sont
    !formselect rep8 list co,noco,al,noal prompt colinéaires,non colinéaires,alignés,non alignés
    Donc les points \(G\), \(H\) et \(M\) sont
    !formselect rep9 list co,noco,al,noal prompt colinéaires,non colinéaires,alignés,non alignés
    </li></ul>
  !endif
!!!! BOUTONS SUBMIT
  !if $etape<5
    <div class="wimscenter">
    !if $next=1
      <input type="submit" name="user" value="$name_questsuiv">
    !else
      <input type="submit" name="user" value="$name_validate">
    !endif
    </div>
  !endif
  !goto score
!endif
!!!! END EXO 3

:EXO4
!!!! EXO4 Projete orthogonal
!if $mode1=exo4
  !!!! BUT : trouver D tel que BCD rectangle en C ;
  !!!! trouver ainsi une direction normale à (BC)
  !if $etape=1 and $next=0
    <ul class="question"><li>
    On peut proposer le point \(D\) de coordonnées :
    (<input type="text" name="rep1" id="rep1" size="8" value="$rep1"> ,
    <input type="text" name="rep2" id="rep2" size="8" value="$rep2">)
    </li><li>
    On a alors :
    <label for="rep4">\(B C^2\) =</label> <input type="text" name="rep4" id="rep4" size="8" value="$rep4"> et
    <label for="rep5">\(C D^2\) =</label> <input type="text" name="rep5" id="rep5" size="8" value="$rep5">
    et
    <label for="rep6">\(B D^2\) =</label> <input type="text" name="rep6" id="rep6" size="8" value="$rep6">
    </li><li>Le triangle \(B C D\)
    !formselect rep3 list yes,no prompt est,n'est pas
 rectangle en \(C\).
    </li></ul>
  !endif
  !if $etape=2 and $next=0
   <ul class="question"><li>
    Le point \(P\) appartient à :
    !formcheckbox rep1 list point,parabc,perpbc,paracd,perpcd prompt \((B C)\), la parallèle à \((B C)) passant par \(A), la perpendiculaire à \((B C)) passant par \(A), la parallèle à \((C D)) passant par \(A), la perpendiculaire à \((C D)) passant par \(A)
    </li></ul>
  !endif
  !if $etape=3 and $next=0
  <ul class="question"><li>
    La droite \((C D)\) a coefficient directeur :
    <label for="rep1">\(a\) =</label> <input type="text" name="rep1" id="rep1" size="8" value="$rep1">
    </li><li>
     \(\Delta\) a pour équation \(y = m x + p\) avec
    <label for="rep2">\(m\) =</label> <input type="text" name="rep2" id="rep2" size="8" value="$rep2"> et \(p\) = <input type="text" name="rep3" id="rep3" size="8" value="$rep3">
    </li></ul>
  !endif
  !if $etape=4 and $next=0
    La droite \((B C)\) a pour équation \(y = m'x + p'\) avec
    <label for="rep1">\(m'\) =</label> <input type="text" name="rep1" id="rep1" size="8" value="$rep1"> et \(p'\) = <input type="text" name="rep2" id="rep2" size="8" value="$rep2">
  !endif
  !if $etape=5 and $next=0
    <div class="wimscenter">
    <label for="rep1">\(x_P\) =</label> <input type="text" name="rep1" id="rep1" size="8" value="$rep1"> et
    <label for="rep2">\(y_P\) =</label> <input type="text" name="rep2" size="8" value="$rep2">
    </div>
  !endif
!!!! BOUTONS SUBMIT
  !if $etape<6
    <div class="wimscenter">
    !if $next=1
      <input type="submit" name="user" value="$name_questsuiv">
    !else
      <input type="submit"  name="user" value="$name_validate">
    !endif
    </div>
  !endif
!endif
!!!! END EXO 4
:score
!formend
!!! Affichage des scores partiels
!if $etape>1 and $affsco!=$empty
  <h2 class="small">Scores obtenus</h2>
  <ol>$affsco</ol>
!endif
