!! Fichier help.phtml

<h2 class="small"> Consignes d'écriture.</h2>
<ul><li> Les résultats doivent être donnés sous forme exacte.
</li><li> Dans une écriture décimale, le séparateur de la partie entière
et de la partie décimale est le point et non pas la virgule.
</li><li> Un nombre rationnel sera écrit sous forme de fraction irréductible.
</li><li> La fraction \(\frac{a}{b}\) s'écrit <span class="tt">a/b</span>.
 La fraction \(\frac{a+c}{b+d}\) s'écrit <span class="tt">(a+c)/(b+d)</span>.
</li><li> La racine carrée de \(a\), soit \(\sqrt{a}\), s'écrit <span class="tt">sqrt(a)</span>.
 Par exemple, taper <span class="tt">3*sqrt(2)</span>
pour écrire \(3\sqrt{2}\), sans oublier le symbole de multiplication *.
</ul>
<h2 class="small">Formulaire sur les coordonnées.</h2>
<ul><li>
Coordonnées d'un vecteur \(\overrightarrow{A B} : (x_B - x_A ; y_B - y_A)\)
</li><li>
Coordonnées du milieu \(I\) d'un segment \([A B]\) : \(x_I = \frac {x_A + x_B}{2}\) et \(y_I = \frac {y_A + y_B}{2}\)
</li><li>
Distance entre deux points \(A\) et \(B\) : \(A B = sqrt( (x_B - x_A)^2 + (y_B - y_A)^2)\)
</li></ul>
<h2 class="small">Formulaire sur les droites.</h2>
<ul><li>
Toute droite verticale du plan a une <b>équation réduite</b> de la forme \(x = c\).
</li><li>
Toute droite non verticale du plan a une équation réduite de la forme \(y = m x + p\).
Le coefficient \(m\) est le <b>coefficient directeur</b> de la droite.
Le coefficient \(p\) est l'<b>ordonnée à l'origine</b> de la droite.
</li><li>
Le point \(A\) appartient à la droite \(D\) d'équation \(y = m x + p\) si et seulement si
ses coordonnées vérifient l'équation de la droite, ce qui signifie que \(y_A = m x_A + p\).
</li><li>
Calcul du coefficient directeur d'une droite non verticale \((A B)\) : \( m = \frac{y_B-y_A}{x_B-x_A}\).
</li><li>
Calcul de l'ordonnée à l'origine d'une droite d'équation \(y = m x + p\),
connaissant un point \(A\) de la droite :
on tire la valeur de \(p\) de l'égalité \(y_A = m x_A + p\).
</li><li>
Deux droites parallèles non verticales ont le même coefficient directeur.
</li></ul>
<h2 class="small">Formulaire sur les triangles.</h2>
<ul>
<li>Le <b>centre de gravité</b> d'un triangle est le point d'intersection des médianes.
 Il est situé aux deux-tiers d'une médiane à partir du sommet correspondant.
</li><li>L'<b>orthocentre</b> d'un triangle est le point d'intersection des hauteurs.
</li><li>Les médiatrices d'un triangle se croisent au <b>centre du cercle circonscrit</b> au triangle.
</li><li>Les bissectrices d'un triangle se croisent au <b>centre du cercle inscrit</b> dans le triangle.
</li></ul>
