!! Fichier Intro.phtml
!read lang_titles_fr
!header
<p>
Ce module présente des exercices de synthèse de géométrie analytique, en classe de Seconde.
</p>
Les exercices se déroulent par étapes corrigées au fur et à mesure.
<ul><li>
Triangles et parallélogrammes :
points à coordonnées rationnelles (1)
ou radicales (2) :
<ul><li>
Nature d'un triangle : calculs de longueurs
</li><li>
Nature d'un quadrilatère : situation précédente avec, en plus,
 utilisation des coordonnées du milieu d'un segment
</li><li>
Nature d'un quadrilatère avec vecteurs : situation précédente avec,
 en plus, utilisation des coordonnées de vecteurs
</li><li>
et enfin, l'exercice complet avec recherche du centre de gravité
d'un triangle.
</li>
</ul></li><li>
Droite d'Euler : alignement des centres de gravité, du cercle circonscrit
et orthocentre d'un triangle, en 4 étapes.
</li><li>
Projeté orthogonal : déterminer graphiquement une perpendiculaire à une droite puis calculer le
 projeté orthogonal d'un point sur cette droite, en 5 étapes.</li>
</ul>
<hr>
!set liste=exo1_2,exo1_6,exo1_7,exo1,exo2_2,exo2_6,exo2_7,exo2,exo3,exo4
!form new
<div class="wimscenter">
!!default mode=exo1
!set wims_formselect_switch=multiple="multiple" size="10"
!formselect mode list $liste prompt $exotitles
</div>
!reset wims_formselect_switch
<input type="hidden" name="module" value="$module">
<div class="wimscenter">
<input type="submit" value="Sélectionnez un exercice puis cliquez ici">
</div>
!formend

!tail
