!! Fichier main.phtml

!read lang_titles_fr
!set t=!positionof item $mode in $listexos
!set title=!item $t of $exotitles
!set module_title=$title
!set wims_html_header=$wims_html_header\
<style>\
ul.question {list-style:none}\
</style>

!!table.present {width:100%;background-color:#FFCC66;\
!!margin-left:auto;margin-right:auto;border-collapse:collapse;}\
!!table.present td {border-collapse:collapse;padding:3pt;\
!!background-color:#FFCC66;vertical-align:top;}\
!!table.present tr > td:nth-child(3) {width:15%;background-color:#00FFCC}\
!!table.present tr > td:first-child {width:40%}\
!!table.present tr > td:nth-child(2) {width:45%}\
!!td.score {background-color:red}\

!header
!!! La présentation de l'exercice.
!!!!if $status!=done
!read present.phtml
!!!!!endif
!if $error!=$empty
  <div>
  !read msg.phtml
  </div>
!endif
!if $status=waiting
  !read form.phtml
!endif
!if $status=done
  !!! L'analyse de réponse finale
  !read answer.phtml
!endif
!!!TEST
<div class="wimscenter">
!set wims_ref_class=wims_button
!href exo_Renew
</div>
!tail
