!! Fichier present.phtml
!!! Ce fichier présente la question à résoudre.
!let wims_texsize=-1
!!niveau donne le nombre d'étapes.
!if $mode1=exo3
  !goto EXO3
!endif
!if $mode1=exo4
  !goto EXO4
!endif
!!!! EXO Michel Triangles, parallélogrammes
!if $mode1 isitemof exo1,exo2
  <div class="wims_columns">
  <div class="medium_size img_col">
  !if $etape=1
    !insdraw $dessin1
  !else
    !let i=$[$etape-1]
    !if $i=-1
      !insdraw $(dessin$niveau)
    !else
      !insdraw $(dessin$i)
    !endif
  !endif
  </div><div class="medium_size text_col">
  Le but de cet exercice est d'étudier une configuration
  en géométrie analytique.
  Il y a $niveau étapes qui sont évaluées au fur et à mesure.
  <h2 class="small">Énoncé.</h2>
  Dans un repère orthonormal du plan, on considère les points :
  \(A($xA; $yA)\), \(B($xB; $yB)\) et \(C($xC; $yC)\).
  !if $reponse!=$empty
  <h2 class="small">Solutions</h2>
  <ul>$reponse</ul>
  !endif
  </div></div>
!!!! Analyse des réponses à la question courante :
  !if $error=$empty and $feedback!=$empty
    $feedback
  !endif
!!! Nouvelle Question
  !set etape=$[$etape]
  !if $etape>0
    !if $etape=1 or $niveau>=$etape
      <h2 class="small">Étape $etape.</h2>
      !if $etape=1
        Calculer les distances \(A B\), \(A C\) et \(B C\).
        <div class="wims_instruction"> Donner des valeurs exactes.
        Pour écrire une racine carrée \(sqrt(a)\) taper <span class="tt">sqrt(a)</span> et
        pour \(b\sqrt{a}\) taper <span class="tt">b*sqrt(a)</span>, sans oublier
        le symbole <span class="tt">*</span>.</div>
      !else
        !if $etape=2
          Quelle est la nature du triangle \(A B C\) ?
        !endif
        !if $etape=3
          Calculer les coordonnées du milieu \(I\) de \([B C]\).
        !endif
        !if $etape=4
          Calculer les coordonnées du symétrique \(E\) de \(A\) par rapport à \(I\).
        !endif
        !if $etape=5
          Quelle est la nature du quadrilatère \(A B E C\) ?
        !endif
        !if $etape=6
          Calculer les coordonnées du point \(D\) tel que \(A B C D\) est un parallélogramme.
        !endif
        !if $etape=7
          Calculer les coordonnées du point \(F\) tel que \(\overrightarrow{D F}=2 \overrightarrow{D A}\).
        !endif
        !if $etape=8
          Calculer les coordonnées du centre de gravité \(G\) du triangle \(A B C\).
        !endif
        !if $etape=9
          Pour finir, calculer les coordonnées du centre de gravité H du triangle \(D E F\).
        !endif
      !endif
    !endif
    !exit
!!<br>
!!<br>[Réponses attendues :
!!<br> \(A B = $repAB\) ; \(A C = $repAC\) ; \(B C = $repBC\)
!!<br>I = \($repxI\); \($repyI\) E = \($repxE\); \($repyE\) D = \($repxD\); \($repyD\) F = \($repxF) ; \($repyF)
!!<br>G = \($repxG); \($repyG) H = \($repxH); \($repyH) etape \($etape)]
!!<br> sim : $sim
!endif
!!!! END EXO Michel Triangles Parallélogrammes
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!! EXO 3 VeRo Droite d'Euler
:EXO3
!if $mode1=exo3
  <div class="wims_columns">
  <div class="medium_size img_col">
  !insdraw $(dessin$etape)
  </div><div class="medium_size img_txt">
  Le but de cet exercice est de vérifier, par le calcul analyique, que le centre de gravité,
  l'orthocentre et le centre du cercle circonscrit d'un triangle
  sont alignés sur une droite appellée "<span class="wims_emph">droite d'Euler</span>".
  <div class="wims_instruction">Il y a 4 étapes, corrigées au fur et à mesure.
  On demande des valeurs exactes, entières ou fractions irréductibles.</div>

  <h2 class="small">Énoncé.</h2>
  Dans le plan muni d'un repère orthonormé, on considère le triangle \(A B C) dont les sommets sont
  \(A\)($xA; $yA), \(B)($xB; $yB) et \(C)($xC; $yC).

  !!! Solutions aux questions précédentes
  !if $reponse!=$empty
    <h2 class="small">Solutions.</h2>\
    <ul>$reponse</ul>
  !endif
  </div></div>
  <h2 class="small">Étape $etape.</h2>
  !if $etape=1
    Soit \(G\) le centre de gravité du triangle
    \(A B C\).
  !endif
  !if $etape=2
      On admet que le point \(P($xP; $yP)\) est le pied de la
    hauteur issue de \(A\) sur la droite \((B C)\).
    Soit \(H\) l'orthocentre du triangle \(A B C\).
  !endif
  !if $etape=3
    Soit \(M\) le centre du cercle circonscrit au triangle
    \(A B C\).
  !endif
  !if $etape=4
     Enfin, examinons si les points \(G\), \(H\) et \(M\) sont alignés.
  !endif
  !exit
!endif
!!!!!! END EXO DTE d'EULER
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!! EXO 4 Dte perpendiculaire
:EXO4
!if $mode1=exo4
  <div class="wims_columns">
  <div class="medium_size img_col">
  !insdraw $(dessin$etape)
  </div><div class="medium_size text_col">
  Le but de cet exercice est de déterminer les coordonnées du projeté orthogonal
  d'un point sur une droite.
  <div class="wims_instruction">Il y a 5 étapes, corrigées au fur et à mesure.
  On demande des valeurs exactes, entières ou fractions irréductibles.</div>

  <h2 class="small">Énoncé.</h2>
  Dans le plan muni d'un repère orthonormé, on considère les trois points
  \(A\)($xA; $yA), \(B\)($xB; $yB) et \(C\)($xC; $yC).
  !!! Solutions aux questions précédentes
  !if $reponse!=$empty
    <h2 class="small">Solutions.</h2>
    <ul>$reponse</ul>
  !endif
  </div></div>
  <h2 class="small">Étape $etape.</h2>
  !if $etape=1
    En vous aidant du graphique, proposez un point \(D\) tel
    que le triangle \(B C D\) soit rectangle en \(C\).
    Vérifiez la construction en appliquant le théorème de
    Pythagore.
  !endif
  !if $etape=2
    Soit \(P\) le projeté orthogonal du point \(A\) sur la droite
    \(B C\). Quelle(s) propriété(s) géométrique(s) caractérise(nt) le point \(P\) ?
  !endif
  !if $etape=3
    Soit $m_Delta la parallèle à \((C D)\)
    passant par \(A\). Déterminez une équation de $m_Delta.
  !endif
  !if $etape=4
    Déterminez une équation de la droite \((B C)\).
  !endif
  !if $etape=5
    Calculez les coordonnées du point \(P\).
  !endif
!endif
!!!!!! END EXO PROJ ORTHOGONAL

