!! Fichier var.init
wims_backslash_instex=yes
wims_backslash_insmath=yes
wims_multiexec=pari maxima
wims_texsize=-1
!set name_validate=Valider
!set name_questsuiv=Étape suivante
!!! style pour bouton coloré

style=font-size:14px;color:#330033;font-weight:bold;background-color: #FFCC66;
!!! pour les titres

!set listexos=exo1_2,exo1_6,exo1_7,exo1,exo2_2,exo2_6,exo2_7,exo2,exo3,exo4
!set listniveau=2,6,7,9,2,6,7,9,1,5
!if $mode=$empty
  mode=!randitem $listexos
!endif
mode1=$mode
!if _ isin $mode1
  mode1=!replace internal _ by , in $mode1
  niveau=$(mode1[2])
  mode1=$(mode1[1])
!else
  niveau=!positionof item $mode in $listexos
  niveau=!item $niveau of $listniveau
!endif
status=waiting

!!!!! EXO 3 ou 4 sur droite d'EULER / SWITCH
!if $mode1 isitemof exo3,exo4
  !read euler.init
  !exit
!endif
!!!!! EXO 1 ou 2
!reset error score1 score2 score3 score4 score5 score6 score7 score8 score9
etape=1
!!!! choix des points A et B
i=!randint 1,6
xA=!item $i of 0,-1,-2,-3,-4,-5
i=!randint 1,11
yA=!item $i of 0,-1,-2,-3,-4,-5,1,2,3,4,5
i=!randint 1,5
xB=!item $i of 1,2,3,4,5
i=!randint 1,11
yB=!item $i of 0,-1,-2,-3,-4,-5,1,2,3,4,5

?????
r2=!exec maxima sqrt(2)

!!!! Liste des natures
!!! nature triangle=0-isocèle, 1-rectangle , 2-isocèle-rectangle, 3-équilatéral, 4-non particulier
!!! nature quadrilatère=0-parallélogramme, 1-losange, 2-rectangle, 3-carré, 4-autre
!!! choix des similitudes et calcul de C

!if $mode1=exo1
  i=!randint 1,6
  sim=!item $i of rotp90,rotm90,simp90,simm90,simp45,simm45
  !if $i=1 or $i=2
    repnattri=2
    repnatqua=3
  !endif
  !if $i=3 or $i=4
    repnattri=1
    repnatqua=2
  !endif
  !if $i=5 or $i=6
    repnattri=2
    repnatqua=0
  !endif
!endif
!if $mode1=exo2
  i=!randint 1,6
  sim=!item $i of simp60, simm30, rotp60, rotm60, rotp30, rotm30
  !if $i=1 or $i=2
    repnattri=1
    repnatqua=0
  !endif
  !if $i=3 or $i=4
    repnattri=3
    repnatqua=1
  !endif
  !if $i=5 or $i=6
    repnattri=0
    repnatqua=1
  !endif
!endif

nat1=!item $[1+ $repnattri] of triangle isocèle, triangle rectangle , triangle isocèle-rectangle, triangle équilatéral, triangle non particulier
nat2=!item $[1+ $repnatqua] of parallélogramme, losange, rectangle, carré, autre quadrilatère
!!! rotation de +90 de centre A
!if $sim=rotp90
  xC=!exec maxima $xA + ($yA) - ($yB)
  yC=!exec maxima -($xA) + ($yA)  + ($xB)
!endif
!!! rotation de -90 de centre A
!if $sim=rotm90
  xC=!exec maxima $xA - ($yA) + ($yB)
  yC=!exec maxima $xA + ($yA) - ($xB)
!endif
!!! similitude de +90 de centre A de rapport 2
!if $sim=simp90
  xC=!exec maxima -2*($yB) + ($xA) + 2*($yA)
  yC=!exec maxima 2*$xB - 2*($xA) + ($yA)
!endif
!!! similitude de -90 de centre A de rapport 2
!if $sim=simm90
  xC=!exec maxima 2*($yB) + ($xA) - 2*($yA)
  yC=!exec maxima -2*($xB) + 2*($xA) + ($yA)
!endif
!!! similitude de +45 de centre A de rapport rac(2)
!if $sim=simp45
  xC=!exec maxima $xB - ($yB) + ($yA)
  yC=!exec maxima $xB + ($yB) - ($xA)
!endif
!!! similitude de -45 de centre A de rapport rac(2)
!if $sim=simm45
  xC=!exec maxima $xB + ($yB) - ($yA)
  yC=!exec maxima -$xB + ($yB) + ($xA)
!endif
!!! rotation de 60 de centre A
!if $sim=rotp60
  xC=!exec maxima ((1/2)*$xA + (1/2)*$xB + (sqrt(3)/2)*$yA - (sqrt(3)/2)*$yB)
  yC=!exec maxima (-(sqrt(3)/2)*$xA + (sqrt(3)/2)*$xB + (1/2)*$yA + (1/2)*$yB)
!endif
!!! rotation de -60 de centre A
!if $sim=rotm60
  xC=!exec maxima ((1/2)*$xA + (1/2)*$xB - (sqrt(3)/2)*$yA + (sqrt(3)/2)*$yB)
  yC=!exec maxima ((sqrt(3)/2)*$xA - (sqrt(3)/2)*$xB + (1/2)*$yA + (1/2)*$yB)
!endif
!!! rotation de 30 de centre A
!if $sim=rotp30
  xC=!exec maxima ((1 - sqrt(3)/2)*$xA + (sqrt(3)/2)*$xB + (1/2)*$yA - (1/2)*$yB)
  yCmaxima=!exec maxima (-(1/2)*$xA + (1/2)*$xB + (1-sqrt(3)/2)*$yA + (sqrt(3)/2)*$yB)
!endif
!!! rotation de -30 de centre A
!if $sim=rotm30
  xC=!exec maxima ((1 - sqrt(3)/2)*$xA + (sqrt(3)/2)*$xB - (1/2)*$yA + (1/2)*$yB)
  yC=!exec maxima ((1/2)*$xA - (1/2)*$xB + (1 - sqrt(3)/2)*$yA + (sqrt(3)/2)*$yB)
!endif
!!! similitude de +60 de centre A de rapport 1/2
!if $sim =simp60
  xC=!exec maxima ((3/4)*$xA + (1/4)*$xB + (sqrt(3)/4)*$yA - (sqrt(3)/4)*$yB)
  yC=!exec maxima (-(sqrt(3)/4)*$xA + (sqrt(3)/4)*$xB + (3/4)*$yA + (1/4)*$yB)
!endif
!!! similitude de -30 de centre A de rapport rac(3)/2
!if $sim=simm30
  xC=!exec maxima ((1/4)*$xA + (3/4)*$xB - (sqrt(3)/4)*$yA + (sqrt(3)/4)*$yB)
  yC=!exec maxima ((sqrt(3)/4)*$xA - (sqrt(3)/4)*$xB + (1/4)*$yA + (3/4)*$yB)
!endif
!!!! Calculs des distances AB, AC et BC
repAB=!exec maxima (($xB - ($xA))^2 + ($yB - ($yA))^2)
repAB_=!exec maxima (sqrt($repAB))
!if ^ isin $repAB_
  repAB=sqrt($repAB)
!else
  repAB=$repAB_
!endif
repAC=!exec maxima ($xC - ($xA))^2 + ($yC - ($yA))^2
repAC_=!exec maxima (sqrt($repAC))
!if ^ isin $repAC_
  repAC=sqrt($repAC)
!else
  repAC=$repAC_
!endif
repBC=!exec maxima ($xC - ($xB))^2 + ($yC - ($yB))^2
repBC_=!exec maxima (sqrt($repBC))
if ^ isin $repBC_
  repBC=sqrt($repBC)
!else
  repBC=$repBC_
!endif
!!!! Calculs des coordonnées des autres points
repxI=!exec maxima ($xB + ($xC))/2
repyI=!exec maxima ($yB + ($yC))/2
repxD=!exec maxima $xA + ($xC) - ($xB)
repyD=!exec maxima $yA + ($yC) - ($yB)
repxE=!exec maxima $xB + ($xC) - ($xA)
repyE=!exec maxima $yB + ($yC) - ($yA)
repxF=!exec maxima $xB + ($xA) - ($xC)
repyF=!exec maxima $yB + ($yA) - ($yC)
repxG=!exec maxima ($xB + ($xC) + ($xA))/3
repyG=!exec maxima ($yB + ($yC) + ($yA))/3
repxH=!exec maxima ($repxD + ($repxE) + ($repxF))/3
repyH=!exec maxima ($repyD + ($repyE) + ($repyF))/3

!!!! Cadre du dessin
insdraw_size=300,300
!!!! Calcul du range
xmax=!exec pari vecmax([$xA,$xB, $[$xC], $[$repxD], $[$repxE], $[$repxF]])
ymax=!exec pari vecmax([$yA,$yB, $[$yC], $[$repyD], $[$repyE], $[$repyF]])
xmin=!exec pari vecmin([$xA,$xB, $[$xC], $[$repxD], $[$repxE], $[$repxF]])
ymin=!exec pari vecmin([$yA,$yB, $[$yC], $[$repyD], $[$repyE], $[$repyF]])
dmax=!exec pari vecmax([$ymax - ($ymin),$xmax - ($xmin)])
dmax=!exec pari (floor($dmax) + 3)
xmin=!exec pari (floor($xmin) - 1)
xmax=$[$xmin + ($dmax)]
ymin=!exec pari (floor($ymin) - 1)
ymax=$[$ymin + ($dmax)]

!!!! LES PIXELS SONT DEFINIS DANS DRAW; ICI X VA DE  0 A 800 DE GAUCHE A DROITE
!!!! ET Y VA DE 0 A 800 DE HAUT EN BAS

dessin1=xrange $xmin, $xmax\
yrange $ymin, $ymax\
parallel $xmin, $ymin, $xmin, $ymax,1,0, $[$xmax - ($xmin) + 1], grey\
parallel $xmin, $ymin, $xmax, $ymin,0,1, $[$ymax - ($ymin) + 1], grey\
hline 0,0,black\
vline 0,0,black\
segments black,0.7,0.3,1,0\
segments black,0.7,-0.3,1,0\
segments black,0.3,0.7,0,1\
segments black,-0.3,0.7,0,1\
!!arrow 0,0,1,0,10, black\
!!arrow 0,0,0,1,10, black\
text blue,$[$xA+0.3],$[$yA+0.3],,A\
text blue,$[$xB+0.3],$[$yB+0.3],,B\
text blue,$[$xC+0.3],$[$yC+0.3],,C\
segments blue,$xA,$yA,$xB,$yB\
segments blue,$xA,$yA,$xC,$yC\
segments blue,$xC,$yC,$xB,$yB\
fcircle $xA,$yA,5,red\
fcircle $xB,$yB,5,red\
fcircle $xC,$yC,5,red

dessin2=$dessin1

dessin3=$dessin2\
text blue,$[$repxI+0.3],$[$repyI+0.3],,I\
fcircle $repxI,$repyI,5,red

dessin4=$dessin3\
segments blue,$xA,$yA,$repxE,$repyE\
text blue,$[$repxE+0.3],$[$repyE+0.3],,E\
fcircle $repxE,$repyE,5, red

dessin5=$dessin4\
segments blue,$xB,$yB,$repxE,$repyE\
segments blue,$xC,$yC,$repxE,$repyE

dessin6=$dessin5\
segments blue,$xC,$yC,$repxD,$repyD\
segments blue,$repxD,$repyD,$xA,$yA\
text blue,$[$repxD+0.3],$[$repyD+0.3],,D\
fcircle $repxD,$repyD,5, red

dessin7=$dessin6\
segments blue,$repxD,$repyD,$repxF,$repyF\
text blue,$[$repxF+0.3],$[$repyF+0.3],,F\
fcircle $repxF,$repyF,5,red

dessin8=$dessin7\
segments green,$repxD,$repyD,$xB,$yB\
text blue,$[$repxG+0.3],$[$repyG+0.3],,G\
fcircle $repxG,$repyG,5,red

!!! les points G et H sont confondus ; [FC] médiane de DEF
dessin9=$dessin8\
segments green,$repxF,$repyF,$xC,$yC

!!! Question-réponse - feedback
!reset question reponse feedback
message=Entrer les résultats puis cliquez sur <span class="tt">$name_validate</span> :
!reset affsco
!!! Réponse de l'utilisateur
!reset xI yI xD yD xE yE xF yF xG yG xH yH nattri natqua dAB dAC dBC

status=waiting
!! wims_module_log=$cmd
wims_module_log=$cmd mode $mode
