#if defined TARGET_traduction
# define TITRE Traduction d'expressions à calculer
#endif
#if defined TARGET_resistances
# define TITRE Résistances en dérivation
#endif
#if defined TARGET_moyenne
# define TITRE Moyenne
#endif
#if defined TARGET_depenses
# define TITRE Dépenses
#endif
#if defined TARGET_rebond
# define TITRE Rebond
#endif
#if defined TARGET_proprietaire
# define TITRE Propriétaire
#endif




