!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes

<div class="field box">
<p>Pour les exercices suivi d'un #, vous pouvez choisir de guider les élèves en imposant la méthode.</p>
<strong>Exercice guidé&nbsp;:</strong>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm1 list 1,2 prompt oui ( par défaut ),non
</ul>
</div>

<div class="field box">
<strong>Choix de la méthode ( méthode guidée ou seulement dans la solution )&nbsp;:</strong>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio confparm2 list 1,2,3 prompt en calculant la quantité pour une part ( par défaut ), en utilisant les proportions, en utilisant un tableau de proportionnalité
</ul>
</div>


