!read language lang/names
!header

<div>
<b>$module_title</b> $name_intro.
</div>

!form new

!set liste=orth, paral
!set mode=$liste
!set proj=1
!set diff=1
<fieldset class="property_fields">
<legend>$wims_name_setup</legend>
<ul><li>
<label for="proj">$name_instruction1</label>
!formselect proj list 1,2,3 prompt $name_list
<label for="mode">$name_instruction2</label>
!formselect mode list $liste prompt \
$name_list2
.
</li><li>
$name_level:
!formradio diff list  1,3,4,5 prompt 1,2,3,4
($name_level_help.)
</li></ul>
</p>
<input type="hidden" name="module" value="$module" />
!set wims_ref_class=wims_button
<p class="wimscenter"><input type="submit" value="$wims_name_work"></p>
</fieldset>
!formend
!tail
