#if defined TARGET_expression4 || defined TARGET_droite1 || defined TARGET_expression4 || defined TARGET_droite2
# if defined TARGET_expression4
\author{Joachim,Yameogo; Véronique, Royer}
\email{royer.veronique@orange.fr}
# endif
# if defined TARGET_droite1
\author{Joachim,Yameogo}
\email{yameogo@math.unice.fr}
# endif
# if defined TARGET_droite2
\author{Frederic,Pitoun;Véronique, Royer}
# endif
#else
\author{Véronique, Royer}
\email{royer.veronique@orange.fr}
#endif
