#if defined TARGET_droite1 || defined TARGET_droite2 || defined TARGET_droite3
# define TITRE Étude de droite
#endif
#if defined TARGET_expression1 || defined TARGET_expression2 || defined TARGET_expression3 || defined TARGET_expression4 || defined TARGET_expression5 || defined TARGET_expression6 || defined TARGET_expression7
# define TITRE Expressions
#endif
#if defined TARGET_signe1 || defined TARGET_signe2 || defined TARGET_signe3 || defined TARGET_signe4 || defined TARGET_signe5
# define TITRE Étude de signe
#endif
#if defined TARGET_terminologie1 || defined TARGET_terminologie2 || defined TARGET_terminologie3
# define TITRE Terminologie
#endif
