#include "lang_title_fr.inc"

#if defined TARGET_droite1 || defined TARGET_expression1 || defined TARGET_signe1 || defined TARGET_terminologie1
# define NUM 1
#endif
#if defined TARGET_droite2 || defined TARGET_expression2 || defined TARGET_signe2 || defined TARGET_terminologie2
# define NUM 2
#endif
#if defined TARGET_droite3 || defined TARGET_expression3 || defined TARGET_signe3 || defined TARGET_terminologie3
# define NUM 3
#endif
#if defined TARGET_expression4 || defined TARGET_signe4
# define NUM 4
#endif
#if defined TARGET_expression5 || defined TARGET_signe5
# define NUM 5
#endif
#if defined TARGET_expression6
# define NUM 6
#endif
#if defined TARGET_expression7
# define NUM 7
#endif

\title{TITRE NUM}
