!if $lang iswordof it en es fr nl
  !set datalang=$lang
!else
  !set datalang=en
!endif
!set n=!recordcnt src/data_$datalang
!reset objlist
!for i=1 to $n
  !set l=!record $i of src/data_$datalang
  !set l=!line 1 of $l
  !set objlist=!append item $l to $objlist
!next i

<tr><th>
!if $datalang=it
  Tipo di oggetti:
!endif
!if $datalang=es
  Tipos de objetos:
!endif
!if $datalang=fr
  Type d'objets
!endif
!if $datalang=en
  Type of objects:
!endif
!if $datalang=nl
  Soorten objecten:
!endif
</th><td>
!formselect confparm1 from 1 to $n prompt $objlist
</td></tr>
<tr><th>
!if $datalang=it
  Tipo di operazioni:
  !set oplist=solo somme, somme e prodotti, prodotti e somme, solo prodotti
!endif
!if $datalang=es
  Tipos de operaciones:
  !set oplist=solo sumas, sumas y productos, productos y sumas, solo productos
!endif
!if $datalang=fr
  Type d'opérations:
  !set oplist=Sommes partout, Sommes et produits, Produits et sommes, Produits partout
!endif
!if $datalang=en
  Type of operations:
  !set oplist=All-sums,Sums and products,Products and sums,All-products
!endif
!if $datalang=nl
  Soorten bewerkingen:
  !set oplist=alleen optellen,optellen en vermenigvuldigen,vermenigvuldigen en optellen, alleen vermenigvuldigen
!endif
</th><td>
!formselect confparm2 from 1 to 4 prompt $oplist
</td></tr>
