!header
!read Exindex
!if $lang=it
  Questo modulo può essere considerato un esercizio o un gioco, ma in
  ogni caso costituisce uno strumento importante per fare pratica con
  le operazioni aritmetiche. Il compito di inserire i numeri nella tabella
  costringe a effettuare calcoli mentali veloci di somme e prodotti.
  <p>
  A seconda delle diverse configurazioni, può essere adatto per allievi
  dalla scuola primaria (numeri interi e decimali, positivi e negativi),
  al liceo e oltre (radici, numeri complessi, classi di resto). Le tavole
  grandi (3x5 o 4x5) possono costituire sfide molto avanzate.
  </p><p>
  La possibilità di selezionare i prodotti, permette di fare pratica con
  le proprietà della fattorizzazione.
  </p><p>
  Buona fortuna!
  </p>
  !goto end
!endif
!if $lang=es
  Este módulo puede ser considerado como un ejercicio o un juego, pero es una herramienta importante de entrenamiento
  para realizar operaciones aritméticas. Cuando ingrese los números en la tabla,
  está obligado a calcular mental y rápidamente sus sumas y productos.
  <p>
  Con distintas configuraciones, los ejercicios pueden ser adaptados para estudiantes
  desde nivel de escuela primaria (números enteros y decimales, positivos y negativos),
  hasta nivel de liceo o superior (raíces, números complejos, clases modulares). Y las tablas de gran tamaño (3x5
  o 4x4) pueden ser bastante desafiantes.
  </p><p>
  El poder seleccionar los productos, permite practicar la propiedad
  de factorización.
  </p><p>
  ¡Buena suerte!
  </p>
  !goto end
!endif
!if $lang=fr
  On peut le considérer comme un exercice ou un jeu, mais
  c'est un important outil pour l'entrainement sur les opérations
  arithmétiques. En cherchant à placer les nombres dans le tableau, vous êtes
  obligé de calculer mentalement et rapidement leurs sommes, produits, etc.
  <p>
  Et selon la configuration, l'exercice peut convenir aux élèves du primaire
  (nombres positifs ou relatifs, décimaux) au lycée ou davantage (racines,
  nombres complexes, nombres modulaires). Et les tableaux de grande dimension
  (3x5 ou 4x4) peuvent
  être de véritables défis.
  </p><p>
  N'oubliez pas non plus le cas de produits, qui aide à comprendre la
  factorisation.
  </p><p>
  Bon courage !
  </p>
  !goto end
!endif
!if $lang=nl
  Je kunt deze module inzetten als een spelletje of als een oefening.
  In beide gevallen is deze module een krachtig hulpmiddel bij het
  leren rekenen.
  Voor het invullen van getallen in de tabel, wordt
  zeer snel rekenwerk vereist
  <p>
  Met de diverse instellingen, kunnen de sommen worden gebruikt door
  leerlingen van af dee lagere school (optellen,aftrekken) tot de hogere klassen
  van de middelbare school.
  </p><p>
  Veel plezier !!
  </p>
  !goto end
!endif
One may take it as an exercise or a game, but it is an important training tool
for arithmetic operations. When trying to place the numbers into the table,
you are forced to mentally compute their sums and products rapidly.
<p>
And with different configurations, the exercises may fit students from
primary schools (positive or relative numbers, decimals) to senior high
school or even more (roots, complex numbers, modular numbers). And the large size tables (3x5
or 4x4) may become very challenging.
</p><p>
Don't forget the case of products neighther, which helps you to understand
the factorization.
</p><p>
Bon courage!
</p>

:end
!read oef/intromenu.phtml
!tail
