!header
!read language lang/names

!read present.phtml
<hr />

!if $status=waiting
  !if $error!=$empty
    <div class="wims_alertmsg">
    !read msg.phtml
    </div>
  !endif
  !read form.phtml
  <div class="wimscenter">
  !set wims_ref_class=wims_button wims_secondary_button
  !href exo_Renew
  </div>
  !if $bestdiff<1
    ($name_giveupnote)
  !endif
!else
  !if $error!=$empty
    <div class="wims_alertmsg">
     !read msg.phtml
    </div>
  !endif
  !read answer.phtml
  <div class="wimscenter">
  !set wims_ref_class=wims_button
  !href exo_Renew
  </div>
!endif

:end
!tail
