#if defined TARGET_pllsec2
#define TITLE_it Incidenti o parallele? (2)
#endif
#if defined TARGET_equ_dr0
#define TITLE_it Equazione esplicita
#endif
#if defined TARGET_secnico
#define TITLE_it Rette incidenti
#endif
#if defined TARGET_equ_dr2
#define TITLE_it Equazione di rette: interpretazione grafica
#endif
#if defined TARGET_equ_dr4
#define TITLE_it Retta passante per due punti
#endif
#if defined TARGET_ordonnee
#define TITLE_it Trovare l'ordinata di un punto
#endif
#if defined TARGET_para2
#define TITLE_it Equazione della pararallela a una retta
#endif
#if defined TARGET_sys3
#define TITLE_it Sistema 3x3
#endif
#if defined TARGET_sys3_app
#define TITLE_it Sistemi (problema)
#endif
#if defined TARGET_equdroitevoc
#define TITLE_it Equazione della retta - vocabolario
#endif
#if defined TARGET_equ_dr1
#define TITLE_it Equazione di rette e vettori direttori
#endif
#if defined TARGET_syst2
#define TITLE_it Sistema 2x2 (soluzioni intere)
#endif
#if defined TARGET_eqgeqr
#define TITLE_it Equazione esplicita e equazione cartesiana
#endif
#if defined TARGET_equa_red
#define TITLE_it Equazioni esplicite e implicita
#endif
#if defined TARGET_parallele
#define TITLE_it Equazioni cartesiane e parallelismo
#endif
#if defined TARGET_abscisse
#define TITLE_it Trovare l'ascissa di un punto
#endif
#if defined TARGET_syst1
#define TITLE_it Sistema 2x2
#endif
#if defined TARGET_equ_dr5
#define TITLE_it Parallela ad una retta
#endif
#if defined TARGET_pointdroite
#define TITLE_it Punto su una retta
#endif
#if defined TARGET_equ_dr_mcd
#define TITLE_it Equazione di una retta
#endif
#if defined TARGET_pointsentiers
#define TITLE_it Punti a coordinate intere
#endif
