#if defined TARGET_pllsec2
#define TITLE  Sécantes ou parallèles ? (2)
#endif
#if defined TARGET_equ_dr0
#define TITLE Equation réduite
#endif
#if defined TARGET_secnico
#define TITLE Droites sécantes
#endif
#if defined TARGET_equ_dr2
#define TITLE Equation de droites : lecture graphique
#endif
#if defined TARGET_equ_dr4
#define TITLE Droite passant par deux points
#endif
#if defined TARGET_ordonnee
#define TITLE Trouver l'ordonnée d'un point
#endif
#if defined TARGET_para2
#define TITLE Equation de la parallèle à une droite
#endif
#if defined TARGET_sys3
#define TITLE Sytème de trois équations à trois inconnues
#endif
#if defined TARGET_sys3_app
#define TITLE Sytèmes concrets
#endif
#if defined TARGET_equdroitevoc
#define TITLE Equations de droites - vocabulaire
#endif
#if defined TARGET_equ_dr1
#define TITLE Equation de droites et vecteur directeur
#endif
#if defined TARGET_syst2
#define TITLE Système 2x2 (solutions entières)
#endif
#if defined TARGET_eqgeqr
#define TITLE Equation réduite et équation cartésienne
#endif
#if defined TARGET_equa_red
#define TITLE Equations réduites et correspondances
#endif
#if defined TARGET_parallele
#define TITLE Equation cartésienne et parallèles
#endif
#if defined TARGET_abscisse
#define TITLE Trouver l'abscisse d'un point
#endif
#if defined TARGET_syst1
#define TITLE Système 2x2
#endif
#if defined TARGET_equ_dr5
#define TITLE Parallèle à une droite
#endif
#if defined TARGET_pointdroite
#define TITLE  Point d'une droite
#endif
#if defined TARGET_equ_dr_mcd
#define TITLE Equation d'une droite
#endif
#if defined TARGET_pointsentiers
#define TITLE Point à coordonnées entières
#endif
