#if defined TARGET_devel1 || defined TARGET_devel2 || defined TARGET_devel3
#define TITRE Développement d'expression
#endif
#if defined TARGET_factor1 || defined TARGET_factor2 || defined TARGET_factor3 || defined TARGET_factor4 || defined TARGET_factor5
# define TITRE Factorisation d'expression
#endif
#if defined TARGET_fill1deg
# define TITRE Compléter des équations du premier degré
#endif
#if defined TARGET_fill2deg
# define TITRE Compléter des équations carré ou produit
#endif
#if defined TARGET_solquot
# define TITRE Cocher le solution d'une équation
#endif
#if defined TARGET_synth1deg
# define TITRE Synthèse sur le premier degré
#endif
#if defined TARGET_synth2deg
# define TITRE Synthèse sur le deuxième degré
#endif
#if defined TARGET_synthquot
# define TITRE Synthèse sur les équations quotient
#endif
#if defined TARGET_valinterdit
# define TITRE Cocher la valeur interdite
#endif
#if defined TARGET_valinterdit2
# define TITRE Donner la valeur interdite
#endif
#if defined TARGET_valinterdit3
# define TITRE Donner les valeurs interdites
#endif
