#if defined TARGET_devel1 || defined TARGET_devel2
\text{name_question=Développer l'expression&nbsp;}
\text{name_answer=Expression développée}
#endif
#if defined TARGET_devel3
\text{name_question=Simplifier l'expression&nbsp;}
\text{name_answer=Expression simplifiée&nbsp;}
#endif
#if defined TARGET_factor1 || defined TARGET_factor2 || defined TARGET_factor3 || defined TARGET_factor4 || defined TARGET_factor5
\text{name_question=Factoriser l'expression&nbsp;}
\text{name_answer=Expression factorisée&nbsp;}
#endif
#if defined TARGET_factor2
\text{name_inst=Taper,pour }
#endif
#if defined TARGET_factor3
\text{name_inst=L'expression factorisée doit comporter 3 facteurs.}
#endif
#if defined TARGET_factor4
\text{name_question0=Peut-on factoriser l'expression&nbsp;}
\text{name_yesno=Oui,Non}
\text{name_answer2=Factorisation possible}
#endif
#if defined TARGET_factor5

#endif
#if defined TARGET_synthquot
\text{name_head=Equations à résoudre,Solutions,Valeur(s) interdite(s),brouillon}
\text{name_enonce1=Vous devez résoudre successivement 4 équations du deuxième degré&nbsp;}
\text{name_enonce2=S'il y a une solution unique, vous devez renseigner l'ensemble
  \(S\) avec la solution exacte.}
\text{name_enonce3=S'il y a deux solutions, vous devez renseigner l'ensemble
  \(S\) avec les deux solutions exactes séparées par une virgule.}
\text{name_choix=une solution,deux solutions}
\text{name_answer=Équation}
#endif
