<p>
!if $lang=it
 Ricordiamo la convenzione utilizzata per la scrittura dei numeri in base $(confparm4[1;]): 
!else
 On rappelle les usages de la base $(confparm4[1;]) :
!endif
</p>
<ul>
  <li>
!if $lang=it
 il simbolo \(0\) ha il significato abituale nel sistema di numerazione posizionale.
!else
 le symbole \(0) a l'usage habituel dans les systèmes de numérations de position.
!endif
  </li>
 <li>
  !if $(confparm4[1;])>2
    !if $lang=it
      I primi $[$(confparm4[1;])-1] numeri sono contrassegnati dalle cifre $(confparm4[3;2 to $(confparm4[1;])]) in quest'ordine.
    !else
      Les $[$(confparm4[1;])-1] premiers nombres sont désignés dans l'ordre par
      les symboles $(confparm4[3;2 to $(confparm4[1;])]).
    !endif
  !else
    !if $lang=it
      La quantità 1 è rappresentata dal simbolo $(confparm4[3;2 to $(confparm4[1;])]).
    !else
      La quantité 1 est désignée par le symbole $(confparm4[3;2 to $(confparm4[1;])]).
    !endif
  !endif
 </li>
</ul>
