!default confparm2=2,3,5,12
!default confparm1=2,3,5,12
!default confparm3=1

<tr>
!if $lang=it
 <th>Scelta della base p</th>
!else
 <th>Choix de la base p</th>
!endif
 <td><input type="text" name="confparm1" value="$confparm1"></td>
</tr><tr>
!if $lang=it
 <th>Scelta della base q</th>
!else
 <th>Choix de la base q</th>
!endif
 <td><input type="text" name="confparm2" value="$confparm2"></td>
</tr><tr>
!if $lang=it
 <th>Numero di domande in ogni esercizio</th>
!else
 <th>Nombre de questions par exercice</th>
!endif
 <td>
  !formselect confparm3 list 1,2,3,4,5
 </td>
</tr>
