!header
!read Exindex
!if $lang=it
Questo mudulo raggruppa al momento $exototal esercizi sulla scrittura
posizionale in base p e sul cambio di base da p a q.
<br>
La lista dei valori per p e q può essere definita dal docente
(non può contenere 10).
!else
Ce module regroupe pour l'instant $exototal exercices sur la numération de position
en base p ou les changements de bases de p vers q.
<br>
La liste des valeurs pour p et q peut être définie par l'utilisateur
(elle ne peut pas contenir 10).
!endif

!read oef/$module_language/intromenu.phtml
!tail
