!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices.
<p><b>Niveau européen</b>: A1</p>
<p><b>Tâche :</b> Ton correspondant anglophone vient en France pour
la première fois. Vous ne vous êtes jamais rencontrés.
Décris les membres de ta famille avant son arrivée dans une lettre.
</p><p>
<b>Prérequis</b> : la forme d'une lettre.
</p><p><b>Objectifs</b> :</p>
<ul><li><b>Compétence linguistique</b> :
 Vocabulaire lié à la description des gens (apparence, âge, sentiments).
Grammaire : utilisation des verbes « to be » et « have got »
(formes affirmatives et négatives).
</li>
</ul>
<p><b>Activités de communication langagière :</b></p>
<ul><li><b>Réception</b> : Lire des phrases simples décrivantes des personnes.
		Ecouter la prononciation des mots.
	</li><li>
<b>Production</b> : Ecrire une  lettre simple.
</li></ul>

<p><b>Etapes</b> :</p>
<ul><li>
 Acquisition et réemploi du vocabulaire lié à
 la description des gens (apparence, âge, sentiments)
</li><li>
 Grammaire : utilisation des verbes « to be » et « have got »
 (formes affirmatives et négatives)
</li><li>Repérage et correction des erreurs dans des lettres courtes.
</li><li>Rédaction d'une lettre courte.
</li></ul>

Voici l'ordre conseillé pour les exercices de la séquence:
<ol>
<li>Vocabulary (1)</li>
<li> Vocabulary (2) with sound </li>
<li>Describing people</li>
<li>Le verbe "be" et "have got"</li>
<li>Practice: be/have got </li>
<li>Correct the mistakes in the texts.</li>
<li>Test yourself</li>
<li> Homework</li>
</ol>
!read oef/$module_language/intromenu.phtml
!tail
