!header
!read Exindex
!if $lang=es
  Actualmente, este módulo contiene $exototal ejercicios de estadística.
  !goto tail
!endif
!if $lang=ca
  Actualment, aquest mòdul contè $exototal exercicis d'estadística.
  !goto tail
!endif
!if $lang=it
  Al momento questo modulo contiene $exototal esercizi di statistica.
  !goto tail
!endif
!if $lang=nl
  Deze module bevat -op dit moment- $exototal oefeningen over statistiek.
  !goto tail
!endif
Ce module regroupe pour l'instant $exototal exercices sur les statistiques.

:tail
!read oef/intromenu.phtml
!tail
