
\answer{Box 1}{\(\sh[1])}{type=dragfill}
\answer{Box 2}{\(\sh[2])}{type=dragfill}
\answer{Box 3}{\(\sh[3])}{type=dragfill}
\answer{Box 4}{\(\sh[4])}{type=dragfill}
\answer{Box 5}{\(\sh[5])}{type=dragfill}
\answer{Box 6}{\(\sh[6])}{type=dragfill}
\answer{Box 7}{\(\sh[7])}{type=dragfill}
\answer{Box 8}{\(\sh[8])}{type=dragfill}
\answer{Box 9}{\(\sh[9])}{type=dragfill}
\answer{Box 10}{\(\sh[10])}{type=dragfill}
\answer{Box 11}{\(\sh[11])}{type=dragfill}
\answer{Box 12}{\(\sh[12])}{type=dragfill}
\answer{Box 13}{\(\sh[13])}{type=dragfill}
\answer{Box 14}{\(\sh[14])}{type=dragfill}
\answer{Box 15}{\(\sh[15])}{type=dragfill}
\answer{Box 16}{\(\sh[16])}{type=dragfill}

