
\answer{Box 1}{\sh[1]}{type=algexp}
\answer{Box 2}{\sh[2]}{type=algexp}
\answer{Box 3}{\sh[3]}{type=algexp}
\answer{Box 4}{\sh[4]}{type=algexp}
\answer{Box 5}{\sh[5]}{type=algexp}
\answer{Box 6}{\sh[6]}{type=algexp}
\answer{Box 7}{\sh[7]}{type=algexp}
\answer{Box 8}{\sh[8]}{type=algexp}
\answer{Box 9}{\sh[9]}{type=algexp}
\answer{Box 10}{\sh[10]}{type=algexp}
\answer{Box 11}{\sh[11]}{type=algexp}
\answer{Box 12}{\sh[12]}{type=algexp}
\answer{Box 13}{\sh[13]}{type=algexp}
\answer{Box 14}{\sh[14]}{type=algexp}
\answer{Box 15}{\sh[15]}{type=algexp}
\answer{Box 16}{\sh[16]}{type=algexp}

