#if defined TARGET_trouvecont1 || defined TARGET_trouvecont2 || defined TARGET_trouvecont3 || defined TARGET_trouvecont4
# define TITLE Rendre une fonction continue
#endif
#if defined TARGET_questcont1 || defined TARGET_questcont2 || defined TARGET_questcont3 || defined TARGET_questcont4
# define TITLE La fonction est-elle continue
#endif
#if defined TARGET_contdef1 || defined TARGET_contdef2
# define TITLE Pourquoi une fonction est continue
#endif
#if defined TARGET_tvidicho
# define TITLE TVI: Méthode de dichotomie
#endif
#if defined TARGET_tviscan
# define TITLE TVI: Méthode de balayage
#endif
#if defined TARGET_racinen1 || defined TARGET_racinen2
# define TITLE La fonction racine n-ième
#endif
