!header
!read Exindex

!if $lang iswordof it

  Questo modulo raggruppa al momento $exototal esercizi sull'enumerazione, le percentuali e la probabilità, utilizzabile ad esempio
nelle ultime classi di liceo.

  !goto end

!endif
  
  Ce module regroupe pour l'instant $exototal exercices sur
le dénombrement, les pourcentages et les probabilités par exemple pour la classe de Première.


:end

!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=yes

!read oef/$module_language/intromenu.phtml
!tail
