!!!! This file can contain contents which go after the exercicse list in the intro.
!!Model for some configuration parameters. Uncomment if necessary

!!<tr>
!!<td>
!!<p>Les questions portent sur :
!! !formcheckbox confparm1 list circle,ellipse prompt des cercles,des ellipses
!!</td>
!!</tr>
<tr>
<td>
<p>L'énoncé peut donner :
!formcheckbox confparm2 from 1 to 7 prompt une équation<br>,le centre et les demi-axes (ou le rayon)<br>,le centre et les axes (ou le diamètre)<br>,les sommets (ou 2 points diamétralement opposés du cercle)<br>,une représentation paramétrique<br>,un dessin montrant les sommets (ou 4 points du cercle)<br>,un dessin montrant le centre et les demi-axes (ou le rayon)
</td>
</tr>
<tr>
<td>
<p>La question peut demander :
!formcheckbox confparm3 from 1 to 5 prompt une équation<br>,le centre et les demi-axes (ou le rayon)<br>,le centre et les axes (ou le diamètre)<br>,les sommets (ou un point diamétralement opposé à un point du cercle)<br>,une représentation paramétrique<br>
</td>
</tr>
