!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les équations des cercles et des ellipses.
<br>En combinant les différentes options possibles, cela fait plus d'une trentaine d'exercices différents...
<p> Par exemple : </p>
<ul>
<li>connaissant une équation, donner les éléments géométriques (ou inversement)</li>
<li>passer d'un type d'équation à un autre</li>
<li>à partir de deux points diamétralement opposés, retrouver une équation (ou inversement)</li>
<li>...</li>
</ul>



!default confparm1=circle,ellipse
!default confparm2=1,2,3,4,5,6,7
!default confparm3=1,2,3,4,5,6,7

!read oef/intromenu.phtml
!tail
