!header
!read Exindex
       <p>
       Ce module regroupe pour l'instant $exototal exercices 
       sur le thème des équations de droites planes. Ces exercices sont 
       du  niveau seconde. Ils ont été conçus dans le but de donner 
       aux enseignants des classe de seconde, des exemples d'exercices 
       pouvant servir dans le cadre de l'<b>aide individualisée</b>. 
       </p>

!read oef/$module_language/intromenu.phtml
!tail
