!header
!read Exindex
!if $lang=nl
  Deze module bevat op dit moment $exototal oefeningen over elementaire combinatoriek
  van H6 to U3 niveau.
  !goto end
!endif
!if $lang=en
  This module contains for the time being
  $exototal numerical exercises on elementary combinatorics.
  !goto end
!endif
Ce module regroupe pour l'instant $exototal exercices numériques sur la combinatoire
élémentaire.

:end
!read oef/intromenu.phtml
!read related.phtml combinatoire
!tail

