!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur le thème des plantes aromatiques.
Les exercices permettent de faire le point sur le cycle de vie de deux plantes aromatiques,
l'une annuelle et l'autre vivace.
Un exercice de reconnaissance permet de faire le point sur quelques plantes
aromatiques emblématiques.
Enfin un dernier exercice permet de faire le point sur des mots clés associés
aux plantes aromatiques et à leurs utilisations.

!read oef/intromenu.phtml
!tail
