!header
!read Exindex

!if $lang iswordof it
  Questo modulo contiene attualmente $exototal esercizi sul confronto di numeri.
!goto end 
!endif
!if $lang iswordof es
  Este módulo agrupa por el momento $exototal ejercicios sobre comparación de números.
!goto end 
!endif
  Ce module regroupe pour l'instant $exototal exercices sur les comparaisons de nombres.

:end
!read oef/$module_language/intromenu.phtml
!tail
