!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les probabilités. 
L'ensemble de ses exercices aborde les notions sur les arbres de probabilités, les tableaux à double entrée
 et les diagrammes de Venn (A venir):
<ul><li>Don du sang</li>
<li>Enquête de satisfaction</li>
<li>Bon de réduction</li>
<li>Lunettes 3D</li>
</ul>

Une approche pragmatique est réalisée et les thèmes suivants
 sont abordés :
<ul>
<li>Prévention, Santé et Sécurité</li>
<li>Vie économique et professionnelle</li>
<li>Vie socilae et loisirs</li>
</ul>

Ils ont été réalisés pour un niveau de Terminal BAC PRO section tertiaire.

!read oef/intromenu.phtml
!tail
