#if defined TARGET_deg1 || defined TARGET_fracx1  || defined TARGET_invx || defined TARGET_invx2
\text{name_statement=Résoudre l'inégalité,avec la condition préalable}
\text{name_objectif=L'objectif de l'exercice est de transformer l'inégalité donnée en une
  inégalité équivalente dont la partie gauche est,
  et dont la partie droite est une constante.}
\text{name_and=et}
#endif
#if defined TARGET_lindeduc
\text{name_statement=Soit, un nombre,avec,Montrez}
#endif
#if defined TARGET_majsqr1
\text{name_statement= Soit,un nombre réel avec,Montrez}
\text{name_help=Ceci est un exercice étape par étape. Choisissez une méthode pour chaque
  étape et puis suivre les instructions, l'ordinateur fera le reste pour
  avancer dans le raisonnement.}
\text{name_hint=Vous pouvez certainement séparer la démonstration en deux cas suivant le signe de,
  mais vous devez faire beaucoup d'étapes en faisant cela.,
  Une meilleure solution est de remarquer que,
  est équivalent à,
  ou encore à,
  Cela vous donne-t-il une idée&nbsp;
}
#endif
#if defined TARGET_majsqr1b
\text{name_statement=Soit, un nombre réel avec, Montrez que}
#endif
#if defined TARGET_possqr1 || defined TARGET_possqr2
\text{name_statement=Montrez,pour}
#endif
#if defined TARGET_sum
\text{name_statement= Soit,et, deux nombres réels avec,et,Montrez que}
#endif
#if defined TARGET_transiadd
\text{name_phrase1=la transitivité des inégalités se déduit de la possibilité
  d'ajouter deux inégalités.}
\text{name_phrase2=la possibilité d'ajouter deux inégalités se déduit de la
  transitivité des inégalités.}
\text{name_statement=Vous savez que,Soient donc,Montrez,par les méthodes fournies.}
#endif
#if defined TARGET_xchgmult
\text{name_phrase1=la multiplication d'une inégalité par -1 est la composition
  d'une addition de termes aux deux côtés de l'inégalité et l'échange des
  côtés.}
\text{name_phrase2=l'échange des côtés d'une inégalité est la composition d'une
  addition de termes aux deux côtés de l'inégalité et la multiplication de
  l'inégalité par un nombre.}
\text{name_statement=Vous savez que,
  Transformez donc l'inégalité,
  en,
  par les méthodes fournies}
#endif
