#if defined TARGET_deg1
# define TITRE Inequation of degree 1
#endif
#if defined TARGET_xchgmult
# define TITRE Exchange and mult
#endif
#if defined TARGET_fracx1
# define TITRE Simple fraction I
#endif
#if defined TARGET_invx
# define TITRE Inverse I
#endif
#if defined TARGET_invx2
# define TITRE Inverse II
#endif
#if defined TARGET_lindeduc
# define TITRE Linear deduction
#endif
#if defined TARGET_majsqr1
# define TITRE Upper-bound the square I
#endif
#if defined TARGET_majsqr1b
# define TITRE Upper-bound the square Ib
#endif
#if defined TARGET_possqr1
# define TITRE Positive square I
#endif
#if defined TARGET_possqr2
# define TITRE Positive square II
#endif
#if defined TARGET_transiadd
# define TITRE Transitivity and addition
#endif
#if defined TARGET_sum
# define TITRE Given sum
#endif
