#if defined TARGET_deg1
# define TITRE_fr Inéquation de degré 1
#endif
#if defined TARGET_xchgmult
# define TITRE_fr Échange et mult
#endif
#if defined TARGET_fracx1
# define TITRE_fr Fraction simple I
#endif
#if defined TARGET_invx
# define TITRE_fr Inverse I
#endif
#if defined TARGET_invx2
# define TITRE_fr Inverse II
#endif
#if defined TARGET_lindeduc
# define TITRE_fr Déduction linéaire
#endif
#if defined TARGET_majsqr1
# define TITRE_fr Majorer le carré I
#endif
#if defined TARGET_majsqr1b
# define TITRE_fr Majorer le carré Ib
#endif
#if defined TARGET_possqr1
# define TITRE_fr Carré positif I
#endif
#if defined TARGET_possqr2
# define TITRE_fr Carré positif II
#endif
#if defined TARGET_transiadd
# define TITRE_fr Transitivité et addition
#endif
#if defined TARGET_sum
# define TITRE_fr Somme donnée
#endif
