!! On pose les questions dans ce fichier. D'habitude, c'est par
!! des forms. Voici un exemple de conception de la forme de réponse.

!form reply
  <fieldset>
    <legend>
      !if $reply_cnt=0
        $name_yourreply
      !else
        $name_yourreply2
      !endif
    </legend>
    !for i=1 to $term
      !set c=!char $i of abcdefghijk
      <label for="num$i">\($c)</label>
      = <input size="5" name="num$i" id="num$i" value="$(num$i)" required="required">$ $
    !next i
    <input type="submit" value="$wims_name_send">
  </fieldset>
!formend
