!read language lang/names
!set wims_backslash_insmath=yes
!header

!if $error=robot
  !read msg.phtml
  !goto end
!endif

!! La présentation de l'exercice.
!read present.phtml

!if $status=waiting
  !if $error!=$empty
    <div class="wims_msg alert">
      !read msg.phtml
      <p>$name_again</p>
    </div>
  !else
    !if $cmd=reply
      !read answer.phtml
      <hr style="width:50%">
    !endif
  !endif

  !! La forme de réponse
  !read form.phtml
  <p>
    !set wims_ref_class=wims_button wims_secondary_button
    !href cmd=renew&worksheet=$worksheet&$module_init_parm $name_change
  </p>
!else
  !if $error!=$empty
    <div class="wims_msg alert">
      !read msg.phtml
      <p>$name_again</p>
    </div>
  !endif
  !! L'analyse de réponse
  !read answer.phtml
  <p>
    !set wims_ref_class=wims_button wims_secondary_button
    !href cmd=renew&worksheet=$worksheet&$module_init_parm $name_otherfrac
  </p>
!endif

:end
!tail
