!! This file contains error messages. It will be processed
!! whenever the variable `error' is not empty.

<strong class="wims_warning">$wims_name_Error</strong>

!if empty_data=$error
  $(msg_empty_data[1])
  !set a_=!item $empty_data of a,b,c,d,e,f,g
  \($a_\) $(msg_empty_data[2])
  !exit
!endif

!if bad_data=$error
  $msg_bad_data1
  !set a_=!item $bad_data of a,b,c,d,e,f,g
  \($a_ = $(num$bad_data)\)
  $msg_bad_data2
  !exit
!endif

!if robot=$error
  $msg_robot
  !exit
!endif
