!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur le thème de la biodiversité
des espèces et des écosystèmes. Les exercices A, B et C sont des exercices de reconnaissances
de quelques espèces et d'environnements ce qui permet d'enrichir la culture naturaliste des
élèves. L'exercice D est un QCM permettant de faire le point sur les observations effectuées
dans les exercices A, B et C. L'exercice E portant sur les carctéristiques du biotope est un
QCM qui prend appui sur un graphique, cet exercice permet d'évaluer la capacité à extraire
des informations et à raisonner à partir d'observations. Enfin l'exercice F est un QCM qui permet
aux élèves de mieux cerner les impacts de la variation des conditions du biotope sur la répartition
des espèces et donc sur la variabilité de la biodiversité des espèces dans les environnements.
Cette série d'exercices permet de construire et d'illustrer progressivement des notions écologiques
fondamentales au niveau 2nde.

!read oef/intromenu.phtml
!tail
