!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les pourcentages de pourcentage ou les 
évolutions successives en pourcentages.
Certains exercices laissent une certaine liberté au niveau du choix de la méthode.
On trouve aussi une introduction aux indices de base 100.
!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=

!read oef/intromenu.phtml
!tail
