!! Analyse de réponse dans ce fichier.
<div>
  $name_givenreply
  !for i=1 to $term
    !set i_=!item $i of a,b,c,d,e,f
    \($i_= $(num$i)\)
    !if $i<$term
      ,
    !else
      .
    !endif
  !next i
</div>
<p>$name_verifyreply </p>
<div class="wimscenter">
  \($ans_tex={$ans_num\over $ans_den}.\)
</div>

<p>
!if $diagnostic=0
  $name_analysereply <strong class="oef_indgood">$name_exact</strong>
  !if $reply_cnt=1
    $name_firstattempt
  !else
    $name_otherattempt
  !endif
  $name_score $module_score/10.
!else
  <strong class="oef_indbad">$name_comment</strong>
  $name_nextansw
!endif
</p>
