!read language lang/names
!header
!set wims_backslash_insmath=yes

<p>
$name_intro1
</p><p>
$name_intro2
</p><p>
$name_intro3
</p>
!if $special_parm != expert
  $name_intro_simple
  <ul class="inline">
    <li>
      !href module=$module&cmd=new&term=2&diff=1&integ=0 1
    </li><li>
      !href module=$module&cmd=new&term=2&diff=2&integ=1 2
    </li><li>
      !href module=$module&cmd=new&term=2&diff=4&integ=3 3
    </li><li>
      !href module=$module&cmd=new&term=3&diff=1&integ=1 4
    </li><li>
      !href module=$module&cmd=new&term=3&diff=3&integ=2 5
    </li><li>
      !href module=$module&cmd=new&term=3&diff=4&integ=4 6
    </li><li>
      !href module=$module&cmd=new&term=4&diff=3&integ=3 7
    </li><li>
      !href module=$module&cmd=new&term=5&diff=4&integ=5 8
   </li>
  </ul>
  <div class="formHelp">$name_intro_formhelp</div>

  <p>$name_intro4</p>
  !set wims_ref_class=wims_button wims_secondary_button
  !href cmd=intro&module=$module&special_parm=expert $name_confexpert

!else
  !form new
  <input type="hidden" name="module" value="$module" />
  <p>$name_intro_expert</p>
  <div class="property_fields">
  <fieldset class="field box">
    <legend>$name_intro_numbers</legend>
    !for i = 2 to 5
      <input type="radio" name="term" id="term_$i" value="$i"
      !if $i=2
        checked="checked"
      !endif
      /><label for="term_$i">$i</label> $ $
    !next i
  </fieldset>
  <fieldset class="field box">
    <legend>$name_intro_levels</legend>
    !for i = 1 to 4
      <input type="radio" name="diff" id="diff_$i" value="$i"
      !if $i=1
        checked="checked"
      !endif
      /><label for="diff_$i">$i</label> $ $
    !next i
  </fieldset>
  <fieldset class="field box">
    <legend>$name_intro_zone</legend>
    !for i = 0 to 5
      <input type="radio" name="integ" id="integ_$i" value="$i"
      !if $i=0
        checked="checked"
      !endif
      /><label for="integ_$i">$[$i+1]</label> $ $
    !next i
  </fieldset>
  </div>
  <div class="wimscenter">
    <input type="submit" value="$wims_name_work" />
  </div>
  !formend

  <p>$name_intro5</p>
  !set wims_ref_class=wims_button wims_secondary_button
  !href cmd=intro&module=$module $name_confsimple

!endif expert

!tail
