!! Ce fichier présente la question à résoudre.
!set alist=\(a\)\
\(a\) $name_and \(b\)\
\(a\), \(b\) $name_and \(c\)\
\(a\), \(b\), \(c\) $name_and \(d\)\
\(a\), \(b\), \(c\), \(d\) $name_and \(e\)\
\(a\), \(b\), \(c\), \(d\), \(e\) $name_and \(f\)

$name_present1
!item $term of $name_numberlist
$ $name_fractions:
<div class="wimscenter">
\(\Large{{$numer\over$denom}=$eq_tex }\)
</div>
$name_question1
!line $term of $alist
$ $name_question2
