<tr><td align="center">Choix du type de réaction</td>
 <td>
   <select name="confparm1">
    <option value="acide-metal0">
     Attaque d'un métal en milieu acide (l'acide est en excès)
    </option>
    <option value="acide-metal1">
     Attaque d'un métal en milieu acide (cas général,acide propre)
    </option>
    <option value="acide-metal2">
     Attaque d'un métal en milieu acide (cas général,acide usagé)
    </option>
   </select>
 </td>
</tr>
