#if defined TARGET_tablediner1 || defined TARGET_tablediner2 || defined TARGET_tablediner3 || defined TARGET_tablediner4
# define TITRE_en Dinner table
#endif
#if defined TARGET_Regtriangle
# define TITRE_en Triangles in polygon
#endif
#if defined TARGET_boiteslettres
# define TITRE_en Letterboxes
#endif
#if defined TARGET_bonbon
# define TITRE_en Sweets
#endif
#if defined TARGET_Doublelangue
# define TITRE_en Double languages
#endif
#if defined TARGET_Hotellampe
# define TITRE_en Lamps in a hotel
#endif
#if defined TARGET_triangline
# define TITRE_en Triangles on lines
#endif
#if defined TARGET_triangle
# define TITRE_en Triangles
#endif
#if defined TARGET_subsets
# define TITRE_en Subsets
#endif
#if defined TARGET_rectangle
# define TITRE_en Rectangles
#endif
#if defined TARGET_Ordinat1 || defined TARGET_Ordinat2
# define TITRE_en Computer room
#endif
#if defined TARGET_quadriline
# define TITRE_en Quadrilaterals on lines
#endif
#if defined TARGET_nn || defined TARGET_n
# define TITRE_en Binomial coefficients
#endif
#if defined TARGET_partfix
# define TITRE_en Fixed partitions
#endif
#if defined TARGET_busetconducteu
# define TITRE_en Bus and drivers
#endif
#if defined TARGET_committee
# define TITRE_en Commitee of class
#endif
#if defined TARGET_intersection || defined TARGET_intersection2 || defined TARGET_intersection3
# define TITRE_en Intersection points
#endif
#if defined TARGET_posneg
# define TITRE_en Positive negative
#endif
#if defined TARGET_party
# define TITRE_en Handshakes
#endif
#if defined TARGET_couples
# define TITRE_en Couples
#endif
#if defined TARGET_groupement
# define TITRE_en Groups of pupils
#endif
#if defined TARGET_helico
# define TITRE_en Helico
#endif
#if defined TARGET_mots
# define TITRE_en Words
#endif
#if defined TARGET_monom3 || defined TARGET_monom4
# define TITRE_en Monomial
#endif
