#if defined TARGET_tablediner1 || defined TARGET_tablediner2 || defined TARGET_tablediner3 || defined TARGET_tablediner4
# define TITRE_nl Etentje
#endif
#if defined TARGET_Regtriangle
# define TITRE_nl Driehoeken in een polygoon
#endif
#if defined TARGET_boiteslettres
# define TITRE_nl Letters op een leesplank
#endif
#if defined TARGET_bonbon
# define TITRE_nl Verdelen van snoep
#endif
#if defined TARGET_Doublelangue
# define TITRE_nl Twee talen
#endif
#if defined TARGET_Hotellampe
# define TITRE_nl Lampen in een hotel
#endif
#if defined TARGET_triangline
# define TITRE_nl Driehoeken en lijnen II
#endif
#if defined TARGET_triangle
# define TITRE_nl Driehoeken en lijnen I
#endif
#if defined TARGET_subsets
# define TITRE_nl Sous-ensembles
#endif
#if defined TARGET_rectangle
# define TITRE_nl Rechthoeken
#endif
#if defined TARGET_Ordinat1 || defined TARGET_Ordinat2
# define TITRE_nl Computer lokaal
#endif
#if defined TARGET_quadriline
# define TITRE_nl Vierhoeken en lijnen
#endif
#if defined TARGET_nn || defined TARGET_n
# define TITRE_nl Binomiale co&euml;fficienten
#endif
#if defined TARGET_partfix
# define TITRE_nl Fixed partitions
#endif
#if defined TARGET_busetconducteu
# define TITRE_nl Bussen
#endif
#if defined TARGET_committee
# define TITRE_nl Klasse commissie
#endif
#if defined TARGET_intersection || defined TARGET_intersection2 || defined TARGET_intersection3
# define TITRE_nl Snijpunten
#endif
#if defined TARGET_posneg
# define TITRE_nl Positief Negatief
#endif
#if defined TARGET_party
# define TITRE_nl Handenschudden
#endif
#if defined TARGET_couples
# define TITRE_nl Paren
#endif
#if defined TARGET_groupement
# define TITRE_nl Groepen leerlingen
#endif
#if defined TARGET_helico
# define TITRE_nl Helicopters
#endif
#if defined TARGET_mots
# define TITRE_nl Woorden
#endif
#if defined TARGET_monom3 || defined TARGET_monom4
# define TITRE_nl Machtsfunctie
#endif
