
!set cut=!item $askcnt of 0,0,0,3,4,4,4,4
<div class="wimscenter" style="padding:40px;">
!for i=1 to $askcnt
  !if $i=$[$cut+1] or $i=1
    <p>
  !endif
  !for t in a,b,c
    !set t$t=!item $i of $($(t)_list)
  !next t
  !set formula=$tb*x-$ta*y = $tc
  !if $status=waiting
    <span class="equation">
    !href cmd=reply&good=$i \($formula\)
    </span>
  !else
    !if $i=$good and $i!=$real
      <span class="goodequation equation">
    !endif
    !if $i=$real and $i!=$good
      <span class="equation yourequation">
    !endif
    !if $i =$good and $i =$real
      <span class="equation yourequation goodequation">
    !endif
    !if $i !=$good and $i !=$real
      <span class="equation">
    !endif
    \($formula\)
    </span>
  !endif
  !if $i=$cut or $i=$askcnt
    </p>
  !endif
!next i
</div>
