#if defined TARGET_limcomp1 || defined TARGET_limcomp2 || defined TARGET_limcomp3 || defined TARGET_limcomp4
# define TITRE Limites et composition
#endif
#if defined TARGET_compare1 || defined TARGET_compare2
# define TITRE Limite et comparaison
#endif
#if defined TARGET_calcoper6 || defined TARGET_calcoper7 || defined TARGET_calcoper8 || defined TARGET_calcoper9
# define TITRE Opérations sur les limites
#endif
#if defined TARGET_suitefnc
# define TITRE Suite et fonction
#endif
#if defined TARGET_vertical6
# define TITRE Asymptote verticale
#endif
