#if defined TARGET_ajustement
#define TITLE Ajustement
#define TITLE_es Ajuste
#define TITLE_ca Ajust
#define TITLE_it Andamento
#define TITLE_nl Benadering
#endif
#if defined TARGET_histo
#define TITLE Statistiques : Histogrammes
#define TITLE_es Estadística : Histogramas
#define TITLE_ca Estadística : Histogrames
#define TITLE_it Statistica: Istogrammi
#define TITLE_nl Statistiek : Histogram
#endif
#if defined TARGET_repstat
#define TITLE Représentation de séries statistiques
#define TITLE_es Representación de series de datos
#define TITLE_ca Representació de sèries de dades
#define TITLE_it Rappresentazione di serie di dati
#define TITLE_nl Representatie van een serie getallen
#endif

\title{TITLE}
\title_es{TITLE_es}
\title_ca{TITLE_ca}
\title_it{TITLE_it}
\title_nl{TITLE_nl}
