!! Analyse de réponse dans ce fichier.

!if $asktype!=2
 (Jouw keuze wordt getoond <b>in vette letters</b>, 
 en het goede antwoord is <font color=blue>in het blauw</font>.)<p>
!endif

!if $good!=0
 !if $test=yes
 Jazeker, je keuze klopt prima met de lijn.
 !else
 Neen, je hebt de verkeerde lijn uitgekozen.
  
 !endif
!else
 !if $real>0
 Nee hoor,de goede lijn zit wel degelijk tussen de mogelijkheden 

 !else
 Inderdaad, de goede keuze staat niet tussen de keuzes.
 !endif
!endif

!if $test=yes
 <font color=green><b>Goed geantwoord!.</b></font>
!else
 <font color=red><b>Slecht beantwoord!.</b></font>
!endif

!if $status=next
 (Vraag nummer $replycnt uit $repeat)
 <p>
 !href cmd=next doorgaan met de volgende vraag.
 Je moet eerst de $repeat vragen beantwoorden voor dat je een cijfer kent.

!else
 !if $repeat>1
  <p>
  Je hebt een sessie afgerond met $repeat vragen, en een eindscore
 van $module_score uit 10.
 !else
  Eindscore: $module_score uit 10.
 !endif
!endif
<p>

