
!set cut=!item $askcnt of 0,0,0,0,4,4,5,5
!set setbak=$insplot_set
<center>
!set ins_border=2
!for i=1 to $askcnt
 !if $i isin $cut
  <p>
 !endif
 !for t in ba,ca
  !set t$t=!item $i of $($(t)_list)
 !next t
 !set formula=$tba*x-$tca
 !set ins_attr=alt="Choice $i"
 !if $status=waiting
  !href cmd=reply&good=$i
  !insplot [-$range:$range] [-$range:$range] $formula notitle
</a>&nbsp;
 !else
  !set insplot_set=$setbak
  !if $i=$good
   !set insplot_set=$insplot_set;label "Jouw keuze" at -0.9*$range,0.5*$range
  !endif
  !if $i=$real
   !set insplot_set=$insplot_set;label "het goede antwoord" at -0.9*$range,-0.5*$range
  !endif
  !insplot [-$range:$range] [-$range:$range] $formula notitle
&nbsp;
 !endif
</a>&nbsp;
!next i
</center>

