!header
!read defaults
Er zijn vier manieren om een lijn -niet door de oorsprong en niet horizontaal
of verticaal-  in een platvlak te beschrijven
<ul>
<li>door een impliciete vergelijking
<li>een vergelijking met y als functie van x
<li>een vergelijking met x al
s functie van y
<li>een stelsel van parametrische vergelijkigen
</ul>
<p>
!form new
<input type=hidden name=module value=$module>
Deze module geeft je de mogelijkheid om te oefenen met deze verschillende
manieren om lijnen (en hun grafieken) te definieren.
<p>
Deze module kan:
!formselect type from 1 to 3 prompt de grafieken tonen en vragen om de vergelijking,\
	    een vergelijking tonen en vragen de juiste grafiek te herkennen,\
	    de vergelijking geven en vragen de andere omschrijving te herkennen
.
<table border=0>
<tr>
<td>
Je kunt uit diverse soorten vergelijkingen kiezen:
<td>
!set wims_formselect_switch=multiple
!formselect style list 1,3,4,5 prompt systeem van parametrische vergelijkingen,\
	impliciete vergelijkingen,\
	y als functie van x, x als functie van y

</table>
<p>
!set wims_formselect_switch=
De
!formselect askcnt from $askcntmin to $askcntmax 
 vergelijkingen of grafieken worden gepresenteerd als keuzes,
!formselect miss list no,yes prompt altijd met,niet altijd met
het goede antwoord bevatten.
<p>
Een sessie wordt opgebouwd uit
!formselect repeat from $repeatmin to $repeatmax
vragen. 
<small>
(na elke sessie krijg je een cijfer.)
</small>

<p><center><input type=submit value="Aan het Werk">
</center></form>

!read related.phtml lines, graphic choices, equations, parametric equations

!tail

