
!set t_1=parametric

<b>Oefening.</b> We hebben een rechte lijn in het platte vlak.

!if $givtype=2
zoals te zien in de onderstaande figuur.
 <p><center>
 !set ins_attr=alt="Grafiek van de lijn"
 !insplot [-$range:$range] [-$range:$range] ($ba)*x-($ca) notitle
!else
 beschreven door
 !if $givtype=1
 de volgende parametrische vergelijkingen.
  
 !else
 de volgende vergelijkijng.
 !endif
 <p><center><font size=+1>
 !set formula=!line $givtype of x = $a*t+$c1, y = $b*t+$c2\
	\
	$b*x-$a*y = $c\
	y = $ba*x-$ca\
	x = $ab*y+$cb
 !htmlmath $formula
 </font>
!endif
</center> <p>
!if $asktype=2
Welke van de volgende plaatjes correspondeert met deze lijn? Klik op het plaatje
!else
Welke van de volgende $(t_$asktype) vergelijkingen correspondeert met de lijn? klik op het plaatje
!endif
<p>
!read choice.$asktype.phtml
<p>

