#if defined TARGET_corrdistva
# define TITRE Correspondance Distance-Valeur absolue
#endif
#if defined TARGET_deducencad1
# define TITRE Déduction d'encadrement 1
#endif
#if defined TARGET_deducencad2
# define TITRE Déduction d'encadrement 2
#endif
#if defined TARGET_distva
# define TITRE Distance et valeur absolue
#endif
#if defined TARGET_encadinter
# define TITRE Encadrement->Intervalle
#endif
#if defined TARGET_equava
# define TITRE Équation avec deux valeurs absolues
#endif
#if defined TARGET_intuninter
# define TITRE Union et intersection d'intervalles
#endif
#if defined TARGET_repgraphint
# define TITRE Représentation graphique->Intervalle
#endif
#if defined TARGET_resolva1
# define TITRE Résolution avec une valeur absolue
#endif
#if defined TARGET_resolva2
# define TITRE Résolution avec deux valeurs absolues
#endif
#if defined TARGET_transfencad1
# define TITRE Transformation d'encadrement
#endif
#if defined TARGET_transfineg1
# define TITRE Transformation d'inégalité
#endif
#if defined TARGET_vabsinter
# define TITRE Valeur absolue->Intervalle
#endif
#if defined TARGET_vacalcul
# define TITRE Valeur absolue I
#endif

