!read language lang/names
!header
!read defaults

$name_intro
<p>$name_choiceintro</p>

!form new
<input type="hidden" name="module" value="$module" />
<ul>
<li>$name_style:
!formselect atype from $typemin to $typemax prompt $name_prompt
.
</li><li>
$name_level:
!formselect level from $levelmin to $levelmax
.
</li><li>
$name_seance
!formselect repeat from $repeatmin to $repeatmax
$name_questions
<span class="wims_smallremark">
($name_scoreremark)
</span>.
</li></ul>

<div class="wimscenter wimsform"><input type="submit" value="$wims_name_work" />
</div>
!formend

!read related.phtml graphing, polynomials, real_function
!tail
