
!if $type=1
  $name_present1
 <div class="wimscenter">
 !set ins_attr=alt="Graph f"
 !insplot [-$xrange:$xrange] [-$yrange:$yrange] $f notitle
!else
 $name_present2
 <div class="wimscenter">
  \(f(x) = $f\)
!endif
</div>
!if $type=2
 $name_present3
!else
 $name_present4
!endif
!if $ch=1
  \(f\)
!else
 $name_present5
 \( g(x)=$(namelist[$ch])\)
!endif
 ? $name_present6
<div>
!read choice.$type.phtml
</div>
