\text{name_answer=Votre réponse&nbsp;}
#if defined TARGET_cerclerect4
\text{name_question=Quelle est la mesure (en carreaux) du diamètre
  du cercle circonscrit au triangle rectangle ci-dessous.}
#endif
#if defined TARGET_cerclerect5
\text{name_question=Cliquez sur la position du centre du cercle circonscrit au
  triangle rectangle ci-dessous.}
#endif
#if defined TARGET_vocabulaire1 || defined TARGET_vocabulaire2 || defined TARGET_vocabulaire3 || defined TARGET_vocabulaire4
\text{name_enonc=est un triangle rectangle en}
#endif
#if defined TARGET_vocabulaire1 || defined TARGET_vocabulaire3
\text{name_question=Quelle est l'hypoténuse de ce triangle}
#endif
#if defined TARGET_vocabulaire2 || defined TARGET_vocabulaire4
\text{name_question=Quel est le côté adjacent à l'angle}
#endif
#if defined TARGET_vocabulaire5
\text{name_enonce2=L'angle, mesure,degrés}
\text{name_question=Quelle est la mesure en degrés de l'angle}
#endif
#if defined TARGET_formule1 || defined TARGET_formule2 || defined TARGET_formule3 || defined TARGET_formule4 || defined TARGET_formule5
\text{name_question=Compléter l'égalité suivante }
#endif
#if defined TARGET_vocabulaire5 || defined TARGET_formule2 || defined TARGET_formule3 || defined TARGET_formule4 || defined TARGET_formule5
\text{name_enonce=est un triangle rectangle en}
#endif
#if defined TARGET_formule1 || defined TARGET_formule2
\text{name_cote=Côté adjacent à,Hypoténuse,Côté opposé à }
#endif
#if defined TARGET_formule1
\text{name_enonce=est l'un des deux angles aigus d'un triangle rectangle.}
#endif
#if defined TARGET_cerclerect1
 \text{enonce=Le centre du cercle circonscrit à un triangle rectangle est}
 \text{good=le milieu de son hypoténuse}
 \text{bad=le sommet de son angle droit,le milieu du plus petit côté}
#endif
#if defined TARGET_cerclerect2
 \text{enonce=Le rayon du cercle circonscrit à un triangle rectangle mesure}
 \text{good=la moitié de la longueur de son hypoténuse}
 \text{bad=la longueur de son hypoténuse,la longueur du plus petit côté,la moitié de la longueur du plus petit côté}
#endif
#if defined TARGET_cerclerect1 || defined TARGET_cerclerect2 || defined TARGET_cercle1 || defined TARGET_cercle2 || defined TARGET_cercle3 || defined TARGET_cercle4
\text{name_question=Complétez la phrase suivante&nbsp;}
#endif
#if defined TARGET_cercle1
 \text{enonce=Le cercle circonscrit à un triangle est,}
 \text{good=le cercle passant par les trois sommets du triangle}
 \text{bad=le cercle tangent aux trois côtés du triangle,le cercle passant par les milieux des trois côtés du triangle,un cercle contenant le triangle}
#endif
#if defined TARGET_cercle2
 \text{enonce=Les trois médiatrices d'un triangle}
 \text{good=sont toujours concourantes}
 \text{bad=sont parfois concourantes mais pas tout le temps,ne sont jamais concourantes}
#endif
#if defined TARGET_cercle3
 \text{enonce=Le centre du cercle circonscrit à un triangle est le point d'intersection des trois }
 \text{good=médiatrices du triangle}
 \text{bad=médianes du triangle,bissectrices du triangle,hauteurs du triangle,côtés du triangle}
#endif
#if defined TARGET_cercle4
 \text{enonce=En général, pour trouver le centre du cercle circonscrit à un triangle je dois construire }
 \text{good=deux médiatrices du triangle}
 \text{bad=deux médianes du triangle,deux bissectrices du triangle,deux hauteurs du triangle}
#endif
#if defined TARGET_angcalc1
\text{name_question=Quelle touche de la calculette doit-on utiliser&nbsp;}
\text{name_enonce=On désire calculer l'arrondi, de la mesure de l'angle aigu , vérifiant&nbsp;}
#endif
#if defined TARGET_angcalc1 || defined TARGET_angcalc2 || defined TARGET_angcalc3 || defined TARGET_angcalc4 || defined TARGET_angcalc5
\text{name_precision=au degré,au dixième de degré,au centième de degré}
#endif
#if defined TARGET_angcalc2 || defined TARGET_angcalc3 || defined TARGET_angcalc4 || defined TARGET_angcalc5
\text{name_question=Utiliser la calculatrice pour donner l'arrondi, de la mesure de l'angle aigu,vérifiant }
#endif
#if defined TARGET_calcul1 || defined TARGET_calcul2 || defined TARGET_calcul3 || defined TARGET_calcul4 || defined TARGET_calcul5
\text{name_precision=au dixième,au centième,au millième}
#endif
#if defined TARGET_calcul2 || defined TARGET_calcul3 || defined TARGET_calcul4 || defined TARGET_calcul5
\text{name_question=Utiliser la calculatrice pour donner l'arrondi, de}
#endif
#if defined TARGET_calcul1
\text{name_question=Il faut calculer l'arrondi, du cosinus d'un angle de,degrés.,
  Quelle touche de la calculatrice doit-on utiliser&nbsp;}
\text{name_precision=au dixième,au centième,au millième}
#endif
#if defined TARGET_clongueur1 || defined TARGET_clongueur2 || defined TARGET_clongueur3 || defined TARGET_clongueur4 || defined TARGET_clongueur5 || defined TARGET_cangle1 || defined TARGET_cangle2 || defined TARGET_cangle3 || defined TARGET_cangle4 || defined TARGET_cangle5
\text{name_enonce=est un triangle rectangle en}
\text{name_precision=à l'unité,au dixième,au centième}
#endif
#if defined TARGET_cangle1 || defined TARGET_cangle2 || defined TARGET_cangle3 || defined TARGET_cangle4 || defined TARGET_cangle5
\text{name_question=Calculer la mesure de l'angle, arrondie }
#endif
#if defined TARGET_cerclerect3
\text{name_question=Cliquez sur la position du centre du cercle circonscrit
  au triangle rectangle ci-dessous&nbsp;}
#endif
#if defined TARGET_clongueur1 || defined TARGET_clongueur2 || defined TARGET_clongueur3 || defined TARGET_clongueur4 || defined TARGET_clongueur5
\text{name_question=Calculer la longueur du segment, arrondie}
#endif
#if defined TARGET_cocyclique1
\text{name_enonce=est un point du cercle de diamètre,et de centre O. }
\text{name_question=Quelle est la mesure (en carreaux) du segment,tracé en}
\text{name_color=rouge,bleu,vert,violet}
\text{name_carreau=carreaux}
#endif
#if defined TARGET_cocyclique4 || defined TARGET_cocyclique5
\text{name_enonce=est un point du cercle de diamètre,distinct de, et}
#endif
#if defined TARGET_cocyclique4
\text{name_question=Que représente le segment , pour le triangle}
\text{name_instruction=Vous ne devez taper qu'un seul mot.}
\text{\name_rep=Hypoténuse}
#endif
#if defined TARGET_cocyclique5
\text{name_question=Quelle est la mesure en degrés de l'angle}
#endif
