#include "lang_title_fr.inc"

#if defined TARGET_cangle1 || defined TARGET_cercle1 || defined TARGET_cerclerect1 || defined TARGET_calcul1 || defined TARGET_angcalc1 || defined TARGET_clongueur1 || defined TARGET_vocabulaire1 || defined TARGET_formule1 || defined TARGET_cocyclique1 || defined TARGET_clongueur1
# define NUM 1
#endif
#if defined TARGET_cangle2 || defined TARGET_cercle2 || defined TARGET_cerclerect2 || defined TARGET_calcul2 || defined TARGET_angcalc2 || defined TARGET_clongueur2 || defined TARGET_vocabulaire2 || defined TARGET_formule2 || defined TARGET_cocyclique2 || defined TARGET_clongueur2
# define NUM 2
#endif
#if defined TARGET_cangle3 || defined TARGET_cercle3 || defined TARGET_cerclerect3 || defined TARGET_calcul3 || defined TARGET_angcalc3 || defined TARGET_clongueur3 || defined TARGET_vocabulaire3 || defined TARGET_formule3 || defined TARGET_cocyclique3 || defined TARGET_clongueur3
# define NUM 3
#endif
#if defined TARGET_cangle4 || defined TARGET_cercle4 || defined TARGET_cerclerect4 || defined TARGET_calcul4 || defined TARGET_angcalc4 || defined TARGET_clongueur4 || defined TARGET_vocabulaire4 || defined TARGET_formule4 || defined TARGET_cocyclique4 || defined TARGET_clongueur4
# define NUM 4
#endif
#if defined TARGET_cangle5 || defined TARGET_cercle5 || defined TARGET_cerclerect5 || defined TARGET_calcul5 || defined TARGET_angcalc5 || defined TARGET_clongueur5 || defined TARGET_vocabulaire5 || defined TARGET_formule5 || defined TARGET_cocyclique5 || defined TARGET_clongueur5
# define NUM 5
#endif

\title{TITRE NUM}
