%%%%%%%%%%%%%% TITLE %%%%%%%%%%%%%
#if defined TARGET_01a
# define TITRE 01.a Identifier une hypoténuse
#endif

#if defined TARGET_01b
# define TITRE 01.b Identifier une hypoténuse
#endif

#if defined TARGET_02a
# define TITRE 02.a Aire d'un carré construit sur l'hypoténuse
#endif

#if defined TARGET_02b
# define TITRE 02.b Aire d'un carré construit sur l'hypoténuse
#endif

#if defined TARGET_03a
# define TITRE 03.a Aire d'un carré construit sur une cathète
#endif

#if defined TARGET_03b
# define TITRE 03.b Aire d'un carré construit sur une cathète
#endif

#if defined TARGET_04a
# define TITRE 04.a Calcul de la longueur de l'hypoténuse
#endif

#if defined TARGET_04b
# define TITRE 04.b Calcul de la longueur de l'hypoténuse
#endif

#if defined TARGET_05a
# define TITRE 05.a Calcul de la longueur d'une cathète
#endif

#if defined TARGET_05b
# define TITRE 05.b Calcul de la longueur d'une cathète
#endif

#if defined TARGET_06
# define TITRE 06. Triangles rectangles et égalités de Pythagore simples - QCM
#endif

#if defined TARGET_07
# define TITRE 07. Triangles rectangles et égalités de Pythagore (1) - QCM
#endif

#if defined TARGET_08
# define TITRE 08. Triangles rectangles et égalités de Pythagore (2) - QCM
#endif

#if defined TARGET_09
# define TITRE 09. Triangles rectangles et égalités de Pythagore - Vrai/Faux
#endif
