!header
!read Exindex
C'est un outil d'entraînement essentiel pour les opérations arithmétiques.
Il vous fait remplir une équation algébrique où des termes ou des
opérateurs manquent, pour qu'elle devienne une équation correcte.
 <p>
Selon la configuration, l'exercice peut convenir aux élèves du primaire
(nombres positifs ou relatifs, décimaux), au lycée ou davantage (racines,
nombres complexes).
</p>

!read oef/intromenu.phtml
!tail
