!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.

!set introhook_exists=yes
!set introhook_tableless=yes

<p>Pour chaque paramétrage, si plusieurs cases sont cochées alors le serveur choisira aléatoirement 
l'une d'entre elles à chaque exercice.</p>
<div class="field box">
 <strong>Nature des coefficients&nbsp;:</strong>
 !set wims_html_mode=li
 <ul class="wims_nopuce">
!formcheckbox confparm1 list 1,2,3 prompt entiers (par défaut),décimaux,rationnels
 </ul>
</div>
<div class="field box">
 <strong>Forme de la fonction exponentielle&nbsp;:</strong>
!set wims_html_mode=li
 <ul class="wims_nopuce">
!formcheckbox confparm2 list 1,2,3 prompt \(x \longmapsto \mathrm{e}^x\) (par défaut),\(x \longmapsto \mathrm{e}^{m x}\) avec \(m \neq 0\) et \(m \neq 1\),\(x \longmapsto \mathrm{e}^{m x + p}\) avec \(m \neq 0\) et \(p \neq 0\)
 </ul>
</div>
