!header
!read Exindex
<style>
/**** Bloc description du module ****/
.desc_mod{
  width:80%;
  margin-left:auto;
  margin-right:auto;
  border:1px solid $wims_ref_bgcolor;
  border-top-left-radius: 11px;
  border-top-right-radius: 11px;
}
.title_desc_mod{
  color:white;
  background:$wims_ref_bgcolor;
  border-top-left-radius:10px;
  border-top-right-radius:10px;
  margin-bottom:0px;
  margin-top:0px;
  padding-top:0.5em;
  padding-bottom:0.5em;
}

.p_desc_mod {
  padding-right:0.5em;
  padding-left:0.5em;
} 

.logo_desc_mod {
  float:right;
  margin-left:0.5em;
  margin-right:0.2em;
  margin-top:0.2em;
}
</style>

!if $lang iswordof fr
<div class="desc_mod">
 <h2 class="wimscenter title_desc_mod">Description du module</h2>
 <img src="$module_dir/images/logo_euler.png" class="logo_desc_mod" alt="Logo Euler Académie de Versailles" title="Euler Académie de Versailles" width="48" height="36">
 <p class="p_desc_mod">Ce module regroupe pour l'instant $exototal exercices sur le calcul de la dérivée de la somme, du produit ou du quotient d'une fonction exponentielle et d'une fonction polynôme de degré inférieur ou égal à 2.<br>
 Ces exercices sont adaptés aux programmes de mathématiques de <strong>1<sup>re</sup> Générale (2019) et de Terminales Technologiques (2019)</strong>.
 <br>Par défaut, les coefficients en présence sont des entiers. Ce réglage par défaut peut être modifié plus bas dans <strong><em>Paramétrage spécifique à certains exercices du module</em></strong>.
 </p>
</div>
!goto end
!endif

:end
!read oef/$module_language/intromenu.phtml
!tail
