De algemene formules voor een meetkundige rij zijn:
<p>
<ul>
    <li> De Recursie formule: u<sub>n+1</sub> = <em>r</em> &times; u<sub>n</sub></li>
    Waarbij u<sub>0</sub> = b</li> 
    <li> De Rangnummer formule: u<sub>n</sub> = b &times; <em>r</em><sup>n</sup> <br>
    <li><em>r</em>  wordt de "reden" genoemd van de meetkundige rij</li>
</ul>
bijvoorbeeld:<br>
    Gegeven de  Rekenkundige rij met
    U<sub>8</sub>=26
    en
    U<sub>9</sub>=29
    <br>
    Bereken de termen U<sub>1</sub> en U<sub>3</sub> deze rij...
    <br>
    <textarea cols=20 rows=4 readonly>U1=5 en
U3=11</textarea>
     <br>of<br>
    <textarea cols=20 rows=4 readonly>U_1=5 U_5=11</textarea>
    
!if $subject isitemof 3,8
    <p>
    Let op: ik kijk Hoofdletter gevoelig na...
    <p>
    Wanneer er een <b>Recursieve formule</b> wordt gevraagd in te vullen:<br>
    <textarea cols=20 rows=4 readonly>U(n+1)=4*U(n) 
    met U(0)=5</textarea>
    <p>
    Wanneer er een <b>Rangnummer formule</b> wordt gevraagd in te vullen:
    <br>
    <textarea cols=20 rows=4 readonly>
    Un=21+4n
    of iets als:
    U_n=21+4*n
    </textarea> 
!endif
<hr>			
