
\text{choix= parallèles ou confondues, sécantes, non coplanaires}
\text{texte=para=2 ? cosinus:distance}

\text{name_instruction1=Considérons les deux droites de l'espace données par les
  équations paramétriques}

\matrix{name_instruction2=et
  Ces droites sont
  Calculer la distance entre ces deux droites parallèles.
  Calculer le cosinus de l'angle que forment entre elles ces deux droites sécantes.
  Calculer la distance entre ces deux droites non coplanaires.
  Elles sont }
\text{name_hint1=Deux droites de l'espace sont soit parallèles, soit sécantes,
  soit ni l'un ni l'autre et elles sont alors non coplanaires.}
\text{name_hint2=Pour calculer l'angle que font deux droites sécantes
  dans l'espace, il suffit de calculer l'angle que font deux vecteurs directeurs
  de ces deux droites. }
\text{name_hint3=Pour calculer la distance de deux droites gauches, on considère
  un plan parallèle aux deux droites et contenant une des deux droites.
  On calcule alors la distance d'un point de l'autre droite à ce plan.}
\text{name_hint4=Pour calculer la distance de deux droites parallèles,
  on calcule la distance d'un point de l'une des deux droites à l'autre droite.}
