\text{name_instruction1=Considerem \(\RR^3) amb el seu producte escalar habitual,
\(P) el pla definit per l'equació}
\text{name_instruction2=i \(P') el pla definit per l'equació}

\text{name_instruction3=Trobeu un vector no nul \(v) de \(P) tal que
la projecció ortogonal de \(v) sobre \(P') és
}

\matrix{name_answer=vector de P
pertany a \(P) i és no nul
La projecció ortogonal de (\rep) sobre \(P') és }
