\text{name_let=Let}
\matrix{name_instruction=The points \(Q\), \(R) and \(S)  define
Find the distance from the point \(P = (\a , \b , \c) \)
to the plane passing through \(Q), \(R) and \(S).
to the line passing through \(Q), \(R) and \(S).
distance}

\text{name_hint=The distance from a point \(P) to a plane passing through
three pairwise distinct points\(Q), \(R) and \(S)is given by the formula}

\text{choix= a line,a plane}
