\text{choix= paral·leles o coincidents, secants, no coplanàries}
\text{texte=para=2?cosinus:distància}

\text{name_instruction1=Considera les dues rectes a l'espai amb
equacions}

\matrix{name_instruction2=i
Aquestes rectes són
Trobeu la distància entre aquestes dues rectes paral·leles.
Trobeu el cosinus de l'angle entre aquestes dues rectes secants.
Trobeu la distància entre aquestes dues rectes no coplanàries.
Aquestes rectes són }
\text{name_hint1=Dues rectes a l'espai són paral·leles, o secants (es tallen),
 o són no coplanàries (s'encreuen). }
\text{name_hint2=Per trobar l'angle entre dues rectes que es tallen (secants)
a l'espai, només cal trobar l'angle entre dos vectors directors
d'aquestes rectes. }
\text{name_hint3=Per trobar la distància entre dues rectes no coplanàries, es considera
 un pla paral·lel a les dues rectes i que en conté una d'elles.
 Llavors es calcula la distància entre un punt de l'altra recta i aquest pla.}
\text{name_hint4=Per trobar la distància entre dues rectes paral·leles,
 es calcula la distància entre un punt d'una recta i l'altra recta.}
