\text{name_instruction1=Sea \(\RR^3) con su producto escalar habitual,
\(P) el plano definido por la ecuación}
\text{name_instruction2=y \(P') el plano definido por la ecuación}

\text{name_instruction3=Encontrar un vector no nulo \(v) de \(P) tal que
la proyección ortogonal de \(v) sobre \(P') sea
}

\matrix{name_answer=vector de P
pertenece a \(P) y es no nulo
La proyección ortogonal de (\rep) sobre \(P') es }
