\text{name_instruction=¿Cuál es la distancia desde el punto \(P) de coordenadas (\a , \b , \c)
a la recta \(D) que pasa por los dos puntos}

\matrix{name_vocab=y
distancia}
\text{name_aide1=La distancia desde un punto \(P) a una recta que pasa por dos puntos
\(Q) y \(R) viene dada por
}
\text{name_aide2=Para verlo, nos colocamos en el plano que contiene \(P), \(Q) y \(R).
El número \(||\vec{QR}\wedge\vec{QP}||) es el área del paralelogramo construido
a partir de \(P), \(Q) y \(R). También es el producto de la longitud del segemnto
\(QR) por la distancia de \(P) a la recta \(QR).
}
