
\text{name_instruction1=Soit \(\RR^3) muni de son produit scalaire usuel  noté
  \(< . , . >) et \(F) le sous-espace vectoriel engendré par (\v1) et (\v2).}

\text{name_instruction2=Construire une base orthogonale de \(F) formée de vecteurs
  \(v_1), \(v_2)  à coefficients entiers.
  Déterminer une base \(v_3)  (à coefficients entiers) de l'orthogonal \(F^\perp) de \(F) .
 }
\matrix{name_instruction=pour
  Calculer la norme des trois vecteurs que vous avez trouvé
  Premier vecteur
  Deuxième vecteur
  Vecteur \(v_3) de l'orthogonal
  Norme de
  Les deux vecteurs forment un système libre
  appartient à
  \(v_1) et \(v_2) forment une base orthogonale
  Le vecteur \(v_3) est non nul et appartient à l'orthogonal de \(F)}
