\text{name_instruction1=Consideramos \(\RR^3) con su producto escalar habitual
\(< . , . >) y \(F) el subespacio vectorial generado por (\v1) y (\v2).}

\text{name_instruction2=Construir una base ortogonal de \(F) formada por vectores
 \(v_1), \(v_2)  con coeficientes enteros.
 Determinar una base \(v_3)  (con coeficientes enteros) del ortogonal \(F^\perp) de \(F) .
 }
\matrix{name_instruction=para
  Calcular el módulo de los tres vectores que has encontrado
  Primer vector
  Segundo vector
  Vector \(v_3) del ortogonal
  Módulo de
  Ambos vectores forman un sistema libre
  pertenece a
  \(v_1) y \(v_2) forman una base ortogonal
  El vector \(v_3) es no nulo y pertenece al ortogonal de \(F)}
