\text{name_let=Soit}
\matrix{name_instruction=Les points \(Q\), \(R) et \(S)  définissent
  Calculer la distance du point
    au plan contenant \(Q), \(R) et \(S\)
  à la droite contenant \(Q), \(R) et \(S\)
  distance}

\text{name_hint=La distance d'un point \(P) à un plan contenant trois points
\(Q), \(R) et \( S) distincts deux à deux peut se calculer par la formule}

\text{choix= une droite,un plan}
