\text{choix=paral·lels, no paral·lels}
\text{name_choix=distància,cosinus}
\matrix{name_instruction=Considerem els dos plans de \(\RR^3) d'equacions respectives
i
Aquests plans són
Calcular la distància entre els dos plans paral·lels.
Calcular el cosinus de l'angle que formen els dos plans no paral·lels.
Tots dos plans són
Una distància és un real positiu.
El cosinus d'un angle està comprès entre -1 i 1. }
\text{name_hint1=Per calcular l'angle que formen entre ells
  dos plans no paral·lels, podem calcular l'angle entre els
  dos vectors \(\vec{n}_1) i \(\vec{n}_2) normals respectivament
  als plans. El cosinus de l'angle cercat ve donat per}

\text{name_hint2=Per calcular la distància entre dos plans paral·lels,
  es pot calcular la distància entre un punt d'un dels dos plans i l'altre pla.
  També podem passar les equacions dels dos plans a la forma general
  \(a x + b y + c z = d_1) i  \(a x + b y + c z = d_2).
  Llavors la distància entre els dos plans és igual a}
