\text{name_instruction=What is the distance between the point \(P) with coordinates (\a , \b , \c)
and the line \(D) passing through the two points}

\matrix{name_vocab=and
distance}
\text{name_aide1=The distance between a point \(P) and the line \(D) passing through
the two points \(Q) and \(R) is given by
}
\text{name_aide2=To see that, one considers the plane containing \(P), \(Q) and \(R).
It contains the parallelogram constructed from \(P), \(Q) and \(R), the area of which is
\(||\vec{Q R}\wedge\vec{Q P}||). It is also the product of the length
\(QR) and the distance from \(P) to the line \(Q R).
}
