\text{name_instruction1=Considereu \(\RR^3) amb el seu producte escalar habitual
\(< . , . >) i \(F) el subespai vectorial generat per (\v1) i (\v2).}

\text{name_instruction2=Construir una base ortogonal de \(F) formada per vectors
 \(v_1), \(v_2)  amb coeficients enters.
 Determinar una base \(v_3)  (amb coeficients enters) de l'ortogonal \(F^\perp) de \(F) .
 }
\matrix{name_instruction=amb
  Calcular el mòdul dels tres vectors que heu trobat
  Primer vector
  Segon vector
  Vector \(v_3) de l'ortogonal
  Mòdul de
  Tots dos vectors formen un sistema lliure
  pertanyen a
  \(v_1) i \(v_2) formen una base ortogonal
  El vector \(v_3) és no nul i pertany a l'ortogonal de \(F)}
