\text{choix= parallel or the same, intersecting, non-coplanar}
\text{texte=para=2 ? cosine:distance}

\text{name_instruction1=Consider the two lines in space with
parametric equations}

\matrix{name_instruction2=and
These lines are
Find the distance between these two parallel lines.
Find the cosine of the angle between these two intersecting lines.
Find the distance between these two non-coplanar lines.
They are }
\text{name_hint1=Two lines in space are either parallel, or intersecting,
or neither and then they are non-coplanar.}
\text{name_hint2=To find the angle between two intersecting lines
in space, it suffices to find the angle between two direction vectors
of these lines. }
\text{name_hint3=To find the distance between two non-coplanar lines, one considers
 a plane parallel to the two lines and containing one of them.
 One then computes the distance between a point on the other line and that plane.}
\text{name_hint4=To find the distance between two parallel lines,
 one computes the distance between a point on one line and the other line.}
