\text{name_instruction1=In \(\RR^3) with its usual scalar product denoted
\(< . , . >) let \(F) be the vector space spanned by (\v1) and (\v2).}

\text{name_instruction2=Find an orthogonal basis in \(F) formed by vectors
 \(v_1), \(v_2)  with integral coefficients.
 Find a basis \(v_3)  (with integral coefficients) of the orthogonal complement \(F^\perp) of \(F) .
 }
\matrix{name_instruction=for
  Compute the norms of the three vectors you found
  First vector
  Second vector
  Direction vector \(v_3) of the orthogonal complement
  Norm of
  The two vectors form an independant system
  belongs to
  \(v_1) and \(v_2) form an orthogonal basis
  The vector \(v_3) is non-zero and belongs to the orthogonal of \(F)}
