\text{choix=parallel, non-parallel}
\text{name_choix=distance,cosine}
\matrix{name_instruction=Consider the two planes in \(\RR^3) with equations
and
They are
Compute the distance between the two parallel planes.
Compute the cosine of the angle between the two non-parallel planes.
The two planes are
A distance is a nonnegative real number.
The cosine of an angle lies between -1 and 1. }
\text{name_hint1=To compute the angle between two
non-parallel planes, one can compute the angle between
two vectors \(\vec{n}_1) and \(\vec{n}_2) orthogonal to
the planes. Le cosine sought for is then given by}

\text{name_hint2=To compute the distance between two parallel planes,
 one can compute the distance between a point on one of the two planes and the other plane.
 One may also write similar equations for the two planes
 \(a x + b y + c z = d_1) and  \(a x + b y + c z = d_2).
 The distance between the two planes is then}
