\text{name_let=Sean}
\matrix{name_instruction=Los puntos \(Q\), \(R) y \(S) definen
Calcular la distancia desde el punto
al plano que contiene \(Q), \(R) y \(S\)
a la recta que contiene \(Q), \(R) y \(S\)
distancia}

\text{name_hint=La distancia desde un punto \(P) a un plano que contiene tres puntos
\(Q), \(R) y \( S) distintos de dos en dos se pueden calcular mediante la fórmula}

\text{choix= una recta,un plano}
