
\text{name_instruction1=Soit \(\RR^3) muni de son produit scalaire usuel,
\(P) le plan défini par l'équation}
\text{name_instruction2=et \(P') le plan défini par l'équation}

\text{name_instruction3=Trouver un vecteur non nul \(v) de \(P) tel que
la projection orthogonale de \(v) sur \(P') soit
}

\matrix{name_answer=vecteur de P
appartient à \(P) et est non nul
La projection orthogonale de (\rep) sur \(P') est }
