\text{choix=paralelos, no paralelos}
\text{name_choix=distancia, coseno}
\matrix{name_instruction=Consideremos los dos planos de \(\RR^3) de ecuaciones respectivas
y
Estos planos son
Calcular la distancia entre los dos planos paralelos.
Calcular el coseno del ángulo formado por los dos planos no paralelos.
Ambos planes son
Una distancia es un real positivo.
El coseno de un ángulo está comprendido entre -1 y 1. }
\text{name_hint1=Para calcular el ángulo entre ellos
dos planos no paralelos, podemos calcular el ángulo entre los
dos vectoress \(\vec{n}_1) i \(\vec{n}_2) normales respectivamente
a los planos. El coseno del ángulo buscado viene dado por}

\text{name_hint2=Para calcular la distancia entre dos planos paralelos,
  se puede calcular la distancia entre un punto de uno de los dos planos y el otro plano.
  También podemos pasar las ecuaciones de los dos planos a la forma general
  \(a x + b y + c z = d_1) y  \(a x + b y + c z = d_2).
  La distancia entre los dos planos es entonces igual a}
