\text{name_instruction1=In \(\RR^3) with its usual scalar product,
let \(P) be the plane given by the equation}
\text{name_instruction2=and let \(P') be the plane given by the equation}

\text{name_instruction3=Find a non-zero vector \(v) in \(P) such that
the orthogonal projection of \(v) onto \(P') is
}

\matrix{name_answer=vector in P
belongs to \(P) and is non-zero
the orthogonal projection of (\rep) onto \(P') is }
