
\text{name_instruction=Quelle est la distance du point \(P) de coordonnées (\a , \b , \c)
  à la droite \(D) passant par les deux points}

\matrix{name_vocab=et
distance}
\text{name_aide1=La distance d'un point \(P) à une droite passant par deux points
\(Q) et \(R) est donnée par
}
\text{name_aide2=Pour le voir, on se place dans le plan contenant \(P), \(Q) et \(R).
  Le nombre \(||\vec{QR}\wedge\vec{QP}||) est l'aire du parallélogramme construit
  à partir de \(P), \(Q) et \(R). C'est aussi le produit de la longueur
  \(QR) par la distance de \(P) à la droite \(QR).
}
