
\text{choix=parallèles, non parallèles}
\text{name_choix=distance,cosinus}
\matrix{name_instruction=Considérons les deux plans  de \(\RR^3) d'équations respectives
  et
  Ils sont
  Calculer la distance entre les deux plans parallèles.
  Calculer le cosinus de l'angle que font les deux plans non parallèles.
  Les deux plans sont
  Une distance est un réel positif.
  Le cosinus d'un angle est compris entre -1 et 1. }
\text{name_hint1=Pour calculer l'angle que forment entre eux
  deux plans non parallèles, on peut calculer l'angle que font entre eux
  deux vecteurs \(\vec{n}_1) et \(\vec{n}_2) normaux respectivement
  aux plans. Le cosinus de l'angle cherché est alors donné par}

\text{name_hint2=Pour calculer la distance entre deux plans parallèles,
  on peut calculer la distance entre un point d'un des deux plans et l'autre plan.
  On peut aussi ramener les équations des deux plans sous la forme similaire
  \(a x + b y + c z = d_1) et  \(a x + b y + c z = d_2).
  La distance entre les deux plans est alors égale à}
