#if defined TARGET_orthon
#include "lang_orthon_fr.inc"
\if{\lang=en}{
#include "lang_orthon_en.inc"
}
\if{\lang=es}{
#include "lang_orthon_es.inc"
}
\if{\lang=ca}{
#include "lang_orthon_ca.inc"
}
#endif


#if defined TARGET_plan
#include "lang_plan_fr.inc"
\if{\lang=en}{
#include "lang_plan_en.inc"
}
\if{\lang=es}{
#include "lang_plan_es.inc"
}
\if{\lang=ca}{
#include "lang_plan_ca.inc"
}
#endif


#if defined TARGET_planplan
#include "lang_planplan_fr.inc"
\if{\lang=en}{
#include "lang_planplan_en.inc"
}
\if{\lang=es}{
#include "lang_planplan_es.inc"
}
\if{\lang=ca}{
#include "lang_planplan_ca.inc"
}
#endif
#if defined TARGET_poinplan2
#include "lang_poinplan2_fr.inc"
\if{\lang=en}{
#include "lang_poinplan2_en.inc"
}
\if{\lang=es}{
#include "lang_poinplan2_es.inc"
}
\if{\lang=ca}{
#include "lang_poinplan2_ca.inc"
}
#endif
#if defined TARGET_pointplan
#include "lang_pointplan_fr.inc"
\if{\lang=en}{
#include "lang_pointplan_en.inc"
}
\if{\lang=es}{
#include "lang_pointplan_es.inc"
}
\if{\lang=ca}{
#include "lang_pointplan_ca.inc"
}
#endif

#if defined TARGET_projb
#include "lang_projb_fr.inc"
\if{\lang=en}{
#include "lang_projb_en.inc"
}
\if{\lang=es}{
#include "lang_projb_es.inc"
}
\if{\lang=ca}{
#include "lang_projb_ca.inc"
}
#endif
#if defined TARGET_proje
#include "lang_proje_fr.inc"
\if{\lang=en}{
#include "lang_proje_en.inc"
}
\if{\lang=es}{
#include "lang_proje_es.inc"
}
\if{\lang=ca}{
#include "lang_proje_ca.inc"
}
#endif

#if defined TARGET_droite || defined TARGET_droite2
#include "lang_droite_fr.inc"
\if{\lang=en}{
#include "lang_droite_en.inc"
}
\if{\lang=es}{
#include "lang_droite_es.inc"
}
\if{\lang=ca}{
#include "lang_droite_ca.inc"
}
#endif

#if defined TARGET_droiteplan
#include "lang_droiteplan_fr.inc"
\if{\lang=en}{
#include "lang_droiteplan_en.inc"
}
\if{\lang=es}{
#include "lang_droiteplan_es.inc"
}
\if{\lang=ca}{
#include "lang_droiteplan_ca.inc"
}
#endif

