#if defined TARGET_table
\text{name_enonce=Compléter la table de multiplication&nbsp;}
#endif
#if defined TARGET_multipli
\text{name_enonce=Faire la multiplication posée suivante&nbsp;}
#endif
#if defined TARGET_division
\text{name_enonce=Faire la division posée suivante&nbsp;}
#endif
#if defined TARGET_decomp
\text{name_enonce=Pour chaque nombre, trouver une multiplication.}
\text{name_inst=Il faut que chaque facteur soit strictement inférieur à 10.}
#endif
#if defined TARGET_multipli || defined TARGET_division
\text{name_inst=Vous devez remplir toutes les étiquettes avec des chiffres.}
#endif
