#! /bin/sh

cd defs
list=`ls`
cd ..

for f in $list
do
 tit=`awk -F'=' '$1=="title" {print $2;exit}' defs/$f`
 flist="$flist$f,"
 titlist="$titlist$tit,"
done

cat >defindex <<@
tlist=!char 1 to -2 of $flist
titlist=!char 1 to -2 of $titlist
@
