\text{instruction=En cliquant sur les carrés, prolonger la figure en une frise
par translation du vecteur dessiné et par symétrie centrale par rapport au point. }

\if {\lang=en}{
 \text{instruction=Complete, by clicking the squares,
 the pattern [a Frieze group] by repetitive translation in the direction and distance dictated by the vector and reflection in the given point. }
}

\if {\lang=nl}{
 \text{instruction=Klik met je muis op de vierkantjes en maak zo het patroon [een strookpatroongroep of Frieze] verder af d.m.v. herhaalde translatie in richting en afstand met de getoonde vector en puntspiegeling.}
}

\if{\lang=it}{
\text{instruction=Utilizzando il minor numero di quadretti, prolungare la figura in un fregio con
traslazioni corrispondenti al vettore indicato e con rotazioni di 180 gradi rispetto al punto indicato.}
}

\if {\lang=es}{
 \text{instruction=Haciendo clic en los cuadrados, extender la figura en un friso
  por traslación del vector dibujado y por simetría central con respecto al punto. }
}

\if {\lang=ca}{
 \text{instruction=Clicant als quadrats, estén la figura en un fris
  per translació del vector dibuixat i per simetria central respecte al punt. }
}