\text{instruction=En cliquant sur les carrés, prolonger la figure en une frise par
translation du vecteur dessiné et symétrie glissée par rapport à la droite horizontale
et de vecteur moitié du vecteur dessiné. }

\if {\lang=en}{
 \text{instruction=Complete, by clicking the squares,
 the pattern [a Frieze group] by repetitive translation in the direction and distance dictated by the vector and by glide reflection in the given line. }
}

\if {\lang=nl}{
 \text{instruction=Klik met je muis op de vierkantjes en maak zo het patroon [een strookpatroongroep of Frieze] verder af d.m.v. herhaalde translatie in richting en afstand met de getoonde vector en door glijspiegeling in de rechte lijn.}
}

\if{\lang=it}{
\text{instruction=Utilizzando il minor numero di quadretti, prolungare la figura in un
fregio con traslazioni corrispondenti al vettore indicato e con glissoriflessioni rispetto
alla retta orizzontale indicata e ad un vettore opportuno. }
}

\if {\lang=es}{
 \text{instruction=Haciendo clic en los cuadrados, extender la figura en un friso
  por traslación del vector dibujado y simetría deslizada respecto a la recta horizontal y de vector la mitad del vector dibujado. }
}

\if {\lang=ca}{
 \text{instruction=Clicant als quadrats, estén la figura en un fris
  per translació del vector dibuixat i simetria desplaçada respecte a la recta horitzontal i de vector la meitat del vector dibuixat. }
}