\text{instruction=En cliquant sur les carrés, prolonger la figure en une frise
 par translation du vecteur dessiné et par symétrie par rapport à la droite verticale. }

\if {\lang=en}{
 \text{instruction=Complete, by clicking the squares,
 the pattern [a Frieze group] by repetitive translation in the direction
 and distance dictated by the vector and by vertical glide reflection in the given line. }
}

\if {\lang=nl}{
 \text{instruction=Klik met je muis op de vierkantjes en
  maak zo het patroon [een strookpatroongroep of Frieze] verder af d.m.v.
  herhaalde translatie in richting en afstand met de getoonde vector en door glijspiegeling in de rechte lijn.}
}

\if{\lang=it}{
\text{instruction=Utilizzando il minor numero di quadretti, prolungare la figura in un
fregio con traslazioni corrispondenti al vettore indicato e con riflessioni rispetto alla retta verticale indicata. }
}

\if {\lang=es}{
 \text{instruction=Haciendo clic en los cuadrados, extender la figura en un friso
  por traslación del vector dibujado y por simetría con respecto a la recta vertical. }
}

\if {\lang=ca}{
 \text{instruction=Clicant als quadrats, estén la figura en un fris
  per translació del vector dibuixat i per simetria respecte a la recta vertical. }
}
