\text{instruction=En cliquant sur les carrés, prolonger la figure en une frise
par translation du vecteur dessiné et par symétries par rapport aux droites horizontale et verticale. }

\if {\lang=en}{
 \text{instruction=Complete, by clicking the squares,
 the pattern [a Frieze group] by repetitive translation in the direction and
 distance dictated by the vector and by line reflection in the given horizontal and vertical lines. }
}

\if {\lang=nl}{
 \text{instruction=Klik met je muis op de vierkantjes en maak zo het patroon [een strookpatroongroep of Frieze] verder af d.m.v. herhaalde translatie in richting en afstand met de getoonde vector en lijnspiegeling in de horizontale en verticale lijnen.}
}

\if{\lang=it}{
\text{instruction=Utilizzando il minor numero di quadretti, prolungare la figura in un fregio
con traslazioni corrispondenti al vettore indicato e con riflessioni rispetto alle rette orizzontali e verticali indicate. }
}

\if {\lang=es}{
 \text{instruction=Haciendo clic en los cuadrados, extender la figura en un friso
  por traslación del vector dibujado y por simetrías con respecto a las rectas horizontales y verticales. }
}

\if {\lang=ca}{
 \text{instruction=Clicant als quadrats, estén la figura en un fris
  per translació del vector dibuixat i per simetria respecte a les rectes horitzontals i verticals. }
}