!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur l'algorithmique en Seconde
(programme 2009).
<br>L'objectif est de tester la compréhension des élèves des instructions élémentaires.
<br>Dans ce module on ne teste pas les compétences en programmation.
<br>Dans les versions (2) des exercices, les algorithmes sont écrits avec une
syntaxe variable (langage courant, à la Texas Instrument, à la AlgoBox....)

!read oef/intromenu.phtml
!tail
