#if defined TARGET_carre
# define TITRE Encadrement d'un carré
#endif
#if defined TARGET_difference || defined TARGET_difference2
# define TITRE Encadrement d'une différence
#endif
#if defined TARGET_encadproduit || defined TARGET_encadproduit2 || defined TARGET_encadproduit3
# define TITRE Encadrement d'un produit
#endif
#if defined TARGET_inequation
# define TITRE Inéquations
#endif
#if defined TARGET_oefencad1 || defined TARGET_oefencad2 || defined TARGET_oefencad3
# define TITRE Encadrement de nombres réels
#endif
#if defined TARGET_valabs
# define TITRE Encadrement de |x|
#endif
#if defined TARGET_valeurabsolue1 || defined TARGET_valeurabsolue2 || defined TARGET_valeurabsolue3
# define TITRE Valeur absolue
#endif
#if defined TARGET_inequation
# define TITRE Inéquations
#endif
#if defined TARGET_sum
# define TITRE Somme
#endif

