\solution{<p>Le réel \(y) est encadré par
les bornes \(\c\) et \(\d\),
son opposé \(-y\) entre leurs opposées : \({\t \absd < -y < \s \absc}\).</p>
<p>En additionnant terme à terme l'encadrement \({\a < x < \b}\) de \(x\) et de celui de \(-y\), on obtient :
<p class="wimscenter">\({\a \t \absd < x - y < \b \s \absc}\) c'est-à-dire \({\res3 < x - y < \res4}\).</p>
<p><em>On peut visualiser cet encadrement de la différence \(x - y\) par la figure ci-dessous.</em></p>
Dans le plan muni d'un repère \(( O \overrightarrow{x}\textrm{,} O \overrightarrow{y} )\), l'ensemble des points de coordonnées \((x,y)\)
vérifiant les inégalités \({\a < x < \b}\) et \({\c < y <\d}\) est le rectangle <span style="color:red";>rouge</span>
situé dans la bande délimitée par les deux droites vertes d'équations \(x - y = \res3\) et \(x - y = \res4\).<br>
<em>Ces droites sont parallèles à la droite d'équation \(x - y = 0\), première bissectrice de l'angle
\(( O \overrightarrow{x}\textrm{,} O \overrightarrow{y} )\). Leurs ordonnées \(\res3\) et \(\res4\) en \(0\)
encadrent la différence \(x-y\) pour tous les points \((x,y)\) du rectangle rouge.</em>
<p class="wimscenter">\draw{400,400 }{\Encadrement}</p>}
