\solution{L'expression donnée peut s'écrire comme la somme&nbsp;:
\(S = \expr\).
On minore et on majore chacun de ses deux termes à partir des encadrements suivants&nbsp;:
<ul>
<li>Le binôme \(\texxu\) est compris entre \(\m1\) et \(\M1\). On en déduit :
\({\mx < (\texxu)^2 < \Mx}\).
</li><li>
Le binôme \(\texyw\) est compris entre \(\m2\) et \(\M2\). On en déduit :
\({\my < (\texyw)^2 < \My}\).
</li><li>
Comme le terme \(\v\) présent dans la somme \(S\) est \if{\v>0}{positif}{négatif},
le produit \(\v\; \times (\texyw)^2\) est compris entre
\if{\v>0}{\(\v\; \times \my = \vmy\)}{\(\v\; \times\My = \vMy\)} et
\if{\v>0}{\(\v\; \times\My = \vMy\)}{\(\v\; \times \my = \vmy\)}.
</li></ul>
<p>En appliquant les règles sur l'encadrement d'une somme,
on obtient le meilleur encadrement suivant&nbsp;:</p>
<p class="wimscenter">\({\solm < \expr1 < \solM}\).</p>}
