\text{Explication=<p>Dans le plan muni d'un repère
  \(( O \overrightarrow{x}\textrm{,} O \overrightarrow{y} )\),
  l'ensemble des points de coordonnées \((x,y)\) vérifiant les inégalités
  \({\a < x < \b}\) et \({\c < y <\d}\)
  est le rectangle <span style="color:red";>rouge</span>
  situé dans la bande délimitée par les deux droites vertes
  d'équations \(x + y = \res1\) et \(x + y = \res2\).</p>
  <p>Ces droites sont parallèles à la droite d'équation \(x + y = 0\),
  seconde bissectrice de l'angle
  \(( O \overrightarrow{x}\textrm{,} O \overrightarrow{y} )\).
  Leurs ordonnées en \(0\) sont les bornes \(m\) et \(M\)
  qui encadrent la somme \(x+y\) pour tous les points \((x,y)\) du rectangle rouge.</em>
  </p>
}
