\text{name_answer=La probabilité}

#if defined TARGET_ball
\text{name_evenodd=pair,impair}
\text{name_color=rouge,verte, bleue,jaune}
\text{name_colors=rouges,vertes, bleues,jaunes}
\text{name_statement1=Un sac contient}
\text{name_the=Les,Les,les,les}
\text{name_balls=boule,boules}
\text{name_have=ait,aient}
\text{name_a=un}
\text{name_number=numéro}
\text{name_and=et}
\text{name_statement2=On tire au hasard,du sac.}
\text{name_is=est}
\text{name_one=une}
\text{name_space=&nbsp;}
\text{name_step1=La probabilité de ne tirer que des boules,}
\text{name_step2=La probabilité d'obtenir}
\text{name_enum=sont numérotées de 1 à}
\text{name_step3=La probabilité que parmi les,boules tirées}
\text{name_replygood=Bonne réponse !}
\text{name_yourreply=Votre réponse}
\text{name_sol1=La probabilité de ne tirer que des boules,}
\text{name_sol2=La probabilité d'obtenir}
\text{name_sol3=Comme il y a,dont le numéro est,la probabilité de tirer exactement}
\text{sort_nameadj=1}
#endif
#if defined TARGET_birthdays
\text{name_statement=Si l'on suppose que les jours d'anniversaire sont
  répartis équitablement parmi les 365 jours de l'année et si l'on
  choisit \people personnes au hasard dans l'annuaire, quelle est la probabilité
  pour qu'au moins deux de ces \people personnes aient leur anniversaire le même jour&nbsp;?
}
\text{name_hint=Calculer plutôt la probabilité pour que ces \people personnes
 aient toutes leur anniversaire un jour différent.}
#endif
#if defined TARGET_bw
\text{name_statement=Il y a \black balles noires et \white balles blanches dans
  un sac. Si deux balles sont tirées aléatoirement du sac, quelle est
  la probabilité d'obtenir}
\text{name_space=&nbsp;}
\text{name_balls=une noire et une blanche,deux noires,deux blanches}
#endif
#if defined TARGET_coins
\text{name_statement1=On suppose que chaque fois qu'on jette une pièce, la probabilité
  d'obtenir face dessus est exactement de 1/2.}
\text{name_statement2=Si l'on jette \times fois la pièce, quelle est la probabilité d'obtenir
  exactement \faces fois la face&nbsp;?}
\text{name_solution=Il y a \(C_\times^\faces) façons distinctes
  pour les \faces faces de répartir parmi les \times jets de pièce.
  Et chaque répartition particulière a une probabilité de
  1/2^(\times).}
#endif
#if defined TARGET_freeway
\text{name_statement1=D'après les statistiques, un piéton marchant sur un certain tronçon
  d'autoroute pendant 1 minute a une probabilité de \min d'être renversé par une voiture.}
\text{name_statement2=Monsieur X veut faire le pari de marcher sur ce tronçon d'autoroute
  pendant \tot minutes, sans être victime d'un accident. Quelle est
  sa chance de gagner ce pari fou&nbsp;?}
\text{name_answer=Sa chance}
#endif
#if defined TARGET_rg
\text{name_color=rouge,rouges,verte,vertes}
\text{name_statement=Il y a ,balles rouges et ,balles vertes dans
  un sac. Si, balles sont tirées aléatoirement du sac}
\text{name_statement2=quelle est la probabilité d'obtenir}
\text{name_and=et}
#endif
