!default confparm1=2
!default confparm2=1
!default confparm3=1
!default confparm4=2
<tr><td align="left">Toujours ajouter des parenthèses autour des nombres relatifs ?</td>
<td>
   !formradio confparm1 list 1,2 prompt Oui,Non
 </td></tr>
<tr><td align="left">Les nombres utilisés seront compris entre </td>
<td>
   !formradio confparm2 list 1,2 prompt -10 et 10 ,-100 et 100
 </td></tr>
<tr><td align="left">Affichage d'un axe vertical pour aider les élèves ?</td>
<td>
   !formradio confparm3 list 1,2 prompt Oui,Non
 </td></tr>
<tr><td align="left">Quel symbole utiliser pour désigner les inconnues ?</td>
<td>
   !formradio confparm4 list 1,2 prompt Le point d'interrogation, La lettre <I>x</I>
 </td></tr>