!header
!read Exindex
!if $lang iswordof it
<div style="color:#000080;">Questo modulo raccoglie per il momento $exototal esercizi
sugli insiemi, la cardinalità di un insieme, la rappresentazione di eventi tramite insiemi e
le applicazioni tra due insiemi finiti.</div>
Il parametro "Complessità degli insiemi" serve solo per gli esercizi <i>Posizione di punti aleatori</i> e <i> Cardinalità di un insieme classico</i>,<i>Descrizione di un sottoinsieme del piano</i>.
!goto end
!endif

!if $lang iswordof es
<div style="color:#000080;">Este módulo agrupa por el momento $exototal ejercicios
sobre conjuntos, la cardinalidad de un conjunto, la representación de eventos a través de conjuntos y funciones entre conjunto finitos.</div>
El parámetro "Complejidad de los conjuntos" sirve solamente para los ejercicios <i>Posiciones de puntos aleatorios</i>,<i> Cardinalidad de un conjunto clásico</i> y <i>Descripción de un subconjunto del plano</i>.
<p>El ejercicio <i>Cardinalidad de un conjunto clásico 0</i> es casi idéntico al
 <i>Cardinalidad de un conjunto clásico</i> pero no utiliza el símbolo de sumatoria.
</p><p>
Las letras que aparecen al principio del nombre de cada ejercicio sirven para clasificarlos por tipo:
Se usa A para los ejercicios relativos a los conjuntos y su notación, B para los ejercicios
donde aparecen ejemplos concretos de conjuntos, C para los ejercicios
de conteo, D para los ejercicios ligados a la descripción de eventos usando conjuntos y E para los ejercicios de funciones entre conjuntos finitos. En cada grupo, los ejercicios están ordenados en un nivel creciente de complejidad. </p>
!goto end
!endif



<div style="color:#000080;">Ce module regroupe pour l'instant $exototal exercices
sur les ensembles, le cardinal d'un ensemble, la représentation d'événements par des ensembles et les applications entre deux ensembles finis.</div>
<p>Le paramètre "Complexité des ensembles" sert uniquement pour les exercices
<i>Positions de points aléatoires</i>,
 <i>Cardinal d'un ensemble classique</i>, <i>Cardinal d'un sous-ensemble du plan</i> et
<i>Description d'un sous-ensemble du plan</i>.</p>
<p>L'exercice <i>Cardinal d'un ensemble classique 0</i> est presque identique à l'exercice
 <i>Cardinal d'un ensemble classique</i> mais n'utilise pas le signe de sommation.
</p><p>
Les lettres au début du titre des exercices servent à les regrouper par type :
A pour les exercices sur les notations ensemblistes, B pour les exercices
portant sur des exemples concrets d'ensembles, C pour les exercices
de dénombrement, D pour les exercices sur la description ensembliste d'un
événement. Dans chaque groupe, ils sont numérotés par complexité croissante. </p>

:end
!read oef/intromenu.phtml
!tail
