!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les suites arithmétiques et géométriques. 
L'ensemble de ses exercices traite en paralléle, l'usage des TIC et des formules permettant le calcul du
 n<sup>e</sup> terme et la somme des n<sup>e</sup> termes :
<ul><li>Calcul du 7<sup>e</sup> terme d'une suite géométrique : Passage des intérêts simples aux intérêts
 composés.</li>
<li>Calcul du 8<sup>e</sup> terme d'une suite arithmétique et géométrique : Capitalisme Financier Versus
 Travail.</li>
<li>Calcul de la somme d'une suite géométrique : Quel est le prix réel de la consommation de tabac ?</li>
<li>Pourcentage - Calcul d'un terme et de la somme d'une suite géométrique : Comment connaître sa capacité d'emprunt ?</li>
<li>Résolution d'une équation utilisant le log pour calculer n. D'autres possibilités sont offertes mais
 seul cette résolution est du niveau BAC PRO : Quelle doit être la durée d'un placement financier pour
 acheter un objet ?</li>
</ul>

Une approche pragmatique est réalisée et le thème suivant est abordé :
<ul><li>vie économique et professionnelle</li></ul>

Ils ont été réalisés pour un niveau de Terminal BAC PRO section tertiaire.

!read oef/intromenu.phtml
!tail
