# Change to 0 if you don't want the choice `I don't know'
idontknow=1

# Change to 1 of you want all choices to be present
allchoices=0

# Computational precisions: you can change the defaults here.
# pari_precision=18
#maxima_precision=8
# print_precision=8

# Change to no if you don't want classes to import exercises in this module.
# A typical situation is that these exercises use common resources of the module.
class_importation=yes

# Change to yes if you want to put images in common (images/) to all exercises.
# If you do so, you must disable class_importation.
common_images=yes

!if $exo=suitegUIs or $exo=SuitegUCalculn
oefenv_fn=$wims_firstname
!if $oefenv_fn=$empty
oefenv_fn=l'élève
!endif
!endif

!if $exo=actualisation
oefenv_nomm=$wims_lastname
!if $oefenv_nomm=$empty
oefenv_nomm=DUPONT
!endif
!endif

!changeto oef/var.proc
