!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur la géométrie dans l'espace
niveau Première S.
<ul><li> Alignement de points,</li>
<li> Vecteurs colinéaires,</li>
<li> Points coplanaires,</li>
<li> Vecteurs coplanaires,</li>
<li> Position relative de droites et de plans,</li>
<li> Équation d'objets de l'espace (sphères, cylindres de révolution, cônes de révolution),</li>
<li> Intersection d'objets de l'espace et de plans parallèles aux coordonnées.</li>
</ul>
!set latex_exists=yes
!read oef/$module_language/intromenu.phtml
!tail
