!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur la lumière
selon les programmes de cinquième (France, 2024). On y aborde partiellement&nbsp;:
<ul><li>
les sources de lumière&nbsp;: sources primaires et objets diffusants&nbsp;;
</li><li>
les conditions de visibilité d'une source primaire et d'un objet diffusant&nbsp;;
</li><li>
la propagation de la lumière&nbsp;: définition et modélisation d'un rayon de lumière&nbsp;;
</li><li>
les faisceaux de lumière&nbsp;: définition, modélisation et forme&nbsp;;
</li><li>
les ombres&nbsp;: forme, couleur et condition d'obtention des ombres&nbsp;;
</li><li>les phases de la Lune.
</li><ul>
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=
!! to add a chronometer
!!default scoredelay=60,120
!read oef/intromenu.phtml
!tail
