\description{Sur le quadrillage, vous devez déplacer l'extrémité libre du vecteur bleu pour que les deux vecteurs soient
#if defined TARGET_01colineaire
de même direction.
#endif
#if defined TARGET_02memesens
de même sens.
#endif
#if defined TARGET_03sensoppose
de sens opposé.
#endif
#if defined TARGET_04egaux
égaux.
#endif
#if defined TARGET_05oppose
opposés.
#endif
#if defined TARGET_06memenorme
de même norme.
#endif
#if defined TARGET_07memenormenoncoli
de même norme et ne soient pas de même direction.
#endif
}

\observation{Cet exercice d'apprentissage propose de déplacer l'extrémité libre du vecteur bleu sur le quadrillage pour que 
les deux vecteurs soient
#if defined TARGET_01colineaire
de même direction.
#endif
#if defined TARGET_02memesens
de même sens.
#endif
#if defined TARGET_03sensoppose
de sens opposé.
#endif
#if defined TARGET_04egaux
égaux.
#endif
#if defined TARGET_05oppose
opposés.
#endif
#if defined TARGET_06memenorme
de même norme.
#endif
#if defined TARGET_07memenormenoncoli
de même norme et ne soient pas de même direction.
#endif
Une analyse de la réponse et des éléments de solution sont proposés dans l'applet GeoGebra.}
