%%%%%%%%%%%%%% TITLE %%%%%%%%%%%%%

#if defined TARGET_01colineaire
# define TITRE 01. Représenter un vecteur de même direction qu'un vecteur donné
#endif

#if defined TARGET_02memesens
# define TITRE 02. Représenter un vecteur de même sens qu'un vecteur donné
#endif

#if defined TARGET_03sensoppose
# define TITRE 03. Représenter un vecteur de sens opposé à un vecteur donné
#endif

#if defined TARGET_04egaux
# define TITRE 04. Représenter un vecteur égal à un vecteur donné
#endif

#if defined TARGET_05oppose
# define TITRE 05. Représenter un vecteur opposé à un vecteur donné
#endif

#if defined TARGET_06memenorme
# define TITRE 06. Représenter un vecteur de même norme qu'un vecteur donné
#endif

#if defined TARGET_07memenormenoncoli
# define TITRE 07. Représenter un vecteur non colinéaire de même norme qu'un vecteur donné
#endif
