!header
!read Exindex
!if $lang=fr
  Ce module regroupe pour l'instant $exototal exercices sur les vecteurs en 2D
  (combinaison linéaire, angle, longueur, produit scalaire, produit
  vectoriel, etc.).
  !goto end
!endif

This module contains actually $exototal exercises on vectors in 2D
(linear combinations, angle, length, scalar product, vector product, etc.).
:end
!read oef/intromenu.phtml
!set keyw=!getdef keywords in INDEX
!read related.phtml $keyw
!tail
