!if $error!=$empty
  !exit
!endif

<p>$name_resultat</p>
$name_ecart = $[rint(10*$mean)/10] $name_pixels.
!if $repeat>1
  $name_scorev $[rint(10*$thisscore)/10]/10.
  !if $status=finish
    <p>$scores: $module_score.</p>
  !endif
!else
  $name_Score: $module_score/10.
!endif
<p class="wimscenter">
 <img src="$anim" alt="$name_result" />
</p>

!set m=!itemcnt $jreply
!if $gtype=polygon and $m!=6
  $name_feed
!endif
