!if $jtype=jsxgraph
  !form reply
  <div class="wimscenter">
  !read anstype/jsxgraphcurve.inc $gtype,jreply,$size,$size,$img_url
  </div>
  <div class="jsxgraph_button">
  <span onclick="efface();" class="wims_button" style="cursor:pointer;">$wims_name_erase</span>
  <input type="submit" onclick="javascript:capture();" value="$wims_name_send"/>
  </div>
  <input type="hidden" name="jreply" id="jreply" value="" />
  !formend
  !reset jreply
  !exit
!endif

!set java_reply=+cmd=reply&+jreply=
!set java_background=$img_url
!distribute item $size,$size into java_width, java_height

!read java/Input.phtml $gtype

!reset jreply
