!! what languages are supported? Edit this to your need
!! changed 4/05/2008 [added description_$lang]

!set talen=en,nl,it
!if $lang isin $talen
    !set module_title=!defof title_$lang in INDEX
    !set module_description=!defof description_$lang in INDEX
    !set module_language=$lang
    !set taal=$lang
    !set translated=1
    !read authors/jm.evers/lang/intro.$lang.phtml
!else
    !set translated=0
    !set taal=en
    !set module_description=!defof description_en in INDEX
    !read authors/jm.evers/lang/intro.en.phtml
!endif

