#if defined TARGET_tabprop
\text{name_question=Maak de volgende verhoudingstabel af}
\text{name_question2=We gaan van de ,regel naar de ,door te vermenigvuldigen met}
\text{premsec=eerste, tweede}
#endif
#if defined TARGET_OeufsdePques
\matrix{name_donne=de helft, een kwart
de helft, een derde
een kwart, een kwart
een derde, een derde
een derde, een kwart}
\text{name_enonce=Een aantal kinderen zoeken paaseieren in een tuin.
  XXXX heeft er YYYY, ZZZZ TTTT en NNNN heeft er QQQQ gevonden.}
\text{name_question=Hoeveel eieren zijn er gevonden}
\text{name_answer=Het aantal eieren}
#endif
#if defined TARGET_Biscuits
\text{name_il=}
\text{name_donne=een kwart,een derde, de helft, twee derde,twee vijfde}
\text{name_objects=koekjes, snoepjes}
\text{name_enonce1=Kinderen verdelen onderling}
\text{name_enonce2=XXXX heeft er YYYY gehad, ZZZZ TTTT en NNNN QQQQ.}
\text{name_question=Hoeveel heeft XXXX er gehad}
\text{name_answer=heeft er}
#endif
#if defined TARGET_Ages
\text{name_enonce=XXXX en YYYY zijn samen ZZZZ jaar oud. Als bekend is dat de leeftijd van
YYYY die van XXXX wat is dan de leeftijd van XXXX}
\text{name_answer=De leeftijd van}
\text{name_donne=twee keer, drie keer,vier keer,de helft van,een derde van}
#endif
#if defined TARGET_tabproportion
\text{name_question1=Maak de volgende verhoudingstabel af}
\text{name_question2=Om de getallen in de tweede rij te krijgen,
  moet je getallen in de eerste rij vermenigvuldigen met}
#endif
#if defined TARGET_tabproportion2
\text{name_question=Complète le tableau de proportionnalité suivant&nbsp;}
\text{name_question2=Le coefficient de proportionnalité
  (qui permet de passer de la première ligne à la deuxième ligne) est}
\text{name_hint1=Pour calculer <b>le coefficient</b> de proportionnalité,
  vous pouvez utiliser les calculs suivants&nbsp;}
\text{name_or=ou}
\text{name_hint2=Pour calculer <b>la quatrième case du tableau</b> de proportionnalité,
  vous pouvez utiliser le calcul suivant&nbsp;}
#endif
#if defined TARGET_tabprop2
\text{ouinon=ja,nee}
\text{name_question1=Is deze tabel een verhoudingstabel}
\matrix{name_question2=Juist, het is een verhoudingstabel.
  Met welke factor moet een getal uit de bovenste rij worden vermenigvuldigd
  Inderdaad, het is geen verhoudingstabel.
  Aan welke twee kolommen kun je zien dat dit geen verhoudingstabel is. Geef je antwoord bijvoorbeeld als}
\matrix{name_feed=Je moet de nummers van twee kolommen geven. Een enkele bewijst niets.
  Je moest nummers van twee kolommen geven, geen drie.
  Controleer. We hebben }
\text{name_feed2=Dus het is niet aan de hand van deze kolommen
  dat je hebt kunnen zien dat het geen verhoudingstabel is.}
#endif
