#if defined TARGET_tabprop
\text{name_question=Complète le tableau de proportionnalité suivant&nbsp;}
\text{name_question2=On passe de la ,ligne à la ,en multipliant par}
\text{premsec=première, seconde}
#endif
#if defined TARGET_OeufsdePques
\matrix{name_donne=la moitié, le quart
la moitié, le tiers
le quart, le quart
le tiers, le tiers
le tiers, le quart}
\text{name_enonce=Des enfants cherchent des oeufs de Pâques dans un jardin.
  XXXX en a trouvé YYYY, ZZZZ en a trouvé TTTT et NNNN en a trouvé QQQQ.}
\text{name_question=Combien d'oeufs ont-ils été trouvés&nbsp;}
\text{name_answer=Nombre d'oeufs}
#endif
#if defined TARGET_Biscuits
\text{name_il=il,elle}
\text{name_donne=le quart,le tiers,la moitié, deux tiers, deux cinquième}
\text{name_objects=biscuits, bonbons}
\text{name_enonce1=Des enfants se partagent des}
\text{name_enonce2=XXXX en a eu YYYY, ZZZZ en a eu TTTT et NNNN en a eu QQQQ.}
\text{name_question=Combien XXXX a-t-YYYY eu de ZZZZ}
\text{name_answer=en a eu}
#endif
#if defined TARGET_Ages
\text{name_enonce=XXXX et YYYY ont ZZZZ ans à eux deux. Sachant que l'âge de
  YYYY est TTTT celui de XXXX, quel est l'âge de XXXX&nbsp;}
\text{name_answer=Âge de}
\text{name_donne=le double de,le triple de,quatre fois,la moitié de,le tiers de}
#endif
#if defined TARGET_tabproportion
\text{name_question1=Complète le tableau de proportionnalité suivant&nbsp;}
\text{name_question2=Le coefficient de proportionnalité est}
#endif
#if defined TARGET_tabproportion2
\text{name_question=Complète le tableau de proportionnalité suivant&nbsp;}
\text{name_question2=Le coefficient de proportionnalité
  (qui permet de passer de la première ligne à la deuxième ligne) est}
\text{name_hint1=Pour calculer <b>le coefficient</b> de proportionnalité,
  vous pouvez utiliser les calculs suivants&nbsp;}
\text{name_or=ou}
\text{name_hint2=Pour calculer <b>la quatrième case du tableau</b> de proportionnalité,
  vous pouvez utiliser le calcul suivant&nbsp;}
#endif
#if defined TARGET_tabprop2
\text{ouinon=oui,non}
\text{name_question1=Le tableau suivant est-il un tableau de proportionnalité&nbsp;}
\matrix{name_question2=Oui, c'est un tableau de proportionnalité.
  Quel est le coefficient de proportionnalité&nbsp;
  En effet, ce n'est pas un tableau de proportionnalité&nbsp;
  donne deux numéros de colonnes qui permettent de conclure à la non proportionnalité.}
\matrix{name_feed=Il faut donner deux numéros de colonnes. Un seul ne prouve rien.
  Il faut donner deux numéros de colonnes, pas trois
  Vérifie. On a bien}
\text{name_feed2=Donc, ce n'est pas avec ces deux colonnes que vous allez
  pouvoir montrer que le tableau n'est pas un tableau de proportionnalité.}
#endif
