<b>Types d'expressions pour \(f\) </b>
<table class="wimstable">
<tr><td> 
!set wims_ref_id=confparm11
!formcheckbox confparm1 list 1 prompt \(x^n\) (\(n\geq 4\))
</td><td>
!set wims_ref_id=confparm17
!formcheckbox confparm1 list 7 prompt \(exp(x)\)
</td><td>
!set wims_ref_id=confparm113
!formcheckbox confparm1 list 13 prompt \(sh(x)\)
</td></tr>
<tr><td>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 2 prompt \(\frac{1}{x^n}\) (\(n\geq 4\))
</td><td>
!set wims_ref_id=confparm18
!formcheckbox confparm1 list 8 prompt \(ln(x)\)
</td><td>
!set wims_ref_id=confparm114
!formcheckbox confparm1 list 14 prompt \(ch(x)\)
</td></tr>
<tr><td>
!set wims_ref_id=confparm13
!formcheckbox confparm1 list 3 prompt \(x^{-n}\) (\(n\geq 4\))
</td><td>
!set wims_ref_id=confparm19
!formcheckbox confparm1 list 9 prompt \(a^x\)
</td><td>
!set wims_ref_id=confparm115
!formcheckbox confparm1 list 15 prompt \(th(x)\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm14
!formcheckbox confparm1 list 4 prompt \(\sqrt{x}\)
</td><td>
!set wims_ref_id=confparm110
!formcheckbox confparm1 list 10 prompt \(sin(x)\)
</td><td>
!set wims_ref_id=confparm116
!formcheckbox confparm1 list 16 prompt \(arcsin(x)\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm15
!formcheckbox confparm1 list 5 prompt \(\frac{1}{\sqrt{x}}\)
</td><td>
!set wims_ref_id=confparm111
!formcheckbox confparm1 list 11 prompt \(cos(x)\)
</td><td>
!set wims_ref_id=confparm117
!formcheckbox confparm1 list 17 prompt \(arccos(x)\)
</td></tr>
<tr><td>
!set wims_ref_id=confparm16
!formcheckbox confparm1 list 6 prompt \(x^r\) (\(r \in \mathbb{Q}\))
</td><td>
!set wims_ref_id=confparm112
!formcheckbox confparm1 list 12 prompt \(tan(x)\)
</td><td>
!set wims_ref_id=confparm118
!formcheckbox confparm1 list 18 prompt \(arctan(x)\)
</td></tr>
</table>
<br class="spacer" />

<b>Types d'expressions pour \(g\)</b>
<table class="wimstable">
<tr><td>
!set wims_ref_id=confparm21
!formcheckbox confparm2 list 1 prompt \(x\)
</td><td>
!set wims_ref_id=confparm24
!formcheckbox confparm2 list 4 prompt \(a x \)
</td><td>
!set wims_ref_id=confparm27
!formcheckbox confparm2 list 7 prompt \(a x + b\)
</td><td>
!set wims_ref_id=confparm210
!formcheckbox confparm2 list 10 prompt \(a x^2 + b x\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm22
!formcheckbox confparm2 list 2 prompt \(x^2\)
</td><td>
!set wims_ref_id=confparm25
!formcheckbox confparm2 list 5 prompt \(a x^2\)
</td><td>
!set wims_ref_id=confparm28
!formcheckbox confparm2 list 8 prompt \(a x^2 + b\)
</td><td>
!set wims_ref_id=confparm211
!formcheckbox confparm2 list 11 prompt \(a x^3 + b x\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm23
!formcheckbox confparm2 list 3 prompt \(x^3\)
</td><td>
!set wims_ref_id=confparm26
!formcheckbox confparm2 list 6 prompt \(a x^3\)
</td><td>
!set wims_ref_id=confparm29
!formcheckbox confparm2 list 9 prompt \(a x^3+b\)
</td><td>
!set wims_ref_id=confparm212
!formcheckbox confparm2 list 12 prompt \(a x ^3 + b x^2\)
</td></tr>
</table>
<br class="spacer" />

<b>Types d'expressions pour \(h_1\)</b>
<table class="wimstable">
<tr><td>
!set wims_ref_id=confparm31
!formcheckbox confparm3 list 1 prompt \(1\)
</td><td>
!set wims_ref_id=confparm35
!formcheckbox confparm3 list 5 prompt \(a\)
</td><td>
</td><td>
</td></tr>
<tr><td>
!set wims_ref_id=confparm32
!formcheckbox confparm3 list 2 prompt \(x\)
</td><td>
!set wims_ref_id=confparm36
!formcheckbox confparm3 list 6 prompt \(a x \)
</td><td>
!set wims_ref_id=confparm39
!formcheckbox confparm3 list 9 prompt \(a x + b\)
</td><td>
!set wims_ref_id=confparm312
!formcheckbox confparm3 list 12 prompt \(a x^2 + b x\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm33
!formcheckbox confparm3 list 3 prompt \(x^2\)
</td><td>
!set wims_ref_id=confparm37
!formcheckbox confparm3 list 7 prompt \(a x^2\)
</td><td>
!set wims_ref_id=confparm310
!formcheckbox confparm3 list 10 prompt \(a x^2 + b\)
</td><td>
!set wims_ref_id=confparm313
!formcheckbox confparm3 list 13 prompt \(a x^3 + b x\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm34
!formcheckbox confparm3 list 4 prompt \(x^3\)
</td><td>
!set wims_ref_id=confparm38
!formcheckbox confparm3 list 8 prompt \(a x^3\)
</td><td>
!set wims_ref_id=confparm311
!formcheckbox confparm3 list 11 prompt \(a x^3+b\)
</td><td>
!set wims_ref_id=confparm314
!formcheckbox confparm3 list 14 prompt \(a x ^3 + b x^2\)
</td></tr>
</table>
<br class="spacer" />

<b>Types d'expressions pour \(h_2\)</b>
<table class="wimstable">
<tr><td>
!set wims_ref_id=confparm40
!formcheckbox confparm4 list 0 prompt \(0\)
</td><td>
!set wims_ref_id=confparm41
!formcheckbox confparm4 list 1 prompt \(1\)
</td><td>
!set wims_ref_id=confparm45
!formcheckbox confparm4 list 5 prompt \(a\)
</td><td>
</td></tr>
<tr><td>
!set wims_ref_id=confparm42
!formcheckbox confparm4 list 2 prompt \(x\)
</td><td>
!set wims_ref_id=confparm46
!formcheckbox confparm4 list 6 prompt \(a x \)
</td><td>
!set wims_ref_id=confparm49
!formcheckbox confparm4 list 9 prompt \(a x + b\)
</td><td>
!set wims_ref_id=confparm412
!formcheckbox confparm4 list 12 prompt \(a x^2 + b x\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm43
!formcheckbox confparm4 list 3 prompt \(x^2\)
</td><td>
!set wims_ref_id=confparm47
!formcheckbox confparm4 list 7 prompt \(a x^2\)
</td><td>
!set wims_ref_id=confparm410
!formcheckbox confparm4 list 10 prompt \(a x^2 + b\)
</td><td>
!set wims_ref_id=confparm413
!formcheckbox confparm4 list 13 prompt \(a x^3 + b x\)
</td></tr>
<tr><td> 
!set wims_ref_id=confparm44
!formcheckbox confparm4 list 4 prompt \(x^3\)
</td><td>
!set wims_ref_id=confparm48
!formcheckbox confparm4 list 8 prompt \(a x^3\)
</td><td>
!set wims_ref_id=confparm411
!formcheckbox confparm4 list 11 prompt \(a x^3+b\)
</td><td>
!set wims_ref_id=confparm414
!formcheckbox confparm4 list 14 prompt \(a x ^3 + b x^2\)
</td></tr>
</table>
