!set wims_html_header=!append line \
<link rel="stylesheet" type="text/css" href="$htmldir/schaersvoorde.css" /> \
<!-- schaersvoorde.css ...  --> \
$my_temp_css to $wims_html_header

!if $my_html_onload != $empty
    !set wims_html_onload=!append word $ $my_html_onload $ to $wims_html_onload
!endif

!header
<script type="text/javascript"> var xcalc_window = null; </script>
<script type="text/javascript" src="$jsdir/../lang/remarks.$taal.js"></script>
<script type="text/javascript" src="$jsdir/precheck.js"></script>
<script type="text/javascript" src="$jsdir/wz_dragdrop.js"></script> 
<script type="text/javascript" src="$jsdir/nocut.js"></script>
!set wims_texsize=$mytexsize
<div style="width:100%;height:100%" id="schaersvoorde_exercise">
    <noscript>
	<h1>Please enable javascript to work with our Schaersvoorde modules</h1>
    </noscript>

    !if $status=waiting
	!read exos/form.phtml
    !else
	!if $status=retry
	    !read exos/retry.phtml
	!else
	    !read exos/answer.phtml
	    <p style="text-align:left">
	    !href exo_Again
	    <br />
	    !if $worksheet=$empty
		!href exo_Intro
		.
	    !endif
	    </p>
	!endif
    !endif
<script type="text/javascript" src="$jsdir/wz_tooltip.js"></script> 
</div>
:end
!tail

