!! menu definition file

!let res=!htmlmath (k a)^2 + (k b)^2 = (k c)^2
!let choix1=Calculer un triplet proportionnel à un triplet donné : <center>$res</center> (où (a;b;c) est un triplet pythagoricien et k un entier positif quelconque).<p>

!let res=!htmlmath ( 2ab ; b² - a² ; b² + a² )
!let choix2=Calculer un triplet pythagoricien à partir de deux nombres entiers a et b par les formules :<center>$res</center>

Ce module propose de calculer des triplets pythagoriciens par plusieurs méthodes.<br>
Les algorithmes de ce module ont été programmés par Joan, élève de 3ème au collège Longchamp à Marseille.<br>
<font size="-1">Si vous programmez d'autres algorithmes (dans un langage de 
programmation quelconque) et que vous souhaitez les faire figurer dans 
ce module, n'hésitez pas à les envoyer à l'adresse de l'auteur).</font>

<p>Choisissez une forme de calcul :<hr width=50%> <p>
!form reply

!formradio method list 1,2 prompt $choix1,$choix2


<center><input type=submit value="Envoyer"></center>
</form>
