!let res=!htmlmath ( 2ab ; b² - a² ; b² + a² )

<p>Algorithme calculant un triplet pythagoricien à partir de deux nombres entiers positifs a et b (avec a < b) : 
<center>$res</center> 

<p>Entrez les données nécessaires :<hr width=50%> <p>
!form reply

<li> 
Entrez le nombre a :<input type=text autocomplete=off name=nombre1 size=5 value=$nombre1>
</li>
<li> 
Entrez le nombre b :<input type=text autocomplete=off name=nombre2 size=5 value=$nombre2>
</li>
<center><input type=submit value="Envoyer"></center>
</form>
