!let res=!htmlmath (k a)^2 + (k b)^2 = (k c)^2

<p>Algorithme calculant un triplet proportionnel à un triplet donné : 
<center>$res</center> 
(où (a,b,c) est un triplet 
pythagoricien et k un entier positif quelconque).
<p>Entrez les données nécessaires :<hr width=50%> <p>
!form reply

<li> 
Entrez le nombre k :<input type=text autocomplete=off name=k size=5 value=$k>
</li>
<li> 
Entrez le nombre a du triplet pythagoricien :<input type=text autocomplete=off name=nombre1 size=5 value=$nombre1>
</li>
<li> 
Entrez le nombre b du triplet pythagoricien :<input type=text autocomplete=off name=nombre2 size=5 value=$nombre2>
</li>
<li> 
Entrez le nombre c du triplet pythagoricien :<input type=text autocomplete=off name=nombre3 size=5 value=$nombre3>
</li>
<center><input type=submit value="Envoyer"></center>
</form>
