#if defined TARGET_moho0 || defined TARGET_moho1 || defined TARGET_etagere1 || defined TARGET_etagere2 || defined TARGET_avion || defined TARGET_horizon1 || defined TARGET_horizon2 || defined TARGET_horizon3
\author{Bernadette, Perrin-Riou}
\email{bernadette.m.riou@orange.fr}
#else
# if defined TARGET_rugby
\author{Marie-Claude, David; Guillaume, Wuthrich}
\email{marie-claude.david@math.u-psud.fr}
# else
\author{Dingyu,XIAO}
\email{xiao@unice.fr}
# endif
#endif
