#if defined TARGET_Arbreabattu
# define TITRE_nl Omgeknakte boom
#endif
#if defined TARGET_Cerfvolant
# define TITRE_nl Vlieger
#endif
#if defined TARGET_Mdiane
# define TITRE_nl Zwaartelijn
#endif
#if defined TARGET_Puits
# define TITRE_nl Put
#endif
#if defined TARGET_Trianglerectan
# define TITRE_nl Omgeschreven cirkel
#endif
#if defined TARGET_rugby
# define TITRE_nl Transformation au Rugby
#endif
#if defined TARGET_moho0 || defined TARGET_moho1
# define TITRE_nl Moho
#endif
#if defined TARGET_etagere1 || defined TARGET_etagere2
# define TITRE_nl Étagère
#endif
#if defined TARGET_avion
# define TITRE_nl Avion
#endif
#if defined TARGET_bird
# define TITRE_nl Oiseau
#endif
#if defined TARGET_horizon1 || defined TARGET_horizon2 || defined TARGET_horizon3
# define TITRE_nl Horizon
#endif
