#if defined TARGET_Arbreabattu
# define TITRE_it Albero abbattuto
#endif
#if defined TARGET_Cerfvolant
# define TITRE_it Aquilone
#endif
#if defined TARGET_Mdiane
# define TITRE_it Mediana
#endif
#if defined TARGET_Puits
# define TITRE_it Pozzo
#endif
#if defined TARGET_Trianglerectan
# define TITRE_it Triangolo rettangolo e cerchio circoscritto
#endif
#if defined TARGET_rugby
# define TITRE_it Trasformazione nel rugby
#endif
#if defined TARGET_moho0 || defined TARGET_moho1
# define TITRE_it Moho
#endif
#if defined TARGET_etagere1 || defined TARGET_etagere2
# define TITRE_it Étagère
#endif
#if defined TARGET_avion
# define TITRE_it Avion
#endif
#if defined TARGET_bird
# define TITRE_it Oiseau
#endif
#if defined TARGET_horizon1 || defined TARGET_horizon2 || defined TARGET_horizon3
# define TITRE_it Horizon
#endif
