#if defined TARGET_Arbreabattu
# define TITRE Arbre abattu
#endif
#if defined TARGET_Cerfvolant
# define TITRE Cerf-volant
#endif
#if defined TARGET_Mdiane
# define TITRE Médiane
#endif
#if defined TARGET_Puits
# define TITRE Puits
#endif
#if defined TARGET_Trianglerectan
# define TITRE Triangle rectangle et cercle circonscrit
#endif
#if defined TARGET_rugby
# define TITRE Transformation au Rugby
#endif
#if defined TARGET_moho0 || defined TARGET_moho1
# define TITRE Moho
#endif
#if defined TARGET_etagere1 || defined TARGET_etagere2
# define TITRE Étagère
#endif
#if defined TARGET_avion
# define TITRE Avion
#endif
#if defined TARGET_bird
# define TITRE Oiseau
#endif
#if defined TARGET_horizon1 || defined TARGET_horizon2 || defined TARGET_horizon3
# define TITRE Horizon
#endif
