#if defined TARGET_long2tri
# define TITRE Deux triangles
#endif
#if defined TARGET_anglesin || defined TARGET_anglecos || defined TARGET_angletan
# define TITRE Calculer la mesure d'un angle
#endif
#if defined TARGET_calcrap
# define TITRE Calculette et trigonométrie
#endif
#if defined TARGET_formule
# define TITRE Trigo (choix de la formule)
#endif
#if defined TARGET_longsin || defined TARGET_longcos || defined TARGET_longtan
# define TITRE Calculer une longueur
#endif
#if defined TARGET_vocabulaire1 || defined TARGET_vocabulaire2 || defined TARGET_vocabulaire3
# define TITRE Vocabulaire
#endif
