!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur .....

!read oef/$module_language/intromenu.phtml
<table border=1 background="\imagedir/800px-Moon_and_red_blue_haze.jpg"><tr><td>
Les images utilisées dans ce module ont été recopiées du site
<a href="http://fr.wikipedia.org/"> WikiPedia français</a>, et ont été mises dans le Domaine Public 
par la NASA.
</td></tr></table>
<font size="2">
Mieux voir toutes ces images : 
<a href="http://fr.wikipedia.org/wiki/Lune" target="_new">dans l'article sur la lune</a>
<a href="http://fr.wikipedia.org/wiki/Syst%C3%A8me_solaire" target="_new">dans l'article sur le système solaire</a>
</font>
!tail
