#include "lang_title_fr.inc"

#if defined TARGET_oeftracecerc1 || defined TARGET_oefcercle1 || defined TARGET_oefconstcer1
# define NUM 1
#endif
#if defined TARGET_oeftracecerc2 || defined TARGET_oefcercle2 || defined TARGET_oefconstcer2
# define NUM 2
#endif
#if defined TARGET_oeftracecerc3 || defined TARGET_oefcercle3 || defined TARGET_oefconstcer3
# define NUM 3
#endif
#if defined TARGET_oeftracecerc4 || defined TARGET_oefcercle4 || defined TARGET_oefconstcer4
# define NUM 4
#endif
#if defined TARGET_oeftracecerc5 || defined TARGET_oefcercle5 || defined TARGET_oefconstcer5
# define NUM 5
#endif

\title{TITRE NUM}
