#if defined TARGET_oefconstcer1 || defined TARGET_oefconstcer2 || defined TARGET_oefconstcer3 || defined TARGET_oefconstcer4 || defined TARGET_oefconstcer5
# define TITRE Programme de construction
#endif
#if defined TARGET_oeftracecerc1 || defined TARGET_oeftracecerc2 || defined TARGET_oeftracecerc3 || defined TARGET_oeftracecerc4 || defined TARGET_oeftracecerc5
# define TITRE Tracer un cercle
#endif
#if defined TARGET_oefcercle1 || defined TARGET_oefcercle2 || defined TARGET_oefcercle3 || defined TARGET_oefcercle4 || defined TARGET_oefcercle5
# define TITRE Cercle
#endif
