!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les nombres premiers,
basé sur le document : <em>Bulletin officiel n° 22 du 29 mai 2019.</em>
<ul><li>Attendus de fin d'année en français et mathématiques
</li><li>Repères annuels de progression en français, mathématiques et enseignement moral et civique
</li></ul>
Objectifs :
<ul><li>Déterminer la liste des nombres premiers inférieurs à 30 ou à 100.
</li><li>Déterminer les diviseurs premiers d'un ou deux entiers
</li></ul>
<b>Remarque :</b> Réutilisation des connaissances sur les critères de divisibilité par 2, 3 et 5
<div class="wims_credits">
Élaboré avec la communauté MutuWIMS.</div>

!read oef/intromenu.phtml
!tail
