!set n=!recordcnt src/data
!reset objlist
!for i=1 to $n
 !set l=!record $i of src/data
 !set l=!line 1 of $l
 !set objlist=!append item $l to $objlist
!next i

<tr><td align=center>Soorten objecten:
</td><td>
!formselect confparm1 from 1 to $n prompt $objlist
</td>
<tr><td align=center>Soorten  bewerkingen:
</td><td>
!formselect confparm2 from 1 to 4 prompt alleen optellen,\
	optellen en vermenigvuldigen,vermenigvuldigen en optellen, alleen vermenigvuldigen
