!header
!read Exindex
Je kunt deze module inzetten als een spelletje of als een oefening.<br>
In beide gevallen is deze module een krachtig hulpmiddel bij het
leren rekenen.<br>
Voor het invullen van getallen in de tabel, wordt
zeer snel rekenwerk vereist 
<p>
Met de diverse instellingen, kunnen de sommen worden gebruikt door
leerlingen van af dee lagere school (optellen,aftrekken) tot de hogere klassen
van de middelbare school.
<p>
Veel plezier !!
!read oef/intromenu.phtml
!tail

