!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set wims_html_mode=li
!set confparm2=AG

<tr><th>Pour les suites géométriques :</th>
<td>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio  confparm1 list P, R prompt suites à termes positifs, suites à termes réels
</ul>
<i>Si rien n'est coché, il y aura aléatoirement des suites à termes positifs et des suites à termes réels.</i>
</td>
<tr><th>Pour les exercices non spécifiques, vos élèves connaissent :</th>
<td>
!set wims_html_mode=li
<ul class="wims_nopuce">
!formradio  confparm2 list A, G, AG prompt les suites arithmétiques, les suites géométriques, les deux
</ul>
</td>
