#if defined TARGET_oefaxesym1 || defined TARGET_oefaxesym2 || defined TARGET_oefaxesym3 || defined TARGET_oefaxesym4 || defined TARGET_oefaxesym5
# define TITRE Axe de symétrie
#endif
#if defined TARGET_oefutimed1 || defined TARGET_oefutimed2 || defined TARGET_oefutimed3 || defined TARGET_oefutimed4 || defined TARGET_oefutimed5
# define TITRE Utiliser la médiatrice
#endif
#if defined TARGET_oefutiequi1 || defined TARGET_oefutiequi2 || defined TARGET_oefutiequi3 || defined TARGET_oefutiequi4 || defined TARGET_oefutiequi5
# define TITRE Utiliser l'équidistance
#endif
#if defined TARGET_oefutibiss1 || defined TARGET_oefutibiss2 || defined TARGET_oefutibiss3 || defined TARGET_oefutibiss4 || defined TARGET_oefutibiss5
# define TITRE Utiliser la bissectrice
#endif
#if defined TARGET_oefsymfig1 || defined TARGET_oefsymfig2 || defined TARGET_oefsymfig3 || defined TARGET_oefsymfig4 || defined TARGET_oefsymfig5
# define TITRE Construction du symétrique
#endif
#if defined TARGET_symaxrec1 || defined TARGET_symaxrec2 || defined TARGET_symaxrec3 || defined TARGET_symaxrec4 || defined TARGET_symaxrec5
# define TITRE Reconnaitre une symétrie axiale
#endif
#if defined TARGET_symaxplac1 || defined TARGET_symaxplac2 || defined TARGET_symaxplac3 || defined TARGET_symaxplac4 || defined TARGET_symaxplac5
# define TITRE Placer le symétrique
#endif
#if defined TARGET_oefvocsym1 || defined TARGET_oefvocsym2 || defined TARGET_oefvocsym3 || defined TARGET_oefvocsym4 || defined TARGET_oefvocsym4
# define TITRE Phrase à compléter
#endif
#if defined TARGET_oefsymraison1 || defined TARGET_oefsymraison2 || defined TARGET_oefsymraison3 || defined TARGET_oefsymraison4 || defined TARGET_oefsymraison5
# define TITRE Raisonnements
#endif
#if defined TARGET_oefsyminst1 || defined TARGET_oefsyminst2 || defined TARGET_oefsyminst3 || defined TARGET_oefsyminst4 || defined TARGET_oefsyminst5
#define TITRE Instruments
#endif
#if defined TARGET_oefsymconst1 || defined TARGET_oefsymconst2 || defined TARGET_oefsymconst3 || defined TARGET_oefsymconst4 || defined TARGET_oefsymconst5
#define TITRE Construction
#endif
#if defined TARGET_oefbissect1 || defined TARGET_oefbissect2 || defined TARGET_oefbissect3 || defined TARGET_oefbissect4 || defined TARGET_oefbissect5
# define TITRE Définition de la bissectrice
#endif
#if defined TARGET_oefaxesym1 || defined TARGET_oefaxesym2 || defined TARGET_oefaxesym3 || defined TARGET_oefaxesym4 || defined TARGET_oefaxesym5
# define TITRE Axe de symétrie
#endif
#if defined TARGET_oefconstaxe1 || defined TARGET_oefconstaxe2 || defined TARGET_oefconstaxe3 || defined TARGET_oefconstaxe4 || defined TARGET_oefconstaxe5
# define TITRE Compléter une symétrie
#endif
#if defined TARGET_oefcoder1 || defined TARGET_oefcoder2 || defined TARGET_oefcoder3 || defined TARGET_oefcoder4 || defined TARGET_oefcoder5
# define TITRE Coder
#endif
#if defined TARGET_oefmediat1 || defined TARGET_oefmediat2 || defined TARGET_oefmediat3 || defined TARGET_oefmediat4 || defined TARGET_oefmediat5
# define TITRE Définition de la médiatrice
#endif
