<div class="wims_columns">
  <div class="medium_size">
    <img src="\fig" alt="">
  </div>
  <div class="medium_size">
  <ul>
  <li>La droite (d) est la médiatrice du segment [AB].</li>
  <li>Le point C appartient à la droite (d).</li>
  </ul>
  Donner la nature du triangle ABC en justifiant.
  </div>
</div>
Placer les étiquettes dans le bon ordre :
<ul>
<li>\embed{r1,\size}</li>
<li>\embed{r2,\size}</li>
<li>\embed{r3,\size}</li>
<li>\embed{r4,\size}</li>
</ul>
