#if defined TARGET_cubrt
/* note for translators: keep commas */
\text{name_statement=Encuentre una raíz cúbica \(w\) del número complejo,
entregando su parte real y parte imaginaria}
#endif

#if defined TARGET_tworoots || defined TARGET_tworoots2
\text{impur=imaginario puro}
\text{real=real}
\text{zero=igual a cero}
\text{nor=ni real ni imaginario puro}
#endif

#if defined TARGET_tworoots
/* note for translators: keep commas */
\text{name_statement=Sean,las dos raíces de un polinomio,donde \(p \) es,y \(q\) es real. Supongamos que \(z_1\) y \(z_2\) no son reales ni imaginarios puros. Luego el número \(z_1 - z_2\) es}
#endif

#if defined TARGET_tworoots2
/* note for translators: keep commas */
\text{name_statement=Sean,las dos raíces de un polinomio,donde,es un número real. Luego \(z_1 - z_2\) es un número}
#endif

#if defined TARGET_eqmod
\text{name_statement=Resuelva en \({}\mathbb{C}\) la ecuación}
/* note for translators: keep commas */
\text{name_instruction=Escriba,si piensa que la ecuación no tiene solución}
/* note for translators: keep commas */
\text{name_hint=En el plano complejo, el origen y los puntos que corresponden a,deben formar un  rombo (¿por qué?)}
#endif

#if defined TARGET_modsum
\text{name_yesno=Sí,No}
\text{name_statement=¿Existen números complejos \(z_1\) y \(z_2\) tales que}
\text{name_hint=¿Cuáles son las condiciones sobre los largos de los 3 lados de un triángulo?}
\text{name_answer=Su respuesta}
#endif
#if defined TARGET_modsum2
\text{name_and=y}
/* note for translators: keep commas */
\text{name_statement=Sean,dos números complejos con,grados,Calcule el módulo de}
\text{name_hint=Recuerde el teorema del coseno: si un triángulo tiene tres lados de largos \(a\), \(b\), \(c\) y si denotamos por
\(A\) el ángulo opuesto al lado \(a\), entonces}
#endif

#if defined TARGET_sumofj
/* note for translators: keep commas */
\text{name_statement=Sea,Calcule la suma}
#endif

#if defined TARGET_cbrt
\text{name_style=un complejo tal que,una raíz (compleja) del polinomio}
/* note for translators: keep commas */
????
\text{name_statement=Sea,¿Cuál es el número}
#endif

#if defined TARGET_arggiven
/* note for translators: keep commas */
\text{name_statement=Calcule la parte real e imaginaria del número complejo  \(z\) que tiene a, como módulo y que tiene a,como un argumento}
#endif

#if defined TARGET_pentaroot
/* note for translators: keep commas */
\text{name_statement=Sean,las cuatro raíces (complejas) del polinomio,¿Cuál es el número}
#endif

#if defined TARGET_argask
\text{name_statement=Entregue el módulo y un argumento del número complejo}
\text{name_condition=es un argumento de}
#endif

#if defined TARGET_quadouble
/* note for translators: keep commas */
\text{name_statement=¿Para qué valor de \(w\) el polinomio,tiene una raíz doble (compleja)}
\text{name_answer=La raíz doble}
#endif

#if defined TARGET_quadouble2
\text{name_and=y}
/* note for translators: keep commas */
\text{name_statement=¿Para qué valores reales de,el polinomio,tiene una raíz doble (compleja)}
\text{name_answer=La raíz doble}
#endif

#if defined TARGET_argsum
/* note for translators: keep commas */
\text{name_statement=Sean, Entregue el módulo y un argumento de}
\text{name_condition=es un argumento de}
#endif

#if defined TARGET_pythagorus || defined TARGET_pythagorus2
\text{name_and=y}
/* note for translators: keep commas */
\text{name_statement=Sean,dos números complejos con,¿Cuál es el valor de}
\text{name_answer=Su respuesta}
\text{name_hint=¡Piense en Pitágoras! ¿Cuál es la diferencia entre}
#endif

#if defined TARGET_fraction || defined TARGET_fraction2
\text{name_statement=Calcule la parte real e imaginaria del siguiente número complejo}
\text{name_answer1=Parte real}
\text{name_answer2=Parte imaginaria}
#endif

#if defined TARGET_rootcoef
\text{name_statement1=Sea \(P(X)=X^2 + p X + q\) un polinomio con coeficientes reales
\(p\) y \( q\). Se sabe que \(P\) tiene una raíz compleja \( z\) cuya parte imaginaria es igual a}
\text{name_statement2=En este caso, hay una relación entre los coeficientes
\( p\) y \(q\). Determine esta relación entregando \( q\) en función de \(p\).}
/* note for translators: keep commas */
\text{name_solution=Si,la otra raíz de \(P\) es,Entonces,o,Y}
#endif



#if defined TARGET_sqrt
/* note for translators: keep commas */
\text{name_statement=Encuentre una raíz cuadrada \(w\) del número complejo,
entregando su parte real y parte imaginaria}
#endif

#if defined TARGET_modmax
/* note for translators: keep commas */
\text{name_statement=Entre todos los complejos \(z\) de módulo,
encuentre aquel para el cual el módulo de,es maximal}
#endif
#if defined TARGET_maxmod
\text{name_list_maxmin=máximo,mínimo}
/* note for translators: keep commas */
\text{name_statement=¿Cuál es el,del módulo,cuando \(z\\) es un número complejo con}
\text{name_answer=del módulo}
#endif

#if defined TARGET_Trianglequilat
\text{name_and=y}
/* note for translators: keep commas */
\text{name_statement=Si \(A\) y \(B\) son los puntos en el plano complejo que corresponden a,
encuentre el número complejo \(M\) tal que el triángulo \(ABM\) es equilátero}
\text{name_hint=\(AM\) es la imagen de \(AB\) por una rotación. ¿Cuál rotación?}
#endif

#if defined TARGET_quadpoly
\text{name_statement=Calcule las dos raíces del polinomio}
\text{name_instruction=Puede ingresar las dos raíces \(r1\) y \(r2\) en cualquier orden.}
\text{name_condition1=es una raíz}
\text{name_condition2=es otra raíz}
#endif

#if defined TARGET_sumofi
\text{name_statement=Calcule la suma}
#endif

#if defined TARGET_suminv
/* note for translators: keep commas */
\text{name_statement=Sea \(z\) un número complejo con,Calcule}
#endif

#if defined TARGET_sumroot
/* note for translators: keep commas */
\text{name_statement=Sea,¿Cuál es el valor de}
\text{name_hint=es una raíz del polinomio}
#endif


#if defined TARGET_powerconj
/* note for translators: keep commas */
\text{name_statement=¿Cuántos números complejos \(z\) hay tales que,es igual al conjugado de \(z\)}
\text{name_answer=El número}
/* note for translators: keep commas */
\text{name_solution=Sea \(w\) el conjugado de \(z\). Notemos primero que,
implica \(|z|=1\) o \(z=0\\). Cuando \(|z|=1\) tenemos,
y por lo tanto los números complejos \(z\) que verifican la condición del problema son exactamente las raíces del polinomio}
\text{name_or=o}
#endif
