#if defined TARGET_cubrt
# define TITLE_fr Racine cubique
#endif
#if defined TARGET_tworoots2
# define TITLE_fr Deux racines II
#endif
#if defined TARGET_eqmod
# define TITLE_fr Équation avec module
#endif
#if defined TARGET_modsum
# define TITLE_fr Module de somme
#endif
#if defined TARGET_sumofj
# define TITLE_fr Somme de j
#endif
#if defined TARGET_cbrt
# define TITLE_fr CBRT
#endif
#if defined TARGET_arggiven
# define TITLE_fr Argument donné
#endif
#if defined TARGET_pentaroot
# define TITLE_fr Pentaroot
#endif
#if defined TARGET_argask
# define TITLE_fr Argument demandé
#endif
#if defined TARGET_quadouble
# define TITLE_fr Quadratique racine double
#endif
#if defined TARGET_quadouble2
# define TITLE_fr Quadratique racine double II
#endif
#if defined TARGET_argsum
# define TITLE_fr Argument de somme
#endif
#if defined TARGET_pythagorus2
# define TITLE_fr Pythagore II
#endif
#if defined TARGET_fraction2
# define TITLE_fr Fraction II
#endif
#if defined TARGET_rootcoef
# define TITLE_fr Racine et coefficients
#endif
#if defined TARGET_pythagorus
# define TITLE_fr Pythagore
#endif
#if defined TARGET_sqrt
# define TITLE_fr Racine carrée
#endif
#if defined TARGET_fraction
# define TITLE_fr Fraction
#endif
#if defined TARGET_modmax
# define TITLE_fr Module maximal
#endif
#if defined TARGET_Trianglequilat
# define TITLE_fr Triangle équilatéral
#endif
#if defined TARGET_quadpoly
# define TITLE_fr Racines d'un polynôme quadratique
#endif
#if defined TARGET_sumofi
# define TITLE_fr Somme de i
#endif
#if defined TARGET_suminv
# define TITLE_fr Somme avec inverse
#endif
#if defined TARGET_sumroot
# define TITLE_fr Somme de racines d'unité
#endif
#if defined TARGET_tworoots
# define TITLE_fr Deux racines
#endif
#if defined TARGET_modsum2
# define TITLE_fr Module de somme II
#endif
#if defined TARGET_powerconj
# define TITLE_fr Puissance conjuguée
#endif
#if defined TARGET_maxmod
# define TITLE_fr Maximum de module
#endif

\title{TITLE_fr}
