#if defined TARGET_cubrt
/* note for translators: keep commas */
\text{name_statement=Bepaal het re&euml;le en imaginaire deel van de vierkants wortel
  \(w\) van het complexe getal}
#endif
#if defined TARGET_tworoots || defined TARGET_tworoots2
\text{impur=puur imaginair}
\text{real=ree&euml;l}
\text{zero=gelijk aan nul}
\text{nor=niet ree&euml;l en niet imaginair}
#endif
#if defined TARGET_tworoots
/* note for translators: keep commas */
\text{name_statement=Laat,de twee wortels van de polynoom,
  met daar in \(p \) is,en  met daar in \(q\)  als een ree&euml;l getal.
  Suppose that \(z_1) and \(z_2) are neither real nor pure imaginary.
  Dab is  \(z_1 - z_2) een ____________ getal. }
#endif
#if defined TARGET_tworoots2
/* note for translators: keep commas */
\text{name_statement=Let,be the two roots of a polynomial,where,is a real number.
  Then \(z_1 - z_2\) is a number}
#endif
#if defined TARGET_eqmod
\text{name_statement=Los de onderstaande vergelijking op in \(\CC\)}
/* note for translators: keep commas */
\text{name_instruction=Geef,als je denkt dat er geen oplossing mogelijk is}
/* note for translators: keep commas */
\text{name_hint=In het complexe vlak, vormen de Oorsprong en punten,een gelijkzijdige driehoek...(waarom?)}
#endif
#if defined TARGET_modsum
\text{name_yesno=Ja,Nee}
\text{name_statement=Bestaan er twee complexe getallen \(z_1\) en \(z_2\) zo dat geldt}
\text{name_hint=Welke voorwaarden zijn er voor de lengtes van de 3 zijden van een driehoek ...?}
\text{name_answer=Je antwoord}
#endif
#if defined TARGET_modsum2
\text{name_and=en}
/* note for translators: keep commas */
\text{name_statement=Laa,wee complexe getallen zijn meth,graden,Bepaal de modulus van}
\text{name_hint=Denk aan de cosinus:
  Als een driehoek met zijden \(a\), \(b\), \(c\),
  en met \(A\) als de hoek tegenover zijde \(a\), dan geldt}
#endif
#if defined TARGET_sumofj
/* note for translators: keep commas */
\text{name_statement=Gegeven, Bereken de som}
#endif
#if defined TARGET_cbrt
\text{name_style=een complex getal zijn&sbquo; zo dat,een (complexe) wortel
  zijn van de polynoom}
/* note for translators: keep commas */
????
\text{name_statement=Laat,Wat is dan het getal waarvoor geldt}
#endif
#if defined TARGET_arggiven
/* note for translators: keep commas */
\text{name_statement=CBepaal het re&euml;le en imaginaire deel van het complexe getal
  \(z\) met als modulus,en argument}
#endif
#if defined TARGET_pentaroot
/* note for translators: keep commas */
\text{name_statement=Laat,de vier (complexe) wortels zijn van de polynoom,
  Wat is dan het getal w waarvoor geldt}
#endif
#if defined TARGET_argask
\text{name_statement=Geef Modulus en Argument van het complexe getal}
\text{name_condition=is het argument van}
#endif
#if defined TARGET_quadouble
/* note for translators: keep commas */
\text{name_statement=Voor welke -complexe- waarde van \(w\) heeft de polynoom,
  een complexe dubbel wortel}
\text{name_answer=De dubbele wortel}
#endif
#if defined TARGET_quadouble2
\text{name_and=and}
/* note for translators: keep commas */
\text{name_statement=FVoor welke re&euml;le waarden van,heeft de polynoom
  ,een (complexe) dubbel wortel}
\text{name_answer=De dubbele wortel}
#endif
#if defined TARGET_argsum
/* note for translators: keep commas */
\text{name_statement=Gegeven,Geef modulus en argument vanf}
\text{name_condition=is een argument van }
#endif
#if defined TARGET_pythagorus || defined TARGET_pythagorus2
\text{name_and=en}
/* note for translators: keep commas */
\text{name_statement=Laat,wee complexe getallen zijn met,Wat is dan de waarde van}
\text{name_answer=Je antwoord}
\text{name_hint=Denk aan Pythagoras! Wat is het verschil tussen}
#endif
#if defined TARGET_fraction || defined TARGET_fraction2
\text{name_statement=Bepaal het re&euml;le en imaginaire deel van het onderstaande complexe getal}
\text{name_answer1=Re&euml;le deel}
\text{name_answer2=Imaginaire deel}
#endif
#if defined TARGET_rootcoef
\text{name_statement1=Laat \(P(X)=X^2 + p X + q\)en polynoom zijn met re&euml;le co&euml;fficienten
  \(p\) and \( q\). Gegeven is dat \(P\) een complexe wortel heeft \( z\) waarvan het imaginaire gedeelte gelijk is aan}
\text{name_statement2=Dan is er een relatie tussen de co&euml;fficienten
  \( p\) en \(q\). Bepaal deze realatie, en geeft\( q\) als functie van \(p\).}
/* note for translators: keep commas */
\text{name_solution=Als,tdan is de andere wortel van \(P\),En dus is,of,En}
#endif
#if defined TARGET_sqrt
/* note for translators: keep commas */
\text{name_statement=Bepaal het re&euml;le en imaginaire deel van de vierkants wortel
  \(w\) van het complexe getal}
#endif
#if defined TARGET_modmax
/* note for translators: keep commas */
\text{name_statement=Zoek uit complexe getallen \(z\) met,
  het complexe getal waarvoor geldt dat de modulus,maximaal is}
#endif
#if defined TARGET_maxmod
\text{name_list_maxmin=maximum,minimum}
/* note for translators: keep commas */
\text{name_statement=Wat is het,van de modulus,waarin \(z\) een complex getal is met}
\text{name_answer=of module}
#endif
#if defined TARGET_Trianglequilat
\text{name_and=en}
/* note for translators: keep commas */
\text{name_statement=Laat \(A\) en \(B\) punten zijn in het complexe vlak corresponderend met,
  Bepaal het complexe getal van het punt \(M\) zo dat de driehoek \(ABM\) gelijkzijdig is}
\text{name_hint=\(AM) is het beeld van \(AB) bij een rotatie. Welke rotatie?}
#endif
#if defined TARGET_quadpoly
\text{name_statement=Bepaal de twee wortels van de polynoom}
\text{name_instruction=e mag de twee wortels  \(r1\) and \(r2\) in elke volgorde ingeven.}
\text{name_condition1=is een wortel}
\text{name_condition2=is de andere wortel}
#endif
#if defined TARGET_sumofi
\text{name_statement=Bereken de som}
#endif
#if defined TARGET_suminv
/* note for translators: keep commas */
\text{name_statement=Gegeven het complexe getal \(z\) met,Bepaal het getal}
#endif
#if defined TARGET_sumroot
/* note for translators: keep commas */
\text{name_statement=Gegeven,Wat is de waarde}
\text{name_hint=is een wortel van de polynoom}
#endif
#if defined TARGET_powerconj
/* note for translators: keep commas */
\text{name_statement=Hoeveel complexe getallen \(z\) zijn er waarvoor geldt dat,
  is aan de geconjungeerde van \(z\)}
\text{name_answer=e antwoord}
/* note for translators: keep commas */
\text{name_solution=Laat \(w\) de geconjungeerde (toegevoegde) zijn van \(z\).
  We merken op datt,
  betekend \(|z|=1\) or 0. Wanneer \(|z|=1\) geldt,
 Daarom is het het antwoord op de vraag precies gelijk aan het aantal wortels
  van de polynoom uitgezonderd 0}
\text{name_or=or}
#endif
