#if defined TARGET_cubrt
/* note for translators: keep commas */
\text{name_statement=Find a cubic root \(w\) of the complex number,
by giving its real part and imaginary part}
#endif
#if defined TARGET_tworoots || defined TARGET_tworoots2
\text{impur=pure imaginary}
\text{real=real}
\text{zero=equal to zero}
\text{nor=neither real nor pure imaginary}
#endif
#if defined TARGET_tworoots
/* note for translators: keep commas */
\text{name_statement=Let,be the two roots of a polynomial,
  where \(p \) is,and \(q\) is real. Suppose that \(z_1) and \(z_2) are neither real nor pure imaginary. Then the number \(z_1 - z_2) is}
#endif
#if defined TARGET_tworoots2
/* note for translators: keep commas */
\text{name_statement=Let,be the two roots of a polynomial,where,is a real number.
  Then \(z_1 - z_2\) is a number}
#endif
#if defined TARGET_eqmod
\text{name_statement=Solve in \(\mathbb{C}\) the equation}
/* note for translators: keep commas */
\text{name_instruction=Type,if you think that the equation has no solution}
/* note for translators: keep commas */
\text{name_hint=In the complex plane,the origin and the points corresponding to,should form a rhombus (why?)}
#endif
#if defined TARGET_modsum
\text{name_yesno=Yes,No}
\text{name_statement=Do there exist two complex numbers \(z_1\) and \(z_2\) such that}
\text{name_hint=What are the conditions on the lengths of the 3 sides of a triangle?}
\text{name_answer=Your answer}
#endif
#if defined TARGET_modsum2
\text{name_and=and}
/* note for translators: keep commas */
\text{name_statement=Let,be two complex numbers with,degrees,Compute the module of}
\text{name_hint=Remember the Cosine Theorem: if a triangle has three sides
of lengths \(a\), \(b\), \(c\) and if one denotes by
\(A\) the angle opposite to the side \(a\), then}
#endif
#if defined TARGET_sumofj
/* note for translators: keep commas */
\text{name_statement=Let,Compute the sum}
#endif
#if defined TARGET_cbrt
\text{name_style=a complex number such that,a (complex) root of the polynomial}
/* note for translators: keep commas */
????
\text{name_statement=Let,What is the number}
#endif
#if defined TARGET_arggiven
/* note for translators: keep commas */
\text{name_statement=Compute the real part and imaginary part of the complex number \(z\) having,as module and having,as an argument}
#endif
#if defined TARGET_pentaroot
/* note for translators: keep commas */
\text{name_statement=Let,be the 4 (complex) roots of the polynomial,What is the number}
#endif
#if defined TARGET_argask
\text{name_statement=Give the module and argument of the complex number}
\text{name_condition=is an argument of}
#endif
#if defined TARGET_quadouble
/* note for translators: keep commas */
\text{name_statement=For which complex value of \(w\) the polynomial,has a (complex) double root}
\text{name_answer=The double root}
#endif
#if defined TARGET_quadouble2
\text{name_and=and}
/* note for translators: keep commas */
\text{name_statement=For which real values of,the polynomial,has a (complex) double root}
\text{name_answer=The double root}
#endif
#if defined TARGET_argsum
/* note for translators: keep commas */
\text{name_statement=Let,Give the module and an argument of}
\text{name_condition=is an argument of}
#endif
#if defined TARGET_pythagorus || defined TARGET_pythagorus2
\text{name_and=and}
/* note for translators: keep commas */
\text{name_statement=Let,be two complex numbers with,What is the value of}
\text{name_answer=Your answer}
\text{name_hint=Think of Pythagorus! What is the difference between}
#endif
#if defined TARGET_fraction || defined TARGET_fraction2
\text{name_statement=Compute the real part and imaginary part of the following complex number}
\text{name_answer1=Real part}
\text{name_answer2=Imaginary part}
#endif
#if defined TARGET_rootcoef
\text{name_statement1=Let \(P(X)=X^2 + p X + q\) be a polynomial with real coefficients
\(p\) and \( q\). One knows that \(P\) has a complex root \( z\) whose imaginary part is equal to}
\text{name_statement2=In this case, there is a relation between the coefficients
\( p\) and \(q\). Determine this relation by giving \( q\) as a function of \(p\).}
/* note for translators: keep commas */
\text{name_solution=If,the other root of \(P\) is,Hence,or,And}
#endif
#if defined TARGET_sqrt
/* note for translators: keep commas */
\text{name_statement=Find a square root \(w\) of the complex number,
by giving its real part and imaginary part}
#endif
#if defined TARGET_modmax
/* note for translators: keep commas */
\text{name_statement=Among all complex numbers \(z\) with module,
find the one for which the module of,is maximal}
#endif
#if defined TARGET_maxmod
\text{name_list_maxmin=maximum,minimum}
/* note for translators: keep commas */
\text{name_statement=What is the,of the module,where \(z\) is a complex number with}
\text{name_answer=of module}
#endif
#if defined TARGET_Trianglequilat
\text{name_and=and}
/* note for translators: keep commas */
\text{name_statement=If \(A\) and \(B\) are points in the complex plane corresponding to,
find the complex number of the point \(M\) such that the triangle \(ABM\) is equilateral}
\text{name_hint=\(AM) is the image of \(AB\) by a rotation. Which rotation?}
#endif
#if defined TARGET_quadpoly
\text{name_statement=Compute the two roots of the polynomial}
\text{name_instruction=You may enter the two roots \(r1\) and \(r2\) in any order.}
\text{name_condition1=is a root}
\text{name_condition2=is another root}
#endif
#if defined TARGET_sumofi
\text{name_statement=Compute the sum}
#endif
#if defined TARGET_suminv
/* note for translators: keep commas */
\text{name_statement=Let \(z\) be a complex number with,Compute}
#endif
#if defined TARGET_sumroot
/* note for translators: keep commas */
\text{name_statement=Let,What is the value of}
\text{name_hint=is a root of the polynomial}
#endif
#if defined TARGET_powerconj
/* note for translators: keep commas */
\text{name_statement=How many complex numbers \(z\)  there are such that,is equal to the conjugate of \(z\)}
\text{name_answer=The number}
/* note for translators: keep commas */
\text{name_solution=Let \(w\) be the conjugate of \(z\). We notice first that,
implies \(|z|=1\) or 0. When \(|z|=1\) we have,
therefore the complex numbers \(z\) verifying the condition of the problem are exactly the roots of the polynomial}
\text{name_or=or}
#endif
