#if defined TARGET_cubrt
# define TITLE_es Raíz cúbica
#endif
#if defined TARGET_tworoots2
# define TITLE_es Dos raíces II
#endif
#if defined TARGET_eqmod
# define TITLE_es Ecuación con módulo
#endif
#if defined TARGET_modsum
# define TITLE_es Módulo de la suma
#endif
#if defined TARGET_sumofj
# define TITLE_es Suma de j
#endif
#if defined TARGET_cbrt
# define TITLE_es CBRT
#endif
#if defined TARGET_arggiven
# define TITLE_es Argumento dado
#endif
#if defined TARGET_pentaroot
# define TITLE_es Pentaroot
#endif
#if defined TARGET_argask
# define TITLE_es Encontrar el argumento
#endif
#if defined TARGET_quadouble
# define TITLE_es Cuadrática raíz doble
#endif
#if defined TARGET_quadouble2
# define TITLE_es Cuadrática raíz doble II
#endif
#if defined TARGET_argsum
# define TITLE_es Argumento de la suma
#endif
#if defined TARGET_pythagorus2
# define TITLE_es Pitágoras II
#endif
#if defined TARGET_fraction2
# define TITLE_es Fracción II
#endif
#if defined TARGET_rootcoef
# define TITLE_es Raíz y coeficientes
#endif
#if defined TARGET_pythagorus
# define TITLE_es Pitágoras
#endif
#if defined TARGET_sqrt
# define TITLE_es Raíz cuadrada
#endif
#if defined TARGET_fraction
# define TITLE_es Fracción
#endif
#if defined TARGET_modmax
# define TITLE_es Módulo máximo
#endif
#if defined TARGET_Trianglequilat
# define TITLE_es Triángulo equilátero
#endif
#if defined TARGET_quadpoly
# define TITLE_es Raíz de un polinomio cuadrático
#endif
#if defined TARGET_sumofi
# define TITLE_es Suma de i
#endif
#if defined TARGET_suminv
# define TITLE_es Suma con inverso
#endif
#if defined TARGET_sumroot
# define TITLE_es Suma de las raíces de la unidad
#endif
#if defined TARGET_tworoots
# define TITLE_es Dos raíces
#endif
#if defined TARGET_modsum2
# define TITLE_es Módulo de la suma II
#endif
#if defined TARGET_powerconj
# define TITLE_es Potencia conjugada
#endif
#if defined TARGET_maxmod
# define TITLE_es Máximo del módulo
#endif
