#if defined TARGET_Trianglequilat
# define TITLE_nl Gelijkzijdige driehoek
#endif
#if defined TARGET_argask
# define TITLE_nl Modulus en Argument I
#endif
#if defined TARGET_arggiven
# define TITLE_nl Modulus en Argument II
#endif
#if defined TARGET_argsum
# define TITLE_nl Modulus en Argument III
#endif
#if defined TARGET_cbrt
# define TITLE_nl CBRT
#endif
#if defined TARGET_cubrt
# define TITLE_nl Vierkants wortel I
#endif
#if defined TARGET_eqmod
# define TITLE_nl Vergelijkingen I
#endif
#if defined TARGET_fraction
# define TITLE_nl Breuken I
#endif
#if defined TARGET_fraction2
# define TITLE_nl Breuken II
#endif
#if defined TARGET_maxmod
# define TITLE_nl Modulus I
#endif
#if defined TARGET_modmax
# define TITLE_nl Modulus II
#endif
#if defined TARGET_modsum
# define TITLE_nl Modulus III
#endif
#if defined TARGET_modsum2
# define TITLE_nl Modulus IV
#endif
#if defined TARGET_pentaroot
# define TITLE_nl Pentaroot
#endif
#if defined TARGET_powerconj
# define TITLE_nl Complex geconjungeerde
#endif
#if defined TARGET_pythagorus
# define TITLE_nl Pythagoras I
#endif
#if defined TARGET_pythagorus2
# define TITLE_nl Pythagoras II
#endif
#if defined TARGET_quadouble
# define TITLE_nl Vierkants wortel II
#endif
#if defined TARGET_quadouble2
# define TITLE_nl Vierkants wortel III
#endif
#if defined TARGET_quadpoly
# define TITLE_nl Vierkants wortel IV
#endif
#if defined TARGET_rootcoef
# define TITLE_nl Wortels en co&euml;fficienten
#endif
#if defined TARGET_sqrt
# define TITLE_nl Vierkants wortel V
#endif
#if defined TARGET_suminv
# define TITLE_nl Som met inverse
#endif
#if defined TARGET_sumofi
# define TITLE_nl Som van i
#endif
#if defined TARGET_sumofj
# define TITLE_nl Som van j
#endif
#if defined TARGET_sumroot
# define TITLE_nl Sum van wortels
#endif
#if defined TARGET_tworoots
# define TITLE_nl Twee wortels I
#endif
#if defined TARGET_tworoots2
# define TITLE_nl Twee wortels II
#endif

