#if defined TARGET_cubrt
# define TITLE Cubic root
#endif
#if defined TARGET_tworoots2
# define TITLE Two roots II
#endif
#if defined TARGET_eqmod
# define TITLE Equation with module
#endif
#if defined TARGET_modsum
# define TITLE Module of sum
#endif
#if defined TARGET_sumofj
# define TITLE Sum of j
#endif
#if defined TARGET_cbrt
# define TITLE CBRT
#endif
#if defined TARGET_arggiven
# define TITLE Given argument
#endif
#if defined TARGET_pentaroot
# define TITLE Pentaroot
#endif
#if defined TARGET_argask
# define TITLE Asked argument
#endif
#if defined TARGET_quadouble
# define TITLE Quadratic double root
#endif
#if defined TARGET_quadouble2
# define TITLE Quadratic double root II
#endif
#if defined TARGET_argsum
# define TITLE Argument of sum
#endif
#if defined TARGET_pythagorus2
# define TITLE Pythagorus II
#endif
#if defined TARGET_fraction2
# define TITLE Fraction II
#endif
#if defined TARGET_rootcoef
# define TITLE Root and coefficients
#endif
#if defined TARGET_pythagorus
# define TITLE Pythagorus
#endif
#if defined TARGET_sqrt
# define TITLE Square root
#endif
#if defined TARGET_fraction
# define TITLE Fraction
#endif
#if defined TARGET_modmax
# define TITLE Maximal module
#endif
#if defined TARGET_Trianglequilat
# define TITLE Equilateral triangle
#endif
#if defined TARGET_quadpoly
# define TITLE Roots quadratic polynomial
#endif
#if defined TARGET_sumofi
# define TITLE Sum of i
#endif
#if defined TARGET_suminv
# define TITLE Sum with inverse
#endif
#if defined TARGET_sumroot
# define TITLE Sum of unit roots
#endif
#if defined TARGET_tworoots
# define TITLE Two roots
#endif
#if defined TARGET_modsum2
# define TITLE Module of sum II
#endif
#if defined TARGET_powerconj
# define TITLE Power conjugate
#endif
#if defined TARGET_maxmod
# define TITLE Maximum of module
#endif

