#if defined TARGET_assgrcarre
# define TITRE Association de paraboles
#endif
#if defined TARGET_assgrcube
# define TITRE Association de cubiques
#endif
#if defined TARGET_assgrfctref
# define TITRE Association de graphiques de fonction de référence
#endif
#if defined TARGET_assgrfctref2
# define TITRE Association de graphiques II
#endif
#if defined TARGET_assgrhyper
# define TITRE Association d’hyperboles
#endif
#if defined TARGET_assgrsqrt
# define TITRE Association de demi-paraboles
#endif
#if defined TARGET_assgrtrigo1
# define TITRE Association de sinusoïdes
#endif
#if defined TARGET_assgrtrigo2
# define TITRE Association de sinusoïdes II
#endif
#if defined TARGET_chgrcarre
# define TITRE Choix d'une parabole
#endif
#if defined TARGET_chgrcube
# define TITRE Choix d'une cubique
#endif
#if defined TARGET_chgrhyper
# define TITRE Choix d'une hyperbole
#endif
#if defined TARGET_chgrsqrt
# define TITRE Choix d'une demi-parabole
#endif
#if defined TARGET_chgrtrigo1
# define TITRE Choix d'une sinusoïde
#endif
#if defined TARGET_chgrtrigo2
# define TITRE Choix d'une sinusoïde II
#endif
#if defined TARGET_grtrigo1
# define TITRE Graphes de fonctions trigo simples II
#endif
