!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les paraboles.
Certains exercices (fuseerep, fusee0, canoniq et canon8) proposent plusieurs méthodes
 pour trouver l'altitude de la fusée ou mettre un trinôme sous forme canonique.
 
!!put no if you do not want to have automatic related modules
!set related_modules=
!!complete if you want to put something else than the keywords of INDEX
!set keyw=

!read oef/intromenu.phtml
!tail
