!header
!read Exindex

Ce module regroupe pour l'instant $exototal exercices sur la géométrie plane pour le début du lycée.
Il fait partie du groupement Ev@lwims pour cette classe.
!let test=!text select char abcdefghijklmnopqrstuvwxyz in $wims_version
!if $test!=$empty
 !let test=!positionof item $test in a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
 !let test=!char 2 to 3 of $[100+$test]
 !let test2=!text select char 1234567890. in $wims_version
 !let test=$test2$test
!else
 !let test=$wims_version
!endif
!if $test>4.02
 <p>
 Vous pouvez voir les exercices dans leur contexte d'utilisation en visitant
 !href module=adm/class/classes/&+exampletype=2 les classes ouvertes
 .
 </p>
!endif

!read oef/intromenu.phtml
!tail
