!if $subject=5

Een kaartspel bestaat uit:<br />
<ul> 
    <li>
	52 kaarten
    </li>
    <li>
	4 soorten kaarten:
	<ul>
	    <li>
		Harten:<br />
		<img src="$module_dir/cards/H6.gif" alt="noalt" />
	    </li>
	    <li>
		Ruiten:<br />
		<img src="$module_dir/cards/R6.gif" alt="noalt" />
	    </li>
	    <li>
		Klaver:<br />
		<img src="$module_dir/cards/K6.gif" alt="noalt" />
	    </li>
	    <li>
		Schoppen:<br />
		<img src="$module_dir/cards/S6.gif" alt="noalt" />
	    </li>
	    <li>
		elke soort heeft &eacute;&eacute;n Boer<br />
		elke soort heeft &eacute;&eacute;n Vrouw<br />
		elke soort heeft &eacute;&eacute;n Heer<br />
		elke soort heeft &eacute;&eacute;n Aas<br />
	    </li>
	 </ul>
    </li>
    <li>
	26 rode kaarten (Harten &amp; Ruiten)
    </li>
    <li>
	26 zwarte kaarten (Klaver &amp; Schoppen)
    </li>
</ul>
<table>
    <tr>
    <th>
      <span style="font-size:120%">$Harten</span><br />
      <img src="$module_dir/cards/H2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H10.gif" alt="noalt" />
      <br />
      <img src="$module_dir/cards/H11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/H1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%">$Ruiten</span><br />
      <img src="$module_dir/cards/R2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R9.gif" alt="noalt" />
      <img src="$module_dir/cards/R10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/R11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/R1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%">$Klaver</span><br />
      <img src="$module_dir/cards/K2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/K11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/K1.gif" alt="noalt" /> 
    </th>
    </tr><tr>
    <th>
	 <span style="font-size:120%">$Schoppen</span><br />
      <img src="$module_dir/cards/S2.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S3.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S4.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S5.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S6.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S7.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S8.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S9.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S10.gif" alt="noalt" /> 
      <br />
      <img src="$module_dir/cards/S11.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S12.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S13.gif" alt="noalt" /> 
      <img src="$module_dir/cards/S1.gif" alt="noalt" /> 
    </th>
    <tr>
</table>

!endif
