#if defined TARGET_binary
# define TITRE_nl Binaire getallen
#endif
#if defined TARGET_binary2
# define TITRE_nl Binaire getallen II
#endif
#if defined TARGET_binary3
# define TITRE_nl Binaire getallen III
#endif
#if defined TARGET_binary4
# define TITRE_nl Binaire getallen IV
#endif
#if defined TARGET_calcbase
# define TITRE_nl Rekenen in andere Getallenstelsels
#endif
#if defined TARGET_dessin
# define TITRE_nl Codering en Bits
#endif
#if defined TARGET_texte
# define TITRE_nl Ontcijfering van een woord
#endif
