#if defined TARGET_binary || defined TARGET_binary2 || defined TARGET_binary3
\text{name_puissance=Machten van }
#endif
#if defined TARGET_binary || defined TARGET_binary3
\text{name_enonce=Schrijf het getal,in de binaire notatie.}
\text{name_feed=, geschreven als binair getal is}
#endif
#if defined TARGET_binary2 || defined TARGET_binary4
\text{name_enonce=De binaire representatie van het getal,is}
#endif
#if defined TARGET_binary2
\text{name_question=Vul de tabel verder in.}
#endif
#if defined TARGET_binary3
\text{name_feed2=het gehele getal, is, pair,impair,
  jouw antwoord eindigd op,
  en dat is werkelijk onmogelijk.}
#endif
#if defined TARGET_binary4
\text{name_question=Geef alle mogelijke waarden van,
  Schrijf je antwoord in decimale notatie. }
#endif
#if defined TARGET_calcbase
\text{name_enonce=We werken in het,
  -tallige stelsel. Een getal \(n\) wordt geschreven als,
  Hoe schrijven we dan}
#endif
#if defined TARGET_dessin
\text{name_question=Geef de binaire code}
\text{name_inst=Elke rij van links naar rechts stelt 8 bits voor.
  We lezen dus van links boven naar rechts beneden, en
  hebben we dus nu 8 "woorden" van 8 bits.
  Geef de binaire representatie van de voorgestelde code,
  de "woorden" gescheiden door komma's.}
\text{name_answer=geef de binaire code}
#endif
#if defined TARGET_texte
\text{name_question=Wat is het woord dat hier binair wordt weergegeven.
  Elke (hoofd)letter van het gezochte woord heeft een eigen regel;
  je moet het woord dus vertikaal lezen!.
  <br><small>kijk even in de help-pagina voor nader uitleg</small>}
\text{name_help=Op een computer heeft elke letter een decimale ASCII code
  van 0 tot 256. We schrijven hier een de binaire 1 als een zwart vlakje
  en de 0 als een wit vlakje
  Hier onder zie je de ASCII tabel van de hoofdletters waaruit ons
  geheime woord is opgebouwd}
#endif
