#if defined TARGET_binary
# define TITRE Conversion en binaire
#endif
#if defined TARGET_binary2
# define TITRE Conversion en binaire II
#endif
#if defined TARGET_binary3
# define TITRE Conversion en binaire III
#endif
#if defined TARGET_binary4
# define TITRE Conversion en binaire IV
#endif
#if defined TARGET_calcbase
# define TITRE Calcul en base b
#endif
#if defined TARGET_dessin
# define TITRE Codage de dessin
#endif
#if defined TARGET_texte
# define TITRE Déchiffrage d'un mot
#endif
