!header
!read Exindex
Ce module regroupe $exototal exercices sur les fonctions affines (niveau 3e, programme 2020).
<p>Merci au groupe Euler de Versailles et à Bruno Mifsud de WimsEdu pour leurs relectures et échanges constructifs.</p>
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=
!! to add a chronometer
!!default scoredelay=60,120
!read oef/intromenu.phtml
!tail
