!header
!read Exindex
 <p><img src="$module_dir/images/logomutuwims2.png" style="float:right;margin-left:0.5em;margin-right:0.2em;" alt="Logo Mutuwims" title="Mutuwims" width="60" height="61">
 Ce module regroupe pour l'instant $exototal exercices du type "Course aux nombres". Plus d'information sur le site
de <b>l'académie de Strasbourg</b>.
</p>
<p>Pour l'instant que les niveaux 3 à 12 et T11 (fin de CE2 à terminale générale et première technologique) conçu à partir des sujets de 2022 (sous licence CC BY-NC 4).
Nous avons conservé les questions en y ajoutant des paramètres aléatoires.</p>
<p>Chaque course comporte 15 questions identiques à données aléatoires sur une seule page ou sur 15 pages (version step).</p>
<p>Pensé pour s'entrainer aux courses aux nombres et être limité à 270 secondes.</p>
<p>Seules les versions step avec le paramètre "Stopper à la première erreur" contiennent les feedbacks.</p>
<p>Suivant les paramétrages que vous faites sur cette page, vous pouvez aussi :</p>
<ul><li>créer votre propre course en sélectionnant plusieurs questions</li>
<li>modifier une course existante en ne sélectionnant que quelques questions</li>
<li>utiliser ces exercices dans une feuille de travail.</li></ul>
<p>A noter : tous les exercices "Question XXXX" ne sont pas visibles, mais utilisables.</p>
<p> Mille mercis à Bernadette Perrin-Riou pour son aide précieuse et le temps passé sur ce module</p>
<div style="text-align:right;">Élaboré avec la communauté <b><i>MutuWIMS</i></b></div>
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=no
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=!defof keywords in INDEX

!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=yes
!default scoredelay=270,500
!read oef/intromenu.phtml

!tail
