!header
!read Exindex
!if $lang=fr
  Ce module contient en ce moment $exototal exercice de déduction interactive
  sur les bornes supérieures et inférieures des fonctions d'une variable réelle.
  !goto end
!endif
This module currently contains $exototal exercises of interactive
deduction on upper and lower bounds of functions of one real variable.
:end
!set keyw=!getdef keywords in INDEX
!read related.phtml $keyw

!read deduc/intromenu.phtml
!tail
