#if defined TARGET_combi || defined TARGET_combi2 || defined TARGET_combi4
# define TITRE Combinaison NUM vecteurs
#endif
#if defined TARGET_angle
# define TITRE Angle
#endif
#if defined TARGET_combifind || defined TARGET_combifind2
# define TITRE Trouver combinaison NUM vecteurs
#endif
#if defined TARGET_voltetra
# define TITRE Volume de tétraèdre
#endif
#if defined TARGET_airetriang
# define TITRE Aire de triangle
#endif
#if defined TARGET_airellelo
# define TITRE Aire de parallélogramme
#endif
#if defined TARGET_givenscale
# define TITRE Produits scalaires donnés
#endif
#if defined TARGET_givenvec
# define TITRE Produit vectoriel donné
#endif
#if defined TARGET_lenvec
# define TITRE Produit vectoriel et longueur
#endif
#if defined TARGET_lenvec2
# define TITRE Produit vectoriel et longueur II
#endif
#if defined TARGET_parallelo
# define TITRE Sommet de parallélogramme
#endif
#if defined TARGET_perp2
# define TITRE Perpendiculaire à deux vecteurs
#endif
#if defined TARGET_perpvec
# define TITRE Perpendiculaire et vectoriel
#endif
#if defined TARGET_rellin
# define TITRE Relation linéaire
#endif
#if defined TARGET_volpara
# define TITRE Volume de parallélépipède
#endif
#if defined TARGET_vecscal
# define TITRE Produits vectoriel et scalaire
#endif
#if defined TARGET_sumvect
# define TITRE Somme de vecteurs
#endif
#if defined TARGET_sumvect1
# define TITRE Somme de vecteurs (graphique)
#endif
