!! ne sert plus

\text{name_instruction1=La figure ci-dessus est une vue en perspective de six cubes de même dimension.}
\matrix{name_feedback=On a,relation de Chasles
  La bonne réponse est donc le point
  est un parallélogramme
  le quadrilatère
  Donc, les vecteurs
  sont égaux
  Donc
}
\text{name_and=et}
\text{name_hint=Par les propriétés des cubes}
#if defined TARGET_sumvect
\text{name_instruction2=Complétez l'égalité suivante par un point de la figure
  pour que l'égalité suivante soit vraie.}
\text{name_answer=Point demandé}
\text{name_pointille=(en pointillés bleus),(en pointillés verts)}
#endif
#if defined TARGET_sumvect1
\text{name_instruction2=Tracer la représentation géométrique du vecteur, dont l'origine
  est }
\text{name_answer=}
\text{name_pointille=}
\text{name_orig=L'origine du vecteur que vous avez tracé n'est pas correcte,L'extrémité du vecteur que vous avez tracé n'est pas correcte}
\text{name_long=La longueur du vecteur que vous avez tracé n'est pas correcte,
  La longueur du vecteur que vous avez tracé est correcte}
\text{name_direction=Le vecteur que vous avez tracé n'a pas la bonne direction.,
  Le vecteur que vous avez tracé a la bonne direction.}
#endif
