#if defined TARGET_combi || defined TARGET_combi2 || defined TARGET_combi4
# define TITRE_en Combination NUM vectors
#endif
#if defined TARGET_angle
# define TITRE_en Angle
#endif
#if defined TARGET_combifind || defined TARGET_combifind2
# define TITRE_en Find combination NUM vectors
#endif
#if defined TARGET_voltetra
# define TITRE_en Volume of tetrahedron
#endif
#if defined TARGET_airetriang
# define TITRE_en Area of triangle
#endif
#if defined TARGET_airellelo
# define TITRE_en Area of parallelogram
#endif
#if defined TARGET_givenscale
# define TITRE_en Given scalar products
#endif
#if defined TARGET_givenvec
# define TITRE_en Given vector product
#endif
#if defined TARGET_lenvec
# define TITRE_en Vector product and length
#endif
#if defined TARGET_lenvec2
# define TITRE_en Vector product and length II
#endif
#if defined TARGET_parallelo
# define TITRE_en Vertex of parallelogram
#endif
#if defined TARGET_perp2
# define TITRE_en Perpendicular to two vectors
#endif
#if defined TARGET_perpvec
# define TITRE_en Perpendicular and vector product
#endif
#if defined TARGET_rellin
# define TITRE_en Linear relation
#endif
#if defined TARGET_volpara
# define TITRE_en Volume of parallelepiped
#endif
#if defined TARGET_vecscal
# define TITRE_en Scalar and vector products
#endif
#if defined TARGET_sumvect
# define TITRE_en Somme de vecteurs
#endif
#if defined TARGET_sumvect1
# define TITRE_en Somme de vecteurs (graphique)
#endif
