!header
!read Exindex
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;"/>
 Ce module regroupe pour l'instant $exototal exercices sur la géographie de l'Allemagne:
villes allemandes, cours d'eau, pays limitrophes, &#34; Land &#34;
(région), curiosités touristiques, population de villes...


<div class="wims_credits">Élaboré avec la communauté MutuWIMS</div>
!read oef/intromenu.phtml
!tail
