!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les séries statistiques. 
Les activités sur l'étude du temps de réaction ont été développées à partir du travail réalisé sur ce site :
<a href="http://acces.ens-lyon.fr/acces/ressources/neurosciences/temps-de-reaction-investigation-variabilite-et-traitements-statistiques-des-donnees">acces.ens-lyon.fr</a>.
<br><br>
Ces exercices permettent aux élèves de développer des compétences sur les TIC car la réalisation
 d'histogramme et de tableau est à effectuer avec LibreOffice ou OpenOffice.
 <br><br>
Les notions abordées sont les différents indicateurs de tendance centrale (classe modale, médiane
 , moyenne) et de dispersion (étendue, écart type, écart interquartile).
<br>
&#9888;&#65039; Les calculs statistiques (moyenne, médiane, quartiles) doivent être réalisés à l'aide d'un tableur <strong>pour les exercices médicament 1 et 2.</strong>
<br><br>
&#9888;&#65039; L'étape 5/6 des exercices temps de réaction ne peut être validée qu'avec
 un code enseignant : 314 cd pour une réponse juste, 315 cd pour une réponse à moitié juste, 0 cd pour obtenir 0.
<br><br>
On pourra réaliser le questionnement suivant auprès des élèves :
<ul>
<li>Comment connaître l'élève le plus réactif ?</li>
<li>Pensez-vous que le temps de réaction puisse être modifié par l’écoute de musique ?</li>
<li>Pensez-vous que le temps de réaction puisse être modifié lorsque vous discutez ?</li> 
<li>L'interdiction de téléphoner au volant d'une voiture semble-t-elle justifiée ?</li>
<li>L'interdiction de conduire sous l'effet de l'alcool ou de psychotropes semble-t-elle justifiée ?</li>
<li>Pourquoi sur l'autoroute toutes les 2 heures la pause s'impose-t-elle ?</li>
</ul>


Une approche pragmatique est réalisée et le thème suivant est abordé :
<ul><li>Vie sociale et loisirs</li></ul>

Ils ont été réalisés pour un niveau de CAP, seconde et 1<sup>er</sup>BAC PRO section tertiaire.



!read oef/intromenu.phtml
!tail
