plot=0
draw=0
xrange=-10:10
insplot_set=size 0.6,0.6; border ;autoscale; zeroaxis linetype 3 ; tmargin 1 ; rmargin 1 ; xlabel "x-axis" ; ylabel "y-axis"
!insplot [$xrange] [$xrange] $functie notitle
etext=!record 25 of lang/remarks.$taal
exotext=<a onmouseover="return escape('<img src=\'$wims_refname?&session=$session&module=$module&cmd=getins&special_parm=insert-1.gif\' alt=\'noalt\' />')"><small>$etext</small></a>
!exit
