!header
!read Exindex
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;">
Ce module regroupe pour l'instant $exototal exercices sur les équations du second degré.

<ul><li>
Dans les titres des exercices, "R" (resp. "C"), signifie que la résolution se fait dans l'ensemble
des réels (resp. complexes).
</li><li>
La lettre "J" signifie que les solutions vont tomber "juste", c'est-à-dire vont pouvoir
  s'écrire sans racine carrée.
</li><li>
La lettre "A" signifie que les solutions vont devoir être données de façon arrondie.
</li><li>
Enfin, la lettre "E" signifie que les solutions devront être données de façon exacte
(et donc en utilisant un quotient et une racine carrée).
</li></ul>

<div class="wims_credits">Élaboré avec la communauté
 MutuWIMS</div>
!read oef/intromenu.phtml

!set keyw=!getdef keywords in INDEX
!tail
