!header
!read Exindex
  <img src="$module_dir/images/logomutuwims2.png" style="float:right;margin-left:0.5em;margin-right:0.2em;" alt="Logo Mutuwims" title="Mituwims" width="60" height="61">
 <p>Ce module regroupe pour l'instant $exototal exercices du type QCM à choix unique, inspirés par les sujets zéros de l'épreuve 
 anticipée de mathématiques (parus en 2025 ...)</p>
<p>Trois types d'exercices sont proposés :</p>
<ul><li>Les exercices "Questions XXX" sont des questions uniques. 
Le numéro de la question indique le thème abordé. La mention T, S ou NS 
signale si la question est pour la filière technologique (T), 
la filière générale spécialiste (S) ou non spécialiste (NS)</li>
<li>La "Course d'automate" regroupe les questions précédentes suivant les thèmes choisis. Toutes les questions sont sur une même page.</li>
<li>La "Course d'automate (step )" est identique à la précédente, mais les questions sont présentées une après l'autre.</li>
</ul>
<p>La liste des thèmes abordés est celle du BO automatismes lié à cette épreuve (juin 2025). 
La numérotation des questions en fonction de ces thèmes est ci-dessous :</p>
<ul><li>Calcul numérique (100 ...)
</li><li>Calcul algébrique (200 ...)
</li><li>Equations inéquations seconde(300 ...), première (350 ...)
</li><li>Proportions et pourcentages seconde (400 ...), première (450 ...)
</li><li>Evolutions et variations seconde (500 ...), première (550 ...)
</li><li>Fonctions et représentations seconde (600 ...), première (650 ...)
</li><li>Statistiques seconde (700 ...), première (750 ...)
</li><li>Probabilité seconde (800 ...), première (850 ...)
</li></ul>

<div style="text-align:right;">Élaboré avec la communauté <b><i>MutuWIMS</i></b></div>
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=no
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices )
!set keyw=!defof keywords in INDEX

!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=yes
!read oef/intromenu.phtml
!tail
