!! pour echanger deux equations d'un systeme.

<u><b>Echanger les deux équations :</b></u>
!goto $wims_read_parm
!exit

:question
!form reply
Appuyer sur le bouton "échanger" pour échanger les places des deux équations dans le système ou sur le lien "retour" pour revenir au menu des actions.
<input type="hidden" name="status" value="3" />
<div class="wimscenter"><input type="submit" value="Echanger" /></div>
!formend
!exit

:reponse

!exit

:analyse
!! ------------- calcul du nouveau système
tmp1=!line 1 of $(sys$nbetape)
tmp2=!line 2 of $(sys$nbetape)
sys$[$nbetape+1]=!append line $tmp2 to $(sys$[$nbetape+1])
sys$[$nbetape+1]=!append line $tmp1 to $(sys$[$nbetape+1])
comment$[$nbetape+1]=J'échange les deux équations du système.
!increase nbetape
status=1
evitecalc=0
!exit
