!read language lang/names
!set wims_backslash_insmath=yes
!header
!read defaults
!read Exindex
!set exocnt=!itemcnt $exolist

<p>
$name_intro1
\(f(x) = c_1 f_1(x) + c_2f_2(x)\).
</p><p>
$name_intro2
</p><p>
$name_intro3
</p>
<hr />
!form new
<input type="hidden" name="module" value="$module" />
$name_introtype:
!set wims_formselect_switch="multiple" size="$[min($exocnt,6)]"
!set exo=$special_parm
!if $exo!=$empty
 !set exolist=!listuniq $exo,$exolist
 !set exolist=!replace , by , $ in $exolist
 !set dictionary=$module_dir/Extitles
 !set translator_unknown=leave
 !set titlelist=!exec translator $exolist
!endif
!formselect exo list $exolist prompt $titlelist
!set wims_formselect_switch=
<p>
$name_introtry :
!formselect maxreply list 1,2,3,4,5,6,8,10,12,15,18,20
.
$name_severity :
!formselect severity from 1 to 5
</p>
<input type="submit" value="$wims_name_work" />
!formend

!read related.phtml $name_related
!tail
