!header
!read Exindex

!if $lang=it

Questo modulo contiene attualmente $exototal esercizi sulle
trasformazioni nella scuola secondaria.

<div class="wims_credits">Le figure utilizzate in molti esercizi sono
state create tra il 2018 e il 2022 per il Diplôme National du
Brevet.</div>

!goto end
!endif

Ce module regroupe pour l'instant $exototal exercices sur les
transformations au collège.

<div class="wims_credits">Les figures de nombreux exercices ont été données
entre 2018 et 2022 au  Diplôme National du Brevet.</div>

:end

!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=
!! to add a chronometer
!!default scoredelay=60,120
!read oef/intromenu.phtml
!tail
