#if defined TARGET_formulas
# define TITRE Formules
#endif
#if defined TARGET_poly
# define TITRE Dérivées polynomiales
#endif
#if defined TARGET_frac1 || defined TARGET_frac2
#define TITRE Fractions
#endif
#if defined TARGET_basic1
# define TITRE Dérivées de base
#endif
#if defined TARGET_multvert1
# define TITRE Multiplication virtuelle I
#endif
#if defined TARGET_growpos
# define TITRE Croissance et signe
#endif
#if defined TARGET_simple1
# define TITRE Dérivées simples I
#endif
#if defined TARGET_compvert1a || defined TARGET_compvert1b
# define TITRE Composition virtuelle
#endif
