#if defined TARGET_imagerestr
# define TITRE Image restreinte
#endif
#if defined TARGET_minmaxrestr
# define TITRE Min et max restreint
#endif
#if defined TARGET_intnoninj
# define TITRE Intervalle non injectif
#endif
#if defined TARGET_intminmax
# define TITRE Intervalle avec min/max
#endif
#if defined TARGET_intmax
# define TITRE Intervalle maximal
#endif
#if defined TARGET_intmax2
# define TITRE Intervalle maximal II
#endif
#if defined TARGET_intminmax
# define TITRE Intervalle avec min/max
#endif
#if defined TARGET_intinj
# define TITRE Intervalle injectif
#endif
#if defined TARGET_image
# define TITRE Image 4
#endif
#if defined TARGET_minmax
# define TITRE Min et max 4
#endif
#if defined TARGET_image3
# define TITRE Image 3
#endif
#if defined TARGET_minmax3
# define TITRE Min et max 3
#endif
#if defined TARGET_antdonne
# define TITRE Nombre d'antécédents donné
#endif
#if defined TARGET_ant
# define TITRE Nombre d'antécédents
#endif
