#if defined TARGET_typesol
# define TITRE Type of solutions
#endif
#if defined TARGET_solution
# define TITRE 3 solutions
#endif
#if defined TARGET_3bottles
# define TITRE 3 bottles
#endif
#if defined TARGET_alloy3
# define TITRE Alloy 3 metals
#endif
#if defined TARGET_almostdiag
# define TITRE Almost diagonal
#endif
#if defined TARGET_Intersectiondr
# define TITRE Intersection of lines
#endif
#if defined TARGET_centercircle
# define TITRE Center of circle
#endif
#if defined TARGET_Sommetstriangl
# define TITRE Vertices of triangle
#endif
#if defined TARGET_quadrilat
# define TITRE Quadrilateral
#endif
#if defined TARGET_triangular
# define TITRE Triangular system
#endif
#if defined TARGET_solve3x3
# define TITRE Solve 3x3
#endif
#if defined TARGET_solve2x2
# define TITRE Solve 2x2
#endif
#if defined TARGET_Distancesgales
# define TITRE Equal distances
#endif
#if defined TARGET_circleeq
# define TITRE Equation of circle
#endif
#if defined TARGET_achat
# define TITRE Market
#endif
#if defined TARGET_Troisentiers
# define TITRE Three integers
#endif
#if defined TARGET_Quatreentiers
# define TITRE Four integers
#endif
#if defined TARGET_Quatreentier2
# define TITRE Four integers II
#endif
#if defined TARGET_Quatreentier3
# define TITRE Four integers III
#endif
#if defined TARGET_sixentiers
# define TITRE Six integers
#endif
#if defined TARGET_homo3x4
# define TITRE Homogeneous 3x4
#endif
#if defined TARGET_homo2x3
# define TITRE Homogeneous 2x3
#endif
#if defined TARGET_ages
# define TITRE 3 ages
#endif
