#if defined TARGET_typesol
# define TITRE_fr Type de solutions
#endif
#if defined TARGET_solution
# define TITRE_fr 3 solutions
#endif
#if defined TARGET_3bottles
# define TITRE_fr 3 bouteilles
#endif
#if defined TARGET_alloy3
# define TITRE_fr Alliage 3 métaux
#endif
#if defined TARGET_almostdiag
# define TITRE_fr Presque diagonal
#endif
#if defined TARGET_Intersectiondr
# define TITRE_fr Intersection de droites
#endif
#if defined TARGET_centercircle
# define TITRE_fr Centre de cercle
#endif
#if defined TARGET_Sommetstriangl
# define TITRE_fr Sommets triangle
#endif
#if defined TARGET_quadrilat
# define TITRE_fr Quadrilatère
#endif
#if defined TARGET_triangular
# define TITRE_fr Système triangulaire
#endif
#if defined TARGET_solve3x3
# define TITRE_fr Résoudre 3x3
#endif
#if defined TARGET_solve2x2
# define TITRE_fr Résoudre 2x2
#endif
#if defined TARGET_Distancesgales
# define TITRE_fr Distances égales
#endif
#if defined TARGET_circleeq
# define TITRE_fr Equation de cercle
#endif
#if defined TARGET_achat
# define TITRE_fr Au marché
#endif
#if defined TARGET_Troisentiers
# define TITRE_fr Trois entiers
#endif
#if defined TARGET_Quatreentiers
# define TITRE_fr Quatre entiers
#endif
#if defined TARGET_Quatreentier2
# define TITRE_fr Quatre entiers II
#endif
#if defined TARGET_Quatreentier3
# define TITRE_fr Quatre entiers II
#endif
#if defined TARGET_sixentiers
# define TITRE_fr Six entiers
#endif
#if defined TARGET_homo3x4
# define TITRE_fr Homogène 3x4
#endif
#if defined TARGET_homo2x3
# define TITRE_fr Homogènes2x3
#endif
#if defined TARGET_ages
# define TITRE_fr 3 âges
#endif
