#if defined TARGET_oefvocabmult1 || defined TARGET_oefvocabmult2 || defined TARGET_oefvocabmult3
# define TITRE Vocabulaire b
#endif
#if defined TARGET_oefdiv101 || defined TARGET_oefdiv102 || defined TARGET_oefdiv103 || defined TARGET_oefdiv104 || defined TARGET_oefdiv105
# define TITRE Division par 10, 100, 1000
#endif
#if defined TARGET_oefmachdiv1 || defined TARGET_oefmachdiv2 || defined TARGET_oefmachdiv3 || defined TARGET_oefmachdiv4 || defined TARGET_oefmachdiv5
# define TITRE Division et utilisation de la calculatrice
#endif
#if defined TARGET_oefmachprob1 || defined TARGET_oefmachprob2 || defined TARGET_oefmachprob3 || defined TARGET_oefmachprob4 || defined TARGET_oefmachprob5
# define TITRE Problèmes avec utilisation de la calculatrice
#endif
#if defined TARGET_oefmentaldiv1 || defined TARGET_oefmentaldiv2 || defined TARGET_oefmentaldiv3 || defined TARGET_oefmentaldiv4 || defined TARGET_oefmentaldiv5
# define TITRE Calcul mental sur la division
#endif
#if defined TARGET_oefvocabdiv1 || defined TARGET_oefvocabdiv2 || defined TARGET_oefvocabdiv3 || defined TARGET_oefvocabdiv4 || defined TARGET_oefvocabdiv5
# define TITRE Vocabulaire
#endif
#if defined TARGET_oefdivision1 || defined TARGET_oefdivision2 || defined TARGET_oefdivision3 || defined TARGET_oefdivision4 || defined TARGET_oefdivision5
# define TITRE Division posée
#endif
#if defined TARGET_oefcriterediv1 || defined TARGET_oefcriterediv2 || defined TARGET_oefcriterediv3 || defined TARGET_oefcriterediv4 || defined TARGET_oefcriterediv5
#define TITRE Critères de divisibilité
#endif
#if defined TARGET_oefcriteredivs1 || defined TARGET_oefcriteredivs2 || defined TARGET_oefcriteredivs3 || defined TARGET_oefcriteredivs4 || defined TARGET_oefcriteredivs5
#define TITRE Critères de divisibilité 
#endif
