#if defined TARGET_oefdiv101 || defined TARGET_oefdiv102 || defined TARGET_oefdiv103 || defined TARGET_oefdiv104 || defined TARGET_oefdiv105 || defined TARGET_oefmentaldiv1 || defined TARGET_oefmentaldiv2 || defined TARGET_oefmentaldiv3 || defined TARGET_oefmentaldiv4 || defined TARGET_oefmentaldiv5
\text{name_question=Donnez le résultat de la division&nbsp;}
\text{name_cond=Bonne réponse&nbsp;}
#endif
#if defined TARGET_oefmachdiv1 || defined TARGET_oefmachdiv2 || defined TARGET_oefmachdiv3 || defined TARGET_oefmachdiv4 || defined TARGET_oefmachdiv5
\text{name_question=Trouver, avec la calculatrice&nbsp;}
\text{name_cond=Bonne réponse&nbsp;}
#if defined TARGET_oefmachdiv1 || defined TARGET_oefmachdiv2
\text{name_t=le quotient}
#endif
#if defined TARGET_oefmachdiv3 
\text{name_quot=le quotient décimal}
#endif
#if defined TARGET_oefmachdiv4 ||defined TARGET_oefmachdiv5
\text{name_enon=Le reste de la division euclidienne de,par,est égal à}
\text{name_t=le reste de la division euclidienne de,par}
#endif
#endif
#if defined TARGET_oefmachprob1 || defined TARGET_oefmachprob2 || defined TARGET_oefmachprob3 || defined TARGET_oefmachprob4 || defined TARGET_oefmachprob5
\text{name_question=Trouver la solution du problème en utilisant la calculatrice&nbsp;}
\text{name_cond=Bonne réponse&nbsp;}
\text{name_sol=\(\v1 \minus \v2=\res\)<p>Il lui reste à payer \(\res\)&nbsp;euro.</p>}
\text{name_instr=La réponse sera donnée sans espace.}
#endif
#if defined TARGET_oefvocabmult1 || defined TARGET_oefvocabmult2 || defined TARGET_oefvocabmult3 || defined TARGET_oefvocabdiv1 || defined TARGET_oefvocabdiv2 || defined TARGET_oefvocabdiv3 || defined TARGET_oefvocabdiv4 || defined TARGET_oefvocabdiv5
\text{name_question=Soit la division euclidienne suivante&nbsp;}
#endif
#if defined TARGET_oefvocabmult1 || defined TARGET_oefvocabmult2 || defined TARGET_oefvocabmult3
\text{name_enonce=Le nombre, est, nombre,
  car la division euclidienne donne un reste nul.}
#endif
#if defined TARGET_oefvocabmult1
\text{mot=un multiple du}
#endif
#if defined TARGET_oefvocabmult2
\text{mot=divisible par le}
#endif
#if defined TARGET_oefvocabmult3
\text{mot=un diviseur du}
#endif
#if defined TARGET_oefvocabdiv1
\text{name_enonc=Le,de la division est le nombre}
#endif
#if defined TARGET_oefvocabdiv2
\text{name_enonc=Dans la division, le nombre, est le }
#endif
#if defined TARGET_oefvocabdiv3
\text{name_enon=Dans la division, donner le}
#endif
#if defined TARGET_oefvocabdiv4
\text{name_enonc=Dans la division, est le}
#endif
#if defined TARGET_oefvocabdiv5
\text{name_enon1=Dans la division euclidienne, nous savons que&nbsp;,
  Compléter l'égalité dans cet ordre&nbsp;}
#endif
#if defined TARGET_oefvocabdiv1 || defined TARGET_oefvocabdiv2 || defined TARGET_oefvocabdiv3 || defined TARGET_oefvocabdiv4 || defined TARGET_oefvocabdiv5
\text{name_list=dividende, diviseur,quotient,reste}
#endif
#if defined TARGET_oefdivision1 || defined TARGET_oefdivision2 || defined TARGET_oefdivision3 || defined TARGET_oefdivision4 || defined TARGET_oefdivision5
\text{name_question=Effectuer la division posée suivante&nbsp;}
\text{name_instruction=Vous devez remplir toutes les étiquettes avec
  des chiffres.}
#endif
#if defined TARGET_oefcriterediv1 || defined TARGET_oefcriteredivs1
\text{name_props=à tous les chiffres du nombre,
au dernier chiffre du nombre,
à la somme des chiffres du nombre,
à la somme des deux derniers chiffres du nombre,
au premier chiffre du nombre,
au nombre formé par les deux derniers chiffres du nombre}
\text{name_quest=Pour savoir si un nombre entier est divisible par,je m'intéresse }
\text{name_quests=Ainsi&#44; pour savoir si un nombre entier est divisible par,je m'intéresse }
#endif
#if defined TARGET_oefcriterediv2
\text{name_quest=Vrai ou faux&nbsp;?}
\text{name_rep=vrai,faux,peut-être}
\text{props=Un nombre entier est divisible par 2 lorsque son chiffre des unités est 0 ; 2 ; 4 ; 6 ou 8,
Un nombre entier est divisible par 2 lorsque son chiffre des unités est 4,
Un nombre entier est divisible par 2 lorsque le nombre est pair,
Un nombre entier est divisible par 2 lorsque son chiffre des unités est 1 ; 3 ; 5 ; 7 ou 9,
Un nombre entier est divisible par 2 lorsque son chiffre des dizaines est 2,
Un nombre entier est divisible par 2 lorsque la somme de ses chiffres est divisible par 2,
Un nombre entier est divisible par 5 lorsque son chiffre des unités est 0 ; 2 ; 4 ; 6 ou 8,
Un nombre entier est divisible par 5 lorsque son chiffre des unités est 0 ou 5,
Un nombre entier est divisible par 5 lorsque son chiffre des unités est 0,
Un nombre entier est divisible par 5 lorsque son chiffre des unités est 5,
Un nombre entier est divisible par 5 lorsque son chiffre des dizaines est 5,
Un nombre entier est divisible par 5 lorsque la somme de ses chiffres est divisible par 5,
Un nombre entier est divisible par 10 lorsque son chiffre des unités est 0 ; 2 ; 4 ; 6 ou 8,
Un nombre entier est divisible par 10 lorsque son chiffre des unités est 0 ou 5,
Un nombre entier est divisible par 10 lorsque son chiffre des unités est 0,
Un nombre entier est divisible par 10 lorsque son chiffre des unités est 5,
Un nombre entier est divisible par 10 lorsque son chiffre des dizaines est 1,
Un nombre entier est divisible par 10 lorsque la somme de ses chiffres est divisible par 10}
#endif
#if defined TARGET_oefcriterediv3
\text{name_quest=Le nombre,est-il divisible par}
\text{name_rep=Oui,Non}
\text{benotbe=est,n'est pas}
\matrix{solu=Un nombre entier est divisible par 2 lorsque son chiffre des unités est 0 &#59; 2 &#59; 4 &#59; 6 ou 8.,Or le nombre, se termine par,donc ,divisible par 2.,
Un nombre entier est divisible par 5 lorsque son chiffre des unités est 0 ou 5.,Or le nombre, se termine par,donc , divisible par 5.,
Un nombre entier est divisible par 10 lorsque son chiffre des unités est 0.,Or le nombre, se termine par, donc,divisible par 10.}
#endif
#if defined TARGET_oefcriterediv4
\text{name_rep=Aucun}
\text{name_quest=Relier un nombre avec un diviseur possible de la liste}
\matrix{solu=Un nombre entier est divisible par \(2\) lorsque son chiffre des unités est \(0\) &#59; \(2\) &#59; \(4\) &#59; \(6\) ou \(8\).,se termine par,donc,est divisible par \(2\).
Un nombre entier est divisible par \(5\) lorsque son chiffre des unités est \(0\) ou \(5\).,se termine par \(5\) donc,est divisible par \(5\).
Un nombre entier est divisible par \(10\) lorsque son chiffre des unités est \(0\).,se termine par \(0\) donc,est divisible par \(10\).
Il reste,qui n'est divisible par aucun des nombres proposés.}
#endif
#if defined TARGET_oefcriterediv5
\text{name_quest=Le nombre,est-il divisible,par}
\text{name_rep=Oui,Non}
\text{benotbe=est,n'est pas}
\matrix{solu=Un nombre entier est divisible par \(2\) lorsque son chiffre des unités est \(0\) &#59; \(2\) &#59; \(4\) &#59; \(6\) ou \(8\).<p>, se termine par, donc,divisible par \(2\).</p>
Un nombre entier est divisible par \(5\) lorsque son chiffre des unités est \(0\) ou \(5\).<p>,se termine par,donc,divisible par \(5\).</p>,
Un nombre entier est divisible par \(10\) lorsque son chiffre des unités est \(0\).<p>, se termine par, donc,divisible par \(10\).</p>}
#endif
#if defined TARGET_oefcriteredivs2
\text{name_quest=Vrai ou faux&nbsp;?}
\text{name_rep=vrai,faux,peut-être}
\text{props=Un nombre entier est divisible par 4 lorsque son chiffre des unités est 0 ; 2 ; 4 ; 6 ou 8,
Un nombre entier est divisible par 4 lorsque son chiffre des unités est 0 ; 4 ou 8,
Un nombre entier est divisible par 4 lorsque le nombre formé par son chiffre des dizaines et des unités est divisible par 4,
Un nombre entier est divisible par 4 lorsque le nombre formé par les deux premiers chiffres est divisible par 4,
Un nombre entier est divisible par 4 lorsque le nombre formé par son chiffre des dizaines et des unités est divisible par 4,
Un nombre entier est divisible par 4 lorsque la somme de ses chiffres est divisible par 4,
Un nombre entier est divisible par 3 lorsque son chiffre des unités est 0 ; 3 ; 6 ou 9,
Un nombre entier est divisible par 3 lorsque son chiffre des unités est 1 ; 3 ; 5 ; 7 ou 9,
Un nombre entier est divisible par 3 lorsque le nombre formé par son chiffre des dizaines et des unités est divisible par 3,
Un nombre entier est divisible par 3 lorsque la somme de ses chiffres est divisible par 3,
Un nombre entier est divisible par 3 lorsque la somme de ses chiffres est divisible par 3,
Un nombre entier est divisible par 3 lorsque la somme de ses chiffres est divisible par 3,
Un nombre entier est divisible par 9 lorsque son chiffre des unités est 0 ; 3 ; 6 ou 9,
Un nombre entier est divisible par 9 lorsque son chiffre des unités est 1 ; 3 ; 5 ; 7 ou 9,
Un nombre entier est divisible par 9 lorsque le nombre formé par son chiffre des dizaines et des unités est divisible par 9,
Un nombre entier est divisible par 9 lorsque la somme de ses chiffres est divisible par 9,
Un nombre entier est divisible par 9 lorsque la somme de ses chiffres est divisible par 9,
Un nombre entier est divisible par 9 lorsque la somme de ses chiffres est divisible par 9}
#endif
#if defined TARGET_oefcriteredivs3
\text{name_quest=Le nombre,est-il divisible par}
\text{name_rep=Oui,Non}
\text{benotbe=est,n'est pas}
\matrix{solu=Un nombre entier est divisible par \(3\) lorsque la somme de ses chiffres est divisible par \(3\).,Or la somme des chiffres du nombre,est égale à,qui,divisible par \(3\) donc le nombre,divisible par \(3\).,
Un nombre entier est divisible par \(4\) lorsque le nombre formé par les deux derniers chiffres est divisible par \(4\)., Or les deux derniers chiffres du nombre, forment le nombre, qui, divisible par \(4\) donc le nombre,divisible par \(4\).
Un nombre entier est divisible par \(9\) lorsque la somme de ses chiffres est divisible par \(9\).,Or la somme des chiffres du nombre,est égale à,qui,divisible par \(9\) donc le nombre,divisible par \(9\).,
}
#endif
#if defined TARGET_oefcriteredivs4
\text{name_rep=Aucun}
\text{name_quest=Relier un nombre avec un diviseur possible de la liste}
\matrix{solu=Un nombre entier est divisible par \(3\) lorsque la somme de ses chiffres est divisible par \(3\).,et,est divisible par \(3\) donc,est divisible par \(3\).
Un nombre entier est divisible par \(4\) lorsque le nombre formé par les deux derniers chiffres est divisible par \(4\).,a ses deux derniers chiffres qui forment le nombre,et,est divisible par \(4\) donc,est divisible par \(4\).
Un nombre entier est divisible par \(9\) lorsque la somme de ses chiffres est divisible par \(9\).,et,est divisible par \(9\) donc,est divisible par \(9\).
Il reste,qui n'est divisible par aucun des nombres proposés.}
#endif
#if defined TARGET_oefcriteredivs5
\text{name_quest=Le nombre,est-il divisible}
\text{name_rep=Oui,Non}
\text{benotbe=est,n'est pas}
\matrix{solu=Un nombre entier est divisible par \(3\) lorsque la somme de ses chiffres est divisible par \(3\).<p>,et, divisible par \(3\) donc,divisible par \(3\).</p>,
Un nombre entier est divisible par \(4\) lorsque le nombre formé par ses deux derniers chiffres est divisible par \(4\).,<p>Les deux derniers chiffres du nombre, forment le nombre, et, divisible par \(4\) donc, divisible par \(4\).</p>,
Un nombre entier est divisible par \(9\) lorsque la somme de ses chiffres est divisible par \(9\).<p>,et,divisible par \(9\) donc,divisible par \(9\).</p>}
#endif
