<table class="divposée">
<tr>
  <td></td>
    <td>\ldd[3]</td>
    <td>\ldd[2]</td>
    <td>\ldd[1]</td>
<td class="vline-left bord-bas" aria-hidden="true">\d2</td>
<td class="bord-bas">\d1</td>
</tr>
<tr>
  <td class="bord-bas">\sgn</td>
  <td class="bord-bas">\rp[1]</td>
  <td class="bord-bas">\rp[2]</td>
  <td class="vline-right"></td>
  <td>\rp[3]</td>
  <td>\rp[4]</td>
</tr>
<tr>
<td></td>
  <td>\rp[5]</td>
  <td>\rp[6]</td>
  <td class="vline-right">\rp[7]</td>
  <td></td>
  <td></td>
</tr>
<tr>
  <td class="bord-bas">\sgn</td>
  <td class="bord-bas">\rp[8]</td>
  <td class="bord-bas">\rp[9]</td>
  <td class="bord-bas vline-right">\rp[10]</td>
  <td></td>
  <td></td>
</tr>
<tr>
  <td></td>
  <td></td>
  <td>\rp[11]</td>
  <td class="vline-right">\rp[12]</td>
  <td></td>
  <td></td>
</tr>
</table>
