!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

!if $module_score=10
  $name_answergood
  <div class="wimscenter">
   !insdraw \
  $dessin\
  $dessinsol
  </div>
!else
  $name_redgreen
  <br class="spacer">
  <ul style="list-style-type:none;">
  !if $miss=1
    <li>
     $name_outline
    </li>
  !endif
  !if $miss=2
    <li>
     $name_nopoints
    </li>
  !endif
  !if abs($pente- ($a))<0.15 and abs($ord-($b))>0.1
    <li>
     $name_parallel
    </li>
  !endif
  !if abs($pente-($a))>0.2 and abs($ord-($b))<0.1
    <li>
     $name_ordonnee
    </li>
  !endif

  !if $type=2 and abs($ord)>0.1
    <li>
    $name_origin
    </li>
  !endif
  </ul>
  <br class="spacer">
  <div class="wimscenter">
  !insdraw \
$dessin\
$dessin2\
$dessinsol
  </div>
!endif

$name_score
