!!!replace by !read language lang/names in the version >4.05 to multilanguage
!read language lang/names

!header

<b>$module_title</b> $name_intro

!set type=1
!form new
<ul>
 <li>
!set wims_ref_id=type_2
!formradio type list 2 prompt $(name_intro_afflin[2])
 </li><li>
!set wims_ref_id=type_1
!formradio type list 1 prompt $(name_intro_afflin[1])
 $name_givenby
 !set liste= rep,direct,indirect, applindir,applinante
 !set wims_formselect_switch=multiple="multiple"
 <p class="wimscenter">
  !formselect mode1 list $liste prompt \
$name1,$name2,$name3,$name4,$name5,$name6,$name7
 </p>
 </li>
</ul>
!reset wims_formselect_switch
!default coeff=1
$name_coefficienttype
!formradio coeff list 1,2,3 prompt $name_typenumber
.
<input type="hidden" name="module" value="$module">
<div class="wimscenter wimsform">
  <input type="submit" value="$wims_name_work">
</div>
!formend
!!remplacer par !formend dans la version 4.05a

!tail
