!!!replace by !read language lang/names in the version >4.05 to multilanguage
!read language lang/names
!set wims_backslash_insmath=yes
!header

!read present.phtml

!if $status=waiting
  !if $error!=$empty
    <div class="wims_alertmsg">
    !read msg.phtml
    </div>
  !endif

  !read form.phtml
  <p>
  !set wims_ref_class=wims_button
  !href exo_Renew
  </p>
!else
  !if $error!=$empty
    <div class="wims_alertmsg">
     !read msg.phtml
    </div>
  !endif

  !read answer.phtml
  <br class="spacer">
  !set wims_ref_class=wims_button
  !href exo_Again
  &nbsp;
  !if $worksheet=$empty
    !set wims_ref_class=wims_button
    !href exo_Intro
  !endif
!endif

:end
!tail
