
!set eqlin_tex=!texmath $equationlin
!set eq_tex=!texmath $equation
!set aff=!item $type of $name_intro_linaff

!if $mode issametext rep
  $name_rep $aff
  \(f: x \mapsto $eq_tex\).

!endif

!if $mode issametext direct
  $name_traceraffine $name_direct
!endif

!if $mode issametext indirect
  $name_traceraffine $name_indirect
!endif

!if $mode issametext applindir

  $name_traceraffine $name_lineaireassoc
  \(x \mapsto $eqlin_tex\)
  $name_applindir
!endif

!if $mode issametext applinante
  $name_traceraffine $name_lineaireassoc
  \(x \mapsto $eqlin_tex\)
  $name_applinante
!endif
<p>
$name_clicktwopoints
</p>
