#if defined TARGET_quotientdiv
# define TITRE_nl Quotient van machten
#endif
#if defined TARGET_quprindiv
# define TITRE_nl Bewerkingen en machten
#endif
#if defined TARGET_produitdiv
# define TITRE_nl Product van machten
#endif
#if defined TARGET_puispuissance
# define TITRE Puissance de puissance
#endif
#if defined TARGET_inversediv
# define TITRE_nl Inverse de puissance
#endif
#if defined TARGET_puis1
# define TITRE_nl Machten 1
#endif
#if defined TARGET_puis2
# define TITRE_nl Machten 2
#endif
#if defined TARGET_puis3
# define TITRE_nl Machten 3
#endif
#if defined TARGET_quotient10
# define TITRE_nl Quotient van machten van 10
#endif
#if defined TARGET_quprin10
# define TITRE_nl Bewerkingen en machten van 10
#endif
#if defined TARGET_produit10
# define TITRE_nl Product van machten van 10
#endif
#if defined TARGET_puispuis10
# define TITRE_nl Puissance de puissance de 10
#endif
#if defined TARGET_inverse10
# define TITRE_nl Inversen van machten van 10
#endif
#if defined TARGET_produit
# define TITRE_nl Product
#endif
#if defined TARGET_somme1
# define TITRE_nl SC Macht van 10 en som 2a
#endif
#if defined TARGET_somme3
# define TITRE_nl SC Macht van 10 en som 2b
#endif
#if defined TARGET_somme4
# define TITRE_nl SC Macht van 10 en som 3a
#endif
#if defined TARGET_somme2
# define TITRE_nl SC Macht van 10 en som 3b
#endif
#if defined TARGET_produit2
# define TITRE_nl SC Product 2
#endif
#if defined TARGET_quotient
# define TITRE_nl SC Quotient
#endif
#if defined TARGET_quoprod
# define TITRE_nl SC Quotient en product
#endif
#if defined TARGET_somquo1
# define TITRE_nl SC Som quotient en macht A
#endif
#if defined TARGET_somquo2
# define TITRE_nl SC Som quotient en macht B
#endif
#if defined TARGET_2produit
# define TITRE_nl Produit*
#endif
#if defined TARGET_2somme1
# define TITRE_nl Puissance de 10 et somme 2a*
#endif
#if defined TARGET_2somme3
# define TITRE_nl Puissance de 10 et somme 2b*
#endif
#if defined TARGET_2somme4
# define TITRE_nl Puissance de 10 et somme 3a*
#endif
#if defined TARGET_2somme2
# define TITRE_nl Puissance de 10 et somme 3b*
#endif
#if defined TARGET_2produit2
# define TITRE_nl Produit 2*
#endif
#if defined TARGET_2quotient
# define TITRE_nl Quotient*
#endif
#if defined TARGET_2quoprod
# define TITRE_nl Quotient en product*
#endif
#if defined TARGET_2somquo1
# define TITRE_nl Somme quotient et puissance A*
#endif
#if defined TARGET_2somquo2
# define TITRE_nl Somme quotient et puissance B*
#endif
#if defined TARGET_decimal
# define TITRE_nl Decimale schrijfwijze
#endif
#if defined TARGET_3regles
# define TITRE_nl Les quatre règles
#endif
#if defined TARGET_3regles10
# define TITRE_nl Les quatre règles (puissance 10)
#endif
#if defined TARGET_les3regles2
# define TITRE_nl Les trois règles
#endif
#if defined TARGET_decalage
# define TITRE_nl Opschuiven van de komma 1
#endif
#if defined TARGET_decalage2
# define TITRE_nl Opschuiven van de komma 2
#endif
#if defined TARGET_puisdiv2
# define TITRE_nl Machten van een geheel getal 2
#endif
#if defined TARGET_puisdiv
# define TITRE_nl Machten van een geheel getal
#endif
