#if defined TARGET_decimal
\text{name_question=Schrijf het volgende getal in decimale schrijfwijze,
  Schrijf de volgende getallen in decimale schrijfwijze}
#endif
#if defined TARGET_quotientdiv || defined TARGET_produitdiv || defined TARGET_inversediv || defined TARGET_quprindiv || defined TARGET_puispuissance
\text{name_question=Bereken de volgende uitdrukking,
  Bereken de volgende uitdrukkingen}
#endif
#if defined TARGET_puis1 || defined TARGET_puis2 || defined TARGET_puis3
\text{name_question=Bereken de volgende uitdrukking}
\text{name_instruction=Vous pouvez écrire votre résultat sous forme
  d'une fraction irréductible ou sous forme décimale (si elle existe).}
#endif
#if defined TARGET_2produit || defined TARGET_2quotient || defined TARGET_2quoprod || defined TARGET_2produit2 || defined TARGET_2somme1 || defined TARGET_2somme2 || defined TARGET_2somme3 || defined TARGET_2somme4 || defined TARGET_2somquo1 || defined TARGET_2somquo2
\text{name_question=Bereken de volgende uitdrukking}
\text{name_answer=Partie décimale,Exposant}
\text{name_cond=Calcul effectué correctement}
#endif
#if defined TARGET_quotient10 || defined TARGET_produit10 || defined TARGET_inverse10 || defined TARGET_quprin10 || defined TARGET_puispuis10 || defined TARGET_3regles || defined TARGET_3regles10 || defined TARGET_les3regles2
\text{name_question=Bereken de volgende uitdrukking,
 Bereken de volgende uitdrukkingen}
#endif
#if defined TARGET_produit || defined TARGET_quotient || defined TARGET_quoprod || defined TARGET_produit2 || defined TARGET_somme1 || defined TARGET_somme2 || defined TARGET_somme3 || defined TARGET_somme4 || defined TARGET_somquo1 || defined TARGET_somquo2
\text{name_question1=Bereken de volgende uitdrukking en geef het antwoord in wetenschappelijke notatie}
\text{name_question2=Bereken de volgende uitdrukkingen en geef de antwoorden in wetenschappelijke notatie}
#endif
#if defined TARGET_decalage || defined  TARGET_decalage2
\text{name_question=Vul in,
  Vul in}
#endif
#if defined TARGET_puisdiv2
\text{name_question=Er wordt gevraagd om,
  vindt,trvindt,Wie heeft het juiste antwoord gegeven}
#endif
#if defined TARGET_puisdiv
\text{name_question=Schrijf het volgende getal in decimale schrijfwijze,
  Schrijf de volgende getallen in decimale schrijfwijze}
#endif
