#if defined TARGET_decimal
\text{name_question=Écrire sous forme décimale le nombre suivant&nbsp;,
  Écrire sous forme décimale les nombres suivants&nbsp;}
#endif
#if defined TARGET_quotientdiv || defined TARGET_produitdiv || defined TARGET_inversediv || defined TARGET_quprindiv || defined TARGET_puispuissance
\text{name_question=Compléter l'égalité suivante&nbsp;,
   Compléter les égalités suivantes&nbsp;}
#endif
#if defined TARGET_puis1 || defined TARGET_puis2 || defined TARGET_puis3
\text{name_question=Calculer la valeur exacte de l'expression suivante&nbsp;}
\text{name_instruction=Vous pouvez écrire votre résultat sous forme
  d'une fraction irréductible ou sous forme décimale (si elle existe).}
#endif
#if defined TARGET_2produit || defined TARGET_2quotient || defined TARGET_2quoprod || defined TARGET_2produit2 || defined TARGET_2somme1 || defined TARGET_2somme2 || defined TARGET_2somme3 || defined TARGET_2somme4 || defined TARGET_2somquo1 || defined TARGET_2somquo2
\text{name_question=Calculer l'expression suivante&nbsp;}
\text{name_answer=Partie décimale,Exposant}
\text{name_cond=Calcul effectué correctement}
#endif
#if defined TARGET_quotient10 || defined TARGET_produit10 || defined TARGET_inverse10 || defined TARGET_quprin10 || defined TARGET_puispuis10 || defined TARGET_3regles || defined TARGET_3regles10 || defined TARGET_les3regles2
\text{name_question=Calculer l'expression suivante&nbsp;,
  Calculer les expressions suivantes&nbsp;}
#endif
#if defined TARGET_produit || defined TARGET_quotient || defined TARGET_quoprod || defined TARGET_produit2 || defined TARGET_somme1 || defined TARGET_somme2 || defined TARGET_somme3 || defined TARGET_somme4 || defined TARGET_somquo1 || defined TARGET_somquo2
\text{name_question1=Calculer l'expression suivante et <span class="wims_emph">
    donner l'écriture scientifique du résultat</span>&nbsp;}
\text{name_question2=Calculer les expressions suivantes et
  <span class="wims_emph">donner l'écriture scientifique des résultats</span>&nbsp;}
#endif
#if defined TARGET_decalage || defined  TARGET_decalage2
\text{name_question=Compléter l'égalité suivante&nbsp;,
  Compléter les égalités suivantes&nbsp;}
#endif
#if defined TARGET_puisdiv2
\text{name_question=On demande de calculer,
  trouve,et,Qui a donné la bonne réponse&nbsp;}
#endif
#if defined TARGET_puisdiv
\text{name_question=Écrire sous forme décimale le nombre suivant&nbsp;,
  Écrire sous forme décimale les nombres suivants&nbsp;}
#endif
