!header
!read Exindex
Deze module bevat $exototal oefeningen met arithmetiek (optellen, aftrekken),
die ofwel als sommen ofwel als ontspanning gezien kunnen worden.
<div>
Het zijn allemaal ``drag &amp; drop'' oefeningen, waarbij getallen of
uitdrukkingen in een plaatje gezet moeten worden, met meetkundige voorwaarden
op hun sommen. Het eerste getal in de lijst geeft aan hoeveel objecten er
geplaatst moeten worden. Met een grote variatie aan stijlen en
moeilijkheidsgraden om aan verschillende eisen te voldoen.
</div>
!read oef/$module_language/intromenu.phtml
!tail

