!header
!read Exindex
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;"/>
<p>Ce module regroupe pour l'instant $exototal exercices sur le calcul de l'espérance, la variance 
ou l'écart type d'une combinaison linéaire de variables aléatoires.</p>
 <p><i>Certains exercices  sont inspirés du rallye Maths sans frontière 2017.</i></p>


<div class="wims_credits">Elaboré avec la communauté MutuWIMS</div>
!read oef/intromenu.phtml
!tail
