!set n=!recordcnt src/data
!reset objlist
!for i=1 to $n
 !set l=!record $i of src/data
 !set l=!line 1 of $l
 !set objlist=!append item $l to $objlist
!next i

<tr><td><label for="confparm1">Tipo de objetos:</label>
</td><td>
!formselect confparm1 from 1 to $n prompt $objlist
</td>
</tr><tr><td><label for="confparm2">Número de objetos redundantes:</label>
</td><td>
<input size="3" name="confparm2" id="confparm2" value="0">
</tr>
