!header
!read Exindexc
<div>
Este módulo contiene por el momento $exototal actividades de práctica visual
de aritmética (adición, sustracción), que bien pueden ser consideradas
ejercicios bien actividades recreativas.
</div><div>
Estas son actividades del tipo ``arrastra y pega''; consisten en poner
números o expresiones dentro de una imagen, con condiciones geométricas
sobre sus sumas. El primer número de la lista indica el número de objetos
que debe ponerse. Con gran variedad de estilos y niveles de dificultad,
puede satisfacer varios objetivos.
</div>
!read oef/$module_language/intromenu.phtml
!tail

