\text{lang=slib(oef/env lang)}
\language{fr}
\author{Gang, XIAO}
\email{xiao@unice.fr}
\format{html}
#if defined TARGET_relrtdeg3
\computeanswer{no}
\precision{3000}
#endif
#if defined TARGET_mindeggcd2
\range{-5..5}
\computeanswer{no}
\precision{1000000}
#endif
#if defined TARGET_stadouble
\range{-5..5}
\computeanswer{no}
\precision{1000000}
#endif
#if defined TARGET_deggcd
\range{-5..5}
\computeanswer{no}
\precision{1000000}
#endif
#if defined TARGET_relrtdeg2
\range{-5..5}
\computeanswer{no}
\precision{3000}
#endif
#if defined TARGET_givderiv
\computeanswer{no}
\precision{10000}
#endif
#if defined TARGET_parmdeg2
\range{-5..5}
\computeanswer{no}
\precision{10000}
#endif
#if defined TARGET_diffeqn
\computeanswer{no}
\precision{10000}
#endif
#if defined TARGET_tripledeg3b
\range{-5..5}
\computeanswer{yes}
\precision{10000}
#endif
#if defined TARGET_degsum
\range{-5..5}
\computeanswer{no}
\precision{100000}
#endif
#if defined TARGET_givrtdeg3
\range{-5..5}
\computeanswer{yes}
\precision{1000000}
#endif
#if defined TARGET_rootcomp
\range{-5..5}
\computeanswer{yes}
\precision{100000}
#endif
#if defined TARGET_parmdeg2b
\range{-5..5}
\computeanswer{no}
\precision{10000}
#endif
#if defined TARGET_rootmultsum
\range{-5..5}
\computeanswer{no}
\precision{100000}
#endif
#if defined TARGET_tripledeg3
\range{-5..5}
\computeanswer{yes}
\precision{10000}
#endif
#if defined TARGET_trinomefact
\range{-5..5}
\email{xiao@localhost}
\computeanswer{no}
\precision{10000}
#endif
#if defined TARGET_quadpoly
\range{-5..5}
\computeanswer{no}
\precision{10000}
#endif
#if defined TARGET_rootdeg2
\range{-5..5}
\computeanswer{no}
\precision{3000}
#endif
#if defined TARGET_rootcnt
\range{-5..5}
\computeanswer{no}
\precision{1000000}
#endif
#if defined TARGET_rerootdeg2
\range{-5..5}
\computeanswer{no}
\precision{3000}
#endif
#if defined TARGET_mindeggcdn
\range{-5..5}
\computeanswer{no}
\precision{1000000}
#endif
#if defined TARGET_degmult
\range{-5..5}
\computeanswer{no}
\precision{3000}
#endif
#if defined TARGET_findmult3 || defined TARGET_findmult4 || defined TARGET_findmult5 || defined TARGET_findmult6 || defined TARGET_multiplicity3 || defined TARGET_multiplicity4 || defined TARGET_multiplicity5 || defined TARGET_multiplicity6 || defined TARGET_multparm3 || defined TARGET_multparm4
\computeanswer{no}
\precision{10000}
#endif
