!header
!read Exindex
Ce module contient trois exercices sur la factorisation d'expressions polynômiales : un exercice de factorisation proprement dite et deux exercices de résolution d'équation où la factorisation est la méthode la plus efficace.
Les équations sont de la forme P(x)=0 dans l'exercice Equation 1 et de la forme P(x)=Q(x) dans l'exercice Equation 2.
<br class="spacer">

Les expressions polynômiales proposées dans ces exercices sont des sommes de termes possédant un facteur commun. Cette page de configuration permet de choisir le type et la complexité des expressions.
!read oef/intromenu.phtml
!tail
