<tr>
<b>Nombre de termes de l'expression : </b>
!formradio confparm1 from 2 to 4 prompt  2,3,4
<br class="spacer">

<b>Types de facteur commun et types de termes : </b>
<table class="wimstable">
<tr>
<th> </th>
<th>  \((a x+b)\)<br>
!formcheckbox confparm2 list A prompt \(\)
</th>
<th> \((a x+b)^2\) <br>
!formcheckbox confparm2 list B prompt \(\)</th>
<th> \((a x^2+b x)\) <br>
!formcheckbox confparm2 list C  prompt \(\)</th>
<th>
\((a x^2+b)\)<br>
!formcheckbox confparm2 list D,E prompt \(b>0\),\(b<0\)
</th>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 1 prompt \(\)
</td>
<td>
 \(e(c x + d)(a x+b)\)</td>
<td>
\(e(c x + d)(a x+b)^2\)</td>
<td>
\(e(c x + d)(a x^2+b x)\)</td>
<td>
\(e(c x + d)(a x^2+b)\)</td>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 2 prompt \(\)
</td>
<td>
\((c x + d)(a x+b)\)</td>
<td>
\((c x + d)(a x+b)^2\)</td>
<td>
\((c x + d)(a x^2+b x)\)</td>
<td>
\((c x + d)(a x^2+b)\)</td>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 3 prompt \(\)
</td>
<td>
\(c x (a x+b)\)</td>
<td>
\(c x (a x+b)^2\)</td>
<td>
\(c x (a x^2+b x)\)</td>
<td>
\(c x (a x^2+b)\)</td>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 4 prompt \(\)
</td>
<td>
\(c (a x+b)\)</td>
<td>
\(c (a x+b)^2\)</td>
<td>
\(c (a x^2+b x)\)</td>
<td>
\(c (a x^2+b)\)</td>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 5 prompt \(\)
</td>
<td>
\((a x+b)\)</td>
<td>
\((a x+b)^2\)</td>
<td>
\((a x^2+b x)\)</td>
<td>
\((a x^2+b)\)</td>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 6 prompt \(\)
</td>
<td >
\(c (a x+b)^2\)</td>
<td>
\(c (a x+b)^3\)</td>
<td>
\(c (a x^3+b x^2)\)</td>
<td>
\(c (a x^3+b x)\)</td>
</tr><tr align="center">
<td>
!formcheckbox confparm2 list 7 prompt \(\)
</td>
<td>
\((a x+b)^2\)</td>
<td>
\((a x+b)^3\)</td>
<td>
\((a x^3+b x^2)\)</td>
<td>
\((a x^3+b x)\)</td>
</tr>
</table>
<div class="formHelp">
Sélectionnez dans la première ligne du tableau les types de facteur commun, puis sélectionnez dans la première colonne les types de termes. Les termes de l'expression seront pris aléatoirement parmi vos choix.
</div><br class="spacer">

<b>Facteur commun apparent : </b>
!formradio confparm3 from 1 to 2 prompt oui , non
<div class="formHelp">
Si vous sélectionnez <i>non</i>, le facteur commun sera remplacé dans un ou plusieurs termes par un multiple de ce facteur commun.
</div><br class="spacer">

<b>Complexité des coefficients : </b>
!formradio confparm4 from 1 to 4
<div class="formHelp">
1 : nombres entiers inférieurs à 6, pas de signe négatif entre les termes<br>
2 : nombres entiers inférieurs à 6<br>
3 : nombres entiers inférieurs à 15<br>
4 : nombres rationnels inférieurs à 6</div>
</tr>
