!read language lang/names
!header
<p>
$name_intro1
</p><p>
$name_intro2
</p>
!form new
<input type="hidden" name="module" value="$module">
<fieldset class="property_fields">
<legend>$wims_name_setup</legend>
<ul>
 <li>$name_typepoint:<br>
  !set wims_formselect_switch=multiple
  !formselect type from 1 to 7 prompt \
	$name1,$name2,$name3,$name4,$name5,$name6,$name7
  !set wims_formselect_switch=
  <br>
  <div class="formHelp">$name_typecomment</div>
 </li><li>
 $name_numbershoot
   !set shoots=3
   !formradio shoots list 1,3,5,8,12
   <div class="formHelp">$name_Score</div>
 </li><li>$name_size :
   !set size=256
   !formselect size list 160,200,256,320,400
   <div class="formHelp">$name_sizecomment</div>
</li>
</ul>
</fieldset>
<p class="wimscenter wimsform">
<input type="submit" value="$wims_name_work">
</p>
!formend
!set keyw=!defof keywords in INDEX
!read related.phtml $keyw

!tail
