#if defined TARGET_prinj
# define TITRE_fr Preuve injectivité réciproque
#endif
#if defined TARGET_prcroiss
# define TITRE_fr Preuve croissance réciproque
#endif
#if defined TARGET_prsurj
# define TITRE_fr Preuve surjectivité réciproque
#endif
#if defined TARGET_bijquad
# define TITRE_fr Bijectivité quadratique
#endif
#if defined TARGET_quadratic
# define TITRE_fr Quadratique
#endif
#if defined TARGET_fraction
# define TITRE_fr Fraction
#endif
#if defined TARGET_Imagerciproque2
# define TITRE_fr Image réciproque de l'image
# endif
#if defined TARGET_Imagerciproque
# define TITRE_fr Image réciproque d'un intervalle
#endif
#if defined TARGET_Imagedelimager
# define TITRE_fr Image de l'image réciproque
#endif
#if defined TARGET_nonderrecip
# define TITRE_fr Réciproque non dérivable
#endif
#if defined TARGET_quadratic
# define TITRE_fr Quadratique
#endif
#if defined TARGET_reciproc
# define TITRE_fr Dérivée réciproque
#endif
#if defined TARGET_invval
# define TITRE_fr Valeur réciproque
#endif
