\consigne
<ul class="inline"><li>
\embed{reply1,1,<img src="\imagedir/\ListImage[1]" alt="\Listdesc[1]">}
\bch1
</li><li>
\embed{reply1,2,<img src="\imagedir/\ListImage[2]" alt="\Listdesc[2]">}
\bch2
</li><li>
\embed{reply1,3,<img src="\imagedir/\ListImage[3]" alt="\Listdesc[3]">}
\bch3
</li><li>
\embed{reply1,4,<img src="\imagedir/\ListImage[4]" alt="\Listdesc[4]">}
\bch4
</li>
\if{\nb_meth>=5}{
<li>
\embed{reply1,5,<img src="\imagedir/\ListImage[5]" alt="\Listdesc[5]">}
\bch5
</li>}
</ul>
