!!hotspot questions
!set n=$counter
  <p align="center">
    <table bgcolor=$bgcolor1 cellpadding=$cellpadding cellspacing=$cellspacing>
	<td>
	!if $(question$n) != $empty
	    $(question$n)
	    <br>
	!endif
	!if $(formula$n) != $empty
	    !insmath $(formula$n)
	    <br>
	!endif
	!if $exotext1=$empty
	    $exotext
	!endif
	</td>
	!if $image=2
	    <tr>
	!endif
	<td>
	    !if $image=2
		<table>
		    <th>
			!set ins_attr = ismap
        		!href cmd=reply&$no_name
			!set insdraw_size=$XSIZE,$YSIZE
			!insdraw $var1
			</a>
		    </th>
		    <th>
			!set ins_attr = ismap
        		!href cmd=reply&$no_name
			!set insdraw_size=$xsize,$ysize
			!insdraw $var2
			</a>
		    </th>
		</table>
	    !else
		!set ins_attr = ismap 
        	!href cmd=reply&$no_name
		!if $draw=1
		    !! for fly
		    !set insdraw_size=$XSIZE,$YSIZE
		    !insdraw $(image$n)
		    </a>
		!endif
		!if $plot=1
	    	    !! for GNUplot
		    !set insplot_set=$(image_settings$n)
		    !insplot $(image$n)
		    </a>
		!endif
	    !endif
	</td>
    </table>
  </p>
