!read language lang/names
!header

<span class="wims_mod_title">$module_title</span> $name_intro.
  !form new
<fieldset class="property_fields">
  <legend>$wims_name_setup</legend>
  <input type="hidden" name="module" value="$module" />
  <ul><li>
  !default wlevel=2
  $(name_introprompt[1;]):
  !formradio wlevel list 1,2,3
  </li><li>
  !default slevel=2
  $(name_introprompt[2;]):
  !formradio slevel list 1,2,3,4
  </li><li>
  !default repeat=1
  $(name_introprompt[3;]):
  !formselect repeat from 1 to 8
  </li></ul>
</fieldset>
<div class="wimscenter"><input type="submit" value="$wims_name_work" ></div>
  !formend
!tail
