!set n=$teller

<table border="1" bgcolor="$bgcolor2">
    <td>
	Question <b>$n</b>) 
    <p>
	$voornaam, here is an applet with the movable graph of an unkown trigonometric function. 
	<br>
	$(somtekst$n)
	<p><font size="-1">
	!if $bijles=1
	    !if $wims_user=supervisor
		<small>
		    supervisor, this next text could be made unvisable<br> 
		    by setting the "extra support" to "No"
		</small>
	    !endif	
	    The wanted function <em>could be</em> of the type<br>
	    <img src="$module_dir/gifs/nivo$nivo.$(SIN$n).gif">
	    <br>
	!endif
	!if $instinker=1
	    !if $nivo=1
		Pay attention: some of the functions are really tricky:
		<br>
		what to think of <em>f(x)=d*sin(c*x)/b</em> or <em>f(x)=d+c*sin(x/b)</em>
	    !endif
	    !if $nivo=2
		Pay attention: some of the functions are really tricky:
		<br>
		what to think of <em>f(x)=s*sin(s*x)/s</em> ...
	    !endif
	!endif
	
	<small><em>
	    If you don't get the intention of this, look into the
	    !href target=wims_mhelp cmd=help
	    <b>help-pages</b></a>
	    </em></small>
	</p>	
    </td>
    <tr>
    <td>
	Determine the correct arguments/parameters to the function:
	<br>
	$(opgave$n)
	<br>
	<!-- Yes, sure , I know: you could read the page source and copy the wanted function...
	But you don't learn math that way. Although you may get very good grades ;)
	//-->
	<p align="center">
	    the <font color=$fontcolor2><em> $soort </em></font> function is:<br>
	<table>
	    <td>
		<font color=$fontcolor1 size="+2">
		    <em>	
			$(letter$n)(x)&nbsp;=
		    </em>
		</font>
	    </td>
	    <td>
		!if $wims_user=supervisor 
		    <input size=40 name="ANT$n" value="$(GOED$n)"> 
		!else
		    <input size=40 name="ANT$n" value="$(ANT$n)"> 
		!endif
	    </td>
	</table>
    </td>
</table>
