# checking the bruto formulas
score2=0
extra2=$empty
ca=!nospace $my_bruto
sa=!nospace $your_bruto
# let op haakjes checken !!!
# answers like: C5H2N4O6 == N4O6H2C5

#
ca1=!replace [0-9.] by , in $ca
ca2=!replace [A-Z.] by , in $ca
sa1=!replace [0-9.] by , in $sa
sa2=!replace [A-Z.] by , in $sa

!for p=1 to 2
    !for t=1 to 2
	ca$p=!replace ,, by , in $(ca$p)
	sa$p=!replace ,, by , in $(sa$p)
    !next t
    # better safe than sorry...
!next p

t=!char 1 of $ca1
!if $t=,
    ca1=!char 2 to -1 of $ca1
!endif
t=!char 1 of $ca2
!if $t=,
    ca2=!char 2 to -1 of $ca2
!endif
t=!char 1 of $sa1
!if $t=,
    sa1=!char 2 to -1 of $sa1
!endif
t=!char 1 of $sa2
!if $t=,
    sa2=!char 2 to -1 of $sa2
!endif

t=!char -1 of $ca1
!if $t=,
    ca1=!char 1 to -2 of $ca1
!endif
t=!char -1 of $ca2
!if $t=,
    ca2=!char 1 to -2 of $ca2
!endif
t=!char -1 of $sa1
!if $t=,
    sa1=!char 1 to -2 of $sa1
!endif
t=!char -1 of $sa2
!if $t=,
    sa2=!char 1 to -2 of $sa2
!endif

st=!itemcnt $sa1
ct=!itemcnt $ca1
!if $ct != $st
    !if $ct>$st
	ff=$[$st/$ct]
    !else
	ff=$[$ct/$st]
    !endif
!else
    ff=1
!endif

ss=0
!for p=1 to $ct
    c1=!item $p of $ca1
    c2=!item $p of $ca2
    c3=!toupper $c1
    !if $c3 = $c1
	# CH4 => CH,4
	do_check=0
    !else
	do_check=1
    !endif
    found=0
    !for s=1 to $st
	!if $found=0
	    s1=!item $s of $sa1
	    s2=!item $s of $sa2
	    !if $do_check=1
		t=!positionof $s1 in $sa1
		t1=!itemcnt $t
	        !if $t1>1
		    ex=!record 53 of lang/remarks.$taal
		    #@ In een bruto formule komen de atomen natuurlijk slechts &eacute;&eacute;n keer voor...
		    extra2=!append line $ex to $extra2
		!endif
	    !endif
	    !if $c1=$s1 and $c2=$s2
		!increase ss
		found=1
	    !else
		!if $c1=$s1
		    found=1
		    ex=!record 54 of lang/remarks.$taal
		    #@ je hebt je met atoom <kbd>$c1</kbd> vergist... ( $[abs($s2-$c2)] &times; ernaast)
		    extra2=!append line $ex to $extra2
		!endif
	    !endif
	!endif
    !next s
    !if $found=0
	ex=!record 55 of lang/remarks.$taal
	#@ Atoom $c1 komt niet voor in het molecuul...
	extra2=!append line $ex to $extra2
    !endif
!next p

score2=$[$ff*$ss/$ct]
!ifval $score2 > 0.9
    k2=green
!else
    !ifval $score2>0.5
	k2=orange
    !else
	k2=red
    !endif
!endif

!exit
