!header
!read Exindex

!if $lang=it

Questo modulo raggruppa al momento $exototal esercizi sugli sviluppi dei poliedri convessi.

(versione preliminare, non ancora disponibile la versione stampabile).

!goto tail
!endif

Ce module regroupe pour l'instant $exototal exercices sur les patrons des polyèdres convexes.

(en développement, pas de version imprimable).


:tail
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=
!read oef/intromenu.phtml
!tail
