!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes

<tr>
 <th>Pour les exercices <br /> "Lequel convient ?"</th>
 <td>
 !set wims_html_mode=li
<ul>
!formcheckbox  confparm1 list 1,2 prompt Trouver le script à partir de la figure, Trouver la figure à partir du script
</ul>
  </td>
</tr><tr>
 <th>Pour les exercices<br /> "Angles : ..."</th>
 <td>
 !set wims_html_mode=li
 <ul>
 !formradio confparm2 list 1,2 prompt Donner la mesure des angles tracés,Ne pas donner la mesure des angles tracés
  </ul>
 </td>
</tr>
