!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur des activités d'algorithmique
débranchée basées sur le document : <em>Bulletin officiel n° 22 du 29 mai 2019:</em>
<ul><li>Attendus de fin d'année en français et mathématiques</li>
<li>Repères annuels de progression en français, mathématiques et enseignement moral et civique
</li></ul>
<b>Niveau 1</b>
<ul>
<li>Réaliser des activités d’algorithmique débranchée.</li>
<li>Mettre en ordre et/ou compléter des blocs fournis par le professeur pour
construire un programme simple sur un logiciel de programmation.</li>
<li>Écrire un script de déplacement ou de construction géométrique
utilisant des instructions conditionnelles et/ou la boucle «Répéter...fois».
</li></ul>
<b> Toutes critiques ou propositions d'amélioration sont les bienvenues.</b>

<div class="wims_credits">
Élaboré avec la communauté <STRONG>
MutuWIMS</STRONG>.
</div>
!read oef/intromenu.phtml
!tail
