#if defined TARGET_airellelo
\text{name_instruction=Calculer l'aire du parallélogramme dans le plan cartésien
  dont les 4 sommets sont}
\text{name_hint=The area of the parallelogram is the length of the vector product
  of the two vectors representing two adjacent sides of the parallelogram.}
\text{name_answer=Aire}
#endif
#if defined TARGET_airepent
\text{name_instruction=Calculer l'aire du pentagone \(A B C D E) dans le plan cartésien
  dont les 5 sommets sont}
\text{name_answer=Aire}
#endif
#if defined TARGET_parallelo
\text{name_instruction=Calculer l'aire du parallélogramme dans le plan cartésien
  dont les 4 sommets sont}
\text{name_instruction2=Calculez les coordonnées du quatrième sommet}
#endif
#if defined TARGET_givenscale
\text{name_instruction=Soit, deux vecteurs dans le plan. Trouvez le vecteur \(v) tel que&nbsp;}
\text{name_hint=Ici, \(\langle \cdot, \cdot \rangle) est le produit scalaire.}
#endif
#if defined TARGET_combifind
\matrix{name_instruction=Soit
  deux vecteurs dans le plan et soit
  un autre vecteur. Exprimer \(v) comme combinaison linéaire de \(v_1)}
#endif
#if defined TARGET_combi3
\text{name_instruction=Soit,trois vecteurs dans le plan. Calculez le vecteur}
#endif
#if defined TARGET_combi
\text{name_instruction=Soient, deux vecteurs dans le plan. Calculez le vecteur}
#endif
#if defined TARGET_angle
\text{name_instruction=Soient trois points dans le plan&nbsp;}
\text{name_instruction2=Calculer l'angle \(\widehat{B A C})
  (en degrés, compris entre 0 et 180).}
\text{name_hint=Utiliser la relation entre le produit scalaire de deux vecteurs et
  l'angle entre leur angle.}
\text{name_answer=Angle}
#endif
#if defined TARGET_airetriang
\text{name_instruction=Calculer l'aire du triangle dans le plan cartésien
  dont les 3 sommets sont}
\text{name_hint=Le produit vectoriel de deux vecteurs donne l'aire d'un parallélogramme,
  et la moitié d'un parallélogramme est un triangle.}
\text{name_answer=Aire}
#endif
#if defined TARGET_airequadri
\text{name_instruction=Calculer l'aire du quadrilatère \(A B C D) dans le plan cartésien
  dont les 4 sommets sont}
\text{name_hint=Vous pouvez couper le quadrilatère en 2 triangles et calculer
l'aire de chaque triangle par le produit vectoriel.}
\text{name_answer=Aire}
#endif
#if defined TARGET_rellin
\matrix{name_instruction=Voici 3 vecteurs dans le plan&nbsp;
  Trouver 3 entiers \(a), \(b) et \(c) tels que
  et qui ne sont pas tous nuls.}
\text{name_cond1=sont des entiers non tous nuls}
\text{name_cond2=La somme algébrique des vecteurs est zéro}
#endif
