!header
!read Exindex
<div class="wims_msg" style="width:80%">
  Ce module regroupe pour l'instant $exototal exercices
  relatifs au remplissage du tableau des signes d'un trin&ocirc;me
  ou d'une fonction rationnelle simple à une variable réelle.<br>
  Ces exercices sont du niveau seconde.
  Ils ont été conçus dans le but de donner aux enseignants
  des classes de seconde des exemples d'exercices pouvant servir
  dans le cadre de l'<strong>aide individualisée</strong>.
</div>
!read oef/$module_language/intromenu.phtml
!tail
