\text{lang=slib(oef/env lang)}
#if defined TARGET_cplpremier1 || defined TARGET_cplpremier2 || defined TARGET_cplpremier3 || defined TARGET_cplpremier4 || defined TARGET_cplpremier5
# define TITRE Nombres premiers entre eux
#endif
#if defined TARGET_Applcritere1 || defined TARGET_Applcritere2 || defined TARGET_Applcritere3 || defined TARGET_Applcritere4 || defined TARGET_Applcritere5
# define TITRE Appliquer un critère de divisibilité
#endif
#if defined TARGET_vocabulaire1 || defined TARGET_vocabulaire2 || defined TARGET_vocabulaire3 || defined TARGET_vocabulaire4 || defined TARGET_vocabulaire5
# define TITRE Vocabulaire
#endif
#if defined TARGET_pgcd1 || defined TARGET_pgcd2 || defined TARGET_pgcd3 || defined TARGET_pgcd4 || defined TARGET_pgcd5
# define TITRE PGCD
#endif
#if defined TARGET_listdiv1 || defined TARGET_listdiv2 || defined TARGET_listdiv3 || defined TARGET_listdiv4 || defined TARGET_listdiv5
# define TITRE Liste de diviseurs
#endif
#if defined TARGET_calcfract1 || defined TARGET_calcfract2 || defined TARGET_calcfract3 || defined TARGET_calcfract4 || defined TARGET_calcfract5
# define TITRE Calcul fractionnaire
#endif
#if defined TARGET_critere1 || defined TARGET_critere2 || defined TARGET_critere3 || defined TARGET_critere4 || defined TARGET_critere5
# define TITRE Critères de divisibilité
#endif
#if defined TARGET_fractionsimp1 || defined TARGET_fractionsimp2 || defined TARGET_fractionsimp3 || defined TARGET_fractionsimp4 || defined TARGET_fractionsimp5
# define TITRE Réduction de fractions
#endif
