#include "lang_title_fr.inc"
#if defined TARGET_cplpremier1 || defined TARGET_Applcritere1 || defined TARGET_algoeuclide1 || defined TARGET_algosoustraction1 || defined TARGET_calcfract1 || defined TARGET_critere1 || defined TARGET_fractionsimp1 || defined TARGET_listdiv1 || defined TARGET_pgcd1 || defined TARGET_vocabulaire1
# define NUM 1
#endif
#if defined TARGET_cplpremier2 || defined TARGET_Applcritere2 || defined TARGET_algoeuclide2 || defined TARGET_algosoustraction2 || defined TARGET_calcfract2 || defined TARGET_critere2 || defined TARGET_fractionsimp2 || defined TARGET_listdiv2 || defined TARGET_pgcd2 || defined TARGET_vocabulaire2
# define NUM 2
#endif
#if defined TARGET_cplpremier3 || defined TARGET_Applcritere3 || defined TARGET_algoeuclide3 || defined TARGET_algosoustraction3 || defined TARGET_calcfract3 || defined TARGET_critere3 || defined TARGET_fractionsimp3 || defined TARGET_listdiv3 || defined TARGET_pgcd3 || defined TARGET_vocabulaire3
# define NUM 3
#endif
#if defined TARGET_cplpremier4 || defined TARGET_Applcritere4 || defined TARGET_algoeuclide4 || defined TARGET_algosoustraction4 || defined TARGET_calcfract4 || defined TARGET_critere4 || defined TARGET_fractionsimp4 || defined TARGET_listdiv4 || defined TARGET_pgcd4 || defined TARGET_vocabulaire4
# define NUM 4
#endif
#if defined TARGET_cplpremier5 || defined TARGET_Applcritere5 || defined TARGET_algoeuclide5 || defined TARGET_algosoustraction5 || defined TARGET_calcfract5 || defined TARGET_critere5 || defined TARGET_fractionsimp5 || defined TARGET_listdiv5 || defined TARGET_pgcd5 || defined TARGET_vocabulaire5
# define NUM 5
#endif
\title{TITRE NUM}
