!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les pourcentages. 
L'ensemble de ces exercices aborde les notions suivantes :
<ul><li>Définition d'un pourcentage</li>
<li>Calcul d'une valeur d'un pourcentage</li>
<li>Augmentation et diminution d'un pourcentage</li>
<li>Pourcentage indirect</li>
</ul>

Une approche pragmatique est réalisée et les thèmes suivants
 sont abordés :
<ul><li>sécurité</li>
<li>vie sociale</li>
<li>vie économique et professionnelle</li>
</ul>

Ils ont été réalisés pour une classe de 3<sup>e</sup>
 Prépa professionnelle. Par conséquent un exercice
 comporte un travail sur la fiche métier de l'ONISEP intitulé 
"Chef des ventes".
!read oef/intromenu.phtml
!tail
