!header
!read Exindex
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" title="Communauté MutuWIMS" style="float:right;margin-left:0.5em;margin-right:0.2em;"/>
Ce module regroupe pour l'instant $exototal exercices sur les statistiques descriptives.

Elaboré avec la communauté <STRONG>MutuWIMS</STRONG>
<div class="wims_credits">Certains exercices sont inspirés du module
!href module=H5/stat/OEFevalwimsstat.fr OEF Ev@lwims Statistiques 2
</div>
!read oef/intromenu.phtml
!tail
