#if defined TARGET_oefpyramid1 || defined TARGET_oefpyramid2 || defined TARGET_oefpyramid3 || defined TARGET_oefpyramid4 || defined TARGET_oefpyramid5
\text{name_statement=Trouver les nombres manquants.}
\text{name_decimal=Si nécessaire, vous utiliserez le point comme séparateur décimal.}
\text{name_inst=Le nombre du pavé du dessus est égal à la somme des nombres des deux pavés placés dessous.}
#endif
#if defined TARGET_oefdevinette1  || defined TARGET_oefdevinette2
\text{name_statement=Ma partie entière est,
  Ma partie décimale a trois chiffres après la virgule.,
  Mon chiffre des centièmes est,
  Mon chiffre des dixièmes est,
  Mon chiffre des millièmes est,
  Ma partie entière a quatre chiffres.,
  Mon nombre de dizaines est,
  Mon chiffre des unités est,
  Je suis le nombre}
#endif
#if defined TARGET_oefrecfractdec1 || defined TARGET_oefrecfractdec2 || defined TARGET_oefrecfractdec3 || defined TARGET_oefrecfractdec4 || defined TARGET_oefrecfractdec5 || defined TARGET_oefrecfractdec6 || defined TARGET_oefrecfractdec7
\text{name_comment=Le carré représente l'unité, c'est-à-dire 1.}
\text{name_statement=La partie coloriée correspond au nombre,
  Utiliser la fraction la plus simple.,
  en utilisant l'écriture d'un nombre décimal
}
\text{name_inst=Utiliser la virgule comme séparateur décimal \
  et éviter les zéros inutiles.}
#endif
#if defined TARGET_oefrecfractdec1 || defined TARGET_oefrecfractdec2 || defined TARGET_oefrecfractdec4 || defined TARGET_oefrecfractdec5 || defined TARGET_oefrecfractdec7
\text{name_stat=en utilisant l'écriture d'une fraction décimale}
#endif
#if defined TARGET_oefrecfractdec3
\text{name_stat=en utilisant une somme de fractions décimales}
#endif
#if defined TARGET_oefrecfractdec6
\text{name_stat=en utilisant la somme d'un nombre entier et de fractions décimales}
#endif
#if defined TARGET_oefzeroinutile1
\text{name_stat=Le nombre,se réécrit sans les zéros inutiles}
#endif
#if defined TARGET_oefplusmoins1
\text{name_stat=Choisir la bonne opération pour passer d'un nombre à l'autre}
#endif
#if defined TARGET_oefvocabulaire1
\text{name_mot=nombre,chiffres,somme,nombres,différence,termes}
\text{name_stat=Compléter les phrases ci-dessous}
\text{name_quest1=Le, est composé des,et}
\text{name_quest2=est la,des,et,Les, de la somme sont, et,
  Le calcul de cette, donne }
\text{name_quest3=est la,des nombres, et ,Les , de la différence sont, et,
  Le calcul de cette , donne}
#endif
#if defined TARGET_oeftiers1
\text{name_voc=double,triple,quart,tiers,quadruple,moitié}
\text{name_stat=Placer les mots suivants au bon endroit :
  double, tiers, moitié, triple, quart et quadruple.}
\text{name_isthe=est le,est le, est le, est le, est le, est la}
\text{name_of=de}
\text{name_inst=Il est possible d'utiliser plusieurs fois un même mot.}
#endif
