#include "lang_title_fr.inc"
#if defined TARGET_oefpyramid1 || defined TARGET_oefrecfractdec1 || defined TARGET_oefdevinette1
# define NUM 1
#endif
#if defined TARGET_oefpyramid2 || defined TARGET_oefrecfractdec2 || defined TARGET_oefdevinette2
# define NUM 2
#endif
#if defined TARGET_oefpyramid3 || defined TARGET_oefrecfractdec3
# define NUM 3
#endif
#if defined TARGET_oefpyramid4 || defined TARGET_oefrecfractdec4
# define NUM 4
#endif
#if defined TARGET_oefpyramid5 || defined TARGET_oefrecfractdec5
# define NUM 5
#endif
#if defined TARGET_oefrecfractdec6
# define NUM 6
#endif
#if defined TARGET_oefrecfractdec7
# define NUM 7
#endif
#if defined TARGET_oefzeroinutile1 || defined TARGET_oefplusmoins1 || defined TARGET_oeftiers1 || defined TARGET_oefvocabulaire1
# define NUM
#endif

\title{TITRE NUM}
