!set introhook_exists=yes
!if $lang iswordof it fr es nl
  !set def_lang=$lang
!endif
!if $lang iswordof it
  !set name_introhook=Tipo di numeri,Numero di oggetti ridondanti
!endif
!if $lang iswordof fr
    !set name_introhook=Type d'objets,Nombre d'objets redondants
!endif
!if $lang iswordof nl
    !set name_introhook=Soort objecten,Aantal overbodige objecten
!endif
!if $lang iswordof es
    !set name_introhook=Tipo de objetos,Número de objetos redundantes
!endif
!if $lang iswordof en
    !set name_introhook=Type of objects,Number of redundant objects
!endif

!default def_lang=en
!set n=!recordcnt data/data_$def_lang
!reset objlist
!for i=1 to $n
  !set l=!record $i of data/data_$def_lang
  !set l=!line 1 of $l
  !set objlist=!append item $l to $objlist
!next i
<tr><th><label for="confparm1">
$(name_introhook[1])
</label>
</th><td>
!formselect confparm1 from 1 to $n prompt $objlist
</td>
</tr><tr><th><label for="confparm2">
$(name_introhook[2])
</label>
</th><td>
<input size="3" name="confparm2" id="confparm2" value="0">
</td></tr>
