!header
!read Exindex
!if $lang iswordof it
  <div>
  Questo modulo contiene attualmente $exototal attività visive di aritmetica
  (addizioni e sottrazioni), che possono essere utilizzate come esercizi
  o come giochi.
  </div><div>
  Si tratta di attività &ldquo;drag &amp; drop&rdquo;, consistono cioè nel
  posizionare espressioni numeriche su una figura, con condizioni geometriche
  sulle somme. Il primo numero nel titolo indica il numero di oggetti
  da posizionare. Gli esercizi variano molto sia come stile che come
  livello di difficoltà in modo da venire incontro a esigenze didattiche
  molto diverse.
  </div>
  !goto end
!endif
!if $lang iswordof fr
  <div>
  Ce module contient pour l'instant $exototal activités d'entrainement visuel
  d'arithmétique (addition, soustraction), qu'on peut considérer comme
  exercices ou comme récréations.
  </div><div>
  Ce sont toutes des activités ``drag &amp; drop'', qui consistent à placer des
  nombres ou des expressions dans un dessin, avec des conditions géométriques
  sur les sommes. Le premier nombre dans la liste indique le nombre d'objets à
  placer. Avec une grande variation de styles et de niveau de difficulté pour
  satisfaire les besoins divers.
  </div>
  !goto end
!endif
!if $lang iswordof es
  <div>
  Este módulo contiene por el momento $exototal actividades de práctica visual
  de aritmética (adición, sustracción), que bien pueden ser consideradas
  ejercicios bien actividades recreativas.
  </div><div>
  Estas son actividades del tipo ``arrastra y pega''; consisten en poner
  números o expresiones dentro de una imagen, con condiciones geométricas
  sobre sus sumas. El primer número de la lista indica el número de objetos
  que debe ponerse. Con gran variedad de estilos y niveles de dificultad,
  puede satisfacer varios objetivos.
  </div>
  !goto end
!endif
!if $lang iswordof nl
  <div>
  Deze module bevat $exototal oefeningen met arithmetiek (optellen, aftrekken),
  die ofwel als sommen ofwel als ontspanning gezien kunnen worden.
  </div><div>
  Het zijn allemaal ``drag &amp; drop'' oefeningen, waarbij getallen of
  uitdrukkingen in een plaatje gezet moeten worden, met meetkundige voorwaarden
  op hun sommen. Het eerste getal in de lijst geeft aan hoeveel objecten er
  geplaatst moeten worden. Met een grote variatie aan stijlen en
  moeilijkheidsgraden om aan verschillende eisen te voldoen.
  </div>
!goto end
!endif
<div>
This module contains for the time being $exototal visual training activities
of arithmetics (addition, substraction), which can be considered either as
exercises or recreations.
</div><div>
These are all ``drag &amp; drop'' activities, consisting of placing numbers or
expressions into a picture, with geometric conditions on theirs sums. The
first number in the list indicates the number of objects to place. With a
wide variation of styles and difficulty levels in order to meet various
requirements.
</div>
!endif
:end
!read oef/$module_language/intromenu.phtml
!tail
