Interval notation for Range and Domain :
<ul>
    <li>write x&gt;=10 for  x&ge;10 or reverse 10&lt;=x for 10&le;x 
    </li>
    <li>write x&lt;=10 for x&le;10 or reverse  10&gt;=10 for 10&ge;x
    </li>
    <li>write y&lt;10 and y&gt;20 or reverse 10&gt;y and 20&lt;y
    </li>
    <li>write 10&lt;x&lt;20 
    </li>
    <li>we always start with the &lt; or &gt; sign, followed by a = sign.
    </li>
    <li>the Range or Domain could also be all Real numbers...x $m_in $m_RR<br />
    You answer should then be: <b>x element of R</b>  
    </li>
    <li>the Range or Domain could be all numbers except x=4 <br />
    You should fill in one of these for x $m_in $m_RR\{4}:
        <ul>
            <li>x element of R\{4}</li>
            <li>x&lt;4 and x&gt;4</li>
        </ul> 
    </li>
    <li>the Range or Domain could be all numbers except x=4 and x=6<br />
    You should fill in one of these for x $m_in $m_RR\{4,6}:
        <ul>
            <li>x element of R\{4,6}</li>
            <li>x&lt;4 and 4&lt;x&lt;6 and x&gt;6</li>
        </ul> 
    </li>
    <li>if you make a mistake -with a bit of luck- you may correct these syntax-based mistakes
    </li>
</ul>

