定义域与值域的区间表示法 :
<ul>
    <li>用 x&gt;=10 表示 x&ge;10 或反之用 10&lt;=x 表示 10&le;x 
    </li>
    <li>用 x&lt;=10 表示 x&le;10 或反之用 10&gt;=x 表示 10&ge;x
    </li>
    <li>用 y&lt;10 and y&gt;20 或反之用 10&gt;y and 20&lt;y
    </li>
    <li>用 10&lt;x&lt;20 
    </li>
    <li>总是先用 &lt; 或 &gt; 号后再接一个等号 = .
    </li>
    <li>定义域与值域也可以是所有实数...x $m_in $m_RR<br />
    那时你的回答应该是: <b>x element of R</b>  
    </li>
    <li>定义域与值域也可以是除 x=4 外的所有实数<br />
    这时对于 x $m_in $m_RR\{4} 可以填入:
        <ul> 
            <li>x element of R\{4}</li>
            <li>x&lt;4 and x&gt;4</li>
        </ul>          
    </li>
    <li>定义域与值域也可以是除 x=4 与 x=6 以外的所有实数<br />
    这时对于 x $m_in $m_RR\{4,6} 可以填入:
        <ul> 
            <li>x element of R\{4,6}</li> 
            <li>x&lt;4 and 4&lt;x&lt;6 and x&gt;6</li>
        </ul>          
    </li>
    <li>如果你出了错, 你可以纠正这些语法错误.
    </li>
</ul>

