Noteer bij Bereik en Domein de intervallen als volgt:
<ul>
    <li>noteer x&gt;=10 voor  x&ge;10 of andersom 10&lt;=x voor 10&le;x </li>
    <li>noteer x&lt;=10 voor x&le;10 of anderom  10&gt;=10 voor 10&ge;x</li>
    <li>noteer y&lt;10 en y&gt;20 of andersom 10&gt;y en 20&lt;y</li>
    <li>noteer 10&lt;x&lt;20</li>
    <li>we beginnen altijd met het &lt; of &gt; symbool, dan pas het = teken.</li>
    <li>het Bereik of Domein kunnen natuurlijk ook alle re&euml;ele getallen (x $m_in $m_RR) bevatten<br />
    Noteer dan iets als:<br />
    <b>x element van R</b>
    </li>
    <li>Het Bereik of Domein kunnen ook alle re&euml;ele getallen zijn, behalve bijvoorbeeld <em>x=4</em><br />
    geef dan &eacute;&eacute;n van de volgende mogelijkheden voor x $m_in $m_RR\{4} op:
	<ul>
	    <li>x element van R\{4}</li>
	    <li>x&lt;4 en x&gt;4</li>
	</ul>
    </li>
    <li>Het Bereik of Domein kunnen ook alle re&euml;ele getallen zijn, behalve bijvoorbeeld <em>x=4 en x=6</em><br />
    geef dan &eacute;&eacute;n van de volgende mogelijkheden voor x $m_in $m_RR\{4,6} op:
	<ul>
	    <li>x element van R\{4,6}</li>
	    <li>x&lt;4 en 4&lt;x&lt;6 en x&gt;6</li>
	</ul>
    </li>
    <li>Wordt specifiek gevraagd naar Bereik of Domein in "de interval notatie",<br /> 
    geef dan je antwoord op als: [5:+inf><br />
    of iets als: <-inf:8> U <8:+inf> desnoods korter: R\{8}

    <li>mocht je een foutje maken krijg je -met een beetje mazzel- de som ter correctie terug	
    </li>
</ul>

