#if defined TARGET_mean || defined TARGET_meanw || defined TARGET_seriestat || defined TARGET_effpourcent || defined TARGET_repartition2 || defined TARGET_repartition || defined TARGET_pourcentstat || defined TARGET_pourcentcirc || defined TARGET_pourcentangle
\author{Bernadette, Perrin-Riou}
\email{bernadette.m.riou@orange.fr}
#endif
#if defined TARGET_Moyennesetcoef || defined TARGET_Moyenne
\email{xiao@unice.fr}
\author{XIAO Dingyu}
#endif
#if defined TARGET_mediane
\author{Paul, Byache}
\email{paul-marcel-rog.byache@ac-aix-marseille.fr}
#endif
