#if defined TARGET_Moyenne
# define TITRE_nl Gemiddelden
#endif
#if defined TARGET_Moyennesetcoef
# define TITRE_nl Gemiddelden en co&euml;fficienten
#endif
#if defined TARGET_baton
# define TITRE_nl Construction d'un diagramme en bâtons
#endif
#if defined TARGET_effpourcent
# define TITRE_nl Aantal en percentages
#endif
#if defined TARGET_mean
# define TITRE_nl Statistisch gemiddelde
#endif
#if defined TARGET_meanw
# define TITRE_nl gemiddelde
#endif
#if defined TARGET_mediane
# define TITRE Médiane
#endif
#if defined TARGET_pourcentangle
# define TITRE_nl Cirkeldiagram en hoek
#endif
#if defined TARGET_pourcentcirc
# define TITRE_nl Cirkeldiagram en percentages
#endif
#if defined TARGET_pourcentstat
# define TITRE_nl Cirkeldiagram en aantallen
#endif
#if defined TARGET_repartition
# define TITRE_nl Verdelingen I
#endif
#if defined TARGET_repartition2
# define TITRE_nl Verdeling I
#endif
#if defined TARGET_seriestat
# define TITRE_nl Statistiek
#endif
