!header
!read Exindex
!if $lang=en
  This module actually contains $exototal exercises on the boundedness of
  subsets of real numbers: upper bounded, lower bounded, relation with union
  and intersection, etc.
  !goto end
!endif
Ce module regroupe pour l'instant $exototal exercices sur les majorations /
minorations d'ensembles de nombres réels&nbsp;: majoré, minoré, borné,
majorant, minorant, rapport avec intersection et union, etc.
ainsi que sur les bornes supérieures.
:end
!read oef/intromenu.phtml
!tail

