\language{fr}
\range{-5..5}

\computeanswer{no}
\format{html}
\precision{100}

\text{ltprop=Il a 4 côtés,
   Ses côtés opposés sont parallèles deux à deux,
   Ses côtés opposés ont même longueur deux à deux,
   Il a deux côtés opposés parallèles et de même longueur,
   Ses diagonales se coupent en leur milieu,
   Tous ses côtés ont même longueur,
   Ses diagonales sont perpendiculaires,
   Ses diagonales ont même longueur,
   Il a 3 angles droits,
   Il a un angle droit,
   Il a deux côtés consécutifs de même longueur}
\integer{nbprop=items(\ltprop)}

\text{lt=shuffle(A,B,C,D,E,F,G,H,K,L)}
\text{A=\lt[1]}
\text{B=\lt[2]}
\text{C=\lt[3]}
\text{D=\lt[4]}
\text{name=\A\B\C\D}
