!read language lang/names
!set wims_html_header=$wims_html_header\
 <style type="text/css">.float_left{float:left; padding-right:30px;}\
 </style>
!header

!read types/$ctype.phtml

!if $status=wait
 <p>$name_indication</p>
 !form reply
 <div class="float_left">
  !distribute items alt=Click,1,form click into ins_attr,ins_border,ins_tag
!else
 <div class="float_left"> 
  !set ins_attr=alt="Result"
!endif
  !insdraw fill 1,1,255,255,255\
transparent 255,255,255\
$ins_src
 </div>

$prompt
<br class="clearall" />
!if $status=wait
 !formend
!endif

!if $status!=wait

  <p>$name_ecart: $[rint($error*2)/10] mm.
   !if $reply_cnt<$shoots
    $name_average: $mean mm.
  </p>
  <p class="wimscenter">
   !set wims_ref_class=wims_button
   !href cmd=next $name_continue
  </p>
 !else
 </p><p>
  $name_theend = $mean mm,
  $name_score = $module_score/10.
  </p>
  <p>$name_resume
  !set insdraw_size=$[$ring_size*20],$[$ring_size*20]
  !insdraw fill 1,1,255,255,255\
   transparent 255,255,255\
   $rings\
   $target
  </p>

  !set wims_ref_class=wims_button
  <p class="wimscenter"> 
  !href cmd=renew&worksheet=$wims_sheet&$module_init_parm $name_news
&nbsp;
  !if $worksheet=$empty
   !set wims_ref_class=wims_button
   !href module=$module $name_change
  !endif
  </p>
 !endif
!endif

:end
!tail
