# Variable initialisation file.
# This file is read by wims for new sessions (cmd=new or cmd=renew)

!bound shoots between integer 1 and 20 default 3
!bound size   between integer 150 and 400 default 256

tt=
n=!itemcnt $type
!for i=1 to $n
 t=!item $i of $type
 t=$[rint($t)]
 !if $t>=1 and $t<=7
  tt=!append item $t to $tt
 !endif
!next i
type=$tt
!default type=1,2,3,4,5,6,7

reply_cnt=0
tot_error=0

wims_module_log=new: type $type
