#if defined TARGET_oefairedisq1 || defined TARGET_oefairedisq2 || defined TARGET_oefairedisq3 || defined TARGET_oefairedisq4 || defined TARGET_oefairedisq5
#define TITRE Aire du disque
#endif
#if defined TARGET_oefperimcercle1 || defined TARGET_oefperimcercle2 || defined TARGET_oefperimcercle3 || defined TARGET_oefperimcercle4 || defined TARGET_oefperimcercle5
# define TITRE Longueur du cercle
#endif
#if defined TARGET_oefperim1 || defined TARGET_oefperim2 || defined TARGET_oefperim3 || defined TARGET_oefperim4 || defined TARGET_oefperim5
# define TITRE Calculer un périmètre
#endif
#if defined TARGET_oefformrect1 || defined TARGET_oefformrect2 || defined TARGET_oefformrect3 || defined TARGET_oefformrect4 || defined TARGET_oefformrect5
# define TITRE Formule de l'aire du rectangle
#endif
#if defined TARGET_oefdefcomperim1 || defined TARGET_oefdefcomperim2 || defined TARGET_oefdefcomperim3 || defined TARGET_oefdefcomperim4 || defined TARGET_oefdefcomperim5
# define TITRE Comparaison de périmètres
#endif
#if defined TARGET_oefdefcompaire1 || defined TARGET_oefdefcompaire2 || defined TARGET_oefdefcompaire3 || defined TARGET_oefdefcompaire4 || defined TARGET_oefdefcompaire5
# define TITRE Comparaison d'aires
#endif
#if defined TARGET_oefconvlong1 || defined TARGET_oefconvlong2 || defined TARGET_oefconvlong3 || defined TARGET_oefconvlong4 || defined TARGET_oefconvlong5
# define TITRE Conversion de longueurs
#endif
#if defined TARGET_oefconvaire1 || defined TARGET_oefconvaire2 || defined TARGET_oefconvaire3 || defined TARGET_oefconvaire4 || defined TARGET_oefconvaire5
# define TITRE Conversion d'aires
#endif
#if defined TARGET_oefairetriqu1 || defined TARGET_oefairetriqu2 || defined TARGET_oefairetriqu3 || defined TARGET_oefairetriqu4 || defined TARGET_oefairetriqu5
# define TITRE Aire d'un triangle quelconque
#endif
#if defined TARGET_oefairetri1 || defined TARGET_oefairetri2 || defined TARGET_oefairetri3 || defined TARGET_oefairetri4 || defined TARGET_oefairetri5
# define TITRE Aire du triangle rectangle
#endif
#if defined TARGET_oefairequad1 || defined TARGET_oefairequad2 || defined TARGET_oefairequad3 || defined TARGET_oefairequad4 || defined TARGET_oefairequad5
# define TITRE Aire du pavage
#endif
#if defined TARGET_oefairedisq1 || TARGET_oefairedisq2 || TARGET_oefairedisq3 || defined TARGET_oefairedisq4 || defined TARGET_oefairedisq5
# define TITRE Aire du disque
#endif
#if defined TARGET_oefaire1 || defined TARGET_oefaire2 || defined TARGET_oefaire3 || defined TARGET_oefaire4 || defined TARGET_oefaire5
# define TITRE Aire
#endif
#if defined TARGET_oefformrect1 || defined TARGET_oefformrect2
# define TITRE Formule de l'aire du rectangle
#endif
#if defined TARGET_oefformdisq1 || defined TARGET_oefformdisq2 || defined TARGET_oefformdisq3 || defined TARGET_oefformdisq4 || defined TARGET_oefformdisq5
# define TITRE Formule de l'aire du disque
#endif
#if defined TARGET_oefformcercle1 || defined TARGET_oefformcercle2 || defined TARGET_oefformcercle3 || defined TARGET_oefformcercle4 || defined TARGET_oefformcercle5
# define TITRE Formule du périmètre du cercle
#endif
#if defined TARGET_oefperimaire1 || defined TARGET_oefperimaire2 || defined TARGET_oefperimaire3 || defined TARGET_oefperimaire4 || defined TARGET_oefperimaire5
# define TITRE Périmètre et aire
#endif
