#if defined TARGET_oefperimaire2 || defined TARGET_oefperimaire3 || defined TARGET_oefperimaire4
\text{enonc11=Le périmètre du rectangle est de }
\text{enonc3=L'aire du rectangle est de }
#endif
#if defined TARGET_oefperimaire5
\text{enonce=Donner la formule pour calculer le périmètre d'un rectangle&nbsp;,
  Donner la formule pour calculer l'aire d'un rectangle&nbsp;}
#endif
#if defined TARGET_oefperimaire1
\text{name_enonce=On considère un quadrillage de 1 cm sur 1 cm.,
  Trouver le périmètre de la figure rouge à l'aide du quadrillage&nbsp;,
  Trouver l'aire de la figure rouge à l'aide du quadrillage&nbsp;}
#endif
#if defined TARGET_oefperim1 || defined TARGET_oefperim2 || defined TARGET_oefperim3 || defined TARGET_oefperim4
\text{name_question=Vous devez calculer le périmètre de la figure.}
#endif
#if defined TARGET_oefperim4
\text{name_croix=Les quatre branches de la croix ont la même longueur et la même largeur}
#endif
#if defined TARGET_oefperim1 || defined TARGET_oefperim2 || defined TARGET_oefperim3 || defined TARGET_oefperim4 || defined TARGET_oefperim5
\text{r=Le périmètre}
#endif
#if defined TARGET_oefperim5
\text{r=La longueur}
#endif
#if defined TARGET_oefperim1 || defined TARGET_oefperim2 || defined TARGET_oefperim3 || defined TARGET_oefperim4 || defined TARGET_oefperim5
\text{name_is=est&nbsp;}
#endif
#if defined TARGET_oefperim1
\text{name_dim= Le rectangle a pour longueur, et pour largeur}
#endif
#if defined TARGET_oefperim2 || defined TARGET_oefperim3 || defined TARGET_oefperim4
\text{name_dim=Les dimensions sont les suivantes&nbsp;}
#endif
#if defined TARGET_oefperim5
\text{name_dim=Le rectangle a&nbsp;,pour périmètre, pour largeur}
#endif

#if defined TARGET_oefairequad1 || defined TARGET_oefairequad2 || defined TARGET_oefairequad3 || defined TARGET_oefairequad4 || defined TARGET_oefairequad5
\text{name_enonce=On considère un quadrillage de 1 cm sur 1 cm.}
\text{name_question=Trouver l'aire de la figure rouge à l'aide du quadrillage&nbsp;}
#endif
#if defined TARGET_oefformdisq1 || defined TARGET_oefformcercle1
\text{name_enonce=Choisir la valeur la plus proche de}
#endif
#if defined TARGET_oefformcercle2
\text{name_instruction=En cas de besoin, utiliser la virgule comme séparateur décimal.}
\text{name_question=On considère un cercle qui a un ,de,
  Calculer son}
#endif
#if defined TARGET_oefformcercle5
\text{name_question=Donner la formule pour calculer le périmètre d'un cercle,
  qui utilise le}
#endif
#if defined TARGET_oefconvlong1 || defined TARGET_oefconvlong2 || defined TARGET_oefconvlong3 || defined TARGET_oefconvlong4 || defined TARGET_oefconvlong5 || defined TARGET_oefconvaire1 || defined TARGET_oefconvaire2 || defined TARGET_oefconvaire3 || defined TARGET_oefconvaire4 || defined TARGET_oefconvaire5
\text{name_question=Convertir&nbsp;}
#endif
#if defined TARGET_oefperimaire5 || defined TARGET_oefperimcercle1 || defined TARGET_oefperimcercle2 || defined TARGET_oefperimcercle3 || defined TARGET_oefperimcercle4 || defined TARGET_oefperimcercle5 || defined TARGET_oefformdisq3 || defined TARGET_oefformcercle2 || defined TARGET_oefformcercle3 || defined TARGET_oefformcercle4 || defined TARGET_oefformcercle5 || defined TARGET_oefformdisq2 || defined TARGET_oefformdisq5 || defined TARGET_oefformrect1 || defined TARGET_oefformrect2 || defined TARGET_oefformrect3 || defined TARGET_oefformrect4  || defined TARGET_oefformrect5
\text{name_list=longueur,largeur,diamètre,rayon,côté,hauteur,base}
#endif
#if defined TARGET_oefformrect1 || defined TARGET_oefformrect2
\text{vol=Périmètre du rectangle,
  Périmètre du carré,
  Aire du carré,
  Aire du disque,
  Aire du triangle,
  Périmètre du cercle}
\text{name_question=Cliquer sur la formule de l'aire du rectangle&nbsp;}
#endif
#if defined TARGET_oefformrect1 || defined TARGET_oefformrect2
\text{voli=Aire du rectangle}
#endif
#if defined TARGET_oefformrect3 || defined TARGET_oefformrect4
\text{name_enonc1= On considère un rectangle qui a pour longueur,et pour largeur}
\text{enonc11=Donner l'aire du rectangle}
\text{name_formule=Formule}
#endif
#if defined TARGET_oefformrect5
\text{name_question=Donner la formule pour calculer l'aire d'un rectangle&nbsp;}
#endif
#if defined TARGET_oefformdisq5
\text{name_question=Donner la formule pour calculer l'aire d'un disque
  qui utilise le}
#endif
#if defined TARGET_oefformdisq2
\text{name_instruction=En cas de besoin, vous utiliserez la virgule
  comme séparateur décimal.}
#endif
#if defined TARGET_oefformdisq3 || defined TARGET_oefformdisq4
\text{vol=Périmètre du rectangle,
  Périmètre du carré,
  Aire du carré,
  Aire du rectangle,
  Aire du triangle,
  Périmètre du cercle,
  Aire du disque}
\text{voli=Donner la formule de l'aire du disque}
#endif
#if defined TARGET_oefformcercle3 || defined TARGET_oefformcercle4
\text{name_question=Cliquez sur la formule}
\text{vol=Périmètre du rectangle,
  Périmètre du carré,
  Aire du carré,
  Aire du disque,
  Aire du rectangle,
  Aire du triangle
}
\text{voli=du périmètre du cercle}
#endif
#if defined TARGET_oefformdisq2
\text{name_enonc=On considère un cercle qui a pour longueur de}
\text{name_question=Calculer son}
#endif
#if defined TARGET_oefdefcomperim1
\text{enonc1=On considère un quadrillage de 1 cm sur 1 cm.
 Le périmètre de la figure rouge est :}
#endif
#if defined TARGET_oefdefcomperim2
 \text{enonc1=On considère un pavage formé de triangles équilatéraux de 1 cm de côté.
 Le périmètre de la figure rouge est :}
#endif
#if defined TARGET_oefdefcomperim3
\text{enonc1=Le périmètre de la figure rouge est }
\text{enonc2=périmètre du rectangle \(A B C D\).}
#endif
#if defined TARGET_oefdefcomperim4
\text{enonc1= Le périmètre de la figure bleue est }
\text{enonc2= périmètre de la figure rouge.}
#endif
#if defined TARGET_oefdefcomperim5
\text{enonc1=Le périmètre de la figure rouge est }
\text{enonc2=périmètre de la figure bleue.}
#endif
#if defined TARGET_oefdefcomperim3 || defined TARGET_oefdefcomperim4 || defined TARGET_oefdefcomperim5
\text{name_rep=supérieur (sans être le double) au,inférieur (sans être la moitié) au,égal au,le double du,la moitié du}
#endif

#if defined TARGET_oefdefcompaire1
\text{enonc1=<p>On considère un quadrillage de 1 cm sur 1 cm.</p>
 L'aire de la figure rouge est :}
#endif
#if defined TARGET_oefdefcompaire2
\text{enonc1=<p>On considère un pavage formé de triangles équilatéraux d'aire 1 \(cm^2\).
</p> L'aire de la figure rouge est }
#endif
#if defined TARGET_oefdefcompaire3
\text{enonc1=L'aire de la figure rouge est }
\text{enonc2=l'aire du rectangle \(A B C D\).}
#endif
#if defined TARGET_oefdefcompaire4
\text{enonc1=L'aire de la figure bleue est }
\text{enonc2=l'aire de la figure rouge.}
#endif
#if defined TARGET_oefdefcompaire5
\text{enonc1=L'aire de la figure rouge est }
\text{enonc2=l'aire du la figure bleue.}
#endif
#if defined TARGET_oefairetriqu1 || defined TARGET_oefairetriqu2 || defined TARGET_oefairetriqu3 || defined TARGET_oefairetriqu4 || defined TARGET_oefairetriqu5
\text{name_enonc1=On considère un triangle quelconque \(A B C\) de hauteur \([A H]\).}
\text{name_enonc2=Nous avons&nbsp;:}
#endif
#if defined TARGET_oefairetriqu1 || defined TARGET_oefairetriqu2 || defined TARGET_oefairetriqu3 || defined TARGET_oefairetriqu4 || defined TARGET_oefairetriqu5
\text{enonc11=Calculer l'aire du triangle}
#endif
#if defined TARGET_oefairetri1 || defined TARGET_oefairetri2 || defined TARGET_oefairetri3
\text{enonc11=L'aire du triangle rectangle rouge est de }
#endif
#if defined TARGET_oefairetri1
\text{name_enonc1=On considère un carré de, de côté.}
#endif
#if defined TARGET_oefairetri2
\text{name_enonc1=On considère un rectangle. Son aire mesure}
#endif
#if defined TARGET_oefairetri3
\text{name_enonc1=On considère un rectangle. Sa longueur mesure , cm et sa largeur , cm.}
#endif
#if defined TARGET_oefairetri4
\text{name_enonc1=On considère un triangle \(A B C\) rectangle en \(B\).}
\text{enonc11=L'aire du triangle rectangle est de: }
#endif

#if defined TARGET_oefairetri5
\text{name_enonc1=On considère un triangle \(A B C\) rectangle en \(B\) avec,
  et son aire mesure}
\text{enonc11=Le côté \([B C]\) du triangle rectangle mesure: }
#endif
#if defined TARGET_oefairedisq1
\text{name_enonc=On considère un cercle qui a pour longueur de rayon}
\text{name_question=Calculer&nbsp;, rayon}
#endif
#if defined TARGET_oefairedisq2
\text{name_enonc = Soit un cercle dont le diamètre a pour longueur }
\text{name_question=Calculer, rayon}
#endif
#if defined TARGET_oefairedisq3
\text{name_enonc1=On considère un cercle qui a pour longueur de rayon,
  Donner l'aire du disque&nbsp;}
#endif
#if defined TARGET_oefairedisq4 || defined TARGET_oefairedisq5
\text{name_enonc1=On considère un cercle qui a pour longueur de ,
  Donner l'aire du disque&nbsp;}
#endif
#if defined TARGET_oefairedisq3 || defined TARGET_oefairedisq4
\text{instruction=On prendra 3 comme valeur approchée de \(\,\pi\).}
#endif
#if defined TARGET_oefairedisq5
  \text{instruction=On prendra 3.14 comme valeur approchée de \(\,\pi\).}
#endif
#if defined TARGET_oefaire1
\text{name_enonc1=On considère un carré de, de côté.}
\text{enonc11=L'aire de ce carré est de}
#endif
#if defined TARGET_oefaire2 || defined TARGET_oefaire3 || defined TARGET_oefaire4 || defined TARGET_oefaire5
\text{enonc11=L'aire du rectangle est de }
#endif
#if defined TARGET_oefaire2 || defined TARGET_oefaire3
\text{name_enonc1=On considère un rectangle fabriqué à l'aide de carrés identiques.
  Chaque carré mesure, de côté.}
#endif
#if defined TARGET_oefaire4 || defined TARGET_oefaire5 || defined TARGET_oefperimaire2 || defined TARGET_oefperimaire3 || defined TARGET_oefperimaire4
\text{name_enonc1=On considère un rectangle. Sa longueur mesure, sa largeur}
#endif
#if defined TARGET_oefperimcercle1 || defined TARGET_oefperimcercle2 || defined TARGET_oefperimcercle3 || defined TARGET_oefperimcercle4 || defined TARGET_oefperimcercle5
\text{name_enonc1= On considère un cercle qui a pour longueur de,
  Donner la longueur du cercle }
#endif
#if defined TARGET_oefperimcercle1 || defined TARGET_oefperimcercle2 || defined TARGET_oefperimcercle4 || defined TARGET_oefperimcercle5
\text{instruction=On prendra 3 comme valeur approchée de \(\,\pi\).}
#endif
#if defined TARGET_oefperimcercle3
\text{instruction=On prendra 3.14 comme valeur approchée de \(\,\pi\).}
#endif
#if defined TARGET_oefperimcercle4 || defined TARGET_oefperimcercle5
\text{name_enonc1= On considère un cercle qui a pour longueur, Donner la longueur du }
#endif
