#if defined TARGET_multintrus || defined TARGET_opsimple || defined TARGET_opsimple2 || defined TARGET_FractionsI || defined TARGET_FractionsII || defined TARGET_FractionsIII
# if defined TARGET_multintrus || defined TARGET_opsimple || defined TARGET_opsimple2
\author{Odile, Bénassy}
\email{obenassy@free.fr}
# else
\author{Michel, Gosse}
\email{michel.gosse@ac-poitiers.fr}
# endif
#else
\author{Bernadette, Perrin-Riou}
\email{bernadette.m.riou@orange.fr}
#endif
\language{fr}
\range{-5..5}
\computeanswer{no}
\format{html}
