#if defined TARGET_additfrac0 || defined TARGET_additfrac
# define TITRE Addition de fractions
#endif
#if defined TARGET_calcul
# define TITRE Priorités et calcul
#endif
#if defined TARGET_calcul2
# define TITRE Calcul et parenthèses
#endif
#if defined TARGET_calcprio
# define TITRE Règles de priorité
#endif
#if defined TARGET_FractionsI || defined TARGET_FractionsII || defined TARGET_FractionsIII
# define TITRE Fractions
#endif
#if defined TARGET_mult
# define TITRE Multiplication d'entiers relatifs
#endif
#if defined TARGET_multintrus
# define TITRE Multiplication : quel est l'intrus ?
#endif
#if defined TARGET_opsimple
# define TITRE Opérations simples sur les relatifs
#endif
#if defined TARGET_opsimple2
# define TITRE Opérations simples sur les relatifs
#endif
#if defined TARGET_regleadd
# define TITRE Règles de l'addition
#endif
#if defined TARGET_signe
# define TITRE Signe d'un produit
#endif
#if defined TARGET_transfmult
# define TITRE Transformation par multiplication
#endif
