#if defined TARGET_additfrac0 || defined TARGET_additfrac
# define TITRE_es Adición de fracciones
#endif
#if defined TARGET_calcul
# define TITRE_es Prioridades y cálculo
#endif
#if defined TARGET_calcul2
# define TITRE_es Cálculo y paréntesis
#endif
#if defined TARGET_calcprio
# define TITRE_es Reglas de prioridad
#endif
#if defined TARGET_FractionsI || defined TARGET_FractionsII || defined TARGET_FractionsIII
# define TITRE_es Fracciones
#endif
#if defined TARGET_mult
# define TITRE_es Multiplicación de enteros relativos
#endif
#if defined TARGET_multintrus
# define TITRE_es Multiplicación: ¿cuál es el intruso?
#endif
#if defined TARGET_opsimple
# define TITRE_es Operaciones simples con relativos
#endif
#if defined TARGET_opsimple2
# define TITRE_es Operaciones simples con relativos
#endif
#if defined TARGET_regleadd
# define TITRE_es Reglas de la adición
#endif
#if defined TARGET_signe
# define TITRE_es Signo de un producto
#endif
#if defined TARGET_transfmult
# define TITRE_es Transformación por multiplicación
#endif
