#if defined TARGET_additfrac0 || defined TARGET_additfrac
# define TITRE_nl Optellen van Breuken
#endif
#if defined TARGET_calcul
# define TITRE_nl Priorités et calcul
#endif
#if defined TARGET_calcul2
# define TITRE_nl Calcul et parenthèses
#endif
#if defined TARGET_calcprio
# define TITRE_nl Rekenregels
#endif
#if defined TARGET_FractionsI || defined TARGET_FractionsII || defined TARGET_FractionsIII
# define TITRE_nl Fractions
#endif
#if defined TARGET_mult
# define TITRE_nl Vermenigvuldiging van negatieve getallen
#endif
#if defined TARGET_multintrus
# define TITRE_nl Multiplication: quel est l'intrus ?
#endif
#if defined TARGET_opsimple
# define TITRE_nl Opérations simples sur les relatifs
#endif
#if defined TARGET_opsimple2
# define TITRE_nl Opérations simples sur les relatifs
#endif
#if defined TARGET_regleadd
# define TITRE_nl Règles de l'addition
#endif
#if defined TARGET_signe
# define TITRE_nl Signe d'un produit
#endif
#if defined TARGET_transfmult
# define TITRE_nl Transformatie door vermenigvuldiging
#endif
