#if defined TARGET_additfrac0 || defined TARGET_additfrac
# define TITRE_en Addition de fractions
#endif
#if defined TARGET_calcul
# define TITRE_en Priorités et calcul
#endif
#if defined TARGET_calcul2
# define TITRE_en Calcul et parenthèses
#endif
#if defined TARGET_calcprio
# define TITRE_en Priority rules
#endif
#if defined TARGET_FractionsI || defined TARGET_FractionsII || defined TARGET_FractionsIII
# define TITRE_en Fractions
#endif
#if defined TARGET_mult
# define TITRE_en Multiplication of signed integers
#endif
#if defined TARGET_multintrus
# define TITRE_en Multiplication : quel est l'intrus ?
#endif
#if defined TARGET_opsimple
# define TITRE_en Opérations simples sur les relatifs
#endif
#if defined TARGET_opsimple2
# define TITRE_en Opérations simples sur les relatifs
#endif
#if defined TARGET_regleadd
# define TITRE_en Règles de l'addition
#endif
#if defined TARGET_signe
# define TITRE_en Signe d'un produit
#endif
#if defined TARGET_transfmult
# define TITRE_en Transformation by multiplication
#endif
