#include "lang_title_fr.inc"

#if defined TARGET_etendue1 || defined TARGET_mediane1
# define NUM 1
#endif
#if defined TARGET_etendue2 || defined TARGET_mediane2
# define NUM 2
#endif
#if defined TARGET_etendue3 || defined TARGET_mediane3
# define NUM 3
#endif
#if defined TARGET_etendue4 || defined TARGET_mediane4
# define NUM 4
#endif
#if defined TARGET_etendue5 || defined TARGET_mediane5
# define NUM 5
#endif

\title{TITRE NUM}
