#if defined TARGET_mediane1 || defined TARGET_mediane2 || defined TARGET_mediane3
\text{name_enonce=Calculer la médiane de la série statistique suivante&nbsp;}
#endif
#if defined TARGET_mediane1 || defined TARGET_mediane2 || defined TARGET_mediane3 || defined TARGET_mediane4 || defined TARGET_mediane5
\text{name_head=Effectifs,Médiane}
#endif
#if defined TARGET_etendue1 || defined TARGET_etendue2 || defined TARGET_etendue3 || defined TARGET_etendue4 || defined TARGET_etendue5
\text{name_head=Effectifs,Étendue}
#endif
#if defined TARGET_mediane4
\text{name_enonce=Calculer la médiane de cette série statistique.}
#endif
#if defined TARGET_mediane5
\text{nameclass=Notes}
\text{name_sens=croissants,décroissants}
\text{name_enonce=Un enseignant a relevé les notes obtenues par ses élèves
  lors d'une interrogation notée sur,
  Il y a,élèves dans la classe.,
  Il a tracé le polygone des effectifs cumulés,ci-contre.}
\text{name_question=Quelle est la médiane de cette série statistique&nbsp;}
\text{name_inst=Vous arrondirez votre résultat à l'entier le plus proche.}
#endif
#if defined TARGET_etendue1 || defined TARGET_etendue2
\text{name_enonce=Calculer l'étendue de la série statistique suivante&nbsp;}
#endif
#if defined TARGET_etendue3
\text{name_question=Calculer l'étendue de cette série statistique.}
#endif
#if defined TARGET_etendue5
\text{name_enonce=Utiliser le diagramme en bâton ci-contre pour déterminer
  l'étendue de cette série statistique.}
#endif
#if defined TARGET_etendue4
\text{name_enonce=Utiliser le graphique ci-contre pour déterminer
  l'étendue de cette série statistique.}
#endif
#if defined TARGET_etendue1 || defined TARGET_etendue2 || defined TARGET_etendue3 || defined TARGET_etendue4 || defined TARGET_etendue5
\text{name_answer=Étendue}
#endif
