!header
!read Exindex
!if $lang=fr
Ce module regroupe pour l'instant $exototal exercices de
<b>niveau européen</b> : B2
<p><b>Objectifs :</b></p>
<ul><li><b>Compétence linguistique </b> : utilisation des temps du passé dans la narration.
</li><li><b>Compétence pragmatique</b> : convaincre en insistant sur certains mots
dans un discours (accent de phrase).
</li><li><b>Civilisationnel</b> : La présidence de Kennedy et les années soixante aux USA.
</li></ul>
<p><b>Activités de communication langagières :</b>
<ul><li><b>Réception</b> : Lecture du biographie de Kennedy.
</li><li>
<b>Interaction</b> : Repérage des mots accentués dans un discours puis
préparation d'une conversation en utilisant l'accent de phrase.
</li><li><b>Production</b> : Ecrire une biographie.
</li></ul>
L'ordre conseillé des exercices pour cette séquence est de A à I.
!else
<b>Common European Framework</b>: level B2<p><b>Objectives:</b></p>
<ul><li>
Using past tenses in a narrative.
</li><li>
Using sentence stress to highlight key points in oral discourse.
</li><li>
JF Kennedy and the 60'ies in the USA.
</li>
</ul>
<ul><li>Reading Kennedy's biography.</li>
<li>Using sentence stress in a conversation
for persuasion.</li>
<li>Writing a biography.</li>
</ul>

!endif

!read oef/$module_language/intromenu.phtml
!tail
