!set introhook_exists=yes
!set introhook_tableless=yes

<b>Types de transformations </b>
<table class="wimstable float_left">
<tr>
<td>
!set wims_ref_id=confparm11
!formcheckbox confparm1 list 1 prompt \(x^p x^q \rightarrow x^n\)
</td><td>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 2 prompt \(\frac{x^p}{x^q} \rightarrow x^n\)
</td><td>
!set wims_ref_id=confparm13
!formcheckbox confparm1 list 3 prompt \((x^p)^q \rightarrow x^n\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm14
!formcheckbox confparm1 list 4 prompt \(x x^p\rightarrow x^n\)
</td><td>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 5 prompt \(\frac{x^p}{x} \rightarrow x^n\)
</td><td>
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm17
!formcheckbox confparm1 list 7 prompt \((x^p)^r x^q \rightarrow x^n\)
</td><td>
!set wims_ref_id=confparm18
!formcheckbox confparm1 list 8 prompt \(\frac{(x^p)^r}{x^q} \rightarrow x^n\)
</td><td>
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm110
!formcheckbox confparm1 list 10 prompt \((x^p)^r (x^q)^s \rightarrow x^n\)
</td><td>
!set wims_ref_id=confparm111
!formcheckbox confparm1 list 11 prompt \(\frac{(x^p)^r}{(x^q)^s} \rightarrow x^n\)
</td><td>
</td>
</tr>
</table>
<div class="formHelp">
Sélectionnez le ou les types de transformations à effectuer.
</div>
