#if defined TARGET_boundedsqr1 || defined TARGET_boundedsqr2
# define TITRE_en Bounded square
#endif
#if defined TARGET_crossfrac || defined TARGET_crossfrac2
# define TITRE_en Cross fractions
#endif
#if defined TARGET_fracx1 || defined TARGET_fracx2 || defined TARGET_fracx3
# define TITRE_en Simple fraction
#endif
#if defined TARGET_majsqr1b || defined TARGET_majsqr2 || defined TARGET_majsqr2b || defined TARGET_majsqr3
# define TITRE_en Upper-bound the square
#endif
#if defined TARGET_possqr1 || defined TARGET_possqr2
# define TITRE_en Positive square
#endif
#if defined TARGET_product
# define TITRE_en Given product
#endif
#if defined TARGET_sollin
# define TITRE_en Linear solve
#endif
#if defined TARGET_sumprod || defined TARGET_sumprod2 || defined TARGET_sumprodb
# define TITRE_en Sum and product
#endif
#if defined TARGET_sumprod3a || defined TARGET_sumprod3b || defined TARGET_sumprod3b || defined TARGET_sumprod3b2
# define TITRE_en Sum and product of 3
#endif
#if defined TARGET_twoprod
# define TITRE_en Given two products
#endif
#if defined TARGET_twosqr
# define TITRE_en Two squares
#endif
#if defined TARGET_twosqrgiv
# define TITRE_en Given two squares
#endif
