\help{<b>Utilisation de la barre de navigation de JSXGraph</b>
<ul>
<li><b>Touche ( + ) :</b> zoom avant.</li>

<li><b>Touche ( 0 ) :</b> retour à l'affichage initial.</li>

<li><b>Touche ( – ) :</b> zoom arrière.</li>

<li><b>Flèche &#8592; (gauche) :</b> déplacer à gauche.</li>

<li><b>Flèche &#8594; (droite) :</b> déplacer à droite.</li>

<li><b>Flèche &#8593; (haut) :</b> déplacer vers le haut.</li>

<li><b>Flèche &#8595; (bas) :</b> déplacer vers le bas.</li>
</ul>
}
