!header
!read Exindex
!set wims_backslash_insmath=yes
Ce module regroupe pour l'instant $exototal exercices sur les équations de
droites dans un repère du plan.
Pour chaque exercice,<ol>
<li> équation de la forme \(y=a x+b\);</li>
<li> équation de la forme \(a x+ b y=c\);</li>
<li> équation de la forme \(a x+b y+c=0\).</li>
</ul>

!let tmp=!char 5 of $wims_version
!if $tmp!=$empty
 !let a=!positionof item $tmp in a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
 !let a=$[100+$a]
 !let a=!char 2 to 3 of $a
 !let test=!char 1 to 4 of $wims_version
 !let test=$test$a
!else
 !let test=$wims_version
!endif
!if $test>4.0101
 Vous pouvez accéder directement à une feuille de travail contenant la plupart des exercices de ce module en cliquant
 !href module=adm/sheet&+job=read&+sh=fr/H5/analysis/2equationdroite ici
 .
!endif
!read oef/intromenu.phtml
!tail
