
!if $module_score=$empty
 $name_already
 !exit
!endif

!if $shortcut=yes
 $name_answer1
!else
 $name_answer2
!endif
$name_answer3 $module_score/10.
<p>
!if $bestreply<$replycnt and $bestreply<$maxreply
 $name_best
 <p class="wimscenter">
 !set insplot_set=size 0.5,0.43; $plotset
 !set bestcv=!replace mycurvename by $name_myreply in $bestcurve
 !insplot [-$plotrange:$plotrange] $goodf title "f(x)" lt 8 $bestcv
 </p>
!else
 $name_last
!endif
<p>
$name_thefunction
<p class="wimscenter">
$mf(x) = $fx
</p>

