!header
!read language lang/names

!read present.phtml
<hr />

!if $status=waiting
 !if $error!=$empty
  <div class="wims_alertmsg">
  !read msg.phtml
  </div>
 !endif
 !read form.phtml
!set wims_ref_class=wims_button
 !href exo_Renew
 !if $bestdiff<1
  ($name_giveupnote)
 !endif
!else
 !if $error!=$empty
 <div class="wims_alertmsg">
  !read msg.phtml
  </div>
 !endif
 !read answer.phtml
 <p>
 !set wims_ref_class="wims_button"
 !href exo_Renew
</p>
!endif

:end
!tail
