#!/bin/bash
# Régénère un .oef depuis son source cpp, comme le préprocesseur de WIMS.
#
#   scripts/regenerer-oef.sh <source.cpp> <TARGET> <sortie.oef>
#
# Un même .cpp engendre plusieurs exercices, chacun sous une garde
# `#if defined TARGET_<nom>` ; sa première ligne (`target=a,b,c`) les énumère.
# Elle n'est pas du C et se retire avant l'appel au préprocesseur.
#
# Trois précautions, chacune payée par un essai raté (cf. docs/regenerer-un-oef.md) :
#
#   - le .cpp est en **latin-1**, et `cpp` remplacerait chaque octet accentué
#     par U+FFFD ; d'où la conversion aller-retour ;
#   - `-x c` force le mode C : sur l'extension `.cpp`, `cpp` cherche `cc1plus`,
#     absent d'une installation sans compilateur C++ ;
#   - le corps ne porte **aucune** ligne vide — le générateur d'origine les
#     supprime toutes —, l'en-tête étant trois commentaires puis trois lignes
#     vides. Sans cela, les lignes vides deviennent des tabulations dans le
#     `.def` et le fichier produit diffère de celui de WIMS.
#
# Vérifié sur les deux cibles intactes de `descriptives.fr` : `.oef` et `.def`
# identiques à ceux du dépôt, octet pour octet.
set -euo pipefail

if [ $# -ne 3 ]; then
    sed -n '2,20p' "$0"
    exit 2
fi

src=$1; target=$2; out=$3

{
  printf '%%%% This file is generated by preprocessor!\n'
  printf '%%%% Do not edit it by hand.\n'
  printf '%%%% Edit the source file cpp/%s.\n' "$(basename "$src")"
  printf '\n\n\n'
  tail -n +2 "$src" \
    | iconv -f latin1 -t utf8 \
    | cpp -P -traditional-cpp -x c -D "TARGET_$target" - \
    | iconv -f utf8 -t latin1 \
    | grep -av '^[[:space:]]*$'
} > "$out"

echo "$src [$target] -> $out"
