!if $subject=5 or $subject=6
    <img src="$module_dir/gifs/nivo4.1.gif" alt=" ^{g}\log\left( x \right) + a = ^{g}\log\left( b -x \right) \rightarrow"/>
    <br />
    <img src="$module_dir/gifs/nivo4.2.gif" alt=" ^{g}\log\left( x \right) + ^{g}\log\left( g^{a} \right)   = ^{g}\log\left( b -x \right) \rightarrow"/>
    <br />
    <img src="$module_dir/gifs/nivo4.3.gif" alt=" ^{g}\log\left( x \cdot g^{a} \right)  = ^{g}\log\left( b -x \right) \rightarrow"/>
    <br />
    <img src="$module_dir/gifs/nivo4.4.gif" alt=" x \cdot g^{a} = b -x \rightarrow"/>
    <br />
    <img src="$module_dir/gifs/nivo4.5.gif" alt=" x \cdot g^{a} + x = b \rightarrow"/>
    <br />
    <img src="$module_dir/gifs/nivo4.6.gif" alt=" x \cdot \left( g^{a} + 1 \right) = b \rightarrow"/>
    <br />
    <img src="$module_dir/gifs/nivo4.7.gif" alt=" x = \frac{b}{g^{a} +1}"/>		  
!endif
