If you can't think of an answer, <br />You may allways fill in a Questionmark "?"
<p>
!if $subject<10
    Pay attention: if you are not sure: <b>always use brackets</b><br />
    log(4x/5y) is log(<b>(</b>4x/5<b>)</b>*y) = log(4xy/5) =log(0.8*x*y) = log(0.8xy)
    <p>
    !if $teaching=1
	!set mytexsize=+4
	Powers and logaritms:<p>
	<table><tr><th>RULE</th><th>CONDITION</th></tr><tr>
	    <td>	
		<img src="$module_dir/gifs/help1.gif"  alt="g^{-n} = \frac{1}{g^{n}}" />
	    </td>
	    <td>
		<img src="$module_dir/gifs/help1b.gif"  alt=" g \\/>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help2.gif"  alt="g^{\frac{1}{n}} = \root n \of{g}" />
	    </td>
	    <td>
		<img src="$module_dir/gifs/help2b.gif"  alt="g \\/>\\ 0 \,\, , \,\, n \neq 0"> 
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help3.gif"   alt="g^{p} \cdot g^{q} = g^{p + q}" />
	    </td>
	    <td>
		<img src="$module_dir/gifs/help3b.gif"   alt="g \\/>\\ 0">
	    </td>
    	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help4.gif"   alt="\frac{g^{p}}{g^{q}} = g^{p - q}" />
	    </td>
	    <td>
		<img src="$module_dir/gifs/help4b.gif"   alt="g \\/>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help5.gif"    alt="^{g}\log \left( a \right) = \frac{\log \left( a \right) }{\log \left( g \right) }" />
	    </td>
	    <td>
		<img src="$module_dir/gifs/help5b.gif"    alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help6.gif"    alt="^{g}\log \left( a^{k}\right) = k \cdot ^{g}\log \left( a \right)" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help6b.gif"    alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help7.gif"   alt="^{g}\log\left( a \cdot b \right) = ^{g}\log\left( a \right) +  ^{g}\log\left( b \right) " /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help7b.gif"   alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0  \,\, , \,\, b \\>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help8.gif"   alt=" ^{g}\log\left( \frac{a}{b} \right) =   ^{g}\log\left( a \right) -  ^{g}\log\left( b \right)" />
	    </td>
	    <td>
		<img src="$module_dir/gifs/help8b.gif"   alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0  \,\, , \,\, b \\>\\ 0">
	    </td>    
	</table>
    !endif
!endif
!if $subject isin 16,17
    <p>
	!if $teaching=1
	some small example:<p>
	<img src="$module_dir/gifs/cosxmath.gif"  alt="cos(x)=-1/2" />
	<br />
	<img src="$module_dir/gifs/cosx.gif"  alt="cos(x)" />
	<br />
	!endif
	The general solution is:<br />
	<em>x</em><sub><small>1</small></sub>=2/3&pi;+2k&pi; and <em>x</em><sub><small>2</small></sub>=-2/3&pi;+2k&pi;
	<br />
	But the next set op solutions is -of course- also correct (check this)<br />
	<em>x</em><sub><small>3</small></sub>=2/3&pi;+2k&pi; and <em>x</em><sub><small>4</small></sub>=4/3&pi;+2k&pi;
        <br />
	You should write pi for &pi;
	<br />
	multipication sign are always wellcome: so preferably write  2*k*pi instead of 2k&pi;	
	
	<br />you could fill in<br />
<textarea readonly="readonly" cols="25" rows="2">
x1=2/3*pi+k*2pi
x2=2kpi-2/3
</textarea>

!endif
!if $subject=18
    <p>
    !if $teaching=1
	A small example:<p>
	<img src="$module_dir/gifs/nivo18a.gif"  alt="cos(x)=0.65" />
	<br />
	<img src="$module_dir/gifs/nivo18b.gif"  alt="cos(x)=0.65" />
	<br />
    !endif
	As you see in the domain between <b>0</b> and <b>4</b>&pi; , there are 4 intersection points between
	the graph of cos(x) and the line y=0.65<br />
	the solutions on  Domain [0:4&pi;] are there fore:<br />
<textarea readonly="readonly" cols="25" rows="4"> 
x1=0.86
x2=6.27
x3=2*pi+0.86321189
x4=12.56
</textarea>
<br />
You can also see in this example that you may round off at two decimals,<br />
And you still be using the number <b>pi</b> ;)
<br />
In case you forget a "few" x-values in your answer, you will get a penalty.<br />
By the way: the same is true for too many x-values...
!endif

!if ($subject isitemof 20,21,22,23,24) and ($teaching=1)
    In this exercise we seek answers like:<p>
    <table>
	<tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.1.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.11.gif" /> 
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.2.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.22.gif" />
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.3.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.33.gif" />
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.4.gif" />
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.44.gif" />
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.5.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.55.gif" />
	    </td>
	    </tr>
    </table>
 !exit
!endif
<hr />
!read $authordir/algemenehelp.phtml
			
