Als je op een vraag echt geen zinnig antwoord kan geven,<br />
typ dan maar een "vraagteken"<span size="2">?</span>
<p> 
!if $subject<10
    Denk er aan: gebruik bij twijfel altijd haakjes:
    log(4x/5y) is log(<b>(</b>4x/5<b>)</b>*y) = log(4xy/5) =log(0.8*x*y) = log(0.8xy)
    <p>
    !if $teaching=1
	Machten en logarithmen:<p>
	<table><tr><th>REGEL</th><th>VOORWAARDEN</th></tr><tr>
	    <td>	
		<img src="$module_dir/gifs/help1.gif"  alt="g^{-n} = \frac{1}{g^{n}}" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help1b.gif"  alt=" g \\/>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help2.gif"  alt="g^{\frac{1}{n}} = \root n \of{g}" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help2b.gif"  alt="g \\/>\\ 0 \,\, , \,\, n \neq 0"> 
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help3.gif"   alt="g^{p} \cdot g^{q} = g^{p + q}" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help3b.gif"   alt="g \\/>\\ 0">
	    </td>
    	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help4.gif"   alt="\frac{g^{p}}{g^{q}} = g^{p - q}" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help4b.gif"   alt="g \\/>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help5.gif"    alt="^{g}\log \left( a \right) = \frac{\log \left( a \right) }{\log \left( g \right) }" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help5b.gif"    alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help6.gif"    alt="^{g}\log \left( a^{k}\right) = k \cdot ^{g}\log \left( a \right)" />  
	    </td>
	    <td>
		<img src="$module_dir/gifs/help6b.gif"    alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help7.gif"   alt="^{g}\log\left( a \cdot b \right) = ^{g}\log\left( a \right) +  ^{g}\log\left( b \right) " />  
	    </td>
	    <td>
		<img src="$module_dir/gifs/help7b.gif"   alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0  \,\, , \,\, b \\>\\ 0">
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/help8.gif"   alt=" ^{g}\log\left( \frac{a}{b} \right) =   ^{g}\log\left( a \right) -  ^{g}\log\left( b \right)" /> 
	    </td>
	    <td>
		<img src="$module_dir/gifs/help8b.gif"   alt="g \\/>\\ 0 \,\, , \,\, g \neq 1 \,\, , \,\, a \\>\\ 0  \,\, , \,\, b \\>\\ 0">
	    </td>    
	</tr></table>
    !endif
 !exit
!endif
!if $subject=16 or $subject=17
    <p>
    !if $teaching=1
	Een klein voorbeeldje:<p>
	<img src="$module_dir/gifs/cosxmath.gif"  alt="cos(x)=-1/2" /> 
	<br />
	<img src="$module_dir/gifs/cosx.gif"  alt="cos(x)" /> 
	<br />
    !endif	
	De algemene oplossingen zijn dus:<br />
	<em>x</em><sub><small>1</small></sub>=2/3&pi;+2k&pi; en <em>x</em><sub><small>2</small></sub>=-2/3&pi;+2k&pi;
	<br />
	Maar de volgende set oplossingen zijn -natuurlijk- ook correct (controleer dit!)<br />
	<em>x</em><sub><small>3</small></sub>=2/3&pi;+2k&pi; en <em>x</em><sub><small>4</small></sub>=4/3&pi;+2k&pi;
        <br />
	jij moet natuurlijk intypen pi voor &pi;
	<br />
	Ook maaltekens worden op prijs gesteld: de 2k&pi; liever noteren als 2*k*pi
	<br />Zoals bijvoorbeeld:<br />
<textarea readonly="readonly" cols="25" rows="2">
x1=2/3*pi+k*2pi
x2=2kpi-2/3
</textarea>
 !exit
!endif
!if $subject=18
    <p>
    !if $teaching=1
	Een klein voorbeeldje:<p>
	<img src="$module_dir/gifs/nivo18a.gif"  alt="cos(x)=0.65" /> 
	<br />
	<img src="$module_dir/gifs/nivo18b.gif"  alt="cos(x)=0.65" /> 
	<br />
    !endif
	Je ziet in het plaatje tussen <b>0</b> en <b>4</b>&pi; , een 4-tal snijpunten tussen de cos(x) grafiek en de lijn y=0.65<br />
	De oplossingen op Domein [0:4&pi;] zijn dus:<br />
<textarea readonly="readonly" cols="25" rows="4">
x1=0.86
x2=6.27
x3=2*pi+0.86321189
x4=12.56
</textarea>
<br />
Je ziet dat je de antwoorden tot op twee decimalen mag afronden,<br />
	maar ook dat je <b>pi</b> mag laten staan ;)
	<br />
	Vergeet je een stuk of wat <em>x-waarden</em> in je antwoord , krijg je 'strafpunten'<br />
	En op teveel x-waarden staat ook al g&eacute;&eacute;n bonus...
 !exit
!endif
!if ($subject isitemof 20,21,22,23,24) and ($teaching=1)
    Bij deze som wordt een oplossing gezocht zoals bijvoorbeeld:<p>
    <table>
	    <td>
		<img src="$module_dir/gifs/nivo20.1.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.11.gif" /> 
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.2.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.22.gif" />
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.3.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.33.gif" />
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.4.gif" />
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.44.gif" />
	    </td>
	    </tr><tr>
	    <td>
		<img src="$module_dir/gifs/nivo20.5.gif" /> 
	    </td>
	    <td>
		&nbsp;&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;&nbsp;  
	    </td>
	    <td>
		<img src="$module_dir/gifs/nivo20.55.gif" />
	    </td>
    </tr></table>
 !exit
!endif
<hr />
!read $authordir/algemenehelp.phtml
			
