#if defined TARGET_addimemsigneguid || defined TARGET_addimemsigne
# define TITRE Addition de nombres relatifs de même signe
#endif
#if defined TARGET_addisignediffguid || defined TARGET_addisignediff
# define TITRE Addition de nombres relatifs de signes contraires 
#endif
#if defined TARGET_additrou || defined TARGET_additrousimpl
# define TITRE Addition à trou de nombres relatifs
#endif
#if defined TARGET_definition
# define TITRE Nombre relatif
#endif
#if defined TARGET_somalg1 || defined TARGET_somalg2 || defined TARGET_somalg3 || defined TARGET_somalgsimpl1 || defined TARGET_somalgsimpl2
# define TITRE Calcul d'une somme algébrique
#endif
#if defined TARGET_soust || defined TARGET_soustguid
# define TITRE Soustraction de nombres relatifs
#endif
#if defined TARGET_oppose
# define TITRE Déterminer l'opposé
#endif
#if defined TARGET_simplifie1 || defined TARGET_simplifie2
# define TITRE Simplifier une addition ou une soustraction de nombres relatifs
#endif
#if defined TARGET_situation || defined TARGET_situationsimpl
# define TITRE Associer une situation à une opération
#endif
#if defined TARGET_addisimpl
# define TITRE Addition de nombres relatifs #
#endif
#if defined TARGET_progcalcul
# define TITRE Programme de calcul
#endif
#if defined TARGET_actimemsigne || defined TARGET_actisignediff
# define TITRE Activité
#endif
