#if defined TARGET_diode
# define TITRE_nl Dioden en Lampen
#endif
#if defined TARGET_lampe
# define TITRE_nl Lampen en Voltage I
#endif
#if defined TARGET_lampe2
# define TITRE_nl Lampen en voltage II
#endif
#if defined TARGET_nomsymbol
# define TITRE_nl Associer le nom d'un composant à son symbole
#endif
#if defined TARGET_nomsymbolcorr
# define TITRE_nl Correspondance symbole - nom composants électriques
#endif
