#if defined TARGET_diode
# define TITRE Diodes
#endif
#if defined TARGET_lampe
# define TITRE Lampes et générateurs
#endif
#if defined TARGET_lampe2
# define TITRE Lampes et générateurs : tension
#endif
#if defined TARGET_nomsymbol
# define TITRE Associer le nom d'un composant à son symbole
#endif
#if defined TARGET_nomsymbolcorr
# define TITRE Correspondance symbole - nom composants électriques
#endif
