!header
!read Exindex
<div style="color:navy">Ce module regroupe pour l'instant $exototal exercices
pour apprendre à reconnaitre les principaux éléments d'une cellule végétale
(niveau seconde).

<ul><li>Dans l'exercice <i>"Eléments d'un cellule végétale 1"</i>, le nom d'un élément est donné et il faut sélectionner la définition de cet élément.
</li><li>Dans l'exercice <i>"Eléments d'un cellule végétale 2"</i>, la description d'un composant d'une cellule végétale est donnée et il faut retrouver le nom de ce composant dans une liste de noms.   </li>
<li>Dans l'exercice <i>"Eléments d'un cellule végétale 2*"</i>, la question est la même que dans l'exercice précédent mais il faut écrire le nom du composant, aucune liste n'est donnée.</li>
<li>Dans l'exercice <i>"Schéma d'une cellule végétale"</i>, il faut reconnaitre l'élément désigné sur le schéma d'une cellule végétale. </li>
<li>L'exercice <i>"Spécificités d'une cellule végétale"</i> est un exercice simple sur les différences entre la structure des cellules végétales et celle des cellules animales.  </li>
</ul>
</div>
On trouvera des exercices analogues sur la structure d'une cellule animale dans le module
!href module=U1/biology/oefcellstructure.fr  OEF Organites d'une cellule animale.

!read oef/$module_language/intromenu.phtml
!tail
