\text{reprise_rep=Vous avez répondu&nbsp;:}
\text{rep_exacte=Cette réponse est exacte.}
\text{rep_fausse=Cette réponse est fausse.}
\text{name_instruction=Vous devez utiliser les étiquettes proposées.}
\text{name_ans1=Expression correcte}
\text{name_ans2=Choix des propositions}
\text{name_ans3=Calcul correct}
\text{name_cond=Expression correcte&nbsp;?}
\text{sol1=ou}

#if defined TARGET_randonnee
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=PPP part en randonnée pendant NNN1 jours.<p> QQQ prévoit de marcher NNN2 km chaque matin et NNN3 km chaque après-midi sauf le dernier jour pendant lequel qqq marche NNN4 km de moins.}
\text{name_quest1=Écrire&#44; en une seule expression&#44; la distance totale&#44; en km&#44; parcourue par PPP.}
\text{name_quest2=Calculer en km&#44; la distance totale&#44; parcourue par PPP.}
\text{name_sol2=La distance totale parcourue est}
\text{name_unit=km.}
\text{name_ans2=la distance totale parcourue}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer la distance totale parcourue.}
\text{sol2=ou, si on utilise la seconde expression proposée&nbsp;:}

#endif
#if defined TARGET_bonbon
\text{name_sol1=Une expression possible est}
\text{name_text=PPP a NNN1 amis et chaque ami lui donne NNN2 bonbons.<p> QQQ décide de donner NNN3 bonbons à sa petite soeur.}
\text{name_quest1=Écrire&#44; en une seule expression&#44; le nombre de bonbons qu'il lui reste.}
\text{name_quest2=Calculer le nombre de bonbons qu'il lui reste.}
\text{name_sol2=Il lui reste}
\text{name_unit=bonbons.}
\text{name_ans2=le nombre de bonbons qu'il lui reste}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer le nombre de bonbons restants.}
\text{name_sing=bonbon}
\text{name_plur=bonbons}
#endif
#if defined TARGET_pomme
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=PPP a NNN3 paniers qui contiennent chacun NNN1 pommes.<p> QQQ ajoute NNN2 pommes dans chaque panier.</p>}
\text{name_quest1=Écrire&#44; en une seule expression&#44; le nombre total de pommes.}
\text{name_quest2=Calculer le nombre total de pommes.}
\text{name_sol2=Le nombre total de pommes est }
\text{name_unit=.}
\text{name_ans2=le nombre total de pommes }
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer le nombre total de pommes.}
#endif
#if defined TARGET_librairie
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=PPP part à la librairie avec en poche NNN3 €.<p> QQQ achète un livre à NNN1 € et une gomme à NNN2 €.</p>}
\text{name_quest1=Écrire en une seule expression&#44; la somme d'argent qu'il lui reste.}
\text{name_quest2=Calculer la somme d'argent qu'il lui reste.}
\text{name_sol2=Il va lui rester}
\text{name_unit=€.}
\text{name_ans2=la somme d'argent qu'il lui reste}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer la somme d'argent qu'il reste.}
#endif
#if defined TARGET_chocolat
\text{name_sol1=Une expression possible est}
\text{name_text=PPP a NNN4 € pour acheter NNN1 boîtes de chocolats coûtant NNN2 € pièce.<p>Au moment de payer, qqq utilise un bon de réduction de NNN3 €.</p>}
\text{name_quest1=Écrire en une seule expression&#44; la somme d'argent dépensée.}
\text{name_quest2=Calculer la somme d'argent dépensée.}
\text{name_sol2=QQQ va dépenser}
\text{name_unit=€.}
\text{name_ans2=la somme d'argent dépensée}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer la somme d'argent dépensée.}
#endif
#if defined TARGET_lacourse
\text{name_sol1=Une expression possible est}
\text{name_text=PPP pèse NNN1 kg une semaine avant une course cycliste.<p> QQQ fait un régime qui lui permet de perdre NNN2 kg par jour pendant NNN3 jours.</p>}
\text{name_quest1=Écrire en une seule expression&#44; sa masse le jour de la course.}
\text{name_quest2=Calculer sa masse le jour de la course.}
\text{name_sol2=Sa masse le jour de la course est}
\text{name_unit=kg.}
\text{name_ans2=sa masse le jour de la course}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer sa masse le jour de la course.}
#endif
#if defined TARGET_panini
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=PPP achète NNN1 sandwichs à NNN2 € chacun et NNN3 paninis.<p> QQQ donne NNN5 € et la boulangère lui rend NNN6 €.</p>}
\text{name_quest1=Écrire en une seule expression&#44; le prix d'un panini.}
\text{name_quest2=Calculer le prix d'un panini.}
\text{name_sol2=Le prix d'un panini est}
\text{name_unit=€.}
\text{name_ans2=le prix d'un panini}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer le prix d'un panini.}

#endif
#if defined TARGET_supermarche
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=PPP part faire ses courses avec NNN1 €.<p> QQQ achète NNN2 bouteilles de jus d’orange à NNN3 € pièce puis NNN4 baguettes de pain à NNN5 € pièce et NNN6 kilogrammes de pommes à NNN7 € le kg.</p>}
\text{name_quest1=Écrire une expression pour trouver la somme d’argent qu’il lui reste.}
\text{name_quest2=Calculer la somme d'argent qu'il lui reste.}
\text{name_sol2=Il lui reste}
\text{name_unit= €.}
\text{name_ans2=la somme d'argent qu'il lui reste}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer la somme d'argent qui lui reste.}
#endif
#if defined TARGET_depense
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=PPP achète un nouveau casque avec un micro pour son ordinateur et qui coûte NNN1 € et NNN2 cartouches d’encre pour son imprimante qui coûtent chacune NNN3 €.}
\text{name_quest1=Écrire une expression pour trouver la somme d’argent dépensée.}
\text{name_quest2=Calculer la somme d'argent dépensée.}
\text{name_sol2=QQQ a dépensé}
\text{name_unit=€.}
\text{name_ans2=la somme d'argent dépensée}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer la somme d'argent dépensée.}
#endif
#if defined TARGET_pile
\text{name_sol1=Une expression possible est}
\text{name_text=PPP a acheté une batterie externe à NNN2 € pour recharger son téléphone portable et NNN3 piles pour alimenter une lampe de camping.<p> QQQ a dépensé au total NNN1 €.</p>}
\text{name_quest1=Écrire une expression pour trouver le prix d'une pile.}
\text{name_quest2=Calculer le prix d'une pile.}
\text{name_sol2=Le prix d'une pile est}
\text{name_unit=€.}
\text{name_ans2=le prix d'une pile}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de calculer le prix d'une pile.}
#endif
#if defined TARGET_prog1
\text{name_sol1=Une expression possible est}
\text{name_text=Voici un programme de calcul.<ul><li>Choisis un nombre</li><li>Multiplie ce nombre par NNN2 </li><li>Ajoute NNN3 </li><li>Prends le double du résultat</li><li>Enlève NNN4 .</li>}
\text{name_quest1=En prenant NNN1 comme nombre de départ, écrire une formule qui donne le résultat du programme de calcul.}
\text{name_quest2=Calculer le résultat de ce programme de calcul.}
\text{name_sol2=En prenant NNN1 comme nombre de départ, le résultat du programme de calcul est}
\text{name_unit=.}
\text{name_ans2=}
\text{name_quest1_1=Choisir toutes les expressions qui traduisent le programme de calcul en prenant NNN1 comme nombre de départ.}
#endif
#if defined TARGET_autobus
\text{name_sol1=Il y a plusieurs expressions possibles.}
\text{name_text=Un bus transporte NNN1 personnes.<p>Au premier arrêt&#44; NNN2 personnes descendent et NNN3 montent.</p><p>Au deuxième arrêt&#44; NNN4 descendent et NNN5 montent.</p>}
\text{name_quest1=Écrire une expression pour trouver le nombre de passagers présents dans le bus après le deuxième arrêt.}
\text{name_quest2=Calculer le nombre de passagers présents dans le bus après le deuxième arrêt.}
\text{name_sol2=Après le deuxième arrêt&#44; il y a}
\text{name_unit= passagers dans l'autobus.}
\text{name_ans2=}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de trouver le nombre de passagers dans le bus après le deuxième arrêt.}
#endif
#if defined TARGET_camion
\text{name_sol1=Une expression possible est}
\text{name_text=Un camion transporte NNN1 kg de sable. A chaque arrêt, il décharge NNN2 kg.}
\text{name_quest1=Écrire une expression pour trouver la masse de sable après NNN3 arrêts.}
\text{name_quest2=Calculer la masse de sable après NNN3 arrêts.}
\text{name_sol2=Après NNN3 arrêts&#44; il reste }
\text{name_unit=kg de sable.}
\text{name_ans2=}
\text{name_quest1_1=Choisir toutes les expressions qui permettent de trouver la masse de sable après NNN3 arrêts.}
#endif
