\text{size=style="width:70px;height:70px;"}\help{ Voici le code des couleurs des atomes :
<table class="wimscenter wimsborder">
<tr>
	<th>Nom</th><th>Symbole</th><th>Image</th><th>Nom</th><th>Symbole</th>
	<th>Image</th><th>Nom</th><th>Symbole</th><th>Image</th>
</tr><tr>
 <td>bore</td>
 <td>B</td>
 <td><img src="\imagedir/atome/b.png" \size alt=""></td>
 <td>béryllium</td>
 <td>Be</td>
 <td><img src="\imagedir/atome/be.png" \size alt=""></td>
 <td>carbone</td>
 <td>C</td>
 <td><img src="\imagedir/atome/c.png" \size alt=""></td>
</tr><tr>
 <td>chlore</td>
 <td>Cl</td>
 <td><img src="\imagedir/atome/cl.png" \size alt=""></td>
 <td>fluor</td>
 <td>F </td>
 <td><img src="\imagedir/atome/f.png" \size alt=""></td>
 <td>hydrogène</td>
 <td>H</td>
 <td><img src="\imagedir/atome/h.png" \size alt=""></td>
 </tr><tr>
<td>azote</td>
 <td>N</td>
 <td><img src="\imagedir/atome/n.png" \size alt=""></td>
 <td>oxygène</td>
 <td>O</td>
 <td><img src="\imagedir/atome/o.png" \size alt=""></td>
 <td>phosphore</td>
 <td>P</td>
 <td><img src="\imagedir/atome/p.png" \size alt=""></td>
 </tr><tr>
<td>soufre</td>
 <td>S</td>
 <td><img src="\imagedir/atome/s.png" \size alt=""></td>
</tr>
</table>
}
