!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes
<ul>
<li><STRONG>Dominos des coefficients binomiaux </STRONG>
<br> Nombre de dominos à placer :</li>
<ul class="inline">
 !formradio confparm1 from 3 to 4 
</ul>

<li><STRONG>Déterminer le coefficient de z^n</STRONG>
<br> Nombre de répétitions :</li>
<ul class="inline">
 !formradio confparm2 from 1 to 5
</ul>

</ul>
