#if defined TARGET_flageu
# define TITLE_en Flags of Europe
#endif
#if defined TARGET_flagas
# define TITLE_en Flags of Asia
#endif
#if defined TARGET_flagaf
# define TITLE_en Flags of Africa
#endif
#if defined TARGET_flagam
# define TITLE_en Flags of America
#endif
#if defined TARGET_flagoc
# define TITLE_en Flags of Oceanic
#endif
#if defined TARGET_flagall
# define TITLE_en Flags of countries
#endif
#if defined TARGET_flagbig
# define TITLE_en Flags of big countries
#endif
#if defined TARGET_mapeu
# define TITLE_en Maps of Europa
#endif
#if defined TARGET_mapas
# define TITLE_en Maps of Asia
#endif
#if defined TARGET_mapaf
# define TITLE_en Maps of Africa
#endif
#if defined TARGET_mapam
# define TITLE_en Maps of America
#endif
#if defined TARGET_mapoc
# define TITLE_en Maps of Oceanic
#endif
#if defined TARGET_mapall
# define TITLE_en Maps of countries
#endif
#if defined TARGET_mapbig
# define TITLE_en Maps of big countries
#endif
