#if defined TARGET_flageu
# define TITLE Drapeaux d'Europe
#endif
#if defined TARGET_flagas
# define TITLE Drapeaux d'Asie
#endif
#if defined TARGET_flagaf
# define TITLE Drapeaux d'Afrique
#endif
#if defined TARGET_flagam
# define TITLE Drapeaux d'Amérique
#endif
#if defined TARGET_flagoc
# define TITLE Drapeaux de l'Océanie
#endif
#if defined TARGET_flagall
# define TITLE Drapeaux des pays
#endif
#if defined TARGET_flagbig
# define TITLE Drapeaux des grands pays
#endif
#if defined TARGET_mapeu
# define TITLE Cartes d'Europe
#endif
#if defined TARGET_mapas
# define TITLE Cartes d'Asie
#endif
#if defined TARGET_mapaf
# define TITLE Cartes d'Afrique
#endif
#if defined TARGET_mapam
# define TITLE Cartes d'Amérique
#endif
#if defined TARGET_mapoc
# define TITLE Cartes de l'Océanie
#endif
#if defined TARGET_mapall
# define TITLE Cartes des pays
#endif
#if defined TARGET_mapbig
# define TITLE Cartes des grands pays
#endif


