!set introhook_exists=yes
<tr><td colspan="2">Les paramètres ci-dessous ne sont pas utilisés dans tous les exercices.
</td></tr>
<tr><td >Calculs choisis parmi :</td>
    <td>
!default confparm1=1,2,3,4,5
!formcheckbox confparm1 list 1,2,3,4,5 prompt carré/racine carrée,inverse,double/moitié,multiplication/division,addition/soustraction
    </td></tr>
<tr><th>Niveau de difficulté :</th>
<td>
!default confparm2=3
!formradio confparm2 list 1,2,3 prompt facile,moyen,difficile
</td>
</tr>
<tr><th>Le nombre de départ (antécédent) est :</th>
<td>
!default confparm3=1
!formradio confparm3 list 1,2,3 prompt entier (entre 1 et 10),décimal (1 chiffre après la virgule),rationnel positif
</td>
</tr>
<tr><th>Présence du bouton javascript "Calcule" :</th>
<td>
!default confparm4=1
!formradio confparm4 list 1,2 prompt oui,non
</td>
</tr>
