!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur les programmes de calculs.

Ces exercices sont très largement paramétrables, ce qui permet de les proposer à des élèves de niveaux très variables.
<br/> Voici quelques exemples :
<ol>
<li><a href="wims.cgi?module=H2/algebra/progcalc.fr&cmd=new&exo=2sens&confparm1=3&confparm1=4&confparm1=5&confparm2=3&confparm3=1&confparm4=1&qnum=1&scoredelay=&seedrepeat=0&qcmlevel=1">
Pour travailler sur les 4 opérations et leurs opérations réciproques : </a>
<ul>
<li>Exercice : "Programme de calcul (2 sens)"</li>
<li>Calculs choisis parmi : double/moitié, multiplication/division, addition/soustraction</li>
<li>Nombre de départ : entier</li>
</ul></li>
<li><a href="wims.cgi?module=H2/algebra/progcalc.fr&cmd=new&exo=egalite&confparm1=4&confparm1=5&confparm2=1&confparm3=2&confparm4=1&qnum=1&scoredelay=&seedrepeat=0&qcmlevel=1">
Pour travailler au tout début de la résolution d'équations : </a>
<ul>
<li>Exercice : "Egalité de deux programmes de calcul(1)"</li>
<li>Calculs choisis parmi : multiplication/division, addition/soustraction</li>
<li>Niveau de difficulté : facile</li>
<li>Nombre de départ : décimal</li>
</ul></li>
<li><a href="wims.cgi?module=H2/algebra/progcalc.fr&cmd=new&exo=egalite0&confparm1=4&confparm1=5&confparm2=1&confparm3=3&confparm4=1&qnum=1&scoredelay=&seedrepeat=0&qcmlevel=1">
Un peu plus difficile sur les équations. </a>
<ul>
<li>Exercice : "Egalité de deux programmes de calcul(0)"</li>
<li>Calculs choisis parmi : multiplication/division, addition/soustraction</li>
<li>Niveau de difficulté : facile</li>
<li>Nombre de départ : rationnel</li>
</ul></li>
<li><a href="wims.cgi?module=H2/algebra/progcalc.fr&cmd=new&exo=antecedent&confparm1=1&confparm2=2&confparm3=1&confparm4=1&qnum=1&scoredelay=&seedrepeat=0&qcmlevel=1">
Pour observer qu'une équation du second degré peut avoir deux solutions. </a>
<ul>
<li>Exercice : "Antécédent par un programme de calcul"</li>
<li>Calculs choisis parmi : carré/racine carrée</li>
<li>Niveau de difficulté : moyen</li>
<li>Nombre de départ : entier</li>
</ul></li>
</ol>

!read oef/$module_language/intromenu.phtml
!tail
