!set n=!recordcnt src/data
!reset objlist
!for i=1 to $n
 !set l=!record $i of src/data
 !set l=!line 1 of $l
 !set objlist=!append item $l to $objlist
!next i

<tr><th><label for="confparm1">Tip elementov:</label>
</th><td>
!formselect confparm1 from 1 to $n prompt $objlist
</td>
</tr><tr><th><label for="confparm2">©tevilo odveènih elementov:</label>
</th><td>
<input size="3" name="confparm2" id="confparm2" value="0" />
</tr>
