!header
!read Exindex
Ta zbirka vaj vsebuje skupaj $exototal nalog oz. matematiènih ugank,
namenjenih utrjevanju osnovnih aritmetiènih
operacij (se¹tevanje in od¹tevanje).
Re¹evalec mora dopolniti mesta na sliki z ustreznimi ¹tevili 
iz pripravljenega seznama, tako da izpolni razliène pogoje. 
<p>
©tevilka v oklepaju pri imenu naloge pove ¹tevilo elementov, 
ki jih je potrebno pri tej nalogi
vstaviti na pravo mesto. Veèje ¹tevilo elementov pomeni
zahtevnej¹o nalogo. Na zahtevnost naloge pa lahko vplivamo tudi 
z drugimi nastavitvam: z vrsto ¹tevil (naravna, cela, ulomki...)
in ¹tevilom odveènih elementov.

!read oef/$module_language/intromenu.phtml
!tail
