
!set cut=!item $askcnt of 0,0,0,0,4,4,5,5
!set setbak=$insplot_set
<div class="wimscenter">
!set ins_border=2
!for i=1 to $askcnt
 !if $i isin $cut
  <br/>
 !endif
 !set ins_attr=alt="$name_choice $i"
 !set this=!item $i of $asklist
 !if $status=waiting
  !href cmd=reply&good=$i
  !insplot [-$xrange:$xrange] [-$yrange:$yrange] $(f$this) notitle
</a>
$ $
 !else
  !set insplot_set=$setbak
  !if $i=$good
   !set insplot_set=$insplot_set;label "$name_yourchoice" at -0.9*$xrange,0.5*$yrange
  !endif
  !if $i=$real
   !set insplot_set=$insplot_set;label "$name_goodanswer" at -0.9*$xrange,-0.5*$yrange
  !endif
  !insplot [-$xrange:$xrange] [-$yrange:$yrange] $(f$this) notitle
$ $
 !endif
!next i
</div>
