
!set cut=!item $askcnt of 0,0,0,3,4,4,46,47
<div class="wimscenter">
!for i=1 to $askcnt
 !if $i isin $cut
  <p>
 !else
  !if $i>1
   $
  !endif
 !endif
 !set this=!item $i of $asklist
 !set formula=!htmlmath $(f$this)
 !if $status=waiting
  !href cmd=reply&good=$i $formula
 !else
  !if $i=$good and $i!=$real
   <span class="bold">
  !endif
  !if $i=$real
   <span style="color:blue">
  !endif
  $formula
  !if $i=$good or $i=$real
   </span>
  !endif
 !endif
!next i
</div>
