Voici une résolution détaillée de (I) : \(\ineq\) :
<p>
Le logarithme existe si et seulement si
\(\u > 0\) c'est-à-dire pour
\(\x \symb0 \rep0\).
</p><p>
Sous cette condition, on a les équivalences suivantes :
<div class="wimscenter">
(I) \(\Longleftrightarrow ln(\utex) \symb1 \rep1\).
</div>
On applique la règle \(\ln(u) \symb1 v \Longleftrightarrow u \symb1 e^{v}\) :
<div class="wimscenter">
(I) \(\Longleftrightarrow \utex \symb1 e^{\rep1}\)
</br>
(I) \(\Longleftrightarrow \a\x \symb1 e^{\rep1} \oppb \)
</div>
On divise par \(\a\) \if{\a<0}{(en inversant le sens de l'inégalité car on divise par un nombre négatif)} :
<div class="wimscenter">
(I) \(\Longleftrightarrow \x \symb2 \texrep2 \)
</div>
</p>
<div>Posons \(\alpha = \texrep2 ).<br>
Les réels \(\x\) solutions de (I) doivent vérifier les deux inégalités :
 \(\x \symb0 \rep0 \) <b>et</b> \(\x \symb2 \alpha \)
</div>
Chaque inégalité définit un intervalle ; l'ensemble des solutions est l'intersection des
deux intervalles.
<p>Il vient que l'ensemble des solutions est
\if{\enssol=1}{vide, car les deux inégalités sont mutuellement incompatibles.}
\if{\enssol=2}{l'intervalle borné \if{\rep0<\rep2}{&#93; \rep0 ; \alpha &#91; }{&#93; \alpha ; \rep1 &#91;}. }
\if{\enssol=3}{l'intervalle &#93; \(\borne) ; +&#8734; &#91;}
\if{\enssol=4}{l'intervalle &#93; -&#8734; ; \(\borne) &#91;}
</p>
