#if defined TARGET_exp1
# define TITRE Réécriture avec des exponentielles (1)
#endif
#if defined TARGET_exp2
# define TITRE Réécriture avec des exponentielles (2)
#endif
#if defined TARGET_exp3
# define TITRE Exponentielles et notation puissance
#endif
#if defined TARGET_exp4
# define TITRE Réécrire avec une seule exponentielle
#endif
#if defined TARGET_ineqexp1
# define TITRE Inéquation du type c e^(ax+b) + d >0
#endif
#if defined TARGET_ineqexp2
# define TITRE Inéquation du type c e^(ax+b) > d
#endif
#if defined TARGET_ineqln
# define TITRE Inéquation avec logarithmes (1)
#endif
#if defined TARGET_ineqln1bis
# define TITRE Inéquation avec logarithmes (1 bis)
#endif
#if defined TARGET_ineqln2
# define TITRE Inéquation avec logarithmes (2)
#endif
#if defined TARGET_ineqln3
# define TITRE Inéquation avec logarithmes (3)
#endif
#if defined TARGET_ineqlnprof
# define TITRE Inéquation résolue en ln
#endif
#if defined TARGET_ln1
# define TITRE Réécriture avec des logarithmes (1)
#endif
#if defined TARGET_ln2
# define TITRE Réécriture avec des logarithmes (2)
#endif
#if defined TARGET_lnsuitegeo
# define TITRE Logarithme et suites géométriques
#endif
#if defined TARGET_qcmln
# define TITRE Etude d'une fonction logarithme (QCM)
#endif
#if defined TARGET_signeexp1
# define TITRE Signe d'une expression avec exp (1)
#endif
#if defined TARGET_signeexp2
# define TITRE Signe d'une expression avec exp (2)
#endif
#if defined TARGET_signeln1
# define TITRE Signe d'une expression avec ln (1)
#endif
#if defined TARGET_signeln2
# define TITRE Signe d'une expression avec ln (2)
#endif
#if defined TARGET_simplify1
# define TITRE Simplifications de base
#endif
