n=$counter
!if $impossible=1
    image=0
    draw=0
    plot=0
    image$n=$empty
    exotext=$empty
    !exit
!else
    !if $XRANGE=$empty
	XRANGE=-10,10
	YRANGE=-100,100
    !endif
    draw=1
    plot=0
    xsize=200
    ysize=200
    image_settings$n=$xsize,$ysize
    image$n=\
    xrange $XRANGE\
    yrange $YRANGE\
    linewidth 1\
    vline 0,0,blue\
    hline 0,0,blue\
    linewidth 2\
    $curve1\
    $curve2 \
    linewidth 6\
    $punten

    !if $teaching=1 and $image=0
	insdraw_size=160,160
	!insdraw $(image$n)
	image$n=$empty
	etext=!record 1 of lang/remarks.$taal
	exotext=<a onmouseover="return escape('<img src=\'$wims_refname?&session=$session&module=$module&cmd=getins&special_parm=insert-1.gif\' alt=\'noalt\' />')">$etext</a>
    !endif
!endif
