#if defined TARGET_difference_symetrique
# define TITLE Différence symétrique
#endif
#if defined TARGET_optique1
# define TITLE Convergence et divergence d'une lentille
#endif
#if defined TARGET_optique2
# define TITLE Objet et image réels ou virtuels
#endif
#if defined TARGET_optique3
# define TITLE Renversée ou droite
#endif
#if defined TARGET_optique3cv
# define TITLE Objet ou image à trouver
#endif
#if defined TARGET_optique3cv2
# define TITLE Objet ou image à trouver (II)
#endif
#if defined TARGET_foyer
# define TITLE Foyer
#endif
#if defined TARGET_foyercv
# define TITLE Foyer cliqué
#endif
#if defined TARGET_foyercalcul
# define TITLE Centre optique et foyer (calcul)
#endif
#if defined TARGET_optique4
# define TITLE Centre optique et foyer
#endif
#if defined TARGET_optique2cv
# define TITLE Objet, image, réels, virtuels (lentille cv)
#endif
#if defined TARGET_optique4cv
# define TITLE Centre optique et foyer (cv)
#endif

