!header
!read Exindex
<style>
.logo_desc_mod {
  float:right;
  margin-left:0.5em;
  margin-right:0.2em;
  margin-top:0.2em;
}
</style>
Ce module regroupe pour l'instant $exototal exercices sur les notions d'ordre,
d'intervalle, de valeur absolue et de distance.
<img src="$module_dir/images/logo_euler.png" class="logo_desc_mod" alt="Logo Euler Académie de Versailles" title="Euler Académie de Versailles" width="48" height="36">
<div class="wims_credits">
Module de Régine Mangeard maintenu et complété par le groupe Euler de l'académie de Versailles.
</div>
!read oef/$module_language/intromenu.phtml
!tail
