#if defined TARGET_relrtdeg3
# define TITLE_en Function of roots deg 3
#endif
#if defined TARGET_mindeggcd2
# define TITLE_en Min. deg gcd with derivative 2
#endif
#if defined TARGET_stadouble
# define TITLE_en Root status deg 2
#endif
#if defined TARGET_deggcd
# define TITLE_en Deg gcd with derivative
#endif
#if defined TARGET_relrtdeg2
# define TITLE_en Function of roots deg 2
#endif
#if defined TARGET_givderiv
# define TITLE_en Given gcd with derivative
#endif
#if defined TARGET_parmdeg2
# define TITLE_en Parametrized deg 2
#endif
#if defined TARGET_diffeqn
# define TITLE_en Difference equation
#endif
#if defined TARGET_tripledeg3b
# define TITLE_en Triple root deg 3 II
#endif
#if defined TARGET_degsum
# define TITLE_en Degree of sum
#endif
#if defined TARGET_givrtdeg3
# define TITLE_en Given root deg 3
#endif
#if defined TARGET_rootcomp
# define TITLE_en Root of composed polynomial
#endif
#if defined TARGET_parmdeg2b
# define TITLE_en Parametrized deg 2 II
#endif
#if defined TARGET_rootmultsum
# define TITLE_en Root multiplicity of sum
#endif
#if defined TARGET_tripledeg3
# define TITLE_en Triple root deg 3
#endif
#if defined TARGET_trinomefact
# define TITLE_en factorization of trinomial
#endif
#if defined TARGET_quadpoly
# define TITLE_en Roots complex polynomial deg 2
#endif
#if defined TARGET_rootdeg2
# define TITLE_en Real roots deg 2
#endif
#if defined TARGET_rootcnt
# define TITLE_en Count roots with derivative
#endif
#if defined TARGET_rerootdeg2
# define TITLE_en Re(root) deg 2
#endif
#if defined TARGET_mindeggcdn
# define TITLE_en Min. deg gcd with derivative n
#endif
#if defined TARGET_degmult
# define TITLE_en Min. deg multiple roots
#endif
#if defined TARGET_multparm3 || defined TARGET_multparm4
# define TITLE_en Parametric multiplicity degree DEG
#endif
#if defined TARGET_multiplicity3 || defined TARGET_multiplicity4 || defined TARGET_multiplicity5 || defined TARGET_multiplicity6
# define TITLE_en Multiplicity of a root degree DEG
#endif
#if defined TARGET_findmult3 || defined TARGET_findmult4 || defined TARGET_findmult5 || defined TARGET_findmult6
# define TITLE_en Find multiple root degree DEG
#endif
