#if defined TARGET_relrtdeg3
# define TITLE_it Funzione delle radici di grado 3
#endif
#if defined TARGET_mindeggcd2
# define TITLE_it Min. grado MCD con derivata 2
#endif
#if defined TARGET_stadouble
# define TITLE_it Stato delle radici di grado 2
#endif
#if defined TARGET_deggcd
# define TITLE_it Grado di MCD tramite derivata
#endif
#if defined TARGET_relrtdeg2
# define TITLE_it Funzione delle radici di grado 2
#endif
#if defined TARGET_givderiv
# define TITLE_it MCD dato tramite derivata
#endif
#if defined TARGET_parmdeg2
# define TITLE_it Parametrizzazione grado 2
#endif
#if defined TARGET_diffeqn
# define TITLE_it Equazione della differenza
#endif
#if defined TARGET_tripledeg3b
# define TITLE_it Radici triple grado 3 II
#endif
#if defined TARGET_degsum
# define TITLE_it Grado di somme
#endif
#if defined TARGET_givrtdeg3
# define TITLE_it Radici date di grado 3
#endif
#if defined TARGET_rootcomp
# define TITLE_it Radici di polinomi composti
#endif
#if defined TARGET_parmdeg2b
# define TITLE_it Parametrizzazione grado 2 II
#endif
#if defined TARGET_rootmultsum
# define TITLE_it Molteplicità radici di composizioni
#endif
#if defined TARGET_tripledeg3
# define TITLE_it Radici triple grado 3
#endif
#if defined TARGET_trinomefact
# define TITLE_it Scomposizione di un trinomio
#endif
#if defined TARGET_quadpoly
# define TITLE_it Radici di un polinomio complesso di grado 2
#endif
#if defined TARGET_rootdeg2
# define TITLE_it Radici reali grado 2
#endif
#if defined TARGET_rootcnt
# define TITLE_it Conteggio radici tramite derivata
#endif
#if defined TARGET_rerootdeg2
# define TITLE_it Re(radici) grado 2
#endif
#if defined TARGET_mindeggcdn
# define TITLE_it Min. grado MCD con derivata n
#endif
#if defined TARGET_degmult
# define TITLE_it Min. grado radici multiple
#endif
#if defined TARGET_multparm3 || defined TARGET_multparm4
# define TITLE_it Molteplicità parametrica di grado DEG
#endif
#if defined TARGET_multiplicity3 || defined TARGET_multiplicity4 || defined TARGET_multiplicity5 || defined TARGET_multiplicity6
# define TITLE_it Molteplicità di una radice di grado DEG
#endif
#if defined TARGET_findmult3 || defined TARGET_findmult4 || defined TARGET_findmult5 || defined TARGET_findmult6
# define TITLE_it Trovare radici multiple di grado DEG
#endif
