#if defined TARGET_relrtdeg3
# define TITLE Fonction de racines deg 3
#endif
#if defined TARGET_mindeggcd2
# define TITLE Min. deg pgcd avec dérivée 2
#endif
#if defined TARGET_stadouble
# define TITLE Statut racines deg 2
#endif
#if defined TARGET_deggcd
# define TITLE Degré du pgcd avec dérivée
#endif
#if defined TARGET_relrtdeg2
# define TITLE Fonction de racines deg 2
#endif
#if defined TARGET_givderiv
# define TITLE pgcd donné avec dérivée
#endif
#if defined TARGET_parmdeg2
# define TITLE Paramétré deg 2
#endif
#if defined TARGET_diffeqn
# define TITLE Equation de différence
#endif
#if defined TARGET_tripledeg3b
# define TITLE Racine triple deg 3 II
#endif
#if defined TARGET_degsum
# define TITLE Degré de somme
#endif
#if defined TARGET_givrtdeg3
# define TITLE Racine donnée deg 3
#endif
#if defined TARGET_rootcomp
# define TITLE Racine de polynôme composé
#endif
#if defined TARGET_parmdeg2b
# define TITLE Paramétré deg 2 II
#endif
#if defined TARGET_rootmultsum
# define TITLE Multiplicité racine de somme
#endif
#if defined TARGET_tripledeg3
# define TITLE Racine triple deg 3
#endif
#if defined TARGET_trinomefact
# define TITLE Factorisation de trinôme
#endif
#if defined TARGET_quadpoly
# define TITLE Racines polynome complexe deg 2
#endif
#if defined TARGET_rootdeg2
# define TITLE Racines réelles deg 2
#endif
#if defined TARGET_rootcnt
# define TITLE Compte racines avec dérivée
#endif
#if defined TARGET_rerootdeg2
# define TITLE Re(racine) deg 2
#endif
#if defined TARGET_mindeggcdn
# define TITLE Min. deg pgcd avec dérivée n
#endif
#if defined TARGET_degmult
# define TITLE Min. deg racines multiples
#endif
#if defined TARGET_multparm3 || defined TARGET_multparm4
# define TITLE Multiplicité paramétrée degré DEG
#endif
#if defined TARGET_multiplicity3 || defined TARGET_multiplicity4 || defined TARGET_multiplicity5 || defined TARGET_multiplicity6
# define TITLE Multiplicité racine de degré DEG
#endif
#if defined TARGET_findmult3 || defined TARGET_findmult4 || defined TARGET_findmult5 || defined TARGET_findmult6
# define TITLE Trouver racine multiple degré DEG
#endif
