!header
!read Exindex
!if $lang=nl
  Deze module bevat $exototal oefeningen over de Stelling van Pythagoras
  voor rechthoekige driehoeken.
  !goto end
!endif
!if $lang=it
  Questo modulo contiene al momento $exototal esercizi sul Teorema di Pitagora
  per i triangoli rettangoli.
  !goto end
!endif
Ce module regroupe pour l'instant $exototal exercices sur le théorème de
Pythagore pour les triangles rectangles dans le cadre d'applications pratiques.
:end
!read oef/intromenu.phtml
!tail
