#if defined TARGET_calculA1 || defined TARGET_calculA2 || defined TARGET_calculA3 || defined TARGET_calculA4 || defined TARGET_calculA5 || defined TARGET_calculB1 || defined TARGET_calculB2 || defined TARGET_calculB3 || defined TARGET_calculB4 || defined TARGET_calculB5 || defined TARGET_calculC1 || defined TARGET_calculC2 || defined TARGET_calculC3 || defined TARGET_calculC4 || defined TARGET_calculC5
# define TITRE Calcul
#endif
#if defined TARGET_comparer1 || defined TARGET_comparer2 || defined TARGET_comparer3 || defined TARGET_comparer4 || defined TARGET_comparer5
# define TITRE Comparer deux nombres décimaux
#endif
#if defined TARGET_distance01 || defined TARGET_distance02 || defined TARGET_distance03 || defined TARGET_distance04 || defined TARGET_distance05
# define TITRE Distance à zéro
#endif
#if defined TARGET_distance1 || defined TARGET_distance2 || defined TARGET_distance3 || defined TARGET_distance4 || defined TARGET_distance5
# define TITRE Distance entre deux points
#endif
#if defined TARGET_lectcoord1 || defined TARGET_lectcoord2 || defined TARGET_lectcoord3 || defined TARGET_lectcoord4 || defined TARGET_lectcoord5
# define TITRE Lire les coordonnées d'un point
#endif
#if defined TARGET_lecturegraph1 || defined TARGET_lecturegraph2 || defined TARGET_lecturegraph3 || defined TARGET_lecturegraph4 || defined TARGET_lecturegraph5
# define TITRE Lire l'abscisse d'un point
#endif
#if defined TARGET_lecturegraphB1 || defined TARGET_lecturegraphB2 || defined TARGET_lecturegraphB3 || defined TARGET_lecturegraphB4 || defined TARGET_lecturegraphB5
# define TITRE Lire l'abscisse d'un point
#endif
#if defined TARGET_oppose1 || defined TARGET_oppose2 || defined TARGET_oppose3 || defined TARGET_oppose4 || defined TARGET_oppose5
# define TITRE Points opposés
#endif
#if defined TARGET_phrase1 || defined TARGET_phrase2 || defined TARGET_phrase3 || defined TARGET_phrase4 || defined TARGET_phrase5
# define TITRE Écrire un calcul
#endif
#if defined TARGET_placerpt1 || defined TARGET_placerpt2 || defined TARGET_placerpt3 || defined TARGET_placerpt4 || defined TARGET_placerpt5
# define TITRE Placer un point sur une droite graduée
#endif
#if defined TARGET_placerptB1 || defined TARGET_placerptB2 || defined TARGET_placerptB3 || defined TARGET_placerptB4 || defined TARGET_placerptB5
# define TITRE Placer un point sur une demi-droite graduée
#endif
#if defined TARGET_plcoord1 || defined TARGET_plcoord2 || defined TARGET_plcoord3 || defined TARGET_plcoord4 || defined TARGET_plcoord5
# define TITRE Placer un point dans un repère
#endif
#if defined TARGET_vocabulaire1 || defined TARGET_vocabulaire2 || defined TARGET_vocabulaire3 || defined TARGET_vocabulaire4 || defined TARGET_vocabulaire5
# define TITRE Vocabulaire
#endif
