#include "lang_title_fr.inc"

#if defined TARGET_vocabulaire1 || defined TARGET_plcoord1 || defined TARGET_placerptB1 || defined TARGET_placerpt1 || defined TARGET_comparer1 || defined TARGET_distance01 || defined TARGET_distance1 || defined TARGET_lectcoord1 || defined TARGET_lectcoord1 ||  defined TARGET_phrase1 || defined TARGET_lecturegraph1 || defined TARGET_oppose1
# define NUM 1
#endif
#if defined TARGET_vocabulaire2 || defined TARGET_plcoord2 || defined TARGET_placerptB2 || defined TARGET_placerpt2 || defined TARGET_comparer2 || defined TARGET_distance02 || defined TARGET_distance2 || defined TARGET_lectcoord2 || defined TARGET_lectcoord2 ||  defined TARGET_phrase2 || defined TARGET_lecturegraph2 || defined TARGET_oppose2
# define NUM 2
#endif
#if defined TARGET_vocabulaire3 || defined TARGET_plcoord3 || defined TARGET_placerptB3 || defined TARGET_placerpt3 || defined TARGET_comparer3 || defined TARGET_distance03 || defined TARGET_distance3 || defined TARGET_lectcoord3 || defined TARGET_lectcoord3 ||  defined TARGET_phrase3 || defined TARGET_lecturegraph3 || defined TARGET_oppose3
# define NUM 3
#endif
#if defined TARGET_vocabulaire4 || defined TARGET_plcoord4 || defined TARGET_placerptB4 || defined TARGET_placerpt4 || defined TARGET_comparer4 || defined TARGET_distance04 || defined TARGET_distance4 || defined TARGET_lectcoord4 || defined TARGET_lectcoord4 ||  defined TARGET_phrase4 || defined TARGET_lecturegraph4 || defined TARGET_oppose4
# define NUM 4
#endif
#if defined TARGET_vocabulaire5 || defined TARGET_plcoord5 || defined TARGET_placerptB5 || defined TARGET_placerpt5 || defined TARGET_comparer5 || defined TARGET_distance05 || defined TARGET_distance5 || defined TARGET_lectcoord5 || defined TARGET_lectcoord5 ||  defined TARGET_phrase5 || defined TARGET_lecturegraph5 || defined TARGET_oppose5
# define NUM 5
#endif
#if defined TARGET_calculA1
# define NUM A1
#endif
#if defined TARGET_calculA2
# define NUM A2
#endif
#if defined TARGET_calculA3
# define NUM A3
#endif
#if defined TARGET_calculA4
# define NUM A4
#endif
#if defined TARGET_calculA5
# define NUM A5
#endif
#if defined TARGET_calculB1 || defined TARGET_lecturegraphB1
# define NUM B1
#endif
#if defined TARGET_calculB2 || defined TARGET_lecturegraphB2
# define NUM B2
#endif
#if defined TARGET_calculB3 || defined TARGET_lecturegraphB3
# define NUM B3
#endif
#if defined TARGET_calculB4 || defined TARGET_lecturegraphB4
# define NUM B4
#endif
#if defined TARGET_calculB5 || defined TARGET_lecturegraphB5
# define NUM B5
#endif
#if defined TARGET_calculC1
# define NUM C1
#endif
#if defined TARGET_calculC2
# define NUM C2
#endif
#if defined TARGET_calculC3
# define NUM C3
#endif
#if defined TARGET_calculC4
# define NUM C4
#endif
#if defined TARGET_calculC5
# define NUM C5
#endif
\title{TITRE NUM}
