Als je bij een som het antwoord niet weet ,vul dan in:<br />
<em>? een vraagteken</em>
<br />
    <ol>
	<li> 
	    Vermenigvuldigen een * <br />
	    Dus noteer 5*<em>x</em> <br />
	    <small>natuurlijk reken ik 5<em>x</em> ook wel goed, maar het is beter je het * -symbool aan te leren<small>
	</li>
	<li> 
	    Gebruik voor vermenigvuldigen <b>nooit</b> een &times; symbool : de computer leest dit als een variabele (de letter <em>x</em>)
	</li>
	<li>
	    Gebruik de <b>/</b> voor delen <br />
	    Dus noteer 5/<em>x</em>
	</li>
	<li> 
	    Noteer <em>x</em>^5 voor <em>x</em><sup><small>5</small></sup>
	    <font size="-1">Ook mag je <em>x</em>**5 voor <em>x</em><sup><small>5</small></sup> gebruiken</small>
	</li>
	<li> 
	    Je mag <b>altijd</b> iets met haakjes schrijven ,als je vindt dat het daardoor duidelijker wordt<br />
	    (behalve als de opdracht luidt: <em>schrijf zonder haakjes</em>...)<br />
	    dus (5/x) + 1  <br />
	    of voor mijn part (5)/(x) + (1)
	</li>
    </ol>
<br />
