如果你不能回答这个问题, 只要填入:<br />
<em> 一个问号 <b>?</b>
<br />

基本语法规则:
<ol>
    <li> 
	用星号 * 表示乘法 <br />
	因此写成:  5*<em>x</em> <br />
	<small>当然在 WIMS 里: 5<em>x</em> 也可以,<br /> 不过你应该学会使用 * 号 !</small>
    </li>
    <li> 
	<b>决不</b> 使用 &times; 号表示乘法
    </li>
    <li> 
	使用  / 表示除法 <br />
	因此写成 5/<em>x</em>
    </li>
    <li>
	用 <em>x</em>^5 表示 <em>x</em><sup><small>5</small></sup>
	<font size="-1">你也可以使用 <em>x</em>**5 表示 <em>x</em><sup><small>5</small></sup></small>
    </li>
    <li> 
	你<b>总是</b>可以使用括号 () 使得公式更加明确<br />
	(除非练习有特殊要求: <em>不使用括号</em>...)<br />
	例如 (5/x) + 1  <br />
	或 5/(x) + 1<br />
	或 (5+x)/x
    </li>
</ol>
<br />

