Si vous ne savez pas répondre à une question, mettez simplement<br />
<em> un point d'intersection <b>?</b> .
<br />

Règles de syntaxe de base:
<ol>
    <li> 
	Pour la multiplication, on utilise un signe * <br />
	Par exemple, écrivez:  5*<em>x</em> <br />
	<small>Das WIMS : 5<em>x</em> est correct aussi,<br />mais vous devez apprendre à utiliser le signe * !</small>
    </li>
    <li> 
	N'utilisez <b>jamais</b> un signe &times; pour la multiplication.
    </li>
    <li> 
	Utilisez  / pour la division <br />
	Ainsi écrivez 5/<em>x</em>
    </li>
    <li> 
	Ecrivez <em>x</em>^5 pour <em>x</em><sup><small>5</small></sup>
	<font size="-1">Vous pouvez aussi utiliser <em>x</em>**5 pour <em>x</em><sup><small>5</small></sup>.
    </li>
    <li> 
	Vous pouvez <b>toujours</b> utiliser des parenthèses () pour rendre les choses plus claires,<br />
	(sauf s'il est dit : <em>écrivez sans parenthèses</em>...).<br />
	par exemple (5/x) + 1  <br />
	ou 5/(x) + 1<br />
	ou (5+x)/x
    </li>
</ol>
<br />
