If you're not capable of answering a question , just fill in:<br />
<em> a questionmark <b>?</b>
<br />
Basic syntax rules:
<ol>
    <li> 
	Multiplication use a asterix symbol * <br />
	So write:  5*<em>x</em> <br />
        <small>of course in WIMS : 5<em>x</em> is good as well,<br /> but you should learn to use the * sign !</small>
    </li>
    <li> 
	<b>Never</b> use a &times; sign for Multiplication
    </li>
    <li> 
	Use  / for division <br />
	So write 5/<em>x</em>
    </li>
    <li> 
	Write <em>x</em>^5 for <em>x</em><sup><small>5</small></sup>
	<font size="-1">You may use also <em>x</em>**5 for <em>x</em><sup><small>5</small></sup></small>
    </li>
    <li> 
	You may <b>always</b> use parenthesis () to make things more clear<br />
	(except when it says: <em>write without parenthesis</em>...)<br />
	for instance (5/x) + 1  <br />
	or 5/(x) + 1<br />
	or (5+x)/x
    </li>
</ol>
<br />
