#if defined TARGET_System2x2
\text{name_enonce=Los het onderstaande systeem van vergelijkingen op voor, en}
#endif
#if defined TARGET_resto
\text{name_enonce=mensen gaan naar een restaurant voor een diner.}
\text{name_enonce2=Het menu kost, &euro; voor een kind, en,
  &euro; voor een volwassene. De totale rekening voor een maaltijd is ,&euro;}
\text{name_question=Totaal zaten aan het diner , personen,
 hoeveel kinderen en hoeveel volwassenen zaten aan tafel}
\text{name_answer=Kinderen,Volwassenen}
\text{name_solution=Neem \(x\) als het aantal kinderen,
  en \(y\) als het aantal volwassenen the number.
  We hebben nu het volgende systeem.,
  En de oplossing van dit systeem is}
#endif
#if defined TARGET_rectangle
\text{name_enonce=We hebben een rechthoek met een omtrek van,
  mm. Gegeven :  de lengte is ,
  mm langer dan de breedte, bereken nu de lengte en de breedte (in mm).}
\text{name_answer=Lengte,Breedte}
\text{name_solution=Neem \(x\) voor de lengte, \(y\) voor de breedte. Dan
  hebben we het volgende.}
\text{name_solution2=En de oplossing van dit systeem is}
#endif
