#if defined TARGET_System2x2
\text{name_enonce=Solve the following system of equations for, and}
#endif
#if defined TARGET_resto
\text{name_enonce=persons go to restaurant for dinner.}
\text{name_enonce2=The menu costs, dollars for each child, and,
  dollars for each adult. The total cost for the dinner goes to,dollars}
\text{name_question=Among these, persons,
  how many children and how many adults are there}
\text{name_answer=Children,Adults}
\text{name_solution=Let \(x\) be the number of children,
  and \(y\) the number of adults.
  We have the following system.,
  And the solution of this system is}
#endif
#if defined TARGET_rectangle
\text{name_enonce=We have a rectangle whose perimeter is,
  mm. Given that the length is ,
  mm longer than the width, find out the length and the width (in mm).}
\text{name_answer=Length,Width}
\text{name_solution=Let \(x\)  the length, \(y\) the width. Then
  we have the following system.}
\text{name_solution2=And the solution of this system is}
#endif
