#if defined TARGET_System2x2
\text{name_enonce=Résoudre le système d'équations suivant en, et}
#endif
#if defined TARGET_resto
\text{name_enonce=personnes dînent au restaurant.}
\text{name_enonce2=Le menu coûte,euros pour chaque enfant, et,
  euros pour chaque adulte. Le coût total du dîner se monte à,euros}
\text{name_question=Parmi ces, personnes,
  combien d'enfants et combien d'adultes y a-t-il&nbsp;}
\text{name_answer=Enfants,Adultes}
\text{name_solution=Soit \(x\) le nombre d'enfants,
  et \(y\) le nombre d'adultes.,
  Nous avons le système suivant.,
  La solution du système est}
#endif
#if defined TARGET_rectangle
\text{name_enonce=Un rectangle a un périmètre de ,
  mm. Sachant que sa longueur fait,
  mm de plus que sa largeur, trouver sa longueur et sa largeur (en mm).
}
\text{name_answer=Longeur, Largeur}
\text{name_solution=Soit \(x\) la longueur et \(y\) la largeur. Alors
  nous avons le système suivant.}
\text{name_solution2=La solution de ce système est}
#endif
