\language{fr}
#if defined TARGET_majbase || defined TARGET_divisiontrou || defined TARGET_division || defined TARGET_mental10 || defined TARGET_tablemult || defined TARGET_geonum1D || defined TARGET_mental || defined TARGET_mult || defined TARGET_addition || defined TARGET_numgeo1D || defined TARGET_borne || defined TARGET_livre || defined TARGET_numgeo2D || defined TARGET_geonum2D || defined TARGET_multiplication || defined TARGET_immatriculation || defined TARGET_nbit3 || defined TARGET_changbin || defined TARGET_musique
\email{bpr@math.u-psud.fr}
\author{Bernadette, Perrin-Riou}
#endif
#if defined TARGET_add
\author{Frédéric, Pitoun}
\email{lva.pitoun@free.fr}
#endif
#if defined TARGET_entierbase
\author{Sophie, Lemaire}
\email{sophie.lemaire@math.u-psud.fr}
#endif
#if defined TARGET_guess
\author{Marie-Claude, David;Bernadette,Perrin-Riou}
\email{mcld@math.u-psud.fr,bpr@math.u-psud.fr}
#endif
#if defined TARGET_divisiontrou
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_division
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_mental10
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_tablemult
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_add
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{10000}
#endif
#if defined TARGET_geonum1D
\precision{10000000}
#endif
#if defined TARGET_mental
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_mult
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_addition
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_entierbase
\computeanswer{yes}
#endif
#if defined TARGET_livre
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_geonum2D
\precision{10000000}
#endif
#if defined TARGET_multiplication
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_immatriculation
\precision{100000}
#endif
#if defined TARGET_nbit3
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
#if defined TARGET_changbin
\range{-5..5}
\computeanswer{no}
\format{html}
\precision{1000}
#endif
