#if defined TARGET_majbase
#define TITLE Bases et ordre de grandeur
#define TITLE_it Basi e ordine di grandezza
#endif
#if defined TARGET_divisiontrou
#define TITLE Division à trous
#define TITLE_it Divisione con elemento mancante
#endif
#if defined TARGET_division
#define TITLE Division dans une base
#define TITLE_it Divisione in base b
#endif
#if defined TARGET_mental10
#define TITLE Calcul mental en base décimale
#define TITLE_it Calcolo mentale in base decimale
#endif
#if defined TARGET_tablemult
#define TITLE Tables : trouver la base
#define TITLE_it Tavole: trova la base
#endif
#if defined TARGET_add
#define TITLE Addition en base b
#define TITLE_it Addizione in base b
#endif
#if defined TARGET_geonum1D
#define TITLE Coordonnée sur un axe en binaire
#define TITLE_it Coordinate sulla retta in base 2
#endif
#if defined TARGET_mental
#define TITLE Calcul mental en base quelconque
#define TITLE_it Calcolo mentale in base qualunque
#endif
#if defined TARGET_mult
#define TITLE Multiplication : dans quelle base ?
#define TITLE_it Moltiplicazione: in quale base?
#endif
#if defined TARGET_addition
#define TITLE Tables d'addition
#define TITLE_it Tavole di addizione
#endif
#if defined TARGET_entierbase
#define TITLE Ecriture d'entiers dans une base
#define TITLE_it Scrittura degli interi in base b
#endif
#if defined TARGET_numgeo1D
#define TITLE Point sur un axe en numération binaire
#define TITLE_it Punti sulla retta in base 2
#endif
#if defined TARGET_guess
#define TITLE Devinez le nombre
#define TITLE_it Indovina il numero
#endif
#if defined TARGET_borne
#define TITLE Plus grand/petit nombre dans une base
#define TITLE_it Numero più grande/piccolo in una base
#endif
#if defined TARGET_livre
#define TITLE Pagination d'un livre
#define TITLE_it Impaginazione di un libro
#endif
#if defined TARGET_numgeo2D
#define TITLE Point dans le plan en numération binaire
#define TITLE_it Punti nel piano in base 2
#endif
#if defined TARGET_geonum2D
#define TITLE Coordonnées dans le plan en binaire
#define TITLE_it Coordinate nel piano in base 2
#endif
#if defined TARGET_multiplication
#define TITLE Tables de multiplication
#define TITLE_it Tavole di moltiplicazione
#endif
#if defined TARGET_immatriculation
#define TITLE Immatriculation de voitures
#define TITLE_it Targhe automobilistiche
#endif
#if defined TARGET_nbit3
#define TITLE Nombre de chiffres et base
#define TITLE_it Numero di cifre e base
#endif
#if defined TARGET_changbin
#define TITLE Numération en base b^k
#define TITLE_it Numerazione in base b^k
#endif
#if defined TARGET_musique
#define TITLE Notation musicale
#define TITLE_it Notazione musicale
#endif
