!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices
de classe Terminale,
sur les calculs
algébriques avec des logarithmes et des exponentielles.

Contenu actuel;
<ul>
<li> Pratique de la notation puissance pour les exponentielles de base quelconque.</li>
<li> Réécriture d'expressions numériques ou littérales avec ln ou exp. </li>
<li> Résolution d'inéquations simples avec exponentielles /ou logarithmes
  (avec résolution détaillée fournie en fin d'exercice).</li>
<li> Etude de signe d'expression  du type c*exp(ax+b) + d ou c*ln(ax+b) + d.</li>
<li> Application des logarithmes aux suites géométriques.</li>
</ul>

!read oef/$module_language/intromenu.phtml
!tail
