#if defined TARGET_CDRom
# define TITRE_en CD Rom
#endif
#if defined TARGET_Tourdumonde
# define TITRE_en Tour du monde
#endif
#if defined TARGET_Tempsdeparcour
# define TITRE_en Temps de parcours
#endif
#if defined TARGET_Solde
# define TITRE_en Solde
#endif
#if defined TARGET_Pyramide
# define TITRE_en Pyramid
#endif
#if defined TARGET_chelle
# define TITRE_en Échelle I
#endif
#if defined TARGET_EchelleII
# define TITRE_en Échelle II
#endif
#if defined TARGET_echellereelle1
# define TITRE_en Echelle réelle
#endif
#if defined TARGET_Courses
# define TITRE_en Courses
#endif
#if defined TARGET_Densit
# define TITRE_en Density I
#endif
#if defined TARGET_DensitII
# define TITRE_en Density II
#endif
#if defined TARGET_DensitII2
# define TITRE_en Density III
#endif
#if defined TARGET_Molire
# define TITRE_en Molière
#endif
#if defined TARGET_Poids
# define TITRE_en Weights
#endif
#if defined TARGET_Pourcentages
# define TITRE_en Percentages
#endif
#if defined TARGET_vitesse1
# define TITRE_en Speed
#endif
#if defined TARGET_Tapis
# define TITRE_en Tapis
#endif
#if defined TARGET_Essence
# define TITRE_en Essence
#endif
