#if defined TARGET_CDRom
# define TITRE CD Rom
#endif
#if defined TARGET_Tourdumonde
# define TITRE Tour du monde
#endif
#if defined TARGET_Tempsdeparcour
# define TITRE Temps de parcours
#endif
#if defined TARGET_Solde
# define TITRE Solde
#endif
#if defined TARGET_Pyramide
# define TITRE Pyramide
#endif
#if defined TARGET_chelle
# define TITRE Échelle I
#endif
#if defined TARGET_EchelleII
# define TITRE Échelle II
#endif
#if defined TARGET_distance1
# define TITRE Distance
#endif
#if defined TARGET_echelle1
# define TITRE Échelle III
#endif
#if defined TARGET_echellereelle1
# define TITRE Échelle réelle
#endif
#if defined TARGET_echelcarte1
# define TITRE Échelle carte
#endif
#if defined TARGET_duree1
# define TITRE Durée
#endif
#if defined TARGET_Courses
# define TITRE Courses
#endif
#if defined TARGET_Densit
# define TITRE Densité I
#endif
#if defined TARGET_DensitII
# define TITRE Densité II
#endif
#if defined TARGET_DensitII2
# define TITRE Densité III
#endif
#if defined TARGET_Molire
# define TITRE Molière
#endif
#if defined TARGET_Poids
# define TITRE Poids
#endif
#if defined TARGET_Pourcentages
# define TITRE Pourcentages
#endif
#if defined TARGET_vitesse1
# define TITRE Vitesse
#endif
#if defined TARGET_Tapis
# define TITRE Tapis
#endif
#if defined TARGET_Essence
# define TITRE Essence
#endif
