#if defined TARGET_CDRom
# define TITRE_nl CD Rom
#endif
#if defined TARGET_Tourdumonde
# define TITRE_nl De wereld rond
#endif
#if defined TARGET_Tempsdeparcour
# define TITRE_nl Tijd
#endif
#if defined TARGET_Solde
# define TITRE_nl Uitverkoop
#endif
#if defined TARGET_Pyramide
# define TITRE_nl Pyramide
#endif
#if defined TARGET_chelle
# define TITRE_nl Schaal I
#endif
#if defined TARGET_EchelleII
# define TITRE_nl Schaal II
#endif
#if defined TARGET_distance1
# define TITRE_nl Distance
#endif
#if defined TARGET_echelle1
# define TITRE_nl Schaal III
#endif
#if defined TARGET_echellereelle1
# define TITRE_nl Echelle réelle
#endif
#if defined TARGET_echelcarte1
# define TITRE_nl Echelle carte
#endif
#if defined TARGET_duree1
# define TITRE_nl Durée
#endif
#if defined TARGET_Courses
# define TITRE_nl Boodschappen
#endif
#if defined TARGET_Densit
# define TITRE_nl Dichtheid
#endif
#if defined TARGET_DensitII
# define TITRE_nl Dichtheid II
#endif
#if defined TARGET_DensitII2
# define TITRE_nl Dichtheid III
#endif
#if defined TARGET_EchelleII
# define TITRE_nl Schaal II
#endif
#if defined TARGET_Essence
# define TITRE_nl Benzine
#endif
#if defined TARGET_Molire
# define TITRE_nl Molière
#endif
#if defined TARGET_Multatuli
# define TITRE_nl Multatuli
#endif
#if defined TARGET_Poids
# define TITRE_nl Gewicht
#endif
#if defined TARGET_Pourcentages
# define TITRE_nl Percentages
#endif
#if defined TARGET_Pyramide
# define TITRE_nl Pyramide
#endif
#if defined TARGET_Solde
# define TITRE_nl Solde
#endif
#if defined TARGET_Tapis
# define TITRE_nl Tapijt
#endif
#if defined TARGET_Tempsdeparcour
# define TITRE_nl Temps de parcours.
#endif

