#if defined TARGET_CDRom
\text{name_statement=Ik heb een cdrom-lezer gekocht. Voor de lezer plus,
  cdroms die ieder,euro kosten heb ik , euro betaald.}
\text{name_question=Wat is de prijs van de cdrom-lezer}
\text{name_answer=Prijs (in euros)}
#endif
#if defined TARGET_Tourdumonde
\text{name_statement1=De omtrek van de aarde is ongeveer 40000 40 000 \(\textrm{km}\).
  Om een reis rond de wereldbol met de auto, te simuleren rijdt een piloot
  op een circuit van}
\text{name_statement2=met een gemiddelde snelheid van, (inclusief pauzes en
  onderhoud).}
\text{name_question=Hoe land doet hij er over in uren}
\text{name_answer=Uren}
#endif
#if defined TARGET_Tempsdeparcour
\matrix{name_statement=Ik heb met de auto
  afgelegd met een gemiddelde snelheid van}
\text{name_question=Hoeveel minuten heb ik gereden}
\text{name_answer=Tijd in}
#endif
#if defined TARGET_Solde
\matrix{name_statement=Met,korting
  bespaar ik, euros op een paar laarsjes}
\text{name_question=Wat was de prijs voor de uitverkoop}
\text{name_answer=Prijs (in euros)}
#endif
#if defined TARGET_Pyramide
\text{name_statement=Een pyramide heeft een vierkante voet van,
  Zijn hoogte is ,
  Als je een houten model wilt maken op schaal}
\text{name_question=wat is dan de lengte van de zijkant van de voet (in \(\textrm{cm}\))}
\text{name_answer=Zijkant van de voet in \(\textrm{cm}\)}
#endif
#if defined TARGET_chelle
\text{name_statement=Een plattegrond is op schaal}
\text{name_question=Wat is de werkelijke afstand (in \(\textrm{km}\)) die, op de kaart voorstelt}
\text{name_answer=Werkelijke afstand (in \(\textrm{km}\))}
#endif
#if defined TARGET_Courses
\matrix{name_statement=Mijn moeder stuurt mij naar de supermarkt om
  te kopen. Ik neem, flessen.
  Bij de kassa hoor ik dat ik,tekort kom.
  Ik zet een fles terug en ga terug naar de kassa. Ik krijg vervolgens}
\text{name_product=sinaasappelsap, appelsap, Coca cola, druivensap}
\matrix{name_question=Wat is de prijs van een fles
  Hoeveel geld had ik bij mij}
\text{name_instruction=Les réponses seront données en}
\text{name_euro=euros}
\text{name_answer1=Prijs van een fles}
\text{name_answer2=Mijn geld}
#endif
#if defined TARGET_Densit
\matrix{name_statement=De bevolkingsdichtheid van een land is ,bewoners
  Er wonen,miljoen mensen }
\text{name_question=Wat is haar oppervlak (in duizenden  \(\textrm{km}^2\))&nbsp;}
\text{name_answer=oppervlak (in duizenden  \(\textrm{km}^2\))}
#endif
#if defined TARGET_DensitII
\text{name_statement=Het oppervlak van een land is,
  en haar aantal bewoners is}
\text{name_question=Wat is de bevolkingsdichtheid (in duizenden per km<sup>2</sup>)}
\text{name_answer=Dichtheid (\(hab{/}\textrm{km}^2\))}
#endif
#if defined TARGET_DensitII2
\text{name_statement=La superficie d'un pays est de,
  et sa densité est de,habitants}
\text{name_question=Quelle est sa population (en millions)&nbsp;}
\text{name_answer=Population (en millions)}
#endif
#if defined TARGET_Molire
\text{name_statement=Le professeur de français a acheté,exemplaires de l'Avare.,
  Le libraire lui a fait une remise de, par livre. Il a payé}
\text{name_question=Quel est le prix d'un livre sans la remise}
\text{name_answer=Prix en}
#endif
#if defined TARGET_Poids
\text{name_statement=Een vrachtwagen is,keer zwaarder dan een auto terwijl de
  vrachtwagen, eer lichter is dan een tank. ,
  Wetend dat de vrachtwagen, ton weegt, bereken het gewicht van een auto
  en van een tank (in tonnen).}
\text{name_answer1=Gewicht van een auto}
\text{name_answer2=Gewicht van een tank}
#endif
#if defined TARGET_Pourcentages
\matrix{name_statement=Van de,leerlingen in de onderbouw doen er
  Duits.
doen er Spaans}
\text{name_question1=Hoeveel zijn dat er}
\text{name_question2=Hoeveel percent zijn dat er}
\text{name_answer1=Aantal leerlingen}
\text{name_answer2=Perrcentage}
#endif
#if defined TARGET_Tapis
\text{name_incdec=monte,baisse}
\matrix{name_statement=De prijs van een tapijt was ,euros ein november
  met een,van, in decembe
  en een,van, in januari}
\text{name_question=Wat is de nieuwe prijs}
\text{name_answer=De nieuw prijs is}
\text{name_rep= minder dan, meer dan,dezelfde}
\text{name_euro=euros}
#endif
#if defined TARGET_DensitII2
\text{name_statement=La superficie d'un pays est de,
  et sa densité est de,habitants}
\text{name_question=Quelle est sa population (en millions)&nbsp;}
\text{name_answer=Population (en millions)}
#endif
#if defined TARGET_Essence
\text{name_statement=Een auto verbruikt , liter benzine per 100,
  Zijn tank kan ,liter bevatten}
\text{name_question=hoe ver kan hij daarop rijden}
\text{name_answer=Afstand (in \(\textrm{km}\))}
#endif
#if defined TARGET_EchelleII
\text{name_statement=Een plattegrond is op schaal}
\text{name_question=Wat is de afstand op de kaart (in cm) bij een werkelijke afstand van}
\text{name_answer=Afstand op de kaart (in \(\textrm{cm}\))}
#endif
#if defined TARGET_echelcarte1
\text{name_enonce=Nous avons un plan à l'échelle ,La longueur réelle est de}
\text{name_question2=L'échelle du plan est}
#endif
#if defined TARGET_echelle1
\matrix{name_enonce=Sur un plan, une longueur de
  est représentée par une longueur de
  sur la carte}
\text{name_question2=La longueur sur la carte sera de}
#endif
#if defined TARGET_duree1 || defined TARGET_vitesse1 || defined TARGET_distance1 || defined TARGET_echelle1 || defined TARGET_echelcarte1 || defined TARGET_duree1 || defined TARGET_echellereelle1
\matrix{name_question=Remplir le tableau de proportionalité
  l'une des cases doit contenir le résultat final}
#endif
#if defined TARGET_echelle1 || defined TARGET_echelcarte1
\text{name_head=Longueurs sur la carte en ,
  Longueurs réelles en}
#endif
#if defined TARGET_duree1
\text{name_enonce=Une voiture roule à une vitesse moyenne de,
  Elle a parcouru une distance de}
\text{name_head=Durée en min,Distance en}
\text{name_question2=La durée du parcours est de}
\text{name_question3=Si je convertis en heures et minutes}
#endif
#if defined TARGET_vitesse1
\text{name_enonce=Une voiture a parcouru une distance de,en}
\text{name_header=Durée en,Distance en}
\text{name_question2=La vitesse moyenne est de}
#endif
#if defined TARGET_echellereelle1
\text{name_enonce=Nous avons un plan à l'échelle,
  Nous avons mesuré sur ce plan une longueur de}
\text{name_question2=La longueur réelle correspondante est de}
#endif
#if defined TARGET_distance1
\text{name_enonce=Une voiture roule à une vitesse moyenne de,
  Le voyage a duré }
\text{name_head=Durée en min,Distance en km}
\text{name_question2=La distance parcourue est de}
#endif
