#if defined TARGET_CDRom
# define TITRE_es CD Rom
#endif
#if defined TARGET_Courses
# define TITRE_es Compras
#endif
#if defined TARGET_Densit
# define TITRE_es Densidad
#endif
#if defined TARGET_DensitII
# define TITRE_es Densidad II
#endif
#if defined TARGET_DensitII2
# define TITRE_es Densidad III
#endif
#if defined TARGET_Echelle
# define TITRE_es Escala
#endif
#if defined TARGET_EchelleII
# define TITRE_es Escala II
#endif
#if defined TARGET_Essence
# define TITRE_es Gasolina
#endif
#if defined TARGET_Moliere
# define TITRE_es Molière
#endif
#if defined TARGET_Poids
# define TITRE_es Pesos
#endif
#if defined TARGET_Pourcentages
# define TITRE_es Porcentajes
#endif
#if defined TARGET_Pyramide
# define TITRE_es Pirámide
#endif
#if defined TARGET_Solde
# define TITRE_es Rebajas
#endif
#if defined TARGET_Tapis
# define TITRE_es Alfombra
#endif
#if defined TARGET_Tempsdeparcour
# define TITRE_es Tiempo de recorrido
#endif
#if defined TARGET_Tourdumonde
# define TITRE_es Vuelta al mundo
#endif
#if defined TARGET_chelle
# define TITRE_es Escala
#endif
#if defined TARGET_distance1
# define TITRE_es Distance
#endif
#if defined TARGET_duree1
# define TITRE_es Duración1
#endif
#if defined TARGET_echelcarte1
# define TITRE_es Escalamapa1
#endif
#if defined TARGET_echelle1
# define TITRE_es Escala1
#endif
#if defined TARGET_echellereelle1
# define TITRE_es Escalareal1
#endif
#if defined TARGET_vitesse1
# define TITRE_es Velocidad1
#endif
