#if defined EQCONST
\text{name_statement=Maak twee gelijkwaardige breuken van de onderstaande getallen.}
\text{name_numerator=Teller}
\text{name_denominator=Noemer}
#endif
#if defined MISSING
\text{name_denominator=noemer in}
\text{name_numerator=teller in}
\text{name_statement=Vul de,zodat de uitdrukking correct is:}
\text{name_the=The}
#endif
#if defined FRACEQ
/* note for translators: keep commas */
\text{name_statement=Uit de onderstaande breuken ,zoek ,die gelijkwaardig zijn.}
\text{name_eqfract=De gelijke breuken:}
\text{name_first=Eerste paar:}
\text{name_second=Tweede paar:}
\text{name_third=Derde paar:}
\text{name_fraction=Breuken}
\text{name_list_items=twee, twee paar, drie paar}
#endif
#if defined CORRESP
\text{name_statement1=Slepen: tussen }
#ifdef INVERSE
\text{name_statement2=de breuken met hun inversen.}
#else
\text{name_statement2=gelijke breuken.}
#endif
\text{name_correspondance=De overeenkomstigheid}
#endif
#if defined TARGET_guidadd
/* nominater = teller ; denominator=noemer */
\text{name_list_objects=alleen de teller, alleen de noemer,
de teller en de noemer}
\text{name_gtext1=random(Herschrijf de twee breuken zodat ze een gelijke noemer hebben,
Geef de twee breuken dezelfde noemer)}
\text{name_list_method1=\name_gtext1,
    Herschrijf de twee breuken en geef ze een gelijke noemer,
    Eerst de tellers,
    Eerst de noemers,
    De tellers optellen en de noemers vermenigvuldigen,
    Vermenigvuldig de tellers
}
\text{name_list_method2=De tellers optellen en neem de gemeenschappelijke noemer,
Apart optellen van de noemers en de tellers
}
\text{name_and=en}
\text{name_statement1=Bereken de volgende optelling.}
\text{name_statement2=Kies de start methode:}
\text{name_statement3=Stap 1. Geef de breuken dezelfde noemer.}
/* note for translators: keep commas */
\text{name_statement4=Vermenigvuldien,van,met,we krijgen}
\text{name_statement5=Stap 1. We hebben,en daarom wordt de som}
\text{name_statement6=What is de volgende stap?}
\text{name_statement7=Stap 2. We gaan de tellers optellen en houden de gemeenschappelijke noemers,
en daarom is de som }
\text{name_answer1=Methode }
\text{name_answer2=Te vermenigvuldigen}
\text{name_answer3=Vermenigvuldigingsfactor}
\text{name_answer4=Nieuwe teller}
\text{name_answer5=Nieuwe noemer}
\text{name_answer6=Teller van de som}
\text{name_answer7=Noemer van de som}
\text{name_condition1=De vermenigvuldigin is correct}
\text{name_condition2=De optelling is goed}
\text{name_feedback1=De twee breuken hebben verschillende noemers,Deze kun je nooit direct optellen ; altijd eerst herschrijven zodat ze een geljke noemer hebben.}
\text{name_feedback2=Om de breuken niet in getalswaarde mogen veranderen moeten
we eerste de teller en noemer met een zelfde getal vermenigvuldigen.}
\text{name_feedback3=Je kan natuurlijk niet de teller en noemer  vermenigvuldien met 0 !
 <p>
 Je krijgt dan een ``breuk'' \(0/(0)\), en die bestaat niet.
 </p>}
\text{name_feedback4=Nee, deze oefening staat niet toe dat je vermenigvuldigd met een negatief getal...}
\text{name_feedback5=Je moet de teller en de noemer vermenigvuldigen met een geheel getal.}
\text{name_feedback6=Het doel is dat je de breuken een gelijke noemer geeft.
Jouw vermenigvuldiging zorgt ervoor dat de breuken verschillende noemers krijgen.
Foutieve vermenigvuldiging.
}
\text{name_feedback7=Rekenfout in de vermenigvuldiging.}
\text{name_feedback8=OP twee breuken met dezelfde noemer op te teller, hoef je allen de tellers maar op te teller.}
#endif
