#if defined EQCONST
\text{name_statement=Costruisci due frazioni equivalenti a partire dai numeri indicati sotto.}
\text{name_numerator=Numeratore}
\text{name_denominator=Denominatore}
#endif
#if defined MISSING
\text{name_denominator=denominatore}
\text{name_numerator=numeratore}
\text{name_statement=Inserisci il,mancante in modo da completare l'eguaglianza qui sotto:}
\text{name_the=Il}
#endif
#if defined FRACEQ
/* note for translators: keep commas */
\text{name_statement=Tra le frazioni elencate sotto, individuarne,
che siano equivalenti.}
\text{name_eqfract=Le frazioni equivalenti:}
\text{name_first=Prima coppia:}
\text{name_second=Seconda coppia:}
\text{name_third=Terza coppia:}
\text{name_fraction=Frazione}
\text{name_list_items=due, due coppie, tre coppie}
#endif
#if defined CORRESP
\text{name_statement1=Mettere in corrispondenza}
#ifdef INVERSE
\text{name_statement2=ciascuna frazione con la sua inversa.}
#else
\text{name_statement2=le frazioni equivalenti.}
#endif
\text{name_correspondance=La corrispondenza}
#endif
#if defined TARGET_guidadd
\text{name_list_objects=solo il numeratore, solo il denominatore,
il numeratore e il denominatore}
\text{name_gtext1=random(Riscrivi le frazioni in modo da ottenere lo stesso denominatore,
    Trasforma le frazioni in modo che abbiano lo stesso denominatore)}
\text{name_list_method1=\name_gtext1,
    Riscrivi le frazioni in modo da ottenere lo stesso numeratore,
    Comincia con il sommare i numeratori,
    Comincia con il sommare i denominatori,
    Somma i numeratori e moltiplica i denominatori,
    Moltiplica i numeratori
}
\text{name_list_method2=Somma i numeratori e mantieni il denominatore comune,
 Somma i numeratori e i denominatori rispettivamente
}
\text{name_and=e}
\text{name_statement1=Seleziona il primo passaggio:}
\text{name_statement2=Choose the starting method:}
\text{name_statement3=Passaggio 1. Porta le frazioni allo stesso denominatore.}
/* note for translators: keep commas */
\text{name_statement4=Moltiplicando,di,per,si ottiene}
\text{name_statement5=Passaggio 1. Abbiamo,quindi la somma diventa}
\text{name_statement6=Qual è il passaggio successivo?}
\text{name_statement7=Passaggio 2. Sommiamo i numeratori e manteniamo il
 denominatore comune, la somma risulta quindi}
\text{name_answer1=Metodo passaggio}
\text{name_answer2=Oggetti da moltiplicare}
\text{name_answer3=Fattore}
\text{name_answer4=Nuovo numeratore}
\text{name_answer5=Nuovo denominatore}
\text{name_answer6=Numeratore della somma}
\text{name_answer7=Denominatore della somma}
\text{name_condition1=Le moltiplicazioni sono corrette}
\text{name_condition2=La somma è corretta}
\text{name_feedback1=Le due frazioni hanno denominatori diversi. Non è
 possibile effettuare la somma in questa forma; occorre prima riscriverle
 in modo che abbiano lo stesso denominatore.}
\text{name_feedback2=Per mantenere invariato il valore della frazione occore
 moltiplicarne il numeratore e il denominatore per uno stesso numero.}
\text{name_feedback3=Non ha senso moltiplicare il numeratore e il
 denominatore di una frazione per 0!
 <p>
 Si otterrebbe la ``frazione'' \(0/(0)\), che non ha alcun significato.
 </p>}
\text{name_feedback4=Spiacente, ma in questo esercizio devi evitare di
 utilizzare i numeri negativi.}
\text{name_feedback5=Dovresti moltiplicare numeratore e denominatore di una
 frazione solo per un numero intero.}
\text{name_feedback6= Lo scopo era di portare le frazioni allo stesso
 denominatore. Ma le operazioni scelte non portano a questo risultato, le
 frazioni ottenute non hanno lo stesso denominatore. Errore nel scegliere
 le moltiplicazioni.
}
\text{name_feedback7=Errore nel compiere le moltiplicazioni.}
\text{name_feedback8= Per sommare due frazioni con lo stesso denominatore,
 occorre sommare i numeratori e mantenere invariato il denominatore comune.}
#endif