#if defined EQCONST
\text{name_statement=Construct two equal fractions from the numbers given below.}
\text{name_numerator=Numerator}
\text{name_denominator=Denominator}
#endif
#if defined MISSING
\text{name_denominator=denominator}
\text{name_numerator=numerator}
\text{name_statement=Fill the,below to establish the equality:}
\text{name_the=The}
#endif
#if defined FRACEQ
/* note for translators: keep commas */
\text{name_statement=Among the fractions presented below,find,that are equal.}
\text{name_eqfract=The equal fractions:}
\text{name_first=First pair:}
\text{name_second=Second pair:}
\text{name_third=Third pair:}
\text{name_fraction=Fraction}
\text{name_list_items=two, two pairs, three pairs}
#endif
#if defined CORRESP
\text{name_statement1=Establish the correspondance between}
#ifdef INVERSE
\text{name_statement2=the fractions and their inverses.}
#else
\text{name_statement2=equal fractions.}
#endif
\text{name_correspondance=The correspondance}
#endif
#if defined TARGET_guidadd
\text{name_list_objects=only the numerator, only the denominator,
the numerator and the denominator}
\text{name_gtext1=random(Rewrite the two fractions to put them on the same denominator,
    Put the two fractions on the same denominator)}
\text{name_list_method1=\name_gtext1,
    Rewrite the two fractions to put them to the same numerator,
    Add numerators first,
    Add denominators first,
    Add the numerators and multiply the denominators,
    Multiply the numerators
}
\text{name_list_method2=Add the numerators and keep the common denominator,
 Add the numerators and the denominators separately
}
\text{name_and=and}
\text{name_statement1=Compute the following addition.}
\text{name_statement2=Choose the starting method:}
\text{name_statement3=Step 1. Put the fractions on the same denominator.}
/* note for translators: keep commas */
\text{name_statement4=Multiplying,of,by,we get}
\text{name_statement5=Step 1. We have,therefore the sum becomes}
\text{name_statement6=What is the next step?}
\text{name_statement7=Step 2. We add the numerators and keep the common denominators, therefore the sum is}
\text{name_answer1=Method step}
\text{name_answer2=Objects to multiply}
\text{name_answer3=Multiplier}
\text{name_answer4=New numerator}
\text{name_answer5=New denominator}
\text{name_answer6=Numerator of the sum}
\text{name_answer7=Denominator of the sum}
\text{name_condition1=The multiplications are correct}
\text{name_condition2=The sum is good}
\text{name_feedback1=The two fractions have different denominators. One cannot
 add them directly; we have first to rewrite them in order to put them on
 the same denominator.}
\text{name_feedback2=In order that a fraction remains unchanged in value,
 one must multiply its numerator and denominator by a same number.}
\text{name_feedback3=You don't have the right to multiply the numerator and
 denominator of a fraction by 0!
 <p>
 You would get a ``fraction'' \(0/(0)), which doesn't make sense.
 </p>}
\text{name_feedback4=Sorry but this exercise does not allow you to multiply
 by a negative number.}
\text{name_feedback5=You should multiply the numerator and denominator of
 a fraction by an integer.}
\text{name_feedback6=Your aim is to put the fractions on a same denominator.
 Your multiplications do not achieve this, as the newly written fractions
 have different denominators. Wrong multiplications.
}
\text{name_feedback7=Computational error in the multiplications.}
\text{name_feedback8=To add two fractions of the same denominator, one has
 only to add the numerators, while keeping the common denominator.}
#endif