!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur:
<ul>
<li> sur la détermination d'extremum&nbsp;:
 <ul>
<li>niveau 1: les signes des trinômes sont évidents,</li>
<li>niveau 2: les signes des trinômes nécessitent le calcul du discriminant,</li>
</ul>
</li>
<li> les asymptotes et les branches infinies</li>
</ul>
 en Première S.

!read oef/$module_language/intromenu.phtml
!tail
