#if defined TARGET_raisongeo
# define TITRE Raison de suites géométriques
#endif
#if defined TARGET_raisonarit
# define TITRE Raison de suites arithmétiques
#endif
#if defined TARGET_classersuitesA
# define TITRE Classer des suites A (9 suites).
#endif
#if defined TARGET_classersuitesB
# define TITRE Classer des suites B (9 suites).
#endif
#if defined TARGET_sensvarsuite
# define TITRE Sens de variation de suites
#endif
#if defined TARGET_aritm1
# define TITRE Suite arithmétique ? 1
#endif
#if defined TARGET_aritm2
# define TITRE Suite arithmétique ? 2
#endif
#if defined TARGET_aritgo
# define TITRE Suite arithmético-géométrique
#endif
#if defined TARGET_geom1
# define TITRE Suite géométrique ?
#endif
