!header
!read Exindex
<style>
.logo_desc_mod {
  float:right;
  margin-left:0.5em;
  margin-right:0.2em;
  margin-top:0.2em;
}
</style>
Ce module regroupe pour l'instant $exototal exercices sur les vecteurs du plan de niveau seconde.
<p>
Il comporte des exercices de constructions et transformations de relations vectorielles 
ne nécessitant pas de coordonnées ainsi que des exercices de géométrie analytique.
</p>
<img src="$module_dir/images/logo_euler.png" class="logo_desc_mod" alt="Logo Euler Académie de Versailles" title="Euler Académie de Versailles" width="48" height="36">
<div class="wims_credits">
Module de Régine Mangeard maintenu et complété par le groupe Euler de l'académie de Versailles.
</div>
!read oef/$module_language/intromenu.phtml
!tail
