!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes
!default confparm2=1
!default confparm3=1


!set wims_html_mode=li
<ul>
<li>Paramétrage 1 : "Courses d'automates "
 <br>Numéro des questions à conserver :
<ul class="inline">
 !formcheckbox confparm1 from 1 to 9
</ul>
<small>Si rien n'est coché, toutes les questions sont conservées. </small>
</li><li>Paramétrage 2 : "Course d'automates "
  <br>Type d'exercice
  <ul class="inline"><li>
 !formradio confparm2 list 1,2 prompt A étapes,Toutes les questions sur une page
</li></ul>
</li>
<li>Paramétrage 3 : "Course d'automates "
<br>S'il est à étapes :
<ul class="inline"><li>
 !formradio confparm3 list 1,2 prompt Stopper à la première erreur,Laisser finir
</li></ul>
</li>
</ul>
