!header
!read Exindex
  <p><img src="$module_dir/images/logomutuwims2.png" style="float:right;margin-left:0.5em;margin-right:0.2em;" alt="Logo Mutuwims" title="Mituwims" width="60" height="61">
Une première version de ce module créé par Jean-Luc Donadoni a été publié en 2010.</p>
<p>Il regroupe actuellement $exototal exercices sur les automatismes au collège.</p>
<p>Les courses d'automates sont les sujets zéros publiés sur EDUSCOL en décembre 2025.</p>
<p>La liste des thèmes abordés est celle du BO automatismes lié à la nouvelle épreuve du DNB (dec. 2025). 
La numérotation des questions en fonction de ces thèmes est ci-dessous :</p>
<ul><li>Nombres et calculs (100 ... )</li>
<li>Espace et géométrie (200 ...)</li>
<li>Organisation et gestion des données (300 ...)</li>
<li>Proportionnalités fonctions(400 ...)</li>
<li>Algorithmique et programmation(500 ...)</li>
</ul>
<p>Les questions portants le caractère &#8718; sont des questions à choix unique (exemple Question 106&#8718;).</p>
<p>Les questions <b>QCM XXXXX</b> : D'autres exercices avec cinq questions issues des sujets précédents.</p>
!!mettre no si vous ne voulez pas qu'apparaissent automatiquement des
!!liens vers les modules de niveau similaire ayant un des mots clés
!!du module
!set related_modules=no
!!compléter si vous souhaitez que soit écrite une liste de mots clés
!!différente de celle définie dans le module (séparez chaque
!!mot clé par une virgule et assurez-vous que le lien obtenu
!!fait apparaitre au moins un module d'exercices)
!set keyw=quizz
!!mettre yes si certains des exercices ont une version latex définie
!!par la commande \latex{} afin que cela soit indiqué.
!set latex_exists=yes
!! to add a chronometer
!!default scoredelay=60,120
!read oef/intromenu.phtml
!tail
