!set introhook_tableless=yes
Ce paramétrage concerne l'exercice <b>Transformation d'écritures avec log et exp</b>.
<div class="formHelp">
Cocher les cases voulues.
Si plusieurs cases sont cochées, le type d'expression sera aléatoire entre toutes les cases cochées.
</div>
<ul><li>
!set wims_ref_id=confparm11
!formcheckbox confparm1 list 1 prompt \(u \log(p) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 2 prompt \(-u \log(p) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm13
!formcheckbox confparm1 list 3 prompt \(\log(p)+\log(q) \rightarrow \log(a)\)
</li>
<li>
!set wims_ref_id=confparm14
!formcheckbox confparm1 list 4 prompt \(\log(p)-\log(q) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm15
!formcheckbox confparm1 list 5 prompt \(u \log(p)+\log(q) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm16
!formcheckbox confparm1 list 6 prompt \(u \log(p)-\log(q) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm17
!formcheckbox confparm1 list 7 prompt \(u \log(p)+ v \log(q) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm18
!formcheckbox confparm1 list 8 prompt \(u \log(p) - v \log(q) \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm19
!formcheckbox confparm1 list 9 prompt \(\log(p) + q \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm20
!formcheckbox confparm1 list 10 prompt \(\log(p) - q \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm21
!formcheckbox confparm1 list 11 prompt \(u \log(p) + q \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm22
!formcheckbox confparm1 list 12 prompt \(u \log(p) - q \rightarrow \log(a)\)
</li><li>
!set wims_ref_id=confparm23
!formcheckbox confparm1 list 13 prompt \((a^p)^u \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm24
!formcheckbox confparm1 list 14 prompt \(1/(a^p)^u \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm25
!formcheckbox confparm1 list 15 prompt \(a^p \times a^q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm26
!formcheckbox confparm1 list 16 prompt \(a^p / a^q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm27
!formcheckbox confparm1 list 17 prompt \((a^p)^u \times a^q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm28
!formcheckbox confparm1 list 18 prompt \((a^p)^u / a^q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm29
!formcheckbox confparm1 list 19 prompt \((a^p)^u \times (a^q)^v \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm30
!formcheckbox confparm1 list 20 prompt \((a^p)^u  / (a^q)^v \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm31
!formcheckbox confparm1 list 21 prompt \(a^p \times q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm32
!formcheckbox confparm1 list 22 prompt \(a^p/q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm33
!formcheckbox confparm1 list 23 prompt \((a^p)^u \times q \rightarrow a^x\)
</li><li>
!set wims_ref_id=confparm34
!formcheckbox confparm1 list 24 prompt \((a^p)^u / q \rightarrow a^x\)
</li></ul>
