"""add_unique_name_constraint_to_user

Revision ID: 1f965c019567
Revises: 4b074d659ff2
Create Date: 2026-05-05 23:51:10.672351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f965c019567'
down_revision: Union[str, None] = '4b074d659ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_students')
    op.drop_table('classes')
    op.create_unique_constraint('uq_user_names', 'users', ['first_name', 'last_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_names', 'users', type_='unique')
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='classes_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('class_students',
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='class_students_class_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='class_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'student_id', name='class_students_pkey')
    )
    # ### end Alembic commands ###
