"""add_must_change_password_to_user

Revision ID: 4b074d659ff2
Revises: 5fd60ebc0a0d
Create Date: 2026-05-05 23:38:40.307447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b074d659ff2'
down_revision: Union[str, None] = '5fd60ebc0a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET must_change_password = FALSE")
    op.alter_column('users', 'must_change_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='classes_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('class_students',
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='class_students_class_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='class_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'student_id', name='class_students_pkey')
    )
    # ### end Alembic commands ###
