"""init users

Revision ID: abbbce7c5e1f
Revises: 
Create Date: 2026-04-27 17:45:17.652547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbbce7c5e1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academie_id', sa.Integer(), nullable=False),
    sa.Column('uai', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['academie_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uai')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etab_id', sa.Integer(), nullable=True),
    sa.Column('keycloak_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', 'inspector', name='user_role'), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etab_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('etablissements')
    op.drop_table('academies')
    # ### end Alembic commands ###
