#if defined TARGET_repgraph1 || defined TARGET_repgraph2 || defined TARGET_repgraph3 || defined TARGET_repgraph4 || defined TARGET_repgraph5
# define TITRE Représentation graphique
#endif
#if defined TARGET_reconnait1 || defined TARGET_reconnait2 || defined TARGET_reconnait3 || defined TARGET_reconnait4 || defined TARGET_reconnait5
# define TITRE Reconnaître une fonction affine
#endif
#if defined TARGET_pourcal1 || defined TARGET_pourcal2 || defined TARGET_pourcal3 || defined TARGET_pourcal4 || defined TARGET_pourcal5
# define TITRE Calculer un pourcentage
#endif
#if defined TARGET_vocabulaire1 || defined TARGET_vocabulaire2 || defined TARGET_vocabulaire3 || defined TARGET_vocabulaire4 || defined TARGET_vocabulaire5
# define TITRE Vocabulaire
#endif
#if defined TARGET_relation1 || defined TARGET_relation2 || defined TARGET_relation3 || defined TARGET_relation4 || defined TARGET_relation5
# define TITRE Relation de linéarité
#endif
#if defined TARGET_reconnaitre1 || defined TARGET_reconnaitre2 || defined TARGET_reconnaitre3 || defined TARGET_reconnaitre4 || defined TARGET_reconnaitre5
# define TITRE Reconnaître une fonction linéaire
#endif
#if defined TARGET_pourappl1 || defined TARGET_pourappl2 || defined TARGET_pourappl3 || defined TARGET_pourappl4 || defined TARGET_pourappl5
# define TITRE Appliquer un pourcentage
#endif
#if defined TARGET_lcoef1 || defined TARGET_lcoef2 || defined TARGET_lcoef3 || defined TARGET_lcoef4 || defined TARGET_lcoef5
# define TITRE Lecture du coefficient
#endif
#if defined TARGET_imgantgr1 || defined TARGET_imgantgr2 || defined TARGET_imgantgr3 || defined TARGET_imgantgr4 || defined TARGET_imgantgr5
# define TITRE Lecture graphique image-antécédent
#endif
#if defined TARGET_imgant1 || defined TARGET_imgant2 || defined TARGET_imgant3 || defined TARGET_imgant4 || defined TARGET_imgant5
# define TITRE Calcul d'image ou d'antécédant
#endif
#if defined TARGET_coefficient1 || defined TARGET_coefficient2 || defined TARGET_coefficient3 || defined TARGET_coefficient4 || defined TARGET_coefficient5
# define TITRE Coefficient
#endif
#if defined TARGET_imagec1 || defined TARGET_imagec2 || defined TARGET_imagec3 || defined TARGET_imagec4 || defined TARGET_imagec5
# define TITRE Calcul d'image
#endif
#if defined TARGET_antecedentc1 || defined TARGET_antecedentc2 || defined TARGET_antecedentc3 || defined TARGET_antecedentc4 || defined TARGET_antecedentc5
# define TITRE Calcul d'antécédent
#endif
#if defined TARGET_graphique1 || defined TARGET_graphique2 || defined TARGET_graphique3 || defined TARGET_graphique4 || defined TARGET_graphique5
# define TITRE Graphique
#endif
#if defined TARGET_graph2form1 || defined TARGET_graph2form2 || defined TARGET_graph2form3 || defined TARGET_graph2form4 || defined TARGET_graph2form5
# define TITRE Trouver la formule avec le graphique
#endif
#if defined TARGET_formule1 || defined TARGET_formule2 || defined TARGET_formule3 || defined TARGET_formule4 || defined TARGET_formule5
# define TITRE Établir une formule
#endif
#if defined TARGET_form2graph1 || defined TARGET_form2graph2 || defined TARGET_form2graph3 || defined TARGET_form2graph4 || defined TARGET_form2graph5
# define TITRE Retrouver la représentation graphique
#endif
#if defined TARGET_expression1 || defined TARGET_expression2 || defined TARGET_expression3 || defined TARGET_expression4 || defined TARGET_expression5
# define TITRE Retrouver la formule
#endif
#if defined TARGET_antecedentg1 || defined TARGET_antecedentg2 || defined TARGET_antecedentg3 || defined TARGET_antecedentg4 || defined TARGET_antecedentg5
# define TITRE Lecture graphique d'antécédent
#endif
#if defined TARGET_imageg1 || defined TARGET_imageg2 || defined TARGET_imageg3 || defined TARGET_imageg4 || defined TARGET_imageg5
# define TITRE Lecture graphique d'image
#endif

