#define TITLE Inégalité triangulaire
#define TITLE_en Inégalité triangulaire

\text{name_rep=est,n'est pas}

\matrix{name_instruction=On a les mesures suivantes
  Le plus grand côté a pour mesure
  La somme des mesures des deux autres côtés est égale à
  Donc le triangle
  constructible
  Voici ce que vous devriez avoir sur votre feuille}

\if{\lang=en}{
\text{name_rep=est,n'est pas}

\matrix{name_instruction=On a les mesures suivantes
  Le plus grand côté a pour mesure
  La somme des mesures des deux autres côtés est égale à
  Donc le triangle
  constructible
  Voici ce que vous devriez avoir sur votre feuille}
}
