#define TITLE Calcul d'aire
#define TITLE_en Calcul d'aire

\text{instruction1=On considère le trapèze ci-contre.}
\text{instruction2=Exprimer l'aire \(A\) de ce trapèze droit en fonction de \(x\).}

\text{instruction3=Quelle valeur faut-il donner à \(x\) pour que l'aire \(A\)
  soit égale à \e cm² ? }

\if{\lang=en}{
\text{instruction1=On considère le trapèze ci-contre.}

\text{instruction2=Exprimer l'aire \(A\) de ce trapèze droit en fonction de \(x\).}

\text{instruction3=Quelle valeur faut-il donner à \(x\) pour que l'aire \(A\)
  soit égale à \e cm²? }
}


