#define TITLE Aire d'un triangle
#define TITLE_en Aire d'un triangle

\matrix{name_instruction=Dans le triangle
  on a
  Indication : le triangle est un triangle rectangle en
  Peut-on calculer l'aire du triangle
  avec les données que l'on a
  Quelle formule utilisez-vous pour calculer l'aire de
  Donc l'aire de
  est environ égale à
  Donner le résultat en arrondissant au mm².
  Indication : le triangle n'est pas un triangle rectangle.
  J'appelle H le pied de la hauteur issue de
  On a les mesures suivantes
  Oui,Non
}

\if{\lang=en}{
\matrix{name_instruction=Dans le triangle
  on a
  Indication : le triangle est un triangle rectangle en
  Peut-on calculer l'aire du triangle
  avec les données que l'on a
  Quelle formule utilisez-vous pour calculer l'aire de
  Donc l'aire de
  est environ égale à
  Donner le résultat en arrondissant au mm².
  Indication : le triangle n'est pas un triangle rectangle.
  J'appelle H le pied de la hauteur issue de
  On a les mesures suivantes
  Oui,Non
}
}
