#define TITLE Droites remarquables
#define TITLE_en Droites remarquables

\matrix{name_prop=médiane,médiatrice,hauteur
  en son milieu,perpendiculairement
  issue de
  Voici un triangle
  sur lequel on a marqué les milieux de ses côtés.
  La
  passe par
  et coupe
  Voici la droite
  la droite
  perpendiculairement
  le segment
  en son milieu
}

\if{\lang=en}{
\matrix{name_prop=médiane,médiatrice,hauteur
  en son milieu,perpendiculairement
  issue de
  Voici un triangle
  sur lequel on a marqué les milieux de ses côtés.
  La
  passe par
  et coupe
  Voici la droite
  la droite
  perpendiculairement
  le segment
  en son milieu
}
}
