#define TITLE Droites remarquables QCM
#define TITLE_en Droites remarquables QCM

\text{name_answer=la droite passant par \(\A\) et le milieu \(\A'\) du côté \([\B\C]\).,
la droite passant par \(\A\) et perpendiculaire au côté \([\B\C]\).,
la droite passant par le milieu \(\A'\) du côté \([\B\C]\) et perpendiculaire au côté \([\B\C]\).}

\text{name_question=la médiane issue de \(\A\),
la hauteur issue de \(\A\),
la médiatrice du côté \([\B\C]\)}

\text{name_enonce=Dans le triangle \(\A\B\C\) quelle est \name_question[\k]}
\text{name_is=est}
