#define TITLE Triangle particulier
#define TITLE_en Triangle particulier

\text{nom=triangle rectangle,triangle équilatéral,triangle isocèle}

\text{name_instruction=Mettre en correspondance chaque figure avec son nom.
 On a les données suivantes}

\if{\lang=en}{
\text{nom=triangle rectangle,triangle équilatéral,triangle isocèle}

\text{name_instruction=Mettre en correspondance chaque figure avec son nom.
 On a les données suivantes}
}
