#define TITLE Incidence deux droites perpendiculaires et une droite parallèle
#define TITLE_en Incidence deux droites perpendiculaires et une droite parallèle

\text{name_prop=parallèles,perpendiculaires,sécantes}

\text{name_instruction1=Sachant que les droites \cf[1] et \cf[2] sont
  perpendiculaires et que les droites \cf[1] et \cf[3] sont parallèles,
  que peut-on dire sur les droites \cf[2] et \cf[3]}

\text{name_instruction2=Sachant que les droites \cf[1] et \cf[2] sont
  perpendiculaires et que les droites \cf[2] et \cf[3] sont parallèles,
  que peut-on dire sur les droites \cf[1] et \cf[3]}

\text{name_instruction3=Sachant que les droites \cf[1] et \cf[2] sont
  perpendiculaires, que peut-on dire sur les droites \cf[2] et \cf[3]}

\text{name_prompt=Elles sont}

\if{\lang=en}{
\text{name_prop=parallèles,perpendiculaires,sécantes}

\text{name_instruction1=Sachant que les droites \cf[1] et \cf[2] sont
  perpendiculaires et que les droites \cf[1] et \cf[3] sont parallèles,
  que peut-on dire sur les droites \cf[2] et \cf[3]}

\text{name_instruction2=Sachant que les droites \cf[1] et \cf[2] sont
  perpendiculaires et que les droites \cf[2] et \cf[3] sont parallèles,
  que peut-on dire sur les droites \cf[1] et \cf[3]}

\text{name_instruction3=Sachant que les droites \cf[1] et \cf[2] sont
  perpendiculaires, que peut-on dire sur les droites \cf[2] et \cf[3]}

\text{name_prompt=Elles sont}
}
