plot=1
draw=0
image=0
XRANGE=-20:20
YRANGE=-20:20
insplot_set=size 0.6,0.6; border ; zeroaxis linetype 3 ; tmargin 1 ; rmargin 1 ; xlabel "x-axis" ; ylabel "y-axis"
!insplot [$XRANGE] [$YRANGE] $functie notitle
etext=!record 50 of lang/remarks.$taal
exotext=<a onmouseover="return escape('<img src=\'$wims_refname?&session=$session&module=$module&cmd=getins&special_parm=insert-1.gif\' alt=\'noalt\' />')"><span class="schaersvoorde_link">$etext</span></a>

!exit
