!! This file can contain contents which go to the end of the page.

!if $status=waiting
 <p>
 Na voljo so spletna raèunala:
 !href target=wims_tool module=tool/linear/linsolver Linearni re¹evalec
,
 !href target=wims_tool module=tool/linear/matrix Matrièno raèunalo
,
 !href target=wims_tool module=tool/linear/vector Vektorsko raèunalo
,
 !href target=wims_tool module=tool/number/calcnum Numerièno raèunalo
. (Orodje se odpre v novem oknu.)
!endif
