!header
!read Exindex
Deze module bevat $exototal oefeningen over machten van tien en andere getallen.
Ook wordt de wetenschappelijke notatie behandeld.
!read oef/intromenu.phtml

<p align="left">
    <font size="-2">
	<em>
    	    meer modules met dezelfde&nbsp;
	    !href module=home&search_category=$module_category&search_keywords=$module_keywords
	    zoektermen
    	    </a>
	</em>
    </font>
</p>

!tail
