!header
!read Exindex
This module contains $exototal exercises about the <b>limit calculus 
of logarithm and exponential functions</b>.

The required and tested skills are: 
<small><ul>
<li>limits of polynoms and quotient of polynoms, of functions ln and exp ; 
</li>
<li>computational properties of limits (theorems about the limits of sums, products, quotients, composed functions) ;</li>
<li>indeterminate forms;</li>
<li> compared growth properties  between polynoms and the
functions exp and ln.</li>
</ul>
<font color=blue>
The exercises are composed of several steps. An exercise goes on, even if
a false reply has been given at the precedent step. The good answers
are provided after each step, to enable  further evaluations. 
</font>
<marquee><a href="mailto:royer.veronique@orange.fr"><font color=red><b>NEW EXERCISES. PLEASE SIGNAL ANY BUG...</b></font></a></marquee>
</small>
!read oef/$module_language/intromenu.phtml
!tail
