#if defined TARGET_defim || defined TARGET_defim2 || defined TARGET_defim3
# define TITRE Définition et image
#endif
#if defined TARGET_acoscos
# define TITRE arccos(cos)
#endif
#if defined TARGET_acossin
# define TITRE arccos(sin)
#endif
#if defined TARGET_atantan
# define TITRE arctg(tg)
#endif
#if defined TARGET_compderiv
# define TITRE Dérivabilité de composée
#endif
#if defined TARGET_comprange
# define TITRE Zone composée
#endif
#if defined TARGET_acoscoslin
# define TITRE arccos(cos) linéaire
#endif
#if defined TARGET_derivarc
# define TITRE Dérivée
#endif
#if defined TARGET_acosfrac
# define TITRE Domaine de définition (Arcsin, Arccos)
#endif
