#if defined TARGET_defim || defined TARGET_defim2 || defined TARGET_defim3
# define TITRE_en Définition and image
#endif
#if defined TARGET_acoscos
# define TITRE_en arccos(cos)
#endif
#if defined TARGET_acossin
# define TITRE_en arccos(sin)
#endif
#if defined TARGET_atantan
# define TITRE_en arctg(tg)
#endif
#if defined TARGET_compderiv
# define TITRE_en Composed differentiability
#endif
#if defined TARGET_comprange
# define TITRE_en Composed range
#endif
#if defined TARGET_acoscoslin
# define TITRE_en Linear arccos(cos)
#endif
#if defined TARGET_derivarc
# define TITRE_en Derivative
#endif
#if defined TARGET_acosfrac
# define TITRE_en Definition domain(Arcsin, Arccos)
#endif
