<div class="encadre">
<div id="boited">
<img src="\imagedir/banquise.png" alt="Banquise">
</div>
<div id="boiteg">
<img src="\imagedir/arctiquefonteeee.gif" alt="Fonte de la banquise">
<br>
<b>Évolution de la glace de mer entre 1979 et 2007</b>
</div>
<p class="problematique"> \pro</p>
<div class="enonce">\enonce
Les résultats obtenus ont été placés dans le tableau suivant :
<div class="wims_scrollable">
<table class="wimscenter">
<tr>
<th><b>Année</b></th>
\for{j=1980 to 2006}{<td> \j </td>}
</tr>
<tr>
<th><b>Millions de km<sup>2</sup></b></th>
\for{j=1 to 27}{<td class="wimscenter"> \mmm[\j;] </td>}
</tr>
</table>
</div>
<b>L'ensemble des résultats sont à arrondir à 0,01.</b>
</div>
