!! var6 = max1,max2,max3,max4.... (aantal cellen per kolom)
!! var5 = A1,B1 A2,B2 ... Amax,Bmax
!! var7 = head Kolom A,Kolom B ,Kolom C
!!<table id="spreadsheet_table" class="demospecial"> niet te gebruiken ivm 6px padding 
<table id="spreadsheet_table" style="width:100%;border:1px solid blue;background-color:#a6d4ff;">
 <tr>
  !for head in $var7
   <th style="border:1px solid blue;">$head</th>
  !next head
 </tr>
!set once=0
!set textcolumns=$var8
!set idx=1
!for p=1 to $var6
 !set dd=!word $p of $var5
 <tr>
 !for k in $dd
  <th id="th_$idx" style="border:1px solid blue;"> $k </th>
  !set idx=$[$idx+1]
 !next k
 !if $once=0
  !for i=1 to $textcolumns
   <th rowspan="$var6" valign="top" id="field_$[$i-1]" style="border:1px solid blue;"></th>
  !next i
  !set once=1
 !endif
 </tr>
!next p
</table>
<script type="text/javascript">
 "use strict";
 var table = document.getElementById('spreadsheet_table');
 var H = table.offsetHeight;
 H = parseInt(H/($var6+1)); /* we nemen de hoogte in px van de tabel en delen die door het aantal rijen */
 var textcolumns = $textcolumns;
 var cells=[$var6,$var6,1,1]; /* let op: maximaal 4 kolommen !*/
 var colls=[$cols,$cols,$[3*$colls],$[3*$colls]]; /* dit is de breedte van een kolom */
 for( var p=0 ; p < textcolumns ; p++){
  var h = cells[p]*H;
  var field = document.getElementById('field_'+p);
  var textarea = document.createElement('TEXTAREA');
  textarea.setAttribute("id","textarea_"+p); /* using 'setAttribute' for IE / Edge */
  textarea.setAttribute("rows",cells[p]);
  textarea.setAttribute("cols",colls[p]);
  textarea.setAttribute("style","overflow:hidden;resize:none;text-align:center;line-height:"+H+"px;margin-bottom:0px;height:"+h+"px;max-height:"+h+"px;color:red;top:0px;bottom:0px;left:0px;right:0px;border:none");
  field.appendChild(textarea);
 };
 
 function sendanswer(){
  var show="";var total = new Array(textcolumns);var i = 0;
  for( i = 0; i<textcolumns ; i++){
   var textarea = document.getElementById('textarea_'+i);
   var org = textarea.value;
   var rep = org.split('\n');
   var num = rep.length;
   var reply = new Array();
   var idx = 0;
   for(var p = 0 ; p < num ; p++){
    if( rep[p].length != 0 ){
     if( rep[p].indexOf(',') != 0 ){ rep[p] = rep[p].replace(',','.');}; /* using decimal point in numbers */
     if( is_real_number(rep[p]) ==  0 ){ return; };
     reply[idx] = rep[p];
     idx++;
    };
   };
   show = show + '<textarea cols=3 rows=$var6 style=text-align:center;color:red>'+org+'</textarea>';
   if ( idx == 0 ){setAlarm(r44); return;};
   if(i == 0 ){ if( reply.length != $var6 ){setAlarm("je moest via cut&amp;paste $var6 cellen gebruiken...");return;}; };
   total[i] = reply +"\n";
  };
  myConfirm(show,total,'$wims_ref_name','$session','$module','$counter','$ok_send_color');
 };
</script>
