!nocache
oefstepcnt=0
!if $oefsteps=$empty
  oefstep=0
  !exit
!endif
oefsteps=!translate $	\
$ to ;; in $oefsteps
oefsteps=!lower $oefsteps
oefsteps=!replace replies by r in $oefsteps
oefsteps=!replace choices by c in $oefsteps
oefsteps=!replace reply by r in $oefsteps
oefsteps=!replace choice by c in $oefsteps
oefsteps=!nospace $oefsteps
oefsteps=!rows2lines $oefsteps
!if $dynstep=yes
  oefsteps=!line 1 of $oefsteps
!endif
oefsteps=!nonempty lines $oefsteps
oefstepcnt=!linecnt $oefsteps
rr=!text select r in $oefsteps
cc=!text select c in $oefsteps
creplycnt=!charcnt $rr
cchoicecnt=!charcnt $cc
!default oefstep=1
