#if defined TARGET_alignement
# define TITRE Alignement ou non de trois points
#endif
#if defined TARGET_appartenance
# define TITRE Appartenance d'un point à une droite
#endif
#if defined TARGET_droitespara
# define TITRE Droites parallèles (par les équations)
#endif
#if defined TARGET_droitespara2
# define TITRE Droites parallèles (par les vecteurs)
#endif
#if defined TARGET_ordonneeorigine
# define TITRE Cliquer sur l'ordonnée à l'origine
#endif
#if defined TARGET_parallele
# define TITRE Parallèle à une droite  par un point
#endif
#if defined TARGET_perpendiculaire
# define TITRE Perpendiculaire à une droite
#endif
