#if defined TARGET_ineqexpo1 || defined TARGET_ineqexpo2 || defined TARGET_ineqexpo3 || defined TARGET_ineqexpo4 || defined TARGET_ineqexpo5
# define TITLE Inéquation avec exponentielle
#endif
#if defined TARGET_sumprod1 || defined TARGET_sumprod2 || defined TARGET_sumprod3 || defined TARGET_sumprod4 || defined TARGET_sumprod5
# define TITLE Simplification d'écriture
#endif
#if defined TARGET_eqexpo1 || defined TARGET_eqexpo2 || defined TARGET_eqexpo3 || defined TARGET_eqexpo4 || defined TARGET_eqexpo5 || defined TARGET_eqexpo6
# define TITLE Équation avec exponentielle
#endif
