!header
!read Exindex
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;"/>
Ce module regroupe pour l'instant $exototal exercices sur les équations de droites dans le plan repéré au début du lycée.
Pour une majorité d'exercices, vous avez le choix d'afficher ou de ne pas afficher un graphique pour aider les élèves.

<div class="wims_credits">Elaboré avec la communauté MutuWIMS</div>
!read oef/intromenu.phtml
!tail
