#if defined TARGET_reduire1 || defined TARGET_reduire2 || defined TARGET_reduire3 || defined TARGET_reduire4 || defined TARGET_reduire5 || defined TARGET_reduire1p || defined TARGET_reduire2p
# define TITRE Réduire une expression
#endif
#if defined TARGET_simplifier1 || defined TARGET_simplifier2 || defined TARGET_simplifier3 || defined TARGET_simplifier4 || defined TARGET_simplifier5 || defined TARGET_simplifier1p
# define TITRE Simplifier un produit
#endif
#if defined TARGET_factoriser1 || defined TARGET_factoriser2 || defined TARGET_factoriser3 || defined TARGET_factoriser4 || defined TARGET_factoriser5
# define TITRE Factoriser une somme
#endif
#if defined TARGET_evaluerA1 || defined TARGET_evaluerA2 || defined TARGET_evaluerA3 || defined TARGET_evaluerA4 || defined TARGET_evaluerA5 || defined TARGET_evaluerB1 || defined TARGET_evaluerB2 || defined TARGET_evaluerB3 || defined TARGET_evaluerB4 || defined TARGET_evaluerB5
#define TITRE Évaluer une expression
#endif
#if defined TARGET_distribuer1 || defined TARGET_distribuer2 || defined TARGET_distribuer3 || defined TARGET_distribuer4 || defined TARGET_distribuer5
# define TITRE Distribuer
#endif
#if defined TARGET_developperA1 || defined TARGET_developperA2 || defined TARGET_developperA3 || defined TARGET_developperA4 || defined TARGET_developperA5 || defined TARGET_developperB1 || defined TARGET_developperB2 || defined TARGET_developperB3 || defined TARGET_developperB4 || defined TARGET_developperB5
# define TITRE Développer une expression
#endif
#if defined TARGET_formule1 || defined TARGET_formule2 || defined TARGET_formule3 || defined TARGET_formule4 || defined TARGET_formule5
# define TITRE Établir une formule
#endif
