!form reply
<ol style="list-style-type: upper-alpha;">
<li>
<input type="radio" name="choice" id="choice_A" value="A" /> <label for="choice_A">$textA</label>
</li><li>
<input type="radio" name="choice" id="choice_B" value="B" /> <label for="choice_B">$textB</label>
</li><li>
<input type="radio" name="choice" id="choice_C" value="C" /> <label for="choice_B">$textC</label>
!if $exask=yes
  $(name_inthiscase):
  <ul class="wims_nopuce"><li>
  <label for="exa1">\(a\)</label>=<input size="5" id="exa1" name="exa1" value="$exa1" />,
  <label for="exb1">\(b\)</label>=<input size="5" id="exb1" name="exb1" value="$exb1" />,
  </li><li>
  $name_false&nbsp;:<br>
  <label for="exa2">\(a\)</label>=<input size="5" id="exa2" name="exa2" value="$exa2" />,
  <label for="exb2">\(b\)</label>=<input size="5" id="exb2" name="exb2" value="$exb2" />.
  </li></ul>
!endif
</li>
</ol>
!set wims_ref_class=wims_button
<input type="submit" value="$wims_name_send" />
!formend
