!header

!read present.phtml

!if $status=waiting
  !if $error!=$empty
    <div class="wims_msg alert">
    !read msg.phtml
    </div>
  !endif
  !read form.phtml
  !if $repeatd<1 or $repeated>=$repeat
    <p>
    !set wims_ref_class=wims_button
    !href exo_Renew
    </p>
  !endif
!else
  !if $error!=$empty
    <div class="wims_msg alert">
    !read msg.phtml
    </div>
  !endif
  !! Analysis of reply
  !read answer.phtml
  <div>
  !if $repeated<1 or $repeated>=$repeat
  !set wims_ref_class=wims_button
    !href exo_Again
  !endif
  !set wims_ref_class=wims_button
  !if $worksheet=$empty
     !href exo_Intro
  !endif
  </div>
!endif

:end
!tail
