!default confparm2=1
!default confparm3=1
!default confparm4=1

!if $lang=it

  !set name_mode=Modalità di risoluzione (per gli esercizi più lunghi)
  !set name_list_mode=guidato,esperti
  !set name_kind=Tipi di numeri negli enunciati
  !set name_list_kind=interi,decimali
  !set name_notation=Notazione utilizzata rette (AB), segmenti [CD]

  !goto menu
!endif

!set name_mode=Mode de résolution (pour les exercices longueurs)
!set name_list_mode=guidé,brut
!set name_kind=Nature des nombres de l'énoncé
!set name_list_kind=entiers,décimaux
!set name_notation=Notation utilisée droite (AB), segment [CD]

:menu
<tr><th>$name_mode
</th><td>
!formselect confparm2 list 1,2 prompt $name_list_mode
</td>
</tr><tr><th>$name_kind</th><td>
!formselect confparm3 list 1,2 prompt $name_list_kind
</td></tr>
</tr><tr><th>$name_notation</th><td>
!formselect confparm4 list 1,2 prompt $wims_name_yes,$wims_name_no
</td></tr>
