
\matrix{data=
13,Bouches-du-Rhône,Marseille,Provence-Alpes-Côte-d'Azur,Marseille,342,353,	'
14,Calvados,Caen,Basse-Normandie,Caen,148,102,
2A,Corse-du-Sud,Ajaccio,Corse,Ajaccio,487,422,
21,Côte-d'Or,Dijon,Bourgogne,Dijon,312,178,				'
25,Doubs,Besançon,Franche-Comté,Besançon,364,179,
31,Haute-Garonne,Toulouse,Midi-Pyrénées,Toulouse,209,364,
33,Gironde,Bordeaux,Aquitaine,Bordeaux,143,300,
34,Hérault,Montpellier,Languedoc-Roussillon,Montpellier,280,357,
35,Ille-et-Vilaine,Rennes,Bretagne,Rennes,113,143,
44,Loire-Atlantique,Nantes,Pays-de-la-Loire,Nantes,108,181,
45,Loiret,Orléans,Centre,Orléans,234,158,
51,Marne,Châlons-sur-Marne,Champagne-Ardenne,Châlons-sur-Marne,292,102,
57,Moselle,Metz,Lorraine,Metz,361,96,
59,Nord,Lille,Nord-Pas-de-Calais,Lille,262,44,
63,Puy-de-Dôme,Clermont-Ferrand,Auvergne,Clermont-Ferrand,267,258,
67,Bas-Rhin,Strasbourg,Alsace,Strasbourg,392,105,
69,Rhône,Lyon,Rhône-Alpes,Lyon,313,251,
76,Seine-Maritime,Rouen,Haute-Normandie,Rouen,195,77,
80,Somme,Amiens,Picardie,Amiens,230,66,
86,Vienne,Poitiers,Poitou-Charentes,Poitiers,176,223,
87,Haute-Vienne,Limoges,Limousin,Limoges,202,254,
95,Val-d'Oise,Pontoise,Ile-de-France,Paris,229,103,			'
}


