!header
!read Exindex

!if $lang iswordof fr

Ce module regroupe pour l'instant $exototal exercices sur la géométrie euclidienne
en dimension 3 (distance entre points, plans, droites).  

!goto end
!endif

!if $lang notwordof fr ca es

 This module currently contains $exototal exercises on Euclidean geometry
in dimension 3 (distance between points, planes, lines).
 !goto end
!endif

!if $lang iswordof ca

 Aquest mòdul conté $exototal exercicis sobre geometria euclidiana
de dimensió 3 (distància entre punts, plans, rectes).

 !goto end
!endif

!if $lang iswordof es

 Este módulo contiene $exototal ejercicios sobre geometría euclidiana
de dimensión 3 (distancia entre puntos, planos, rectas).

 !goto end
!endif

:end

!read oef/$module_language/intromenu.phtml
!tail
