#if defined TARGET_deg1
# define TITRE Inéquation de degré 1
#endif
#if defined TARGET_xchgmult
# define TITRE Échange et mult
#endif
#if defined TARGET_fracx1
# define TITRE Fraction simple I
#endif
#if defined TARGET_invx
# define TITRE Inverse I
#endif
#if defined TARGET_invx2
# define TITRE Inverse II
#endif
#if defined TARGET_lindeduc
# define TITRE Déduction linéaire
#endif
#if defined TARGET_majsqr1
# define TITRE Majorer le carré I
#endif
#if defined TARGET_majsqr1b
# define TITRE Majorer le carré Ib
#endif
#if defined TARGET_possqr1
# define TITRE Carré positif I
#endif
#if defined TARGET_possqr2
# define TITRE Carré positif II
#endif
#if defined TARGET_transiadd
# define TITRE Transitivité et addition
#endif
#if defined TARGET_sum
# define TITRE Somme donnée
#endif
