\title_es{GGG Inyectividad y sobreyectividad}

\text{listecas= Una función de \(E) en \(F) puede ser,
Existe una función \(f) de \(E) en \(F) que es,
Una función de \(E) en \(F) es necesariamente no,
Ninguna función de \(E) en \(F) es }
\text{inj=inyectiva}
\text{surj=sobreyectiva}
\text{bij=biyectiva}
\text{aut=otra}

\text{instruction=Sean \(E) y \(F) dos conjuntos  finitos tales que}
\text{warning=La respuesta otra significa que ninguna de las otras afirmaciones es correcta.}