\title_it{GGG Descrizione di un sottoinsieme del piano}

\text{listeforme=quadrato,segmento,triangolo}

\matrix{instruction=Sia \(E\) l'insieme
Come sottoinsieme del piano, gli elementi di \(E\) costituiscono tutti i punti a coordinate intere del
Un modo alternativo di scrivere l'insieme \(E\) è
Per tutti gli interi \(y\) che verificano
l'insieme
La cardinalità di \(E\) è}

\text{name_suchthat=tale che}
\text{name_and=e}
\text{name_has=ha}
\text{name_avec=con}
\text{name_elements=elementi}
\text{name_element=elemento}
\text{name_forall=Per tutti}
\text{name_andnot=e non}
\matrix{name_solution=Dalla seconda espressione di \(E\) si ricava che il numero di elementi di \(E\) è esattamente il numero di interi compresi tra
Un modo per calcolare il numero di elementi di \(E\) è di pensarlo come l'unione di insiemi a due a due disgiunti
La cardinalità di un insieme è il numero dei suoi elementi}

\text{name_solution2=Per calcolare la cardinalità di \(E\), si può anche ragionare geometricamente: si calcolano il numero di punti a coordinate intere che si trovano dentro il quadrato}

\text{name_solution3= e il numero di punti che si trovano sulla diagonale di tale quadrato. Da questi si deduce il numero di punti in \(E\)}

\matrix{name_feedback=Esatto, l'insieme \(E\) ha
L'insieme \(E\) ha
un insieme che ha}

\text{name_help=\(\displaystyle{\ZZ}\) indica l'insieme dei numeri interi e \(\ZZ^2\) l'insieme delle coppie di interi. Si può rappresentare \(\ZZ^2\) come l'insieme dei punti del piano le cui coordinate sono numeri interi.}

