
\text{name_feed1=Avec \reply1 dollars, vous pouvez aller jusqu'au numéro
\nr de la \a2 ème avenue (si ce numéro existe !).}

\text{name_feed2=Avec \reply1 dollars, vous ne pouvez aller que
jusqu'au numéro \nr de la \ar ème avenue.}

\matrix{name_feed3=2- Bonne réponse ! Il y a \nb trajets différents pour faire cette course.
2- Votre réponse est incorrecte. Il y a \nb trajets différents pour faire cette course.}
