#if defined TARGET_traduction1
\title_es{GGG Asociar eventos y conjuntos}
#elif defined TARGET_traduction2
\title_es{GGG Conjuntos: descripción formal}
#elif defined TARGET_traduction3
\title_es{GGG Descripción de los elementos de un conjunto}
#endif

#if defined TARGET_traduction1
\text{name_question=Haga corresponder formulaciones probabilistas equivalentes.}

#else
\text{instruction=Sean \(A\), \(B\) y \(C\) tres conjuntos.}

# if defined TARGET_traduction2
 \text{name_question=La columna de la derecha contiene la descripción formal de los elementos de cuatro conjuntos diferentes ¿Cuáles son}
 \text{name_instruction=Asociar el conjunto correspondiente a cada descripción.}
# else
 \text{name_question=Haga corresponder afirmaciones equivalentes.}

# endif
#endif
