#if defined TARGET_ssensplan
\title_es{GGG Cardinalidad de un subconjunto del plano}
#endif
#if defined TARGET_ssensclassiq
\title_es{GGG Cardinalidad de un conjunto clásico}
#endif
#if defined TARGET_ssensclassiq0
\title_es{GGG Cardinalidad de un conjunto clásico 0}
#endif

\matrix{name_vocab=es un subconjunto de
y
Ha entregado la respuesta correcta
El conjunto \(E\) tiene
elemento,elementos
y no
Podemos \(E\) como el conjunto de puntos de coordenadas enteras incluídas en
el rectángulo, el cuadrado
funciones,funciones biyectivas,funciones inyectivas}

\text{instruction=¿Cuál es la cardinalidad del siguiente conjunto \(E\) }
