\title_es{GGG  Escritura de eventos como conjuntos}

\matrix{name_listens=el evento \ens1 sí ocurre
\ens1 no ocurre
al menos uno de los dos eventos ocurre
entre los dos eventos&#44; solo el evento \ens1 ocurre
los eventos \ens1 y \ens2 ocurren
ninguno de los 2 eventos ocurre
\ens2 ocurre o \ens1 no ocurre
al menos uno de los eventos no ocurre
ni \(\ens1)&#44; ni \(\ens2) ocurren}

\text{instruction=Denotamos por \(\A\) y \(\B\) dos eventos que pueden ocurrir en el transcurso de esta experiencia. Abusando de la notación,
\(\A\) y \(\B\) también denotan los subconjuntos de \({\Omega}\) que describen esto eventos.
}

\text{name_question=¿Cuál es la escritura como conjunto del siguiente evento \(F\) }
\text{name_feedback=<b>Nota:</b> la escritura más simple de \(F\) es}
