
\matrix{name_listens=l'événement \ens1 est réalisé
\ens1 n'est pas réalisé
au moins un des deux événements est réalisé
parmi les 2 événements&#44; seul l'événément \ens1 est réalisé
les événéments \ens1 et \ens2 sont réalisés
aucun des 2 événements n'est réalisé
\ens2 est réalisé ou \ens1 n'est pas réalisé
au moins un des deux événements n'est pas réalisé
ni \(\ens1)&#44; ni \(\ens2) n'est réalisé}


\text{instruction=On désigne par \(\A\) et \(\B\) deux événements qui
peuvent se réaliser au cours de cette expérience. Par abus de notations,
\(\A\) et \(\B\) désignent aussi les parties de \({\Omega}\) qui décrivent ces événements.
}

\text{name_question=Quelle est l'écriture ensembliste de l'événement \(F\) suivant&nbsp;}
\text{name_feedback=<b>Remarque :</b> l'écriture la plus simple de l'événement \(F\) est}
