\title_es{GGG Descripción de un subconjunto del plano}

\text{listeforme=un cuadrado, un segmento de recta, un triángulo}

\matrix{instruction=Sea \(E\) el conjunto
Como subconjunto del plano, los elementos de \(E\) constituyen puntos de coordenadas enteras incluídos en 
Otra manera de escribir el conjunto \(E\) es
Para todo entero \(y\) que verifica
el conjunto
La cardinalidad de \(E\) es}

\text{name_suchthat=tal que}
\text{name_and=y}
\text{name_has=tiene}
\text{name_avec=con}
\text{name_elements=elementos}
\text{name_element=elemento}
\text{name_forall=Para todo}
\text{name_andnot=y no}
\matrix{name_solution=De la segunda expresión de \(E\), el número de elementos de  \(E\) es exactamente el número de enteros comprendidos entre 
Una manera de calcular el número de elementos de \(E\) es escribirlo como una unión de conjuntos disjuntos dos a dos
La cardinalidad de un conjunto es el número de elementos que contiene}

\text{name_solution2=Para calcular la cardinalidad de \(E\), podemos también razonar geométricamente: podemos calcular el número de puntos de coordenadas enteras que se encuentran dentro del cuadrado}

\text{name_solution3= y el número de putos de coordenadas enteras que se encuentran sobre la diagonal de ese cuadrado. Deducimos luego el número de puntos en \(E\)}

\matrix{name_feedback=Respuesta correcta, el conjunto \(E\) tiene
El conjunto \(E\) tiene
un conjunto que tiene}

\text{name_help=\(\displaystyle{\ZZ}\) denota el conjunto de números enteros y \(\ZZ^2\) el conjunto de pares de enteros. Se puede representar \(\ZZ^2\) como el conjunto de puntos del plano cuyas coordenadas son números enteros.}
