\title_it{GGG Eventi e insiemi}

\text{evnt=almeno uno dei 3 eventi si è verificato, l'evento \ens1 si è verificato, tra i 3 eventi solo l'evento \ens1 si è verificato, almeno due eventi tra i tre si sono verificati, gli eventi \ens1 e \ens2 si sono verificati, almeno uno dei due eventi \(\ens1) e \(\ens2) si è verificato,gli eventi \(\ens1) e \(\ens2) si sono verificati ma non \(\ens3), i tre eventi si sono verificati}
\text{evnt2=nessuno dei 3 eventi si è verificato, \ens1 non si è verificato, \ens1 non si è verificato o uno degli altri due eventi si è verificato, al più uno dei 3 eventi si è verificato, almeno uno dei due eventi \ens1 e \ens2 non si è verificato, né \(\ens1) né \(\ens2) si è verificato,\ens3 si è verificato o uno degli altri due eventi non si è verificato, almeno uno dei 3 eventi non si è verificato}

\matrix{name_question=Qual è la scrittura insiemistica dell'evento \(F\) seguente
Risposta corretta, l'evento \(F\) è rappresentato dall'insieme
Qual è l'evento complementare
Risposta corretta, l'evento complementare \(F^c\) è
Qual è la scrittura insiemistica dell'evento complementare
}

\text{label=Insieme,Evento}

