\title_it{GGG Iniettività e suriettività}

\text{listecas= Un'applicazione di \(E) in \(F) può essere,
Esiste sicuramente un'applicazione \(f) di \(E) in \(F) che è,
Un'applicazione di \(E) in \(F) è necessariamente non,
Nessuna applicazione di \(E) in \(F) è }
\text{inj=iniettiva}
\text{surj=suriettiva}
\text{bij=biunivoca}
\text{aut=altro}

\text{instruction=Siano \(E) e \(F) due insiemi finiti tali che}
\text{warning=La risposta altro significa che nessuna delle altre affermazioni è corretta.}
