
\text{listeforme=un carré, un segment de droite, un triangle}

\matrix{instruction=On note \(E\) l'ensemble
Comme sous-ensemble du plan, les éléments de \(E\) constituent tous les points à coordonnées entières inclus dans
Une autre façon d'écrire l'ensemble \(E\) est&nbsp;
Pour tout entier \(y\) vérifiant
l'ensemble
Le cardinal de \(E\) est}

\text{name_suchthat=tel que}
\text{name_and=et}
\text{name_has=a}
\text{name_avec=avec}
\text{name_elements=éléments}
\text{name_element=élément}
\text{name_forall=Pour tout}
\text{name_andnot=et non}
\matrix{name_solution=D'après la seconde expression de \(E\), le nombre d'éléments de \(E\) est le nombre d'entiers compris entre
Une façon de calculer le nombre d'éléments de \(E\) est d'écrire \(E\) comme une réunion d'ensembles deux à deux disjoints
Le cardinal d'un ensemble désigne le nombre d'éléments de cet ensemble}

\text{name_solution2=Pour calculer le cardinal de \(E\), on peut aussi raisonner géométriquement :
on calcule le nombre de points à coordonnées entières se trouvant dans le carré}

\text{name_solution3= et le nombre de points à coordonnées entières
se trouvant sur la diagonale de ce carré. On en déduit ensuite le nombre de points dans \(E\)}

\matrix{name_feedback=Bonne réponse, l'ensemble \(E\) a
L'ensemble \(E\) a
un ensemble ayant}

\text{name_help=\(\displaystyle{\ZZ}\) désigne l'ensemble des entiers et \(\ZZ^2\) l'ensemble des couples d'entiers.
On peut représenter \(\ZZ^2\) comme l'ensemble des points du plan dont les coordonnées
sont des entiers.}
