
\text{evnt=au moins un de ces 3 événements est réalisé, l'événement \ens1 est réalisé, parmi les 3 événements seul l'événément \ens1 est réalisé, au moins deux événements parmi les trois sont réalisés, les événéments \ens1 et \ens2 sont réalisés, au moins un des deux événéments \(\ens1) et \(\ens2) est réalisé,les événements \(\ens1) et \(\ens2) sont réalisés mais pas \(\ens3), les trois événements sont réalisés}
\text{evnt2=aucun de ces 3 événements n'est réalisé, \ens1 n'est pas réalisé, \ens1 n'est pas réalisé ou l'un des deux autres événements est réalisé, au plus un de ces 3 événements est réalisé, au moins un des deux événements \ens1 et \ens2 n'est pas réalisé, ni \(\ens1) ni \(\ens2) n'est réalisé,\ens3 est réalisé ou l'un des deux autres événements n'est pas réalisé, au moins un de ces 3 événements n'est pas réalisé}

\matrix{name_question=Quelle est l'écriture ensembliste de l'événement \(F\) suivant&nbsp;
Bonne réponse, l'événement \(F\) est représenté par l'ensemble
Quel est l'événement complémentaire
Bonne réponse, l'événement complémentaire \(F^c\) est
Quelle est l'écriture ensembliste de l'événement complémentaire
}

\text{label=Ensemble,Evénement}
