
\text{poss1=centre,bord}
\text{name_shape=cercle,carré}
\text{name_data=diamètre,côté}
\text{t0=\name_shape[\k]}
\text{t1=\name_data[\k]}
\text{ieme=\n=1 ? : \(i\)-ième}
\text{poss2=inférieure ou égale à,strictement supérieure à, comprise entre \d0 et }
\matrix{choixA=la distance du \ieme point au 
 du \t0 est 
 \d mm}
\text{poss=non,oui}

\text{name_rep=n'est pas,est}
\matrix{name_pointbleu=Le point bleu marque la position du point choisi.
Les point bleus marquent la position des points choisis.}
\text{name_point=un point,deux points,points}


\text{comdess=la zone coloriée en vert (bords compris) représente l'ensemble des points du \t0 dont la distance au }

\matrix{name_event=Pour \(i\in \{1,...,\n\}\), on note <b>\(A_i\)</b> l'événement
On note <b>\(A\)</b> l'événement
Pour \(i\in \{1,2\}\), on note <b>\(A_i\)</b> l'événement
}

\text{pts=\n>2 ? \n \name_point[3]:\name_point[\n]}
\text{name_instruction=On a choisi au hasard \pts à l'intérieur du \t0 dessiné en marron,
centré en 0 et dont le \t1 mesure \diam mm.}

\text{name_help1=La distance considérée est la distance euclidienne dans le plan : si \(m_1 = (x_1,y_1)\)
 et \(m_2 = (x_2,y_2)\) sont deux points du plan, la distance entre
 \(m_1\) et \(m_2\) est \(d(m_1,m_2)\) = \(\sqrt{(x_1-x_2)^2+(y_1-y_2)^2}\).}
\text{name_help2=La distance d'un point \(m\) à un ensemble \(E\) est définie comme l'infimum des distances
entre \(m) et un point \(e) de \(E\)}

\text{name_question=L'événement, est-il réalisé&nbsp;}
\text{name_remark=Remarque}

