\title_es{GGG Distancia en Manhattan}

\text{warning=Supongamos que las avenidas de Manhattan forman una grilla cuadrada de modo que el taxi puede cambiar de avenida cada 10 números. Supongamos además que el taxímetro del taxi aumenta en un dólar en cada cruce.}

\text{question1=¿Cuánto costará la carrera si el taxista es honesto}
\text{question2=¿Cuántas veces puede el taxi hacer esta carrera sin tomar la misma ruta (siempre suponiendo que el taxista es honesto)}

\text{pointv=Una persona se encuentra en el número \x1 de la \a1-ésima avenida}
\text{point2=Esta persona desea tomar un taxi para llegar al número \x2 de la \a2-ésima avenida}
\text{name_hint=Con 2 dólares, el taxi podría, por ejemplo, llevar a la persona del número \x1 de la \a1-ésima avenida al número \x1v de la \a1v-ésima avenida.}

\text{name_hint2=<b>Indicación</b>: Un trayecto puede ser codificado utilizando solamente los símbolos 0 y 1 (usted debe determinar cómo); el conjunto de trayectos se puede entonces representar como un subconjunto de \(\{0,1\}^\c\). Basta escribir explícitamente este subconjunto, y luego determinar su cardinal.}

\matrix{label= Costo (en dólares)
Número de trayectos diferentes}

\text{name_good=Respuesta correcta! La carrera costará \c dólares.}
