
\matrix{matcaslang= de la réunion du complémentaire de \(A) dans \(S) et du complémentaire de \(B) dans \(S)
de la différence \(A - B)
de la différence \(B - A)
de la différence symétrique de \(A) et de \(B)
de la réunion de \(A) et de \(B)
de l'intersection de \(A) et de \(B)
du complémentaire de l'intersection de \(A) et de \(B) dans \(S)
du complémentaire de la réunion de \(A) et de \(B) dans \(S)
}

\text{instruction=Soit \(S\) l'ensemble des entiers de 1 à \init multiples de \t.
Soit \(A) le sous-ensemble de \(S\) formé des multiples de \u et \(B)
le sous-ensemble de \(S) formé des multiples de \r.
}
\text{question=Donner explicitement la liste \(C\) des éléments }
\text{warning=Si \(C\) est vide, écrire 0.}
