
\text{name_feed1=Con \reply1 dollari potete andare fino al numero \nr della \a2-esima avenue (se questo indirizzo esiste !).}

\text{name_feed2=Con \reply1 dollari potete arrivare solo al numero \nr della \ar-esima avenue.}

\matrix{name_feed3=2- Risposta corretta! Ci sono \nb tragitti differenti per fare questa corsa.
2- La risposta è sbagliata. Ci sono \nb tragitti differenti per fare questa corsa.}
