#if defined TARGET_ssensplan
\title_it{GGG Cardinalità di un sottoinsieme del piano}
#endif
#if defined TARGET_ssensclassiq
\title_it{GGG Cardinalità di un insieme classico}
#endif
#if defined TARGET_ssensclassiq0
\title_it{GGG Cardinalità di un insieme classico 0}
#endif

\matrix{name_vocab=è un sottoinsieme di
e
Hai dato la risposta corretta
L'insieme \(E\) ha
elemento,elementi
e non
Si può rappresentare \(E\) come l'insieme dei punti a coordinate intere compresi nel
rettangolo,quadrato
applicazioni,applicazioni biunivoche,applicazioni iniettive}

\text{instruction=Qual è la cardinalità dell'insieme \(E\) seguente}
