
\matrix{name_choix=Soit \(\A\) un sous-ensemble d'un ensemble \(E\) et soit \(\B\) un sous-ensemble d'un ensemble \(F\)
Soient \(\A\) et \(\B\) deux sous-ensembles d'un ensemble \(E\)}

\matrix{instruction=Donner l'expression de la fonction indicatrice de l'ensemble
au point
en notant
}

\text{name_help=Par définition, \(1_A\) est alors une fonction à valeurs dans
\(\{0,1\}\) définie sur \(\Omega\) par \(1_{A}(x) = 1 \)
si et seulement si \( x\in A \).}
