\title_es{GGG Conjuntos de múltiplos}

\matrix{matcaslang= de la unión del complemento de \(A) en \(S) y del complemento de \(B) en \(S)
de la diferencia \(A - B)
de la diferencia \(B - A)
de la diferencia simétrica de \(A) y \(B)
de la unión de \(A) y \(B)
de la intersección de \(A) y \(B)
del complemento de la intersección de  \(A) y \(B) en \(S)
del complemento de la unión de \(A) y \(B) en \(S)
}

\text{instruction=Sea \(S\) el conjunto de enteros entre 1 y \init que son múltiplos de \t.
Sea \(A) el subconjunto de \(S\) formado por múltiplos de \u y \(B)
el subconjunto de \(S) formado por múltiplos de \r.
}
\text{question=Entregue explícitamente la lista \(C\) de los elementos }
\text{warning=Si \(C\) es vacío, escribir 0.}
