
\text{instruction=
Sur les \N élèves d'un lycée, \Ang suivent des cours d'anglais,
\All ceux d'allemand, \Esp ceux d'espagnol. Parmi eux,
\ae apprennent au moins l'anglais et l'espagnol, \aa apprennent au moins l'anglais
et l'allemand et \ale apprennent au moins
l'allemand et l'espagnol.
Enfin, \AAlE d'entre eux apprennent les trois langues.
}

\matrix{question=Combien n'apprennent aucune de ces trois langues
Combien d'élèves font uniquement de l'anglais et de l'espagnol}

\matrix{label=Aucune de ces langues
Anglais et espagnol uniquement}
