\title_it{GGG Distanze a Manhattan}

\text{warning=Si suppone che le strade di Manhattan formino una griglia quadrettata in modo tale che il taxi possa
cambiare strada ogni 10 numeri e si suppone che il tassametro del taxi avanzi di un dollaro ad ogni
incrocio.}

\text{question1=Quanto costerà la corsa se il tassista è onesto}
\text{question2=Quante volte il taxi può fare questa corsa senza imboccare lo stesso tragitto (supponendo sempre che il tassista sia onesto)}

\text{pointv=Una persona si trova al numero \x1 della \a1-esima avenue}
\text{point2=Desidera prendere un taxi per recarsi al numero \x2 della \a2-esima avenue}
\text{name_hint=Con 2 dollari, il taxi vi potrebbe portare, per esempio, dal numero \x1 della \a1 -esima avenue al numero \x1v della \a1v -esima avenue.}

\text{name_hint2=<b>Suggerimento</b>: Un tragitto può essere codificato utilizzando unicamente i simboli 0 e 1 (sta a voi dire come); l'insieme dei tragitti è allora rappresentato da un sottoinsieme di \(\{0,1\}^\c\). È sufficiente scrivere esplicitamente questo sottoinsieme per poi determinare la sua cardinalità.}

\matrix{label= Costo (in dollari)
Numero di percorsi differenti}

\text{name_good=Risposta corretta! La corsa costerà \c dollari.}

