\title_es{GGG Función indicatriz}

\matrix{name_choix=Sea \(\A\) un subconjunto de un conjunto \(E\) y sea \(\B\) un subconjunto de un conjunto \(F\)
Sean \(\A\) y \(\B\) dos subconjuntos de un conjunto \(E\)}

\matrix{instruction=Entregue la expresión de la función indicatriz del conjunto
en el punto
escribiendo
}

\text{name_help=Por definición, \(1_A\) es una función de \(\Omega\) en \(\{0,1\}\) definida como: \(1_{A}(x) = 1 \) si y solamente si \( x\in A \). Dicho de otro modo, \(1_{A}(x) = 0\) si y solamente si \( x\in \Omega \setminus A \).}
