\text{name_feed1=Con \reply1 dólares, puede llegar hasta el número \nr de la \a2-ésima avenida (si es que ese número existe !).}

\text{name_feed2=Con \reply1 dólares, puede llegar solamente hasta el número \nr de la \ar-ésima avenida.}

\matrix{name_feed3=2- Respuesta correcta! Hay \nb trayectos diferentes para hacer esta carrera.
2- Su respuesta es incorrecta.  Hay \nb trayectos diferentes para hacer esta carrera.}