\title_es{GGG Eventos y conjuntos}

\text{evnt=al menos uno de esos tres eventos ocurre, el evento \ens1 ocurre, entre los 3 eventos solo el evento \ens1 ocurre, al menos dos de los tres eventos ocurren, los eventos \ens1 y \ens2 ocurren, al menos uno de los dos eventos \(\ens1) y \(\ens2) ocurre,los eventos \(\ens1) y \(\ens2) ocurren pero \(\ens3) no ocurre, los tres eventos ocurren}
\text{evnt2=ninguno de esos 3 eventos ocurre, \ens1 no ocurre, \ens1 no ocurre o un de los otros dos eventos ocurre, a lo más uno de esos eventos ocurre, al menos uno de los dos eventos \ens1 y \ens2 no ocurren, ni \(\ens1) ni \(\ens2) ocurren,\ens3 ocurre o alguno de los otros dos eventos no ocurre, al menos uno de esos 3 eventos no ocurre}

\matrix{name_question=¿Cuál es la escritura como conjunto del siguiente evento \(F\)
Respuesta correcta, el evento \(F\) se representa por el conjunto
Cuál es el evento complementario
Respuesta correcta, el evento complementario \(F^c\) es
Cuál es la escritura como conjunto del evento complementario
}

\text{label=Conjunto,Evento}
