\title_it{GGG Ripartizione degli studenti in opzioni}

\text{instruction=
Su \N studenti di un liceo, \Ang seguono corsi di inglese,
\All quelli di tedesco, \Esp quelli di spagnolo. Tra loro,
\ae studiano almeno l'inglese e lo spagnolo, \aa studiano almeno l'inglese e il tedesco e \ale studiano almeno
il tedesco e lo spagnolo.
Infine, \AAlE tra loro studiano tutte e tre le lingue.
}

\matrix{question=Quanti non studiano nessuna di queste tre lingue
Quanti studenti fanno unicamente inglese e spagnolo}

\matrix{label=Nessuna delle lingue
Unicamente inglese e spagnolo}

