\title_es{GGG Distribución de estudiantes en opciones}

\text{instruction=
De los \N alumnos de un liceo, \Ang siguen los cursos de inglés,
\All siguen los de alemán, \Esp los de español. Entre ellos,
\ae estudian al menos inglés y español, \aa estudian al menos inglés y alemán  y \ale estudian al menos alemán y español.
Finalmente, \AAlE de ellos estudian las tres lenguas.
}

\matrix{question= Cuántos no estudian ninguna de esas tres lenguas
 Cuántos estudiantes estudian solamente inglés y español }

\matrix{label=Ninguna de esas lenguas
Solamente inglés y español}
