
#if defined TARGET_traduction1
\text{name_question=Mettre en correspondance les formulations probabilistes équivalentes.}

#else
\text{instruction=Soit \(A\), \(B\) et \(C\) trois ensembles.}

# if defined TARGET_traduction2
 \text{name_question=La colonne de droite contient les descriptions des éléments
 de quatre ensembles différents. Lesquels&nbsp;}
 \text{name_instruction=Associer l'ensemble correspondant à chaque description.}

# else
 \text{name_question=Faire correspondre les affirmations équivalentes.}

# endif
#endif
