\text{listecas= Une application de \(E) dans \(F) peut être,
Il existe une application \(f) de \(E) dans \(F) qui est,
Une application de \(E) dans \(F) est nécessairement non,
Aucune application de \(E) dans \(F) n'est }
\text{inj=injective}
\text{surj=surjective}
\text{bij=bijective}
\text{aut=autre}


\text{instruction=Soient \(E) et \(F) deux ensembles finis tels que}
\text{warning=La réponse \aut signifie qu'aucune des propositions n'est possible.}
