!set prompt=<span class="bold" style="color:red">/</span>,$name_edge\
	<img src="$module_dir/gifs/o1.gif" alt="o1" />,$name_vertex\
	<img src="$module_dir/gifs/o0.gif" alt="o0" />,$name_orthocentre

!if $status!=wait
  !set prompt=$prompt\
	  <span class="bold" style="color:#00ff00">/</span>,$name_height\
	  <img src="$module_dir/gifs/o3.gif" alt="o3" />,$name_heightf\
	  <img src="$module_dir/gifs/cross.gif" alt="cross" />,$name_yourclick\
	  <img src="$module_dir/gifs/circle.gif" alt="circle" />,$name_truevertex
!endif
