!header
!read Exindex
!if $lang=fr
  Ce module regroupe pour l'instant $exototal exercices de calcul sur la loi d'ohm
  et les connections en série et en parallèle des résistances électriques.
  Chaque exercice correspond à un type de circuit&nbsp;; vous pouvez
  choisir le style des questions à poser sur le circuit, et surtout vous
  pouvez choisir plusieurs types et styles pour que le logiciel
  les mélange aléatoirement.
  <p>
  N'oubliez pas non plus le chronomètre qui, combiné avec une large marge
  d'erreur, est un outil idéal pour s'entrainer au calcul mental.
  </p>
  !goto end
!endif
!if $lang=nl
  Deze module bevat momenteel $exototal oefeningen met over <em>wet van Ohm</em>, serie en parallel schakelingen van weerstanden.<br>
  het vraagtype van de oefening is handmatig configureerbaar of door de software random instelbaar.
  <p>
  Niet te vergeten, de extra moeilijkheidsgraad door toepassing van een tijdlimiet.
  </p>
  !goto end
!endif
This module actually contains $exototal computational exercises on ohm's law
and serial and parallel connections of electric resistors. Each exercise
corresponds to a type of circuit; you can choose the style of questions to
ask for the circuit. It is also possible to choose several types and styles
for the software to make random mixes.
<p>
Don't forget the chronometer which, combined with a large error tolerance, is an
ideal tool for practising with mental computations.
</p>
:end
!read oef/$module_language/intromenu.phtml
!tail
