\title{Question 0305 Problème}
\keywords{pbsolving}
\integer{a=random(1,2,3,4)}
\integer{b=random(1,2)}
\text{voiture=\a>1?voitures:voiture}
\text{moto=\b>1?motos:motos}
\text{enonce= Dans un garage, il y a \a \voiture et \b \moto . Combien comptes-tu de roues &#63; }
\text{enonceb=}
\integer{rep=\a*4+\b*2}
\text{feedback=Une voiture a quatre roues et une moto deux. La réponse est donc \(4\times\a+2\times\b\)}
