\title{Question 0314 Distribution équitable}
\keywords{mental_calculation,division}
\integer{a=random(32,28,16,36)}
\integer{b=4}
\integer{rep=\a/\b}
\text{enonce=On distribue équitablement \a cartes à \b joueurs. <STRONG>Combien de cartes aura chaque joueur </STRONG> &#63; }
\text{enonceb=}
\text{feedback=Il faut faire la division de \a par \b, ou encore trouver le nombre qu'il manque dans : \(\b \times \dots = \a\).}
