\title{Question 0317 Durée}
\keywords{mental_calculation,time,clock}
\integer{hdeb=random(8,9,10,11,14,15,16)}
\integer{mindeb=random(30,40,50)}
\integer{reste1=60-\mindeb}
\integer{hfin=\hdeb+1}
\integer{rep=random(40,50)}
\integer{minfin=(\mindeb+\rep)%60}
\text{enonce=Un cours commence à \hdeb h \mindeb et se termine à \hfin h \minfin.<br><STRONG> Combien de temps dure ce cours &#63;</STRONG><br> }
\text{enonceb= minutes.}
\text{feedback=Il y a déjà \reste1 minutes de \hdeb h \mindeb jusqu'à \hfin h 00, puis \minfin minutes de \hfin h 00 à \hfin h \minfin. }
