\title{Question 0404 Proportionalité}
\keywords{mental_calculation,proportionality}

\integer{a=randint(6,8)}
\integer{b=\a/2*randint(3,5)}
\integer{k=randint(2,2,3)}
\integer{c=\b*\k}
\integer{rep=\a*\k}
\text{enonce= \a feutres coûtent \b &euro;. }
\text{enonceb= feutres coûtent \c &euro;.}
\integer{temp0404=\rep}

\text{feedback=En observant : \(\c=\b \times \k\). Donc \(\a \times \k\) feutres coûtent \c &euro; . }
