\title{Question 0416 Problème}
\keywords{mental_calculation,multiplication,pbsolving}

\integer{a=randint(11,12)}
\integer{b=randint(2,3,4)}
\text{A=slib(lang/fname en,girl,2)}
\text{trucs=randomitem(billes,bracelets,feutres,crayons,pièces)}
\text{prenom1=\A[1]}
\text{prenom2=\A[2]}
\integer{rep=\a*\b}

\text{enonce=\prenom1 a \(\a \) \trucs. \prenom2 a \(\b \) fois plus de \trucs que \prenom1.<br> \prenom2 a  }
\text{enonceb= \trucs.}

\text{feedback= \(\a \times \b= \rep \) }
