\title{Question 0512 Différentes écritures d'une fraction }
\keywords{mental_calculation,decimals,rational_number,number_writing}
\matrix{mtx=5,10
10,20
2,4
3,6
4,10
8,10}
\text{mtx=randomrow(\mtx)}
\integer{a0512=\mtx[1]}
\integer{b0512=\mtx[2]}
\text{enonce=Donne deux écriture différentes de \(\a0512/\b0512 \)}
\text{enonceb= }
\text{feedback=}
%%%%%%% conditions, deux champs de réponse \reponse1 et \reponse2
%%%%%
%%%condition{Bonnes réponses ?}{(\reponse1=\a0512/\b0512) and (\reponse2=\a0512/\b0512) and (\reponse1 notsametext \a0512/\b0512) and (\reponse2 notsametext \a0512/\b0512) and (\reponse1 notsametext \reponse2)}
%%%% voir codage course sur course level 4
