\title{Question 0522 Tiers quarts 1 bis}
%%% de 0421
\keywords{mental_calculation,division,proportionality}
\text{A=4,120,200,240;3,150,60,90}
\text{A=randomrow(\A)}
\text{prop=\A[1]=4?\(\frac{3}{4}\):\(\frac{2}{3}\)}
\integer{a=randomitem(item(2..4,\A))}
\integer{a0=\A[1]=4?3*\a:2*\a}

\integer{rep=\a0/\A[1]}

\text{enonce=Calcule le \prop de \a &euro;.<br>}
\text{enonceb=&euro;}
\text{coef0521=\A[1]=4?3:2}
\text{feedback= \(\coef0521 \times \a \div \A[1]= \rep\) }
