\title{Question 0529 Proportionnalité}
\keywords{mental_calculation,proportionality}
%%% modif MB correction du 250811 suite signalement de bug (en direct)

\integer{a=randint(3,4)}
\integer{k=randint(2,2,3)}
\integer{b=\a/\k*randint(3,5)}

\integer{c=\a*\k}
\integer{rep=\b*\c/\a}
\text{enonce= Quand je monte \a marches, je m'élève de \b cm. Quand je monte de \c marches, je m'élève de }
\text{enonceb= cm..}

\text{feedback=En observant : \(\c=\a \times \k\). Donc je m'élève de \(\b \times \k\) cm. . }
