\title{Question 0719 Tableau de proportionnalité}
\keywords{proportionality}

\text{donnee=shuffle(7,8,9,6)}
\integer{a=\donnee[1]}
\integer{b=\donnee[2]}
\integer{c=\donnee[3]*\a}
\integer{d=\b*\donnee[3]}
\text{rep=\d}
\text{enonce=Complète le tableau de proportionnalité &#58; <table><tr><td>\a</td><td>\b</td></tr><tr><td>\c</td><td>}
\text{enonceb=</td></table>}
\text{feedback=On remarquera que \(\a \times \donnee[3]=\c\). Donc \(\b \times \donnee[3]=\d\)}
