\title{Question 0723 Fraction d'entier}
\keywords{methodical_calculation,fraction,multiplication}
\text{questions=shuffle(4,3,6,7,9)}

\integer{a=\questions[1]}
\integer{b=\questions[2]}
\integer{c=\b*\questions[3]}

\integer{rep=\a/\b*\c}
\text{enonce=\(\frac{\a}{\b} \times \c={}\)}
\text{feedback=On peut remarquer que \(\c= \b \times \questions[3]\) donc \(\frac{\a}{\b} \times \c=\a \times \questions[3]\)}
