\title{Question 0726 Calculs avec parenthèses et priorités}
\keywords{skill_calculate,calculation,priority_rule}
\text{qprod=shuffle(2,3,4,5)}
\integer{a=\qprod[1]}
\integer{b=\qprod[2]}
\integer{c=\qprod[3]}
\integer{d=\qprod[4]}
%%% por feedback
\integer{k1=\c+\d}
\integer{k2=\b*\k1}
\integer{rep=\a+\b*(\c+\d)}
\text{rep=\rep}
\text{enonce=Calcule \(\a+\b \times(\c+\d)\)}
\text{enonceb=}
\text{enoncec=}
\text{feedback=Attention aux priorités.\(\a +\b \times \k1=\a+\k2\)}
