\title{Question 0729 Aire du disque}
\keywords{geometric_vocabulary,circle}
\integer{d=randint(2..5)*2}
\integer{cas=randomitem(1,1,1,2)}
\integer{r=\d/2}
\integer{q=\cas=1?\d:\r}
\text{mot=\cas=1?diamètre:rayon}
\integer{rep=\r*\r}
\text{enonce=L'aire d'un disque de \mot \(\q cm\) est &#58; }
\text{enonceb=&#960; \( cm^2\)}
\text{feedback=Son rayon est donc égal à \(\r cm\). Son aire à \(\r \times \r \) &#960; \( cm^2\)}
