\title{Question 0814 Inverse}
\keywords{mental_calculation,division,number_writing}
\matrix{fractions=3,4;3,5;3,2;6,5;6,7;7,2;7,3;7,4;7,5;7,6}
\text{frace=randomrow(\fractions)}
\integer{a=\frace[1]}
\integer{b=\frace[2]}
\rational{rep=simplify(\b/\a)}
\text{enonce=L'inverse de \(\frac{\a}{\b}\)<br>Réponse &#58; }
\text{enonceb=}
\text{feedback=La bonne réponse était \(\frac{\b}{\a}\) puisque l'inverse d'une fraction \(\frac{a}{b}\) est \(\frac{b}{a}\).}
