\title{Question 0829 Remplacer et calculer}
\keywords{mental_calculation,literal_calculation}
%%%%%%%%%%% question 6 %%%%%%%%%%%
\text{list=shuffle(2,3,5,6)}
\integer{x=\list[1]*random(-1,-1,1)}
\integer{y=\list[2]*random(-1,-1,1)}
\integer{a=\list[3]*(-1)}
\integer{b=\list[4]}
\integer{rep=\a*\x+\b*\y}

\text{enonce=Calcule \(\a x+\b y\) pour <br> \(x= \x\) et \(y=\y\) <br> Réponse &#58; }
\text{enonceb= }
%%%%
\integer{ax=\a*\x}
\integer{by=\b*\y}
\text{feedback=\(\a x=\ax\) et \(\b y=\by \) il reste à faire l'addition. }
