\title{Question 0830 Problème}
\keywords{mental_calculation,pbsolving}

\text{list=shuffle(4,5)}
\text{k=shuffle(2,3,5)}

\integer{n1=\list[1]*\k[2]} %%% nb cahiers
\integer{p1=\list[2]*\k[2]} %%% prix des a1 cahiers%%%
\integer{n2=\list[1]*\k[1]} %%% nb de cahiers question
\real{rep=\p1/\n1*\n2}
\text{enonce=\n1 cahiers identiques coûtent \(\p1\) &euro;.<br><STRONG>Combien coûtent \n2 cahiers &#63;</strong><br> }
\text{enonceb=&euro;.}
\text{feedback=On notera que \list[1] cahiers coûtent \list[2]&euro; et que \(\n2=\list[1] \times \k[1]\).<br> La bonne réponse est donc \(\list[2] \times \k[1]\) &euro; }
