\title{Question 0911 Autour de l'aire d'un carré }
\keywords{mental_calculation,area,squareroot}
\integer{a11=random(10,15,2,5,6)}
\text{rep=sqrt(\a11)}
\text{enonce=L'aire d'un carré est égale à \(\a11\)\(cm^2\). Quelle est la valeur exacte de la longueur du côté du carré ?}
\text{enonceb=\(cm\).}
\text{feedback=Rappel : l'aire d'un carré s'obtient en élevant au carré la longueur des côtés. Il faut donc
prendre la racine carrée de l'aire pour avoir la longueur des côtés. Ici \(\sqrt{\a11}\)}
