\title{Question 0913 Échelle et longueur }
\keywords{mental_calculation,proportionality,length}
\integer{a13=random(20,40)}
\integer{b13=\a13=20?randint(22..29):randint(10..19)}
\real{rep=\b13*\a13/100}
\text{enonce=Jules achète un modèle réduit d'une voiture à l'échelle \(\frac{1}{\a13}\). La longueur du modèle réduit est \(\b13\) \(cm\). Sa longueur réelle est }
\text{enonceb= \( m\).}
\text{feedback=Rappel : l'échelle \(\frac{1}{\a13}\) signifie que les mesures réelles sont les mesures du modèle
  réduit multipliés par \({\a13}\). Attention à faire aussi la conversion \({}1 m =100 cm\).}
