\title{Question 0917 Compléter un tableau de proportionnalité}
\keywords{mental_calculation,proportionality}
%%% a0917 | b0917
%%% rep | c0917
\integer{b0917=random(4,5)}
\if{\b0917=4}{
\integer{c0917=random(2,3)}
\integer{a0917=random(6,7,9,10)}}
\if{\b0917=5}{
\integer{c0917=random(2,3,4)}
\integer{a0917=random(6,7,9,10)}}
\real{rep=\a0917*\c0917/\b0917}
\text{enonce=Complète le tableau de proportionnalité.}
\text{enonce=\enonce<table class="wimsborder"><tr><td>\( \a0917 \)</td><td>\( \b0917 \)</td></tr><tr><td>}
\text{enonceb=</td><td>\( \c0917 \)</td></tr></table>}
</td><td>\( \c0917 \)</td></tr></table>
\text{feedback=Méthode pour trouver la quatrième valeur : \(\a0917 \times \c0917 \div \b0917\)}
