\title{Question 0928 Diviser par une fraction}
\keywords{mental_calculation,division,fraction}\integer{temp0928=randint(7,11,15,13,19)}
\integer{rep=\temp0928}
\text{enonce= \(1 \div \frac{1}{\temp0928} =\) }
\text{enonceb=}
\text{feedback=Rappel : \(1 \div \frac{1}{\temp0928} \) est l'inverse de \(\frac{1}{\temp0928}\). Et l'inverse de \(\frac{a}{b}\) est \(\frac{b}{a}\). Pour \(a\) et \(b\) non nuls évidemment.}
