\title{Question 0930 Proportionnalité}
\keywords{mental_calculation,proportionality}
a*10 abeilles
b*10 = question production
a*b= prod unitaire
\text{k15=shuffle(3,7,5)}
\integer{a15=\k15[1]*10}
\integer{b15=\k15[2]*10}
\integer{c15=\k15[1]*\k15[2]}
\text{rep=100}
\text{enonce=\( \a15 \) abeilles produisent \( \c15 g \) de miel par an. Combien d'abeilles faut-il pour produire \( \b15 g \) de miel par an ?}
\text{enonceb=abeilles}
\text{feedback=}
