\title{Question 1001 Multiplication par un nombre décimal}
\keywords{mental_calculation,decimals,multiplication}
\real{a=randint(2..9)}
\real{b=randint(1..9)/10}
\real{temp01=\a*\b}
\real{rep=\temp01}
\text{enonce=\(\a \times \b =\) }
\text{enonceb=}
\text{feedback=Rappel : multiplier un nombre décimal par 0.1, 0.01 ou 0.001 c'est décaler la virgule de 1, 2 ou 3 chiffres vers gauche. Et ajouter des zéros si besoin.
Ici : \(\a \times \b =\temp01\)}
