\title{Question 1006 Résolution de problème }
\keywords{mental_calculation,pbsolving}
%%%%%%%%%Question 6 %%%%%%%%%%%%%%%%%%%%%%%
\real{a6=randint(6,8,9)}
\real{unite6=random(0.60,0.70,0.80,0.90)}
\integer{c6=\a6=8?2:3}
\real{rep=\c6*\unite6}
\real{b6=\a6*\unite6}
\text{enonce=\(\a6\) croissants coûtent \(\b6\)&euro;. Quel est le prix de \(\c6\) croissants &#63; <br>Réponse : }
\text{enonceb=&euro;}
\text{feedback=Par une division, un croissant coûte \unite6 &euro;.}
