\title{Question 1007 Probabilité }
\keywords{mental_calculation,probability }
%%%%%%%%%Question 7 %%%%%%%%%%%%%%%%%%%%%%%
\text{temp7=random(6,7,9)}
\real{nn7=randint(2..5)}
\real{nb7=\temp7-\nn7}
\text{couleur7=random(blanche,noire)}
\rational{rep=\couleur7 issametext blanche ? \nb7/\temp7:\nn7/\temp7}
\text{enonce=Une urne contient \(\nn7\) boules noires et \(\nb7\) boules blanches. On tire une boule au hasard. Quelle est la probabilité de tirer une boule \couleur7 ? <br>Réponse : }
\text{enonceb=}
\text{feedback=Attention, il y a \(\nn7+\nb7 \) boules dans le sac.}
