\title{Question 1015 Ecriture et fraction décimales}
\keywords{mental_calculation,decimals,fraction}
%%%%%%%%%%%% question 15 %%%%%%%%%%%%%
\integer{a15=randitem(1,2,3)*10+randitem(1,2,3)}
\text{enonce=Ecriture décimale de \(1-\a15/100\) : }
\real{rep=1-\a15/100}
\text{enonceb=<div class="wims_instruction"> Attention : saisir 1.25 pour 1,25</div>}
\text{feedback=On peut tout mettre sur le dénominateur 100 : 
<br>\(1-\frac{\a15}{100}=\frac{100-\a15}{100}\)}
