\title{Question 1017 Calcul d'antécédent fonction affine}
\keywords{mental_calculation,functions,affine_function}
%%%%%%%%%%% question 2 %%%%%%%%%%%
\integer{m2=randitem(2,4,5)}
\integer{p2=randitem(1,2,3,4,5)}
\integer{q2=\m2=5 ? randitem(15,10,20)-\p2 : randitem(8,12,16)-\p2}
\real{rep=-(\p2+\q2)/\m2}
\text{enonce= Déterminer l'antécédent de \q2 par la fonction \(f\) définie par \(f(x)=-\m2 x-\p2\).<br> Réponse : }
\text{enonceb=}
\text{feedback=Il faut résoudre \(f(x)=\q2\), soit \(-\m2 x-\p2=\q2\).}
