\title{Question 1027 Equation carrée}
\keywords{mental_calculation,equations,squareroot}
%%%%%%%%%%% question 12 %%%%%%%%%%%

\integer{a12=randint(2..10)}
\integer{b12=randint(3..9)}
\integer{aa12=\a12^2}
\integer{c12=\a12^2-\b12}

\real{temp12=-\a12}
\real{rep=\temp12}
\text{enonce=Quelle est la solution négative de l'équation \(x^2 - \b12 = \c12\) &#63; <br>Réponse : }
\text{enonceb=}
\text{feedback=Ici, on obtient \(x^2=\aa12\), qui a pour solutions \(\a12\) et \(\temp12\).}
