\title{Question 1029 Rapport de réduction, aire}
\keywords{mental_calculation,proportionality, area}
%%%%%%%%%%% question 14 %%%%%%%%%%%

%%% réponse, rapport aire, aire réduite, aire grande
\text{data14=randomrow(2,4,5,20
2,4,3,12
3,9,4,36
3,9,6,54
5,25,3,75
5,25,4,100
7,49,2,98
10,100,4,400)}

\rational{rep=1/\data14[1]}
\text{enonce=Soit une figure d'aire \(\data14[4] cm^2\). Après une réduction, on obtient une figure d'aire \(\data14[3] cm^2\). <br>Quel est le rapport de réduction &#63; Réponse &#58; }
\text{enonceb=<div class="wims_instruction">Donner la réponse sous forme de fraction ou sous forme décimale exacte.</div>}
\text{feedback=Pour passer de \(\data14[4] cm^2\) à \(\data14[3] cm^2\), l'aire a été divisée par \data14[2].<br>Les longueur ont donc été divisées par \(\sqrt{\data14[2]}=\data14[1]\). <br>Le rapport de réduction est \(1/\data14[1]\).}
