\title{Question 1120 Lecture d'images}
\keywords{mental_calculation,functions,coordinates}
#include "11202122.inc"
\text{solution=linewidth 5
crosshairsize 5
crosshairs red,\x0,\y0,\x1,\y1}
\text{img=draw(250,300
\repere
)}
\text{imgsol=draw(250,300
\repere
\solution
)}
\integer{rep=\y0*\y1}
\text{enonce=\intro <br><img src="\img" alt="représentation graphique"> <br> f(\x0) \({}\times{}\) f(\x1)=}
\text{enonceb=}
\text{feedback=<img src="\imgsol" alt="représentation graphique"><br>f(\x0)=\y0 et f(\x1)=\y1}
