\title{Question 1212 Equation de degré 2}
\keywords{mental_calculation,equations}

\integer{a=randint(2..9)*random(1,-1)}
\text{atxt=\a>0?+\a:\a}
\text{x=random(a,b,t,x,y,m,p)}
\integer{sol=-\a}
\text{rep=0,\sol}
\text{enonce=Solution(s) de \({\x}^2 \atxt \x=0\) <br>Réponse : }
\text{enonceb=<div class="wims_instruction">S'il y a plusieurs solutions, séparer les solutions par une virgule.</div>}
\text{feedback=En factorisant : \({\x}(\x \atxt)=0\) <br> Les solutions sont donc \(0 \) et \(\sol\)}

%%% anstype fset
