\title{Question 1213 Calcul d'image}
\keywords{mental_calculation,functions}
ax^2+b
\real{a=randint(2,2,2,3,3,3,3,4,5)}
\real{b=randint(1,2)*randint(1,2,-1,-2)}
\rational{x=1/\a}
\function{f=-\a*x^2+\b}
\real{rep=evalue(\f,x=\x)}
\text{enonce=\( f(x)=\f \). Calculer \(f(\x)\) <br> Réponse &#58; }
\text{enonceb=}
\text{feedback=On peut simplifier avant de calculer : \(\a \left( \frac{1}{\a} \right)^2=\frac{1}{\a}\)}
