\title{Question 1223 Transformation de formules}
\keywords{literal_calculation,mental_calculation}


%%%% enonce , rep
\matrix{quest=On obtient la densité \(d\) d'un objet en divisant sa masse \(m\) par son volume \(V\).<br> Exprimer \(m\) en fonction de \(d\) et \(V\)<br>\(m={}\).,V*d,d=V/m;
On obtient la densité \(d\) d'un objet en divisant sa masse \(m\) par son volume \(V\).<br> Exprimer \(V\) en fonction de \(d\) et \(m\).<br>\(V={}\),m/d,d=V/m;
On obtient la vitesse \(v\) d'un objet en divisant la distance parcourue \(d\) par le temps de parcours \(t\).<br> Exprimer \(d\) en fonction de \(t\) et \(v\).<br>\(d={}\),t*d,v=d/t;
On obtient la vitesse \(v\) d'un objet en divisant la distance parcourue \(d\) par le temps de parcours \(t\).<br> Exprimer \(t\) en fonction de \(d\) et \(v\).<br>\(t={}\),d/v,v=d/t }
\text{quest=randomrow(\quest)}
\text{rep=\quest[2]}
\text{enonce=\quest[1]}
\text{enonceb=}
\text{feedback=Par définition \(\quest[3]\)}
