\title{Question 1227 Suite récurrente}
\keywords{mental_calculation,sequence,recurrence_relation}

\integer{u0=randint(2,3,10)}
\integer{u1=\u0^2}
\integer{u2=\u1^2}
\integer{rep=\u2}
\text{enonce=Soit la suite \(u\) telle que \(u_0 = \u0\) et pour tout entier naturel \(n\) &#58; \(u_{n+1} = u_n ^2 \). <br> \(u_2={}\) }
\text{enonceb=}
\text{feedback=On a \(u_{1} = \u0 ^2=\u1 \), puis \(u_{2} = \u1 ^2=\u2 \) }
