\title{Question 1228 Limite d'une suite explicite}
\keywords{mental_calculation,limit,sequence,geometric_sequence}

\text{quest=shuffle(2,3,5,6,7,8,9)}
\integer{a=\quest[1]}
\integer{b=\quest[2]}

\text{enonce=\( \lim_{n \to +\infty} \frac{\a^n}{\b^n}\) <br>Réponse &#58;}
\text{enonceb=<div class="wims_instruction">Si besoin, saisir <b>+inf</b> pour \(+\infty\).</div>}
\text{rep=\a<\b?0:+inf}
\text{feedback=\(\frac{\a^n}{\b^n}=\left(\frac{\a}{\b}\right)^n\). }
