\title{Question T1123 Calcul racine carrée}
\keywords{mental_calculation,methodical_calculation,squareroot}
%%%%%%%%%%%%%% Question 20 %%%%%%%%%%%%

\integer{a23=randitem(3,5,6,7,8,10,11,12,13)}
\integer{b23=randint(2..6)}
\integer{b231=\b23^2}
\integer{temp23=\a23-\b23^2}

\text{enonce=\((\sqrt{\a23}-\b23)(\sqrt{\a23}+\b23)=\) }
\text{enonceb=}
\function{rep=\temp23}
\text{feedback=\((\sqrt{\a23}-\b23)(\sqrt{\a23}+\b23)=(\sqrt{\a23})^2-\b23^2=\a23-\b231=\temp23\).}
\integer{size=6}
