\text{enonfor=Une boucle <code>for</code> parcourt une séquence en partant du premier
 élément jusqu'au dernier. On sort de la boucle lorsque le dernier élément de la séquence a été
 lu. L'ensemble des instructions dans le corps de la boucle est donc lu à chaque fois.
 Les instructions dans le corps de la boucle sont indentées.}
\text{exempleran=}
\text{exemplefor=<div style="width:300px;overflow:auto">
<pre>for compteur in range(\rrr):<br>
print(compteur)</pre>
</div>
  renvoie l'affichage suivant grâce à la fonction <code>print</code> qui
  se trouve à l'intérieur de la boucle :
\exfor1}
