\text{enonfor=}
\text{enonran1=La fonction <code>range</code> permet la création d'une séquence de nombres entiers.}

\text{enonran2= Lorsque deux arguments sont utilisés dans la fonction range,
 la séquence créée part de la valeur du premier argument inclus et se termine à la valeur
 du dernier argument <b>exclue</b> en ajoutant 1 à chaque étape.}
\text{exemplefor=}
\text{exempleran=<code>print(list(range(\rrr)))</code> renvoie la liste : [3,4,5,6]}

