\text{enonfor=}
\text{enonran1=La fonction <code>range</code> permet la création d'une
  séquence de nombres entiers.}

\text{enonran2= Lorsqu'un seul argument est utilisé dans la fonction range,
 la séquence créée part de l'élément 0 et se termine à la valeur de l'argument
 <b>exclue</b> en ajoutant 1 à chaque étape.}
\text{exemplefor=}
\text{exempleran=<code>print(list(range(\rrr)))</code> renvoie la liste : [0,1,2]}
