\text{enonfor=}
\text{enonran1=La fonction <code>range</code> permet la création d'une séquence
  de nombres entiers.}

\text{enonran2= Lorsque trois arguments sont utilisés dans la fonction range,
  alors :
<ul><li>le premier est la valeur de <strong>départ incluse</strong>;</li>
<li>le second est la valeur de <strong>fin exclue</strong>;</li>
<li>le troisième se nomme le <strong>pas</strong>: on ajoute cette valeur pour passer
 d'une valeur à la suivante.</li>
</ul>}
\text{exemplefor=}
\text{exempleran=<code>print(list(range(\rrr)))</code> renvoie la liste : [2,5,8,11]}
