#if defined TARGET_convduree1 || defined TARGET_convduree2 || defined TARGET_convduree3 || defined TARGET_convduree4 || defined TARGET_convduree5
\text{name_enonce=Convertir dans le système décimal,
  Convertir dans le système horaire}
#endif
#if defined TARGET_convvit1 || defined TARGET_convvit2 || defined TARGET_convvit3 || defined TARGET_convvit4 || defined TARGET_convvit5
\text{name_question=Convertir,en}
\text{name_youranswer=Votre réponse}
#endif
#if defined TARGET_reconnaitreA1 || defined TARGET_reconnaitreA2
\text{bad=Non,Oui}
\text{enonce=Ce tableau est-il un tableau de proportionnalité&nbsp;}
#endif
#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4
# if defined TARGET_tableau1 || defined TARGET_tableau2
\text{name_enonce=Compléter le tableau de proportionnalité suivant sachant que le coefficient de proportionnalité (pour passer de la première à la deuxième ligne) est}
# endif
# if defined TARGET_tableau3 || defined TARGET_tableau4
\text{name_enonce=Compléter le tableau de proportionnalité suivant}
# endif
#endif
