#if defined TARGET_vitesse1 || defined TARGET_vitesse2 || defined TARGET_vitesse3 || defined TARGET_vitesse4 || defined TARGET_vitesse5
# define TITRE Calcul de vitesse moyenne
#endif
#if defined TARGET_convvit1 || defined TARGET_convvit2 || defined TARGET_convvit3 || defined TARGET_convvit4 || defined TARGET_convvit5
# define TITRE Conversion vitesse
#endif
#if defined TARGET_graphique1 || defined TARGET_graphique2 || defined TARGET_graphique3 || defined TARGET_graphique4 || defined TARGET_graphique5
# define TITRE Lecture de graphique
#endif
#if defined TARGET_pourcentageA2 || defined TARGET_pourcentageA3 || defined TARGET_pourcentageA4 || defined TARGET_pourcentageA5
# define TITRE Utiliser un pourcentage
#endif
#if defined TARGET_pourcentageB1 || defined TARGET_pourcentageB2 || defined TARGET_pourcentageB3 || defined TARGET_pourcentageB4
# define TITRE Calculer un pourcentage
#endif
#if defined TARGET_reconnaitreA1 || defined TARGET_reconnaitreA2
# define TITRE Reconnaître la proportionnalité
#endif
#if defined TARGET_tableau1 || defined TARGET_tableau2 || defined TARGET_tableau3 || defined TARGET_tableau4
# define TITRE Compléter un tableau
#endif
#if defined TARGET_convduree1 || defined TARGET_convduree2 || defined TARGET_convduree3 || defined TARGET_convduree4 || defined TARGET_convduree5
# define TITRE Conversion d'unités de temps
#endif
