!header
!read Exindex
!if $lang=it
  Questo modulo raccoglie $exototal esercizi sull'applicazione
  del Teorema di Talete ai triangoli simili.
  !goto end
!endif
!if $lang=nl
  Deze module bevat $exototal oefeningen over de stelling van Thales
  voor gelijkvormige driehoeken.
  !goto end
!endif
Ce module regroupe pour l'instant $exototal exercices sur le théorème de
Thalès pour les triangles similaires.
:end
!read oef/intromenu.phtml
!tail
