#if defined TARGET_formulas
# define TITRE_fr Formules
#endif
#if defined TARGET_poly
# define TITRE_fr Dérivées polynomiales
#endif
#if defined TARGET_frac1 || defined TARGET_frac2
#define TITRE_fr Fractions
#endif
#if defined TARGET_basic1
# define TITRE_fr Dérivées de base
#endif
#if defined TARGET_multvert1
# define TITRE_fr Multiplication virtuelle I
#endif
#if defined TARGET_growpos
# define TITRE_fr Croissance et signe
#endif
#if defined TARGET_simple1
# define TITRE_fr Dérivées simples I
#endif
#if defined TARGET_compvert1a || defined TARGET_compvert1b
# define TITRE_fr Composition virtuelle
#endif
