<b>Types d'expressions </b>
<table class="wimstable">
<tr>
<td>
!set wims_ref_id=confparm11
!formcheckbox confparm1 list 1 prompt \(z_1 + z_2\)
</td><td>
!set wims_ref_id=confparm12
!formcheckbox confparm1 list 2 prompt \(z_1 + \overline{z_2}\)
</td><td>
!set wims_ref_id=confparm13
!formcheckbox confparm1 list 3 prompt \(\overline{z_1} + \overline{z_2}\)
</td><td>
!set wims_ref_id=confparm14
!formcheckbox confparm1 list 4 prompt \(\overline{z_1 + z_2}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm15
!formcheckbox confparm1 list 5 prompt \(z_1 -z_2\)
</td><td>
!set wims_ref_id=confparm16
!formcheckbox confparm1 list 6 prompt \(z_1 - \overline{z_2}\)
</td><td>
!set wims_ref_id=confparm17
!formcheckbox confparm1 list 7 prompt \(\overline{z_1} - \overline{z_2}\)
</td><td>
!set wims_ref_id=confparm18
!formcheckbox confparm1 list 8 prompt \(\overline{z_1 - z_2}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm19
!formcheckbox confparm1 list 9 prompt \(z_1 \times z_2\)
</td><td>
!set wims_ref_id=confparm110
!formcheckbox confparm1 list 10 prompt \(z_1 \times \overline{z_2}\)
</td><td>
!set wims_ref_id=confparm111
!formcheckbox confparm1 list 11 prompt \(\overline{z_1} \times \overline{z_2}\)
</td><td>
!set wims_ref_id=confparm112
!formcheckbox confparm1 list 12 prompt \(\overline{z_1 \times z_2}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm113
!formcheckbox confparm1 list 13 prompt \(z^2\)
</td><td>
!set wims_ref_id=confparm114
!formcheckbox confparm1 list 14 prompt \(z \times \overline{z}\)
</td><td>
!set wims_ref_id=confparm115
!formcheckbox confparm1 list 15 prompt \(\overline{z}^2\)
</td><td>
!set wims_ref_id=confparm116
!formcheckbox confparm1 list 16 prompt \(\overline{z^2}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm117
!formcheckbox confparm1 list 17 prompt \(\frac{z_1}{z_2}\)
</td><td>
!set wims_ref_id=confparm118
!formcheckbox confparm1 list 18 prompt \(\frac{z_1}{\overline{z_2}}\)
</td><td>
!set wims_ref_id=confparm119
!formcheckbox confparm1 list 19 prompt \(\frac{\overline{z_1}}{\overline{z_2}}\)
</td><td>
!set wims_ref_id=confparm120
!formcheckbox confparm1 list 20 prompt \(\overline{\left(\frac{z_1}{z_2}\right)}\)
</td>
</tr><tr>
<td>
!set wims_ref_id=confparm121
!formcheckbox confparm1 list 21 prompt \(\frac{1}{z}\)
</td><td>
!set wims_ref_id=confparm122
!formcheckbox confparm1 list 22 prompt \(\frac{1}{\overline{z}}\)
</td><td>
!set wims_ref_id=confparm123
!formcheckbox confparm1 list 23 prompt \(\overline{\left(\frac{1}{z}\right)}\)
</td><td>
</td>
</tr>
</table>
<div class="formHelp">
Sélectionnez les types d'expressions à calculer.
</div><br class="spacer">
