!for i=1 to 5
   !let repexo$i=$empty
!next i
!let nbreesscalc=0
<u>Liste des actions:</u>
<table>
!if division isin $algo
 <tr><td>
 !form reply
 <input type=hidden name=status value=2>
 <input type=hidden name=action value=1>
 <input type=submit value=Division> de deux entiers pour simplifier le calcul.
 </form></td></tr>
!endif
!if soustraction isin $algo
 <tr><td>
 !form reply
 <input type=hidden name=status value=2>
 <input type=hidden name=action value=2>
 <input type=submit value=Soustraction> de deux entiers pour simplifier le calcul.
 </form></td></tr>
!endif
<tr><td>
!form reply
<input type=hidden name=status value=2>
<input type=hidden name=action value=3>
<input type=submit value=Conclure> à partir des calculs effectués.
</form></td>
</tr></table>