!header

$module_title est un exercice sur le calcul du PGCD de deux entiers par l'algorithme d'Euclide ou l'algorithme des soustractions successives. Cet exercice demande à l'élève de saisir la suite des opérations à effectuer.

<p><hr> <p>
!default nbreexo=1
!form new
Nombre d'exercices dans la séance :
!formselect paranbreexo from 1 to 10
<br>
Algorithme 
!formselect paralgo list division,soustraction prompt d'Euclide,des soustractions
<br>
!default paraetape=5
Nombre maximum d'étapes : 
!formselect paraetape from 3 to 15
<input type=hidden name=module value=$module> 
<center><input type=submit value="Au travail"></center>
</form>

!read related.phtml pgcd 

!tail
