# Variable initialisation file.
# This file is read by wims for new sessions.

# content of the file: initialisation of the problem.


renewlink=cmd=renew&worksheet=$worksheet&$module_init_parm

!default status=0
wims_module_log=$cmd
noexo=1
exogood=0
noteinter=0

insmath_rawmath=yes
wims_backslash_insmath=yes
listaction=division.phtml,soustraction.phtml,conclure.phtml
meserreur=<p> <b> Erreur: </b> Vous avez envoyé une réponse incomplète ou incompréhensible. Veuillez la corriger. <p>
erreur=$empty
nbreexo=$paranbreexo
!bound nbreexo between 1 and 10 default 1
algo=$paralgo
!bound algo within division,soustraction default division
maxetape=$paraetape
!bound maxetape between 3 and 15 default 5
