#if defined TARGET_oefenoncqua1 || defined TARGET_oefenoncqua2 || defined TARGET_oefenoncqua3 || defined TARGET_oefenoncqua4 || defined TARGET_oefenoncqua5
# define TITRE Énoncé
#endif
#if defined TARGET_oefdemon1 || defined TARGET_oefdemon2 || defined TARGET_oefdemon3 || defined TARGET_oefdemon4 || defined TARGET_oefdemon5
# define TITRE Démonstration
#endif
#if defined TARGET_oefrepqua1 || defined TARGET_oefrepqua2 || defined TARGET_oefrepqua3 || defined TARGET_oefrepqua4 || defined TARGET_oefrepqua5
# define TITRE Reproduire un quadrilatère
#endif
#if defined TARGET_oefquadvoc1 || defined TARGET_oefquadvoc2 || defined TARGET_oefquadvoc3 || defined TARGET_oefquadvoc4 || defined TARGET_oefquadvoc5
# define TITRE Vocabulaire de quadrilatères particuliers
#endif
#if defined TARGET_oefconstcompl1 || defined TARGET_oefconstcompl2 || defined TARGET_oefconstcompl3 || defined TARGET_oefconstcompl4 || defined TARGET_oefconstcompl5
# define TITRE Figures complexes
#endif
#if defined TARGET_oefrecqua1 || defined TARGET_oefrecqua2 || defined TARGET_oefrecqua3 || defined TARGET_oefrecqua4 || defined TARGET_oefrecqua5
# define TITRE Reconnaître un quadrilatère
#endif
#if defined TARGET_oefquadprop1 || defined TARGET_oefquadprop2 || defined TARGET_oefquadprop3 || defined TARGET_oefquadprop4 || defined TARGET_oefquadprop5
# define TITRE Propriétés des quadrilatères
#endif
#if defined TARGET_oefquaddiag1 || defined TARGET_oefquaddiag2 || defined TARGET_oefquaddiag3 || defined TARGET_oefquaddiag4 || defined TARGET_oefquaddiag5
# define TITRE Diagonales d'un quadrilatère
#endif
