#include "lang_title_fr.inc"

#if defined TARGET_oefquaddiag1 || defined TARGET_oefquadprop1 || defined TARGET_oefrecqua1 || defined TARGET_oefconstcompl1 || defined TARGET_oefquadvoc1 || defined TARGET_oefrepqua1 || defined TARGET_oefenoncqua1 || defined TARGET_oefdemon1
# define NUM 1
#endif
#if defined TARGET_oefquaddiag2 || defined TARGET_oefquadprop2 || defined TARGET_oefrecqua2 || defined TARGET_oefconstcompl2 || defined TARGET_oefquadvoc2 || defined TARGET_oefrepqua2 || defined TARGET_oefenoncqua2 || defined TARGET_oefdemon2
# define NUM 2
#endif
#if defined TARGET_oefquaddiag3 || defined TARGET_oefquadprop3 || defined TARGET_oefrecqua3 || defined TARGET_oefconstcompl3 || defined TARGET_oefquadvoc3 || defined TARGET_oefrepqua3 || defined TARGET_oefenoncqua3 || defined TARGET_oefdemon3
# define NUM 3
#endif
#if defined TARGET_oefquaddiag4 || defined TARGET_oefquadprop4 || defined TARGET_oefrecqua4 || defined TARGET_oefconstcompl4 || defined TARGET_oefquadvoc4 || defined TARGET_oefrepqua4 || defined TARGET_oefenoncqua4 || defined TARGET_oefdemon4
# define NUM 4
#endif
#if defined TARGET_oefquaddiag5 || defined TARGET_oefquadprop5 || defined TARGET_oefrecqua5 || defined TARGET_oefconstcompl5 || defined TARGET_oefquadvoc5 || defined TARGET_oefrepqua5 || defined TARGET_oefenoncqua5 || defined TARGET_oefdemon5
# define NUM 5
#endif

\title{TITRE NUM}
