#if defined TARGET_basic
# define TITRE_nl weerstand
#endif
#if defined TARGET_parallel
# define TITRE_nl parallel schakeling
#endif
#if defined TARGET_serial
# define TITRE_nl serie schakeling
#endif
#if defined TARGET_par3
# define TITRE_nl parallel schakeling
#endif
#if defined TARGET_ser3
# define TITRE_nl serie schakeling
#endif
#if defined TARGET_h
# define TITRE_nl type h
#endif
#if defined TARGET_li
# define TITRE_nl type il
#endif
#if defined TARGET_parser
# define TITRE_nl parallel + serieschakeling
#endif
#if defined TARGET_bridge
# define TITRE_nl type H
#endif
