\matrix{name_quest=het voltage van de spanningsbron U
  de spanning over A (volt)
  de stroomsterkte I
  de stroomsterkte door R
  de waarde van R
}
\text{name_degre=graden}

\text{name_pre=Bekijk het stroomschema hiernaast}
\text{name_of=van}
\matrix{name_known=De stroomsterkte
  de stroomsterkte door R is
  de spanning in A is
}

\text{name_whatis=Wat is hierin }
\text{name_attention=ATTENTIE}
\text{name_warning=De fouttolerantie in je antwoord mag }
\text{name_warning2=zijn}
\text{name_feedback=Let op de fouttolerantie!
  Het lijkt erop dat je de fouttolerantie overschreden hebt.}
