#if defined TARGET_basic
# define TITRE_fr Résistance
#endif
#if defined TARGET_parallel
# define TITRE_fr Parallèle
#endif
#if defined TARGET_serial
# define TITRE_fr Série
#endif
#if defined TARGET_par3
# define TITRE_fr Parallèle
#endif
#if defined TARGET_ser3
# define TITRE_fr Série
#endif
#if defined TARGET_h
# define TITRE_fr Type h
#endif
#if defined TARGET_li
# define TITRE_fr Type il
#endif
#if defined TARGET_parser
# define TITRE_fr Parallèle + série
#endif
#if defined TARGET_bridge
# define TITRE_fr Type H
#endif
