\matrix{name_quest=la tension de la source U&nbsp;
  la tension sur le point A&nbsp;
  l'intensité du courant I&nbsp;
  l'intensité du courant passant par R&nbsp;
  la valeur de R&nbsp;
}

\text{name_pre=Dans le schéma ci-contre}
\text{name_of=de}
\matrix{name_known=l'intensité du courant est
  l'intensité du courant passant par R est
  la tension sur le point A est de
}

\text{name_whatis=Quelle est}

\text{name_warning=Vous avez droit à une marge d'erreur de}
\text{name_warning2=dans la réponse}
\text{name_attention=Attention}
\text{name_feedback=Attention à la tolérance d'erreur !
  Votre calcul semble avoir une marge d'erreur trop importante.}
