!header
!read Exindex
<p>Ce module regroupe pour l'instant $exototal activités sur les algorithmes.
Le but de l'ensemble des exercices est de permettre aux élèves d'apréhender les algorithmes
  relatifs au Lycée Général et Technologique.
  Un script python à compléter permet de comprendre l'algorithme. Pour aider les élèves,
  une représentation graphique vient illustrer le fonctionnement du code. Le but est de
  travailler de concert dans des cadres algébriques, graphiques et algorithmiques
  afin de maîtriser la notion abordée.
</p>

!read oef/intromenu.phtml
!tail
