!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes
!default confparm1=ambiance
<strong>Thème pour l'éditeur Python</strong> :
!formradio confparm1 list ambiance,neat,zenburn prompt sombre,clair aéré,sombre aéré
