
!if $abandon!=yes
 好极了! 你成功的构造了这张表.
 !if $laps>$allow
  (但是你超过了一点点规定的时间.)
 !endif
 <p>
 <center><table border=0 cellspacing=2 cellpadding=5 bgcolor=lightgrey>
 !for i=1 to $rows
  <tr>
  !for j=1 to $cols
   <td align=center>&nbsp;&nbsp;&nbsp;$(x$[$j+$cols*($i-1)])&nbsp;&nbsp;&nbsp;</td>
  !next j
  <td align=center><font color=blue>$(rowsum$i)</font></td>
 !next i
 <tr>
 !for j=1 to $cols
  <td align=center><font color=blue>$(colsum$j)</font></td>
 !next j
 <td align=center><small><font color=blue>
 !if $kind=sum
  sum
 !else
  product
 !endif
 </font></small></td>
 </tr></table></center>
!else
 对不起，你已经放弃了.这是问题的一种解答(可能有另外
 的解答).
 <p>
 <center><table border=0 cellspacing=2 cellpadding=5 bgcolor=lightgrey>
 !for i=1 to $rows
  <tr>
  !for j=1 to $cols
   !set t_=!item $j+$cols*($i-1) of $list
   <td align=center>&nbsp;&nbsp;&nbsp;$t_&nbsp;&nbsp;&nbsp;</td>
  !next j
  <td align=center><font color=blue>$(rowsum$i)</font></td>
 !next i
 <tr>
 !for j=1 to $cols
  <td align=center><font color=blue>$(colsum$j)</font></td>
 !next j
 <td align=center><small><font color=blue>
 !if $kind=sum
  sum
 !else
  product
 !endif
 </font></small></td>
 </tr></table></center>
!endif

<p><hr> <p>

你的得分: $module_score/10.

