!header

!pedia 魔方
 是一个有 n 行 n 列的表格, 用
1, 2, ..., n<sup>2</sup>填充这个表格, 使每行和每列的和相等.
<p>
!form new
<input type=hidden name=module value="$module">
!default rows=2
!default cols=3
!default kind=sum
$module_title 是这种原理的一种变化:
你面前的表格有
!formselect rows from 2 to 8
 行和
!formselect cols from 2 to 8
 列, 并且已给出的数在每一行和每一列的边上.
你的目标是用数 1.2....,行数&times;列数去填满这个表格,
使每一行和每一列的
!formselect kind list sum,product prompt 和,乘积
与所给的数相等. 每个数只能用一次.
<p>
允许你用
!default allow=120
!formselect allow list 30,60,90,120,180,240,300,420,600,900,1200,1800\
	prompt 0.5,1,1.5,2,3,4,5,7,10,15,20,30
 分钟解决每个问题.
<p>
<center><input type=submit value="游戏开始"></center>
</form>

!tail
