!read language lang/names
!header
<span class="module_title">$module_title</span> $name_intro

!form new
<input type="hidden" name="module" value="$module" />

<fieldset class="property_fields">
<legend>$wims_name_setup</legend>
!set level=1
<div class="field">
<strong>$name_introlevel</strong>
 !formradio level list 1,2,3
</div>
<div class="field">
<strong>
$name_introcount:
</strong>
!set shoots=3
!formselect shoots from 1 to 8
</div>
</fieldset>
<div class="wims_instruction">
$name_introscore
</div>
<div class="wimscenter">
<input type="submit" value="OK" />
</div>

!formend

!set keyw=!getdef keywords in INDEX
!read related.phtml $keyw

!tail

