!!!! This file can contain contents which go after the exercise list in the intro.
!!Model for some configuration parameters. Uncomment if necessary
!!and replace no by yes in the following line.
!set introhook_exists=yes
!set introhook_tableless=yes

<div class="field box">
<b>Pour les exercices 01, 03 et 05, le PPCM dans la solution est obtenu</b>
<ul class="wims_nopuce">
<li>
!set wims_ref_id=confparm1_1
!formradio confparm1 list 1 prompt en dressant la liste des multiples (par défaut)
</li>
<li>
!set wims_ref_id=confparm1_2
!formradio confparm1 list 2 prompt par décomposition en facteurs premiers
</li>
</ul>
</div>
