!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices de niveaux très variés sur le système solaire.
<div class="wims_instruction">Dans les exercices "Les planètes et leur distance au Soleil", les distances sont exprimées :
<ul><li>en km et sans puissances de 10 : version (1)</li>
<li> en km, avec ou sans puissances de 10 : version (2)</li>
<li> en UA ou en km, avec ou sans puissances de 10 : version (3)</li></ul></div>

!read oef/intromenu.phtml
!tail
