#if defined TARGET_signeQuot3 || defined TARGET_ineqQuotient2 || defined TARGET_inequationEvidente
# if defined TARGET_signeQuot3
\author{Véronique, Royer; Chantal, Causse}
# endif
# if defined TARGET_ineqQuotient2
\author{Véronique, Royer; Josep, Lopez}
# endif
# if defined TARGET_inequationEvidente
\author{Véronique, Royer ; Régine, Mangeard}
# endif
#else
\author{Véronique, Royer}
#endif
\email{royer.veronique@orange.fr}

