#if defined TARGET_Graphique
# define TITRE Lecture graphique
#endif
#if defined TARGET_assTabExp
# define TITRE Associer tableau et expressions
#endif
#if defined TARGET_ineqParticuliere
# define TITRE Inéquation particulière
#endif
#if defined TARGET_ineqQuotient
# define TITRE Inéquation avec quotient
#endif
#if defined TARGET_ineqQuotient2
# define TITRE Inéquation avec quotient (2)
#endif
#if defined TARGET_ineqQuotient3
# define TITRE Inéquation avec quotient (3)
#endif
#if defined TARGET_inequationEvidente
# define TITRE Inéquation évidente
#endif
#if defined TARGET_methodologie
# define TITRE Vérifier un tableau de signes (1)
#endif
#if defined TARGET_methodologie2
# define TITRE Vérifier un tableau de signes (2)
#endif
#if defined TARGET_signeBinome
# define TITRE Signe d'un binôme \(ax+b)
#endif
#if defined TARGET_signeEvident
# define TITRE Expression de signe évident
#endif
#if defined TARGET_signeGraphique
# define TITRE Lecture graphique
#endif
#if defined TARGET_signeProdQuot2
# define TITRE Signe d'un produit ou quotient
#endif
#if defined TARGET_signeProdQuotient
# define TITRE Signe d'une fonction produit ou quotient
#endif
#if defined TARGET_signeQuot3
# define TITRE Signe d'une expression a + u(x)/v(x)
#endif
