!header
!readproc Exindex
!readproc Vindex
!if $lang=fr
  Ce module regroupe pour l'instant $exototal exercices configurables pour la
  mémorisation du tableau périodique des éléments.
  !goto end
!endif
!if $lang=fr
  Deze module bevat $exototal configureerbare oefeningen, om te leren werken met het <em>periodiek
  systeem deze elementen</em>.
  !goto end
!endif
This module actually gathers $exototal configurable exercises for
memorising the periodic table of elements.
:end
!read oef/intromenu.phtml
!tail
