#if defined TARGET_trigo3
# define TITRE Trigonométrie, résolution d'équations I
#endif

#if defined TARGET_trigo2
# define TITRE Trigonométrie, résolution d'équations II
#endif

#if defined TARGET_trigo1
# define TITRE Trigonométrie I
#endif

#if defined TARGET_trigo
# define TITRE Trigonométrie, calculs
#endif

#if defined TARGET_planim
# define TITRE Planimètre et trigonométrie
#endif

#if defined TARGET_phase
# define TITRE Calcul de la phase
#endif

#if defined TARGET_compose
# define TITRE Composer
#endif

#if defined TARGET_decomp1
# define TITRE Décomposer I
#endif

#if defined TARGET_decomp2
# define TITRE Décomposer II
#endif
