#if defined TARGET_2term0
# define TITRE_nl 2 termen
#endif
#if defined TARGET_3term0
# define TITRE_nl 3 termen
#endif
#if defined TARGET_3term1
# define TITRE_nl 3 termen met haakjes
#endif
#if defined TARGET_4term0
# define TITRE_nl 4 termen
#endif
#if defined TARGET_4term1
# define TITRE_nl 4 termen met 1 set haakjes
#endif
#if defined TARGET_4term2
# define TITRE_nl termen met 2 sets haakjes
#endif
#if defined TARGET_5term0
# define TITRE_nl 5 termen
#endif
#if defined TARGET_5term1
# define TITRE_nl 5 termen met 1 set haakjes
#endif
#if defined TARGET_5term2
# define TITRE_nl 5 termen met 2 sets haakjes
#endif
#if defined TARGET_5term3
# define TITRE_nl 5 termen met 3 sets haakjes
#endif
#if defined TARGET_6term0
# define TITRE_nl 6 termen
#endif
#if defined TARGET_6term1
# define TITRE_nl 6 termen met 1 set haakjes
#endif
#if defined TARGET_7term0
# define TITRE_nl 7 termen
#endif
#if defined TARGET_8term0
# define TITRE_nl 8 termen
#endif
