#if defined TARGET_2term0
# define TITRE_it 2 termini
#endif
#if defined TARGET_3term0
# define TITRE_it 3 termini
#endif
#if defined TARGET_3term1
# define TITRE_it 3 termini con parentesi
#endif
#if defined TARGET_4term0
# define TITRE_it 4 termini
#endif
#if defined TARGET_4term1
# define TITRE_it 4 termini 1 coppia
#endif
#if defined TARGET_4term2
# define TITRE_it 4 termini 2 coppie
#endif
#if defined TARGET_5term0
# define TITRE_it 5 termini
#endif
#if defined TARGET_5term1
# define TITRE_it 5 termini 1 coppia
#endif
#if defined TARGET_5term2
# define TITRE_it 5 termini 2 coppie
#endif
#if defined TARGET_5term3
# define TITRE_it 5 termini 3 coppie
#endif
#if defined TARGET_6term0
# define TITRE_it 6 termini
#endif
#if defined TARGET_6term1
# define TITRE_it 6 termini 1 coppia
#endif
#if defined TARGET_7term0
# define TITRE_it 7 termini
#endif
#if defined TARGET_8term0
# define TITRE_it 8 termini
#endif
