#if defined TARGET_2term0
# define TITRE 2 terms
#endif
#if defined TARGET_3term0
# define TITRE 3 terms
#endif
#if defined TARGET_3term1
# define TITRE 3 terms with parentheses
#endif
#if defined TARGET_4term0
# define TITRE 4 terms
#endif
#if defined TARGET_4term1
# define TITRE 4 terms 1 pair
#endif
#if defined TARGET_4term2
# define TITRE 4 terms 2 pairs
#endif
#if defined TARGET_5term0
# define TITRE 5 terms
#endif
#if defined TARGET_5term1
# define TITRE 5 terms 1 pair
#endif
#if defined TARGET_5term2
# define TITRE 5 terms 2 pairs
#endif
#if defined TARGET_5term3
# define TITRE 5 terms 3 pairs
#endif
#if defined TARGET_6term0
# define TITRE 6 terms
#endif
#if defined TARGET_6term1
# define TITRE 6 terms 1 pair
#endif
#if defined TARGET_7term0
# define TITRE 7 terms
#endif
#if defined TARGET_8term0
# define TITRE 8 terms
#endif
