#if defined TARGET_oefcompltabl1 || defined TARGET_oefcompltabl2 || defined TARGET_oefcompltabl3 || defined TARGET_oefcompltabl4 || defined TARGET_oefcompltabl5
# define TITRE Tableau à compléter
#endif
#if defined TARGET_oeffairetabl1 || defined TARGET_oeffairetabl2 || defined TARGET_oeffairetabl3 || defined TARGET_oeffairetabl4 || defined TARGET_oeffairetabl5
# define TITRE Faire un tableau
#endif
#if defined TARGET_oefgraph1 || defined TARGET_oefgraph2 || defined TARGET_oefgraph3 || defined TARGET_oefgraph4 || defined TARGET_oefgraph5
# define TITRE Lire un graphique
#endif
#if defined TARGET_oeflirefrasimpl1 || defined TARGET_oeflirefrasimpl2 || defined TARGET_oeflirefrasimpl3 || defined TARGET_oeflirefrasimpl4 || defined TARGET_oeflirefrasimpl5
# define TITRE Lecture d'une fraction
#endif
#if defined TARGET_oefliretabl1 || defined TARGET_oefliretabl2 || defined TARGET_oefliretabl3 || defined TARGET_oefliretabl4 || defined TARGET_oefliretabl5
# define TITRE Lire un tableau à double entrée
#endif
#if defined TARGET_oefutigraph1 || defined TARGET_oefutigraph2 || defined TARGET_oefutigraph3 || defined TARGET_oefutigraph4 || defined TARGET_oefutigraph5
# define TITRE Utiliser un graphique
#endif
#if defined TARGET_oefutitableau1 || defined TARGET_oefutitableau2 || defined TARGET_oefutitableau3 || defined TARGET_oefutitableau4 || defined TARGET_oefutitableau5
# define TITRE Utiliser un tableau
#endif
#if defined TARGET_oefutitabl1 || defined TARGET_oefutitabl2 || defined TARGET_oefutitabl3 || defined TARGET_oefutitabl4 || defined TARGET_oefutitabl5
# define TITRE Utiliser un tableau à double entrée
#endif
#if defined TARGET_oefplacfrasimpl1 || defined TARGET_oefplacfrasimpl2 || defined TARGET_oefplacfrasimpl3 || defined TARGET_oefplacfrasimpl4 || defined TARGET_oefplacfrasimpl5
# define TITRE Placer une fraction
#endif
#if defined TARGET_oefliretableau1 || defined TARGET_oefliretableau2 || defined TARGET_oefliretableau3 || defined TARGET_oefliretableau4 || defined TARGET_oefliretableau5
# define TITRE Lire un tableau
#endif
\title{TITRE NUM}
