!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices de calcul sur la loi d'ohm
et les connections en série et en parallèle des résistances électriques.
Chaque exercice correspond à un type de circuit&nbsp;; vous pouvez
choisir le style des questions à poser sur le circuit, et surtout vous
pouvez choisir plusieurs types et styles pour que le logiciel
les mélange aléatoirement.
<p>
N'oubliez pas non plus le chronomètre qui, combiné avec une large marge
d'erreur, est un outil idéal pour s'entrainer au calcul mental.
</p>

!read oef/$module_language/intromenu.phtml
!tail
