!! do not change this file...
!! change $authordir/sh/help.phtml and kick "changehelp.sh" script

!if $myvar4 != $empty
    !! "$myvar4" is "$session" and is attached to URL-string (to see if the mathview is wanted: see "phtml/myheader.phtml"
    !! !href target=wims_mhelp session=$stupid_fix&+module=$module&+cmd=help&+myvar4=$session
    !if $mathview>0 and $inputs=1
	!! inputs=1 meaning : just 1 inputfield , no multiplechoice or other answering_type
	<div align="center">
	    !! this looks a bit nonsense to have two passive mathviewers
	    !! but the JAVA is not really suitable for slowcomputers
	    !! and with the other one, WIMS has to pay the price...
	    !if $mathview=2
		!read $phtmldir/showmath.java.phtml
	    !else
		!read $phtmldir/showmath.wims.phtml
	    !endif
        </div>
    !endif
    
!else

    <hr>
	!! read specific help file for this module...
	!read lang/help.$taal.phtml
    <hr>
	!! AND  read general help file...I know this is a waste of cpu-recources
	!read $remarkdir/help.$taal.phtml

!endif
!! changed: Fri Jun 29 09:08:16 UTC 2007
