#if defined TARGET_chelle2
\text{name_enonce=Een ladder E steunt tegen een muur,
  is, lang}
\matrix{name_question=Hoe groot is de hoek,rond je getal af
  Hoe lang is de ladder,arfronden op een decimeter}
\text{name_answer=Hoek,in graden,Lengte van de ladder}
#endif
#if defined TARGET_Sinus || defined TARGET_Tangente || defined TARGET_Cosinus
\text{name_enonce=is een rechthoekige driehoek in,  is,
De hoek, Bereken hiermee de lengte ,in centimeters, à l'unité près}
\text{name_answer= De lengte, in}
#endif
#if defined TARGET_Hauteurdunarbr
\text{name_enonce=De hoek, is,De hoek,
  Het mannetje staat, van de boom. Bereken hiermee de hoogte (in meter) van de boom.}
\text{name_answer=De hoogte van de boom is}
#endif
