Quelques aides:<p align="left">
<ul>
    <li>le terme <b>ln<em>(x)</em></b> signifie le logarithme naturel</br>
    c'est-à-dire de nombre de base <em>e</em><br /></small><br />
    <b>ln<em>(x)</em></b> =  <em><sup>e</sup><b></em>log<em>(x)</em></b>
    <li>
	Dans le cas de plusieurs asymptotes:<br />
	<textarea cols="30" rows="2" readonly="readonly">the line x=4 and x=-5</textarea>
    <li>
	Avec encore plus d'asymptotes:<br />
	<textarea cols="30" rows="2" readonly="readonly">the line x=4 and x=-5 and y=-10</textarea>
    <li>
	Toutes les asymptotes des fonctions périodiques:<br />
	<b>k</b> $m_in $m_ZZ<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2*k*pi/3</textarea>
	<br />or<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2kpi/3</textarea>
	<br />or<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2*s*pi/3
avec s élément de Z
</textarea>
    <li>
	S'il vous est demandé une <b>solution précise</b>:
	<textarea cols="30" rows="2" readonly="readonly">the line x=sqrt(2)</textarea>
	<br /> il y aura une pénalité si vous écrivez "the line x=1.4142"
    <li>
	D'autres petites aides:
	<ul>
	    <li>La puissance <em>x</em> <sup><small>3</small></sup> doit être écrite :
	    <textarea cols="30" rows="2" readonly="readonly">x^3
or
x**3</textarea>
	    <li>La racine carrée &radic;<em>x</em> doit être écrite :
	    <textarea cols="30" rows="2" readonly="readonly">sqrt(x)
ou
x^(1/2)
ou
x**0.5
	    </textarea>
	    <li>Si vous n'êtes pas sûr, utilisez <b>toujours</b> des parenthèses<br />
	<textarea cols="30" rows="2" readonly="readonly">
x^3/2 = x^(3/2)
x/5*7 = (x/5)*7 = 7*(x/5) = 7x/5
et non x/35 !!!!
	</textarea>
	    <li>Pour les nombres réels, utilisez un <b>point</b> et <span style="color:red">non une virgule</span>.
	</ul>

</ul>
    
</p>
