Een paar kleine opmerkingen:
<ul>
    <li>de term <b>ln<em>(x)</em></b> betekend de natuurlijke logaritme</br>
    dus met het grondgetal <em>e</em><br /></small><br />
    <b>ln<em>(x)</em></b> =  <em><sup>e</sup><b></em>log<em>(x)</em></b>
    <li>
	Bij meerdere asymptoten invullen<br />
	<textarea cols="30" rows="2" readonly="readonly">de lijn x=4 en x=-5</textarea>
    <li>
	Bij nog meer asymptoten invullen<br />
	<textarea cols="30" rows="2" readonly="readonly">de lijn x=4 en x=-5 en y=-10</textarea>
    <li>
	Bij alle asymptoten van periodieke functies invullen<br />
	<b>k</b> $m_in $m_ZZ<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2*k*pi/3
</textarea>
	<br />of<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2kpi/3
</textarea>
<br />of<br />
<textarea cols="30" rows="1" readonly="readonly">
x=2*s*pi/3
met s element Z
</textarea>
    <li>
	Bij een <b>exacte oplossing</b> graag invullen
	<textarea cols="30" rows="2" readonly="readonly">de lijn x=sqrt(2)</textarea>
	<br /> in dit geval krijg je strafpunten als je "de lijn x=1.4142" invult
    <li>
	Wat algemene dingen
	<ul>
	    <li>De macht <em>x</em> <sup><small>3</small></sup> wordt genoteerd als:
	    <textarea cols="30" rows="2" readonly="readonly">x^3
of
x**3</textarea>
	    <li>De wortel &radic;<em>x</em> wordt genoteerd als:
	    <textarea cols="30" rows="2" readonly="readonly">sqrt(x)
of
x^(1/2)
of
x**0.5
	    </textarea>
	    <li>Weet je de 'voorrangsregels' niet meer, of ben je niet zeker,<br />
	    gebruik dan <b>altijd</b> haakjes.<br />
	<textarea cols="30" rows="2" readonly="readonly">
x^3/2 = x^(3/2)
x/5*7 = (x/5)*7 = 7*(x/5) = 7x/5
en dus geen x/35 !!!!
	</textarea>
	    <li>Gebruik een <b>decimale punt</b> en dus <span style="color:red">geen komma</span> bij gebroken getallen
	</ul>

</ul>
    
