A few tips:<p align="left">
<ul>
    <li>the term <b>ln<em>(x)</em></b> means the natural logaritm</br>
    so with basenumber <em>e</em><br /></small><br />
    <b>ln<em>(x)</em></b> =  <em><sup>e</sup><b></em>log<em>(x)</em></b>
    <li>
	When filling in multiple asymptotes:<br />
	<textarea cols="30" rows="2" readonly="readonly">the line x=4 and x=-5</textarea>
    <li>
	With even more asymptotes:<br />
	<textarea cols="30" rows="2" readonly="readonly">the line x=4 and x=-5 and y=-10</textarea>
    <li>
	All asymptotes of periodic functions:<br />
	<b>k</b> $m_in $m_ZZ<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2*k*pi/3</textarea>
	<br />or<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2kpi/3</textarea>
	<br />or<br />
	<textarea cols="30" rows="1" readonly="readonly">
x=2*s*pi/3
with s element of Z
</textarea>
    <li>
	If asked for an <b>precise solution</b>:
	<textarea cols="30" rows="2" readonly="readonly">the line x=sqrt(2)</textarea>
	<br /> you will get a penalty if you fill in "the line x=1.4142"
    <li>
	More small stuff:
	<ul>
	    <li>The power <em>x</em> <sup><small>3</small></sup> should be written like:
	    <textarea cols="30" rows="2" readonly="readonly">x^3
or
x**3</textarea>
	    <li>The square root &radic;<em>x</em> is written like:
	    <textarea cols="30" rows="2" readonly="readonly">sqrt(x)
or
x^(1/2)
or
x**0.5
	    </textarea>
	    <li>If you are not sure, <b>always</b> use round parenthesis<br />
	<textarea cols="30" rows="2" readonly="readonly">
x^3/2 = x^(3/2)
x/5*7 = (x/5)*7 = 7*(x/5) = 7x/5
and not x/35 !!!!
	</textarea>
	    <li>For broken numbers, use a <b>point</b> and <span style="color:red">no comma</span>.
	</ul>

</ul>
    
</p>
