一些提示:<p align="left">
<ul>
    <li><b>ln<em>(x)</em></b> 指自然对数</br>
    其底数是 <em>e</em><br /></small><br />
    <b>ln<em>(x)</em></b> =  <em><sup>e</sup><b></em>log<em>(x)</em></b>
    <li>
    填充多重渐近线:<br />
    <textarea cols="30" rows="2" readonly="readonly">x=4 and x=-5</textarea>
    <li>
    更多渐近线:<br />
    <textarea cols="30" rows="2" readonly="readonly">x=4 and x=-5 and y=-10</textarea>
    <li>
    周期函数的所有渐近线:<br />
    <b>k</b> $m_in $m_ZZ<br />
    <textarea cols="30" rows="1" readonly="readonly">
x=2*k*pi/3</textarea>
    <br />或<br />
    <textarea cols="30" rows="1" readonly="readonly">
x=2kpi/3</textarea>
    <br />或<br />
    <textarea cols="30" rows="1" readonly="readonly">
x=2*s*pi/3
其中 s 是 Z 的元素
</textarea>
    <li>
    如果要求<b>精确解</b>:
    <textarea cols="30" rows="2" readonly="readonly">x=sqrt(2)</textarea>
    <br /> 如果你填了 "x=1.4142", 将会扣分.
    <li>
    其它:
    <ul>
        <li>方幂 <em>x</em> <sup><small>3</small></sup> 应该写成:
        <textarea cols="30" rows="2" readonly="readonly">x^3
或
x**3</textarea>
        <li>平方根 &radic;<em>x</em> 写成:
        <textarea cols="30" rows="2" readonly="readonly">sqrt(x)
或
x^(1/2)
或
x**0.5
        </textarea>
        <li>如果你没有把握, <b>总是</b>使用括号<br />
    <textarea cols="30" rows="2" readonly="readonly">
x^3/2 = x^(3/2)
x/5*7 = (x/5)*7 = 7*(x/5) = 7x/5
而不是 x/35 !!!!
    </textarea>
        <li>对于分数, 使用 <b>小数点</b> 而 <span style="color:red">不是逗号</span>.
    </ul>

</ul>
    
</p>
